"""PE Intelligence Brain — senior-partner judgment layer over a packet.

This package does not modify any existing calculation. It consumes a
``DealAnalysisPacket`` and emits a ``PartnerReview`` with three kinds
of findings:

1. **Reasonableness bands** — sanity-check IRRs, EBITDA margins, and
   lever realizability against size / payer-mix peer ranges. Flags when
   a model output drifts outside the band a senior partner would
   accept without a very good story.
2. **Heuristics** — codified PE rules of thumb. Medicare-heavy payer
   mix caps exit multiples. Denial improvements above 200 bps/yr are
   aggressive. Capitation plays need different math than FFS. These
   rules live in :mod:`heuristics` and are mirrored in
   ``docs/PE_HEURISTICS.md`` as a living doc.
3. **Narrative commentary** — short paragraphs in the voice a senior
   partner would write in an IC memo: direct, opinionated, with the
   bear case explicit.

The entry point is :func:`partner_review.partner_review`. It is called
from OUTSIDE ``packet_builder`` — the packet stays pure; judgment is
applied downstream. This preserves the "one packet, rendered by many
consumers" invariant.
"""
from __future__ import annotations

from .reasonableness import (
    Band,
    BandCheck,
    check_ebitda_margin,
    check_irr,
    check_lever_realizability,
    check_multiple_ceiling,
    run_reasonableness_checks,
)
from .heuristics import (
    Heuristic,
    HeuristicContext,
    HeuristicHit,
    all_heuristics,
    run_heuristics,
)
from .narrative import (
    NarrativeBlock,
    compose_narrative,
)
from .partner_review import (
    PartnerReview,
    partner_review,
    partner_review_from_context,
)
from .red_flags import (
    RED_FLAG_FIELDS,
    run_all_rules,
    run_red_flags,
)
from .valuation_checks import (
    ValuationInputs,
    check_equity_concentration,
    check_ev_walk,
    check_interest_coverage,
    check_terminal_growth,
    check_terminal_value_share,
    check_wacc,
    run_valuation_checks,
)
from .ic_memo import (
    render_all as render_ic_memo_all,
    render_html as render_ic_memo_html,
    render_markdown as render_ic_memo_markdown,
    render_text as render_ic_memo_text,
)
from .bear_book import (
    BEAR_PATTERNS,
    BearPatternHit,
    scan_bear_book,
)
from .exit_readiness import (
    ExitReadinessInputs,
    ExitReadinessReport,
    ReadinessFinding,
    score_exit_readiness,
)
from .regime_classifier import (
    ALL_REGIMES,
    RegimeInputs,
    RegimeResult,
    classify_regime,
    rank_all_regimes,
)
from .market_structure import (
    HHI_HIGHLY_CONCENTRATED,
    HHI_UNCONCENTRATED,
    MarketStructureResult,
    analyze_market_structure,
    compute_cr,
    compute_cr3,
    compute_cr5,
    compute_hhi,
    is_consolidation_play,
)
from .stress_test import (
    ScenarioOutcome,
    StressGridResult,
    run_stress_grid,
)
from .operating_posture import (
    ALL_POSTURES,
    PostureInputs,
    PostureResult,
    classify_posture,
    posture_from_stress_and_heuristics,
)
from .white_space import (
    WhiteSpaceInputs,
    WhiteSpaceOpportunity,
    WhiteSpaceResult,
    detect_white_space,
    top_opportunities,
)
from .investability_scorer import (
    InvestabilityInputs,
    InvestabilityResult,
    inputs_from_review as investability_inputs_from_review,
    score_investability,
)
from .extra_heuristics import (
    run_all_plus_extras,
    run_extra_heuristics,
)
from .extra_bands import (
    check_bed_occupancy,
    check_capex_intensity,
    check_case_mix_index,
    check_length_of_stay,
    check_rvu_per_provider,
    run_extra_bands,
)
from .extra_archetypes import (
    ExtraArchetypeContext,
    ExtraArchetypeHit,
    classify_extra_archetypes,
)
from .extra_red_flags import (
    EXTRA_RED_FLAG_FIELDS,
    run_extra_red_flags,
)
from .scenario_narrative import (
    ScenarioNarrativeResult,
    render_scenario_markdown,
    render_scenario_narrative,
)
from .deal_comparison import (
    ComparisonFinding,
    ComparisonResult,
    compare_reviews,
    render_comparison_markdown,
)
from .priority_scoring import (
    PriorityInputs,
    PriorityScore,
    rank_deal_portfolio,
    render_priority_list_markdown,
    score_deal_priority,
)
from .board_memo import (
    render_board_memo,
    render_board_memo_markdown,
)
from .contract_diligence import (
    ContractPortfolio,
    ContractRisk,
    PayerContract,
    analyze_contract_portfolio,
    render_contract_diligence_markdown,
)
from .service_line_analysis import (
    ServiceLine,
    ServiceLinePortfolio,
    ServiceLineRisk,
    analyze_service_lines,
    render_service_lines_markdown,
)
from .quality_metrics import (
    QualityImpact,
    QualityInputs,
    QualityProfile,
    analyze_quality_profile,
    render_quality_profile_markdown,
)
from .labor_cost_analytics import (
    LaborFinding,
    LaborInputs,
    LaborProfile,
    analyze_labor_profile,
    render_labor_profile_markdown,
)
from .analyst_cheatsheet import (
    build_cheatsheet,
    render_cheatsheet_markdown,
)
from .reimbursement_bands import (
    check_gross_to_net,
    check_payer_rate_growth,
    check_site_neutral_parity,
    run_reimbursement_bands,
)
from .ebitda_quality import (
    AddbackFinding,
    EBITDAAddback,
    EBITDAQualityReport,
    assess_ebitda_quality,
    render_ebitda_quality_markdown,
)
from .covenant_monitor import (
    CovenantDefinition,
    CovenantObservation,
    CovenantReport,
    CovenantStatus,
    evaluate_covenant,
    monitor_covenants,
    render_covenant_report_markdown,
)
from .liquidity_monitor import (
    CashWeek,
    LiquidityReport,
    project_cash_detail,
    project_cash_runway,
    render_liquidity_markdown,
)
from .ma_pipeline import (
    ADDON_STAGES,
    AddOnTarget,
    PipelineSummary,
    analyze_pipeline,
    render_pipeline_markdown,
)
from .esg_screen import (
    ESGFlag,
    ESGInputs,
    ESGReport,
    render_esg_markdown,
    screen_esg,
)
from .deepdive_heuristics import (
    DEEP_DIVE_FIELDS,
    run_deepdive_heuristics,
)
from .master_bundle import (
    build_master_bundle,
    bundle_index,
)
from .tax_structuring import (
    TaxFinding,
    TaxStructureInputs,
    TaxStructureReport,
    analyze_tax_structure,
    render_tax_structure_markdown,
)
from .insurance_diligence import (
    InsuranceGap,
    InsuranceInputs,
    InsuranceReport,
    render_insurance_report_markdown,
    screen_insurance,
)
from .memo_formats import (
    render_all_formats as render_all_memo_formats,
    render_deck_bullets,
    render_email as render_memo_email,
    render_one_pager,
    render_pdf_ready,
    render_slack as render_memo_slack,
)
from .narrative_styles import (
    ALL_NARRATIVE_STYLES,
    compose_analyst_brief,
    compose_bullish_view,
    compose_founder_voice,
    compose_skeptic_view,
    compose_styled_narrative,
    compose_three_sentence,
)
from .thesis_templates import (
    TEMPLATES as THESIS_TEMPLATES,
    ThesisTemplate,
    fill_template,
    get_template,
    list_templates,
    render_template_markdown,
)
from .auditor_view import (
    AuditEntry,
    AuditTrail,
    build_audit_trail,
    filter_entries,
    summarize_trail,
)
from .capital_plan import (
    CapexLine,
    CapitalPlan,
    CapitalPlanFinding,
    has_plan_mismatch,
    validate_capital_plan,
)
from .recon import (
    ReconFinding,
    has_mismatch,
    reconcile,
)
from .kpi_alert_rules import (
    DEFAULT_RULES as KPI_DEFAULT_RULES,
    KPIAlert,
    KPIObservation,
    KPIRule,
    evaluate_all as evaluate_kpi_alerts,
    evaluate_kpi,
    summarize_alerts as summarize_kpi_alerts,
)
from .partner_discussion import (
    DiscussionItem,
    build_discussion,
    render_discussion_markdown,
)
from .cohort_tracker import (
    CohortDeal,
    CohortRanking,
    CohortStats,
    bottom_decile,
    cohort_stats,
    compare_to_cohort,
    group_by_vintage,
    rank_within_cohort,
    top_decile,
)
from .icr_gate import (
    ICReadinessResult,
    evaluate_ic_readiness,
)
from .commercial_due_diligence import (
    CDDFinding,
    CDDInputs,
    competitive_position,
    growth_plausibility,
    market_share_check,
    market_size_sanity,
    run_cdd_checks,
)
from .operational_kpi_cascade import (
    KPICascadeInputs,
    KPIMovement,
    build_cascade,
    top_levers,
    total_ebitda_impact,
)
from .pipeline_tracker import (
    FunnelStats,
    PIPELINE_STAGES,
    PipelineDeal,
    funnel_stats,
    source_mix,
    stale_deals,
)
from .lp_side_letter_flags import (
    ConformanceFinding,
    SideLetterRule,
    SideLetterSet,
    check_side_letters,
    has_breach,
)
from .cash_conversion import (
    CashConversionInputs,
    ConversionAssessment,
    assess_conversion,
    cash_conversion_ratio,
    expected_conversion_by_subsector,
)
from .regulatory_stress import (
    RegulatoryStressInputs,
    StressShock,
    run_regulatory_stresses,
    shock_340b_reduction,
    shock_cms_ipps_cut,
    shock_medicaid_freeze,
    shock_site_neutral,
    shock_snf_vbp_accel,
    summarize_regulatory_exposure,
)
from .fund_model import (
    Fund,
    FundDeal,
    FundProjection,
    commentary_for_quartile,
    fund_vintage_percentile,
    project_fund,
)
from .working_capital import (
    WCRelease,
    WCSummary,
    WorkingCapitalInputs,
    ap_days_to_cash,
    ar_days_to_cash,
    inventory_days_to_cash,
    total_wc_release,
)
from .synergy_modeler import (
    SynergyInputs,
    SynergyResult,
    apply_partner_haircut,
    realization_schedule,
    size_cost_synergies,
    size_procurement_synergies,
    size_rcm_synergies,
    size_revenue_synergies,
    size_synergies,
)
from .thesis_validator import (
    ConsistencyFinding,
    ThesisStatement,
    validate_thesis,
)
from .management_assessment import (
    DimensionScore,
    ManagementInputs,
    ManagementScore,
    score_management,
)
from .debt_sizing import (
    covenant_stress_passes,
    leverage_headroom,
    max_interest_rate_to_break,
    prudent_leverage,
)
from .deal_comparables import (
    COMPS,
    Comparable,
    filter_comps,
    multiple_stats,
    position_in_comps,
)
from .exit_math import (
    WaterfallResult,
    exit_waterfall,
    moic_cagr_to_irr,
    project_exit_ev,
    required_exit_ebitda_for_moic,
)
from .value_creation_tracker import (
    LeverActual,
    LeverPlan,
    LeverStatus,
    evaluate_lever,
    evaluate_plan,
    rollup_status,
)
from .workbench_integration import (
    archetype_summary,
    build_api_payload,
    build_workbench_bundle,
)
from .comparative_analytics import (
    DealSnapshot,
    DealVsBookFinding,
    concentration_warnings,
    correlation_risk,
    deal_rank_vs_peers,
    deal_vs_book,
    portfolio_concentration,
)
from .diligence_tracker import (
    DiligenceBoard,
    DiligenceItem,
    WORKSTREAMS,
    board_from_review,
    render_board_markdown,
)
from .ic_voting import (
    ROLE_WEIGHTS,
    Vote,
    VoteOutcome,
    Voter,
    aggregate_vote,
    auto_vote_from_review,
    default_committee,
)
from .hundred_day_plan import (
    HundredDayPlan,
    PlanAction,
    generate_plan,
    render_plan_markdown,
)
from .lp_pitch import (
    render_lp_all,
    render_lp_html,
    render_lp_markdown,
)
from .regulatory_watch import (
    REGISTRY as REGULATORY_REGISTRY,
    RegulatoryItem,
    for_deal as regulatory_items_for_deal,
    list_items as list_regulatory_items,
    summarize_for_partner as regulatory_summary_for_partner,
)
from .payer_math import (
    PayerScenario,
    ProjectionInputs,
    ScenarioResult,
    VBCInputs,
    VBCProjection,
    YearProjection,
    blended_rate_growth,
    compare_payer_scenarios,
    project_ebitda_from_revenue,
    project_revenue,
    standard_scenarios,
    vbc_revenue_projection,
)
from .deal_archetype import (
    ArchetypeContext,
    ArchetypeHit,
    classify_archetypes,
    primary_archetype,
)
from .sector_benchmarks import (
    GapFinding,
    SectorBenchmark,
    compare_to_peers,
    get_benchmark,
    list_metrics_for_subsector,
    list_subsectors,
)
from .scenario_stress import (
    StressInputs,
    StressResult,
    run_partner_stresses,
    stress_labor_shock,
    stress_lever_slip,
    stress_multiple_compression,
    stress_rate_down,
    stress_volume_down,
    worst_case_summary,
)

__all__ = [
    "Band",
    "BandCheck",
    "Heuristic",
    "HeuristicContext",
    "HeuristicHit",
    "NarrativeBlock",
    "PartnerReview",
    "all_heuristics",
    "check_ebitda_margin",
    "check_irr",
    "check_lever_realizability",
    "check_multiple_ceiling",
    "compose_narrative",
    "partner_review",
    "partner_review_from_context",
    "RED_FLAG_FIELDS",
    "ValuationInputs",
    "check_equity_concentration",
    "check_ev_walk",
    "check_interest_coverage",
    "check_terminal_growth",
    "check_terminal_value_share",
    "check_wacc",
    "run_all_rules",
    "run_heuristics",
    "run_reasonableness_checks",
    "run_red_flags",
    "run_valuation_checks",
    "StressInputs",
    "StressResult",
    "run_partner_stresses",
    "stress_labor_shock",
    "stress_lever_slip",
    "stress_multiple_compression",
    "stress_rate_down",
    "stress_volume_down",
    "worst_case_summary",
    "render_ic_memo_all",
    "render_ic_memo_html",
    "render_ic_memo_markdown",
    "render_ic_memo_text",
    "GapFinding",
    "SectorBenchmark",
    "compare_to_peers",
    "get_benchmark",
    "list_metrics_for_subsector",
    "list_subsectors",
    "ArchetypeContext",
    "ArchetypeHit",
    "classify_archetypes",
    "primary_archetype",
    "BEAR_PATTERNS",
    "BearPatternHit",
    "scan_bear_book",
    "ExitReadinessInputs",
    "ExitReadinessReport",
    "ReadinessFinding",
    "score_exit_readiness",
    "PayerScenario",
    "ProjectionInputs",
    "ScenarioResult",
    "VBCInputs",
    "VBCProjection",
    "YearProjection",
    "blended_rate_growth",
    "compare_payer_scenarios",
    "project_ebitda_from_revenue",
    "project_revenue",
    "standard_scenarios",
    "vbc_revenue_projection",
    "REGULATORY_REGISTRY",
    "RegulatoryItem",
    "regulatory_items_for_deal",
    "list_regulatory_items",
    "regulatory_summary_for_partner",
    "render_lp_all",
    "render_lp_html",
    "render_lp_markdown",
    "HundredDayPlan",
    "PlanAction",
    "generate_plan",
    "render_plan_markdown",
    "ROLE_WEIGHTS",
    "Vote",
    "VoteOutcome",
    "Voter",
    "aggregate_vote",
    "auto_vote_from_review",
    "default_committee",
    "DiligenceBoard",
    "DiligenceItem",
    "WORKSTREAMS",
    "board_from_review",
    "render_board_markdown",
    "DealSnapshot",
    "DealVsBookFinding",
    "concentration_warnings",
    "correlation_risk",
    "deal_rank_vs_peers",
    "deal_vs_book",
    "portfolio_concentration",
    "archetype_summary",
    "build_api_payload",
    "build_workbench_bundle",
    "LeverActual",
    "LeverPlan",
    "LeverStatus",
    "evaluate_lever",
    "evaluate_plan",
    "rollup_status",
    "WaterfallResult",
    "exit_waterfall",
    "moic_cagr_to_irr",
    "project_exit_ev",
    "required_exit_ebitda_for_moic",
    "COMPS",
    "Comparable",
    "filter_comps",
    "multiple_stats",
    "position_in_comps",
    "covenant_stress_passes",
    "leverage_headroom",
    "max_interest_rate_to_break",
    "prudent_leverage",
    "DimensionScore",
    "ManagementInputs",
    "ManagementScore",
    "score_management",
    "ConsistencyFinding",
    "ThesisStatement",
    "validate_thesis",
    "SynergyInputs",
    "SynergyResult",
    "apply_partner_haircut",
    "realization_schedule",
    "size_cost_synergies",
    "size_procurement_synergies",
    "size_rcm_synergies",
    "size_revenue_synergies",
    "size_synergies",
    "WCRelease",
    "WCSummary",
    "WorkingCapitalInputs",
    "ap_days_to_cash",
    "ar_days_to_cash",
    "inventory_days_to_cash",
    "total_wc_release",
    "Fund",
    "FundDeal",
    "FundProjection",
    "commentary_for_quartile",
    "fund_vintage_percentile",
    "project_fund",
    "RegulatoryStressInputs",
    "StressShock",
    "run_regulatory_stresses",
    "shock_340b_reduction",
    "shock_cms_ipps_cut",
    "shock_medicaid_freeze",
    "shock_site_neutral",
    "shock_snf_vbp_accel",
    "summarize_regulatory_exposure",
    "CashConversionInputs",
    "ConversionAssessment",
    "assess_conversion",
    "cash_conversion_ratio",
    "expected_conversion_by_subsector",
    "SideLetterRule",
    "SideLetterSet",
    "check_side_letters",
    "has_breach",
    "FunnelStats",
    "PIPELINE_STAGES",
    "PipelineDeal",
    "funnel_stats",
    "source_mix",
    "stale_deals",
    "KPICascadeInputs",
    "KPIMovement",
    "build_cascade",
    "top_levers",
    "total_ebitda_impact",
    "CDDFinding",
    "CDDInputs",
    "competitive_position",
    "growth_plausibility",
    "market_share_check",
    "market_size_sanity",
    "run_cdd_checks",
    "ICReadinessResult",
    "evaluate_ic_readiness",
    "CohortDeal",
    "CohortRanking",
    "CohortStats",
    "bottom_decile",
    "cohort_stats",
    "compare_to_cohort",
    "group_by_vintage",
    "rank_within_cohort",
    "top_decile",
    "DiscussionItem",
    "build_discussion",
    "render_discussion_markdown",
    "KPI_DEFAULT_RULES",
    "KPIAlert",
    "KPIObservation",
    "KPIRule",
    "evaluate_kpi",
    "evaluate_kpi_alerts",
    "summarize_kpi_alerts",
    "ReconFinding",
    "has_mismatch",
    "reconcile",
    "CapexLine",
    "CapitalPlan",
    "CapitalPlanFinding",
    "has_plan_mismatch",
    "validate_capital_plan",
    "AuditEntry",
    "AuditTrail",
    "build_audit_trail",
    "filter_entries",
    "summarize_trail",
    "THESIS_TEMPLATES",
    "ThesisTemplate",
    "fill_template",
    "get_template",
    "list_templates",
    "render_template_markdown",
    "ALL_REGIMES",
    "RegimeInputs",
    "RegimeResult",
    "classify_regime",
    "rank_all_regimes",
    "HHI_HIGHLY_CONCENTRATED",
    "HHI_UNCONCENTRATED",
    "MarketStructureResult",
    "analyze_market_structure",
    "compute_cr",
    "compute_cr3",
    "compute_cr5",
    "compute_hhi",
    "is_consolidation_play",
    "ScenarioOutcome",
    "StressGridResult",
    "run_stress_grid",
    "ALL_POSTURES",
    "PostureInputs",
    "PostureResult",
    "classify_posture",
    "posture_from_stress_and_heuristics",
    "WhiteSpaceInputs",
    "WhiteSpaceOpportunity",
    "WhiteSpaceResult",
    "detect_white_space",
    "top_opportunities",
    "InvestabilityInputs",
    "InvestabilityResult",
    "investability_inputs_from_review",
    "score_investability",
    "run_all_plus_extras",
    "run_extra_heuristics",
    "check_bed_occupancy",
    "check_capex_intensity",
    "check_case_mix_index",
    "check_length_of_stay",
    "check_rvu_per_provider",
    "run_extra_bands",
    "ALL_NARRATIVE_STYLES",
    "compose_analyst_brief",
    "compose_bullish_view",
    "compose_founder_voice",
    "compose_skeptic_view",
    "compose_styled_narrative",
    "compose_three_sentence",
    "render_all_memo_formats",
    "render_deck_bullets",
    "render_memo_email",
    "render_one_pager",
    "render_pdf_ready",
    "render_memo_slack",
    "ExtraArchetypeContext",
    "ExtraArchetypeHit",
    "classify_extra_archetypes",
    "EXTRA_RED_FLAG_FIELDS",
    "run_extra_red_flags",
    "ScenarioNarrativeResult",
    "render_scenario_markdown",
    "render_scenario_narrative",
    "ComparisonFinding",
    "ComparisonResult",
    "compare_reviews",
    "render_comparison_markdown",
    "PriorityInputs",
    "PriorityScore",
    "rank_deal_portfolio",
    "render_priority_list_markdown",
    "score_deal_priority",
    "render_board_memo",
    "render_board_memo_markdown",
    "ContractPortfolio",
    "ContractRisk",
    "PayerContract",
    "analyze_contract_portfolio",
    "render_contract_diligence_markdown",
    "ServiceLine",
    "ServiceLinePortfolio",
    "ServiceLineRisk",
    "analyze_service_lines",
    "render_service_lines_markdown",
    "QualityImpact",
    "QualityInputs",
    "QualityProfile",
    "analyze_quality_profile",
    "render_quality_profile_markdown",
    "LaborFinding",
    "LaborInputs",
    "LaborProfile",
    "analyze_labor_profile",
    "render_labor_profile_markdown",
    "build_cheatsheet",
    "render_cheatsheet_markdown",
    "check_gross_to_net",
    "check_payer_rate_growth",
    "check_site_neutral_parity",
    "run_reimbursement_bands",
    "AddbackFinding",
    "EBITDAAddback",
    "EBITDAQualityReport",
    "assess_ebitda_quality",
    "render_ebitda_quality_markdown",
    "CovenantDefinition",
    "CovenantObservation",
    "CovenantReport",
    "CovenantStatus",
    "evaluate_covenant",
    "monitor_covenants",
    "render_covenant_report_markdown",
    "CashWeek",
    "LiquidityReport",
    "project_cash_detail",
    "project_cash_runway",
    "render_liquidity_markdown",
    "ADDON_STAGES",
    "AddOnTarget",
    "PipelineSummary",
    "analyze_pipeline",
    "render_pipeline_markdown",
    "ESGFlag",
    "ESGInputs",
    "ESGReport",
    "render_esg_markdown",
    "screen_esg",
    "DEEP_DIVE_FIELDS",
    "run_deepdive_heuristics",
    "build_master_bundle",
    "bundle_index",
    "TaxFinding",
    "TaxStructureInputs",
    "TaxStructureReport",
    "analyze_tax_structure",
    "render_tax_structure_markdown",
    "InsuranceGap",
    "InsuranceInputs",
    "InsuranceReport",
    "render_insurance_report_markdown",
    "screen_insurance",
]
