"""PE Intelligence Brain — senior-partner judgment layer over a packet.

This package does not modify any existing calculation. It consumes a
``DealAnalysisPacket`` and emits a ``PartnerReview`` with three kinds
of findings:

1. **Reasonableness bands** — sanity-check IRRs, EBITDA margins, and
   lever realizability against size / payer-mix peer ranges. Flags when
   a model output drifts outside the band a senior partner would
   accept without a very good story.
2. **Heuristics** — codified PE rules of thumb. Medicare-heavy payer
   mix caps exit multiples. Denial improvements above 200 bps/yr are
   aggressive. Capitation plays need different math than FFS. These
   rules live in :mod:`heuristics` and are mirrored in
   ``docs/PE_HEURISTICS.md`` as a living doc.
3. **Narrative commentary** — short paragraphs in the voice a senior
   partner would write in an IC memo: direct, opinionated, with the
   bear case explicit.

The entry point is :func:`partner_review.partner_review`. It is called
from OUTSIDE ``packet_builder`` — the packet stays pure; judgment is
applied downstream. This preserves the "one packet, rendered by many
consumers" invariant.
"""
from __future__ import annotations

from .reasonableness import (
    Band,
    BandCheck,
    check_ebitda_margin,
    check_irr,
    check_lever_realizability,
    check_multiple_ceiling,
    run_reasonableness_checks,
)
from .heuristics import (
    Heuristic,
    HeuristicContext,
    HeuristicHit,
    all_heuristics,
    run_heuristics,
)
from .narrative import (
    NarrativeBlock,
    compose_narrative,
)
from .partner_review import (
    PartnerReview,
    partner_review,
    partner_review_from_context,
)
from .red_flags import (
    RED_FLAG_FIELDS,
    run_all_rules,
    run_red_flags,
)
from .valuation_checks import (
    ValuationInputs,
    check_equity_concentration,
    check_ev_walk,
    check_interest_coverage,
    check_terminal_growth,
    check_terminal_value_share,
    check_wacc,
    run_valuation_checks,
)
from .ic_memo import (
    render_all as render_ic_memo_all,
    render_html as render_ic_memo_html,
    render_markdown as render_ic_memo_markdown,
    render_text as render_ic_memo_text,
)
from .bear_book import (
    BEAR_PATTERNS,
    BearPatternHit,
    scan_bear_book,
)
from .exit_readiness import (
    ExitReadinessInputs,
    ExitReadinessReport,
    ReadinessFinding,
    score_exit_readiness,
)
from .regime_classifier import (
    ALL_REGIMES,
    RegimeInputs,
    RegimeResult,
    classify_regime,
    rank_all_regimes,
)
from .market_structure import (
    HHI_HIGHLY_CONCENTRATED,
    HHI_UNCONCENTRATED,
    MarketStructureResult,
    analyze_market_structure,
    compute_cr,
    compute_cr3,
    compute_cr5,
    compute_hhi,
    is_consolidation_play,
)
from .stress_test import (
    ScenarioOutcome,
    StressGridResult,
    run_stress_grid,
)
from .operating_posture import (
    ALL_POSTURES,
    PostureInputs,
    PostureResult,
    classify_posture,
    posture_from_stress_and_heuristics,
)
from .white_space import (
    WhiteSpaceInputs,
    WhiteSpaceOpportunity,
    WhiteSpaceResult,
    detect_white_space,
    top_opportunities,
)
from .investability_scorer import (
    InvestabilityInputs,
    InvestabilityResult,
    inputs_from_review as investability_inputs_from_review,
    score_investability,
)
from .extra_heuristics import (
    run_all_plus_extras,
    run_extra_heuristics,
)
from .extra_bands import (
    check_bed_occupancy,
    check_capex_intensity,
    check_case_mix_index,
    check_length_of_stay,
    check_rvu_per_provider,
    run_extra_bands,
)
from .extra_archetypes import (
    ExtraArchetypeContext,
    ExtraArchetypeHit,
    classify_extra_archetypes,
)
from .extra_red_flags import (
    EXTRA_RED_FLAG_FIELDS,
    run_extra_red_flags,
)
from .scenario_narrative import (
    ScenarioNarrativeResult,
    render_scenario_markdown,
    render_scenario_narrative,
)
from .deal_comparison import (
    ComparisonFinding,
    ComparisonResult,
    compare_reviews,
    render_comparison_markdown,
)
from .priority_scoring import (
    PriorityInputs,
    PriorityScore,
    rank_deal_portfolio,
    render_priority_list_markdown,
    score_deal_priority,
)
from .board_memo import (
    render_board_memo,
    render_board_memo_markdown,
)
from .contract_diligence import (
    ContractPortfolio,
    ContractRisk,
    PayerContract,
    analyze_contract_portfolio,
    render_contract_diligence_markdown,
)
from .service_line_analysis import (
    ServiceLine,
    ServiceLinePortfolio,
    ServiceLineRisk,
    analyze_service_lines,
    render_service_lines_markdown,
)
from .quality_metrics import (
    QualityImpact,
    QualityInputs,
    QualityProfile,
    analyze_quality_profile,
    render_quality_profile_markdown,
)
from .labor_cost_analytics import (
    LaborFinding,
    LaborInputs,
    LaborProfile,
    analyze_labor_profile,
    render_labor_profile_markdown,
)
from .analyst_cheatsheet import (
    build_cheatsheet,
    render_cheatsheet_markdown,
)
from .reimbursement_bands import (
    check_gross_to_net,
    check_payer_rate_growth,
    check_site_neutral_parity,
    run_reimbursement_bands,
)
from .ebitda_quality import (
    AddbackFinding,
    EBITDAAddback,
    EBITDAQualityReport,
    assess_ebitda_quality,
    render_ebitda_quality_markdown,
)
from .covenant_monitor import (
    CovenantDefinition,
    CovenantObservation,
    CovenantReport,
    CovenantStatus,
    evaluate_covenant,
    monitor_covenants,
    render_covenant_report_markdown,
)
from .liquidity_monitor import (
    CashWeek,
    LiquidityReport,
    project_cash_detail,
    project_cash_runway,
    render_liquidity_markdown,
)
from .ma_pipeline import (
    ADDON_STAGES,
    AddOnTarget,
    PipelineSummary,
    analyze_pipeline,
    render_pipeline_markdown,
)
from .esg_screen import (
    ESGFlag,
    ESGInputs,
    ESGReport,
    render_esg_markdown,
    screen_esg,
)
from .deepdive_heuristics import (
    DEEP_DIVE_FIELDS,
    run_deepdive_heuristics,
)
from .master_bundle import (
    build_master_bundle,
    bundle_index,
)
from .tax_structuring import (
    TaxFinding,
    TaxStructureInputs,
    TaxStructureReport,
    analyze_tax_structure,
    render_tax_structure_markdown,
)
from .insurance_diligence import (
    InsuranceGap,
    InsuranceInputs,
    InsuranceReport,
    render_insurance_report_markdown,
    screen_insurance,
)
from .portfolio_dashboard import (
    PortfolioDashboard,
    build_portfolio_dashboard,
    render_portfolio_dashboard_markdown,
)
from .integration_readiness import (
    IntegrationFinding,
    IntegrationInputs,
    IntegrationReport,
    assess_integration_readiness,
    render_integration_report_markdown,
)
from .management_comp import (
    CompFinding,
    CompPlanInputs,
    CompReport,
    render_comp_plan_markdown,
    review_comp_plan,
)
from .red_team_review import (
    RedTeamAttack,
    RedTeamReport,
    build_red_team_report,
    render_red_team_markdown,
)
from .data_room_tracker import (
    CANONICAL_CHECKLIST,
    DataRoomItem,
    DataRoomReport,
    analyze_data_room,
    render_data_room_markdown,
)
from .workstream_tracker import (
    Workstream,
    WorkstreamMilestone,
    WorkstreamReport,
    aggregate_workstreams,
    render_workstream_report_markdown,
)
from .negotiation_position import (
    NegotiationPosition,
    derive_negotiation_position,
    render_negotiation_markdown,
)
from .loi_drafter import (
    LOIDraft,
    compose_loi,
    render_loi_markdown,
)
from .post_mortem import (
    PostMortemFinding,
    PostMortemInputs,
    PostMortemReport,
    render_post_mortem_markdown,
    run_post_mortem,
)
from .cycle_timing import (
    ALL_PHASES,
    CycleInputs,
    CycleResult,
    classify_cycle,
    render_cycle_markdown,
)
from .exit_planning import (
    ExitMilestone,
    ExitPlan,
    ExitPlanInputs,
    build_exit_plan,
    render_exit_plan_markdown,
)
from .benchmark_bands import (
    check_interest_to_ebitda,
    check_nwc_days,
    check_outpatient_share,
    check_same_store_sales_growth,
    check_sga_intensity,
    run_benchmark_bands,
)
from .payer_mix_risk import (
    PayerMixRiskInputs,
    PayerMixRiskReport,
    PayerRisk,
    analyze_payer_mix_risk,
    render_payer_mix_risk_markdown,
)
from .peer_discovery import (
    PeerDeal,
    PeerMatch,
    find_peers,
    render_peers_markdown,
)
from .reimbursement_cliff import (
    CliffImpact,
    CliffReport,
    ReimbursementCliff,
    default_cliff_library,
    evaluate_cliffs,
    render_cliff_report_markdown,
)
from .scenario_comparison import (
    ScenarioComparison,
    ScenarioInputs,
    ScenarioOutcome as ScenarioComparisonOutcome,
    compare_scenarios,
    render_scenario_comparison_markdown,
)
from .vintage_return_curve import (
    VintageCurve,
    VintageInputs,
    YearPoint as VintageYearPoint,
    project_vintage_curve,
    render_vintage_curve_markdown,
)
from .coinvest_sizing import (
    CoInvestInputs,
    CoInvestSizing,
    render_coinvest_markdown,
    size_coinvest,
)
from .sensitivity_grid import (
    SUPPORTED_VARIABLES as SENSITIVITY_VARIABLES,
    SensitivityBase,
    SensitivityGrid,
    SensitivityPoint,
    render_sensitivity_markdown,
    render_tornado_markdown,
    run_sensitivity,
    tornado,
)
from .capital_structure_tradeoff import (
    CapStructureInputs,
    CapStructurePoint,
    CapStructureResult,
    render_cap_structure_markdown,
    sweep_cap_structure,
)
from .refinancing_window import (
    DebtTranche,
    RefiContext,
    RefiPlan,
    RefiRecommendation,
    plan_refinance,
    render_refi_plan_markdown,
)
from .dividend_recap_analyzer import (
    RecapAssessment,
    RecapInputs,
    analyze_recap,
    render_recap_markdown,
)
from .carve_out_risks import (
    CarveOutAssessment,
    CarveOutInputs,
    CarveOutRisk,
    assess_carve_out,
    render_carve_out_markdown,
)
from .secondary_sale_valuation import (
    SecondarySaleAssessment,
    SecondarySaleInputs,
    render_secondary_markdown,
    value_secondary_sale,
)
from .lbo_stress_scenarios import (
    LBO_STRESS_LIBRARY,
    LBOStressInputs,
    LBOStressReport,
    LBOStressResult,
    LBOStressScenario,
    render_lbo_stress_markdown,
    run_all_lbo_stresses,
    run_scenario as run_lbo_stress_scenario,
)
from .physician_compensation_benchmark import (
    MGMA_BENCHMARKS,
    PhysicianCompFinding,
    PhysicianCompInputs,
    PhysicianCompReport,
    benchmark_physician_comp,
    render_physician_comp_markdown,
)
from .ebitda_normalization import (
    CATEGORY_ORDER as EBITDA_CATEGORY_ORDER,
    EBITDAItem,
    HAIRCUTS as EBITDA_HAIRCUTS,
    NormalizationResult,
    normalize_ebitda,
    render_normalization_markdown,
)
from .staffing_pipeline_analyzer import (
    DEFAULT_RAMP_MONTHS,
    DEFAULT_TTF_DAYS,
    RoleProjection,
    RoleState,
    StaffingFinding,
    StaffingReport,
    analyze_staffing,
    render_staffing_markdown,
)
from .ma_integration_scoreboard import (
    DIMENSION_WEIGHTS as INTEGRATION_DIMENSION_WEIGHTS,
    BoltOnInputs,
    BoltOnScore,
    IntegrationScoreboard,
    build_scoreboard,
    render_scoreboard_markdown,
    score_bolton,
)
from .customer_concentration_drilldown import (
    ConcentrationAnalysis,
    CustomerRecord,
    CustomerRisk,
    analyze_customers,
    render_concentration_markdown,
)
from .geographic_reach_analyzer import (
    CPOM_RESTRICTIVE_STATES,
    EXPANSION_FAVORABLE_STATES,
    GeoFinding,
    GeoReachReport,
    StateFootprint,
    analyze_geography,
    render_geo_markdown,
)
from .growth_algorithm_diagnostic import (
    GrowthComponent,
    GrowthDiagnostic,
    GrowthInputs,
    diagnose_growth,
    render_growth_markdown,
)
from .technology_debt_assessor import (
    TechDebtFinding,
    TechDebtInputs,
    TechDebtReport,
    assess_technology_debt,
    render_tech_debt_markdown,
)
from .roic_decomposition import (
    ROICFinding,
    ROICInputs,
    ROICResult,
    SUBSECTOR_BANDS as ROIC_SUBSECTOR_BANDS,
    decompose_roic,
    render_roic_markdown,
)
from .working_capital_peer_band import (
    WC_PEER_BANDS,
    WCInputs,
    WCLever,
    WCPeerReport,
    benchmark_working_capital,
    render_wc_markdown,
)
from .hold_period_optimizer import (
    HoldInputs,
    HoldOptimizerResult,
    HoldYearOutcome,
    optimize_hold,
    render_hold_markdown,
)
from .pricing_power_diagnostic import (
    DIMENSION_WEIGHTS as PRICING_DIMENSION_WEIGHTS,
    PricingFinding,
    PricingPowerInputs,
    PricingPowerReport,
    assess_pricing_power,
    render_pricing_power_markdown,
)
from .portfolio_rollup_viewer import (
    PortfolioDeal,
    PortfolioRollup,
    SectorSummary,
    TopMover,
    build_portfolio_rollup,
    render_rollup_markdown,
)
from .bank_syndicate_picker import (
    LENDER_UNIVERSE,
    Lender,
    LenderPick,
    SyndicateInputs,
    SyndicateRecommendation,
    pick_syndicate,
    render_syndicate_markdown,
)
from .exit_channel_selector import (
    CHANNELS as EXIT_CHANNELS,
    ChannelRank,
    ExitChannelInputs,
    ExitChannelRecommendation,
    rank_exit_channels,
    render_exit_channel_markdown,
)
from .mgmt_incentive_sizer import (
    BASE_POOL_PCT as MIP_BASE_POOL_PCT,
    MIPAllocation,
    MIPInputs,
    MIPPlan,
    render_mip_markdown,
    size_mip,
)
from .qofe_tracker import (
    QOFE_STATUSES,
    QofEAdjustment,
    QofEFinding,
    QofEInputs,
    QofETracker,
    render_qofe_markdown,
    track_qofe,
)
from .board_composition_analyzer import (
    REQUIRED_COMMITTEES,
    REQUIRED_EXPERIENCE_AREAS,
    BoardGap,
    BoardInputs,
    BoardMember,
    BoardReport,
    analyze_board,
    render_board_markdown as render_board_composition_markdown,
)
from .historical_failure_library import (
    FAILURE_LIBRARY,
    FailureMatch,
    FailurePattern,
    list_all_patterns as list_failure_patterns,
    match_failures,
    render_failures_markdown,
)
from .partner_voice_memo import (
    REC_DILIGENCE_MORE,
    REC_INVEST,
    REC_PASS,
    PartnerVoiceInputs,
    PartnerVoiceMemo,
    build_partner_memo,
    render_partner_memo_markdown,
)
from .recurring_vs_onetime_ebitda import (
    ONE_TIME_CATEGORIES,
    RECURRING_CATEGORIES,
    EBITDAContribution,
    RecurringSplit,
    render_recurring_split_markdown,
    split_ebitda,
)
from .obbba_sequestration_stress import (
    RegulatoryStressInputs as OBBBAStressInputs,
    RegulatoryStressReport as OBBBAStressReport,
    RegulatoryShock as OBBBAShock,
    render_reg_stress_markdown,
    stress_regulatory,
)
from .archetype_subrunners import (
    ARCHETYPE_RUNNERS,
    ArchetypeContext as ArchetypeSubrunnerContext,
    ArchetypeReport as ArchetypeSubrunnerReport,
    ArchetypeWarning,
    back_office_consolidation_review,
    capacity_expansion_review,
    cmi_uplift_review,
    cost_basis_compression_review,
    outpatient_migration_review,
    payer_mix_shift_review,
    render_archetype_markdown as render_archetype_subrunner_markdown,
    roll_up_review,
    run_archetype,
)
from .unrealistic_on_its_face import (
    FaceInputs,
    ImplausibilityFinding,
    ImplausibilityReport,
    render_implausibility_markdown,
    scan_unrealistic,
)
from .partner_voice_variants import (
    VOICES,
    VOICE_BUILDERS,
    VoiceBundle,
    VoiceContext,
    VoiceParagraph,
    compose_all_voices,
    compose_voice,
    render_voices_markdown,
)
from .cross_module_connective_tissue import (
    ConnectedInsight,
    ConnectedReport,
    SignalBundle,
    connect_signals,
    render_connected_markdown,
)
from .diligence_checklist_live import (
    CANONICAL_ITEMS as DILIGENCE_CANONICAL_ITEMS,
    ChecklistItem as DiligenceChecklistItem,
    ChecklistReport as DiligenceChecklistReport,
    ChecklistStatus as DiligenceChecklistStatus,
    render_checklist_markdown as render_diligence_checklist_markdown,
    walk_checklist,
)
from .partner_traps_library import (
    TRAPS_LIBRARY,
    PartnerTrap,
    TrapHit,
    list_all_traps,
    match_traps,
    render_traps_markdown,
)
from .first_thirty_minutes import (
    FirstThirtyContext,
    FirstThirtyPlan,
    PartnerQuestion,
    build_first_thirty,
    render_first_thirty_markdown,
)
from .thesis_coherence_check import (
    CoherenceReport,
    Incoherence,
    ThesisPillar,
    check_coherence,
    render_coherence_markdown,
)
from .margin_of_safety import (
    LeverSafety,
    SafetyInputs,
    SafetyReport,
    analyze_safety,
    render_safety_markdown,
)
from .management_vs_packet_gap import (
    Claim,
    GapFinding,
    GapReport as MgmtGapReport,
    compare_claims,
    render_gap_markdown,
)
from .rcm_lever_cascade import (
    CascadeInputs,
    CascadeReport,
    CascadeStep,
    render_cascade_markdown,
    trace_cascade,
)
from .bear_case_generator import (
    BearCaseInputs,
    BearCaseReport,
    BearDriver,
    generate_bear_case,
    render_bear_case_markdown,
)
from .payer_mix_shift_cascade import (
    MixShiftInputs,
    MixShiftReport,
    MixShiftStep,
    RATE_MULTIPLIER,
    render_mix_shift_markdown,
    trace_mix_shift,
)
from .labor_shortage_cascade import (
    LaborCascadeInputs,
    LaborCascadeReport,
    LaborCascadeStep,
    render_labor_cascade_markdown,
    trace_labor_cascade,
)
from .exit_story_generator import (
    ExitStory,
    ExitStoryInputs,
    generate_exit_story,
    render_exit_story_markdown,
)
from .partner_scorecard import (
    ScorecardCheck,
    ScorecardInputs,
    ScorecardReport,
    render_scorecard_markdown,
    run_scorecard,
)
from .cycle_timing_pricing_check import (
    SUBSECTOR_CYCLE_AVG_MULT,
    CyclePricingInputs,
    CyclePricingReport,
    check_cycle_pricing,
    render_cycle_pricing_markdown,
)
from .one_hundred_day_plan_from_packet import (
    Plan as AutoPlan,
    PlanAction as AutoPlanAction,
    PlanContext as AutoPlanContext,
    generate_plan as generate_plan_from_packet,
    render_plan_markdown as render_auto_plan_markdown,
)
from .outpatient_migration_cascade import (
    OPMigrationInputs,
    OPMigrationReport,
    OPMigrationStep,
    render_op_migration_markdown,
    trace_op_migration,
)
from .quality_of_diligence_scorer import (
    REQUIRED as QOD_REQUIRED,
    DiligenceCompleted,
    DimensionScore as QoDDimensionScore,
    QoDReport,
    render_qod_markdown,
    score_diligence,
)
from .management_first_sitdown import (
    AgendaItem,
    SitdownAgenda,
    SitdownContext,
    build_agenda,
    render_agenda_markdown,
)
from .ic_decision_synthesizer import (
    ICDecision,
    ICSignalBundle,
    render_ic_decision_markdown,
    synthesize_ic_decision,
)
from .healthcare_regulatory_calendar import (
    CALENDAR as REG_CALENDAR,
    CalendarHit,
    CalendarReport,
    RegulatoryEvent,
    events_for_deal,
    list_all_events,
    render_calendar_markdown,
)
from .deal_smell_detectors import (
    DealSmell,
    SmellContext,
    SmellReport,
    detect_smells,
    render_smells_markdown,
)
from .letter_to_seller import (
    Letter,
    LetterContext,
    compose_letter,
    render_letter_markdown,
)
from .synergy_credibility_scorer import (
    CATEGORY_BASE_REALIZATION,
    SynergyAssessment,
    SynergyClaim,
    SynergyReport,
    render_synergy_report_markdown,
    score_synergies,
)
from .memo_formats import (
    render_all_formats as render_all_memo_formats,
    render_deck_bullets,
    render_email as render_memo_email,
    render_one_pager,
    render_pdf_ready,
    render_slack as render_memo_slack,
)
from .narrative_styles import (
    ALL_NARRATIVE_STYLES,
    compose_analyst_brief,
    compose_bullish_view,
    compose_founder_voice,
    compose_skeptic_view,
    compose_styled_narrative,
    compose_three_sentence,
)
from .thesis_templates import (
    TEMPLATES as THESIS_TEMPLATES,
    ThesisTemplate,
    fill_template,
    get_template,
    list_templates,
    render_template_markdown,
)
from .auditor_view import (
    AuditEntry,
    AuditTrail,
    build_audit_trail,
    filter_entries,
    summarize_trail,
)
from .capital_plan import (
    CapexLine,
    CapitalPlan,
    CapitalPlanFinding,
    has_plan_mismatch,
    validate_capital_plan,
)
from .recon import (
    ReconFinding,
    has_mismatch,
    reconcile,
)
from .kpi_alert_rules import (
    DEFAULT_RULES as KPI_DEFAULT_RULES,
    KPIAlert,
    KPIObservation,
    KPIRule,
    evaluate_all as evaluate_kpi_alerts,
    evaluate_kpi,
    summarize_alerts as summarize_kpi_alerts,
)
from .partner_discussion import (
    DiscussionItem,
    build_discussion,
    render_discussion_markdown,
)
from .cohort_tracker import (
    CohortDeal,
    CohortRanking,
    CohortStats,
    bottom_decile,
    cohort_stats,
    compare_to_cohort,
    group_by_vintage,
    rank_within_cohort,
    top_decile,
)
from .icr_gate import (
    ICReadinessResult,
    evaluate_ic_readiness,
)
from .commercial_due_diligence import (
    CDDFinding,
    CDDInputs,
    competitive_position,
    growth_plausibility,
    market_share_check,
    market_size_sanity,
    run_cdd_checks,
)
from .operational_kpi_cascade import (
    KPICascadeInputs,
    KPIMovement,
    build_cascade,
    top_levers,
    total_ebitda_impact,
)
from .pipeline_tracker import (
    FunnelStats,
    PIPELINE_STAGES,
    PipelineDeal,
    funnel_stats,
    source_mix,
    stale_deals,
)
from .lp_side_letter_flags import (
    ConformanceFinding,
    SideLetterRule,
    SideLetterSet,
    check_side_letters,
    has_breach,
)
from .cash_conversion import (
    CashConversionInputs,
    ConversionAssessment,
    assess_conversion,
    cash_conversion_ratio,
    expected_conversion_by_subsector,
)
from .regulatory_stress import (
    RegulatoryStressInputs,
    StressShock,
    run_regulatory_stresses,
    shock_340b_reduction,
    shock_cms_ipps_cut,
    shock_medicaid_freeze,
    shock_site_neutral,
    shock_snf_vbp_accel,
    summarize_regulatory_exposure,
)
from .fund_model import (
    Fund,
    FundDeal,
    FundProjection,
    commentary_for_quartile,
    fund_vintage_percentile,
    project_fund,
)
from .working_capital import (
    WCRelease,
    WCSummary,
    WorkingCapitalInputs,
    ap_days_to_cash,
    ar_days_to_cash,
    inventory_days_to_cash,
    total_wc_release,
)
from .synergy_modeler import (
    SynergyInputs,
    SynergyResult,
    apply_partner_haircut,
    realization_schedule,
    size_cost_synergies,
    size_procurement_synergies,
    size_rcm_synergies,
    size_revenue_synergies,
    size_synergies,
)
from .thesis_validator import (
    ConsistencyFinding,
    ThesisStatement,
    validate_thesis,
)
from .management_assessment import (
    DimensionScore,
    ManagementInputs,
    ManagementScore,
    score_management,
)
from .debt_sizing import (
    covenant_stress_passes,
    leverage_headroom,
    max_interest_rate_to_break,
    prudent_leverage,
)
from .deal_comparables import (
    COMPS,
    Comparable,
    filter_comps,
    multiple_stats,
    position_in_comps,
)
from .exit_math import (
    WaterfallResult,
    exit_waterfall,
    moic_cagr_to_irr,
    project_exit_ev,
    required_exit_ebitda_for_moic,
)
from .value_creation_tracker import (
    LeverActual,
    LeverPlan,
    LeverStatus,
    evaluate_lever,
    evaluate_plan,
    rollup_status,
)
from .workbench_integration import (
    archetype_summary,
    build_api_payload,
    build_workbench_bundle,
)
from .comparative_analytics import (
    DealSnapshot,
    DealVsBookFinding,
    concentration_warnings,
    correlation_risk,
    deal_rank_vs_peers,
    deal_vs_book,
    portfolio_concentration,
)
from .diligence_tracker import (
    DiligenceBoard,
    DiligenceItem,
    WORKSTREAMS,
    board_from_review,
    render_board_markdown,
)
from .ic_voting import (
    ROLE_WEIGHTS,
    Vote,
    VoteOutcome,
    Voter,
    aggregate_vote,
    auto_vote_from_review,
    default_committee,
)
from .hundred_day_plan import (
    HundredDayPlan,
    PlanAction,
    generate_plan,
    render_plan_markdown,
)
from .lp_pitch import (
    render_lp_all,
    render_lp_html,
    render_lp_markdown,
)
from .regulatory_watch import (
    REGISTRY as REGULATORY_REGISTRY,
    RegulatoryItem,
    for_deal as regulatory_items_for_deal,
    list_items as list_regulatory_items,
    summarize_for_partner as regulatory_summary_for_partner,
)
from .payer_math import (
    PayerScenario,
    ProjectionInputs,
    ScenarioResult,
    VBCInputs,
    VBCProjection,
    YearProjection,
    blended_rate_growth,
    compare_payer_scenarios,
    project_ebitda_from_revenue,
    project_revenue,
    standard_scenarios,
    vbc_revenue_projection,
)
from .deal_archetype import (
    ArchetypeContext,
    ArchetypeHit,
    classify_archetypes,
    primary_archetype,
)
from .sector_benchmarks import (
    GapFinding,
    SectorBenchmark,
    compare_to_peers,
    get_benchmark,
    list_metrics_for_subsector,
    list_subsectors,
)
from .scenario_stress import (
    StressInputs,
    StressResult,
    run_partner_stresses,
    stress_labor_shock,
    stress_lever_slip,
    stress_multiple_compression,
    stress_rate_down,
    stress_volume_down,
    worst_case_summary,
)

__all__ = [
    "Band",
    "BandCheck",
    "Heuristic",
    "HeuristicContext",
    "HeuristicHit",
    "NarrativeBlock",
    "PartnerReview",
    "all_heuristics",
    "check_ebitda_margin",
    "check_irr",
    "check_lever_realizability",
    "check_multiple_ceiling",
    "compose_narrative",
    "partner_review",
    "partner_review_from_context",
    "RED_FLAG_FIELDS",
    "ValuationInputs",
    "check_equity_concentration",
    "check_ev_walk",
    "check_interest_coverage",
    "check_terminal_growth",
    "check_terminal_value_share",
    "check_wacc",
    "run_all_rules",
    "run_heuristics",
    "run_reasonableness_checks",
    "run_red_flags",
    "run_valuation_checks",
    "StressInputs",
    "StressResult",
    "run_partner_stresses",
    "stress_labor_shock",
    "stress_lever_slip",
    "stress_multiple_compression",
    "stress_rate_down",
    "stress_volume_down",
    "worst_case_summary",
    "render_ic_memo_all",
    "render_ic_memo_html",
    "render_ic_memo_markdown",
    "render_ic_memo_text",
    "GapFinding",
    "SectorBenchmark",
    "compare_to_peers",
    "get_benchmark",
    "list_metrics_for_subsector",
    "list_subsectors",
    "ArchetypeContext",
    "ArchetypeHit",
    "classify_archetypes",
    "primary_archetype",
    "BEAR_PATTERNS",
    "BearPatternHit",
    "scan_bear_book",
    "ExitReadinessInputs",
    "ExitReadinessReport",
    "ReadinessFinding",
    "score_exit_readiness",
    "PayerScenario",
    "ProjectionInputs",
    "ScenarioResult",
    "VBCInputs",
    "VBCProjection",
    "YearProjection",
    "blended_rate_growth",
    "compare_payer_scenarios",
    "project_ebitda_from_revenue",
    "project_revenue",
    "standard_scenarios",
    "vbc_revenue_projection",
    "REGULATORY_REGISTRY",
    "RegulatoryItem",
    "regulatory_items_for_deal",
    "list_regulatory_items",
    "regulatory_summary_for_partner",
    "render_lp_all",
    "render_lp_html",
    "render_lp_markdown",
    "HundredDayPlan",
    "PlanAction",
    "generate_plan",
    "render_plan_markdown",
    "ROLE_WEIGHTS",
    "Vote",
    "VoteOutcome",
    "Voter",
    "aggregate_vote",
    "auto_vote_from_review",
    "default_committee",
    "DiligenceBoard",
    "DiligenceItem",
    "WORKSTREAMS",
    "board_from_review",
    "render_board_markdown",
    "DealSnapshot",
    "DealVsBookFinding",
    "concentration_warnings",
    "correlation_risk",
    "deal_rank_vs_peers",
    "deal_vs_book",
    "portfolio_concentration",
    "archetype_summary",
    "build_api_payload",
    "build_workbench_bundle",
    "LeverActual",
    "LeverPlan",
    "LeverStatus",
    "evaluate_lever",
    "evaluate_plan",
    "rollup_status",
    "WaterfallResult",
    "exit_waterfall",
    "moic_cagr_to_irr",
    "project_exit_ev",
    "required_exit_ebitda_for_moic",
    "COMPS",
    "Comparable",
    "filter_comps",
    "multiple_stats",
    "position_in_comps",
    "covenant_stress_passes",
    "leverage_headroom",
    "max_interest_rate_to_break",
    "prudent_leverage",
    "DimensionScore",
    "ManagementInputs",
    "ManagementScore",
    "score_management",
    "ConsistencyFinding",
    "ThesisStatement",
    "validate_thesis",
    "SynergyInputs",
    "SynergyResult",
    "apply_partner_haircut",
    "realization_schedule",
    "size_cost_synergies",
    "size_procurement_synergies",
    "size_rcm_synergies",
    "size_revenue_synergies",
    "size_synergies",
    "WCRelease",
    "WCSummary",
    "WorkingCapitalInputs",
    "ap_days_to_cash",
    "ar_days_to_cash",
    "inventory_days_to_cash",
    "total_wc_release",
    "Fund",
    "FundDeal",
    "FundProjection",
    "commentary_for_quartile",
    "fund_vintage_percentile",
    "project_fund",
    "RegulatoryStressInputs",
    "StressShock",
    "run_regulatory_stresses",
    "shock_340b_reduction",
    "shock_cms_ipps_cut",
    "shock_medicaid_freeze",
    "shock_site_neutral",
    "shock_snf_vbp_accel",
    "summarize_regulatory_exposure",
    "CashConversionInputs",
    "ConversionAssessment",
    "assess_conversion",
    "cash_conversion_ratio",
    "expected_conversion_by_subsector",
    "SideLetterRule",
    "SideLetterSet",
    "check_side_letters",
    "has_breach",
    "FunnelStats",
    "PIPELINE_STAGES",
    "PipelineDeal",
    "funnel_stats",
    "source_mix",
    "stale_deals",
    "KPICascadeInputs",
    "KPIMovement",
    "build_cascade",
    "top_levers",
    "total_ebitda_impact",
    "CDDFinding",
    "CDDInputs",
    "competitive_position",
    "growth_plausibility",
    "market_share_check",
    "market_size_sanity",
    "run_cdd_checks",
    "ICReadinessResult",
    "evaluate_ic_readiness",
    "CohortDeal",
    "CohortRanking",
    "CohortStats",
    "bottom_decile",
    "cohort_stats",
    "compare_to_cohort",
    "group_by_vintage",
    "rank_within_cohort",
    "top_decile",
    "DiscussionItem",
    "build_discussion",
    "render_discussion_markdown",
    "KPI_DEFAULT_RULES",
    "KPIAlert",
    "KPIObservation",
    "KPIRule",
    "evaluate_kpi",
    "evaluate_kpi_alerts",
    "summarize_kpi_alerts",
    "ReconFinding",
    "has_mismatch",
    "reconcile",
    "CapexLine",
    "CapitalPlan",
    "CapitalPlanFinding",
    "has_plan_mismatch",
    "validate_capital_plan",
    "AuditEntry",
    "AuditTrail",
    "build_audit_trail",
    "filter_entries",
    "summarize_trail",
    "THESIS_TEMPLATES",
    "ThesisTemplate",
    "fill_template",
    "get_template",
    "list_templates",
    "render_template_markdown",
    "ALL_REGIMES",
    "RegimeInputs",
    "RegimeResult",
    "classify_regime",
    "rank_all_regimes",
    "HHI_HIGHLY_CONCENTRATED",
    "HHI_UNCONCENTRATED",
    "MarketStructureResult",
    "analyze_market_structure",
    "compute_cr",
    "compute_cr3",
    "compute_cr5",
    "compute_hhi",
    "is_consolidation_play",
    "ScenarioOutcome",
    "StressGridResult",
    "run_stress_grid",
    "ALL_POSTURES",
    "PostureInputs",
    "PostureResult",
    "classify_posture",
    "posture_from_stress_and_heuristics",
    "WhiteSpaceInputs",
    "WhiteSpaceOpportunity",
    "WhiteSpaceResult",
    "detect_white_space",
    "top_opportunities",
    "InvestabilityInputs",
    "InvestabilityResult",
    "investability_inputs_from_review",
    "score_investability",
    "run_all_plus_extras",
    "run_extra_heuristics",
    "check_bed_occupancy",
    "check_capex_intensity",
    "check_case_mix_index",
    "check_length_of_stay",
    "check_rvu_per_provider",
    "run_extra_bands",
    "ALL_NARRATIVE_STYLES",
    "compose_analyst_brief",
    "compose_bullish_view",
    "compose_founder_voice",
    "compose_skeptic_view",
    "compose_styled_narrative",
    "compose_three_sentence",
    "render_all_memo_formats",
    "render_deck_bullets",
    "render_memo_email",
    "render_one_pager",
    "render_pdf_ready",
    "render_memo_slack",
    "ExtraArchetypeContext",
    "ExtraArchetypeHit",
    "classify_extra_archetypes",
    "EXTRA_RED_FLAG_FIELDS",
    "run_extra_red_flags",
    "ScenarioNarrativeResult",
    "render_scenario_markdown",
    "render_scenario_narrative",
    "ComparisonFinding",
    "ComparisonResult",
    "compare_reviews",
    "render_comparison_markdown",
    "PriorityInputs",
    "PriorityScore",
    "rank_deal_portfolio",
    "render_priority_list_markdown",
    "score_deal_priority",
    "render_board_memo",
    "render_board_memo_markdown",
    "ContractPortfolio",
    "ContractRisk",
    "PayerContract",
    "analyze_contract_portfolio",
    "render_contract_diligence_markdown",
    "ServiceLine",
    "ServiceLinePortfolio",
    "ServiceLineRisk",
    "analyze_service_lines",
    "render_service_lines_markdown",
    "QualityImpact",
    "QualityInputs",
    "QualityProfile",
    "analyze_quality_profile",
    "render_quality_profile_markdown",
    "LaborFinding",
    "LaborInputs",
    "LaborProfile",
    "analyze_labor_profile",
    "render_labor_profile_markdown",
    "build_cheatsheet",
    "render_cheatsheet_markdown",
    "check_gross_to_net",
    "check_payer_rate_growth",
    "check_site_neutral_parity",
    "run_reimbursement_bands",
    "AddbackFinding",
    "EBITDAAddback",
    "EBITDAQualityReport",
    "assess_ebitda_quality",
    "render_ebitda_quality_markdown",
    "CovenantDefinition",
    "CovenantObservation",
    "CovenantReport",
    "CovenantStatus",
    "evaluate_covenant",
    "monitor_covenants",
    "render_covenant_report_markdown",
    "CashWeek",
    "LiquidityReport",
    "project_cash_detail",
    "project_cash_runway",
    "render_liquidity_markdown",
    "ADDON_STAGES",
    "AddOnTarget",
    "PipelineSummary",
    "analyze_pipeline",
    "render_pipeline_markdown",
    "ESGFlag",
    "ESGInputs",
    "ESGReport",
    "render_esg_markdown",
    "screen_esg",
    "DEEP_DIVE_FIELDS",
    "run_deepdive_heuristics",
    "build_master_bundle",
    "bundle_index",
    "TaxFinding",
    "TaxStructureInputs",
    "TaxStructureReport",
    "analyze_tax_structure",
    "render_tax_structure_markdown",
    "InsuranceGap",
    "InsuranceInputs",
    "InsuranceReport",
    "render_insurance_report_markdown",
    "screen_insurance",
    "PortfolioDashboard",
    "build_portfolio_dashboard",
    "render_portfolio_dashboard_markdown",
    "IntegrationFinding",
    "IntegrationInputs",
    "IntegrationReport",
    "assess_integration_readiness",
    "render_integration_report_markdown",
    "CompFinding",
    "CompPlanInputs",
    "CompReport",
    "render_comp_plan_markdown",
    "review_comp_plan",
    "RedTeamAttack",
    "RedTeamReport",
    "build_red_team_report",
    "render_red_team_markdown",
    "CANONICAL_CHECKLIST",
    "DataRoomItem",
    "DataRoomReport",
    "analyze_data_room",
    "render_data_room_markdown",
    "Workstream",
    "WorkstreamMilestone",
    "WorkstreamReport",
    "aggregate_workstreams",
    "render_workstream_report_markdown",
    "NegotiationPosition",
    "derive_negotiation_position",
    "render_negotiation_markdown",
    "LOIDraft",
    "compose_loi",
    "render_loi_markdown",
    "PostMortemFinding",
    "PostMortemInputs",
    "PostMortemReport",
    "render_post_mortem_markdown",
    "run_post_mortem",
    "ALL_PHASES",
    "CycleInputs",
    "CycleResult",
    "classify_cycle",
    "render_cycle_markdown",
    "ExitMilestone",
    "ExitPlan",
    "ExitPlanInputs",
    "build_exit_plan",
    "render_exit_plan_markdown",
    "check_interest_to_ebitda",
    "check_nwc_days",
    "check_outpatient_share",
    "check_same_store_sales_growth",
    "check_sga_intensity",
    "run_benchmark_bands",
    "PayerMixRiskInputs",
    "PayerMixRiskReport",
    "PayerRisk",
    "analyze_payer_mix_risk",
    "render_payer_mix_risk_markdown",
    "PeerDeal",
    "PeerMatch",
    "find_peers",
    "render_peers_markdown",
    "CliffImpact",
    "CliffReport",
    "ReimbursementCliff",
    "default_cliff_library",
    "evaluate_cliffs",
    "render_cliff_report_markdown",
    "ScenarioComparison",
    "ScenarioInputs",
    "ScenarioComparisonOutcome",
    "compare_scenarios",
    "render_scenario_comparison_markdown",
    "VintageCurve",
    "VintageInputs",
    "VintageYearPoint",
    "project_vintage_curve",
    "render_vintage_curve_markdown",
    "CoInvestInputs",
    "CoInvestSizing",
    "render_coinvest_markdown",
    "size_coinvest",
    "SENSITIVITY_VARIABLES",
    "SensitivityBase",
    "SensitivityGrid",
    "SensitivityPoint",
    "render_sensitivity_markdown",
    "render_tornado_markdown",
    "run_sensitivity",
    "tornado",
    "CapStructureInputs",
    "CapStructurePoint",
    "CapStructureResult",
    "render_cap_structure_markdown",
    "sweep_cap_structure",
    "DebtTranche",
    "RefiContext",
    "RefiPlan",
    "RefiRecommendation",
    "plan_refinance",
    "render_refi_plan_markdown",
    "RecapAssessment",
    "RecapInputs",
    "analyze_recap",
    "render_recap_markdown",
    "CarveOutAssessment",
    "CarveOutInputs",
    "CarveOutRisk",
    "assess_carve_out",
    "render_carve_out_markdown",
    "SecondarySaleAssessment",
    "SecondarySaleInputs",
    "render_secondary_markdown",
    "value_secondary_sale",
    "LBO_STRESS_LIBRARY",
    "LBOStressInputs",
    "LBOStressReport",
    "LBOStressResult",
    "LBOStressScenario",
    "render_lbo_stress_markdown",
    "run_all_lbo_stresses",
    "run_lbo_stress_scenario",
    "MGMA_BENCHMARKS",
    "PhysicianCompFinding",
    "PhysicianCompInputs",
    "PhysicianCompReport",
    "benchmark_physician_comp",
    "render_physician_comp_markdown",
    "EBITDA_CATEGORY_ORDER",
    "EBITDA_HAIRCUTS",
    "EBITDAItem",
    "NormalizationResult",
    "normalize_ebitda",
    "render_normalization_markdown",
    "DEFAULT_RAMP_MONTHS",
    "DEFAULT_TTF_DAYS",
    "RoleProjection",
    "RoleState",
    "StaffingFinding",
    "StaffingReport",
    "analyze_staffing",
    "render_staffing_markdown",
    "INTEGRATION_DIMENSION_WEIGHTS",
    "BoltOnInputs",
    "BoltOnScore",
    "IntegrationScoreboard",
    "build_scoreboard",
    "render_scoreboard_markdown",
    "score_bolton",
    "ConcentrationAnalysis",
    "CustomerRecord",
    "CustomerRisk",
    "analyze_customers",
    "render_concentration_markdown",
    "CPOM_RESTRICTIVE_STATES",
    "EXPANSION_FAVORABLE_STATES",
    "GeoFinding",
    "GeoReachReport",
    "StateFootprint",
    "analyze_geography",
    "render_geo_markdown",
    "GrowthComponent",
    "GrowthDiagnostic",
    "GrowthInputs",
    "diagnose_growth",
    "render_growth_markdown",
    "TechDebtFinding",
    "TechDebtInputs",
    "TechDebtReport",
    "assess_technology_debt",
    "render_tech_debt_markdown",
    "ROIC_SUBSECTOR_BANDS",
    "ROICFinding",
    "ROICInputs",
    "ROICResult",
    "decompose_roic",
    "render_roic_markdown",
    "WC_PEER_BANDS",
    "WCInputs",
    "WCLever",
    "WCPeerReport",
    "benchmark_working_capital",
    "render_wc_markdown",
    "HoldInputs",
    "HoldOptimizerResult",
    "HoldYearOutcome",
    "optimize_hold",
    "render_hold_markdown",
    "PRICING_DIMENSION_WEIGHTS",
    "PricingFinding",
    "PricingPowerInputs",
    "PricingPowerReport",
    "assess_pricing_power",
    "render_pricing_power_markdown",
    "PortfolioDeal",
    "PortfolioRollup",
    "SectorSummary",
    "TopMover",
    "build_portfolio_rollup",
    "render_rollup_markdown",
    "LENDER_UNIVERSE",
    "Lender",
    "LenderPick",
    "SyndicateInputs",
    "SyndicateRecommendation",
    "pick_syndicate",
    "render_syndicate_markdown",
    "EXIT_CHANNELS",
    "ChannelRank",
    "ExitChannelInputs",
    "ExitChannelRecommendation",
    "rank_exit_channels",
    "render_exit_channel_markdown",
    "MIP_BASE_POOL_PCT",
    "MIPAllocation",
    "MIPInputs",
    "MIPPlan",
    "render_mip_markdown",
    "size_mip",
    "QOFE_STATUSES",
    "QofEAdjustment",
    "QofEFinding",
    "QofEInputs",
    "QofETracker",
    "render_qofe_markdown",
    "track_qofe",
    "REQUIRED_COMMITTEES",
    "REQUIRED_EXPERIENCE_AREAS",
    "BoardGap",
    "BoardInputs",
    "BoardMember",
    "BoardReport",
    "analyze_board",
    "render_board_composition_markdown",
    "FAILURE_LIBRARY",
    "FailureMatch",
    "FailurePattern",
    "list_failure_patterns",
    "match_failures",
    "render_failures_markdown",
    "REC_DILIGENCE_MORE",
    "REC_INVEST",
    "REC_PASS",
    "PartnerVoiceInputs",
    "PartnerVoiceMemo",
    "build_partner_memo",
    "render_partner_memo_markdown",
    "ONE_TIME_CATEGORIES",
    "RECURRING_CATEGORIES",
    "EBITDAContribution",
    "RecurringSplit",
    "render_recurring_split_markdown",
    "split_ebitda",
    "OBBBAStressInputs",
    "OBBBAStressReport",
    "OBBBAShock",
    "render_reg_stress_markdown",
    "stress_regulatory",
    "ARCHETYPE_RUNNERS",
    "ArchetypeSubrunnerContext",
    "ArchetypeSubrunnerReport",
    "ArchetypeWarning",
    "back_office_consolidation_review",
    "capacity_expansion_review",
    "cmi_uplift_review",
    "cost_basis_compression_review",
    "outpatient_migration_review",
    "payer_mix_shift_review",
    "render_archetype_subrunner_markdown",
    "roll_up_review",
    "run_archetype",
    "FaceInputs",
    "ImplausibilityFinding",
    "ImplausibilityReport",
    "render_implausibility_markdown",
    "scan_unrealistic",
    "VOICES",
    "VOICE_BUILDERS",
    "VoiceBundle",
    "VoiceContext",
    "VoiceParagraph",
    "compose_all_voices",
    "compose_voice",
    "render_voices_markdown",
    "ConnectedInsight",
    "ConnectedReport",
    "SignalBundle",
    "connect_signals",
    "render_connected_markdown",
    "DILIGENCE_CANONICAL_ITEMS",
    "DiligenceChecklistItem",
    "DiligenceChecklistReport",
    "DiligenceChecklistStatus",
    "render_diligence_checklist_markdown",
    "walk_checklist",
    "TRAPS_LIBRARY",
    "PartnerTrap",
    "TrapHit",
    "list_all_traps",
    "match_traps",
    "render_traps_markdown",
    "FirstThirtyContext",
    "FirstThirtyPlan",
    "PartnerQuestion",
    "build_first_thirty",
    "render_first_thirty_markdown",
    "CoherenceReport",
    "Incoherence",
    "ThesisPillar",
    "check_coherence",
    "render_coherence_markdown",
    "LeverSafety",
    "SafetyInputs",
    "SafetyReport",
    "analyze_safety",
    "render_safety_markdown",
    "Claim",
    "GapFinding",
    "MgmtGapReport",
    "compare_claims",
    "render_gap_markdown",
    "CascadeInputs",
    "CascadeReport",
    "CascadeStep",
    "render_cascade_markdown",
    "trace_cascade",
    "BearCaseInputs",
    "BearCaseReport",
    "BearDriver",
    "generate_bear_case",
    "render_bear_case_markdown",
    "MixShiftInputs",
    "MixShiftReport",
    "MixShiftStep",
    "RATE_MULTIPLIER",
    "render_mix_shift_markdown",
    "trace_mix_shift",
    "LaborCascadeInputs",
    "LaborCascadeReport",
    "LaborCascadeStep",
    "render_labor_cascade_markdown",
    "trace_labor_cascade",
    "ExitStory",
    "ExitStoryInputs",
    "generate_exit_story",
    "render_exit_story_markdown",
    "ScorecardCheck",
    "ScorecardInputs",
    "ScorecardReport",
    "render_scorecard_markdown",
    "run_scorecard",
    "SUBSECTOR_CYCLE_AVG_MULT",
    "CyclePricingInputs",
    "CyclePricingReport",
    "check_cycle_pricing",
    "render_cycle_pricing_markdown",
    "AutoPlan",
    "AutoPlanAction",
    "AutoPlanContext",
    "generate_plan_from_packet",
    "render_auto_plan_markdown",
    "OPMigrationInputs",
    "OPMigrationReport",
    "OPMigrationStep",
    "render_op_migration_markdown",
    "trace_op_migration",
    "QOD_REQUIRED",
    "DiligenceCompleted",
    "QoDDimensionScore",
    "QoDReport",
    "render_qod_markdown",
    "score_diligence",
    "AgendaItem",
    "SitdownAgenda",
    "SitdownContext",
    "build_agenda",
    "render_agenda_markdown",
    "ICDecision",
    "ICSignalBundle",
    "render_ic_decision_markdown",
    "synthesize_ic_decision",
    "REG_CALENDAR",
    "CalendarHit",
    "CalendarReport",
    "RegulatoryEvent",
    "events_for_deal",
    "list_all_events",
    "render_calendar_markdown",
    "DealSmell",
    "SmellContext",
    "SmellReport",
    "detect_smells",
    "render_smells_markdown",
    "Letter",
    "LetterContext",
    "compose_letter",
    "render_letter_markdown",
    "CATEGORY_BASE_REALIZATION",
    "SynergyAssessment",
    "SynergyClaim",
    "SynergyReport",
    "render_synergy_report_markdown",
    "score_synergies",
]
