from __future__ import annotations

import argparse
import os
from typing import Any, Dict, Optional

import pandas as pd
import yaml

from .store import PortfolioStore


def _load_yaml(path: str) -> Dict[str, Any]:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="RCM Monte Carlo Portfolio Store (Leap 7)")
    ap.add_argument("--db", required=True, help="Path to portfolio SQLite DB")

    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init", help="Initialize the portfolio DB")

    ap_add = sub.add_parser("add-run", help="Add a diligence run (config + summary)")
    ap_add.add_argument("--deal-id", required=True)
    ap_add.add_argument("--scenario", required=True, choices=["actual", "benchmark", "target"], help="Scenario label")
    ap_add.add_argument("--config", required=True, help="Path to YAML config used for the run")
    ap_add.add_argument("--summary", required=True, help="Path to summary.csv generated by the main CLI")
    ap_add.add_argument("--notes", default="", help="Optional notes")

    ap_list_deals = sub.add_parser("list-deals", help="List deals in DB")

    ap_list_runs = sub.add_parser("list-runs", help="List runs in DB")
    ap_list_runs.add_argument("--deal-id", default=None)

    ap_export = sub.add_parser("export-priors", help="Export empirical priors YAML from stored runs")
    ap_export.add_argument("--out", required=True, help="Output YAML path")

    return ap


def main(argv: Optional[list] = None) -> int:
    args = build_parser().parse_args(argv)
    store = PortfolioStore(args.db)

    if args.cmd == "init":
        store.init_db()
        print(f"Initialized DB: {args.db}")
        return 0

    if args.cmd == "add-run":
        cfg = _load_yaml(args.config)
        summary_df = pd.read_csv(args.summary, index_col=0)
        run_id = store.add_run(deal_id=args.deal_id, scenario=args.scenario, cfg=cfg, summary_df=summary_df, notes=args.notes)
        print(f"Added run_id={run_id} to {args.db}")
        return 0

    if args.cmd == "list-deals":
        df = store.list_deals()
        if df.empty:
            print("(no deals)")
        else:
            print(df.to_string(index=False))
        return 0

    if args.cmd == "list-runs":
        df = store.list_runs(deal_id=args.deal_id)
        if df.empty:
            print("(no runs)")
        else:
            print(df.to_string(index=False))
        return 0

    if args.cmd == "export-priors":
        priors = store.export_priors(args.out)
        print(f"Wrote priors to: {args.out}")
        return 0

    raise RuntimeError("unhandled command")


if __name__ == "__main__":
    raise SystemExit(main())
