// SeekingChartis — module catalog
// Authoritative data for every UI page the platform can open.
// Each entry drives a fully-fleshed ModulePage render: title, code,
// purpose, panels, key metrics, presets, sources.
// Scraped from the RCM-MC Python source (ui/*.py docstrings).

window.MODULES_CATALOG = [
  // ─────────────────────────── Deal lifecycle ───────────────────────────
  {
    id: "screen",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Screener",
    route: "/screen",
    tagline: "Paste hospital names. Get ranked verdicts in seconds.",
    kind: "screener",
    purpose:
      "Fast triage for partners and analysts: input a list of targets, the corpus returns a verdict, composite score, and the three most important signals per hospital. The entry point for origination.",
    panels: [
      { title: "Input", body: "Paste CCNs, hospital names, or DSO names — one per line. Or import from a saved search." },
      { title: "Ranked verdicts", body: "Each row: name · CCN · state · beds · composite score · verdict (PASS/WATCH/FAIL) · top signal." },
      { title: "Verdict distribution", body: "Stacked bar of PASS / WATCH / FAIL across the input set." },
    ],
    columns: ["CCN", "Hospital", "State", "Beds", "Score", "Verdict", "Top signal"],
    presets: [
      { name: "Community 80-250 beds, Southeast" },
      { name: "Safety-net below P25 collections" },
      { name: "Academic medical centers >400 beds" },
    ],
    sources: ["HCRIS FY2022", "ML composite", "Heuristic library v0.6"],
  },
  {
    id: "source",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Source",
    route: "/source",
    tagline: "Thesis-driven origination from the full HCRIS universe.",
    kind: "filter-list",
    purpose:
      "Build a thesis (state, beds, payer mix, margin bands, volume growth) and see every hospital in the HCRIS universe that fits — ranked by the investability composite.",
    panels: [
      { title: "Thesis filters", body: "Region · size · ownership · system affiliation · payer mix bands · margin bands · volume trend." },
      { title: "Universe table", body: "5,808 hospitals with live scoring. Hover for signal stack; click to open the deal dashboard." },
      { title: "Map view", body: "County-level choropleth; shade = composite score; dot size = beds." },
    ],
    columns: ["CCN", "Hospital", "State", "Beds", "Commercial %", "Margin %", "Composite"],
    presets: [
      { name: "Public-to-private rollup candidates" },
      { name: "Regional consolidators" },
      { name: "Distressed critical-access" },
    ],
    sources: ["HCRIS FY2022", "CMS POS file", "NPPES", "Investability scorer"],
  },
  {
    id: "new-deal",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "New deal",
    route: "/new-deal",
    tagline: "5-step intake wizard — from CCN to full analysis packet.",
    kind: "wizard",
    purpose:
      "Guided registration: pick the target, set the thesis, attach the data room, configure the RCM levers, and kick off the analysis packet. Takes ~90 seconds.",
    steps: [
      { n: 1, name: "Target", body: "Pick by CCN or search. Pre-fills from HCRIS." },
      { n: 2, name: "Thesis", body: "Archetype · vintage · entry multiple · sponsor · hold horizon." },
      { n: 3, name: "Data room", body: "Upload seller KPIs; overrides flow into Bayesian calibration." },
      { n: 4, name: "RCM levers", body: "Set 7-lever assumptions or accept ML-predicted targets." },
      { n: 5, name: "Kickoff", body: "Run packet; opens the analysis workbench when complete." },
    ],
    sources: ["HCRIS", "Analysis packet builder", "Bayesian calibration"],
  },
  {
    id: "deal-dashboard",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Deal dashboard",
    route: "/deal/<id>",
    tagline: "Operating chart for a single deal.",
    kind: "deal-dashboard",
    purpose:
      "The partner's home base on any given deal. Notes, tags, deadlines, health indicator, owner roster, stage history. Jump to any per-deal surface.",
    panels: [
      { title: "Header strip", body: "Name · stage · vintage · owner · composite · health dot · priority." },
      { title: "Notes & tags", body: "Freeform notes, stage-scoped; taggable by partner/analyst." },
      { title: "Deadlines", body: "IOI · LOI · IC date · committee prep · exclusivity clock." },
      { title: "Stage history", body: "Stage snapshots with delta annotations." },
      { title: "Per-deal jumps", body: "Workbench · partner review · red flags · archetype · investability · IC packet." },
    ],
    sources: ["portfolio.deals", "portfolio.notes", "portfolio.snapshots"],
  },
  {
    id: "analysis",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Analysis workbench",
    route: "/analysis/<id>",
    tagline: "Bloomberg-style six-tab analyst console.",
    kind: "workbench",
    open: "analysis", // hands off to the in-mockup workbench
    purpose:
      "The full DealAnalysisPacket across six tabs: Overview, RCM Profile, EBITDA Bridge, Monte Carlo, Risk & Diligence, Provenance. Zero external libraries — everything built with inline SVG + HTML.",
    panels: [
      { title: "Overview", body: "Headline composite · thesis summary · top-3 signals · what would change the mind." },
      { title: "RCM profile", body: "7-lever current vs P75 peer cohort · Bayesian posteriors · credible intervals." },
      { title: "EBITDA bridge", body: "Interactive waterfall; per-lever sliders debounce 300ms and repost to the bridge API." },
      { title: "Monte Carlo", body: "10k-path simulation · MOIC/IRR distribution · downside + base + upside bands." },
      { title: "Risk & diligence", body: "Heuristic hits · reasonableness grid · open diligence checklist." },
      { title: "Provenance", body: "Source tag for every number: HCRIS / ML / seller / calibrated / benchmark." },
    ],
    sources: ["DealAnalysisPacket", "bridge API", "Monte Carlo engine", "Provenance system"],
  },
  {
    id: "compare",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Compare",
    route: "/compare",
    tagline: "Side-by-side deal metrics.",
    kind: "compare",
    purpose:
      "Line up two to four deals and compare the full RCM + thesis + returns stack. Delta columns highlight the differences that matter.",
    panels: [
      { title: "Deal selector", body: "Pick up to 4 deals by name or CCN." },
      { title: "Side-by-side matrix", body: "All 7 levers · bridge totals · IRR/MOIC · investability · red-flag count." },
      { title: "Delta column", body: "Every row shows abs + % gap, colored by direction." },
    ],
    columns: ["Metric", "Deal A", "Deal B", "Deal C", "Δ (A→B)", "Δ (A→C)"],
    sources: ["DealAnalysisPacket (x n)", "deal_comparison.py"],
  },
  {
    id: "ic-memo",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "IC memo",
    route: "/api/deals/<id>/memo",
    tagline: "One-click investment-committee memo.",
    kind: "long-form",
    purpose:
      "Auto-generates a complete, substantive IC memo using only public data and ML models. Saves analysts 20+ hours per deal. Every number is fact-checked against the packet.",
    sections: [
      "Target Overview & Thesis",
      "Market Context & Competitive Position",
      "RCM Performance Analysis with Comps",
      "Predicted Improvement Opportunities",
      "EBITDA Bridge with Sensitivities",
      "Returns Analysis (Base/Bull/Bear)",
      "Key Risks & Mitigants",
      "Data Sources & Methodology Appendix",
    ],
    sources: ["ic_memo.py", "partner_review", "Analysis packet"],
  },
  {
    id: "ic-packet",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "IC packet",
    route: "/deal/<id>/ic-packet",
    tagline: "Everything in one document.",
    kind: "long-form",
    purpose:
      "The 'give me everything' view. Combines ic_memo + master_bundle: full memo, analyst cheatsheet, 100-day plan, bear patterns, regulatory items, partner discussion.",
    sections: [
      "Table of contents",
      "IC memo (full text)",
      "Analyst cheatsheet",
      "100-day plan (markdown)",
      "Bear patterns",
      "Regulatory items",
      "Partner discussion",
      "Audit trail",
    ],
    sources: ["pe_intelligence.master_bundle", "pe_intelligence.ic_memo"],
  },
  {
    id: "partner-review",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Partner review",
    route: "/deal/<id>/partner-review",
    tagline: "The brain's verdict in partner voice.",
    kind: "deal-verdict",
    purpose:
      "Biggest integration with the PE Intelligence Brain. IC recommendation banner, bull/bear case, three-things-that-would-change-my-mind, reasonableness bands, heuristic hits, investability composite, regime, market structure, stress grid.",
    panels: [
      { title: "Recommendation banner", body: "PASS · PROCEED_WITH_CAVEATS · PROCEED · STRONG_PROCEED with rationale." },
      { title: "Partner voice", body: "Headline · bull case · bear case · IC-memo paragraph (written as the partner would)." },
      { title: "Three things to change my mind", body: "Key questions derived from the weakest signals." },
      { title: "Reasonableness grid", body: "IN_BAND · STRETCH · OUT_OF_BAND · IMPLAUSIBLE counts per thesis claim." },
      { title: "Heuristic hits", body: "Critical · high · medium · low severity with per-hit detail." },
      { title: "Stress grid", body: "Pass/fail per downside scenario + covenant breach flags." },
    ],
    sources: ["pe_intelligence.partner_review", "_enrich_secondary_analytics"],
  },
  {
    id: "red-flags",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Red flags",
    route: "/deal/<id>/red-flags",
    tagline: "The 30-second 'should I care?' read.",
    kind: "red-flags",
    purpose:
      "Focused 'what's wrong with this deal' surface. Only the heuristic hits and reasonableness violations — no narrative, no stress grid, no composite.",
    severities: ["CRITICAL", "HIGH", "MEDIUM", "LOW"],
    sources: ["pe_intelligence.partner_review (hits)", "reasonableness grid"],
  },
  {
    id: "archetype",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Archetype & regime",
    route: "/deal/<id>/archetype",
    tagline: "Sponsor structure + time-series regime.",
    kind: "deal-classifier",
    purpose:
      "Two orthogonal classifications: archetype (platform-rollup, take-private, carve-out, turnaround, buy-and-build, continuation, GP-led secondary, PIPE, operating-lift, growth equity) and regime (durable_growth, emerging_volatile, steady, stagnant, declining_risk).",
    panels: [
      { title: "Archetype", body: "Best-fit archetype + lever stack + named risks + IC questions." },
      { title: "Regime", body: "Time-series classification · confidence · signals · playbook · key risk." },
    ],
    sources: ["pe_intelligence.deal_archetype", "pe_intelligence.regime_classifier"],
  },
  {
    id: "investability",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Investability & exit",
    route: "/deal/<id>/investability",
    tagline: "Should we be in this deal at all?",
    kind: "deal-score",
    purpose:
      "Composite 0-100 investability score (opportunity / value / stability sub-scores, letter grade) plus exit-readiness across 12 dimensions rolling up to: not_ready · needs_work · mostly_ready · exit_ready.",
    panels: [
      { title: "Composite score", body: "0-100 with letter grade. Sub-scores: opportunity, value, stability." },
      { title: "Named strengths & weaknesses", body: "Top signals on either side." },
      { title: "Exit readiness", body: "12 dimensions: audited financials, KPI reporting, data room, QoE, EBITDA trend, margin trend, buyer universe, management retention, legal, add-back recon, EBITDA vs plan, revenue vs plan." },
      { title: "Three things that most need to be true", body: "Top 3 weaknesses as thesis conditions." },
    ],
    sources: ["investability_scorer", "exit_readiness"],
  },
  {
    id: "market-structure",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Market structure",
    route: "/deal/<id>/market-structure",
    tagline: "How concentrated is this market?",
    kind: "market",
    purpose:
      "HHI, CR3, CR5, top-share; consolidation_play_score + thesis hint; fragmentation verdict (concentrated / fragmented / consolidating / bimodal).",
    panels: [
      { title: "Concentration metrics", body: "HHI · CR3 · CR5 · top-share." },
      { title: "Consolidation play score", body: "0-100 with thesis hint." },
      { title: "Fragmentation verdict", body: "One of: concentrated · fragmented · consolidating · bimodal." },
    ],
    sources: ["pe_intelligence.market_structure", "packet.market_shares"],
  },
  {
    id: "white-space",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "White space",
    route: "/deal/<id>/white-space",
    tagline: "Where the target has room to grow.",
    kind: "whitespace",
    purpose:
      "Adjacencies along three dimensions: geographic (states adjacent to footprint), segment (service lines the target lacks but peers run), channel (HOPD → ASC, IP → OP, direct-contracting → employer self-funded).",
    panels: [
      { title: "Geographic adjacencies", body: "States not covered but adjacent or typical for subsector." },
      { title: "Segment adjacencies", body: "Service lines / sub-specialties common to the subsector." },
      { title: "Channel adjacencies", body: "Delivery-channel expansion paths." },
    ],
    sources: ["pe_intelligence.white_space"],
  },
  {
    id: "stress",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Stress grid",
    route: "/deal/<id>/stress",
    tagline: "What if everything goes wrong?",
    kind: "stress",
    purpose:
      "Downside scenarios (rate cut, volume shock, denial spike, payer renegotiation loss, cost inflation). Each scenario: pass/fail · EBITDA delta · covenant breach flag.",
    panels: [
      { title: "Downside scenarios", body: "Grid of outcomes with severity tagging." },
      { title: "Covenant headroom", body: "Pre/post-stress breach flags per scenario." },
    ],
    sources: ["pe_intelligence.stress_test.run_stress_grid"],
  },
  {
    id: "packet-export",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Packet export",
    route: "/api/deals/<id>/package",
    tagline: "One-click diligence ZIP.",
    kind: "export",
    purpose:
      "Bundles the full packet: IC memo PDF, EBITDA bridge XLS, Monte Carlo CSV, 100-day plan MD, provenance trail, analyst cheatsheet, bear patterns.",
    sources: ["packet.export_bundle"],
  },

  // ─────────────────────────── Portfolio ops ───────────────────────────
  {
    id: "dashboard",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Partner dashboard",
    route: "/",
    tagline: "The seven-panel partner landing.",
    kind: "dashboard",
    purpose:
      "Pipeline funnel · active alerts · portfolio health distribution · recent deals · upcoming deadlines · PE intelligence highlights · corpus insights. Every panel degrades gracefully if a backend query fails.",
    panels: [
      { title: "Pipeline funnel", body: "Sourcing → Screened → IOI → LOI → Diligence → IC → Closed." },
      { title: "Active alerts", body: "All triggered alerts, newest first." },
      { title: "Portfolio health", body: "Distribution bar of health scores across deals." },
      { title: "Recent deals", body: "Top 6 by activity." },
      { title: "Deadlines", body: "Next 14 days across the portfolio." },
      { title: "PE verdicts", body: "Top-3 partner-review verdicts." },
      { title: "Corpus insights", body: "Recent additions + top vintages." },
    ],
    sources: ["portfolio.deals", "alerts.triggered", "pe_intelligence.partner_review"],
  },
  {
    id: "portfolio-overview",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Portfolio overview",
    route: "/portfolio/overview",
    tagline: "Fund-level rollup.",
    kind: "portfolio-rollup",
    purpose:
      "Every deal, rolled up to fund metrics: MOIC · IRR · realized vs unrealized · sector mix · vintage distribution · sponsor concentration.",
    columns: ["Deal", "Stage", "Vintage", "Entry EV", "Current EV", "MOIC", "IRR", "Status"],
    sources: ["portfolio_overview.py", "portfolio.deals"],
  },
  {
    id: "heatmap",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Portfolio heatmap",
    route: "/portfolio/heatmap",
    tagline: "Metric heatmap across every deal.",
    kind: "heatmap",
    purpose:
      "Rows = deals, columns = top-8 RCM metrics. Cells colored by percentile rank vs the comparable cohort. Trend arrows from sequential analysis runs.",
    columns: ["Deal", "Denial rate", "Final denial", "Days in AR", "AR > 90d", "Net coll.", "Clean claim", "Cost/collect", "CMI"],
    sources: ["portfolio_heatmap.py", "Analysis packets (latest)"],
  },
  {
    id: "portfolio-map",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Geographic map",
    route: "/portfolio/map",
    tagline: "MSA / state concentration.",
    kind: "map",
    purpose:
      "County-level choropleth + dot overlay. Dot size = beds or EV. Hover → deal card. Color = composite score.",
    sources: ["portfolio_map.py", "CMS POS", "portfolio.deals"],
  },
  {
    id: "portfolio-mc",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Portfolio Monte Carlo",
    route: "/portfolio/monte-carlo",
    tagline: "Correlated fund-level simulation.",
    kind: "monte-carlo",
    purpose:
      "10k-path simulation across the full portfolio with deal-level correlations (sector, geography, vintage). Fund IRR/MOIC distribution · tail risk · diversification benefit.",
    sources: ["scenarios.portfolio_mc", "correlation matrix"],
  },
  {
    id: "portfolio-bridge",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Portfolio bridge",
    route: "/portfolio/bridge",
    tagline: "Attribution + waterfall across the fund.",
    kind: "bridge",
    purpose:
      "From committed capital to net-to-LP: GP commit · fees · carry · realized + unrealized gains per deal · reserves · DPI / TVPI evolution.",
    sources: ["portfolio_bridge_page.py"],
  },
  {
    id: "lp-update",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "LP digest",
    route: "/lp-update",
    tagline: "Partner-ready LP update.",
    kind: "long-form",
    purpose:
      "Quarterly LP update, auto-composed. Portfolio highlights, material developments per deal, variance vs plan, pacing, ESG.",
    sections: [
      "Executive summary",
      "Fund performance",
      "Deal highlights",
      "Material developments",
      "Capital activity",
      "Pipeline",
      "Exits",
      "ESG",
    ],
    sources: ["exports.lp_update"],
  },
  {
    id: "hold",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Hold dashboard",
    route: "/hold",
    tagline: "Variance + initiatives.",
    kind: "hold",
    purpose:
      "Per-deal in-hold view: variance vs plan, initiative rollup, 100-day-plan completion, owner accountability.",
    columns: ["Deal", "Hold yr", "EBITDA vs plan", "Revenue vs plan", "Initiatives", "On-track %", "Owner"],
    sources: ["hold_dashboard.py", "initiatives.rollup"],
  },

  // ─────────────────────────── Analytics & models ───────────────────────────
  {
    id: "ebitda",
    group: "ANL",
    groupName: "Analytics & models",
    title: "EBITDA bridge",
    route: "/analysis/<id>#ebitda",
    tagline: "7-lever PE returns math.",
    kind: "bridge",
    purpose:
      "For any hospital, auto-generates a 7-lever RCM EBITDA bridge with revenue / cost / WC breakdown, implementation timing, IRR/MOIC sensitivity at multiple entry multiples, waterfall (CSS-only), covenant headroom.",
    levers: [
      "Denial reduction",
      "Days-in-AR compression",
      "AR>90d cleanup",
      "Net collection rate",
      "Clean claim rate",
      "Cost-to-collect",
      "Payer mix shift",
    ],
    sources: ["ebitda_bridge_page.py", "_compute_bridge", "_compute_returns_grid"],
  },
  {
    id: "scenarios",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Scenarios",
    route: "/scenarios",
    tagline: "Payer policy + macro shocks.",
    kind: "scenarios",
    purpose:
      "Pre-built macro + policy scenarios applied across the portfolio: Medicare rate cut 2%, Medicaid expansion, No Surprises Act enforcement, payer renegotiation, labor inflation, volume shock.",
    sources: ["scenarios_page.py"],
  },
  {
    id: "scenario-modeler",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Scenario modeler",
    route: "/scenario-modeler",
    tagline: "Name your own scenario.",
    kind: "scenario-builder",
    purpose:
      "Adjust RCM levers, payer mix, volume, and macro assumptions. Each scenario flows through the EBITDA bridge and returns engine. Save and compare up to 4 scenarios side-by-side.",
    presets: [
      { name: "Base Case", desc: "ML-predicted targets at P75 peers, 60% gap closure" },
      { name: "Conservative", desc: "50% of base improvement, flat multiple" },
      { name: "Aggressive", desc: "130% improvement, 1× multiple expansion, 4% growth" },
      { name: "Downside", desc: "Rate cut + denial spike" },
      { name: "Payer Renegotiation", desc: "Commercial rate uplift" },
      { name: "Bed Expansion", desc: "+50 beds, 18mo ramp" },
      { name: "Merger Synergy", desc: "Shared RCM platform" },
    ],
    sources: ["scenario_modeler_page.py"],
  },
  {
    id: "sensitivity",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Sensitivity",
    route: "/sensitivity",
    tagline: "Tornado + partial dependences.",
    kind: "sensitivity",
    purpose:
      "Per-deal sensitivity analysis. Tornado chart of returns sensitivity to each lever; partial-dependence curves for non-linear drivers (volume × case-mix, denial rate × AR days).",
    sources: ["sensitivity_dashboard.py"],
  },
  {
    id: "regression",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Regression lab",
    route: "/regression",
    tagline: "Regression across the corpus.",
    kind: "regression",
    purpose:
      "Fit and interrogate regressions across the 655-deal corpus + the 5,808-hospital universe. Coefficient plots, residuals, influence diagnostics.",
    sources: ["regression_page.py"],
  },
  {
    id: "bayesian",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Bayesian calibration",
    route: "/bayesian",
    tagline: "Priors & posteriors per hospital.",
    kind: "bayesian",
    purpose:
      "Per-hospital Bayesian posterior estimates for all RCM metrics, with shrinkage visualization, credible intervals, and data quality scoring.",
    sources: ["bayesian_page.py", "ml.bayesian_calibration"],
  },
  {
    id: "surrogate",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Surrogate model",
    route: "/surrogate",
    tagline: "Fast proxy for Monte Carlo.",
    kind: "surrogate",
    purpose:
      "Gradient-boosted surrogate trained on Monte Carlo runs. Returns MOIC/IRR estimate 10,000× faster than full MC, with conformal prediction intervals.",
    sources: ["surrogate_page.py", "ml.surrogate_model"],
  },
  {
    id: "fund-learning",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Fund learning",
    route: "/fund-learning",
    tagline: "Cross-deal calibration.",
    kind: "fund-learning",
    purpose:
      "Learn what the fund's deals have in common: which signals predicted realized outcomes, which thesis archetypes underperformed, which sponsor profiles the fund gets right.",
    sources: ["fund_learning_page.py"],
  },
  {
    id: "quant-lab",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Quant lab",
    route: "/quant-lab",
    tagline: "Full quant stack.",
    kind: "quant",
    purpose:
      "Bayesian calibration · DEA efficiency frontier · queueing theory · survival analysis · market intelligence · causal inference · cross-deal learning. The complete analytical moat in one page.",
    sources: ["quant_lab_page.py"],
  },

  // ─────────────────────────── Market intelligence ───────────────────────────
  {
    id: "market",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Market analysis",
    route: "/market",
    tagline: "Sector-level views.",
    kind: "market",
    purpose:
      "Sector rollups: sub-industry margin bands, volume trends, concentration indices, sponsor activity.",
    sources: ["market_analysis_page.py"],
  },
  {
    id: "market-data",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Market data",
    route: "/market-data",
    tagline: "External indicators.",
    kind: "market",
    purpose:
      "CPI-medical · hospital wage index · MA enrollment · Medicare rate settings · state expansion status · labor metrics.",
    sources: ["market_data_page.py"],
  },
  {
    id: "competitive",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Competitive intel",
    route: "/competitive",
    tagline: "Comp & sponsor profiles.",
    kind: "competitive",
    purpose:
      "For any target: local competitors (HHI + CR3 + share), sponsor exposure in the sub-sector, recent transactions, valuations, multiple history.",
    sources: ["competitive_intel_page.py"],
  },
  {
    id: "demand",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Demand",
    route: "/demand",
    tagline: "Utilization + volume curves.",
    kind: "demand",
    purpose:
      "Hospital and MSA-level volume by service line, year-over-year, with regression-residual highlights (underperformers + overperformers).",
    sources: ["demand_page.py"],
  },
  {
    id: "denial",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Denial",
    route: "/denial",
    tagline: "Denial taxonomy + benchmarks.",
    kind: "denial",
    purpose:
      "Corpus-wide denial patterns by payer, CARC/RARC code, service line, region. Benchmark each target against its comparable cohort.",
    sources: ["denial_page.py"],
  },
  {
    id: "pressure",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Pressure",
    route: "/pressure",
    tagline: "Payer pressure signals.",
    kind: "pressure",
    purpose:
      "Rising denial trends, payer-specific AR extensions, commercial rate pushback, PDPM/MS-DRG movement, policy enforcement.",
    sources: ["pressure_page.py"],
  },
  {
    id: "sponsor-track",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Sponsor track record",
    route: "/sponsor-track-record",
    tagline: "Sortable league table of every PE sponsor.",
    kind: "sponsor",
    purpose:
      "From the 655-deal corpus: deal count + realized count, MOIC (p25/p50/mean/p75), IRR median, median hold, loss rate, home-run rate, consistency, sector specialization.",
    columns: ["Sponsor", "# Deals", "Realized", "MOIC p50", "MOIC p75", "IRR p50", "Hold (yr)", "Loss %", "HR %", "Consistency"],
    sources: ["data_public.sponsor_track_record"],
  },
  {
    id: "payer-intel",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Payer intelligence",
    route: "/payer-intelligence",
    tagline: "Does payer mix predict outcomes?",
    kind: "payer",
    purpose:
      "Corpus-wide payer mix averages, correlation of commercial / medicaid / self-pay % against realized MOIC, four payer-mix regime bands with per-band MOIC P25/P50/P75.",
    sources: ["data_public.payer_intelligence"],
  },
  {
    id: "rcm-benchmarks",
    group: "MKT",
    groupName: "Market intelligence",
    title: "RCM benchmarks",
    route: "/rcm-benchmarks",
    tagline: "Industry benchmarks for core RCM metrics.",
    kind: "benchmarks",
    purpose:
      "P25/P50/P75 bands per segment (community, academic, critical access, LTAC, ASC, behavioral, physician group, home health) for the seven core RCM metrics.",
    columns: ["Segment", "Initial denial", "Clean claim", "Days in AR", "Collection rate", "Write-off %", "Cost/collect", "Overturn %"],
    sources: ["data_public.rcm_benchmarks", "HFMA MAP 2023", "Advisory Board 2022"],
  },
  {
    id: "corpus-backtest",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Corpus backtest",
    route: "/corpus-backtest",
    tagline: "Does the platform forecast correctly?",
    kind: "backtest",
    purpose:
      "Cross-matches platform-predicted outcomes against the 655-deal corpus's realized MOIC / IRR. Scores platform forecast accuracy by vintage and sub-sector.",
    sources: ["data_public.backtester"],
  },
  {
    id: "pe-intel-hub",
    group: "MKT",
    groupName: "Market intelligence",
    title: "PE intelligence hub",
    route: "/pe-intelligence",
    tagline: "What can the brain do?",
    kind: "hub",
    purpose:
      "Landing page for the 278-module PE Intelligence Brain. Surfaces the seven partner reflexes and links to the archetype library, reasonableness matrix, red-flag catalog, and bear book.",
    sources: ["pe_intelligence_hub_page.py"],
  },
  {
    id: "deal-screening",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Deal screening engine",
    route: "/deal-screening",
    tagline: "Run the corpus through your thresholds.",
    kind: "screener",
    purpose:
      "Interactive: tighten thresholds (max composite risk, max EV/EBITDA, max Medicaid%, etc.) and watch PASS / WATCH / FAIL counts shift live.",
    sources: ["data_public.deal_screening_engine"],
  },

  // ─────────────────────────── Tools & admin ───────────────────────────
  {
    id: "command",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Command center",
    route: "/command",
    tagline: "Operator console.",
    kind: "command",
    purpose:
      "Run backfills, inspect job queue, trigger data refreshes, roll the cache, promote models. Admins only.",
    sources: ["command_center.py"],
  },
  {
    id: "data-explorer",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Data explorer",
    route: "/data-explorer",
    tagline: "Ad-hoc SQL / slice.",
    kind: "explorer",
    purpose:
      "Read-only query layer over the SeekingChartis SQLite. Pre-baked views for corpus_deals, portfolio_deals, ml_predictions, provenance_log. CSV export.",
    sources: ["data_explorer.py"],
  },
  {
    id: "data",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Data dashboard",
    route: "/data",
    tagline: "Freshness + coverage.",
    kind: "data",
    purpose:
      "Last-refresh timestamps per source, row counts, coverage gaps, schema health, test pass/fail, ETL job latency.",
    sources: ["data_dashboard.py"],
  },
  {
    id: "library",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Library",
    route: "/library",
    tagline: "Saved views + memos + corpus.",
    kind: "library",
    purpose:
      "The reference catalogue: saved screener filters, analyst memos, published LP letters, and the 655-deal corpus index with search + filters.",
    sources: ["library_page.py"],
  },
  {
    id: "provenance",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Provenance",
    route: "/provenance",
    tagline: "Source attribution for every number.",
    kind: "provenance",
    purpose:
      "Every metric in the platform carries a source: HCRIS public filing · ML prediction · seller data room · Bayesian calibration · benchmark default · computed derivation. The trust layer.",
    sources_palette: [
      { label: "HCRIS", desc: "CMS Cost Report public filing", trust: "high" },
      { label: "ML", desc: "Machine-learned prediction", trust: "medium" },
      { label: "Seller", desc: "Seller data room input", trust: "medium" },
      { label: "Calibrated", desc: "Bayesian posterior (prior + data)", trust: "high" },
      { label: "Benchmark", desc: "Industry benchmark default", trust: "medium" },
      { label: "Computed", desc: "Derived from upstream metrics", trust: "high" },
    ],
    sources: ["provenance.py"],
  },
  {
    id: "methodology",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Methodology",
    route: "/methodology",
    tagline: "How each number is built.",
    kind: "docs",
    purpose:
      "Full explainer for every calculation in the platform. Input sources, formulas, edge cases, validation rules, citations.",
    sources: ["methodology_page.py"],
  },
  {
    id: "team",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Team",
    route: "/team",
    tagline: "Owners & approvers.",
    kind: "team",
    purpose:
      "Who owns each deal, who can approve what, current workloads, out-of-office, delegate chain.",
    sources: ["team_page.py"],
  },
  {
    id: "settings",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Settings",
    route: "/settings",
    tagline: "Auth, webhooks, automations.",
    kind: "settings",
    purpose:
      "Auth providers, SSO, API keys, webhook integrations, Slack / Teams alerts, alert thresholds, model promotion rules.",
    sources: ["settings_pages.py", "settings_ai_page.py"],
  },

  // ─────────────────────── Hospital-level & research ───────────────────────
  {
    id: "hospital-profile",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Hospital profile",
    route: "/hospital/<ccn>",
    tagline: "The stock-quote view of any hospital in the country.",
    kind: "long-form",
    purpose:
      "Every CCN in the corpus gets a full profile — identity strip, fundamentals, grade, payer mix, comparables, news. Works even for hospitals not in a live deal.",
    panels: [
      { title: "Identity strip", body: "CCN · location · beds · NPR · margin · investability grade." },
      { title: "Fundamentals", body: "3-year revenue, opex, net income; occupancy; case mix index." },
      { title: "Payer mix ring", body: "Medicare / Medicaid / Commercial split with benchmark overlay." },
      { title: "Comparables", body: "Nearest 8 hospitals by size + region with side-by-side grades." },
      { title: "News & filings", body: "CMS actions, 990 filings, local press, CoN activity." },
    ],
    sections: ["Overview", "Financials", "Quality & safety", "Payer mix", "Market context", "Comparables", "News"],
    sources: ["hospital_profile.py", "HCRIS", "CMS provider of services"],
  },
  {
    id: "thesis-card",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Thesis card",
    route: "/thesis/<ccn>",
    tagline: "The 30-second answer: should we pursue this hospital?",
    kind: "deal-verdict",
    purpose:
      "Synthesises every ML model into a single card — investability grade, EBITDA uplift, margin prediction, turnaround probability, top 3 risks, top 3 catalysts. Embeds in the hospital profile.",
    panels: [
      { title: "Verdict", body: "Grade + 1-sentence thesis. 'Pursue', 'Watch', or 'Pass'." },
      { title: "Uplift headline", body: "Predicted EBITDA delta vs current, with confidence band." },
      { title: "Top 3 risks", body: "ML-surfaced concentration, payer, operational, or regulatory flags." },
      { title: "Top 3 catalysts", body: "Denial reduction, AR compression, payer renegotiation potential." },
    ],
    sources: ["thesis_card.py", "ML ensemble"],
  },
  {
    id: "hospital-history",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Hospital history",
    route: "/history/<ccn>",
    tagline: "Multi-year financials, COVID resilience, peer trend projections.",
    kind: "long-form",
    purpose:
      "Treats each hospital like a stock — historical financials (10 yrs), YoY growth, CAGR, COVID resilience score, peer-relative trajectory, forward projection.",
    panels: [
      { title: "Revenue & opex timeline", body: "Stacked area; 2014-2023; COVID period highlighted." },
      { title: "Margin trend", body: "Op margin with peer P25/P75 band. Resilience score." },
      { title: "Beds & volume", body: "Stability of physical footprint; service-line exits flagged." },
      { title: "Peer trajectory", body: "Same-region same-size peers on one chart." },
    ],
    sources: ["hospital_history.py"],
  },
  {
    id: "hospital-stats",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Hospital statistics",
    route: "/stats/<ccn>",
    tagline: "Where this hospital falls on every variable — national + state.",
    kind: "heatmap",
    purpose:
      "Per-hospital regression profile: z-scores, percentiles, residuals vs expected across 16 metrics. Highlights statistical outliers for diligence investigation.",
    columns: ["Metric", "Value", "National P", "State P", "Z-score", "Residual", "Flag"],
    sources: ["hospital_stats_page.py", "regression_page.py"],
  },

  // ─────────────────────── ML & data room ───────────────────────
  {
    id: "ml-insights",
    group: "ANL",
    groupName: "Analytics & models",
    title: "ML insights",
    route: "/ml-insights",
    tagline: "Clustering, distress, RCM opportunity — the moat.",
    kind: "dashboard",
    purpose:
      "Surfaces proprietary ML: hospital clustering, distress prediction, RCM opportunity scoring, statistical outlier detection. The analysis Bloomberg and Capital IQ cannot replicate.",
    panels: [
      { title: "Cluster map", body: "Hospitals grouped by 11 financial + operational features; each cluster gets a persona." },
      { title: "Distress screener", body: "Top 25 candidates by distress probability with 1-year horizon AUC ≈ 0.84." },
      { title: "RCM opportunity", body: "Predicted EBITDA uplift from denial + AR + payer-mix improvements." },
      { title: "Outliers", body: "Hospitals >2.5σ from regression-predicted margin; drill into residuals." },
    ],
    sources: ["ml_insights_page.py", "hospital_clustering.py", "distress_predictor.py"],
  },
  {
    id: "data-room",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Data room",
    route: "/data-room/<deal>",
    tagline: "Merge seller data with ML predictions — Bayesian update on every entry.",
    kind: "long-form",
    purpose:
      "Analysts enter seller-reported KPIs; the system Bayesian-updates every prediction, recalculates the bridge, and flags where seller data confirms or contradicts the model. Every data point carries provenance.",
    panels: [
      { title: "Metric entry grid", body: "38 metric slots; type (rate / continuous / count); source + as-of date." },
      { title: "Prediction delta", body: "For each entry: prior, seller value, posterior, shrinkage, confirms/contradicts." },
      { title: "Provenance trail", body: "Every entry: who, when, which document, which page." },
      { title: "Recalc bridge", body: "Live EBITDA bridge updates as entries are added." },
    ],
    sections: ["Unit economics", "Payer contracts", "RCM ops", "Physician comp", "Real estate", "Diligence Q&A"],
    sources: ["data_room_page.py", "data/data_room.py"],
  },
  {
    id: "value-tracker",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Value creation tracker",
    route: "/value/<deal>",
    tagline: "Plan vs actuals, lever by lever, quarter by quarter.",
    kind: "bridge",
    purpose:
      "Frozen EBITDA bridge plan alongside quarterly actuals. Realization rates, ramp deviation detection, feed accuracy into the prediction ledger.",
    panels: [
      { title: "Plan vs actual by lever", body: "Denial, AR, coding, payer mix, cost-to-collect — each with on-track / lagging / off-track." },
      { title: "Realization curve", body: "Expected ramp vs actual; shows deviation at each quarter." },
      { title: "Attribution to initiatives", body: "Which operational initiatives drove which lever." },
      { title: "Lessons learned", body: "Feedback loop to the prediction model." },
    ],
    sources: ["value_tracking_page.py", "pe/value_tracker.py"],
  },
  {
    id: "model-validation",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Model validation",
    route: "/model-validation",
    tagline: "Prediction accuracy by metric. The compounding data moat.",
    kind: "backtest",
    purpose:
      "Prediction accuracy by metric, coverage calibration, bias trends, per-cohort breakdowns. Builds trust and quantifies how predictions improve over time.",
    panels: [
      { title: "RMSE trend", body: "Per metric; 90-day rolling; separates improvements from data drift." },
      { title: "Calibration plot", body: "Predicted probability vs observed frequency; 10 buckets." },
      { title: "Coverage by cohort", body: "Does a P80 interval cover 80% of actuals? Segmented by size + region." },
      { title: "Bias scorecard", body: "Systematic over/under-prediction per metric." },
    ],
    sources: ["model_validation_page.py", "ml/prediction_ledger.py"],
  },
  {
    id: "predictive-screener",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Predictive screener",
    route: "/predictive-screen",
    tagline: "Filter 6k hospitals by ML-predicted performance.",
    kind: "screener",
    purpose:
      "Deal sourcing via ML on public data: filter the HCRIS universe by predicted RCM performance, EBITDA uplift, distress probability, and market position. No internal data required.",
    panels: [
      { title: "Filter stack", body: "Region · size · payer mix · predicted denial · predicted uplift · distress probability." },
      { title: "Ranked universe", body: "Top N by composite with signal stack on hover." },
      { title: "Data-quality flag", body: "Filters out implausible HCRIS filings automatically." },
    ],
    columns: ["CCN", "Hospital", "State", "Beds", "Pred denial", "Pred uplift", "Distress p", "Composite"],
    presets: [
      { name: "High uplift, low distress" },
      { name: "Turnaround plays (high distress + recovery signal)" },
      { name: "Clean acquisitions (grade A, small)" },
    ],
    sources: ["predictive_screener.py"],
  },

  // ─────────────────────── Diligence tools ───────────────────────
  {
    id: "diligence-questions",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Diligence questions",
    route: "/diligence/<deal>/questions",
    tagline: "Auto-generated Q&A for seller management.",
    kind: "long-form",
    purpose:
      "Every identified flag becomes a pointed diligence question. Categories, priority, rationale. Exportable to Word.",
    panels: [
      { title: "Category roll-up", body: "Financials · RCM · payer · physician comp · real estate · compliance." },
      { title: "Priority badges", body: "Critical / high / medium with automatic routing to workstream leads." },
      { title: "Response tracker", body: "Seller response status per question." },
    ],
    columns: ["#", "Priority", "Category", "Question", "Rationale"],
    sources: ["diligence_page.py", "analysis/diligence_questions.py"],
  },
  {
    id: "playbook",
    group: "PRT",
    groupName: "Portfolio ops",
    title: "Value-creation playbook",
    route: "/playbook/<deal>",
    tagline: "The 100-day plan, tuned to this hospital.",
    kind: "long-form",
    purpose:
      "Auto-generated 100-day and 18-month playbook. Initiatives mapped to EBITDA levers, sequenced by dependency, owner placeholders.",
    sections: ["First 30 days", "30-60", "60-90", "90-180", "Year 2"],
    sources: ["diligence_page.py", "analysis/playbook.py"],
  },
  {
    id: "challenge-solver",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Challenge solver",
    route: "/models/challenge/<deal>",
    tagline: "What has to be true for the thesis to work?",
    kind: "long-form",
    purpose:
      "Inverse model: given a target IRR, solves for the minimum required performance on each lever. Surfaces which levers the thesis is most sensitive to.",
    panels: [
      { title: "Target IRR", body: "User sets hurdle (20 / 22 / 25%)." },
      { title: "Required levers", body: "Minimum denial reduction, AR compression, etc. to clear hurdle." },
      { title: "Feasibility score", body: "Each lever scored against historical achievability." },
    ],
    sources: ["advanced_tools_page.py", "analysis/challenge.py"],
  },

  // ─────────────────────── PE models ───────────────────────
  {
    id: "debt-model",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Debt model",
    route: "/models/debt/<deal>",
    tagline: "Year-by-year debt trajectory, leverage, cash sweeps.",
    kind: "bridge",
    purpose:
      "Full debt schedule: balance, mandatory + optional repayment, interest, leverage trajectory. Covenant headroom flagged at each year.",
    columns: ["Year", "Balance", "Principal", "Interest", "Leverage"],
    sources: ["advanced_tools_page.py", "pe/debt_model.py"],
  },
  {
    id: "waterfall",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Returns waterfall",
    route: "/models/waterfall/<deal>",
    tagline: "LP / GP split, tier by tier, with IRR + MOIC.",
    kind: "bridge",
    purpose:
      "Tier-by-tier LP/GP allocation at exit: hurdle, catch-up, promote tiers. Gross vs net IRR + MOIC. Sensitivities to hold period and exit multiple.",
    sources: ["waterfall_page.py", "pe/waterfall.py"],
  },
  {
    id: "pe-returns",
    group: "ANL",
    groupName: "Analytics & models",
    title: "PE returns & covenants",
    route: "/models/returns/<deal>",
    tagline: "IRR, MOIC, covenant headroom in one view.",
    kind: "deal-score",
    purpose:
      "Computed returns (IRR, MOIC, hold years, total distributions) plus covenant headroom analysis across base / downside / upside.",
    sources: ["pe_returns_page.py", "pe/pe_math.py"],
  },
  {
    id: "value-bridge",
    group: "ANL",
    groupName: "Analytics & models",
    title: "EBITDA value bridge",
    route: "/models/bridge/<deal>",
    tagline: "7-lever waterfall with probability-weighted impact.",
    kind: "bridge",
    purpose:
      "The canonical value bridge: current EBITDA → target EBITDA via 7 levers. Each lever: raw impact, probability, weighted impact, ramp months.",
    sources: ["pe_tools_page.py", "pe/value_bridge.py"],
  },
  {
    id: "causal",
    group: "ANL",
    groupName: "Analytics & models",
    title: "Causal inference",
    route: "/models/causal/<deal>",
    tagline: "Did the initiative actually move the metric?",
    kind: "long-form",
    purpose:
      "Three methods side-by-side — interrupted time series, difference-in-differences, pre/post — to quantify whether a portfolio initiative actually caused the observed metric change.",
    panels: [
      { title: "Method comparison", body: "Effect, CI, p-value per method." },
      { title: "What this means", body: "Plain-language interpretation for the IC memo." },
    ],
    sources: ["analytics_pages.py", "analytics/causal.py"],
  },

  // ─────────────────────── Corpus & research ───────────────────────
  {
    id: "news",
    group: "MKT",
    groupName: "Market intelligence",
    title: "News feed",
    route: "/news",
    tagline: "Healthcare PE market news, curated for diligence teams.",
    kind: "long-form",
    purpose:
      "Curates regulatory updates, payer policy shifts, deal activity, and RCM industry news into a Seeking Alpha-style article feed. Each article tagged with impact on PE-backed hospitals.",
    sections: ["M&A activity", "Regulatory", "Payer policy", "RCM industry", "Earnings", "Research"],
    sources: ["news_page.py"],
  },
  {
    id: "conference",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Conference roadmap",
    route: "/conferences",
    tagline: "JPM Healthcare, HIMSS, Becker's — every event on the PE calendar.",
    kind: "long-form",
    purpose:
      "Curated calendar of healthcare investment conferences, PE summits, and industry events. Each event tagged by relevance (deal sourcing, management meetings, RCM tech, operator perspectives).",
    sections: ["Flagship (JPM, HIMSS)", "Major industry", "RCM-specific", "Regional summits"],
    sources: ["conference_page.py"],
  },
  {
    id: "verticals",
    group: "MKT",
    groupName: "Market intelligence",
    title: "Verticals",
    route: "/verticals",
    tagline: "ASC, Behavioral Health, MSO — bridges beyond acute care.",
    kind: "long-form",
    purpose:
      "Sub-sector capabilities beyond acute care hospitals. Each vertical has its own metric registry, value bridge, and operator benchmarks.",
    sections: ["Acute care", "ASC", "Behavioral health", "MSO / physician groups", "Home health (roadmap)"],
    sources: ["verticals_page.py"],
  },

  // ─────────────────────── Workflow ───────────────────────
  {
    id: "deal-timeline",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Deal timeline",
    route: "/deal/<id>/timeline",
    tagline: "Every event on this deal, top-down.",
    kind: "long-form",
    purpose:
      "Unified activity timeline for a deal — analysis runs, alerts, exports, notes, overrides, MC runs. Color-coded cards, filter toggles, date range. Also lives as the workbench 8th tab.",
    panels: [
      { title: "Analysis events", body: "Every packet build + metric change, who triggered it." },
      { title: "Alerts fired", body: "With ack state and reason." },
      { title: "Exports", body: "IC memo, LP update, data-room extracts." },
      { title: "Overrides", body: "Human adjustments to model outputs, with justification." },
    ],
    sources: ["deal_timeline.py"],
  },
  {
    id: "deal-quick-view",
    group: "LFC",
    groupName: "Deal lifecycle",
    title: "Deal quick view",
    route: "/deal/<id>/quick",
    tagline: "Fallback when the full workbench isn't ready yet.",
    kind: "deal-dashboard",
    purpose:
      "Shows deal profile data with direct links to every model. Used when a deal is freshly created and hasn't been through the full analysis pipeline yet.",
    sources: ["deal_quick_view.py"],
  },
  {
    id: "quick-import",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Quick import",
    route: "/import",
    tagline: "Create a deal from the browser — no curl required.",
    kind: "wizard",
    purpose:
      "Minimal form for creating deals directly from the UI. Name, CCN, denial rate, AR days, net collection, revenue — just enough to bootstrap before the 5-step wizard kicks in.",
    sources: ["quick_import.py"],
  },

  // ─────────────────────── Alternate home views ───────────────────────
  {
    id: "home-v2",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Home (market-first)",
    route: "/home-v2",
    tagline: "Seeking Alpha-style: market pulse, insights, active deals.",
    kind: "dashboard",
    purpose:
      "Alternate home layout. Market pulse KPIs, editorial insights, active deal list, data freshness. Portfolio is one section, not the whole page.",
    sources: ["home_v2.py"],
  },
  {
    id: "dashboard-v2",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Dashboard (morning view)",
    route: "/dashboard-v2",
    tagline: "What needs my attention today, in 5 seconds.",
    kind: "dashboard",
    purpose:
      "Partner morning view: four summary cards, 'Needs attention' action list, deal-card grid, quick-action buttons. Replaces the legacy dashboard when routed from /.",
    sources: ["dashboard_v2.py"],
  },
  {
    id: "analysis-landing",
    group: "TLS",
    groupName: "Tools & admin",
    title: "Analysis landing",
    route: "/analysis",
    tagline: "Hub for all analytical tools, before you pick a deal.",
    kind: "dashboard",
    purpose:
      "When the user clicks 'Analysis' in the nav without a deal selected, shows recent deals with one-click access to every model.",
    sources: ["analysis_landing.py"],
  },
];
