#!/usr/bin/env python3
"""Audit every data_public analyzer page for honest data-source disclosure.

For each ``rcm_mc/ui/data_public/*_page.py`` it detects whether the page
discloses its data basis (a ck_source_purpose header, a ck_illustrative_note
banner, or a universe= label), whether it imports a real-data loader, and
whether it leans on the seed/illustrative corpus or hardcoded compute. It
cross-references the surface-status tier and flags pages that render figures
with NO disclosure of any kind (the integrity risk).

Writes ``data_quality/page_data_source_audit.json`` +
``docs/reports/PAGE_DATA_SOURCE_AUDIT.md``. Read-only; no app import side
effects beyond surface_status classification.

Run: python scripts/audit_page_data_sources.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from rcm_mc.diligence.surface_status import classify_surface

_ROOT = Path(__file__).resolve().parent.parent
_PAGES = _ROOT / "rcm_mc" / "ui" / "data_public"
_JSON = _ROOT / "data_quality" / "page_data_source_audit.json"
_MD = _ROOT / "docs" / "reports" / "PAGE_DATA_SOURCE_AUDIT.md"

# real-data loader modules — importing one signals a live/derived source.
_REAL_LOADERS = (
    "rcm_mc.data import", "from ..data", "from rcm_mc.data.",
    "snf", "mips_data", "ma_data", "payer_data", "hrsa_data",
    "drug_shortage_data", "mssp_aco_data", "industry_intel", "market_intel",
    "hcris",
)
_DISCLOSURE = ("ck_source_purpose", "ck_illustrative_note", 'universe="',
               "universe='", "DATA REQUIRED", "EXPORT REQUIRED")

# Real-data / admin / navigation pages: disclosure is BY SOURCE (they render
# real CMS/deal/registry data or are pure navigation indexes), so an
# "illustrative" banner would be dishonest. They carry no synthetic-data risk
# and are excluded from the NO_DISCLOSURE flag. Documented in
# docs/DATA_VERIFICATION_POLICY.md.
_REAL_OR_NAV_ROUTES = frozenset({
    "/cms-data-browser", "/cms-sources", "/data-sources-admin",
    "/deal-search", "/module-index",
})


def _route_for(fname: str) -> str:
    return "/" + fname[:-len("_page.py")].replace("_", "-")


def main() -> int:
    _JSON.parent.mkdir(parents=True, exist_ok=True)
    _MD.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for p in sorted(_PAGES.glob("*_page.py")):
        txt = p.read_text(errors="replace")
        route = _route_for(p.name)
        tier = classify_surface(route)
        has_disc = any(m in txt for m in _DISCLOSURE)
        has_real = any(m in txt for m in _REAL_LOADERS)
        uses_corpus = bool(re.search(r"_SEED_DEALS|deals_corpus|extended_seed|corpus", txt))
        renders_data = bool(re.search(r"ck_kpi_block|ck_value_anchor|compute_|<table", txt))
        # Flag: renders figures but discloses nothing.
        # Real-data pages (import a real loader) and known real/admin/nav routes
        # disclose by source — not a synthetic-data risk.
        disclosed_by_source = has_real or route in _REAL_OR_NAV_ROUTES
        flag = ""
        if renders_data and not has_disc and not disclosed_by_source:
            flag = "NO_DISCLOSURE"
        elif tier["tier"] == "red" and not has_disc and not disclosed_by_source:
            flag = "RED_NO_DISCLOSURE"
        rows.append({
            "route": route, "file": p.name, "tier": tier["tier"],
            "has_disclosure": has_disc, "imports_real_loader": has_real,
            "uses_seed_corpus": uses_corpus, "renders_data": renders_data,
            "flag": flag,
        })

    flagged = [r for r in rows if r["flag"]]
    summary = {
        "pages": len(rows),
        "with_disclosure": sum(1 for r in rows if r["has_disclosure"]),
        "with_real_loader": sum(1 for r in rows if r["imports_real_loader"]),
        "flagged_no_disclosure": len(flagged),
        "by_tier": {t: sum(1 for r in rows if r["tier"] == t)
                    for t in ("green", "navy", "yellow", "red")},
    }
    _JSON.write_text(json.dumps({"summary": summary, "pages": rows}, indent=2))

    lines = [
        "# Page Data-Source Audit (generated)",
        "",
        "Generated by `scripts/audit_page_data_sources.py`. Flags `data_public`",
        "analyzer pages that render figures with **no** data-source disclosure",
        "(no source/purpose header, illustrative banner, or DATA/EXPORT REQUIRED",
        "label). Cross-references the surface-status tier.",
        "",
        f"- Pages: **{summary['pages']}** · with disclosure: "
        f"**{summary['with_disclosure']}** · importing a real loader: "
        f"**{summary['with_real_loader']}** · **flagged (no disclosure): "
        f"{summary['flagged_no_disclosure']}**",
        f"- By tier: {summary['by_tier']}",
        "",
        "## Flagged — render data, disclose nothing (fix first)",
        "",
        "| Route | File | Tier | Real loader? | Flag |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(flagged, key=lambda x: x["route"]):
        lines.append(f"| `{r['route']}` | {r['file']} | {r['tier']} | "
                     f"{'yes' if r['imports_real_loader'] else 'no'} | {r['flag']} |")
    if not flagged:
        lines.append("| _(none — every data-rendering page discloses its basis)_ | | | | |")
    _MD.write_text("\n".join(lines) + "\n")
    print(f"Audited {len(rows)} pages; {len(flagged)} flagged (no disclosure). "
          f"→ {_JSON.name}, {_MD.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
