#!/usr/bin/env python3
"""Generate served_route_stubs.py — honest placeholder Guide contexts for every
SERVED route not already covered by the palette-derived stubs or manual
contexts.

The registry stubs one PageContext per *palette* route; routes that are served
(``RCMHandler._discover_all_routes``) but absent from the palette returned NO
context ("none"), so the Guide had nothing for them. This emits a
NEEDS_VALIDATION placeholder (tells the assistant NOT to invent specifics) for
each, keyed by route — overlaid first in the registry so palette stubs + manual
contexts still override. Honest coverage, not fabricated detail.

Run: python scripts/gen_served_route_stubs.py
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from rcm_mc.server import RCMHandler
from rcm_mc.assistant.context.discovered_tool_routes import DISCOVERED_TOOL_ROUTES
from rcm_mc.assistant.context.manual_page_contexts import MANUAL_PAGE_CONTEXTS

_OUT = Path(__file__).resolve().parent.parent / "rcm_mc" / "assistant" / "context" / "served_route_stubs.py"
_ACR = {"cms", "hcris", "apm", "aco", "snf", "irf", "ltch", "mssp", "lp", "ic",
        "roi", "ebitda", "qoe", "esg", "hcit", "ma", "rcm", "pe", "gp", "dpi"}


def _title(route: str) -> str:
    parts = route.strip("/").split("/")
    words = re.split(r"[-_]", parts[-1] or parts[0])
    return " ".join(w.upper() if w.lower() in _ACR else w.capitalize()
                    for w in words if w)


def main() -> int:
    covered = {d.route for d in DISCOVERED_TOOL_ROUTES} | set(MANUAL_PAGE_CONTEXTS)
    served = RCMHandler._discover_all_routes()
    missing = sorted(r for r in served if r not in covered)

    lines = [
        '"""Generated NEEDS_VALIDATION stubs for served routes absent from the',
        "palette/manual contexts — so the Guide has an honest placeholder (and is",
        "told not to invent specifics) for EVERY served route. Generated by",
        "scripts/gen_served_route_stubs.py; overridden by palette stubs + manual",
        "contexts in the registry.",
        '"""',
        "from __future__ import annotations",
        "",
        "from typing import Dict, List, Tuple",
        "",
        "from .generated_page_context_stubs import _stub_for",
        "from .types import PageContext, PageContextCategory",
        "",
        f"# {len(missing)} served routes (generated {datetime.now(timezone.utc).date().isoformat()})",
        "SERVED_ROUTE_NAMES: List[Tuple[str, str]] = [",
    ]
    for r in missing:
        t = _title(r).replace('"', "")
        lines.append(f'    ({r!r}, {t!r}),')
    lines += [
        "]",
        "",
        "SERVED_ROUTE_STUBS: Dict[str, PageContext] = {",
        "    route: _stub_for(route, title, PageContextCategory.UNKNOWN)",
        "    for route, title in SERVED_ROUTE_NAMES",
        "}",
    ]
    _OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(missing)} served-route stubs → {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
