#!/usr/bin/env python3
"""Generate docs/TOOLS_PAGE_ROUTE_AUDIT.md — every /tools route classified.

Combines the live route catalog (``RCMHandler._discover_all_routes``), the
surface-status tier (``classify_surface``), and the data_public disclosure scan
(``data_quality/page_data_source_audit.json`` if present) into a single audit
table: route · tier · data status · discloses? · real loader? · action.

Run: python scripts/audit_page_data_sources.py && python scripts/gen_tools_route_audit.py
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from rcm_mc.diligence.surface_status import classify_surface
from rcm_mc.server import RCMHandler

_ROOT = Path(__file__).resolve().parent.parent
_AUDIT = _ROOT / "data_quality" / "page_data_source_audit.json"
_OUT = _ROOT / "docs" / "TOOLS_PAGE_ROUTE_AUDIT.md"

_TIER_STATUS = {
    "green": "real data (live/public/user)",
    "navy": "calculator on your inputs",
    "yellow": "illustrative seed corpus",
    "red": "synthetic / hardcoded",
}


def main() -> int:
    routes = RCMHandler._discover_all_routes()
    disc = {}
    if _AUDIT.exists():
        for p in json.loads(_AUDIT.read_text()).get("pages", []):
            disc[p["route"]] = p
    by_tier = {"red": [], "yellow": [], "navy": [], "green": []}
    for r in routes:
        c = classify_surface(r)
        by_tier.setdefault(c["tier"], []).append(r)

    today = datetime.now(timezone.utc).date().isoformat()
    lines = [
        "# /tools Page Route Audit (generated)",
        "",
        f"Generated by `scripts/gen_tools_route_audit.py` on {today} over "
        f"{len(routes)} `/tools`-surfaced routes. Tier from "
        "`surface_status.classify_surface`; disclosure from the page audit.",
        "",
        "| Tier | Count |",
        "|---|---|",
    ]
    for t in ("green", "navy", "yellow", "red"):
        lines.append(f"| {t} | {len(by_tier.get(t, []))} |")
    lines.append("")
    for t in ("red", "yellow", "navy", "green"):
        rs = sorted(by_tier.get(t, []))
        lines.append(f"\n## {t.upper()} — {_TIER_STATUS[t]} ({len(rs)})\n")
        lines.append("| Route | Discloses? | Real loader? | Action |")
        lines.append("|---|---|---|---|")
        for r in rs:
            d = disc.get(r)
            if d is None:
                disc_s, loader_s, action = "n/a (not data_public)", "—", "verify in route audit"
            else:
                disc_s = "yes" if d["has_disclosure"] else "**NO**"
                loader_s = "yes" if d["imports_real_loader"] else "no"
                action = ("add source/illustrative label" if d["flag"]
                          else ("wire real data when source exists" if t in ("yellow", "red")
                                else "ok"))
            lines.append(f"| `{r}` | {disc_s} | {loader_s} | {action} |")
    _OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(routes)} routes → {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
