#!/usr/bin/env python3
"""Generate docs/reports/FULL_ROUTE_DATA_GUIDE_AUDIT.md (Queue 7).

One master audit row per discovered route combining: tier (surface_status),
data-source disclosure (page audit, for data_public pages), and Guide
page-context status (DOCUMENTED / inferred / none) + a suggested action.

Run: python scripts/audit_page_data_sources.py && \
     python scripts/gen_full_route_data_guide_audit.py
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from rcm_mc.diligence.surface_status import classify_surface
from rcm_mc.server import RCMHandler
from rcm_mc.assistant.context.get_page_context import get_page_context

_ROOT = Path(__file__).resolve().parent.parent
_AUDIT = _ROOT / "data_quality" / "page_data_source_audit.json"
_OUT = _ROOT / "docs" / "reports" / "FULL_ROUTE_DATA_GUIDE_AUDIT.md"


def _guide_status(route: str) -> str:
    try:
        ctx = get_page_context(route).context
        if ctx is None:
            return "none"
        return ctx.source_confidence.name  # DOCUMENTED / INFERRED_FROM_PAGE / ...
    except Exception:
        return "none"


def main() -> int:
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    routes = RCMHandler._discover_all_routes()
    disc = {}
    if _AUDIT.exists():
        for p in json.loads(_AUDIT.read_text()).get("pages", []):
            disc[p["route"]] = p

    rows = []
    counts = {"documented_guide": 0, "inferred_guide": 0, "no_guide": 0,
              "data_disclosed": 0, "data_pages": 0}
    for r in sorted(routes):
        tier = classify_surface(r)["tier"]
        g = _guide_status(r)
        d = disc.get(r)
        if d is not None:
            counts["data_pages"] += 1
            if d["has_disclosure"] or d["imports_real_loader"]:
                counts["data_disclosed"] += 1
            disc_s = "yes" if (d["has_disclosure"] or d["imports_real_loader"]) else "NO"
        else:
            disc_s = "n/a"
        if g == "DOCUMENTED":
            counts["documented_guide"] += 1
        elif g == "none":
            counts["no_guide"] += 1
        else:
            counts["inferred_guide"] += 1
        action = []
        if disc_s == "NO":
            action.append("add source label")
        if g == "none":
            action.append("add Guide ctx")
        rows.append((r, tier, disc_s, g, "; ".join(action) or "ok"))

    today = datetime.now(timezone.utc).date().isoformat()
    lines = [
        "# Full Route × Data × Guide Audit (generated)",
        "",
        f"Generated by `scripts/gen_full_route_data_guide_audit.py` on {today} "
        f"over {len(routes)} routes. Combines surface-status tier, data-source "
        "disclosure, and Guide page-context status.",
        "",
        f"- Guide: **{counts['documented_guide']} documented**, "
        f"{counts['inferred_guide']} inferred, {counts['no_guide']} none.",
        f"- Data pages: **{counts['data_disclosed']}/{counts['data_pages']} "
        "disclosed by label or real-loader** (0 undisclosed is the invariant).",
        "",
        "| Route | Tier | Data disclosed | Guide ctx | Action |",
        "|---|---|---|---|---|",
    ]
    for r, tier, disc_s, g, action in rows:
        lines.append(f"| `{r}` | {tier} | {disc_s} | {g} | {action} |")
    _OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(routes)} routes (guide: {counts['documented_guide']} doc / "
          f"{counts['inferred_guide']} inf / {counts['no_guide']} none) → {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
