#!/usr/bin/env python3
"""Regenerate docs/PEDESK_DILIGENCE_SURFACE_STATUS.md from the single source of
truth (``rcm_mc/diligence/surface_status.py``) + the live route catalog
(``RCMHandler._discover_all_routes``).

Keeping the doc generated (not hand-edited) means it can never drift from the
``/tools`` circles — both read the same ``classify_surface``. Re-run after any
reclassification:  python scripts/gen_surface_status_doc.py
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from rcm_mc.diligence.surface_status import classify_surface, TIERS
from rcm_mc.server import RCMHandler

_OUT = Path(__file__).resolve().parent.parent / "docs" / "PEDESK_DILIGENCE_SURFACE_STATUS.md"

_CIRCLE = {"green": "🟢", "navy": "🔵", "yellow": "🟡", "red": "🔴"}
# worst-first
_ORDER = ["red", "yellow", "navy", "green"]
_HEADING = {
    "red": "RED 🔴 — entirely synthetic (highest priority to fix)",
    "yellow": "YELLOW 🟡 — realistic figures on the illustrative seed corpus",
    "navy": "NAVY 🔵 — diligence calculator (computes off your inputs)",
    "green": "GREEN 🟢 — real CMS/public or your own deal/system data",
}
_LEGEND_MEANING = {
    "green": "Real CMS/public or your own deal/system data",
    "navy": "Diligence calculator — computes off your inputs",
    "yellow": "Realistic figures on the illustrative seed corpus",
    "red": "Entirely synthetic / hardcoded values",
}


def main() -> int:
    routes = RCMHandler._discover_all_routes()
    buckets: dict[str, list[tuple[str, str]]] = {t: [] for t in _ORDER}
    for r in routes:
        c = classify_surface(r)
        buckets[c["tier"]].append((r, c["status_label"]))

    counts = {t: len(buckets[t]) for t in _ORDER}
    today = datetime.now(timezone.utc).date().isoformat()

    lines = [
        "# PEdesk diligence surface status",
        "",
        f"Data-honesty status for every PEdesk surface. Source of truth: "
        f"`rcm_mc/diligence/surface_status.py` (the `/tools` index renders the "
        f"matching circle). Generated by `scripts/gen_surface_status_doc.py` — "
        f"do not hand-edit; reclassify in the source and re-run. "
        f"Last generated {today} over {len(routes)} surfaces.",
        "",
        "| Tier | Circle | Meaning | Count |",
        "|---|---|---|---|",
    ]
    for t in ["green", "navy", "yellow", "red"]:
        lines.append(f"| {t.upper()} | {_CIRCLE[t]} | {_LEGEND_MEANING[t]} | {counts[t]} |")
    lines.append("")

    for t in _ORDER:
        lines.append(f"\n## {_HEADING[t]}  ({counts[t]})\n")
        lines.append("| Route | Status |")
        lines.append("|---|---|")
        for route, label in sorted(buckets[t]):
            lines.append(f"| `{route}` | {_CIRCLE[t]} {label} |")

    _OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(routes)} surfaces "
          f"(red {counts['red']}, yellow {counts['yellow']}, "
          f"navy {counts['navy']}, green {counts['green']}) → {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
