"""Manifest-freshness guard — the surface-ranking manifest can never go stale.

`rcm_mc/ui/_surface_rankings.py` is AUTO-GENERATED by `scripts/rank_surfaces.py`
and consumed at runtime by the nav-bar backfill and the `/best/<section>`
catalogs. It is a checked-in generated file, so it silently drifts when a page
ships without anyone re-running the generator — which is exactly how a body of
real work became "ghost pages" (rendered, but in no browsable surface). The
2026-06-15 ghost-page audit found 11 recent pages stranded this way.

This guard regenerates the rankings in-memory from the same single source of
truth (`build_rankings()`) and asserts the committed manifest matches, so a new
route is forced into the catalogs in the same PR that adds it. If this fails,
the fix is mechanical:  python scripts/rank_surfaces.py  (then commit the diff).
"""
from __future__ import annotations

import unittest
from collections import defaultdict

# Mirror _write_manifest's section order so the comparison reconstructs the
# exact grouping the generator emits.
_ORDER = ["source", "pipeline", "diligence", "library", "research",
          "portfolio", "home", "uncategorized"]


class ManifestFreshness(unittest.TestCase):
    def test_committed_manifest_matches_generator(self):
        from scripts.rank_surfaces import build_rankings
        from rcm_mc.ui._surface_rankings import RANKINGS

        rows = build_rankings()
        by_section: dict[str, list[str]] = defaultdict(list)
        for r in rows:
            by_section[r["section"]].append(r["route"])
        expected = {sec: by_section[sec] for sec in _ORDER if by_section.get(sec)}
        committed = {sec: [r["route"] for r in rs] for sec, rs in RANKINGS.items()}

        self.assertEqual(
            set(expected), set(committed),
            msg="surface-ranking manifest has different sections than the "
                "generator — run `python scripts/rank_surfaces.py` and commit.")
        for sec in expected:
            self.assertEqual(
                expected[sec], committed.get(sec),
                msg=f"surface-ranking manifest is STALE for section {sec!r}: "
                    f"the generator would produce a different route list. A "
                    f"page likely shipped without regenerating the manifest, so "
                    f"it is a ghost (in no /best/<section> or nav backfill). "
                    f"Fix: `python scripts/rank_surfaces.py` then commit the "
                    f"diff to rcm_mc/ui/_surface_rankings.py.")


if __name__ == "__main__":
    unittest.main()
