"""Canonical Open Payments tables + an idempotent SQLite store.

Eleven normalization targets: the dataset catalog, nine curated 2024
payment / profile / summary tables, and the generic on-demand JSON rows
table. The curated column sets are **snapshots of the live datastore
column names** (sampled 2026-07-06 via
``/api/1/datastore/query/{uuid}/0?limit=2``). The DKAN engine already
serves lowercase snake_case names, so the columns below are byte-for-byte
the native field names — no case mapping is applied (that IS the
documented normalization: identity). The detail payment files are wide
on purpose (91 general / 252 research columns); the width is the value,
so every native column is kept.

Repeating blocks (five drug/device product slots on the detail files,
five principal-investigator slots on research) are generated by the
``_product_block`` / ``_pi_block`` helpers so the patterned live layout
stays readable and the exact live ordering is preserved.

Storage is SQLite to match the rest of RCM-MC (no pandas/duckdb in the
runtime). Every write is an **upsert keyed by the native id** so a
re-run never double-counts — idempotency is enforced at the table, not
the caller. All SQL is parameterised; the column lists below are the
only interpolated identifiers and they are module constants, never user
input. Everything is stored TEXT (numeric-looking payment amounts too):
SQLite is dynamically typed and the uniform ``/v1/query`` layer casts
explicitly where it needs numbers.
"""
from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Sequence, Tuple


@dataclass(frozen=True)
class TableDef:
    name: str
    pk: str
    columns: Tuple[str, ...]   # all columns incl. pk, in order

    def create_sql(self) -> str:
        cols = []
        for c in self.columns:
            if c == self.pk:
                cols.append(f"{c} TEXT PRIMARY KEY")
            else:
                cols.append(f"{c} TEXT")
        return f"CREATE TABLE IF NOT EXISTS {self.name} (\n  " + ",\n  ".join(cols) + "\n)"

    def upsert_sql(self) -> str:
        cols = ", ".join(self.columns)
        placeholders = ", ".join("?" for _ in self.columns)
        updates = ", ".join(
            f"{c}=excluded.{c}" for c in self.columns if c != self.pk
        )
        return (
            f"INSERT INTO {self.name} ({cols}) VALUES ({placeholders}) "
            f"ON CONFLICT({self.pk}) DO UPDATE SET {updates}"
        )


# ── live-layout block helpers ─────────────────────────────────────────
def _product_block(i: int) -> Tuple[str, ...]:
    """One of the five associated drug/device product slots on the
    general + research detail files (live order preserved)."""
    return (
        f"covered_or_noncovered_indicator_{i}",
        f"indicate_drug_or_biological_or_device_or_medical_supply_{i}",
        f"product_category_or_therapeutic_area_{i}",
        f"name_of_drug_or_biological_or_device_or_medical_supply_{i}",
        f"associated_drug_or_biological_ndc_{i}",
        f"associated_device_or_medical_supply_pdi_{i}",
    )


def _pi_block(i: int) -> Tuple[str, ...]:
    """One of the five principal-investigator slots on the research
    detail file. NOTE the live quirk: ``primary_type_N``/``specialty_N``
    use an underscore before the index but ``license_state_codeN`` does
    not — preserved verbatim."""
    p = f"principal_investigator_{i}"
    return (
        f"{p}_covered_recipient_type", f"{p}_profile_id", f"{p}_npi",
        f"{p}_first_name", f"{p}_middle_name", f"{p}_last_name",
        f"{p}_name_suffix",
        f"{p}_business_street_address_line1",
        f"{p}_business_street_address_line2",
        f"{p}_city", f"{p}_state", f"{p}_zip_code", f"{p}_country",
        f"{p}_province", f"{p}_postal_code",
        *(f"{p}_primary_type_{j}" for j in range(1, 7)),
        *(f"{p}_specialty_{j}" for j in range(1, 7)),
        *(f"{p}_license_state_code{j}" for j in range(1, 6)),
    )


# Shared sub-blocks across the three detail files (live order).
_RECIPIENT_ADDRESS = (
    "recipient_primary_business_street_address_line1",
    "recipient_primary_business_street_address_line2",
    "recipient_city", "recipient_state", "recipient_zip_code",
    "recipient_country", "recipient_province", "recipient_postal_code",
)
_COVERED_RECIPIENT_TYPES = (
    *(f"covered_recipient_primary_type_{j}" for j in range(1, 7)),
    *(f"covered_recipient_specialty_{j}" for j in range(1, 7)),
    *(f"covered_recipient_license_state_code{j}" for j in range(1, 6)),
)
_MANUFACTURER = (
    "submitting_applicable_manufacturer_or_applicable_gpo_name",
    "applicable_manufacturer_or_applicable_gpo_making_payment_id",
    "applicable_manufacturer_or_applicable_gpo_making_payment_name",
    "applicable_manufacturer_or_applicable_gpo_making_payment_state",
    "applicable_manufacturer_or_applicable_gpo_making_payment_country",
)

# ── native column snapshots (live 2026-07-06) ─────────────────────────
GENERAL_PAYMENT_COLUMNS: Tuple[str, ...] = (
    "change_type", "covered_recipient_type",
    "teaching_hospital_ccn", "teaching_hospital_id", "teaching_hospital_name",
    "covered_recipient_profile_id", "covered_recipient_npi",
    "covered_recipient_first_name", "covered_recipient_middle_name",
    "covered_recipient_last_name", "covered_recipient_name_suffix",
    *_RECIPIENT_ADDRESS,
    *_COVERED_RECIPIENT_TYPES,
    *_MANUFACTURER,
    "total_amount_of_payment_usdollars", "date_of_payment",
    "number_of_payments_included_in_total_amount",
    "form_of_payment_or_transfer_of_value",
    "nature_of_payment_or_transfer_of_value",
    "city_of_travel", "state_of_travel", "country_of_travel",
    "physician_ownership_indicator",
    "third_party_payment_recipient_indicator",
    "name_of_third_party_entity_receiving_payment_or_transfer_of_ccfc",
    "charity_indicator", "third_party_equals_covered_recipient_indicator",
    "contextual_information", "delay_in_publication_indicator",
    "record_id", "dispute_status_for_publication",
    "related_product_indicator",
    *_product_block(1), *_product_block(2), *_product_block(3),
    *_product_block(4), *_product_block(5),
    "program_year", "payment_publication_date",
)

RESEARCH_PAYMENT_COLUMNS: Tuple[str, ...] = (
    "change_type", "covered_recipient_type", "noncovered_recipient_entity_name",
    "teaching_hospital_ccn", "teaching_hospital_id", "teaching_hospital_name",
    "covered_recipient_profile_id", "covered_recipient_npi",
    "covered_recipient_first_name", "covered_recipient_middle_name",
    "covered_recipient_last_name", "covered_recipient_name_suffix",
    *_RECIPIENT_ADDRESS,
    *_COVERED_RECIPIENT_TYPES,
    *_pi_block(1), *_pi_block(2), *_pi_block(3), *_pi_block(4), *_pi_block(5),
    *_MANUFACTURER,
    "related_product_indicator",
    *_product_block(1), *_product_block(2), *_product_block(3),
    *_product_block(4), *_product_block(5),
    "total_amount_of_payment_usdollars", "date_of_payment",
    "form_of_payment_or_transfer_of_value",
    *(f"expenditure_category{j}" for j in range(1, 7)),
    "preclinical_research_indicator", "delay_in_publication_indicator",
    "name_of_study", "dispute_status_for_publication",
    "record_id", "program_year", "payment_publication_date",
    "clinicaltrials_gov_identifier", "research_information_link",
    "context_of_research",
)

OWNERSHIP_PAYMENT_COLUMNS: Tuple[str, ...] = (
    "change_type", "physician_profile_id", "physician_npi",
    "physician_first_name", "physician_middle_name", "physician_last_name",
    "physician_name_suffix",
    *_RECIPIENT_ADDRESS,
    "physician_primary_type", "physician_specialty",
    "record_id", "program_year",
    "total_amount_invested_usdollars", "value_of_interest",
    "terms_of_interest",
    *_MANUFACTURER,
    "dispute_status_for_publication",
    "interest_held_by_physician_or_an_immediate_family_member",
    "payment_publication_date",
)

PROFILE_COLUMNS: Tuple[str, ...] = (
    "entity_id", "entity_provider_type", "entity_npi", "entity_alternate_id",
    "entity_type", "entity_name",
    *(f"entity_alternate_name{j}" for j in range(1, 6)),
    "entity_address_line_1", "entity_address_line_2",
    "entity_city", "entity_state", "entity_zipcode",
    "entity_country_name", "entity_province_name",
    "entity_specialty", "location",
)

PROFILE_SUPPLEMENT_COLUMNS: Tuple[str, ...] = (
    "covered_recipient_profile_type", "covered_recipient_profile_id",
    "associated_covered_recipient_profile_id_1",
    "associated_covered_recipient_profile_id_2",
    "covered_recipient_npi",
    "covered_recipient_profile_first_name",
    "covered_recipient_profile_middle_name",
    "covered_recipient_profile_last_name",
    "covered_recipient_profile_suffix",
    "covered_recipient_profile_alternate_first_name",
    "covered_recipient_profile_alternate_middle_name",
    "covered_recipient_profile_alternate_last_name",
    "covered_recipient_profile_alternate_suffix",
    "covered_recipient_profile_address_line_1",
    "covered_recipient_profile_address_line_2",
    "covered_recipient_profile_city", "covered_recipient_profile_state",
    "covered_recipient_profile_zipcode",
    "covered_recipient_profile_country_name",
    "covered_recipient_profile_province_name",
    "covered_recipient_profile_primary_specialty",
    *(f"covered_recipient_profile_ops_taxonomy_{j}" for j in range(1, 7)),
    *(f"covered_recipient_profile_license_state_code_{j}" for j in range(1, 6)),
)

SUMMARY_DASHBOARD_COLUMNS: Tuple[str, ...] = (
    "dashboard_row_number", "data_metrics",
    "py_2019", "py_2020", "py_2021", "py_2022", "py_2023", "py_2024",
    "py_2025", "total",
)

PAYMENTS_BY_RECIPIENT_NATURE_COLUMNS: Tuple[str, ...] = (
    "recipient_id", "recipient_type", "covered_recipient_npi",
    "covered_recipient_profile_first_name",
    "covered_recipient_profile_middle_name",
    "covered_recipient_profile_last_name",
    "teaching_hospital_name", "nature_of_payment_type_code",
    "number_of_transaction", "total_amount",
)

PAYMENTS_BY_ENTITY_NATURE_COLUMNS: Tuple[str, ...] = (
    "amgpo_id", "nature_of_payment_type_code", "number_of_transaction",
    "total_amount", "amgpo_name",
)

STATE_PAYMENT_TOTALS_COLUMNS: Tuple[str, ...] = (
    "country_code", "country_name", "state_code", "state_name",
    "nature_of_payment", "recipient_type", "program_year",
    "total_number_of_physicians",
    "total_number_of_non_physician_practitioners",
    "total_number_of_teaching_hospitals",
    "total_payment_amount_physician",
    "total_payment_amount_non_physician_practitioner",
    "total_payment_amount_teaching_hospital",
    "mean_total_payment_amount_physician",
    "mean_total_payment_amount_non_physician_practitioner",
    "mean_total_payment_amount_teaching_hospital",
    "median_total_payment_amount_physician",
    "median_total_payment_amount_non_physician_practitioner",
    "median_total_payment_amount_teaching_hospital",
    "total_payment_count_physician",
    "total_payment_count_non_physician_practitioner",
    "total_payment_count_teaching_hospital",
    "mean_total_payment_count_physician",
    "mean_total_payment_count_non_physician_practitioner",
    "mean_total_payment_count_teaching_hospital",
    "median_total_payment_count_physician",
    "median_total_payment_count_non_physician_practitioner",
    "median_total_payment_count_teaching_hospital",
)

# Catalog columns are normalized (flattened) from the DKAN metastore
# entry shape in normalize.py; the live catalog carries no
# accrualPeriodicity or landingPage — landing_page/api_url are composed
# from the identifier instead.
CATALOG_COLUMNS: Tuple[str, ...] = (
    "identifier", "title", "description", "theme", "keyword",
    "access_level", "issued", "modified", "temporal",
    "distribution_title", "media_type", "format", "download_url",
    "described_by", "n_distributions", "api_url", "landing_page",
    "contact_name", "contact_email", "publisher", "license",
    "bureau_code", "program_code", "data_quality",
)

# ── Canonical schema ──────────────────────────────────────────────────
_META = ("source_endpoint", "ingested_at")

TABLES: Dict[str, TableDef] = {
    "open_payments_catalog": TableDef(
        "open_payments_catalog", "identifier",
        (*CATALOG_COLUMNS, *_META),
    ),
    "op_general_payment": TableDef(
        "op_general_payment", "record_id",
        (*GENERAL_PAYMENT_COLUMNS, *_META),
    ),
    "op_research_payment": TableDef(
        "op_research_payment", "record_id",
        (*RESEARCH_PAYMENT_COLUMNS, *_META),
    ),
    "op_ownership_payment": TableDef(
        "op_ownership_payment", "record_id",
        (*OWNERSHIP_PAYMENT_COLUMNS, *_META),
    ),
    "op_profile": TableDef(
        "op_profile", "entity_id",
        (*PROFILE_COLUMNS, *_META),
    ),
    "op_profile_supplement": TableDef(
        "op_profile_supplement", "covered_recipient_profile_id",
        (*PROFILE_SUPPLEMENT_COLUMNS, *_META),
    ),
    "op_summary_dashboard": TableDef(
        "op_summary_dashboard", "dashboard_row_number",
        (*SUMMARY_DASHBOARD_COLUMNS, *_META),
    ),
    "op_payments_by_recipient_nature": TableDef(
        "op_payments_by_recipient_nature", "recipient_nature_key",
        ("recipient_nature_key",
         *PAYMENTS_BY_RECIPIENT_NATURE_COLUMNS, *_META),
    ),
    "op_payments_by_entity_nature": TableDef(
        "op_payments_by_entity_nature", "entity_nature_key",
        ("entity_nature_key", *PAYMENTS_BY_ENTITY_NATURE_COLUMNS, *_META),
    ),
    "op_state_payment_totals": TableDef(
        "op_state_payment_totals", "state_totals_key",
        ("state_totals_key", *STATE_PAYMENT_TOTALS_COLUMNS, *_META),
    ),
    # Generic on-demand rows: any catalog dataset by UUID. row_idx is
    # zero-padded in normalize.py so TEXT ordering matches numeric order.
    "open_payments_rows": TableDef(
        "open_payments_rows", "row_key",
        ("row_key", "dataset_key", "row_idx", "row_json", "fetched_at",
         *_META),
    ),
}

CANONICAL_TABLES: Tuple[str, ...] = tuple(TABLES)


class OpenPaymentsStore:
    """Thin SQLite wrapper: schema bootstrap + idempotent batch upsert.

    The only module that talks to the Open Payments SQLite file
    directly, mirroring the RCM-MC convention that a single store owns
    the connection.
    """

    def __init__(self, db_path: str = ":memory:") -> None:
        self.db_path = db_path
        # check_same_thread=False so the read-only HTTP surface
        # (ThreadingHTTPServer, one worker thread per request) can share the
        # connection. Writes only happen single-threaded in the pipeline, so
        # this does not introduce a write race; WAL + busy_timeout cover the
        # rest.
        self.conn = sqlite3.connect(db_path, check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.execute("PRAGMA busy_timeout=5000")
        self.ensure_schema()

    def ensure_schema(self) -> None:
        cur = self.conn.cursor()
        for tdef in TABLES.values():
            cur.execute(tdef.create_sql())
        # Helpful secondary indexes for the /v1/query + lookup paths:
        # NPI fan-outs, state slicing, and manufacturer-name LIKEs.
        cur.execute("CREATE INDEX IF NOT EXISTS ix_ogp_npi "
                    "ON op_general_payment(covered_recipient_npi)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_ogp_state "
                    "ON op_general_payment(recipient_state)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_ogp_manufacturer "
                    "ON op_general_payment("
                    "applicable_manufacturer_or_applicable_gpo_making_payment_name)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_orp_npi "
                    "ON op_research_payment(covered_recipient_npi)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_oop_npi "
                    "ON op_ownership_payment(physician_npi)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_opr_npi "
                    "ON op_profile(entity_npi)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_ops_npi "
                    "ON op_profile_supplement(covered_recipient_npi)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_obr_npi "
                    "ON op_payments_by_recipient_nature(covered_recipient_npi)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_ost_state "
                    "ON op_state_payment_totals(state_code)")
        cur.execute("CREATE INDEX IF NOT EXISTS ix_opr_dataset "
                    "ON open_payments_rows(dataset_key)")
        self.conn.commit()

    def upsert(self, table: str, rows: Sequence[Dict[str, Any]]) -> int:
        """Upsert canonical rows keyed by the table's native PK.

        Rows are dicts of column→value; missing columns default to NULL,
        extra keys are ignored. Returns the number of rows written.
        """
        if not rows:
            return 0
        tdef = TABLES[table]
        now = _utc_now()
        sql = tdef.upsert_sql()
        params: List[Tuple[Any, ...]] = []
        for r in rows:
            r = dict(r)
            r.setdefault("ingested_at", now)
            params.append(tuple(_coerce(r.get(c)) for c in tdef.columns))
        with self.conn:  # implicit BEGIN/COMMIT, atomic
            self.conn.executemany(sql, params)
        return len(params)

    def replace_slice(self, table: str, dataset_key: str,
                      rows: Sequence[Dict[str, Any]], *,
                      slice_sig: str = "") -> int:
        """Atomically replace ONE dataset's slice of a shared generic table.

        A re-fetch that returns fewer rows than the previous pull would,
        under plain upserts, strand the earlier pull's trailing
        ``row_idx`` rows — served intermixed with fresh rows and counted
        by every surface, with nothing flagging the mixed vintages. One
        transaction deletes exactly the slice being re-pulled and writes
        the fresh rows (mirroring ``oig_leie``'s replace-in-transaction
        semantics), so a reader never observes a half-replaced slice.

        Slice targeting matches the normalizer's key grammar: unfiltered
        pulls key ``{dataset_key}:{row_idx}`` (one colon segment) and
        filtered pulls ``{dataset_key}:{slice_sig}:{row_idx}`` — dataset
        keys are slugs/UUIDs (never contain ``:``) and signatures are
        fixed-length hex, so the LIKE shapes below classify exactly.
        Only meaningful for the generic ``*_rows`` table.
        """
        tdef = TABLES[table]
        for needed in ("row_key", "dataset_key", "row_idx"):
            if needed not in tdef.columns:
                raise ValueError(
                    f"replace_slice targets generic row tables; {table!r} "
                    f"has no {needed!r} column")
        sql = tdef.upsert_sql()
        now = _utc_now()
        params: List[Tuple[Any, ...]] = []
        for r in rows:
            r = dict(r)
            r.setdefault("ingested_at", now)
            params.append(tuple(_coerce(r.get(c)) for c in tdef.columns))
        with self.conn:  # implicit BEGIN/COMMIT, atomic
            if slice_sig:
                self.conn.execute(
                    f"DELETE FROM {tdef.name} WHERE dataset_key = ? "
                    f"AND row_key LIKE ? || ':' || ? || ':%'",
                    (dataset_key, dataset_key, slice_sig))
            else:
                self.conn.execute(
                    f"DELETE FROM {tdef.name} WHERE dataset_key = ? "
                    f"AND row_key LIKE ? || ':%' "
                    f"AND row_key NOT LIKE ? || ':%:%'",
                    (dataset_key, dataset_key, dataset_key))
            if params:
                self.conn.executemany(sql, params)
        return len(params)

    def count(self, table: str, where: str = "", args: Sequence[Any] = ()) -> int:
        sql = f"SELECT COUNT(*) AS n FROM {table}"
        if where:
            sql += f" WHERE {where}"
        row = self.conn.execute(sql, tuple(args)).fetchone()
        return int(row["n"]) if row else 0

    def fetchall(self, sql: str, args: Sequence[Any] = ()) -> List[sqlite3.Row]:
        return list(self.conn.execute(sql, tuple(args)).fetchall())

    def close(self) -> None:
        self.conn.close()


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")


def _coerce(value: Any) -> Any:
    """SQLite stores TEXT; coerce lists/dicts to JSON and scalars to str.

    None stays None (NULL). We keep everything TEXT so the uniform
    ``/v1/query`` layer has one type model — numeric comparisons there
    cast explicitly.
    """
    if value is None:
        return None
    if isinstance(value, (list, dict)):
        import json
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    if isinstance(value, bool):
        return "1" if value else "0"
    return str(value)
