"""AUTO-GENERATED discovered tool routes — the PEdesk route manifest.

Source of truth: ``_DEFAULT_PALETTE_MODULES`` in rcm_mc/ui/_chartis_kit.py
(the Cmd+K / Tools palette, grouped into the seven PEdesk tool groups).
Regenerate with rcm_mc/assistant/context/_generate_discovered.py.
Routes are query-string-normalized and de-duplicated.
"""
from __future__ import annotations

from typing import List

from .types import PageContextCategory, ToolRouteDefinition

_SOURCE_FILE = "rcm_mc/ui/_chartis_kit.py::_DEFAULT_PALETTE_MODULES"

DISCOVERED_TOOL_ROUTES: List[ToolRouteDefinition] = [
    ToolRouteDefinition(
        title='Command Center',
        route='/app',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Day One · Monday brief',
        route='/day-one',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='My Dashboard',
        route='/my/AT',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Alerts',
        route='/alerts',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Escalations',
        route='/escalations',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Watchlist',
        route='/watchlist',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Diligence Questions · ledger',
        route='/diligence/questions',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Activity Feed',
        route='/activity',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deadlines',
        route='/deadlines',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Global Search',
        route='/global-search',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Search',
        route='/search',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Pressure Test',
        route='/pressure',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Query',
        route='/query',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Global Healthcare Markets',
        route='/markets/global',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Pipeline',
        route='/pipeline',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Target Screener',
        route='/target-screener',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Sourcing',
        route='/source',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Hospital Screener',
        route='/screen',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Predictive Screener',
        route='/predictive-screener',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='PE Intelligence',
        route='/pe-intelligence',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Screening',
        route='/deal-screening',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Find Comps',
        route='/find-comps',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Verified Deals · real, sourced healthcare PE deals',
        route='/verified-deals',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Conferences',
        route='/conferences',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='New Deal',
        route='/new-deal',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Pipeline Bridge · deal → EBITDA bridge',
        route='/pipeline/bridge',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Screening Dashboard',
        route='/screening/dashboard',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Profile',
        route='/diligence/deal',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Reimbursement Cliff Calendar · 2026-2029 Medicare/340B rate events by subsector',
        route='/diligence/cliff-calendar',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='PE Intelligence Library · the full ~222-tool analytic toolkit, searchable',
        route='/diligence/pe-library',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title="Run PE Tool on a Deal · run an analytic tool against a real deal's packet",
        route='/diligence/pe-tool',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='PE Reference Libraries · historical failures + partner traps (curated knowledge)',
        route='/diligence/pe-reference',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Thesis Pipeline',
        route='/diligence/thesis-pipeline',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Diligence Checklist',
        route='/diligence/checklist',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Data Activation Center · activate analyses with your data',
        route='/data-activation',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Geographic Intelligence · real-data state analysis hub',
        route='/geo-intel',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='State Comparison · compare states across real public data',
        route='/state-compare',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='State Rankings · rank all states on one real metric',
        route='/state-rankings',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title="State Profile · one state's metrics + national ranks",
        route='/state-profile',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Similar States · states most like a chosen state (real data)',
        route='/state-peers',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title="County Explorer · drill into a state's counties (real ACS data)",
        route='/county-explorer',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Geo Metrics & Sources · what every geo metric measures + coverage',
        route='/geo-metrics',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Metro Markets · real CBSA/metro demographics (Census ACS)',
        route='/metro-markets',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Geo Map · US choropleth of any real state metric',
        route='/geo-map',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Ingestion',
        route='/diligence/ingest',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Benchmarks',
        route='/diligence/benchmarks',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CMS X-Ray · Provider scanner',
        route='/diligence/xray',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='HCRIS X-Ray',
        route='/diligence/hcris-xray',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CIM Cross-Check · Variance engine',
        route='/diligence/cim-crosscheck',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Expert-Call Program · CDD voice-of-customer planner',
        route='/diligence/expert-calls',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CDD Scope · engagement depth levels',
        route='/diligence/cdd-scope',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Roll-Up Builder · Pro-forma platform',
        route='/pipeline/rollup',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Data Quality · Source certification',
        route='/data-quality',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Root Cause',
        route='/diligence/root-cause',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Value Creation',
        route='/diligence/value',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Risk Workbench',
        route='/diligence/risk-workbench',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=['/diligence/risk-workbench?demo=steward'],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Counterfactual',
        route='/diligence/counterfactual',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Compare Deals',
        route='/diligence/compare',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Comparison · packet side-by-side',
        route='/compare',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Diligence Workspace',
        route='/diligence',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Checklist Dashboard',
        route='/diligence-checklist',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Cost Structure',
        route='/cost-structure',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Healthcare Verticals',
        route='/verticals',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Snapshot Ingestion',
        route='/diligence/snapshot',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sponsor Detail',
        route='/diligence/sponsor-detail',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bear Case · downside thesis builder',
        route='/diligence/bear-case',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Comparable Outcomes · per-deal benchmark',
        route='/diligence/comparable-outcomes',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Regulatory Calendar · thesis kill-switches',
        route='/diligence/regulatory-calendar',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bankruptcy Scan',
        route='/screening/bankruptcy-survivor',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='QoE Memo',
        route='/diligence/qoe-memo',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Denial Prediction',
        route='/diligence/denial-prediction',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Autopsy',
        route='/diligence/deal-autopsy',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Physician Attrition',
        route='/diligence/physician-attrition',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Provider Economics',
        route='/diligence/physician-eu',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Management',
        route='/diligence/management',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Monte Carlo',
        route='/diligence/deal-mc',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Exit Timing',
        route='/diligence/exit-timing',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Covenant Stress',
        route='/diligence/covenant-stress',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bridge Audit',
        route='/diligence/bridge-audit',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Payer Stress',
        route='/diligence/payer-stress',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='IC Packet',
        route='/diligence/ic-packet',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Engagements',
        route='/engagements',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sector Intelligence',
        route='/sector-intelligence',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Home Health',
        route='/home-health',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Hospice',
        route='/hospice',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Nursing Homes (SNF)',
        route='/nursing-homes',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Dialysis Facilities',
        route='/dialysis',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Inpatient Rehab (IRF)',
        route='/inpatient-rehab',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Long-Term Care Hospitals (LTCH)',
        route='/long-term-care-hospital',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Library (licensed)',
        route='/deal-library',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deals Library',
        route='/library',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deals Library (alt)',
        route='/deals-library',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Methodology',
        route='/methodology',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Metric Glossary',
        route='/metric-glossary',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='RCM Benchmarks',
        route='/rcm-benchmarks',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Data Catalog',
        route='/data',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Comparables',
        route='/comparables',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Rates',
        route='/market-rates',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Data · State (CA)',
        route='/market-data/state/CA',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='HFMA KPI Benchmarks',
        route='/benchmarks',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CMS Data Sources',
        route='/cms-sources',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CMS Public Data Browser',
        route='/cms-data-browser',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Public Data Catalog',
        route='/data/catalog',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Library — Multiples',
        route='/deal-library/comps',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Library — Sponsors',
        route='/deal-library/sponsors',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Data',
        route='/market-data',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Data Map',
        route='/market-data/map',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Methodology — Calculations',
        route='/methodology/calculations',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Module Index',
        route='/module-index',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='News',
        route='/news',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Research Hub',
        route='/research',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Industry Intelligence',
        route='/industry',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Intel · Geographic',
        route='/market-intel/geo',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Notes',
        route='/notes',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sector Momentum',
        route='/sector-momentum',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='IRR Dispersion',
        route='/irr-dispersion',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Hold Analysis',
        route='/hold-analysis',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Comparable Outcomes',
        route='/comparable-outcomes',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='TAM / SAM Builder',
        route='/diligence/tam-sam',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Texas Infusion Market · TAM/SAM + concentration + metro ranking',
        route='/diligence/texas-infusion',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Infusion Market Scan · every state ranked for an infusion roll-up',
        route='/diligence/infusion-markets',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Visuals · graphics toolkit hub (charts, maps, exhibits)',
        route='/visuals',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Further Analysis · Tableau-style data explorer over CMS/CDC/Census/labor/market datasets',
        route='/further-analysis',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Cross-Dataset Analysis · correlate any two state-grain public datasets (Pearson r, R², scatter + trendline)',
        route='/cross-analysis',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Public Data APIs · catalog of free non-CMS healthcare data sources (NPPES, openFDA, ClinicalTrials, Census, ProPublica 990) by diligence question',
        route='/data-apis',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Excel Mapping · configurable US-state choropleth',
        route='/excel-mapping',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Excel Model Templates · live-formula workbooks (LBO, QoE, NWC peg, CDD market model)',
        route='/excel-templates',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CDD Hub · the commercial-diligence workflow in running order',
        route='/cdd',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Voice of Customer · NPS, KPC gaps, willingness-to-pay',
        route='/voc-survey',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Win/Loss Analyzer · conversion record vs named competitors',
        route='/win-loss',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Medicare Rate Environment · CMS payment updates + blended impact',
        route='/rate-environment',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='MA Penetration · state choropleth + footprint exposure scorer',
        route='/ma-penetration',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Pricing Power · elasticity curves + segment-optimal price moves',
        route='/pricing-power',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Healthcare Labor Market · wage inflation + staffing fragility by role',
        route='/labor-market',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Chart Builder · CDD chart kit (column, waterfall, marimekko, bubble)',
        route='/chart-builder',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Pie Chart · client-ready pie/donut from per-slice values',
        route='/pie-chart',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Exhibit Composer · lay up to 4 charts on one deck slide',
        route='/exhibit',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Saved Charts · reopen named Chart Builder / Exhibit configs',
        route='/charts',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bear Cases',
        route='/bear-cases',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Regulatory Calendar',
        route='/regulatory-calendar',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Intelligence',
        route='/market-intel',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Dataset Backtest',
        route='/corpus-backtest',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Backtest',
        route='/backtest',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Analysis Landing',
        route='/analysis',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Data Intelligence',
        route='/data-intelligence',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Feature Importance',
        route='/models/importance',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Insights',
        route='/insights',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='ML Insights',
        route='/ml-insights',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Model Quality',
        route='/models/quality',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Model Validation',
        route='/model-validation',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Prior Calibration',
        route='/calibration',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Quant Lab',
        route='/quant-lab',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Scenario Explorer',
        route='/scenarios',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Surrogate Model',
        route='/surrogate',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio',
        route='/portfolio',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Map',
        route='/portfolio/map',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Heatmap',
        route='/portfolio/heatmap',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Risk Scan',
        route='/portfolio/risk-scan',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Monitor',
        route='/portfolio/monitor',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Dataset Analytics',
        route='/deal-corpus-analytics',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sponsor Track Record',
        route='/sponsor-track-record',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Payer Intelligence',
        route='/payer-intelligence',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='LP Update',
        route='/lp-update',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Cohorts',
        route='/cohorts',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Fund Learning',
        route='/fund-learning',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Initiatives',
        route='/initiatives',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Owners',
        route='/owners',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Monte Carlo',
        route='/portfolio/monte-carlo',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Regression Analysis',
        route='/portfolio/regression',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Variance Drill-Down',
        route='/variance',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Audit Log',
        route='/audit',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Users',
        route='/users',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Import Deal',
        route='/import',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Exports',
        route='/exports',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Jobs',
        route='/jobs',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Run History',
        route='/runs',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Settings',
        route='/settings',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='AI Settings',
        route='/settings/ai',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Workspace Settings',
        route='/settings/workspace',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Team',
        route='/team',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='CLI Runs',
        route='/cli-runs',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Audit Chain',
        route='/admin/audit-chain',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Data Source Admin',
        route='/admin/data-sources',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Open Data Lab',
        route='/tools/open-data',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Demo Mode',
        route='/demo',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Ops Status',
        route='/ops',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
]
