"""AUTO-GENERATED discovered tool routes — the PEdesk route manifest.

Source of truth: ``_DEFAULT_PALETTE_MODULES`` in rcm_mc/ui/_chartis_kit.py
(the Cmd+K / Tools palette, grouped into the seven PEdesk tool groups).
Regenerate with rcm_mc/assistant/context/_generate_discovered.py.
Routes are query-string-normalized and de-duplicated.
"""
from __future__ import annotations

from typing import List

from .types import PageContextCategory, ToolRouteDefinition

_SOURCE_FILE = "rcm_mc/ui/_chartis_kit.py::_DEFAULT_PALETTE_MODULES"

DISCOVERED_TOOL_ROUTES: List[ToolRouteDefinition] = [
    ToolRouteDefinition(
        title='Command Center',
        route='/app',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Day One · Monday brief',
        route='/day-one',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='My Dashboard',
        route='/my/AT',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Alerts',
        route='/alerts',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Escalations',
        route='/escalations',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Watchlist',
        route='/watchlist',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Diligence Questions · ledger',
        route='/diligence/questions',
        category=PageContextCategory.HOME_OPERATIONS,
        source_group='Home & Operations',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Pipeline',
        route='/pipeline',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Sourcing',
        route='/source',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Hospital Screener',
        route='/screen',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Predictive Screener',
        route='/predictive-screener',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='PE Intelligence',
        route='/pe-intelligence',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Screening',
        route='/deal-screening',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Find Comps',
        route='/find-comps',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Conferences',
        route='/conferences',
        category=PageContextCategory.PIPELINE_SOURCING,
        source_group='Pipeline & Sourcing',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Profile',
        route='/diligence/deal',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Thesis Pipeline',
        route='/diligence/thesis-pipeline',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Diligence Checklist',
        route='/diligence/checklist',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Ingestion',
        route='/diligence/ingest',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Benchmarks',
        route='/diligence/benchmarks',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='HCRIS X-Ray',
        route='/diligence/hcris-xray',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Root Cause',
        route='/diligence/root-cause',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Value Creation',
        route='/diligence/value',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Risk Workbench',
        route='/diligence/risk-workbench',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=['/diligence/risk-workbench?demo=steward'],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Counterfactual',
        route='/diligence/counterfactual',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Compare Deals',
        route='/diligence/compare',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bankruptcy Scan',
        route='/screening/bankruptcy-survivor',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='QoE Memo',
        route='/diligence/qoe-memo',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Denial Prediction',
        route='/diligence/denial-prediction',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Autopsy',
        route='/diligence/deal-autopsy',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Physician Attrition',
        route='/diligence/physician-attrition',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Provider Economics',
        route='/diligence/physician-eu',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Management',
        route='/diligence/management',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deal Monte Carlo',
        route='/diligence/deal-mc',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Exit Timing',
        route='/diligence/exit-timing',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Covenant Stress',
        route='/diligence/covenant-stress',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bridge Audit',
        route='/diligence/bridge-audit',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Payer Stress',
        route='/diligence/payer-stress',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='IC Packet',
        route='/diligence/ic-packet',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Engagements',
        route='/engagements',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sector Intelligence',
        route='/sector-intelligence',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Home Health',
        route='/home-health',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Hospice',
        route='/hospice',
        category=PageContextCategory.DILIGENCE_WORKSPACE,
        source_group='Diligence Workspace',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deals Library',
        route='/library',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Deals Library (alt)',
        route='/deals-library',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Methodology',
        route='/methodology',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Metric Glossary',
        route='/metric-glossary',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='RCM Benchmarks',
        route='/rcm-benchmarks',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Data Catalog',
        route='/data',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Comparables',
        route='/comparables',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Rates',
        route='/market-rates',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Data · State (CA)',
        route='/market-data/state/CA',
        category=PageContextCategory.LIBRARY_REFERENCE,
        source_group='Library & Reference',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Research Hub',
        route='/research',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Notes',
        route='/notes',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sector Momentum',
        route='/sector-momentum',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='IRR Dispersion',
        route='/irr-dispersion',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Hold Analysis',
        route='/hold-analysis',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Comparable Outcomes',
        route='/comparable-outcomes',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Bear Cases',
        route='/bear-cases',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Regulatory Calendar',
        route='/regulatory-calendar',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Market Intelligence',
        route='/market-intel',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Corpus Backtest',
        route='/corpus-backtest',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Backtest',
        route='/backtest',
        category=PageContextCategory.RESEARCH_BACKTESTING,
        source_group='Research & Backtesting',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio',
        route='/portfolio',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Map',
        route='/portfolio/map',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Heatmap',
        route='/portfolio/heatmap',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Risk Scan',
        route='/portfolio/risk-scan',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Monitor',
        route='/portfolio/monitor',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Portfolio Analytics',
        route='/portfolio-analytics',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Sponsor Track Record',
        route='/sponsor-track-record',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Payer Intelligence',
        route='/payer-intelligence',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='LP Update',
        route='/lp-update',
        category=PageContextCategory.PORTFOLIO_LP,
        source_group='Portfolio & LP',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Audit Log',
        route='/audit',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Users',
        route='/users',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
    ToolRouteDefinition(
        title='Import Deal',
        route='/import',
        category=PageContextCategory.ADMIN_SYSTEM,
        source_group='Admin & System',
        is_auto_generated=True,
        aliases=[],
        source_file=_SOURCE_FILE,
    ),
]
