"""PEdesk Guide metric registry — conservative, read-only.

Standard textbook formulas (EV/EBITDA, EBITDA margin, leverage, days in
AR, …) are stated with formula_confidence = ``inferred`` (the formula is
the standard definition; whether PEdesk computes it exactly that way is
inferred, not confirmed from code). Proprietary / model-derived metrics
keep formula = "Needs source documentation." + ``needs_validation``.
No precise formula is invented for anything model-specific.
"""
from __future__ import annotations

from typing import Any, Dict, List

from .types import (
    DataConfidence,
    FormulaConfidence,
    MetricContext,
    SourceConfidence,
)

_NEEDS = "Needs source documentation."
_BASE_NOTES = [
    "PEdesk Guide is read-only and explanatory — it never computes, "
    "re-runs, or alters this metric.",
    "If the exact PEdesk formula or data lineage isn't in this entry, say "
    "it needs source documentation rather than inventing it.",
]

# shorthands
_DOC = FormulaConfidence.DOCUMENTED
_INF = FormulaConfidence.INFERRED
_NV = FormulaConfidence.NEEDS_VALIDATION
_NA = FormulaConfidence.NOT_APPLICABLE
_OBS = DataConfidence.OBSERVED_TARGET_DATA
_PUB = DataConfidence.PUBLIC_BENCHMARK_DATA
_USR = DataConfidence.USER_ENTERED_DATA
_EST = DataConfidence.MODEL_ESTIMATE
_MIX = DataConfidence.MIXED
_UNK = DataConfidence.UNKNOWN


def _m(metric_id: str, label: str, aliases: List[str], definition: str,
       why: str, interp: str, **kw: Any) -> MetricContext:
    d: Dict[str, Any] = dict(
        formula=_NEEDS,
        formula_confidence=_NV,
        source_types=[_UNK],
        common_misread=_NEEDS,
        caveats=[_NEEDS],
        related_metrics=[],
        related_routes=[],
        source_confidence=SourceConfidence.INFERRED_FROM_PAGE,
        data_confidence=_UNK,
    )
    d.update(kw)
    return MetricContext(
        metric_id=metric_id, label=label, aliases=aliases,
        definition=definition, why_it_matters=why,
        diligence_interpretation=interp,
        notes_for_assistant=list(_BASE_NOTES),
        last_reviewed_at="2026-05-22", owner="pedesk-guide", **d,
    )


_METRICS: List[MetricContext] = [
    # ── Financial / PE ──────────────────────────────────────────────
    _m("revenue", "Revenue", ["net revenue", "net patient revenue", "npr", "top line"],
       "Net patient/operating revenue — the cash-realizable top line.",
       "The base every margin and multiple is taken against.",
       "Confirm it's NET (after contractual allowances/bad debt), not gross charges.",
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["revenue_growth", "ebitda_margin"]),
    _m("revenue_growth", "Revenue Growth", ["growth", "topline growth", "yoy growth"],
       "Period-over-period percentage change in revenue.",
       "Organic growth is a core driver of the value-creation thesis.",
       "Separate organic growth from acquired/roll-up growth and rate vs volume.",
       formula="(revenue_t - revenue_{t-1}) / revenue_{t-1}", formula_confidence=_INF,
       source_types=[_OBS], data_confidence=_MIX, related_metrics=["revenue"]),
    _m("ebitda", "EBITDA", ["earnings before interest taxes depreciation amortization"],
       "Operating earnings before interest, taxes, depreciation, amortization.",
       "The cash-earnings base for multiples, leverage, and the bridge.",
       "Reported EBITDA differs from ADJUSTED EBITDA — confirm which is shown.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["adjusted_ebitda", "ebitda_margin", "ev_to_ebitda"]),
    _m("adjusted_ebitda", "Adjusted EBITDA", ["adj ebitda", "pro forma ebitda", "qoe ebitda"],
       "EBITDA after add-backs/normalizations (one-offs, owner comp, pro-forma).",
       "The number deals are actually priced on; QoE exists to vet it.",
       "Every add-back is a negotiation — scrutinize quality and recurrence.",
       source_types=[_OBS, _USR], data_confidence=_MIX,
       caveats=["Add-backs are judgmental; aggressive add-backs inflate value."],
       related_metrics=["ebitda", "ebitda_bridge", "value_creation_opportunity"],
       related_routes=["/diligence/bridge-audit", "/diligence/qoe-memo"]),
    _m("ebitda_margin", "EBITDA Margin", ["margin", "ebitda %"],
       "EBITDA as a percentage of revenue.",
       "Profitability and operating-leverage read; drives margin-expansion theses.",
       "A thin/negative margin can be a turnaround base, not a disqualifier.",
       formula="EBITDA / revenue", formula_confidence=_INF,
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["ebitda", "operating_margin", "revenue"]),
    _m("enterprise_value", "Enterprise Value", ["ev", "tev"],
       "Total enterprise value (equity + net debt) of the business.",
       "The price tag the return math is built on.",
       "EV vs equity value differ by net debt — don't conflate.",
       formula="equity value + net debt (- cash)", formula_confidence=_INF,
       source_types=[_OBS, _EST], data_confidence=_MIX,
       related_metrics=["ev_to_ebitda", "ebitda", "debt"]),
    _m("ev_to_ebitda", "EV / EBITDA", ["ev/ebitda", "entry multiple", "ebitda multiple", "turns"],
       "Enterprise value divided by EBITDA — the headline valuation multiple.",
       "Entry multiple is the single biggest lever on returns.",
       "Compare against the right comp set (sector/size); a 'cheap' multiple may reflect risk.",
       formula="enterprise_value / EBITDA", formula_confidence=_INF,
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["enterprise_value", "ebitda", "exit_multiple"],
       related_routes=["/market-rates", "/comparables"]),
    _m("leverage", "Leverage", ["net leverage", "debt/ebitda", "turns of debt"],
       "Net debt as a multiple of EBITDA.",
       "Sets covenant headroom and amplifies both returns and downside risk.",
       "Compare against covenant max; high leverage on thin EBITDA is fragile.",
       formula="net debt / EBITDA", formula_confidence=_INF,
       source_types=[_OBS, _EST], data_confidence=_MIX,
       related_metrics=["debt", "covenant_cushion", "ebitda"],
       related_routes=["/diligence/covenant-stress"]),
    _m("debt", "Debt", ["total debt", "net debt", "borrowings"],
       "Total/net interest-bearing debt in the capital structure.",
       "The denominator of deleveraging and the covenant base.",
       "Gross vs net debt (net of cash) differ — confirm which.",
       source_types=[_OBS, _EST], data_confidence=_MIX,
       related_metrics=["leverage", "covenant_cushion"]),
    _m("covenant_cushion", "Covenant Cushion", ["covenant headroom", "headroom", "cushion"],
       "How far EBITDA (or leverage) can move before a covenant trips.",
       "Thin cushion means a small EBITDA miss triggers a technical breach.",
       "Cushion shrinks fast under stress — read it against the stress scenarios.",
       source_types=[_EST], data_confidence=_MIX,
       related_metrics=["leverage", "debt", "payer_stress_impact"],
       related_routes=["/diligence/covenant-stress"]),
    _m("moic", "MOIC", ["multiple of invested capital", "multiple", "moc", "cash on cash"],
       "Total value returned to equity divided by equity invested.",
       "The dollar-return headline, less hold-sensitive than IRR.",
       "Gross vs net (after fees/carry) MOIC differ materially.",
       formula="total value to equity / invested equity", formula_confidence=_INF,
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["irr", "exit_multiple", "hold_period"],
       related_routes=["/comparable-outcomes", "/market-rates"]),
    _m("irr", "IRR", ["internal rate of return", "levered irr", "net irr", "gross irr"],
       "Annualized internal rate of return on the equity cash flows.",
       "The time-weighted return; the conventional ~20% PE-healthcare hurdle.",
       "IRR is hold-sensitive and flatters early distributions; pair with MOIC.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["moic", "hold_period"],
       related_routes=["/irr-dispersion"]),
    _m("exit_multiple", "Exit Multiple", ["exit ev/ebitda", "terminal multiple"],
       "The EV/EBITDA assumed at exit.",
       "Multiple expansion/compression is a major returns driver and assumption risk.",
       "An assumed exit multiple above entry must be justified, not assumed.",
       formula="exit enterprise_value / exit EBITDA", formula_confidence=_INF,
       source_types=[_EST, _PUB], data_confidence=_EST,
       related_metrics=["ev_to_ebitda", "moic"]),
    _m("hold_period", "Hold Period", ["hold", "hold years", "holding period"],
       "Years from acquisition close to exit.",
       "Sets the compounding window; PE-healthcare median is ~5-6 years.",
       "Short holds often imply distress or a strategic premium; long holds, a slower thesis.",
       formula="exit date - entry date (years)", formula_confidence=_INF,
       source_types=[_EST], data_confidence=_EST, related_metrics=["irr", "moic"]),
    _m("synergy_estimate", "Synergy Estimate", ["synergies", "cost synergies", "revenue synergies"],
       "Estimated cost/revenue synergies (often in a roll-up/platform thesis).",
       "Synergies underpin multiple-arbitrage and platform value-creation cases.",
       "Synergy estimates are routinely optimistic; weight by execution risk.",
       source_types=[_EST], data_confidence=_EST,
       caveats=["Cross-sell/revenue synergies carry high execution risk."],
       related_metrics=["value_creation_opportunity", "ebitda_bridge"]),
    _m("value_creation_opportunity", "Value Creation Opportunity",
       ["vco", "value opportunity", "ev uplift", "value creation"],
       "Estimated EBITDA/EV upside from the value-creation plan.",
       "Quantifies the upside thesis the deal is underwritten on.",
       "It is a model estimate of POTENTIAL, not realized or guaranteed value.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["ebitda_bridge", "synergy_estimate", "rcm_uplift",
                       "bridge_realization_probability"],
       related_routes=["/diligence/value", "/diligence/bridge-audit"]),
    _m("ebitda_bridge", "EBITDA Bridge", ["bridge", "value bridge", "ebitda walk"],
       "Decomposition of EBITDA from current to a pro-forma/target across "
       "value-creation levers.",
       "Shows where uplift comes from and how much each lever contributes.",
       "Gross lever impact differs from probability-weighted/realized impact.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["adjusted_ebitda", "value_creation_opportunity",
                       "bridge_realization_probability", "rcm_uplift"],
       related_routes=["/diligence/bridge-audit"]),

    # ── Revenue cycle ───────────────────────────────────────────────
    _m("denial_rate", "Denial Rate", ["initial denial rate", "idr", "denials"],
       "Share of submitted claims initially denied by payers.",
       "The starting point of RCM leakage; every downstream lever sits below it.",
       "Initial vs final (post-appeal) denial rate are very different numbers.",
       formula="denied claims / total claims submitted", formula_confidence=_INF,
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["clean_claim_rate", "rcm_uplift", "collections_leakage"],
       related_routes=["/diligence/denial-prediction"]),
    _m("net_collection_rate", "Net Collection Rate", ["ncr", "net collections"],
       "Net payments collected as a share of the amount allowed to be collected.",
       "Measures how much of collectible revenue actually lands.",
       "Net vs gross collection rate differ; net excludes contractual allowances.",
       formula="net payments / (charges - contractual adjustments)", formula_confidence=_INF,
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["gross_collection_rate", "bad_debt_rate"]),
    _m("gross_collection_rate", "Gross Collection Rate", ["gcr", "gross collections"],
       "Payments as a share of gross charges.",
       "A coarse collections read; heavily affected by chargemaster levels.",
       "GCR is distorted by gross-charge inflation — net collection rate is more meaningful.",
       formula="payments / gross charges", formula_confidence=_INF,
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["net_collection_rate"]),
    _m("days_in_ar", "Days in A/R", ["dar", "days sales outstanding", "dso", "ar days"],
       "Average days revenue sits in accounts receivable before collection.",
       "Working-capital and collections-efficiency signal; lower is better.",
       "Spikes can reflect a billing-system change or payer slowdown, not just inefficiency.",
       formula="accounts receivable / (net revenue / 365)", formula_confidence=_INF,
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["net_collection_rate", "collections_leakage"]),
    _m("clean_claim_rate", "Clean Claim Rate", ["ccr", "first-pass rate", "first pass yield"],
       "Share of claims accepted on first submission without rework.",
       "High clean-claim rate means less denial rework and faster cash.",
       "Definitions of 'clean' vary by system; confirm the denominator.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["denial_rate", "rcm_uplift"]),
    _m("bad_debt_rate", "Bad Debt Rate", ["bad debt", "write-off rate"],
       "Share of revenue written off as uncollectible.",
       "Direct leakage; rising self-pay/high-deductible plans push it up.",
       "Bad debt vs charity care are different write-off categories.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["net_collection_rate", "collections_leakage"]),
    _m("underpayment_rate", "Underpayment Rate", ["underpayments", "payer underpayment"],
       "Share/amount of claims paid below the contracted rate.",
       "Recoverable leakage — a common RCM value-creation lever.",
       "Requires contract modeling to detect; absence of a flag isn't absence of underpayment.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["payer_mix", "rcm_uplift"]),
    _m("payer_mix", "Payer Mix", ["payor mix", "payer concentration", "mix"],
       "Distribution of revenue/volume across Medicare, Medicaid, commercial, self-pay.",
       "The single biggest driver of reimbursement and pricing power.",
       "Day-mix vs revenue-mix differ; commercial share drives economics.",
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["medicare_exposure", "medicaid_exposure",
                       "commercial_payer_exposure", "payer_stress_impact"],
       related_routes=["/diligence/payer-stress", "/payer-intelligence"]),
    _m("medicare_exposure", "Medicare Exposure", ["medicare share", "medicare %", "medicare mix"],
       "Share of revenue/volume from Medicare.",
       "Government rates are administratively set; high exposure caps pricing power.",
       "Medicare Advantage vs traditional Medicare behave differently.",
       formula="Medicare revenue (or days) / total", formula_confidence=_INF,
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["payer_mix", "medicaid_exposure"]),
    _m("medicaid_exposure", "Medicaid Exposure", ["medicaid share", "medicaid %", "medicaid mix"],
       "Share of revenue/volume from Medicaid.",
       "Lowest-reimbursing payer; high exposure pressures margins.",
       "Medicaid expansion/redetermination shifts can move this materially.",
       formula="Medicaid revenue (or days) / total", formula_confidence=_INF,
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["payer_mix", "medicare_exposure"]),
    _m("commercial_payer_exposure", "Commercial Payer Exposure",
       ["commercial share", "commercial mix", "commercial %"],
       "Share of revenue/volume from commercial payers.",
       "Highest-reimbursing payer; commercial share is the pricing-power engine.",
       "Single-payer concentration within commercial is a hidden risk.",
       formula="commercial revenue (or days) / total", formula_confidence=_INF,
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["payer_mix", "payer_stress_impact"]),
    _m("rcm_uplift", "RCM Uplift", ["revenue cycle uplift", "rcm opportunity", "rcm ebitda uplift"],
       "Estimated EBITDA improvement from revenue-cycle interventions.",
       "Quantifies the core operational value-creation lever in RCM-led deals.",
       "It is a MODEL ESTIMATE of opportunity, not realized improvement.",
       source_types=[_EST], data_confidence=_EST,
       caveats=["Estimate from current metrics vs benchmark targets; realization is uncertain."],
       related_metrics=["denial_rate", "days_in_ar", "collections_leakage",
                       "ebitda_bridge"],
       related_routes=["/diligence/denial-prediction", "/predictive-screener"]),
    _m("collections_leakage", "Collections Leakage", ["revenue leakage", "collections leakage"],
       "Estimated collectible revenue lost to denials, underpayments, write-offs.",
       "Sizes the recoverable RCM opportunity.",
       "An estimate of recoverable dollars, not a guaranteed recovery.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["denial_rate", "bad_debt_rate", "underpayment_rate",
                       "rcm_uplift"]),

    # ── Provider / physician ────────────────────────────────────────
    _m("physician_attrition", "Physician Attrition", ["provider attrition", "physician turnover", "md turnover"],
       "Rate at which physicians/providers leave the group.",
       "Provider departures destroy revenue and referral relationships fast.",
       "Key-physician concentration matters more than the average rate.",
       source_types=[_OBS, _EST], data_confidence=_MIX,
       related_metrics=["referral_leakage", "panel_size"],
       related_routes=["/diligence/physician-attrition"]),
    _m("provider_productivity", "Provider Productivity", ["productivity", "provider output"],
       "Output per provider (often wRVU- or visit-based).",
       "Drives revenue capacity and the de-novo/expansion case.",
       "Specialty-mix differences make cross-provider comparison tricky.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["wrvu", "panel_size", "provider_contribution_margin"],
       related_routes=["/diligence/physician-eu"]),
    _m("wrvu", "wRVU", ["work rvu", "rvu", "work relative value unit", "wrvus"],
       "Work Relative Value Unit — CMS productivity unit for physician work.",
       "The standard currency for physician productivity and compensation.",
       "wRVU is WORK rvu only — not total RVU (which adds practice-expense/malpractice).",
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["provider_productivity", "compensation_to_collections"],
       related_routes=["/diligence/physician-eu"]),
    _m("compensation_to_collections", "Compensation-to-Collections",
       ["comp to collections", "comp ratio", "comp/collections"],
       "Provider compensation as a share of the collections they generate.",
       "Core physician-economics ratio; high ratios compress group margin.",
       "Benchmarks vary widely by specialty and employment model.",
       formula="provider compensation / provider collections", formula_confidence=_INF,
       source_types=[_OBS, _PUB], data_confidence=_MIX,
       related_metrics=["provider_contribution_margin", "wrvu"],
       related_routes=["/diligence/physician-eu"]),
    _m("provider_contribution_margin", "Provider Contribution Margin",
       ["contribution margin", "provider margin"],
       "Margin a provider contributes after direct costs (incl. comp).",
       "Shows which providers/sites are economically additive.",
       "Allocation of shared/overhead costs changes the answer.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["compensation_to_collections", "provider_productivity"]),
    _m("panel_size", "Panel Size", ["patient panel", "panel"],
       "Number of patients attributed to a provider/practice.",
       "Capacity and continuity proxy; supports volume forecasts.",
       "Attributed vs active panel differ; stale panels overstate capacity.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["provider_productivity", "referral_leakage"]),
    _m("referral_leakage", "Referral Leakage", ["network leakage", "out-of-network referrals"],
       "Share of referrals leaving the network/system.",
       "Lost downstream revenue; a CIN/network value-creation target.",
       "Leakage can be clinically appropriate; not all leakage is recoverable.",
       source_types=[_OBS, _EST], data_confidence=_MIX,
       related_metrics=["panel_size", "physician_attrition"]),
    _m("app_support_ratio", "APP Support Ratio", ["app ratio", "advanced practice ratio", "app:md ratio"],
       "Ratio of advanced practice providers (NP/PA) to physicians.",
       "A care-model/efficiency lever; higher APP leverage can lift margin.",
       "Optimal ratio is specialty- and regulation-dependent.",
       source_types=[_OBS], data_confidence=_MIX,
       related_metrics=["provider_productivity"]),

    # ── Hospital / HCRIS ────────────────────────────────────────────
    _m("bed_count", "Bed Count", ["beds", "licensed beds", "staffed beds"],
       "Number of hospital beds (licensed or staffed).",
       "Scale proxy used for sizing and peer-matching.",
       "Licensed vs staffed vs available beds differ; occupancy uses available.",
       source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["occupancy_rate"], related_routes=["/diligence/hcris-xray"]),
    _m("occupancy_rate", "Occupancy Rate", ["occupancy", "bed occupancy"],
       "Patient days as a share of available bed days.",
       "Capacity-utilization signal for a hospital.",
       "Seasonal and case-mix swings make point-in-time occupancy noisy.",
       formula="patient days / available bed days", formula_confidence=_INF,
       source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["bed_count", "case_mix_index"],
       related_routes=["/diligence/hcris-xray"]),
    _m("cost_per_adjusted_discharge", "Cost per Adjusted Discharge",
       ["cost per discharge", "cpad", "cost/adjusted discharge"],
       "Operating cost per case, adjusted for outpatient volume.",
       "Core hospital efficiency benchmark.",
       "Case-mix and the outpatient adjustment factor drive comparability.",
       source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["labor_cost_ratio", "case_mix_index", "operating_margin"],
       related_routes=["/diligence/hcris-xray"]),
    _m("labor_cost_ratio", "Labor Cost Ratio", ["labor ratio", "labor % of revenue", "labor cost %"],
       "Labor cost as a share of net revenue.",
       "Labor is the largest hospital cost; the key margin lever.",
       "Agency/locum reliance inflates it and is often reducible.",
       formula="labor cost / net revenue", formula_confidence=_INF,
       source_types=[_PUB, _OBS], data_confidence=_MIX,
       related_metrics=["operating_margin", "cost_per_adjusted_discharge"],
       related_routes=["/diligence/hcris-xray"]),
    _m("operating_margin", "Operating Margin", ["op margin", "operating income margin"],
       "Operating income as a share of revenue.",
       "Bottom-line operating health from public filings.",
       "HCRIS operating margin lags real-time and includes filing artifacts.",
       formula="operating income / revenue", formula_confidence=_INF,
       source_types=[_PUB, _OBS], data_confidence=_MIX,
       related_metrics=["ebitda_margin", "labor_cost_ratio"],
       related_routes=["/diligence/hcris-xray"]),
    _m("medicare_cost_report_year", "Medicare Cost Report Year",
       ["hcris year", "cost report year", "filing year"],
       "The fiscal year of the CMS HCRIS cost report being shown.",
       "Tells you how current (or stale) the public hospital data is.",
       "HCRIS filings lag 1-2+ years; always check the year before relying on it.",
       formula_confidence=_NA, source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["operating_margin"], related_routes=["/diligence/hcris-xray"]),
    _m("case_mix_index", "Case Mix Index", ["cmi", "case mix"],
       "Average DRG weight — acuity/complexity of the patient population.",
       "Normalizes cost and reimbursement comparisons for acuity.",
       "Higher CMI legitimately raises cost-per-case; don't read it as inefficiency.",
       source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["cost_per_adjusted_discharge", "occupancy_rate"]),

    # ── Risk / model ────────────────────────────────────────────────
    _m("risk_score", "Risk Score", ["deal risk score", "risk rating"],
       "A composite model score summarizing deal risk.",
       "A fast triage signal across the portfolio/pipeline.",
       "It is a model composite, not a probability — read the components.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["bankruptcy_pattern_match", "confidence_tier"]),
    _m("data_coverage_score", "Data Coverage Score", ["coverage score", "completeness score"],
       "How complete the underlying data is for an analysis.",
       "Low coverage means downstream numbers lean on priors/imputation.",
       "High coverage isn't accuracy — only completeness.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["imputation_share", "confidence_tier"]),
    _m("confidence_tier", "Confidence Tier", ["confidence", "data quality grade", "confidence grade"],
       "A graded confidence level (e.g. A-D) for an estimate or page.",
       "Tells the reader how much weight to put on the figures.",
       "A high tier reflects data quality, not investment merit.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["data_coverage_score", "imputation_share"]),
    _m("imputation_share", "Imputation Share", ["imputed share", "% imputed", "imputation"],
       "Share of inputs filled from priors/benchmarks rather than observed data.",
       "High imputation means the result is benchmark-driven, not target-specific.",
       "More imputation = more reliance on priors over the actual target.",
       source_types=[_EST, _PUB], data_confidence=_EST,
       related_metrics=["data_coverage_score", "model_estimate"]),
    _m("model_estimate", "Model Estimate", ["estimate", "predicted value", "ml estimate"],
       "A value produced by a platform model rather than observed.",
       "Distinguishes computed predictions from reported/observed figures.",
       "Always an estimate with uncertainty — never treat as observed truth.",
       formula_confidence=_NA, source_types=[_EST], data_confidence=_EST,
       related_metrics=["confidence_tier", "benchmark_percentile"]),
    _m("benchmark_percentile", "Benchmark Percentile", ["percentile", "peer percentile", "pXX"],
       "Where a target sits in the distribution of a peer/corpus benchmark.",
       "Contextualizes a raw number against the relevant cohort.",
       "Percentiles over a thin cohort swing on individual deals — check n.",
       source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["model_estimate"],
       related_routes=["/market-rates", "/comparables"]),
    _m("bankruptcy_pattern_match", "Bankruptcy Pattern Match",
       ["distress match", "failure pattern", "bankruptcy similarity"],
       "Similarity of a deal's signature to historical distressed/failed cases.",
       "Flags historical-analogue distress risk the bull case may ignore.",
       "A high match is a prompt to investigate, not a verdict of failure.",
       source_types=[_EST], data_confidence=_MIX,
       related_metrics=["risk_score"],
       related_routes=["/diligence/deal-autopsy", "/screening/bankruptcy-survivor"]),
    _m("payer_stress_impact", "Payer Stress Impact", ["payer stress", "reimbursement stress impact"],
       "Estimated EBITDA/return impact under adverse payer-mix or rate scenarios.",
       "Sizes downside sensitivity to the top healthcare risk driver.",
       "A scenario estimate, not a forecast; depends on the assumed shock.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["payer_mix", "commercial_payer_exposure", "covenant_cushion"],
       related_routes=["/diligence/payer-stress"]),
    _m("bridge_realization_probability", "Bridge Realization Probability",
       ["realization probability", "probability of achievement", "lever probability"],
       "Estimated probability that a value-creation lever / bridge is achieved.",
       "Converts gross lever impact into a probability-weighted, defensible number.",
       "Probabilities are model assumptions — gross vs weighted impact differ a lot.",
       source_types=[_EST], data_confidence=_EST,
       related_metrics=["ebitda_bridge", "value_creation_opportunity", "rcm_uplift"],
       related_routes=["/diligence/bridge-audit"]),

    # ── Sector Intelligence: Home Health + Hospice (CMS public quality) ──
    _m("home_health_star_rating", "Home Health Star Rating",
       ["quality of patient care star rating", "hha star rating", "hh star rating"],
       "CMS Home Health Care quality-of-patient-care star rating (1-5) per "
       "Medicare-certified agency.",
       "A quick public quality read across a fragmented agency market.",
       "Public benchmark only — not the target's own outcomes; confirm the "
       "agencies in scope match the deal.",
       source_types=[_PUB], data_confidence=_PUB,
       related_routes=["/home-health"]),
    _m("timely_initiation_of_care", "Timely Initiation of Care",
       ["timely care", "timely initiation", "started care timely"],
       "Share of patients whose home-health team began care in a timely "
       "manner (publicly reported HH process measure).",
       "Operational responsiveness signal; weak timeliness can flag intake/"
       "staffing issues.",
       "Process measure, not outcomes or revenue; CMS-reported, not target data.",
       source_types=[_PUB], data_confidence=_PUB,
       related_routes=["/home-health"]),
    _m("discharge_to_community", "Discharge to Community (HH)",
       ["dtc", "discharge to community rate"],
       "Risk-standardized rate of home-health patients discharged to the "
       "community (publicly reported HH outcome).",
       "A headline outcome measure for home-health quality.",
       "Risk-standardized public measure; not the target's internal results.",
       source_types=[_PUB], data_confidence=_PUB,
       related_routes=["/home-health"]),
    _m("hospice_care_index", "Hospice Care Index",
       ["hci", "care index", "hospice care index overall"],
       "CMS Hospice Care Index — a composite of ten care-pattern indicators "
       "(0-10) per Medicare-certified hospice.",
       "A single public read on hospice care patterns across a fragmented "
       "market; outlier indices can flag compliance/quality concerns.",
       "Composite of process/pattern indicators, not outcomes or economics; "
       "CMS-reported, not target data.",
       source_types=[_PUB], data_confidence=_PUB,
       related_routes=["/hospice"]),
    _m("hospice_composite_process", "Hospice Composite Process Measure",
       ["his composite", "composite process measure", "hospice composite"],
       "Share of patients who received all applicable HIS care processes at "
       "admission (publicly reported hospice composite).",
       "A bundled admission-quality signal for hospice diligence.",
       "Process composite, not outcomes; public benchmark, not target actuals.",
       source_types=[_PUB], data_confidence=_PUB,
       related_routes=["/hospice"]),
    _m("visits_in_last_days", "Hospice Visits in Last Days of Life",
       ["visits last days", "visits in the last days of life"],
       "Share of patients with hospice visits in the last days of life "
       "(publicly reported HIS measure).",
       "End-of-life engagement signal relevant to hospice quality/compliance.",
       "Public process measure; not the target's own staffing/visit data.",
       source_types=[_PUB], data_confidence=_PUB,
       related_routes=["/hospice"]),
]

# ── Added metrics (standard textbook definitions; formula_confidence=INFERRED
#    where the formula is the standard one but PEdesk's exact computation isn't
#    confirmed from code; NOT_APPLICABLE for externally-defined composites). ──
_METRICS.extend([
    _m("hhi", "Herfindahl-Hirschman Index (HHI)",
       ["herfindahl", "hhi", "market concentration", "concentration index"],
       "Market-concentration index: the sum of squared market shares of all "
       "competitors in a market.",
       "The standard antitrust/market-structure gauge — high HHI means a "
       "concentrated (less competitive, often more pricing-power) market; low "
       "HHI means fragmented (roll-up runway).",
       "Read the scale: shares as percentages give 0–10,000 (DOJ: <1,500 "
       "unconcentrated, 1,500–2,500 moderate, >2,500 concentrated); shares as "
       "fractions give 0–1. Confirm which scale a page uses before comparing.",
       formula="sum over competitors of (market_share_i)^2",
       formula_confidence=_INF, source_types=[_PUB, _EST], data_confidence=_MIX,
       related_metrics=["benchmark_percentile"],
       related_routes=["/concentration-risk", "/market-intel"]),
    _m("concentration_ratio", "Concentration Ratio (CR3 / CR5)",
       ["cr3", "cr5", "concentration ratio", "top-n share"],
       "Combined market share of the largest N competitors (CR3 = top 3, "
       "CR5 = top 5).",
       "A simpler concentration read than HHI — how much of a market the few "
       "biggest players control.",
       "CRn ignores the distribution below the top N; pair with HHI. A high CR3 "
       "in a target's market signals entrenched incumbents.",
       formula="sum of market shares of the top N competitors",
       formula_confidence=_INF, source_types=[_PUB, _EST], data_confidence=_MIX,
       related_metrics=["hhi"], related_routes=["/concentration-risk"]),
    _m("dscr", "Debt Service Coverage Ratio (DSCR)",
       ["dscr", "debt service coverage", "coverage ratio"],
       "Cash available for debt service divided by total debt service "
       "(interest + scheduled principal) over a period.",
       "The core covenant/solvency test — DSCR below ~1.0x means the business "
       "isn't generating enough cash to cover its debt payments.",
       "Definitions of the numerator vary (EBITDA vs operating cash flow vs "
       "EBITDA−capex); confirm which a page uses. DSCR is only meaningful once "
       "real cash-flow and debt-service figures are loaded.",
       formula="operating cash flow / (interest + scheduled principal)",
       formula_confidence=_INF, source_types=[_OBS, _USR], data_confidence=_MIX,
       related_metrics=["leverage", "debt", "covenant_cushion"],
       related_routes=["/debt-service", "/covenant-headroom"]),
    _m("tvpi", "TVPI (Total Value to Paid-In)",
       ["tvpi", "total value to paid-in", "gross multiple", "total value mult"],
       "Total value (cumulative distributions + residual NAV) divided by "
       "capital paid in by LPs.",
       "The headline fund-level multiple LPs track — total value created per "
       "dollar called, realized and unrealized combined.",
       "TVPI includes UNREALIZED NAV, so it can flatter a young fund; read it "
       "alongside DPI (realized cash) and the fund's age.",
       formula="(cumulative distributions + residual NAV) / paid-in capital",
       formula_confidence=_INF, source_types=[_USR, _OBS], data_confidence=_MIX,
       related_metrics=["dpi", "rvpi", "moic", "irr"],
       related_routes=["/lp-dashboard", "/dpi-tracker"]),
    _m("dpi", "DPI (Distributions to Paid-In)",
       ["dpi", "distributions to paid-in", "realized multiple", "cash-on-cash"],
       "Cumulative cash distributions to LPs divided by capital paid in.",
       "The realized-cash truth of fund performance — money actually returned, "
       "with no unrealized marks.",
       "A low DPI on an older fund is a real concern; on a young fund it's "
       "expected (the j-curve). DPI + RVPI = TVPI.",
       formula="cumulative distributions / paid-in capital",
       formula_confidence=_INF, source_types=[_USR, _OBS], data_confidence=_MIX,
       related_metrics=["tvpi", "rvpi", "moic"],
       related_routes=["/lp-dashboard", "/dpi-tracker"]),
    _m("rvpi", "RVPI (Residual Value to Paid-In)",
       ["rvpi", "residual value to paid-in", "unrealized multiple"],
       "Residual (unrealized) NAV divided by capital paid in.",
       "The unrealized half of TVPI — value still in the ground that exits "
       "must convert to cash.",
       "RVPI is a MARK, not cash; its reliability depends on how conservatively "
       "the GP carries NAV. DPI + RVPI = TVPI.",
       formula="residual NAV / paid-in capital",
       formula_confidence=_INF, source_types=[_USR, _EST], data_confidence=_MIX,
       related_metrics=["tvpi", "dpi"], related_routes=["/lp-dashboard"]),
    _m("cms_star_rating", "CMS Five-Star Rating",
       ["star rating", "five-star", "overall rating", "cms stars",
        "quality rating"],
       "CMS's 1–5 star composite quality rating for a provider (nursing home, "
       "dialysis facility, hospital, etc.).",
       "A standardized, public quality signal — relevant to reimbursement "
       "(e.g. MA bonus), survey risk, and reputational diligence.",
       "It is CMS's OWN composite methodology (health inspection, staffing, "
       "quality measures), refreshed on CMS's schedule and can lag; it is a "
       "quality signal, NOT a financial or revenue metric.",
       formula="CMS composite methodology (externally defined)",
       formula_confidence=_NA, source_types=[_PUB], data_confidence=_PUB,
       related_metrics=["home_health_star_rating"],
       related_routes=["/nursing-homes", "/dialysis", "/ma-star"]),
    _m("days_cash_on_hand", "Days Cash on Hand",
       ["days cash on hand", "dcoh", "liquidity days", "cash days"],
       "Number of days a provider could cover operating expenses from cash and "
       "short-term investments at the current burn rate.",
       "A core liquidity/solvency gauge — low days cash on hand is an early "
       "distress signal, especially for thin-margin providers.",
       "Excludes access to revolver/credit; a low figure with ample undrawn "
       "liquidity is less alarming than it looks. Needs real balance-sheet "
       "data to compute.",
       formula="(cash + short-term investments) / (annual operating expenses "
       "/ 365)",
       formula_confidence=_INF, source_types=[_OBS, _USR], data_confidence=_MIX,
       related_metrics=["dscr", "covenant_cushion"],
       related_routes=["/treasury", "/debt-service"]),
])

METRIC_REGISTRY: Dict[str, MetricContext] = {m.metric_id: m for m in _METRICS}
