"""Generated NEEDS_VALIDATION stubs for served routes absent from the
palette/manual contexts — so the Guide has an honest placeholder (and is
told not to invent specifics) for EVERY served route. Generated by
scripts/gen_served_route_stubs.py; overridden by palette stubs + manual
contexts in the registry.
"""
from __future__ import annotations

from typing import Dict, List, Tuple

from .generated_page_context_stubs import _stub_for
from .types import PageContext, PageContextCategory

# 0 served routes (generated 2026-06-10)
SERVED_ROUTE_NAMES: List[Tuple[str, str]] = [
]

SERVED_ROUTE_STUBS: Dict[str, PageContext] = {
    route: _stub_for(route, title, PageContextCategory.UNKNOWN)
    for route, title in SERVED_ROUTE_NAMES
}
