// SeekingChartis Command Center — data layer
// Mirrors the shapes in rcm_mc/output v1 outputs (33_portfolio_dashboard,
// 10_diligence_run/summary, etc.) so model semantics stay intact.

const PORTFOLIO = {
  asOf: "2026-04-15",
  fund: "SeekingChartis Healthcare Opportunity Fund II",
  weighted: { moic: 2.69, irr: 0.219, dpi: 0.42, tvpi: 2.69 },
  kpis: [
    { id: "deals",       label: "Active Deals",        value: "3",     delta: "+1 vs Q1", dir: "up",   tone: "default", glyph: "▣",
      spark: [2,2,2,2,3,3,3] },
    { id: "moic",        label: "Weighted MOIC",       value: "2.69x", delta: "+0.18x QoQ", dir: "up", tone: "green", glyph: "↗",
      spark: [2.20,2.30,2.36,2.41,2.51,2.58,2.69] },
    { id: "irr",         label: "Weighted IRR",        value: "21.9%", delta: "−1.4 pts QoQ", dir: "down", tone: "amber", glyph: "%",
      spark: [24.1,23.8,23.5,23.0,22.8,22.4,21.9] },
    { id: "atrisk",      label: "Covenants at Risk",   value: "0",     delta: "All SAFE", dir: "flat", tone: "green", glyph: "◇",
      spark: [1,1,1,0,0,0,0] },
    { id: "drag",        label: "Avg EBITDA Drag",     value: "$17.5M",delta: "−$1.2M QoQ", dir: "up", tone: "green", glyph: "Σ",
      spark: [19.2,18.8,18.5,18.1,17.9,17.7,17.5] },
    { id: "dar",         label: "Avg DAR Drag",        value: "12.1d", delta: "−0.4d QoQ", dir: "up", tone: "green", glyph: "⏱",
      spark: [13.0,12.8,12.6,12.5,12.3,12.2,12.1] },
    { id: "init",        label: "Initiatives Tracked", value: "47",    delta: "12 lagging", dir: "down", tone: "amber", glyph: "⚑",
      spark: [40,42,43,45,46,47,47] },
    { id: "cash",        label: "Avg Days Cash",       value: "84d",   delta: "+3d QoQ", dir: "up", tone: "green", glyph: "$",
      spark: [78,79,80,81,82,83,84] },
  ],
  funnel: [
    { stage: "Sourced",  count: 14, ev: "$3.2B" },
    { stage: "Screened", count: 9,  ev: "$2.1B" },
    { stage: "IOI",      count: 4,  ev: "$1.4B" },
    { stage: "LOI",      count: 2,  ev: "$680M" },
    { stage: "SPA",      count: 1,  ev: "$450M" },
    { stage: "Closed",   count: 1,  ev: "$450M" },
    { stage: "Hold",     count: 3,  ev: "$1.2B" },
  ],
  deals: [
    { id: "ccf_2026", name: "Cleveland Care Federation", stage: "Hold",
      ev: 450, moic: 2.69, irr: 0.219, covenant: "SAFE", drift: -28.9, owner: "JD",
      headline: "Coding/CDI initiative behind plan; prior auth recovering" },
    { id: "nyp_2026", name: "Northeastern Provider Network", stage: "IOI",
      ev: 720, moic: null, irr: null, covenant: "—", drift: null, owner: "MK",
      headline: "Awaiting HCRIS pull, denial composition strong (P25)" },
    { id: "mgh_2026", name: "Midwest General Health", stage: "Sourced",
      ev: 290, moic: null, irr: null, covenant: "—", drift: null, owner: "AL",
      headline: "Rural critical access, payer-mix HHI risk flagged" },
  ],
  covenants: {
    quarters: ["Q3'24","Q4'24","Q1'25","Q2'25","Q3'25","Q4'25","Q1'26","Q2'26"],
    rows: [
      { name: "Net Leverage",        sub: "≤ 6.5x",
        cells: [["safe","4.8x"],["safe","4.9x"],["safe","5.0x"],["safe","5.1x"],["safe","5.3x"],["watch","5.6x"],["watch","5.9x"],["watch","6.1x"]],
        trend: "+0.2x" },
      { name: "Interest Coverage",   sub: "≥ 2.0x",
        cells: [["safe","3.4x"],["safe","3.3x"],["safe","3.2x"],["safe","3.0x"],["safe","2.8x"],["safe","2.7x"],["watch","2.4x"],["watch","2.2x"]],
        trend: "−0.2x" },
      { name: "Days Cash on Hand",   sub: "≥ 60 days",
        cells: [["safe","92d"],["safe","88d"],["safe","85d"],["safe","83d"],["safe","82d"],["safe","82d"],["safe","83d"],["safe","84d"]],
        trend: "+1d" },
      { name: "EBITDA / Plan",       sub: "≥ 90%",
        cells: [["safe","104%"],["safe","102%"],["safe","98%"],["watch","96%"],["watch","94%"],["watch","93%"],["watch","91%"],["watch","87%"]],
        trend: "−4 pts" },
      { name: "Denial Rate",         sub: "≤ 8.5%",
        cells: [["safe","6.2%"],["safe","6.4%"],["safe","6.8%"],["safe","7.1%"],["watch","7.6%"],["watch","8.0%"],["watch","8.2%"],["safe","7.9%"]],
        trend: "−0.3 pts" },
      { name: "Days in A/R",         sub: "≤ 50 days",
        cells: [["safe","42d"],["safe","43d"],["safe","44d"],["watch","46d"],["watch","48d"],["watch","49d"],["watch","51d"],["watch","52d"]],
        trend: "+1d" },
    ],
  },
  initiatives: [
    { name: "Coding & CDI Improvement",  deal: "ccf_2026", actual: "$0.02M", variance: -10.0, tone: "a", progress: 38 },
    { name: "Prior Authorization Reform",deal: "ccf_2026", actual: "$0.01M", variance: +28.0, tone: "r", progress: 22 },
    { name: "Denials Workflow Automation",deal:"ccf_2026", actual: "$0.18M", variance: +6.4,  tone: "g", progress: 71 },
    { name: "Self-Pay Recovery",          deal:"ccf_2026", actual: "$0.09M", variance: +2.1,  tone: "g", progress: 64 },
    { name: "Underpayment Recovery",      deal:"ccf_2026", actual: "$0.04M", variance: -15.2, tone: "a", progress: 45 },
    { name: "Charge Capture Audit",       deal:"ccf_2026", actual: "$0.07M", variance: +9.8,  tone: "g", progress: 58 },
  ],
  alerts: [
    { tone: "amber", title: "ccf_2026 — Coding/CDI initiative slipping",
      desc: "Cumulative drift has widened to −28.9% over 4 quarters; lagging vs $0.5M Q3 target.",
      cta: "Open Variance →" },
    { tone: "blue",  title: "nyp_2026 — HCRIS pull pending",
      desc: "Q4'25 cost report not yet ingested; peer percentiles will recompute on arrival.",
      cta: "View Source →" },
    { tone: "amber", title: "Playbook signal — Prior Auth recurring",
      desc: "Prior auth shows >+15% variance across 2 of 3 held deals — consider playbook revision.",
      cta: "Inspect Playbook →" },
  ],
  deliverables: [
    { name: "01_one_liner.html",            kind: "HTML", size: "5 KB"  },
    { name: "02_markdown_memo.html",        kind: "HTML", size: "7 KB"  },
    { name: "04_shortlist_brief.html",      kind: "HTML", size: "6 KB"  },
    { name: "30_portfolio_rollup.html",     kind: "HTML", size: "6 KB"  },
    { name: "33_portfolio_dashboard.html",  kind: "HTML", size: "9 KB"  },
    { name: "34_variance_ccf.html",         kind: "HTML", size: "6 KB"  },
    { name: "39_exit_memo_ccf.html",        kind: "HTML", size: "5 KB"  },
    { name: "diligence_workbook.xlsx",      kind: "XLS",  size: "82 KB" },
    { name: "pe_hold_grid.csv",             kind: "CSV",  size: "12 KB" },
    { name: "pe_returns.json",              kind: "JSON", size: "3 KB"  },
  ],
  drag: {
    title: "EBITDA Drag Decomposition",
    sub: "Source-attributed lift on actual_rcm_ebitda_impact (per 10_diligence_run/summary.csv)",
    items: [
      { label: "Denial write-off",      pct: 60.2, val: "$14.6M", color: "var(--red)" },
      { label: "Denial rework cost",    pct: 12.6, val: "$2.2M",  color: "var(--amber)" },
      { label: "Underpayment leakage",  pct: 11.1, val: "$1.7M",  color: "var(--accent-2)" },
      { label: "DAR carry cost",        pct: 9.4,  val: "$1.4M",  color: "var(--accent)" },
      { label: "Underpay recovery cost",pct: 6.7,  val: "$0.2M",  color: "var(--blue)" },
    ],
  },
};

window.PORTFOLIO = PORTFOLIO;
