"""SeekingChartis brand system — single source of truth for all visual identity.

Healthcare PE diligence platform. Every page, export, and audit trail
references this module for brand consistency.
"""
from __future__ import annotations

from typing import Any, Dict


BRAND = {
    "name": "SeekingChartis",
    "tagline": "Healthcare diligence, instrument-grade",
    "version": "1.0.0",
    "copyright": "SeekingChartis",
    "footer_text": "SeekingChartis v1.0.0 — Healthcare diligence, instrument-grade",
}

LOGO_SVG = (
    '<svg viewBox="0 0 32 32" width="28" height="28" fill="none" xmlns="http://www.w3.org/2000/svg">'
    '<path d="M16 2L16 28" stroke="#1F4E78" stroke-width="2.5" stroke-linecap="round"/>'
    '<path d="M10 6C10 6 13 8 16 8C19 8 22 6 22 6" stroke="#1F4E78" stroke-width="2" stroke-linecap="round"/>'
    '<path d="M10 12C10 12 13 14 16 14C19 14 22 12 22 12" stroke="#1F4E78" stroke-width="2" stroke-linecap="round"/>'
    '<path d="M10 18C10 18 13 20 16 20C19 20 22 18 22 18" stroke="#1F4E78" stroke-width="2" stroke-linecap="round"/>'
    '<path d="M12 2L20 2" stroke="#1F4E78" stroke-width="2" stroke-linecap="round"/>'
    '<circle cx="10" cy="3" r="1.5" fill="#3b82f6"/>'
    '<circle cx="22" cy="3" r="1.5" fill="#3b82f6"/>'
    '</svg>'
)

WORDMARK_SVG = (
    '<svg viewBox="0 0 200 24" width="200" height="24" xmlns="http://www.w3.org/2000/svg">'
    '<text x="0" y="18" font-family="Source Serif Pro, Georgia, serif" '
    'font-size="20" font-weight="600" fill="#e2e8f0" letter-spacing="0.5">SeekingChartis</text>'
    '</svg>'
)

PALETTE = {
    # Bloomberg Terminal-inspired professional dark — near-black base,
    # high-contrast data, amber accent for status, blue for links.
    "bg": "#05070b",
    "bg_secondary": "#0b0f16",
    "bg_tertiary": "#131922",
    "border": "#1c2430",
    "border_light": "#2b3646",
    "text_primary": "#e6edf5",
    "text_secondary": "#9aa7b8",
    "text_muted": "#5f6b7c",
    "text_link": "#5b9bd5",
    "brand_primary": "#1a3a5c",
    "brand_accent": "#2d6ba4",
    "accent_amber": "#e8a33d",
    "positive": "#22c55e",
    "negative": "#ef4444",
    "warning": "#f59e0b",
    "neutral": "#5b6abf",
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#ca8a04",
    "low": "#64748b",
    "ticker_up": "#22c55e",
    "ticker_down": "#ef4444",
    "ticker_flat": "#9aa7b8",
}

TYPOGRAPHY = {
    "font_serif": "Georgia, 'Times New Roman', serif",
    "font_sans": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    "font_mono": "'JetBrains Mono', 'SF Mono', 'Fira Code', 'Consolas', monospace",
}

NAV_ITEMS = [
    {"label": "Home", "href": "/home", "icon": "home"},
    {"separator": True, "label": "DISCOVER"},
    {"label": "Deal Screener", "href": "/predictive-screener", "icon": "filter"},
    {"label": "Market Data", "href": "/market-data/map", "icon": "map"},
    {"label": "Hospital Screener", "href": "/screen", "icon": "filter"},
    {"label": "News & Research", "href": "/news", "icon": "news"},
    {"separator": True, "label": "PORTFOLIO"},
    {"label": "Pipeline", "href": "/pipeline", "icon": "filter"},
    {"label": "Deals", "href": "/portfolio", "icon": "grid"},
    {"label": "Monitor", "href": "/portfolio/monitor", "icon": "chart"},
    {"label": "Team", "href": "/team", "icon": "grid"},
    {"label": "Import Deal", "href": "/import", "icon": "grid"},
    {"separator": True, "label": "ANALYTICS"},
    {"label": "Regression", "href": "/portfolio/regression", "icon": "chart"},
    {"label": "ML Insights", "href": "/ml-insights", "icon": "chart"},
    {"label": "Quant Lab", "href": "/quant-lab", "icon": "chart"},
    {"label": "Model Validation", "href": "/model-validation", "icon": "chart"},
    {"separator": True, "label": "REFERENCE"},
    {"label": "Methodology", "href": "/methodology", "icon": "bookmark"},
    {"label": "Data Sources", "href": "/data", "icon": "bookmark"},
    {"label": "Settings", "href": "/settings", "icon": "gear"},
    {"separator": True, "label": "CORPUS"},
    {"label": "Deals Library", "href": "/deals-library", "icon": "grid"},
    {"label": "Comparables", "href": "/comparables", "icon": "grid"},
    {"label": "Risk Matrix", "href": "/risk-matrix", "icon": "chart"},
    {"label": "Underwriting", "href": "/underwriting", "icon": "chart"},
    {"label": "Market Rates", "href": "/market-rates", "icon": "chart"},
    {"label": "Backtest", "href": "/backtest", "icon": "chart"},
    {"label": "Portfolio Optimizer", "href": "/portfolio-optimizer", "icon": "chart"},
    {"label": "Deal Quality", "href": "/deal-quality", "icon": "chart"},
    {"label": "Sector Intel", "href": "/sector-intel", "icon": "chart"},
    {"label": "Vintage Performance", "href": "/vintage-perf", "icon": "chart"},
    {"label": "Payer Intelligence", "href": "/payer-intel", "icon": "chart"},
    {"label": "Leverage Intelligence", "href": "/leverage-intel", "icon": "chart"},
    {"label": "Size Intelligence", "href": "/size-intel", "icon": "chart"},
    {"label": "Corpus Dashboard", "href": "/corpus-dashboard", "icon": "chart"},
    {"label": "Deal Search", "href": "/deal-search", "icon": "filter"},
    {"label": "IC Memo Gen.", "href": "/corpus-ic-memo", "icon": "doc"},
    {"label": "Return Attribution", "href": "/return-attribution", "icon": "chart"},
    {"label": "Deal Flow Heatmap", "href": "/deal-flow-heatmap", "icon": "grid"},
    {"label": "Concentration Risk", "href": "/concentration-risk", "icon": "chart"},
    {"label": "Hold Analysis", "href": "/hold-analysis", "icon": "chart"},
    {"label": "IRR Dispersion", "href": "/irr-dispersion", "icon": "chart"},
    {"label": "Payer Rate Trends", "href": "/payer-rate-trends", "icon": "chart"},
    {"label": "Entry Multiple", "href": "/entry-multiple", "icon": "chart"},
    {"label": "Corpus Coverage", "href": "/corpus-coverage", "icon": "doc"},
    {"label": "Find Comps", "href": "/find-comps", "icon": "filter"},
    {"label": "Sector Momentum", "href": "/sector-momentum", "icon": "chart"},
    {"label": "GP Benchmarking", "href": "/gp-benchmarking", "icon": "chart"},
    {"label": "RCM Red Flags", "href": "/rcm-red-flags", "icon": "chart"},
    {"label": "Hold Optimizer", "href": "/hold-optimizer", "icon": "chart"},
    {"label": "Payer Stress", "href": "/payer-stress", "icon": "chart"},
    {"label": "Multiple Decomp", "href": "/multiple-decomp", "icon": "chart"},
    {"label": "Capital Efficiency", "href": "/capital-efficiency", "icon": "chart"},
    {"label": "Deal Risk Scores", "href": "/deal-risk-scores", "icon": "chart"},
    {"label": "Sector Correlation", "href": "/sector-correlation", "icon": "chart"},
    {"label": "Acquisition Timing", "href": "/acq-timing", "icon": "chart"},
    {"label": "Portfolio Simulator", "href": "/portfolio-sim", "icon": "chart"},
    {"label": "QoE Analyzer", "href": "/qoe-analyzer", "icon": "chart"},
    {"label": "Covenant Monitor", "href": "/covenant-monitor", "icon": "chart"},
    {"label": "Provider Network", "href": "/provider-network", "icon": "chart"},
    {"label": "Exit Multiple Analysis", "href": "/exit-multiple", "icon": "chart"},
    {"label": "Diligence Checklist", "href": "/diligence-checklist", "icon": "doc"},
    {"label": "Value Creation Tracker", "href": "/value-creation", "icon": "chart"},
    {"label": "Underwriting Model", "href": "/underwriting-model", "icon": "chart"},
    {"label": "Mgmt Fee Tracker", "href": "/mgmt-fee-tracker", "icon": "chart"},
    {"label": "LP Dashboard", "href": "/lp-dashboard", "icon": "chart"},
    {"label": "Bolt-on M&A", "href": "/bolton-analyzer", "icon": "chart"},
    {"label": "Working Capital", "href": "/working-capital", "icon": "chart"},
    {"label": "Debt Service", "href": "/debt-service", "icon": "chart"},
    {"label": "Mgmt Comp", "href": "/mgmt-comp", "icon": "chart"},
    {"label": "Physician Productivity", "href": "/physician-productivity", "icon": "chart"},
    {"label": "Regulatory Risk", "href": "/regulatory-risk", "icon": "chart"},
    {"label": "Cost Structure", "href": "/cost-structure", "icon": "chart"},
    {"label": "Quality Scorecard", "href": "/quality-scorecard", "icon": "chart"},
    {"label": "ESG Dashboard", "href": "/esg-dashboard", "icon": "chart"},
    {"label": "Exit Readiness", "href": "/exit-readiness", "icon": "chart"},
    {"label": "Tax Structure", "href": "/tax-structure", "icon": "chart"},
    {"label": "Fund Attribution", "href": "/fund-attribution", "icon": "chart"},
    {"label": "Unit Economics", "href": "/unit-economics", "icon": "chart"},
    {"label": "Deal Pipeline", "href": "/deal-pipeline", "icon": "chart"},
    {"label": "Payer Shift", "href": "/payer-shift", "icon": "chart"},
    {"label": "Key Person Risk", "href": "/key-person", "icon": "chart"},
    {"label": "Scenario MC", "href": "/scenario-mc", "icon": "chart"},
    {"label": "TSA Tracker", "href": "/transition-services", "icon": "chart"},
    {"label": "Revenue Leakage", "href": "/revenue-leakage", "icon": "chart"},
    {"label": "Reference Pricing", "href": "/ref-pricing", "icon": "chart"},
    {"label": "Geo Market", "href": "/geo-market", "icon": "chart"},
    {"label": "Capital Schedule", "href": "/capital-schedule", "icon": "chart"},
    {"label": "Peer Valuation", "href": "/peer-valuation", "icon": "chart"},
    {"label": "VCP 100-Day", "href": "/value-creation-plan", "icon": "chart"},
    {"label": "Cap Structure", "href": "/cap-structure", "icon": "chart"},
    {"label": "Real Estate", "href": "/real-estate", "icon": "chart"},
    {"label": "Workforce Plan", "href": "/workforce-planning", "icon": "chart"},
    {"label": "Tech Stack", "href": "/tech-stack", "icon": "chart"},
    {"label": "Growth Runway", "href": "/growth-runway", "icon": "chart"},
    {"label": "Dividend Recap", "href": "/dividend-recap", "icon": "chart"},
    {"label": "Continuation Vehicle", "href": "/continuation-vehicle", "icon": "chart"},
    {"label": "Earnout", "href": "/earnout", "icon": "chart"},
    {"label": "Clinical Outcomes", "href": "/clinical-outcomes", "icon": "chart"},
    {"label": "Competitive Intel", "href": "/competitive-intel", "icon": "chart"},
    {"label": "Patient Experience", "href": "/patient-experience", "icon": "chart"},
    {"label": "Supply Chain", "href": "/supply-chain", "icon": "chart"},
    {"label": "Provider Retention", "href": "/provider-retention", "icon": "chart"},
    {"label": "Demand Forecast", "href": "/demand-forecast", "icon": "chart"},
    {"label": "Reinvestment", "href": "/reinvestment", "icon": "chart"},
    {"label": "Partner Economics", "href": "/partner-economics", "icon": "chart"},
    {"label": "Insurance Tracker", "href": "/insurance-tracker", "icon": "chart"},
    {"label": "ACO Economics", "href": "/aco-economics", "icon": "chart"},
    {"label": "Phys Comp Plan", "href": "/phys-comp-plan", "icon": "chart"},
    {"label": "Locum Workforce", "href": "/locum-tracker", "icon": "chart"},
    {"label": "MA Contracts", "href": "/ma-contracts", "icon": "chart"},
    {"label": "340B Drug Pricing", "href": "/drug-pricing-340b", "icon": "chart"},
    {"label": "Sponsor Heatmap", "href": "/sponsor-heatmap", "icon": "grid"},
    {"label": "Payer Concentration", "href": "/payer-concentration", "icon": "chart"},
    {"label": "Roll-Up Economics", "href": "/rollup-economics", "icon": "chart"},
    {"label": "CIN Analyzer", "href": "/cin-analyzer", "icon": "chart"},
    {"label": "Base Rates", "href": "/base-rates", "icon": "grid"},
    {"label": "REIT / SLB", "href": "/reit-analyzer", "icon": "chart"},
    {"label": "Capital Pacing", "href": "/capital-pacing", "icon": "chart"},
    {"label": "Covenant Headroom", "href": "/covenant-headroom", "icon": "chart"},
    {"label": "Red-Flag Scanner", "href": "/redflag-scanner", "icon": "chart"},
    {"label": "Value Backtester", "href": "/backtester", "icon": "chart"},
    {"label": "Direct Employer", "href": "/direct-employer", "icon": "chart"},
    {"label": "Deal Origination", "href": "/deal-origination", "icon": "chart"},
    {"label": "Trial Site Econ", "href": "/trial-site-econ", "icon": "chart"},
    {"label": "HCIT Platform", "href": "/hcit-platform", "icon": "chart"},
    {"label": "Biosimilars", "href": "/biosimilars", "icon": "chart"},
    {"label": "Telehealth Econ", "href": "/telehealth-econ", "icon": "chart"},
    {"label": "De Novo Expansion", "href": "/denovo-expansion", "icon": "chart"},
    {"label": "Health Equity", "href": "/health-equity", "icon": "chart"},
    {"label": "Physician Labor", "href": "/physician-labor", "icon": "chart"},
    {"label": "Platform Maturity", "href": "/platform-maturity", "icon": "chart"},
    {"label": "Direct Lending", "href": "/direct-lending", "icon": "chart"},
    {"label": "PMI Playbook", "href": "/pmi-playbook", "icon": "chart"},
    {"label": "FWA Detection", "href": "/fraud-detection", "icon": "chart"},
    {"label": "Drug Shortage", "href": "/drug-shortage", "icon": "chart"},
    {"label": "Anti-Trust Screener", "href": "/antitrust-screener", "icon": "chart"},
    {"label": "AI Operating Model", "href": "/ai-operating-model", "icon": "chart"},
    {"label": "Cyber Risk", "href": "/cyber-risk", "icon": "chart"},
    {"label": "ZBB Tracker", "href": "/zbb-tracker", "icon": "chart"},
    {"label": "CMS Data Browser", "href": "/cms-data-browser", "icon": "bookmark"},
    {"label": "MSA Concentration", "href": "/msa-concentration", "icon": "chart"},
    {"label": "IC Memo Generator", "href": "/ic-memo-gen", "icon": "chart"},
    {"label": "Module Index", "href": "/module-index", "icon": "bookmark"},
    {"label": "Deal Post-Mortem", "href": "/deal-postmortem", "icon": "chart"},
    {"label": "Secondaries", "href": "/secondaries-tracker", "icon": "chart"},
    {"label": "Tax Structure Analyzer", "href": "/tax-structure-analyzer", "icon": "chart"},
    {"label": "Diligence Vendors", "href": "/diligence-vendors", "icon": "chart"},
    {"label": "Refi Optimizer", "href": "/refi-optimizer", "icon": "chart"},
    {"label": "LP Reporting", "href": "/lp-reporting", "icon": "chart"},
    {"label": "LBO Stress Test", "href": "/lbo-stress", "icon": "chart"},
    {"label": "Board Governance", "href": "/board-governance", "icon": "chart"},
    {"label": "VDR Tracker", "href": "/vdr-tracker", "icon": "chart"},
    {"label": "Escrow & Earnout", "href": "/escrow-earnout", "icon": "chart"},
    {"label": "Debt Financing", "href": "/debt-financing", "icon": "chart"},
    {"label": "VCP Tracker", "href": "/vcp-tracker", "icon": "chart"},
    {"label": "Co-Invest Pipeline", "href": "/coinvest-pipeline", "icon": "grid"},
    {"label": "DPI Tracker", "href": "/dpi-tracker", "icon": "chart"},
    {"label": "NAV Loan Tracker", "href": "/nav-loan-tracker", "icon": "chart"},
    {"label": "Medical RE Tracker", "href": "/medical-realestate", "icon": "chart"},
    {"label": "CMS APM Tracker", "href": "/cms-apm", "icon": "bookmark"},
    {"label": "MA / Stars Tracker", "href": "/ma-star", "icon": "bookmark"},
    {"label": "Data Admin", "href": "/admin/data-sources", "icon": "gear"},
    {"label": "Sponsor League", "href": "/sponsor-league", "icon": "grid"},
    {"label": "Exit Timing", "href": "/exit-timing", "icon": "chart"},
    {"label": "CMS Sources", "href": "/cms-sources", "icon": "bookmark"},
]

NAV_ICONS = {
    "home": "&#9679;", "chart": "&#9672;", "news": "&#9993;",
    "map": "&#9728;", "filter": "&#9707;", "grid": "&#9638;",
    "bookmark": "&#9733;", "gear": "&#9881;",
}
