"""IC Packet page — /diligence/ic-packet.

Runs the full multi-module pipeline against a fixture (or the
Steward demo) and produces a single HTML document suitable for
browser Save-as-PDF.

Pipeline:
    CCD ingest → KPI bundle → Cash waterfall → Counterfactual
    advisor (with caller metadata) → Bankruptcy-Survivor Scan →
    Steward Score (from metadata) → Cyber composite (from metadata)
    → V28 recalibration (when MA members supplied) → Market-intel
    comps + transaction multiple → IC packet render.

Landing page has a fixture picker + the same query params the QoE
memo + counterfactual page accept. The resulting IC-packet URL is
URL-reproducible.
"""
from __future__ import annotations

import html
import urllib.parse
from datetime import date
from typing import Any, Dict, List, Optional

from ..diligence._pages import AVAILABLE_FIXTURES, _resolve_dataset
from ._chartis_kit import (
    P, chartis_shell, ck_kpi_block, ck_next_section, ck_panel,
    ck_section_header, ck_section_intro, ck_signal_badge, ck_source_purpose,
    ck_sticky_toc,
)


def _slugify_for_anchor(text: str) -> str:
    """Convert an h2 title into a URL-fragment-safe anchor id."""
    import re as _re
    slug = _re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower())
    return _re.sub(r"^-+|-+$", "", slug) or "section"


def _inject_h2_anchors(html_str: str) -> tuple:
    """Walk the IC-packet body HTML, add ``id="..."`` to every
    ``<h2>...</h2>`` that doesn't already carry one, and return the
    rewritten HTML alongside the ordered (id, title) pairs.

    The IC packet is generated by ten small section helpers in
    rcm_mc/exports/ic_packet.py — each emits a fixed-shape ``<h2>``
    title. Slugifying them server-side here gives us anchors without
    asking each helper to declare one. JS-side DOM walking would work
    too, but doing it server-side keeps the deep-link hash valid in
    the HTML that ships to print or PDF.
    """
    import re as _re
    titles: List[tuple] = []
    seen: Dict[str, int] = {}

    def _add(match):
        attrs = match.group(1)
        title = match.group(2)
        # Strip any html nested in the title for the slug source
        clean = _re.sub(r"<[^>]+>", "", title)
        if 'id="' in attrs:
            return match.group(0)
        slug = _slugify_for_anchor(clean)
        # de-dupe on collision so the TOC stays unambiguous
        if slug in seen:
            seen[slug] += 1
            slug = f"{slug}-{seen[slug]}"
        else:
            seen[slug] = 0
        titles.append((slug, clean))
        return f'<h2{attrs} id="{slug}">{title}</h2>'

    rewritten = _re.sub(
        r"<h2([^>]*)>(.*?)</h2>", _add, html_str, flags=_re.DOTALL
    )
    return rewritten, titles


_HOSPITAL_BASED_SPECIALTIES = {
    "EMERGENCY_MEDICINE", "ANESTHESIOLOGY", "RADIOLOGY",
    "PATHOLOGY", "NEONATOLOGY", "HOSPITALIST",
}


_FORM_CSS = f"""
<style>
/* 2026-05-28 batch 40 · Tier-4 trope removal — cap radius at 2px. */
.ic-form{{display:grid;grid-template-columns:1fr 1fr;gap:12px;
max-width:720px;margin-top:20px;background:{P["panel"]};
border:1px solid {P["border"]};border-radius:2px;padding:20px;}}
.ic-form .ic-form-full{{grid-column:span 2;}}
.ic-form label{{font-size:9px;color:{P["text_faint"]};
letter-spacing:1.5px;text-transform:uppercase;font-weight:600;
display:block;margin-bottom:4px;}}
.ic-form input,.ic-form select{{width:100%;padding:6px 8px;
background:{P["panel_alt"]};color:{P["text"]};
border:1px solid {P["border"]};font-family:inherit;}}
.ic-form .ic-form-submit{{grid-column:span 2;justify-self:start;
margin-top:6px;padding:8px 20px;background:{P["accent"]};
color:{P["panel"]};border:0;font-size:10px;letter-spacing:1.5px;
text-transform:uppercase;font-weight:700;cursor:pointer;}}
</style>
"""


def _landing() -> str:
    options = "".join(
        f'<option value="{html.escape(n)}">{html.escape(l)}</option>'
        for n, l in AVAILABLE_FIXTURES
    )
    # Single editorial head (real <h1>): this is the sole masthead, so the
    # shell does NOT auto-inject a generic "RCM Diligence — …" title above it.
    from ._chartis_kit import ck_editorial_head
    intro = ck_editorial_head(
        eyebrow="IC Packet Assembler",
        title="One-click IC Memo",
        meta=(
            f"{len(AVAILABLE_FIXTURES)} FIXTURE"
            f"{'S' if len(AVAILABLE_FIXTURES) != 1 else ''} · "
            "URL-REPRODUCIBLE · BROWSER-PRINT READY"
        ),
        lede_italic_phrase="The signed IC deliverable, in one step.",
        lede_body=(
            "Assembles the signed IC deliverable in one browser-print "
            "step: cover + partner synthesis + headline numbers + "
            "Bankruptcy-Survivor Scan + QoR waterfall + risk-module "
            "summary + counterfactual levers + market context + "
            "100-day plan + open questions + walkaway conditions + "
            "signature block. Single URL-reproducible memo."
        ),
    )
    form = (
        '<form method="GET" action="/diligence/ic-packet" class="ic-form">'
        '<div class="ic-form-full">'
        '<label>Dataset</label>'
        '<select name="dataset" required>'
        f'<option value="">— pick a CCD fixture —</option>{options}'
        '</select></div>'
    )
    for name, label, placeholder in [
        ("deal_name", "Deal name", "Project Aurora"),
        ("partner_name", "Partner", ""),
        ("preparer_name", "Preparer", ""),
        ("engagement_id", "Engagement ID", ""),
        ("legal_structure", "Legal structure", ""),
        ("landlord", "Landlord", ""),
        ("states", "States (comma-sep)", "OR, WA"),
        ("specialty", "Specialty", "EMERGENCY_MEDICINE"),
        ("cbsa_codes", "CBSA codes (comma-sep)", ""),
        ("msas", "MSAs (comma-sep)", ""),
    ]:
        form += (
            f'<div><label>{html.escape(label)}</label>'
            f'<input name="{name}" placeholder="{html.escape(placeholder)}">'
            f'</div>'
        )
    form += (
        '<button type="submit" class="ic-form-submit">'
        'Assemble IC Packet</button></form>'
    )
    body = f'{_FORM_CSS}{intro}' + ck_panel(form, title="Inputs")
    # 2026-05-28 wave-B: ck_page_actions adds Copy share link
    # + Back-to-top affordances. Idempotent JS guards.
    from ._chartis_kit import ck_page_actions
    body = body + ck_page_actions()
    return chartis_shell(body, "RCM Diligence — IC Packet Assembler")


def _split_list(raw: str) -> List[str]:
    return [t.strip() for t in (raw or "").split(",") if t.strip()]


def render_ic_packet_page(qs: Optional[Dict[str, List[str]]] = None) -> str:
    qs = qs or {}
    dataset = (qs.get("dataset") or [""])[0]
    if not dataset:
        return _landing()
    ds_path = _resolve_dataset(dataset)
    if ds_path is None:
        return _landing()

    # Imports inside the handler keep the module lightweight on
    # boot and let individual subpackage failures degrade gracefully.
    from ..diligence import ingest_dataset
    from ..diligence.benchmarks import compute_cash_waterfall, compute_kpis
    from ..diligence.counterfactual import (
        counterfactual_bridge_lever, run_counterfactuals_from_ccd,
    )
    from ..diligence.real_estate import (
        LeaseLine, LeaseSchedule, compute_steward_score,
    )
    from ..diligence.regulatory import compose_packet
    from ..diligence.screening import (
        ScanInput, run_bankruptcy_survivor_scan,
    )
    from ..diligence.cyber import (
        assess_business_associates, compose_cyber_score,
        ehr_vendor_risk_score,
    )
    from ..market_intel import (
        find_comparables, sector_sentiment, transaction_multiple,
    )
    from ..exports import ICPacketMetadata, render_ic_packet_html

    def first(k: str) -> str:
        return (qs.get(k) or [""])[0].strip()

    specialty = first("specialty").upper() or None
    states = _split_list(first("states"))
    cbsa_codes = _split_list(first("cbsa_codes"))
    msas = _split_list(first("msas"))
    legal_structure = first("legal_structure").upper() or None
    landlord = first("landlord") or None

    def float_or_none(k: str):
        v = first(k)
        try:
            return float(v) if v else None
        except ValueError:
            return None

    def int_or_none(k: str):
        v = first(k)
        try:
            return int(float(v)) if v else None
        except ValueError:
            return None

    meta = ICPacketMetadata(
        deal_name=first("deal_name") or dataset,
        target_entity=first("target_entity") or None,
        engagement_id=first("engagement_id") or None,
        ic_date=first("ic_date") or date.today().isoformat(),
        partner_name=first("partner_name") or None,
        preparer_name=first("preparer_name") or None,
        recommendation=first("recommendation").upper()
            or "PROCEED_WITH_CONDITIONS",
    )
    if specialty:
        sent = sector_sentiment(specialty)
        if sent:
            meta.sector_sentiment = sent

    # 1. CCD ingest + Phase-2 engines.
    try:
        ccd = ingest_dataset(ds_path)
    except Exception as exc:  # noqa: BLE001
        # 2026-05-28 batch 22 · err-path also uses the universal head.
        from ._chartis_kit import ck_editorial_head
        err_intro = ck_editorial_head(
            eyebrow="IC Packet",
            title=f"Ingest failed for {html.escape(dataset)}.",
            meta="INGEST FAILED · CHECK FIXTURE",
            lede_italic_phrase="The dataset didn't ingest.",
            lede_body=html.escape(str(exc)),
        )
        return chartis_shell(err_intro, "IC Packet")
    as_of = date(2025, 1, 1)
    try:
        bundle = compute_kpis(ccd, as_of_date=as_of, provider_id=dataset)
    except Exception:  # noqa: BLE001
        bundle = None
    try:
        waterfall = compute_cash_waterfall(
            ccd.claims, as_of_date=as_of,
        )
    except Exception:  # noqa: BLE001
        waterfall = None

    # 2. Bankruptcy-Survivor Scan.
    try:
        scan = run_bankruptcy_survivor_scan(ScanInput(
            target_name=meta.deal_name,
            specialty=specialty, states=states, msas=msas,
            cbsa_codes=cbsa_codes,
            legal_structure=legal_structure,
            landlord=landlord,
            lease_term_years=int_or_none("lease_term_years"),
            lease_escalator_pct=float_or_none("lease_escalator_pct"),
            ebitdar_coverage=float_or_none("ebitdar_coverage"),
            geography=first("geography").upper() or None,
            is_hospital_based_physician=(
                (specialty or "") in _HOSPITAL_BASED_SPECIALTIES
            ),
            oon_revenue_share=float_or_none("oon_revenue_share"),
            hopd_revenue_annual_usd=float_or_none("hopd_revenue_annual_usd"),
        ))
    except Exception:  # noqa: BLE001
        scan = None

    # 3. Counterfactual advisor.
    cf_meta: Dict[str, Any] = {}
    if legal_structure:
        cf_meta["legal_structure"] = legal_structure
    if states:
        cf_meta["states"] = states
    if landlord:
        cf_meta["landlord"] = landlord
    if specialty:
        cf_meta["specialty"] = specialty
        cf_meta["is_hospital_based_physician"] = (
            specialty in _HOSPITAL_BASED_SPECIALTIES
        )
    if cbsa_codes:
        cf_meta["cbsa_codes"] = cbsa_codes
    if msas:
        cf_meta["msas"] = msas
    for k in (
        "lease_term_years", "lease_escalator_pct",
        "ebitdar_coverage", "annual_rent_usd",
        "portfolio_ebitdar_usd",
    ):
        val = (
            int_or_none(k) if k.endswith("_years")
            else float_or_none(k)
        )
        if val is not None:
            cf_meta[k] = val
    if first("geography"):
        cf_meta["geography"] = first("geography").upper()
    try:
        cfs = run_counterfactuals_from_ccd(ccd, metadata=cf_meta)
    except Exception:  # noqa: BLE001
        cfs = None

    # 4. Steward Score (when we have lease metadata).
    steward = None
    if landlord or int_or_none("lease_term_years"):
        try:
            sched = LeaseSchedule(lines=[LeaseLine(
                property_id=meta.deal_name,
                property_type=(specialty or "HOSPITAL").upper()
                    if specialty else "HOSPITAL",
                base_rent_annual_usd=float(
                    float_or_none("annual_rent_usd") or 1.0
                ),
                escalator_pct=float_or_none("lease_escalator_pct") or 0.0,
                term_years=int_or_none("lease_term_years") or 10,
                landlord=landlord,
            )])
            steward = compute_steward_score(
                sched,
                portfolio_ebitdar_annual_usd=float_or_none(
                    "portfolio_ebitdar_usd",
                ),
                portfolio_annual_rent_usd=float_or_none("annual_rent_usd"),
                geography=first("geography").upper() or None,
            )
        except Exception:  # noqa: BLE001
            steward = None

    # 5. Cyber composite (best-effort from caller-supplied metadata).
    cyber = None
    ehr_vendor = first("ehr_vendor").upper() or None
    bas = _split_list(first("business_associates"))
    if ehr_vendor or bas:
        try:
            cyber = compose_cyber_score(
                external_rating=None,
                ehr_vendor_risk=(
                    ehr_vendor_risk_score(ehr_vendor) if ehr_vendor
                    else None
                ),
                ba_findings=(
                    assess_business_associates(bas) if bas else []
                ),
                it_capex=None, bi_loss=None,
                annual_revenue_usd=float_or_none("annual_revenue_usd")
                    or 0.0,
            )
        except Exception:  # noqa: BLE001
            cyber = None

    # 6. Market-intel comps + transaction multiple.
    public_comps: Optional[List[Dict[str, Any]]] = None
    sector_label: Optional[str] = None
    peer_median = None
    transaction_band = None
    mi_category = first("market_category").upper() or None
    mi_revenue = float_or_none("revenue_usd")
    mi_ev = float_or_none("enterprise_value_usd")
    if mi_category:
        try:
            payload = find_comparables(
                target_category=mi_category,
                target_revenue_usd=mi_revenue,
            )
            public_comps = payload.get("comps") or []
            band_d = payload.get("band") or {}
            peer_median = band_d.get("median_ev_ebitda")
        except Exception:  # noqa: BLE001
            pass
    if specialty:
        try:
            sector_label = sector_sentiment(specialty)
            transaction_band = transaction_multiple(
                specialty=specialty, ev_usd=mi_ev,
            )
        except Exception:  # noqa: BLE001
            pass

    # 7. Deal Autopsy — historical failure/survivor signature match.
    autopsy_matches: Optional[List[Any]] = None
    try:
        from ..diligence.deal_autopsy import (
            historical_library, match_target, signature_from_ccd,
        )

        autopsy_metadata: Dict[str, float] = {}

        # Lease intensity — rent / revenue if we have both.
        annual_rent = float_or_none("annual_rent_usd")
        if annual_rent and mi_revenue and mi_revenue > 0:
            autopsy_metadata["lease_intensity"] = min(
                1.0, annual_rent / mi_revenue / 0.20,
            )

        # EBITDAR stress band — 1.0 at coverage ≤ 1.0x, 0.0 at ≥ 2.5x.
        cov = float_or_none("ebitdar_coverage")
        if cov is not None:
            if cov <= 1.0:
                autopsy_metadata["ebitdar_stress"] = 1.0
            elif cov >= 2.5:
                autopsy_metadata["ebitdar_stress"] = 0.0
            else:
                autopsy_metadata["ebitdar_stress"] = (
                    (2.5 - cov) / 1.5
                )

        # OON revenue share flows directly.
        oon = float_or_none("oon_revenue_share")
        if oon is not None:
            autopsy_metadata["oon_revenue_share"] = oon

        # Regulatory exposure — lean on scan / counterfactual output
        # when available.
        reg_exposure: Optional[float] = None
        if scan is not None:
            verdict = getattr(scan, "verdict", None)
            verdict_val = (
                verdict.value if hasattr(verdict, "value")
                else str(verdict or "")
            )
            reg_exposure = {
                "CRITICAL": 0.9, "RED": 0.75, "YELLOW": 0.45,
                "GREEN": 0.15,
            }.get(verdict_val.upper(), None)
        if cfs is not None and reg_exposure is None:
            # Proxy: any critical counterfactual lever present.
            if getattr(cfs, "critical_findings_addressed", 0):
                reg_exposure = 0.7
        if reg_exposure is not None:
            autopsy_metadata["regulatory_exposure"] = reg_exposure

        target_sig = signature_from_ccd(
            ccd, metadata=autopsy_metadata,
        )
        autopsy_matches = match_target(
            target_sig, historical_library(), top_k=5,
        )
    except Exception:  # noqa: BLE001
        autopsy_matches = None

    # 7c. Regulatory Calendar × Kill-Switch — partner-facing
    # timeline of CMS/OIG/FTC/DOJ/NSA-IDR events mapped to the
    # target's thesis drivers with the specific calendar date
    # each driver dies.  Feeds reg_headwind on Deal MC and
    # narratively into the IC memo.
    reg_exposure = None
    try:
        from ..diligence.regulatory_calendar import (
            analyze_regulatory_exposure,
        )
        ma_mix = None
        if first("medicare_share"):
            try:
                ma_mix = float(first("medicare_share")) * 0.55
            except ValueError:
                ma_mix = None
        comm = None
        if first("commercial_payer_share"):
            try:
                comm = float(first("commercial_payer_share"))
            except ValueError:
                comm = None
        has_reit = bool(landlord) and any(
            m in str(landlord).upper()
            for m in ("MPT", "WELLTOWER", "VENTAS", "OMEGA", "SABRA")
        )
        target = {
            "specialty": specialty,
            "specialties": [specialty] if specialty else [],
            "ma_mix_pct": ma_mix,
            "commercial_payer_share": comm,
            "has_hopd_revenue":
                bool(float_or_none("hopd_revenue_annual_usd")),
            "has_reit_landlord": has_reit,
            "revenue_usd": mi_revenue,
            "ebitda_usd": float_or_none("ebitda_usd"),
        }
        reg_exposure = analyze_regulatory_exposure(
            target_profile=target, horizon_months=24,
        )
    except Exception:  # noqa: BLE001
        reg_exposure = None

    # 7b. Checklist coverage — derive observations from what the
    # pipeline has actually produced and run the tracker.
    checklist_state = None
    try:
        from ..diligence.checklist import (
            compute_status, DealObservations,
        )
        obs = DealObservations(
            ccd_ingested=True,  # implicit by reaching this point
            bankruptcy_scan_run=(scan is not None),
            steward_run=(steward is not None),
            cyber_run=(cyber is not None),
            counterfactual_run=(cfs is not None),
            market_intel_run=(public_comps is not None
                              or transaction_band is not None),
            sector_sentiment_reviewed=(sector_label is not None),
            deal_autopsy_run=bool(autopsy_matches),
            regulatory_calendar_run=(reg_exposure is not None),
            # New diligence modules — observed from successful
            # evidence extraction in the bear case block
            hcris_xray_run=(
                bool(bear_block_html) and "HCRIS" in bear_block_html
            ) if bear_block_html else bool(first("hcris_ccn")),
            covenant_stress_run=(
                bool(bear_block_html) and
                "Covenant" in bear_block_html
            ),
            payer_stress_run=(
                bool(bear_block_html) and
                "Payer" in bear_block_html
            ),
            qor_waterfall_computed=(waterfall is not None),
            hfma_days_in_ar_computed=(bundle is not None),
            hfma_denial_rate_computed=(bundle is not None),
            hfma_ar_aging_computed=(bundle is not None),
            hfma_nrr_computed=(bundle is not None),
            cohort_liquidation_computed=(bundle is not None),
            denial_pareto_computed=(bundle is not None),
            # Deliverable — we're building the IC packet right now
            ic_packet_assembled=True,
        )
        checklist_state = compute_status(obs)
    except Exception:  # noqa: BLE001
        checklist_state = None

    # 7d. Render a standalone Regulatory Timeline block we can inject
    # into the IC packet HTML output (the renderer signature doesn't
    # take a regulatory_exposure param yet).
    reg_block_html = ""
    if reg_exposure is not None:
        reg_block_html = _render_regulatory_block(reg_exposure)

    # 7e. Auto-generate a Bear Case block from available sources.
    # Runs extractors standalone — uses the same library as
    # /diligence/bear-case but produces print-ready HTML inline.
    bear_block_html = ""
    try:
        from ..diligence.bear_case import generate_bear_case
        from ..diligence.hcris_xray import xray as _hcris_xray
        hcris_report = None
        ccn = first("hcris_ccn")
        if ccn:
            try:
                hcris_report = _hcris_xray(ccn=ccn)
            except Exception:  # noqa: BLE001
                hcris_report = None
        br = generate_bear_case(
            target_name=meta.deal_name,
            regulatory_exposure=reg_exposure,
            autopsy_matches=autopsy_matches,
            hcris_xray=hcris_report,
        )
        if br.evidence:
            bear_block_html = br.ic_memo_html
    except Exception:  # noqa: BLE001
        bear_block_html = ""

    # 8. Assemble.
    html_str = render_ic_packet_html(
        metadata=meta,
        bankruptcy_scan=scan,
        cash_waterfall=waterfall,
        regulatory_packet=None,
        steward_score=steward,
        cyber_score=cyber,
        ma_v28_result=None,
        physician_comp_roster_size=None,
        stark_findings_count=None,
        counterfactuals=cfs,
        open_questions=getattr(bundle, "diligence_questions", None)
            if bundle else None,
        walkaway_conditions=_derive_walkaway(cfs),
        hundred_day_summary=None,
        enterprise_value_usd=mi_ev,
        revenue_usd=mi_revenue,
        ebitda_usd=float_or_none("ebitda_usd"),
        projected_moic=float_or_none("projected_moic"),
        projected_irr=float_or_none("projected_irr"),
        peer_median_ev_ebitda=peer_median,
        public_comps=public_comps,
        sector_sentiment=sector_label,
        transaction_multiple_band=transaction_band,
        autopsy_matches=autopsy_matches,
        checklist_state=checklist_state,
    )
    # Inject the deal-context bar at the top (just after <body>)
    # and the regulatory timeline + bear case blocks at the end.
    try:
        from .power_ui import deal_context_bar
        bar_html = deal_context_bar(qs, active_surface="ic_packet")
    except Exception:  # noqa: BLE001
        bar_html = ""
    if bar_html and "<body>" in html_str:
        html_str = html_str.replace("<body>", "<body>" + bar_html, 1)
    elif bar_html and "</head>" in html_str:
        html_str = html_str.replace(
            "</head>", "</head>" + bar_html, 1,
        )

    injection = reg_block_html + bear_block_html
    if injection and "</body>" in html_str:
        html_str = html_str.replace(
            "</body>", injection + "</body>",
        )
    elif injection:
        html_str = html_str + injection

    # Editorial port (2026-04-29): the IC-packet HTML format is shared
    # with the standalone-export download (rcm_mc/exports/ic_packet.py)
    # so it ships its own <!DOCTYPE>+<head>+<body>. For the in-app
    # /diligence/ic-packet route we strip the body and re-wrap in
    # chartis_shell so the partner sees the navy topbar + parchment
    # palette consistent with every other partner page. The export
    # download path renders this HTML standalone elsewhere.
    import re
    body_match = re.search(
        r"<body[^>]*>(.*)</body>", html_str, re.DOTALL,
    )
    style_match = re.search(
        r"<style[^>]*>(.*?)</style>", html_str, re.DOTALL,
    )
    inner_body = body_match.group(1) if body_match else html_str
    extra_css = style_match.group(1) if style_match else None

    # Editorial header strip — partner sees which modules ran at a
    # glance before scrolling into the packet itself.
    modules_run = sum([
        bundle is not None,
        waterfall is not None,
        scan is not None,
        cfs is not None,
        steward is not None,
        cyber is not None,
        bool(public_comps) or transaction_band is not None,
        bool(autopsy_matches),
        reg_exposure is not None,
        bool(bear_block_html),
    ])
    rec_label = (meta.recommendation or "").replace("_", " ")
    rec_tone = (
        "negative" if "WALK" in (meta.recommendation or "")
        else "positive" if "PROCEED" in (meta.recommendation or "")
        else "warning"
    )
    runtime_header = (
        ck_source_purpose(
            purpose="Assemble a one-click, IC-ready packet — KPIs, bridge, bear case, regulatory, comps — from the full diligence pipeline in one pass.",
            universe="illustrative",
            confidence="derived",
            source=f"Run against the '{html.escape(str(dataset))}' CCD fixture + your entered deal economics; module outputs are illustrative on fixture data — re-run on the target's own data before a real IC.",
            next_action="Export the packet / preview the print version",
        )
        + ck_section_header(
            "Modules assembled into this packet",
            eyebrow="IC packet · runtime",
        )
        + '<div class="ck-kpi-strip">'
        + ck_kpi_block(
            "Recommendation",
            ck_signal_badge(rec_label or "—", tone=rec_tone),
            sub="partner-set; override in the URL",
        )
        + ck_kpi_block("Modules run", f"{modules_run} / 10")
        + ck_kpi_block(
            "Bear-case",
            "yes" if bear_block_html else "skipped",
            sub="auto-synthesized counter-narrative",
        )
        + ck_kpi_block(
            "Regulatory timeline",
            "yes" if reg_block_html else "skipped",
            sub="kill-date overlay attached" if reg_block_html else "no exposure data",
        )
        + '</div>'
    )

    # Add anchor ids to every h2 in the packet body, then build a
    # sticky right-rail TOC so partners can jump from "Headline
    # Numbers" to "Bear-case" or "Exit Strategy" without scrolling
    # the entire 80-100KB packet. Section count varies (some
    # modules skip when their inputs are missing) so we generate
    # the TOC from the rewritten body, not a hardcoded list.
    anchored_body, titles = _inject_h2_anchors(inner_body)
    # Print preview — partners frequently want to see the LP-facing
    # version before they hit Cmd+P. ?print=1 wraps the packet body
    # in .ck-print-preview (defined globally in chartis_shell CSS)
    # which shrinks to an 880px centered card with a bone-toned
    # control bar at top; the bar + the "Preview print version →"
    # link in the default view both display:none in @media print.
    preview = bool(qs.get("print"))
    # Build the URL the "Exit preview" link points back to — same
    # qs without the print flag — and the inverse URL the "Preview
    # print version →" link uses from the default view.
    base_qs = {k: v for k, v in qs.items() if k != "print"}
    pq = urllib.parse.urlencode(
        [(k, v[0] if isinstance(v, list) else v)
         for k, v in base_qs.items()],
        doseq=False,
    )
    preview_url = f"/diligence/ic-packet?{pq}&print=1"
    exit_url = f"/diligence/ic-packet?{pq}"

    if preview:
        body_with_toc = (
            '<div class="ck-print-preview">'
            '<div class="ck-print-preview-bar">'
            f'<span class="ck-print-preview-meta">Print preview · '
            f'{html.escape(meta.deal_name)}</span>'
            f'<a href="{html.escape(exit_url)}" '
            'class="ck-print-preview-exit">Exit preview</a>'
            '</div>'
            + runtime_header
            + anchored_body
            + '</div>'
        )
    elif titles:
        toc_sections = [{"id": s, "title": t} for (s, t) in titles]
        toc = ck_sticky_toc(toc_sections)
        body_with_toc = (
            '<div class="ck-print-preview-cta">'
            f'<a href="{html.escape(preview_url)}" class="ck-link">'
            'Preview print version →</a>'
            '</div>'
            + runtime_header
            + '<div class="ck-toc-layout">'
            + toc
            + '<div class="ck-toc-content">'
            + anchored_body
            + '</div></div>'
            + ck_next_section(
                "Return to the portfolio",
                "/portfolio",
                eyebrow="Continue —",
                italic_word="portfolio",
            )
        )
    else:
        body_with_toc = (
            '<div class="ck-print-preview-cta">'
            f'<a href="{html.escape(preview_url)}" class="ck-link">'
            'Preview print version →</a>'
            '</div>'
            + runtime_header + inner_body
            + ck_next_section(
                "Return to the portfolio",
                "/portfolio",
                eyebrow="Continue —",
                italic_word="portfolio",
            )
        )

    return chartis_shell(
        body_with_toc,
        title=f"IC Packet — {meta.deal_name}",
        active_nav="/pe-intelligence",
        extra_css=extra_css,
        editorial_intro={
            "eyebrow": "IC PACKET",
            "headline": "What the committee will read on this deal.",
            "italic_word": "will",
            "body": (
                "Auto-assembled IC deliverable for "
                f"{meta.deal_name} — thesis, base case, bear case, "
                "comparables, exit path, and the questions partners "
                "expect to be asked. Generated against the live packet."
            ),
        },
    )


_REG_BLOCK_CSS = """
<style>
.ic-reg-block{page-break-before:always;padding:28px 32px;
font-family:var(--sc-serif,Georgia,serif);color:#1a1a1a;}
.ic-reg-block .ic-reg-eyebrow{font-size:11px;letter-spacing:1.6px;
text-transform:uppercase;color:#7a8699;font-weight:600;}
.ic-reg-block h2{font-size:22px;margin:4px 0 10px 0;}
.ic-reg-block h3{font-size:14px;margin:16px 0 8px 0;}
.ic-reg-block .ic-reg-verdict{padding:12px 16px;background:#f7f3ea;
border-left:4px solid var(--vcol);border-radius:0 3px 3px 0;margin:12px 0;}
.ic-reg-block .ic-reg-verdict-label{font-size:11px;font-weight:700;
letter-spacing:1.2px;color:var(--vcol);text-transform:uppercase;}
.ic-reg-block .ic-reg-headline{font-size:14px;margin-top:6px;font-weight:600;}
.ic-reg-block .ic-reg-rationale{font-size:12px;color:#465366;
margin-top:6px;line-height:1.6;}
.ic-reg-block table{width:100%;border-collapse:collapse;font-size:12.5px;}
.ic-reg-block thead tr{background:#ece5d6;}
.ic-reg-block th{padding:6px 10px;text-align:left;border-bottom:2px solid #d6cfc0;}
.ic-reg-block td{padding:6px 10px;border-bottom:1px solid #e8e0d0;}
.ic-reg-block td.mono{font-family:monospace;}
.ic-reg-block td.tone-killed{color:#b5321e;font-weight:600;}
.ic-reg-block td.tone-damaged{color:#b8732a;font-weight:600;}
.ic-reg-block td.delta-neg{color:#b5321e;}
.ic-reg-block td.delta-pos{color:#0a8a5f;}
.ic-reg-block tr.ic-reg-total{border-top:2px solid #1a2332;font-weight:700;}
.ic-reg-block p.ic-reg-empty{font-size:13px;color:#465366;}
</style>
"""


def _render_regulatory_block(report: Any) -> str:
    """Compact Regulatory Calendar × Kill-Switch block for the IC
    Packet.  Deliberately standalone — the packet HTML is a
    separate template we don't rewrite here, we just append."""
    from ..diligence.regulatory_calendar.impact_mapper import (
        ImpactVerdict,
    )
    verdict_color = {
        "PASS": "#0a8a5f", "CAUTION": "#b8732a",
        "WARNING": "#b8732a", "FAIL": "#b5321e",
    }.get(report.verdict.value, "#7a8699")

    killed_rows: List[str] = []
    for tl in report.driver_timelines:
        if tl.worst_verdict.value == "UNAFFECTED":
            continue
        tone_cls = {
            "KILLED": "tone-killed", "DAMAGED": "tone-damaged",
        }.get(tl.worst_verdict.value, "")
        killed_rows.append(
            f'<tr>'
            f'<td>{html.escape(tl.driver_label)}</td>'
            f'<td class="{tone_cls}">{tl.worst_verdict.value}</td>'
            f'<td class="mono">{tl.first_kill_date or "—"}</td>'
            f'<td>{tl.residual_lift_pct*100:.2f} pp of '
            f'{tl.expected_lift_pct*100:.2f} pp claimed</td>'
            f'</tr>'
        )

    overlay_rows: List[str] = []
    for o in report.ebitda_overlay:
        delta_cls = (
            "delta-neg" if o.ebitda_delta_usd < 0 else "delta-pos"
        )
        overlay_rows.append(
            f'<tr>'
            f'<td>{o.year}</td>'
            f'<td class="mono {delta_cls}">${o.ebitda_delta_usd:+,.0f}</td>'
            f'<td>{o.margin_delta_pp:+.2f} pp margin '
            f'· {len(o.driving_events)} event'
            f'{"s" if len(o.driving_events) != 1 else ""}</td>'
            f'</tr>'
        )
    total_eb = sum(o.ebitda_delta_usd for o in report.ebitda_overlay)
    total_cls = "delta-neg" if total_eb < 0 else "delta-pos"

    return (
        _REG_BLOCK_CSS
        + f'<section class="ic-reg-block ic-section" '
        f'style="--vcol:{verdict_color};">'
        '<div class="ic-reg-eyebrow">Regulatory Calendar × Kill-Switch</div>'
        '<h2>Thesis timeline — which drivers die, and when</h2>'
        '<div class="ic-reg-verdict">'
        f'<div class="ic-reg-verdict-label">Verdict: {report.verdict.value}</div>'
        f'<div class="ic-reg-headline">{html.escape(report.headline)}</div>'
        f'<div class="ic-reg-rationale">{html.escape(report.rationale)}</div>'
        '</div>'
        + (
            '<h3>Impaired thesis drivers</h3>'
            '<table>'
            '<thead><tr>'
            '<th>Driver</th><th>Verdict</th>'
            '<th>First Kill Date</th><th>Residual Lift</th>'
            f'</tr></thead><tbody>{"".join(killed_rows)}</tbody></table>'
            if killed_rows else
            '<p class="ic-reg-empty">'
            'No thesis drivers impaired within the 24-month horizon.</p>'
        )
        + (
            '<h3>EBITDA bridge overlay</h3>'
            '<table>'
            '<thead><tr>'
            '<th>Year</th><th>EBITDA Δ (USD)</th><th>Notes</th>'
            f'</tr></thead><tbody>{"".join(overlay_rows)}'
            '<tr class="ic-reg-total">'
            '<td>TOTAL</td>'
            f'<td class="mono {total_cls}">${total_eb:+,.0f}</td>'
            '<td></td></tr>'
            '</tbody></table>'
            if overlay_rows else ''
        )
        + '</section>'
    )


def _derive_walkaway(cfs: Any) -> Optional[List[str]]:
    """Auto-derive walkaway conditions from the counterfactual set:
    every RED/CRITICAL counterfactual with LOW feasibility becomes a
    walkaway condition (the partner can't cleanly remediate it)."""
    if cfs is None:
        return None
    items = getattr(cfs, "items", []) or []
    out = []
    for cf in items:
        feas = getattr(cf, "feasibility", "")
        if feas != "LOW":
            continue
        module = getattr(cf, "module", "")
        change = getattr(cf, "change_description", "")
        out.append(f"{module}: {change}")
    return out or None
