"""Ranked "best of <section>" index — the page each nav bar's "show more"
opens.

Mirrors the /diligence index pattern: an editorial, evidence-first catalog of
a section's surfaces, but ordered by the surface ranking (usefulness-weighted)
from ``_surface_rankings.RANKINGS`` (generated by scripts/rank_surfaces.py).
Each row carries its data-honesty tier and score so a partner sees *why* a page
leads. No fabricated entries — every row is a real, route-backed page.
"""
from __future__ import annotations

from typing import Dict, List, Optional

_SECTION_TITLE = {
    "source": "Source", "pipeline": "Pipeline", "diligence": "Diligence",
    "library": "Library", "research": "Research", "portfolio": "Portfolio",
    "home": "Home",
}
_TIER_DOT = {
    "green": ("#0a8a5f", "LIVE — real data"),
    "navy": ("#15324f", "Computed / model"),
    "data_required": ("#b8732a", "DATA REQUIRED"),
    "yellow": ("#c9a227", "Illustrative"),
    "red": ("#b5321e", "Placeholder"),
}

_CSS = """
.sb-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin:16px 0;}
@media (max-width:820px){.sb-grid{grid-template-columns:1fr;}}
.sb-card{display:flex;flex-direction:column;gap:6px;background:var(--sc-paper,#faf6ec);
 border:1px solid var(--sc-rule,#c9c1ac);border-left:3px solid var(--sc-teal,#155752);
 padding:13px 16px;text-decoration:none;}
.sb-card:hover{box-shadow:var(--sc-shadow-2,0 8px 24px rgba(11,32,55,.14));}
.sb-rank{font-family:var(--sc-serif);font-style:italic;font-size:18px;color:var(--sc-teal,#155752);}
.sb-label{font-family:var(--sc-serif);font-size:17px;color:var(--sc-navy,#15202b);line-height:1.15;}
.sb-meta{display:flex;align-items:center;gap:8px;font-family:var(--sc-mono);font-size:10px;
 letter-spacing:.04em;color:var(--sc-text-dim,#6a7480);}
.sb-dot{width:9px;height:9px;border-radius:50%;display:inline-block;}
.sb-score{margin-left:auto;font-weight:600;color:var(--sc-navy,#15202b);}
.sb-route{font-family:var(--sc-mono);font-size:10px;color:var(--sc-text-faint,#8b94a0);}
"""


def render_section_best(section: str, qs: Optional[Dict] = None) -> str:
    from ._chartis_kit import (chartis_shell, ck_page_title, ck_panel,
                               ck_source_purpose)
    try:
        from ._surface_rankings import RANKINGS
    except Exception:  # noqa: BLE001
        RANKINGS = {}
    import html as _h

    section = (section or "").strip().lower()
    title = _SECTION_TITLE.get(section, section.title() or "Section")
    rows: List[Dict] = list(RANKINGS.get(section, []))

    head = ck_page_title(
        f"All {title} tools",
        eyebrow=f"{title.upper()}",
        meta=(f"{len(rows)} tools" if rows else "no tools yet"),
    )
    src = ck_source_purpose(
        purpose=f"Everything in {title}, ordered best-first. Open any tool — "
                "the dot shows whether it runs on live data, a computed model, "
                "or illustrative figures.",
        universe="derived",
        source="Every row is a real, route-backed page.",
        confidence="derived",
        next_action=f"Open the first {title} tool",
        next_href=(rows[0]["route"] if rows else "/home"),
    )

    if not rows:
        body = head + src + ck_panel(
            f'<p class="ck-section-body">No ranked surfaces for “{_h.escape(title)}” '
            'yet. Run <code>python scripts/rank_surfaces.py</code> to refresh the '
            'manifest.</p>', title="Nothing ranked")
        return chartis_shell(body, f"{title} — best", active_nav="/" + section,
                             extra_css=_CSS)

    cards = []
    for r in rows:
        color, label = _TIER_DOT.get(r.get("tier", ""), ("#8b94a0", "—"))
        cards.append(
            f'<a class="sb-card" href="{_h.escape(r["route"])}">'
            f'<div class="sb-meta">'
            f'<span class="sb-dot" style="background:{color}"></span>'
            f'<span>{_h.escape(label)}</span></div>'
            f'<div class="sb-label">{_h.escape(r["label"])}</div>'
            f'<div class="sb-route">{_h.escape(r["route"])}</div></a>'
        )
    grid = f'<div class="sb-grid">{"".join(cards)}</div>'
    body = head + src + grid
    return chartis_shell(body, f"All {title} tools", active_nav="/" + section,
                         extra_css=_CSS)
