"""Real geographic US state map (SVG paths) for the Portfolio Map.

Drop-in replacement for the old tile-grid cartogram (`render_us_state_map`):
same call signature, but renders the actual contiguous-US geography from
vendored Albers-projected state paths (`_us_geo_paths.py`, generated by
`tools/build_us_geo_paths.py` from the public-domain US Census GeoJSON).
Alaska & Hawaii are scaled bottom-left insets. 100% local — no map tiles, no
GeoJSON fetch, no external APIs at runtime.

States shade on a cream→green scale by value; Certificate-of-Need (accent)
states carry an amber outline; the selected state a navy outline. Click or
keyboard-activate a state to dispatch a ``us-map-select`` CustomEvent (same
event the old cartogram emitted) so existing page wiring keeps working.
"""
from __future__ import annotations

import html as _html
from typing import Callable, Dict, List, Optional

from ._us_geo_paths import US_GEO_VIEWBOX, US_STATE_PATHS

_NODATA = "#e7dfca"      # muted cream — state with no value
_G_LO = (214, 232, 223)  # light green
_G_HI = (24, 87, 63)     # green-deep
_ACCENT = "#b8842e"      # amber — CON / accent jurisdictions
_uid = [0]


def _esc(s) -> str:
    return _html.escape("" if s is None else str(s))


def _shade(value: Optional[float], lo: float, hi: float) -> str:
    if value is None:
        return _NODATA
    if hi <= lo:
        t = 1.0
    else:
        t = max(0.0, min(1.0, (value - lo) / (hi - lo)))
    r = round(_G_LO[0] + (_G_HI[0] - _G_LO[0]) * t)
    g = round(_G_LO[1] + (_G_HI[1] - _G_LO[1]) * t)
    b = round(_G_LO[2] + (_G_HI[2] - _G_LO[2]) * t)
    return f"rgb({r},{g},{b})"


_CSS = """
#{cid}{{font-family:var(--sc-mono,monospace);}}
#{cid} .usgeo-svg{{width:100%;height:auto;display:block;background:var(--sc-bone,#f3eddb);
 border:1px solid var(--sc-rule,#c9c1ac);}}
#{cid} .usgeo-state{{stroke:#fbf7ee;stroke-width:0.6;transition:filter .12s,stroke .12s;}}
#{cid} .usgeo-state[data-clickable='1']{{cursor:pointer;}}
#{cid} .usgeo-state[data-clickable='1']:hover{{filter:brightness(.92);stroke:var(--sc-navy,#0b2341);stroke-width:1.1;}}
#{cid} .usgeo-state[data-clickable='1']:focus-visible{{outline:none;stroke:var(--sc-teal,#1f7a5a);stroke-width:2;}}
#{cid} .usgeo-state.usgeo-accent{{stroke:{ac};stroke-width:1.5;}}
#{cid} .usgeo-state.usgeo-selected{{stroke:var(--sc-navy,#0b2341);stroke-width:2.4;}}
#{cid} .usgeo-inset-label{{font-size:11px;fill:var(--sc-text-dim,#6a7480);
 letter-spacing:.1em;text-transform:uppercase;font-family:var(--sc-mono,monospace);}}
#{cid} .usgeo-legend{{display:flex;flex-wrap:wrap;gap:16px;align-items:center;
 margin:12px 2px 0;font-size:11px;letter-spacing:.04em;color:var(--sc-text-dim,#6a7480);
 text-transform:uppercase;}}
#{cid} .usgeo-legend .it{{display:inline-flex;align-items:center;gap:6px;}}
#{cid} .usgeo-legend .sw{{width:14px;height:14px;border:1px solid var(--sc-rule,#c9c1ac);}}
#{cid} .usgeo-legend .sw.grad{{background:linear-gradient(90deg,rgb(214,232,223),rgb(24,87,63));width:48px;}}
#{cid} .usgeo-legend .sw.con{{background:transparent;border:2px solid {ac};}}
#{cid} .usgeo-legend .sw.sel{{background:transparent;border:2px solid var(--sc-navy,#0b2341);}}
#{cid} .usgeo-caveat{{font-family:var(--sc-serif,Georgia,serif);font-style:italic;
 font-size:12.5px;line-height:1.5;color:var(--sc-text-dim,#6a7480);
 margin:10px 2px 0;max-width:80ch;}}
#{cid} .usgeo-empty{{font-family:var(--sc-serif,Georgia,serif);font-style:italic;
 font-size:14px;color:var(--sc-text-dim,#6a7480);margin:0 2px 10px;}}
"""


def _js(cid: str, link_template: str = "") -> str:
    # When a link template is supplied, clicking/Enter on a state navigates to
    # the templated URL (drill-down) — restoring the click-through the tile-grid
    # map had. With no template, click just highlights + emits us-map-select for
    # pages that drive their own behavior off the event.
    import json as _json
    tpl = _json.dumps(link_template or "")
    return (
        "<script>(function(){var root=document.getElementById('" + cid + "');"
        "if(!root)return;var TPL=" + tpl + ";"
        "function sel(st){root.querySelectorAll('.usgeo-state.usgeo-selected')"
        ".forEach(function(o){o.classList.remove('usgeo-selected');});"
        "var t=root.querySelector('.usgeo-state[data-state=\"'+st+'\"]');"
        "if(t)t.classList.add('usgeo-selected');"
        "document.dispatchEvent(new CustomEvent('us-map-select',{detail:{state:st}}));}"
        "root.querySelectorAll('.usgeo-state[data-clickable=\"1\"]').forEach(function(p){"
        "function go(){var st=p.getAttribute('data-state');"
        "if(TPL){window.location.href=TPL.replace('{state}',encodeURIComponent(st));return;}"
        "sel(st);}"
        "p.style.cursor=TPL?'pointer':'';"
        "p.addEventListener('click',go);"
        "p.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' ')"
        "{e.preventDefault();go();}});});})();</script>"
    )


def render_us_geo_map(
    values: Dict[str, float],
    *,
    metric_label: str = "deals",
    value_format: Optional[Callable[[float], str]] = None,
    state_notes: Optional[Dict[str, str]] = None,
    accent_states: Optional[set] = None,
    accent_label: str = "accent jurisdiction",
    selected_state: Optional[str] = None,
    state_link_template: str = "",
    empty_message: str = "",
    map_title: str = "United States portfolio map",
    exposure_label: str = "Portfolio exposure (low&nbsp;→&nbsp;high concentration)",
    caveat_text: str = (
        "Approximate geographic SVG map (Albers projection of US Census state "
        "boundaries, public domain). State shading reflects PEdesk portfolio "
        "records with state-level geography; outlined states are the accent "
        "jurisdictions named in the legend. This is not a precise coastline or "
        "facility-location map."
    ),
) -> str:
    """Self-contained SVG geographic US map. Signature mirrors
    ``us_map.render_us_state_map`` so it is a drop-in replacement.

    ``map_title`` / ``exposure_label`` / ``caveat_text`` default to the
    portfolio-map wording (so /portfolio/map is unchanged) but let other
    surfaces — e.g. the Target Screener shading states by provider count —
    relabel the title, legend gradient, and caveat honestly."""
    _uid[0] += 1
    cid = f"usgeo{_uid[0]}"
    values = {str(k).upper(): float(v) for k, v in (values or {}).items()}
    accent = {str(s).upper() for s in (accent_states or set())}
    notes = {str(k).upper(): v for k, v in (state_notes or {}).items()}
    sel = (selected_state or "").upper()
    fmt = value_format or (lambda v: f"{v:g}")
    has_data = bool(values)
    lo = min(values.values()) if values else 0.0
    hi = max(values.values()) if values else 1.0

    paths = []
    for abbr, rec in US_STATE_PATHS.items():
        v = values.get(abbr)
        fill = _shade(v, lo, hi)
        cls = "usgeo-state"
        if abbr in accent:
            cls += " usgeo-accent"
        if abbr == sel:
            cls += " usgeo-selected"
        clickable = "1" if (state_link_template or True) else "0"
        # Honest aria-label: name + value (or "no data") + accent note.
        if v is not None:
            vlabel = f"{fmt(v)} {metric_label}"
        else:
            vlabel = f"no {metric_label} data"
        alabel = f"{rec['name']} — {vlabel}"
        if abbr in accent:
            alabel += f"; {accent_label}"
        title_attr = notes.get(abbr, "")
        paths.append(
            f'<path class="{cls}" data-state="{abbr}" d="{rec["d"]}" '
            f'fill="{fill}" data-clickable="{clickable}" tabindex="0" '
            f'role="button" aria-label="{_esc(alabel)}">'
            + (f"<title>{_esc(rec['name'])}: {_esc(title_attr)}</title>"
               if title_attr else f"<title>{_esc(alabel)}</title>")
            + "</path>"
        )

    vb = " ".join(str(n) for n in US_GEO_VIEWBOX)
    inset_labels = (
        f'<text class="usgeo-inset-label" x="10" y="{US_GEO_VIEWBOX[3]-118}">Alaska</text>'
        f'<text class="usgeo-inset-label" x="187" y="{US_GEO_VIEWBOX[3]-118}">Hawaii</text>'
    )
    svg = (
        f'<svg class="usgeo-svg" viewBox="{vb}" role="img" '
        f'aria-labelledby="{cid}-t {cid}-d" preserveAspectRatio="xMidYMid meet">'
        f'<title id="{cid}-t">{_esc(map_title)}</title>'
        f'<desc id="{cid}-d">Geographic map of US states shaded by '
        f'{_esc(metric_label)}; Alaska and Hawaii shown as bottom-left insets. '
        'Outlined states are accent jurisdictions.</desc>'
        + "".join(paths) + inset_labels + "</svg>"
    )

    legend = (
        '<div class="usgeo-legend">'
        f'<span class="it"><span class="sw" style="background:{_NODATA}"></span>No data</span>'
        f'<span class="it"><span class="sw grad"></span>{exposure_label}</span>'
        f'<span class="it"><span class="sw con"></span>{_esc(accent_label)}</span>'
        '<span class="it"><span class="sw sel"></span>Selected state</span>'
        '</div>'
    )
    caveat = f'<p class="usgeo-caveat">{_esc(caveat_text)}</p>'
    empty = ""
    if not has_data and empty_message:
        empty = f'<p class="usgeo-empty">{_esc(empty_message)}</p>'

    css = _CSS.format(cid=cid, ac=_ACCENT)
    return (
        f'<div id="{cid}"><style>{css}</style>'
        + empty + svg + legend + caveat + _js(cid, state_link_template) + '</div>'
    )
