"""Internal /v3-status dashboard for the v3 transformation campaign.

Reads ``docs/V3_ROUTE_INVENTORY.md`` (generated by
``RCM_MC/tools/v3_route_inventory.py`` per campaign target 1B), parses
the compliance summary table + packet-driven count, and renders an
editorial-shell HTML page with the numbers in tabular-nums.

Why this exists:
    Until 1D, the campaign progress was tracked in commit messages.
    Re-reading commit prose every loop is fragile. /v3-status surfaces
    the same counts as a live page so contributors can hit one URL
    and see "where are we?" without grepping git log.

Why this page is exempt from the DealAnalysisPacket invariant:
    CLAUDE.md says every UI page must render from
    ``get_or_build_packet(deal_id)``. That invariant exists for
    partner-facing analytical pages — every deal view must pull its
    state from the canonical dataclass so audit and UI stay
    consistent. /v3-status is an internal tooling dashboard about the
    migration itself, not analytical content about a deal. There is
    no deal_id; the source of truth is the inventory file. This page
    is one of the rare exceptions and is documented as such here.

Composability:
    Uses fmt_num / fmt_pct from rcm_mc.ui._ui_kit (campaign target
    1C). Re-running the route inventory generator after a migration
    commit automatically refreshes what this page shows.
"""
from __future__ import annotations

import html as _html
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import NamedTuple

from ._chartis_kit import (
    chartis_shell, ck_eyebrow, ck_fmt_num, ck_kpi_block,
    ck_next_section, ck_provenance_tooltip,
)
from ._ui_kit import fmt_num, fmt_pct

REPO_ROOT = Path(__file__).resolve().parents[3]
INVENTORY_PATH = REPO_ROOT / "docs" / "V3_ROUTE_INVENTORY.md"


class StatusCounts(NamedTuple):
    """Parsed campaign progress numbers."""
    total: int
    v3: int
    legacy: int
    bespoke: int
    redirect: int
    unknown: int
    packet_driven: int
    inventory_mtime_iso: str  # ISO date string of inventory file mtime
    inventory_present: bool


_TOTAL_RE = re.compile(r"\*\*Total routes mapped:\*\*\s+(\d+)")
_PACKET_RE = re.compile(r"\*\*Packet-driven[^*]*?\*\*[^|]*?(\d+)\s+of\s+(\d+)")
_ROW_RE = re.compile(r"^\|\s+([^|]+?)\s+\|\s+(\d+)\s+\|", re.M)


def parse_inventory(text: str, *, chrome_prefix: str = "v3") -> StatusCounts:
    """Pull the four campaign numbers out of the inventory markdown.

    Resilient to caveat-text drift but assumes the compliance-summary
    table rows still start with the canonical labels (``v3`` or
    ``v5`` for the chartis bucket, ``legacy``, ``bespoke``,
    ``redirect``, ``unknown``) — those are what the generator emits
    and what 1B's regression test pins.

    ``chrome_prefix`` selects which label prefixes the chartis-route
    count (``StatusCounts.v3`` field stores that count regardless of
    name — it is the "chartis-classified" bucket from the inventory).
    """
    total_m = _TOTAL_RE.search(text)
    total = int(total_m.group(1)) if total_m else 0

    rows = {label.strip().lower(): int(count) for label, count in _ROW_RE.findall(text)}
    def _lookup(prefix: str) -> int:
        for label, count in rows.items():
            if label.startswith(prefix):
                return count
        return 0

    packet_m = _PACKET_RE.search(text)
    packet = int(packet_m.group(1)) if packet_m else 0

    return StatusCounts(
        total=total,
        v3=_lookup(chrome_prefix),
        legacy=_lookup("legacy"),
        bespoke=_lookup("bespoke"),
        redirect=_lookup("redirect"),
        unknown=_lookup("unknown"),
        packet_driven=packet,
        inventory_mtime_iso="",  # filled in by render_v3_status
        inventory_present=True,
    )


def _empty_counts(present: bool, mtime_iso: str = "") -> StatusCounts:
    return StatusCounts(
        total=0, v3=0, legacy=0, bespoke=0, redirect=0,
        unknown=0, packet_driven=0,
        inventory_mtime_iso=mtime_iso, inventory_present=present,
    )


def _kpi_card(label: str, value_html: str, sub: str = "") -> str:
    """Single editorial-style KPI block. Pure HTML, no external CSS
    needed beyond what /static/v3/chartis.css already provides."""
    sub_html = (
        f'<div class="micro" style="margin-top:.25rem;">{_html.escape(sub)}</div>'
        if sub else ""
    )
    return (
        '<div style="border:1px solid var(--border,#D6CFC0);'
        'background:var(--paper,#FAF7F0);'
        'padding:1rem 1.25rem;border-radius:6px;min-width:9rem;flex:1;">'
        f'<div class="micro">{_html.escape(label)}</div>'
        f'<div style="font-size:1.6rem;font-weight:600;margin-top:.35rem;">{value_html}</div>'
        f"{sub_html}"
        '</div>'
    )


def render_v3_status() -> str:
    """Top-level renderer. Returns a complete HTML document via
    chartis_shell. Wired to GET /v3-status in server.py."""
    if INVENTORY_PATH.is_file():
        text = INVENTORY_PATH.read_text(encoding="utf-8")
        counts = parse_inventory(text)
        mtime = datetime.fromtimestamp(
            INVENTORY_PATH.stat().st_mtime, tz=timezone.utc
        )
        counts = counts._replace(inventory_mtime_iso=mtime.date().isoformat())
    else:
        counts = _empty_counts(present=False)

    if not counts.inventory_present:
        body = (
            '<section class="prose">'
            '<h2>Inventory missing</h2>'
            '<p>'
            '<code>docs/V3_ROUTE_INVENTORY.md</code> is not present. '
            'Run <code>python3 RCM_MC/tools/v3_route_inventory.py</code> '
            'from the repo root to regenerate it. The status page reads '
            'campaign progress from that file.'
            '</p>'
            '</section>'
        )
        return chartis_shell(body, "v3 Status — Inventory Missing", subtitle="")

    pct_v3 = (100.0 * counts.v3 / counts.total) if counts.total else 0.0
    pct_packet = (100.0 * counts.packet_driven / counts.total) if counts.total else 0.0

    # Cycle 48 — port to ck_kpi_block + provenance.
    chrome_value = ck_provenance_tooltip(
        "v3 chrome adoption",
        ck_fmt_num(counts.v3),
        explainer=(
            f"Routes rendering through chartis_shell or living "
            f"under rcm_mc/ui/chartis/ ({pct_v3:.1f}% of "
            f"{counts.total} routes). The campaign predecessor to "
            f"the v5 effort - v3 is essentially complete; the "
            f"remaining gap is the structural-port cluster."
        ),
    )
    packet_value = ck_provenance_tooltip(
        "Packet-driven routes",
        ck_fmt_num(counts.packet_driven),
        explainer=(
            "Renderers calling get_or_build_packet or importing "
            "DealAnalysisPacket. CLAUDE.md invariant: every "
            "partner-facing analytical page should reach the "
            "packet. Detection is heuristic - the real number is "
            "higher than this."
        ),
        inject_css=False,
    )
    kpi_grid = (
        f'<div class="ck-kpi-grid" style="grid-template-columns:repeat(7,1fr);gap:8px;margin:1.25rem 0;">'
        + ck_kpi_block("Total Routes", ck_fmt_num(counts.total), "in inventory")
        + ck_kpi_block("v3 Chrome", chrome_value, f"{pct_v3:.1f}%")
        + ck_kpi_block("Legacy Shell", ck_fmt_num(counts.legacy), "_ui_kit only")
        + ck_kpi_block("Bespoke", ck_fmt_num(counts.bespoke), "no shell")
        + ck_kpi_block("Redirects", ck_fmt_num(counts.redirect), "non-rendering")
        + ck_kpi_block("Unresolved", ck_fmt_num(counts.unknown), "needs triage")
        + ck_kpi_block("Packet-driven", packet_value, f"of {counts.total}")
        + '</div>'
    )

    progress_table = (
        '<h2 style="margin-top:1.5rem;">Compliance summary</h2>'
        '<table class="ck-table" style="margin-top:.5rem;">'
        '<thead><tr><th>Status</th><th style="text-align:right;">Count</th>'
        '<th style="text-align:right;">% of total</th></tr></thead><tbody>'
        + "".join(
            f'<tr><td>{_html.escape(label)}</td>'
            f'<td style="text-align:right;">{fmt_num(count)}</td>'
            f'<td style="text-align:right;">{fmt_pct(100.0 * count / counts.total if counts.total else 0)}</td>'
            f'</tr>'
            for label, count in (
                ("v3 (chartis_shell or under ui/chartis/)", counts.v3),
                ("legacy (shell from _ui_kit only)", counts.legacy),
                ("bespoke (no shell — direct HTML)", counts.bespoke),
                ("redirect", counts.redirect),
                ("unknown / unresolved", counts.unknown),
            )
        )
        + '</tbody></table>'
    )

    packet_section = (
        '<h2 style="margin-top:1.5rem;">DealAnalysisPacket adoption</h2>'
        '<p>Renderers calling <code>get_or_build_packet</code> or '
        f'importing <code>DealAnalysisPacket</code>: {fmt_num(counts.packet_driven)} '
        f'of {fmt_num(counts.total)} ({fmt_pct(pct_packet)}). '
        'CLAUDE.md invariant: every partner-facing analytical page '
        'should reach the packet. Detection here is heuristic '
        '(immediate renderer file only); the real number is higher.</p>'
    )

    foot = (
        f'<p class="micro" style="margin-top:2rem;">Inventory regenerated '
        f'{_html.escape(counts.inventory_mtime_iso)} (UTC). '
        f'Re-run <code>RCM_MC/tools/v3_route_inventory.py</code> after any '
        f'page migration to refresh these numbers.</p>'
    )

    body = (
        '<section style="max-width:62rem;">'
        '<p class="micro">v3 Transformation Campaign — '
        '<strong>saving-seeking-chartis</strong> branch</p>'
        '<p>Campaign progress map. Numbers come from '
        '<code>docs/V3_ROUTE_INVENTORY.md</code>.</p>'
        + kpi_grid
        + progress_table
        + packet_section
        + foot
        + '</section>'
        + ck_next_section(
            "Open the v5 transformation status",
            "/v5-status",
            eyebrow="Continue —",
            italic_word="v5",
        )
    )

    # 2026-05-28 batch 29 · Phase 3 · universal strict 5-block head.
    from ._chartis_kit import ck_editorial_head
    head = ck_editorial_head(
        eyebrow="V3 STATUS",
        title="Where the v3 transformation landed.",
        meta=(
            f"{counts.total} ROUTES · "
            f"{counts.v3} V3 ({pct_v3:.0f}%) · "
            f"{counts.packet_driven} PACKET-DRIVEN ({pct_packet:.0f}%)"
        ),
        lede_italic_phrase="Where the v3 transformation landed.",
        lede_body=(
            "Predecessor to the v5 editorial campaign. v3 "
            "ported every renderer to chartis_shell; v5 added "
            "italic-serif headlines, primitive density, "
            "provenance, and ck_fmt_* discipline on top. "
            "Numbers come from the route inventory."
        ),
    )
    body = head + body
    return chartis_shell(
        body,
        "v3 Transformation Status",
        subtitle="campaign progress · saving-seeking-chartis",
    )
