"""Internal /v5-status dashboard for the v5 Chartis transformation campaign.

Reads ``docs/V5_ROUTE_INVENTORY.md`` (generated by
``RCM_MC/tools/v3_route_inventory.py --v5`` per campaign targets 1B+1D),
parses the compliance summary + packet-driven count, and renders via
``chartis_shell`` with the same KPI layout as ``/v3-status``.

This mirrors ``v3_status_page`` for the v5 campaign naming; the
underlying route classification is shared with the v3 inventory
generator (chartis-reachable bucket labeled ``v5`` in the markdown).

Exempt from the DealAnalysisPacket invariant for the same reasons as
``/v3-status`` — migration metadata, not deal analytics.
"""
from __future__ import annotations

import html as _html
from datetime import datetime, timezone
from pathlib import Path

from ._chartis_kit import chartis_shell
from ._ui_kit import fmt_num, fmt_pct
from .v3_status_page import _empty_counts, _kpi_card, parse_inventory

REPO_ROOT = Path(__file__).resolve().parents[3]
INVENTORY_PATH = REPO_ROOT / "docs" / "V5_ROUTE_INVENTORY.md"


def render_v5_status() -> str:
    """GET /v5-status — full HTML via chartis_shell."""
    if INVENTORY_PATH.is_file():
        text = INVENTORY_PATH.read_text(encoding="utf-8")
        counts = parse_inventory(text, chrome_prefix="v5")
        mtime = datetime.fromtimestamp(
            INVENTORY_PATH.stat().st_mtime, tz=timezone.utc
        )
        counts = counts._replace(inventory_mtime_iso=mtime.date().isoformat())
    else:
        counts = _empty_counts(present=False)

    if not counts.inventory_present:
        body = (
            '<section class="prose">'
            "<h2>Inventory missing</h2>"
            "<p>"
            "<code>docs/V5_ROUTE_INVENTORY.md</code> is not present. "
            "Run <code>python3 RCM_MC/tools/v3_route_inventory.py --v5</code> "
            "from the repo root to regenerate it."
            "</p>"
            "</section>"
        )
        return chartis_shell(body, "v5 Status — Inventory Missing", subtitle="")

    pct_chrome = (100.0 * counts.v3 / counts.total) if counts.total else 0.0
    pct_packet = (100.0 * counts.packet_driven / counts.total) if counts.total else 0.0

    kpi_grid = (
        '<div style="display:flex;gap:1rem;flex-wrap:wrap;margin:1.25rem 0;">'
        + _kpi_card("Total routes", fmt_num(counts.total))
        + _kpi_card(
            "v5 chrome",
            fmt_num(counts.v3),
            sub=f"of {counts.total} ({pct_chrome:.1f}%)",
        )
        + _kpi_card("Legacy shell", fmt_num(counts.legacy))
        + _kpi_card("Bespoke (no shell)", fmt_num(counts.bespoke))
        + _kpi_card("Redirects", fmt_num(counts.redirect))
        + _kpi_card("Unresolved", fmt_num(counts.unknown))
        + _kpi_card(
            "Packet-driven",
            fmt_num(counts.packet_driven),
            sub=f"of {counts.total}",
        )
        + "</div>"
    )

    progress_table = (
        '<h2 style="margin-top:1.5rem;">Compliance summary</h2>'
        '<table class="ck-table" style="margin-top:.5rem;">'
        '<thead><tr><th>Status</th><th style="text-align:right;">Count</th>'
        '<th style="text-align:right;">% of total</th></tr></thead><tbody>'
        + "".join(
            f'<tr><td>{_html.escape(label)}</td>'
            f'<td style="text-align:right;">{fmt_num(count)}</td>'
            f'<td style="text-align:right;">{fmt_pct(100.0 * count / counts.total if counts.total else 0)}</td>'
            f"</tr>"
            for label, count in (
                ("v5 (chartis_shell or under ui/chartis/)", counts.v3),
                ("legacy (shell from _ui_kit only)", counts.legacy),
                ("bespoke (no shell — direct HTML)", counts.bespoke),
                ("redirect", counts.redirect),
                ("unknown / unresolved", counts.unknown),
            )
        )
        + "</tbody></table>"
    )

    packet_section = (
        '<h2 style="margin-top:1.5rem;">DealAnalysisPacket adoption</h2>'
        "<p>Renderers calling <code>get_or_build_packet</code> or "
        f"importing <code>DealAnalysisPacket</code>: {fmt_num(counts.packet_driven)} "
        f"of {fmt_num(counts.total)} ({fmt_pct(pct_packet)}). "
        "CLAUDE.md invariant: every partner-facing analytical page "
        "should reach the packet. Detection here is heuristic "
        "(immediate renderer file only); the real number is higher.</p>"
    )

    foot = (
        f'<p class="micro" style="margin-top:2rem;">Inventory regenerated '
        f"{_html.escape(counts.inventory_mtime_iso)} (UTC). "
        f"Re-run <code>python3 RCM_MC/tools/v3_route_inventory.py --v5</code> after any "
        f"page migration to refresh these numbers.</p>"
    )

    body = (
        '<section style="max-width:62rem;">'
        '<p class="micro">v5 Chartis campaign — '
        "<strong>saving-seeking-chartis</strong> branch</p>"
        '<h1 style="margin-top:.25rem;">v5 status</h1>'
        "<p>Campaign progress map. Numbers come from "
        "<code>docs/V5_ROUTE_INVENTORY.md</code>.</p>"
        + kpi_grid
        + progress_table
        + packet_section
        + foot
        + "</section>"
    )

    return chartis_shell(
        body,
        "v5 Transformation Status",
        subtitle="campaign progress · saving-seeking-chartis",
    )
