"""Internal /v5-status dashboard for the v5 Chartis transformation campaign.

Reads ``docs/V5_ROUTE_INVENTORY.md`` (generated by
``RCM_MC/tools/v3_route_inventory.py --v5`` per campaign targets 1B+1D),
parses the compliance summary + packet-driven count, and renders via
``chartis_shell`` with the same KPI layout as ``/v3-status``.

This mirrors ``v3_status_page`` for the v5 campaign naming; the
underlying route classification is shared with the v3 inventory
generator (chartis-reachable bucket labeled ``v5`` in the markdown).

Exempt from the DealAnalysisPacket invariant for the same reasons as
``/v3-status`` — migration metadata, not deal analytics.
"""
from __future__ import annotations

import html as _html
from datetime import datetime, timezone
from pathlib import Path

from ._chartis_kit import (
    chartis_shell, ck_eyebrow, ck_fmt_num,
    ck_kpi_block, ck_next_section, ck_provenance_tooltip,
)
from ._ui_kit import fmt_num, fmt_pct
from .v3_status_page import _empty_counts, _kpi_card, parse_inventory

REPO_ROOT = Path(__file__).resolve().parents[3]
INVENTORY_PATH = REPO_ROOT / "docs" / "V5_ROUTE_INVENTORY.md"


def render_v5_status() -> str:
    """GET /v5-status — full HTML via chartis_shell."""
    if INVENTORY_PATH.is_file():
        text = INVENTORY_PATH.read_text(encoding="utf-8")
        counts = parse_inventory(text, chrome_prefix="v5")
        mtime = datetime.fromtimestamp(
            INVENTORY_PATH.stat().st_mtime, tz=timezone.utc
        )
        counts = counts._replace(inventory_mtime_iso=mtime.date().isoformat())
    else:
        counts = _empty_counts(present=False)

    if not counts.inventory_present:
        body = (
            '<section class="prose">'
            "<h2>Inventory missing</h2>"
            "<p>"
            "<code>docs/V5_ROUTE_INVENTORY.md</code> is not present. "
            "Run <code>python3 RCM_MC/tools/v3_route_inventory.py --v5</code> "
            "from the repo root to regenerate it."
            "</p>"
            "</section>"
        )
        return chartis_shell(body, "v5 Status — Inventory Missing", subtitle="")

    pct_chrome = (100.0 * counts.v3 / counts.total) if counts.total else 0.0
    pct_packet = (100.0 * counts.packet_driven / counts.total) if counts.total else 0.0

    # Cycle 47 — port v3_status._kpi_card cards to ck_kpi_block +
    # provenance on the campaign-progress numbers.
    chrome_value = ck_provenance_tooltip(
        "v5 chrome adoption",
        ck_fmt_num(counts.v3),
        explainer=(
            f"Routes rendering through chartis_shell or living "
            f"under rcm_mc/ui/chartis/. Currently {pct_chrome:.1f}% "
            f"of {counts.total} total routes. The campaign "
            f"target is 100%."
        ),
    )
    packet_value = ck_provenance_tooltip(
        "Packet-driven routes",
        ck_fmt_num(counts.packet_driven),
        explainer=(
            "Renderers calling get_or_build_packet or importing "
            "DealAnalysisPacket. CLAUDE.md invariant: every "
            "partner-facing analytical page should reach the "
            "packet. Detection is heuristic - the real number is "
            "higher than this."
        ),
        inject_css=False,
    )
    kpi_grid = (
        f'<div class="ck-kpi-grid" style="grid-template-columns:repeat(7,1fr);gap:8px;margin:1.25rem 0;">'
        + ck_kpi_block("Total Routes", ck_fmt_num(counts.total), "in inventory")
        + ck_kpi_block("v5 Chrome", chrome_value, f"{pct_chrome:.1f}%")
        + ck_kpi_block("Legacy Shell", ck_fmt_num(counts.legacy), "_ui_kit only")
        + ck_kpi_block("Bespoke", ck_fmt_num(counts.bespoke), "no shell")
        + ck_kpi_block("Redirects", ck_fmt_num(counts.redirect), "non-rendering")
        + ck_kpi_block("Unresolved", ck_fmt_num(counts.unknown), "needs triage")
        + ck_kpi_block("Packet-driven", packet_value, f"of {counts.total}")
        + "</div>"
    )

    progress_table = (
        '<h2 style="margin-top:1.5rem;">Compliance summary</h2>'
        '<table class="ck-table" style="margin-top:.5rem;">'
        '<thead><tr><th>Status</th><th style="text-align:right;">Count</th>'
        '<th style="text-align:right;">% of total</th></tr></thead><tbody>'
        + "".join(
            f'<tr><td>{_html.escape(label)}</td>'
            f'<td style="text-align:right;">{fmt_num(count)}</td>'
            f'<td style="text-align:right;">{fmt_pct(100.0 * count / counts.total if counts.total else 0)}</td>'
            f"</tr>"
            for label, count in (
                ("v5 (chartis_shell or under ui/chartis/)", counts.v3),
                ("legacy (shell from _ui_kit only)", counts.legacy),
                ("bespoke (no shell — direct HTML)", counts.bespoke),
                ("redirect", counts.redirect),
                ("unknown / unresolved", counts.unknown),
            )
        )
        + "</tbody></table>"
    )

    packet_section = (
        '<h2 style="margin-top:1.5rem;">DealAnalysisPacket adoption</h2>'
        "<p>Renderers calling <code>get_or_build_packet</code> or "
        f"importing <code>DealAnalysisPacket</code>: {fmt_num(counts.packet_driven)} "
        f"of {fmt_num(counts.total)} ({fmt_pct(pct_packet)}). "
        "CLAUDE.md invariant: every partner-facing analytical page "
        "should reach the packet. Detection here is heuristic "
        "(immediate renderer file only); the real number is higher.</p>"
    )

    foot = (
        f'<p class="micro" style="margin-top:2rem;">Inventory regenerated '
        f"{_html.escape(counts.inventory_mtime_iso)} (UTC). "
        f"Re-run <code>python3 RCM_MC/tools/v3_route_inventory.py --v5</code> after any "
        f"page migration to refresh these numbers.</p>"
    )

    # Title comes from chartis_shell(editorial_intro=...); removed
    # the duplicate ck_eyebrow that stacked another mini-title here.
    body = (
        '<section style="max-width:62rem;">'
        + '<p class="micro">v5 Chartis campaign — '
        "<strong>saving-seeking-chartis</strong> branch</p>"
        "<p>Campaign progress map. Numbers come from "
        "<code>docs/V5_ROUTE_INVENTORY.md</code>.</p>"
        + kpi_grid
        + progress_table
        + packet_section
        + foot
        + "</section>"
        + ck_next_section(
            "Open the v3 fidelity status",
            "/v3-status",
            eyebrow="Continue —",
            italic_word="v3",
        )
    )

    # 2026-05-28 batch 29 · Phase 3 · universal strict 5-block head.
    from ._chartis_kit import ck_editorial_head
    head = ck_editorial_head(
        eyebrow="V5 STATUS",
        title="Where the chartis transformation stands.",
        meta=(
            f"{counts.total} ROUTES · "
            f"{counts.v3} V5-CHROMED ({pct_chrome:.0f}%) · "
            f"{counts.packet_driven} PACKET-DRIVEN ({pct_packet:.0f}%)"
        ),
        lede_italic_phrase=(
            "Live campaign progress against the v5 editorial "
            "chrome targets — shell adoption, primitive "
            "density, italic-serif coverage, fmt-helper use, "
            "provenance density."
        ),
        lede_body=(
            "The numbers come from the "
            "audit, not from claimed status."
        ),
    )
    body = head + body
    # 2026-05-28 wave-B: ck_page_actions adds Copy share link
    # + Back-to-top affordances. Idempotent JS guards.
    from ._chartis_kit import ck_page_actions
    body = body + ck_page_actions()
    return chartis_shell(
        body,
        "v5 Transformation Status",
        subtitle="campaign progress · saving-seeking-chartis",
    )
