"""Extended seed deal set #76 — pediatrics themed healthcare PE transactions.

This module provides a curated list of 15 synthetic private equity deal
records focused on pediatric healthcare: general pediatrics, pediatric
specialty practices, NICU staffing / services, pediatric dental, and
pediatric therapy (OT/PT/SLP/ABA adjacent). All figures are illustrative
and intended for modeling, benchmarking, and scenario analysis.

Keys (17) per deal:
    company_name, sector, subsector, year, ev_mm, ev_ebitda,
    ebitda_mm, revenue_mm, ebitda_margin, hold_years, moic, irr,
    payer_mix, comm_pct, region, buyer, status
"""

EXTENDED_SEED_DEALS_76 = [
    {
        "company_name": "BrightPath Pediatric Partners",
        "sector": "Pediatrics",
        "subsector": "Primary Care MSO",
        "year": 2018,
        "ev_mm": 185.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 14.8,
        "revenue_mm": 82.22,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2108,
        "payer_mix": {"commercial": 0.38, "medicare": 0.02, "medicaid": 0.55, "self_pay": 0.05},
        "comm_pct": 0.38,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "LittleStars Pediatrics Group",
        "sector": "Pediatrics",
        "subsector": "Multi-site Clinic Platform",
        "year": 2019,
        "ev_mm": 245.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 18.85,
        "revenue_mm": 94.25,
        "ebitda_margin": 0.20,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.1993,
        "payer_mix": {"commercial": 0.40, "medicare": 0.01, "medicaid": 0.53, "self_pay": 0.06},
        "comm_pct": 0.40,
        "region": "Midwest",
        "buyer": "Audax",
        "status": "Partially Realized",
    },
    {
        "company_name": "KidsFirst Urgent Care",
        "sector": "Pediatrics",
        "subsector": "Pediatric Urgent Care",
        "year": 2021,
        "ev_mm": 132.0,
        "ev_ebitda": 14.2,
        "ebitda_mm": 9.3,
        "revenue_mm": 58.13,
        "ebitda_margin": 0.16,
        "hold_years": 3.0,
        "moic": 1.9,
        "irr": 0.2383,
        "payer_mix": {"commercial": 0.42, "medicare": 0.01, "medicaid": 0.50, "self_pay": 0.07},
        "comm_pct": 0.42,
        "region": "West",
        "buyer": "Sentinel Capital",
        "status": "Active",
    },
    {
        "company_name": "Sapling Pediatric Cardiology",
        "sector": "Pediatric Specialty",
        "subsector": "Cardiology",
        "year": 2020,
        "ev_mm": 310.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 90.91,
        "ebitda_margin": 0.22,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.45, "medicare": 0.02, "medicaid": 0.48, "self_pay": 0.05},
        "comm_pct": 0.45,
        "region": "Northeast",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
    {
        "company_name": "NorthStar Pediatric GI",
        "sector": "Pediatric Specialty",
        "subsector": "Gastroenterology",
        "year": 2022,
        "ev_mm": 198.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 14.35,
        "revenue_mm": 71.75,
        "ebitda_margin": 0.20,
        "hold_years": 2.5,
        "moic": 1.6,
        "irr": 0.2086,
        "payer_mix": {"commercial": 0.44, "medicare": 0.01, "medicaid": 0.49, "self_pay": 0.06},
        "comm_pct": 0.44,
        "region": "National",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Cypress Pediatric Pulmonology",
        "sector": "Pediatric Specialty",
        "subsector": "Pulmonology & Sleep",
        "year": 2017,
        "ev_mm": 88.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 7.65,
        "revenue_mm": 45.0,
        "ebitda_margin": 0.17,
        "hold_years": 6.0,
        "moic": 3.2,
        "irr": 0.2174,
        "payer_mix": {"commercial": 0.41, "medicare": 0.02, "medicaid": 0.52, "self_pay": 0.05},
        "comm_pct": 0.41,
        "region": "Southeast",
        "buyer": "Harren Equity",
        "status": "Realized",
    },
    {
        "company_name": "Cradle NICU Services",
        "sector": "NICU",
        "subsector": "Neonatology Staffing",
        "year": 2016,
        "ev_mm": 420.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 26.25,
        "revenue_mm": 131.25,
        "ebitda_margin": 0.20,
        "hold_years": 6.5,
        "moic": 3.6,
        "irr": 0.2149,
        "payer_mix": {"commercial": 0.36, "medicare": 0.01, "medicaid": 0.58, "self_pay": 0.05},
        "comm_pct": 0.36,
        "region": "National",
        "buyer": "Bain Capital",
        "status": "Realized",
    },
    {
        "company_name": "Lullaby Neonatal Partners",
        "sector": "NICU",
        "subsector": "Hospital-based NICU Mgmt",
        "year": 2020,
        "ev_mm": 565.0,
        "ev_ebitda": 17.0,
        "ebitda_mm": 33.24,
        "revenue_mm": 147.73,
        "ebitda_margin": 0.225,
        "hold_years": 4.5,
        "moic": 2.5,
        "irr": 0.2205,
        "payer_mix": {"commercial": 0.33, "medicare": 0.01, "medicaid": 0.61, "self_pay": 0.05},
        "comm_pct": 0.33,
        "region": "Southeast",
        "buyer": "Warburg Pincus",
        "status": "Active",
    },
    {
        "company_name": "Meridian Neonatal Transport",
        "sector": "NICU",
        "subsector": "Neonatal Transport & Outreach",
        "year": 2023,
        "ev_mm": 142.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 9.79,
        "revenue_mm": 54.39,
        "ebitda_margin": 0.18,
        "hold_years": 2.5,
        "moic": 1.45,
        "irr": 0.1596,
        "payer_mix": {"commercial": 0.32, "medicare": 0.02, "medicaid": 0.61, "self_pay": 0.05},
        "comm_pct": 0.32,
        "region": "Midwest",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "SmileKids Pediatric Dental",
        "sector": "Pediatric Dental",
        "subsector": "DSO Pediatric",
        "year": 2018,
        "ev_mm": 380.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 27.14,
        "revenue_mm": 135.7,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2098,
        "payer_mix": {"commercial": 0.35, "medicare": 0.00, "medicaid": 0.58, "self_pay": 0.07},
        "comm_pct": 0.35,
        "region": "Southeast",
        "buyer": "Webster Equity",
        "status": "Realized",
    },
    {
        "company_name": "TinyTooth Dental Group",
        "sector": "Pediatric Dental",
        "subsector": "Pediatric & Orthodontic DSO",
        "year": 2021,
        "ev_mm": 640.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 38.79,
        "revenue_mm": 172.4,
        "ebitda_margin": 0.225,
        "hold_years": 3.5,
        "moic": 2.1,
        "irr": 0.2259,
        "payer_mix": {"commercial": 0.33, "medicare": 0.00, "medicaid": 0.60, "self_pay": 0.07},
        "comm_pct": 0.33,
        "region": "National",
        "buyer": "Harren Equity",
        "status": "Active",
    },
    {
        "company_name": "Acorn Pediatric Dental Partners",
        "sector": "Pediatric Dental",
        "subsector": "Medicaid-focused DSO",
        "year": 2017,
        "ev_mm": 210.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 16.41,
        "revenue_mm": 89.18,
        "ebitda_margin": 0.184,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": 0.2069,
        "payer_mix": {"commercial": 0.20, "medicare": 0.00, "medicaid": 0.73, "self_pay": 0.07},
        "comm_pct": 0.20,
        "region": "West",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Kidspire Therapy Services",
        "sector": "Pediatric Therapy",
        "subsector": "Pediatric OT/PT/SLP",
        "year": 2019,
        "ev_mm": 165.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 12.22,
        "revenue_mm": 81.47,
        "ebitda_margin": 0.15,
        "hold_years": 4.0,
        "moic": 2.0,
        "irr": 0.1892,
        "payer_mix": {"commercial": 0.39, "medicare": 0.01, "medicaid": 0.54, "self_pay": 0.06},
        "comm_pct": 0.39,
        "region": "Midwest",
        "buyer": "Audax",
        "status": "Partially Realized",
    },
    {
        "company_name": "BuildingBlocks ABA",
        "sector": "Pediatric Therapy",
        "subsector": "Autism / ABA Therapy",
        "year": 2022,
        "ev_mm": 295.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 19.67,
        "revenue_mm": 87.42,
        "ebitda_margin": 0.225,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": 0.2164,
        "payer_mix": {"commercial": 0.37, "medicare": 0.00, "medicaid": 0.57, "self_pay": 0.06},
        "comm_pct": 0.37,
        "region": "West",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Beacon Pediatric Rehab",
        "sector": "Pediatric Therapy",
        "subsector": "Multi-disciplinary Rehab",
        "year": 2024,
        "ev_mm": 58.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 5.52,
        "revenue_mm": 39.43,
        "ebitda_margin": 0.14,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1472,
        "payer_mix": {"commercial": 0.34, "medicare": 0.01, "medicaid": 0.58, "self_pay": 0.07},
        "comm_pct": 0.34,
        "region": "Northeast",
        "buyer": "Sentinel Capital",
        "status": "Active",
    },
]
