"""Extended seed batch 52 — laboratory and diagnostics PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_52: list[dict] = [
    {
        "source_id": "ext52_001",
        "company_name": "Helix Clinical Laboratories",
        "sector": "clinical laboratory testing",
        "year": 2016,
        "ev_mm": 285.0,
        "ev_ebitda": 12.5,
        "moic": 3.4,
        "irr": 0.31,
        "hold_years": 4.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.62, "medicare": 0.28, "medicaid": 0.07, "self_pay": 0.03},
        "geography": "Southeast US",
        "ebitda_margin": 0.28,
        "revenue_mm": 105.0,
    },
    {
        "source_id": "ext52_002",
        "company_name": "Meridian Pathology Associates",
        "sector": "anatomic pathology group",
        "year": 2018,
        "ev_mm": 148.0,
        "ev_ebitda": 11.2,
        "moic": 3.1,
        "irr": 0.29,
        "hold_years": 4.0,
        "sponsor": "Welsh, Carson, Anderson & Stowe",
        "payer_mix": {"commercial": 0.58, "medicare": 0.30, "medicaid": 0.09, "self_pay": 0.03},
        "geography": "Midwest US",
        "ebitda_margin": 0.25,
        "revenue_mm": 59.0,
    },
    {
        "source_id": "ext52_003",
        "company_name": "Apex Molecular Diagnostics",
        "sector": "molecular diagnostics",
        "year": 2015,
        "ev_mm": 210.0,
        "ev_ebitda": 13.8,
        "moic": 4.2,
        "irr": 0.38,
        "hold_years": 3.5,
        "sponsor": "New Mountain Capital",
        "payer_mix": {"commercial": 0.65, "medicare": 0.25, "medicaid": 0.07, "self_pay": 0.03},
        "geography": "Northeast US",
        "ebitda_margin": 0.33,
        "revenue_mm": 70.0,
    },
    {
        "source_id": "ext52_004",
        "company_name": "Clearwater Toxicology Solutions",
        "sector": "toxicology lab",
        "year": 2017,
        "ev_mm": 175.0,
        "ev_ebitda": 10.8,
        "moic": 2.9,
        "irr": 0.27,
        "hold_years": 4.5,
        "sponsor": "Audax Private Equity",
        "payer_mix": {"commercial": 0.55, "medicare": 0.22, "medicaid": 0.18, "self_pay": 0.05},
        "geography": "South Central US",
        "ebitda_margin": 0.30,
        "revenue_mm": 65.0,
    },
    {
        "source_id": "ext52_005",
        "company_name": "GenScope Hereditary Testing",
        "sector": "genetics testing",
        "year": 2019,
        "ev_mm": 320.0,
        "ev_ebitda": 15.2,
        "moic": 3.8,
        "irr": 0.36,
        "hold_years": 3.5,
        "sponsor": "General Atlantic",
        "payer_mix": {"commercial": 0.68, "medicare": 0.20, "medicaid": 0.08, "self_pay": 0.04},
        "geography": "West Coast US",
        "ebitda_margin": 0.35,
        "revenue_mm": 99.0,
    },
    {
        "source_id": "ext52_006",
        "company_name": "Pinnacle Reference Laboratories",
        "sector": "reference lab services",
        "year": 2014,
        "ev_mm": 415.0,
        "ev_ebitda": 11.5,
        "moic": 3.3,
        "irr": 0.28,
        "hold_years": 5.0,
        "sponsor": "Blackstone",
        "payer_mix": {"commercial": 0.60, "medicare": 0.32, "medicaid": 0.06, "self_pay": 0.02},
        "geography": "National US",
        "ebitda_margin": 0.26,
        "revenue_mm": 171.0,
    },
    {
        "source_id": "ext52_007",
        "company_name": "RapidSense Point-of-Care",
        "sector": "point-of-care diagnostics",
        "year": 2020,
        "ev_mm": 260.0,
        "ev_ebitda": 14.5,
        "moic": 4.6,
        "irr": 0.39,
        "hold_years": 3.0,
        "sponsor": "Insight Partners",
        "payer_mix": {"commercial": 0.63, "medicare": 0.24, "medicaid": 0.10, "self_pay": 0.03},
        "geography": "Mountain West US",
        "ebitda_margin": 0.36,
        "revenue_mm": 78.0,
    },
    {
        "source_id": "ext52_008",
        "company_name": "Luminos Digital Pathology",
        "sector": "digital pathology platform",
        "year": 2021,
        "ev_mm": 195.0,
        "ev_ebitda": 15.8,
        "moic": 3.6,
        "irr": 0.34,
        "hold_years": 3.5,
        "sponsor": "Francisco Partners",
        "payer_mix": {"commercial": 0.70, "medicare": 0.20, "medicaid": 0.07, "self_pay": 0.03},
        "geography": "Northeast US",
        "ebitda_margin": 0.38,
        "revenue_mm": 57.0,
    },
    {
        "source_id": "ext52_009",
        "company_name": "FluidMark Liquid Biopsy",
        "sector": "liquid biopsy company",
        "year": 2019,
        "ev_mm": 380.0,
        "ev_ebitda": 14.0,
        "moic": 4.4,
        "irr": 0.37,
        "hold_years": 4.0,
        "sponsor": "OrbiMed",
        "payer_mix": {"commercial": 0.66, "medicare": 0.23, "medicaid": 0.08, "self_pay": 0.03},
        "geography": "West Coast US",
        "ebitda_margin": 0.32,
        "revenue_mm": 128.0,
    },
    {
        "source_id": "ext52_010",
        "company_name": "TargetDx Companion Diagnostics",
        "sector": "companion diagnostics",
        "year": 2016,
        "ev_mm": 300.0,
        "ev_ebitda": 13.2,
        "moic": 3.7,
        "irr": 0.33,
        "hold_years": 4.0,
        "sponsor": "Bain Capital",
        "payer_mix": {"commercial": 0.67, "medicare": 0.22, "medicaid": 0.08, "self_pay": 0.03},
        "geography": "Northeast US",
        "ebitda_margin": 0.31,
        "revenue_mm": 103.0,
    },
    {
        "source_id": "ext52_011",
        "company_name": "PharmGenix Testing Services",
        "sector": "pharmacogenomics testing",
        "year": 2018,
        "ev_mm": 155.0,
        "ev_ebitda": 12.0,
        "moic": 3.2,
        "irr": 0.30,
        "hold_years": 4.5,
        "sponsor": "ABRY Partners",
        "payer_mix": {"commercial": 0.61, "medicare": 0.27, "medicaid": 0.09, "self_pay": 0.03},
        "geography": "Southeast US",
        "ebitda_margin": 0.27,
        "revenue_mm": 61.0,
    },
    {
        "source_id": "ext52_012",
        "company_name": "NexaLIS Lab Information Systems",
        "sector": "lab information systems",
        "year": 2013,
        "ev_mm": 120.0,
        "ev_ebitda": 10.5,
        "moic": 2.8,
        "irr": 0.24,
        "hold_years": 5.5,
        "sponsor": "Thoma Bravo",
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "geography": "Midwest US",
        "ebitda_margin": 0.22,
        "revenue_mm": 52.0,
    },
    {
        "source_id": "ext52_013",
        "company_name": "BioTrack Specimen Management",
        "sector": "specimen management",
        "year": 2015,
        "ev_mm": 88.0,
        "ev_ebitda": 9.5,
        "moic": 2.7,
        "irr": 0.23,
        "hold_years": 5.0,
        "sponsor": "Sverica Capital Management",
        "payer_mix": {"commercial": 0.52, "medicare": 0.33, "medicaid": 0.11, "self_pay": 0.04},
        "geography": "Mid-Atlantic US",
        "ebitda_margin": 0.20,
        "revenue_mm": 42.0,
    },
    {
        "source_id": "ext52_014",
        "company_name": "Crimson Blood Banking Systems",
        "sector": "blood banking",
        "year": 2017,
        "ev_mm": 225.0,
        "ev_ebitda": 11.8,
        "moic": 3.0,
        "irr": 0.26,
        "hold_years": 5.0,
        "sponsor": "KKR",
        "payer_mix": {"commercial": 0.57, "medicare": 0.31, "medicaid": 0.09, "self_pay": 0.03},
        "geography": "Southeast US",
        "ebitda_margin": 0.24,
        "revenue_mm": 87.0,
    },
    {
        "source_id": "ext52_015",
        "company_name": "Vitalis Transfusion Medicine Group",
        "sector": "transfusion medicine",
        "year": 2022,
        "ev_mm": 340.0,
        "ev_ebitda": 12.8,
        "moic": 3.5,
        "irr": 0.32,
        "hold_years": 4.0,
        "sponsor": "TPG Capital",
        "payer_mix": {"commercial": 0.59, "medicare": 0.29, "medicaid": 0.09, "self_pay": 0.03},
        "geography": "West Coast US",
        "ebitda_margin": 0.29,
        "revenue_mm": 120.0,
    },
]
