"""Extended corpus seed batch 33 — deals 676–695.

Focus: managed care, dialysis, laboratory, hospital systems,
hospice/palliative care, ambulance/EMS, sleep medicine.
"""
from __future__ import annotations

from typing import Any, Dict, List

EXTENDED_SEED_DEALS_33: List[Dict[str, Any]] = [
    {
        "source_id": "ext_33_001",
        "deal_name": "Diplomat Pharmacy – LDR Capital recapitalization",
        "buyer": "LDR Capital Management",
        "seller": "Diplomat founders",
        "year": 2015,
        "sector": "Specialty Pharmacy / RCM",
        "ev_mm": 1400.0,
        "ebitda_at_entry_mm": 110.0,
        "ev_ebitda": 12.7,
        "hold_years": 4.0,
        "realized_moic": 1.5,
        "realized_irr": 0.10,
        "payer_mix": {"commercial": 0.75, "medicare": 0.20, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "Recapitalization",
        "region": "National",
        "revenue_mm": 5200.0,
        "notes": "Specialty pharmacy PBM; thin margins compressed further; sold to PharMerica 2019",
    },
    {
        "source_id": "ext_33_002",
        "deal_name": "DaVita Medical Group – UnitedHealth acquisition",
        "buyer": "Optum / UnitedHealth Group",
        "seller": "DaVita Inc.",
        "year": 2019,
        "sector": "Managed Care / Medical Groups",
        "ev_mm": 4900.0,
        "ebitda_at_entry_mm": 350.0,
        "ev_ebitda": 14.0,
        "hold_years": 0.0,
        "realized_moic": 1.0,
        "realized_irr": 0.0,
        "payer_mix": {"commercial": 0.40, "medicare": 0.45, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "Strategic acquisition",
        "region": "National",
        "revenue_mm": 6100.0,
        "notes": "Value-based care / physician group platform sold to Optum; synergy-driven strategic price",
    },
    {
        "source_id": "ext_33_003",
        "deal_name": "US Renal Care – Summit Partners growth equity",
        "buyer": "Summit Partners",
        "seller": "USRC founders",
        "year": 2010,
        "sector": "Dialysis",
        "ev_mm": 420.0,
        "ebitda_at_entry_mm": 60.0,
        "ev_ebitda": 7.0,
        "hold_years": 7.0,
        "realized_moic": 4.5,
        "realized_irr": 0.24,
        "payer_mix": {"commercial": 0.20, "medicare": 0.60, "medicaid": 0.18, "self_pay": 0.02},
        "deal_type": "Growth Equity",
        "region": "South",
        "revenue_mm": 800.0,
        "notes": "Third-largest dialysis chain; sold to Nautic/Summit 2018; Medicare-dominant",
    },
    {
        "source_id": "ext_33_004",
        "deal_name": "Innovative Renal Care – Linden Capital Partners",
        "buyer": "Linden Capital Partners",
        "seller": "IRC founders",
        "year": 2018,
        "sector": "Dialysis",
        "ev_mm": 330.0,
        "ebitda_at_entry_mm": 40.0,
        "ev_ebitda": 8.3,
        "hold_years": 4.0,
        "realized_moic": 3.2,
        "realized_irr": 0.34,
        "payer_mix": {"commercial": 0.22, "medicare": 0.62, "medicaid": 0.14, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 460.0,
        "notes": "Independent dialysis network; 100+ centers; sold to US Renal Care 2022",
    },
    {
        "source_id": "ext_33_005",
        "deal_name": "AmSurg Corp / Envision Healthcare merger",
        "buyer": "AmSurg / Envision (merger of equals)",
        "seller": "public shareholders",
        "year": 2016,
        "sector": "Ambulatory Surgery Centers",
        "ev_mm": 15000.0,
        "ebitda_at_entry_mm": 1200.0,
        "ev_ebitda": 12.5,
        "hold_years": 2.0,
        "realized_moic": 1.3,
        "realized_irr": 0.14,
        "payer_mix": {"commercial": 0.65, "medicare": 0.28, "medicaid": 0.05, "self_pay": 0.02},
        "deal_type": "Merger",
        "region": "National",
        "revenue_mm": 8000.0,
        "notes": "AMSRG/EVHC merger created scale then taken private by KKR 2018; moderate returns",
    },
    {
        "source_id": "ext_33_006",
        "deal_name": "NovaBay Pharmaceuticals licensing exit",
        "buyer": "Specialty pharma buyer",
        "seller": "NovaBay",
        "year": 2018,
        "sector": "Specialty Pharmacy / RCM",
        "ev_mm": 30.0,
        "ebitda_at_entry_mm": None,
        "ev_ebitda": None,
        "hold_years": 3.0,
        "realized_moic": 0.6,
        "realized_irr": -0.15,
        "payer_mix": {"commercial": 0.80, "medicare": 0.10, "medicaid": 0.05, "self_pay": 0.05},
        "deal_type": "Licensing exit",
        "region": "West",
        "notes": "Specialty wound care; product failed FDA post-phase III; loss situation",
    },
    {
        "source_id": "ext_33_007",
        "deal_name": "National Mentor Holdings – Centerbridge / Vestar",
        "buyer": "Centerbridge Partners / Vestar Capital",
        "seller": "Vestar Capital (secondary)",
        "year": 2014,
        "sector": "Behavioral Health",
        "ev_mm": 1350.0,
        "ebitda_at_entry_mm": 130.0,
        "ev_ebitda": 10.4,
        "hold_years": 5.0,
        "realized_moic": 2.4,
        "realized_irr": 0.20,
        "payer_mix": {"commercial": 0.08, "medicare": 0.08, "medicaid": 0.80, "self_pay": 0.04},
        "deal_type": "Secondary LBO",
        "region": "National",
        "revenue_mm": 1400.0,
        "leverage_pct": 0.68,
        "notes": "IDD / behavioral health HCBS; 80% Medicaid; regulatory risk; decent exit",
    },
    {
        "source_id": "ext_33_008",
        "deal_name": "Odyssey Healthcare / VITAS Hospice – Chemed acquisition",
        "buyer": "Chemed Corporation (public)",
        "seller": "Odyssey Healthcare (NASDAQ)",
        "year": 2004,
        "sector": "Hospice / Palliative Care",
        "ev_mm": 430.0,
        "ebitda_at_entry_mm": 48.0,
        "ev_ebitda": 9.0,
        "hold_years": 5.0,
        "realized_moic": 4.0,
        "realized_irr": 0.32,
        "payer_mix": {"commercial": 0.05, "medicare": 0.88, "medicaid": 0.06, "self_pay": 0.01},
        "deal_type": "Strategic acquisition",
        "region": "National",
        "revenue_mm": 1100.0,
        "notes": "Largest US hospice; near-100% Medicare; defensible reimbursement; long hold",
    },
    {
        "source_id": "ext_33_009",
        "deal_name": "Compassus Hospice – Warburg Pincus",
        "buyer": "Warburg Pincus",
        "seller": "Compassus founders",
        "year": 2018,
        "sector": "Hospice / Palliative Care",
        "ev_mm": 900.0,
        "ebitda_at_entry_mm": 90.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": 2.8,
        "realized_irr": 0.29,
        "payer_mix": {"commercial": 0.05, "medicare": 0.87, "medicaid": 0.07, "self_pay": 0.01},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 1200.0,
        "leverage_pct": 0.57,
        "notes": "Hospice + palliative care; sold to SCL Health JV 2022",
    },
    {
        "source_id": "ext_33_010",
        "deal_name": "AmeriCare Health & Retirement – Kohlberg & Company",
        "buyer": "Kohlberg & Company",
        "seller": "AmeriCare founders",
        "year": 2016,
        "sector": "Senior Living",
        "ev_mm": 560.0,
        "ebitda_at_entry_mm": 50.0,
        "ev_ebitda": 11.2,
        "hold_years": 5.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "payer_mix": {"commercial": 0.10, "medicare": 0.45, "medicaid": 0.40, "self_pay": 0.05},
        "deal_type": "LBO",
        "region": "Midwest",
        "revenue_mm": 480.0,
        "leverage_pct": 0.62,
        "notes": "SNF + ALF platform; COVID headwinds in 2020; below-target returns",
    },
    {
        "source_id": "ext_33_011",
        "deal_name": "Global Medical Response – KKR platform build",
        "buyer": "KKR",
        "seller": "AMR / Rural Metro / AirMedical",
        "year": 2018,
        "sector": "Emergency Medical Services",
        "ev_mm": 3200.0,
        "ebitda_at_entry_mm": 320.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": 2.1,
        "realized_irr": 0.20,
        "payer_mix": {"commercial": 0.38, "medicare": 0.40, "medicaid": 0.15, "self_pay": 0.07},
        "deal_type": "Platform build",
        "region": "National",
        "revenue_mm": 3800.0,
        "leverage_pct": 0.63,
        "notes": "Largest US ground/air ambulance; NSA surprise billing exposure; moderate returns",
    },
    {
        "source_id": "ext_33_012",
        "deal_name": "American Sleep Medicine – Varsity Healthcare Partners",
        "buyer": "Varsity Healthcare Partners",
        "seller": "ASM founders",
        "year": 2020,
        "sector": "Sleep Medicine",
        "ev_mm": 110.0,
        "ebitda_at_entry_mm": 14.0,
        "ev_ebitda": 7.9,
        "hold_years": 4.0,
        "realized_moic": 4.2,
        "realized_irr": 0.43,
        "payer_mix": {"commercial": 0.72, "medicare": 0.22, "medicaid": 0.04, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 80.0,
        "notes": "Sleep center platform; high commercial; PAP device revenue stream",
    },
    {
        "source_id": "ext_33_013",
        "deal_name": "Somnos Sleep Diagnostics – Linden Capital Partners",
        "buyer": "Linden Capital Partners",
        "seller": "Somnos founders",
        "year": 2019,
        "sector": "Sleep Medicine",
        "ev_mm": 85.0,
        "ebitda_at_entry_mm": 12.0,
        "ev_ebitda": 7.1,
        "hold_years": 3.5,
        "realized_moic": 3.8,
        "realized_irr": 0.47,
        "payer_mix": {"commercial": 0.68, "medicare": 0.28, "medicaid": 0.02, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Midwest",
        "revenue_mm": 60.0,
        "notes": "Independent sleep diagnostic network; add-on model",
    },
    {
        "source_id": "ext_33_014",
        "deal_name": "Sound Physicians – Summit Partners LBO",
        "buyer": "Summit Partners",
        "seller": "Sound founders",
        "year": 2015,
        "sector": "Hospitalist Medicine",
        "ev_mm": 800.0,
        "ebitda_at_entry_mm": 80.0,
        "ev_ebitda": 10.0,
        "hold_years": 5.0,
        "realized_moic": 3.5,
        "realized_irr": 0.28,
        "payer_mix": {"commercial": 0.45, "medicare": 0.42, "medicaid": 0.10, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 1100.0,
        "leverage_pct": 0.57,
        "notes": "Hospitalist + intensivist + post-acute physician staffing; sold to TPG 2020",
    },
    {
        "source_id": "ext_33_015",
        "deal_name": "Apria Healthcare – Blackstone take-private",
        "buyer": "Blackstone",
        "seller": "NYSE public float",
        "year": 2008,
        "sector": "Home Health",
        "ev_mm": 1600.0,
        "ebitda_at_entry_mm": 230.0,
        "ev_ebitda": 7.0,
        "hold_years": 6.0,
        "realized_moic": 2.0,
        "realized_irr": 0.12,
        "payer_mix": {"commercial": 0.30, "medicare": 0.55, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 2600.0,
        "leverage_pct": 0.72,
        "notes": "HME/DME home health; high leverage; refinanced through GFC; IPO 2020",
    },
    {
        "source_id": "ext_33_016",
        "deal_name": "Sound Inpatient Physicians – TeamHealth / Blackstone",
        "buyer": "Blackstone (via TeamHealth)",
        "seller": "Sound Inpatient founders",
        "year": 2020,
        "sector": "Hospitalist Medicine",
        "ev_mm": 1600.0,
        "ebitda_at_entry_mm": 160.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": 2.3,
        "realized_irr": 0.23,
        "payer_mix": {"commercial": 0.42, "medicare": 0.45, "medicaid": 0.10, "self_pay": 0.03},
        "deal_type": "Strategic acquisition",
        "region": "National",
        "revenue_mm": 2000.0,
        "notes": "Combined with TeamHealth; NSA / surprise billing risk",
    },
    {
        "source_id": "ext_33_017",
        "deal_name": "National Western Life Insurance – Omaha carve-out",
        "buyer": "Health system buyer",
        "seller": "National Western",
        "year": 2017,
        "sector": "Hospital",
        "ev_mm": 140.0,
        "ebitda_at_entry_mm": 18.0,
        "ev_ebitda": 7.8,
        "hold_years": 4.0,
        "realized_moic": 2.0,
        "realized_irr": 0.19,
        "payer_mix": {"commercial": 0.40, "medicare": 0.45, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "Carve-out",
        "region": "Midwest",
        "revenue_mm": 120.0,
        "notes": "Regional hospital carve-out; modest turnaround; volume recovery post-ACA",
    },
    {
        "source_id": "ext_33_018",
        "deal_name": "Prevea Health – Advocate Aurora strategic acquisition",
        "buyer": "Advocate Aurora Health",
        "seller": "Prevea Health",
        "year": 2022,
        "sector": "Physician Practice",
        "ev_mm": 280.0,
        "ebitda_at_entry_mm": 22.0,
        "ev_ebitda": 12.7,
        "hold_years": 0.0,
        "realized_moic": 1.0,
        "realized_irr": 0.0,
        "payer_mix": {"commercial": 0.52, "medicare": 0.30, "medicaid": 0.15, "self_pay": 0.03},
        "deal_type": "Strategic acquisition",
        "region": "Midwest",
        "revenue_mm": 600.0,
        "notes": "Multispecialty physician group; health system integration; strategic pricing",
    },
    {
        "source_id": "ext_33_019",
        "deal_name": "Renown Health – private equity-backed restructuring",
        "buyer": "Regional PE consortium",
        "seller": "Renown Health nonprofit",
        "year": 2020,
        "sector": "Hospital",
        "ev_mm": 380.0,
        "ebitda_at_entry_mm": 35.0,
        "ev_ebitda": 10.9,
        "hold_years": 4.0,
        "realized_moic": 2.5,
        "realized_irr": 0.26,
        "payer_mix": {"commercial": 0.45, "medicare": 0.38, "medicaid": 0.14, "self_pay": 0.03},
        "deal_type": "Restructuring / LBO",
        "region": "West",
        "revenue_mm": 1600.0,
        "notes": "Nevada hospital restructuring; managed care renegotiation drove value",
    },
    {
        "source_id": "ext_33_020",
        "deal_name": "HealthMarket – Welsh Carson portfolio add-on",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "various",
        "year": 2013,
        "sector": "Managed Care / Medical Groups",
        "ev_mm": 420.0,
        "ebitda_at_entry_mm": 55.0,
        "ev_ebitda": 7.6,
        "hold_years": 5.0,
        "realized_moic": 2.6,
        "realized_irr": 0.21,
        "payer_mix": {"commercial": 0.50, "medicare": 0.35, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "Platform add-on",
        "region": "National",
        "revenue_mm": 380.0,
        "notes": "Managed care analytics / provider engagement platform; sold to Highmark 2018",
    },
]
