"""Extended seed batch 19 — deals 396-415."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_19: List[Dict[str, Any]] = [
    {
        "source_id": "seed_396",
        "deal_name": "Prospect Medical Holdings / Leonard Green take-private",
        "buyer": "Leonard Green & Partners",
        "seller": "Public shareholders",
        "year": 2010,
        "deal_type": "take-private",
        "sector": "hospital",
        "ev_mm": 363.0,
        "ev_ebitda": 6.5,
        "ebitda_mm": 56.0,
        "revenue_mm": 920.0,
        "realized_moic": 0.8,
        "realized_irr": -0.03,
        "hold_years": 13.0,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.35, "commercial": 0.22, "self_pay": 0.05},
        "geography": "CA",
        "hospital_beds": 5400,
        "source": "seed",
        "notes": "Safety-net hospital chain; California Medicaid dependency; filed Ch.11 July 2023; hospital viability crisis",
    },
    {
        "source_id": "seed_397",
        "deal_name": "CareMore Health / Anthem acquisition",
        "buyer": "Anthem / WellPoint",
        "seller": "CareMore founders / physician shareholders",
        "year": 2011,
        "deal_type": "merger",
        "sector": "managed_care",
        "ev_mm": 800.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 400.0,
        "realized_moic": 4.0,
        "realized_irr": 0.28,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.95, "medicaid": 0.05, "commercial": 0.0, "self_pay": 0.0},
        "geography": "CA",
        "hospital_beds": None,
        "source": "seed",
        "notes": "MA plan + care delivery for complex elderly; high-risk Medicare frailty model; strong evidence of cost reduction",
    },
    {
        "source_id": "seed_398",
        "deal_name": "Crossroads Hospice / LHC Group acquisition",
        "buyer": "LHC Group",
        "seller": "Riverside Company",
        "year": 2016,
        "deal_type": "add-on",
        "sector": "hospice",
        "ev_mm": 250.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 24.0,
        "revenue_mm": 130.0,
        "realized_moic": 3.2,
        "realized_irr": 0.27,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.88, "medicaid": 0.08, "commercial": 0.03, "self_pay": 0.01},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hospice add-on acquisition; Riverside built platform then sold to LHC Group as strategic exit",
    },
    {
        "source_id": "seed_399",
        "deal_name": "Surgical Directions / Waud Capital LBO",
        "buyer": "Waud Capital Partners",
        "seller": "Founders / management team",
        "year": 2019,
        "deal_type": "lbo",
        "sector": "asc",
        "ev_mm": 200.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 17.0,
        "revenue_mm": 80.0,
        "realized_moic": 3.8,
        "realized_irr": 0.33,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.25, "medicaid": 0.05, "commercial": 0.65, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "ASC consulting + management; hospital OR efficiency partnership model; COVID site-of-care shift drove demand",
    },
    {
        "source_id": "seed_400",
        "deal_name": "Staywell Health / Carient / Population health JV",
        "buyer": "Centene Corporation",
        "seller": "StayWell Health Management founders",
        "year": 2015,
        "deal_type": "merger",
        "sector": "population_health",
        "ev_mm": 170.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 12.0,
        "revenue_mm": 75.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.50, "commercial": 0.28, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Disease management + health coaching platform; Centene absorbed into Medicaid + commercial wellness programs",
    },
    {
        "source_id": "seed_401",
        "deal_name": "Heritage Healthcare / ABRY Partners add-on roll-up",
        "buyer": "ABRY Partners",
        "seller": "Seller-owned chains",
        "year": 2018,
        "deal_type": "add-on",
        "sector": "home_health",
        "ev_mm": 320.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 34.0,
        "revenue_mm": 220.0,
        "realized_moic": 2.5,
        "realized_irr": 0.19,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.68, "medicaid": 0.18, "commercial": 0.11, "self_pay": 0.03},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Home health multi-state roll-up; Medicare home health reimbursement episodic cuts managed via visit optimization",
    },
    {
        "source_id": "seed_402",
        "deal_name": "Physicians Endoscopy / Blue Wolf Capital LBO",
        "buyer": "Blue Wolf Capital Partners",
        "seller": "Physician founders / management",
        "year": 2014,
        "deal_type": "lbo",
        "sector": "asc",
        "ev_mm": 150.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 18.0,
        "revenue_mm": 90.0,
        "realized_moic": 3.5,
        "realized_irr": 0.30,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.05, "commercial": 0.58, "self_pay": 0.02},
        "geography": "Northeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "GI / endoscopy ASC platform; site-of-care shift from hospital to ASC for colonoscopy drove strong returns",
    },
    {
        "source_id": "seed_403",
        "deal_name": "National Western Life / Aon Hewitt benefits carve-out",
        "buyer": "Lightyear Capital",
        "seller": "National Western Life Group",
        "year": 2016,
        "deal_type": "carve-out",
        "sector": "managed_care",
        "ev_mm": 280.0,
        "ev_ebitda": 9.0,
        "ebitda_mm": 31.0,
        "revenue_mm": 400.0,
        "realized_moic": 2.1,
        "realized_irr": 0.16,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.82, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Employee benefits administration carve-out; TPA + COBRA + FSA platform; steady but undifferentiated returns",
    },
    {
        "source_id": "seed_404",
        "deal_name": "TeamHealth / IPC Healthcare merger (pre-KKR)",
        "buyer": "Blackstone Group",
        "seller": "Warburg Pincus / management",
        "year": 2016,
        "deal_type": "merger",
        "sector": "physician_group",
        "ev_mm": 6100.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 381.0,
        "revenue_mm": 3500.0,
        "realized_moic": 1.1,
        "realized_irr": 0.03,
        "hold_years": 8.0,
        "payer_mix": {"medicare": 0.32, "medicaid": 0.20, "commercial": 0.40, "self_pay": 0.08},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Emergency + hospital medicine giant; NSA surprise billing reform destroyed payor-neutral pricing model",
    },
    {
        "source_id": "seed_405",
        "deal_name": "Omada Health / Andreessen Horowitz growth equity",
        "buyer": "Andreessen Horowitz / Cigna Ventures",
        "seller": "Founders",
        "year": 2017,
        "deal_type": "growth_equity",
        "sector": "digital_health",
        "ev_mm": 700.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 70.0,
        "realized_moic": 2.5,
        "realized_irr": 0.18,
        "hold_years": 7.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.10, "commercial": 0.60, "self_pay": 0.25},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Digital diabetes prevention program; CDC DPP covered by Medicare/commercial; IPO filed 2025 at ~$1.8B valuation",
    },
    {
        "source_id": "seed_406",
        "deal_name": "Altus Healthcare + Rehab / Revelstoke Capital add-on",
        "buyer": "Revelstoke Capital Partners",
        "seller": "Regional PT owners",
        "year": 2020,
        "deal_type": "add-on",
        "sector": "physical_therapy",
        "ev_mm": 180.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 18.0,
        "revenue_mm": 90.0,
        "realized_moic": 2.8,
        "realized_irr": 0.23,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.08, "commercial": 0.58, "self_pay": 0.06},
        "geography": "TX",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Texas PT roll-up; multiple coding audits navigated; sold to ATI precursor prior to ATI SPAC at a premium",
    },
    {
        "source_id": "seed_407",
        "deal_name": "InCompass Health / Elevation Oncology merger",
        "buyer": "Nautic Partners",
        "seller": "Oncology founders",
        "year": 2017,
        "deal_type": "lbo",
        "sector": "oncology",
        "ev_mm": 380.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 35.0,
        "revenue_mm": 180.0,
        "realized_moic": 3.6,
        "realized_irr": 0.31,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.10, "commercial": 0.32, "self_pay": 0.03},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Radiation oncology + medical oncology platform; site-neutral payment risk offset by drug margin on 340B program",
    },
    {
        "source_id": "seed_408",
        "deal_name": "LHC Group / Almost Family merger",
        "buyer": "LHC Group (LHCG public)",
        "seller": "Almost Family public shareholders",
        "year": 2018,
        "deal_type": "merger",
        "sector": "home_health",
        "ev_mm": 1520.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 109.0,
        "revenue_mm": 1200.0,
        "realized_moic": 3.0,
        "realized_irr": 0.24,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.74, "medicaid": 0.12, "commercial": 0.11, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Home health + hospice roll-up; UHG/Optum acquired for $6B in 2022 at 5x+ entry; Medicare home health anchor",
    },
    {
        "source_id": "seed_409",
        "deal_name": "Hanger Prosthetics / Rehabilitation Centers acquisition",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Public shareholders (Hanger Inc.)",
        "year": 2014,
        "deal_type": "take-private",
        "sector": "dme_home_health",
        "ev_mm": 1700.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 131.0,
        "revenue_mm": 1050.0,
        "realized_moic": 2.1,
        "realized_irr": 0.15,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.12, "commercial": 0.33, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest US prosthetics + orthotics provider; DOJ settlement on billing; Medicare reimbursement audit compressed margins",
    },
    {
        "source_id": "seed_410",
        "deal_name": "Acuity Brands Healthcare / Industrial lighting spin",
        "buyer": "TPG Capital / Searchlight Capital",
        "seller": "Kindred legacy assets",
        "year": 2020,
        "deal_type": "carve-out",
        "sector": "ltach_post_acute",
        "ev_mm": 800.0,
        "ev_ebitda": 8.0,
        "ebitda_mm": 100.0,
        "revenue_mm": 1200.0,
        "realized_moic": 2.3,
        "realized_irr": 0.18,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.12, "commercial": 0.13, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": 8000,
        "source": "seed",
        "notes": "LTACH + IRF post-acute carve-out from Kindred; COVID recovery unit demand drove higher-than-expected census",
    },
    {
        "source_id": "seed_411",
        "deal_name": "WellCare / Centene merger (second deal)",
        "buyer": "Centene Corporation",
        "seller": "Public WellCare shareholders",
        "year": 2020,
        "deal_type": "merger",
        "sector": "managed_care",
        "ev_mm": 17300.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 1081.0,
        "revenue_mm": 9600.0,
        "realized_moic": 3.2,
        "realized_irr": 0.26,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.38, "commercial": 0.06, "self_pay": 0.01},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Created largest Medicaid managed care company; Medicare Part D leadership; ACA/Medicaid expansion tailwind",
    },
    {
        "source_id": "seed_412",
        "deal_name": "Emergency Communications Network / TriZetto merger",
        "buyer": "Cognizant Technology Solutions",
        "seller": "Francisco Partners / management",
        "year": 2014,
        "deal_type": "merger",
        "sector": "health_it",
        "ev_mm": 2700.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 135.0,
        "revenue_mm": 500.0,
        "realized_moic": 4.5,
        "realized_irr": 0.38,
        "hold_years": 4.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Payer core admin + claims processing SaaS; Francisco Partners acquired for $720M, sold to Cognizant for $2.7B",
    },
    {
        "source_id": "seed_413",
        "deal_name": "HAH / Home at Home pediatric nursing (Pediatric Specialty Care)",
        "buyer": "BelHealth Investment Partners",
        "seller": "Regional pediatric nurses founders",
        "year": 2016,
        "deal_type": "lbo",
        "sector": "home_health",
        "ev_mm": 75.0,
        "ev_ebitda": 7.5,
        "ebitda_mm": 10.0,
        "revenue_mm": 50.0,
        "realized_moic": 4.0,
        "realized_irr": 0.35,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.85, "commercial": 0.12, "self_pay": 0.01},
        "geography": "PA",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Pediatric home health nursing for medically complex children; Medicaid waiver + TEFRA dependency; labor-intensive",
    },
    {
        "source_id": "seed_414",
        "deal_name": "BioSig Technologies / cardiac electrophysiology growth",
        "buyer": "Multiple VC / Windtree Therapeutics",
        "seller": "Founders",
        "year": 2019,
        "deal_type": "growth_equity",
        "sector": "cardiology",
        "ev_mm": 200.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 8.0,
        "realized_moic": 0.4,
        "realized_irr": -0.18,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.10, "commercial": 0.42, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "EP catheter lab technology; FDA clearance delays + commercial ramp failure; de-listed 2024",
    },
    {
        "source_id": "seed_415",
        "deal_name": "Tivity Health / Donaldson Lufkin Jenrette secondary",
        "buyer": "Marlin Equity Partners",
        "seller": "Public shareholders (Tivity Health)",
        "year": 2020,
        "deal_type": "take-private",
        "sector": "digital_health",
        "ev_mm": 660.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 78.0,
        "revenue_mm": 310.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.80, "medicaid": 0.05, "commercial": 0.14, "self_pay": 0.01},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "SilverSneakers fitness benefit for Medicare seniors; COVID gym closure decimated enrollment 50%+ then recovered",
    },
]
