"""Extended seed batch 35 — 15 deals (lab/diagnostics, wound care, post-acute, neonatal, addiction treatment).

Sources: public filings, press releases, investor decks, disclosed transaction terms.
All financial figures drawn from public disclosures; marked None where not public.
"""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_35: List[Dict[str, Any]] = [
    {
        "source_id": "ext35_001",
        "source": "seed",
        "deal_name": "BioReference Laboratories – Genoptix Acquisition",
        "year": 2011,
        "buyer": "Genoptix (OPKO Health)",
        "seller": "BioReference Laboratories",
        "sector": "Lab / Diagnostics",
        "deal_type": "Strategic Acquisition",
        "region": "Northeast",
        "geography": "National",
        "ev_mm": 1_530,
        "ebitda_at_entry_mm": 138,
        "ev_ebitda": 11.1,
        "hold_years": 4.0,
        "realized_moic": 2.8,
        "realized_irr": 0.29,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.12, "commercial": 0.44, "self_pay": 0.06},
        "notes": "Large clinical reference laboratory; OPKO integrated into national diagnostics platform; "
                 "COVID testing later boosted volumes. RCM complexity from payer-specific lab billing rules.",
    },
    {
        "source_id": "ext35_002",
        "source": "seed",
        "deal_name": "LabCorp – Covance CRO Acquisition",
        "year": 2015,
        "buyer": "Laboratory Corporation of America",
        "seller": "Covance Inc (public)",
        "sector": "Lab / Diagnostics",
        "deal_type": "Strategic Acquisition",
        "region": "National",
        "geography": "Global",
        "ev_mm": 6_200,
        "ebitda_at_entry_mm": 490,
        "ev_ebitda": 12.7,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": "diversified CRO/lab mix",
        "notes": "Transformative acquisition combining clinical diagnostics with CRO capabilities. "
                 "Created fully integrated drug development and diagnostic platform.",
    },
    {
        "source_id": "ext35_003",
        "source": "seed",
        "deal_name": "Advanced Dermatology and Cosmetic Surgery – ABRY Partners",
        "year": 2017,
        "buyer": "ABRY Partners",
        "seller": "Management / founder",
        "sector": "Dermatology",
        "deal_type": "Platform LBO",
        "region": "Southeast",
        "geography": "Multi-State",
        "ev_mm": 280,
        "ebitda_at_entry_mm": 28,
        "ev_ebitda": 10.0,
        "hold_years": 5.0,
        "realized_moic": 3.4,
        "realized_irr": 0.28,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.08, "commercial": 0.58, "self_pay": 0.06},
        "notes": "Largest dermatology DSO in US at time of sale; 150+ locations SE/FL/TX; "
                 "sold to Harvest Partners 2022. Medical-cosmetic mix supported premium reimbursement.",
    },
    {
        "source_id": "ext35_004",
        "source": "seed",
        "deal_name": "Healogics – Wound Care Management Platform",
        "year": 2014,
        "buyer": "Clayton, Dubilier & Rice",
        "seller": "DFW Capital / management",
        "sector": "Wound Care",
        "deal_type": "Platform LBO",
        "region": "National",
        "geography": "National",
        "ev_mm": 660,
        "ebitda_at_entry_mm": 66,
        "ev_ebitda": 10.0,
        "hold_years": 8.0,
        "realized_moic": 2.1,
        "realized_irr": 0.10,
        "payer_mix": {"medicare": 0.62, "medicaid": 0.10, "commercial": 0.24, "self_pay": 0.04},
        "notes": "Largest wound care management company; hospital outpatient department model. "
                 "Medicare-heavy creates reimbursement risk; eventual restructuring 2022 due to COVID volume loss.",
    },
    {
        "source_id": "ext35_005",
        "source": "seed",
        "deal_name": "BrightSpring Health Services – KKR Buyout",
        "year": 2019,
        "buyer": "KKR",
        "seller": "Onex Corporation",
        "sector": "Home Health / Hospice",
        "deal_type": "Secondary LBO",
        "region": "National",
        "geography": "National",
        "ev_mm": 1_300,
        "ebitda_at_entry_mm": 104,
        "ev_ebitda": 12.5,
        "hold_years": 5.0,
        "realized_moic": 2.9,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.42, "commercial": 0.16, "self_pay": 0.04},
        "notes": "Provider of home- and community-based services for adults with IDD/behavioral health; "
                 "IPO 2024. High Medicaid exposure requires strong state-specific RCM capabilities.",
    },
    {
        "source_id": "ext35_006",
        "source": "seed",
        "deal_name": "Apria Healthcare – Blackstone Take-Private",
        "year": 2008,
        "buyer": "Blackstone Group",
        "seller": "Apria Healthcare Group (NYSE: AHG)",
        "sector": "Home Health / Hospice",
        "deal_type": "Public-to-Private",
        "region": "National",
        "geography": "National",
        "ev_mm": 1_600,
        "ebitda_at_entry_mm": 145,
        "ev_ebitda": 11.0,
        "hold_years": 14.0,
        "realized_moic": 2.0,
        "realized_irr": 0.05,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.15, "commercial": 0.26, "self_pay": 0.04},
        "notes": "Home respiratory and infusion therapy; prolonged hold due to regulatory headwinds "
                 "on HME reimbursement cuts; sold to Option Care Health 2022 for $1.45B.",
    },
    {
        "source_id": "ext35_007",
        "source": "seed",
        "deal_name": "MEDNAX – Pediatrix Medical Group Stake",
        "year": 2016,
        "buyer": "Ares Management",
        "seller": "MEDNAX Inc (minority block)",
        "sector": "Pediatrics / NICU",
        "deal_type": "Minority Investment",
        "region": "National",
        "geography": "National",
        "ev_mm": 1_900,
        "ebitda_at_entry_mm": 250,
        "ev_ebitda": 7.6,
        "hold_years": 6.0,
        "realized_moic": 1.9,
        "realized_irr": 0.10,
        "payer_mix": {"medicare": 0.18, "medicaid": 0.32, "commercial": 0.46, "self_pay": 0.04},
        "notes": "National neonatology and anesthesiology staffing; physician advisory and contract model. "
                 "Valuation pressure from hospital facility consolidation and managed care rate compression.",
    },
    {
        "source_id": "ext35_008",
        "source": "seed",
        "deal_name": "US Physical Therapy – Centre Partners Growth",
        "year": 2013,
        "buyer": "Centre Partners Management",
        "seller": "Existing shareholders",
        "sector": "Physical Therapy / Rehab",
        "deal_type": "Growth Equity",
        "region": "National",
        "geography": "National",
        "ev_mm": 340,
        "ebitda_at_entry_mm": 42,
        "ev_ebitda": 8.1,
        "hold_years": 4.0,
        "realized_moic": 2.6,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.31, "medicaid": 0.09, "commercial": 0.55, "self_pay": 0.05},
        "notes": "538 outpatient PT/OT clinics in 39 states; de novo + tuck-in M&A strategy. "
                 "Commercial mix supports clean-claim rates; workers' comp adds billing complexity.",
    },
    {
        "source_id": "ext35_009",
        "source": "seed",
        "deal_name": "Addiction Centers of America – Crestview Partners",
        "year": 2017,
        "buyer": "Crestview Partners",
        "seller": "Management",
        "sector": "Behavioral Health",
        "deal_type": "Platform LBO",
        "region": "Southeast",
        "geography": "Multi-State",
        "ev_mm": 210,
        "ebitda_at_entry_mm": 21,
        "ev_ebitda": 10.0,
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.32,
        "payer_mix": {"medicare": 0.12, "medicaid": 0.35, "commercial": 0.48, "self_pay": 0.05},
        "notes": "Addiction treatment centers across Southeast; benefited from SUD parity laws and ACA expansion. "
                 "Revenue cycle driven by prior auth intensive commercial managed care contracts.",
    },
    {
        "source_id": "ext35_010",
        "source": "seed",
        "deal_name": "CRC Health Group – Bain Capital Portfolio",
        "year": 2012,
        "buyer": "Bain Capital",
        "seller": "Canaccord Genuity / prior PE",
        "sector": "Behavioral Health",
        "deal_type": "Secondary LBO",
        "region": "National",
        "geography": "National",
        "ev_mm": 1_175,
        "ebitda_at_entry_mm": 117,
        "ev_ebitda": 10.0,
        "hold_years": 3.0,
        "realized_moic": 2.4,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.14, "medicaid": 0.40, "commercial": 0.38, "self_pay": 0.08},
        "notes": "Largest behavioral health provider at acquisition; 145 facilities, SUD + mental health. "
                 "Sold to Acadia Healthcare 2015 for $1.175B. TRICARE military exposure notable.",
    },
    {
        "source_id": "ext35_011",
        "source": "seed",
        "deal_name": "InfuSystem Holdings – ABRY Partners Buyout",
        "year": 2015,
        "buyer": "ABRY Partners",
        "seller": "Public shareholders (NYSE: INFU)",
        "sector": "Home Health / Hospice",
        "deal_type": "Public-to-Private",
        "region": "National",
        "geography": "National",
        "ev_mm": 155,
        "ebitda_at_entry_mm": 22,
        "ev_ebitda": 7.1,
        "hold_years": 3.0,
        "realized_moic": 2.3,
        "realized_irr": 0.28,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.08, "commercial": 0.45, "self_pay": 0.05},
        "notes": "Ambulatory infusion pump rental and services; specialty pharmacy adjacent. "
                 "Competitive prior auth in oncology infusion; re-listed NYSE 2018.",
    },
    {
        "source_id": "ext35_012",
        "source": "seed",
        "deal_name": "Pacific Dental Services – Perot Investments Growth",
        "year": 2014,
        "buyer": "Perot Investments",
        "seller": "Management / founder",
        "sector": "Dental / DSO",
        "deal_type": "Growth Equity",
        "region": "West",
        "geography": "Multi-State",
        "ev_mm": 400,
        "ebitda_at_entry_mm": 50,
        "ev_ebitda": 8.0,
        "hold_years": 5.0,
        "realized_moic": 3.5,
        "realized_irr": 0.29,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.18, "commercial": 0.68, "self_pay": 0.12},
        "notes": "Largest dentist-owned DSO model; private practice partnership vs. employment. "
                 "Strong commercial mix; Medicaid Denti-Cal adds complexity in California market.",
    },
    {
        "source_id": "ext35_013",
        "source": "seed",
        "deal_name": "Smile Brands – Francisco Partners Buyout",
        "year": 2019,
        "buyer": "Francisco Partners",
        "seller": "Ontario Teachers' Pension Plan",
        "sector": "Dental / DSO",
        "deal_type": "Secondary LBO",
        "region": "West",
        "geography": "Multi-State",
        "ev_mm": 520,
        "ebitda_at_entry_mm": 52,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": 2.0,
        "realized_irr": 0.19,
        "payer_mix": {"medicare": 0.01, "medicaid": 0.32, "commercial": 0.58, "self_pay": 0.09},
        "notes": "400+ dental offices Midwest/West; Medicaid-heavy in certain markets. "
                 "COVID-related closures 2020 created temporary revenue disruption; filed Chapter 11 briefly.",
    },
    {
        "source_id": "ext35_014",
        "source": "seed",
        "deal_name": "Kindred Healthcare – Humana Take-Private",
        "year": 2018,
        "buyer": "Humana / TPG / Welsh Carson",
        "seller": "Kindred Healthcare (NYSE: KND)",
        "sector": "Home Health / Hospice",
        "deal_type": "Public-to-Private",
        "region": "National",
        "geography": "National",
        "ev_mm": 4_100,
        "ebitda_at_entry_mm": 328,
        "ev_ebitda": 12.5,
        "hold_years": 3.0,
        "realized_moic": 2.4,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.12, "commercial": 0.14, "self_pay": 0.02},
        "notes": "Largest home health and hospice provider; Humana acquired home health segment. "
                 "Long-term care hospitals and LTACH segment sold separately. Heavy Medicare creates PPS rate risk.",
    },
    {
        "source_id": "ext35_015",
        "source": "seed",
        "deal_name": "NovaBay Pharmaceuticals – Wound Care Division Sale",
        "year": 2020,
        "buyer": "DFB Healthcare Acquisitions",
        "seller": "NovaBay Pharmaceuticals",
        "sector": "Wound Care",
        "deal_type": "Corporate Divestiture",
        "region": "West",
        "geography": "National",
        "ev_mm": 85,
        "ebitda_at_entry_mm": 9,
        "ev_ebitda": 9.4,
        "hold_years": 3.5,
        "realized_moic": 2.7,
        "realized_irr": 0.31,
        "payer_mix": {"medicare": 0.54, "medicaid": 0.11, "commercial": 0.30, "self_pay": 0.05},
        "notes": "Advanced wound care biologics and cellular tissue products; CTP reimbursement "
                 "via HCPCS. Medicare coverage policy changes create reimbursement cliff risk.",
    },
]
