"""Extended seed deals batch 62.

Theme: Women's health — OB/GYN physician groups, fertility/IVF networks,
breast health imaging and surgery centers, midwifery and birthing centers,
and maternal-fetal medicine (MFM) practices. Fifteen synthetic healthcare
PE transactions representing realistic deal economics across vintages
2016-2024 in the women's health services space.
"""

EXTENDED_SEED_DEALS_62 = [
    {
        "company_name": "Willow OB/GYN Partners",
        "sector": "OB/GYN",
        "subsector": "Multi-Site OB/GYN Physician Group",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 31.11,
        "revenue_mm": 141.41,
        "ebitda_margin": 0.22,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.68, "medicare": 0.04, "medicaid": 0.22, "self_pay": 0.06},
        "comm_pct": 0.68,
        "region": "Southeast",
        "buyer": "Webster Capital",
        "status": "Realized",
    },
    {
        "company_name": "Lumen Fertility Network",
        "sector": "Fertility",
        "subsector": "IVF & Reproductive Endocrinology Platform",
        "year": 2020,
        "ev_mm": 680.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 42.5,
        "revenue_mm": 170.0,
        "ebitda_margin": 0.25,
        "hold_years": 4.5,
        "moic": 2.8,
        "irr": 0.2571,
        "payer_mix": {"commercial": 0.74, "medicare": 0.01, "medicaid": 0.03, "self_pay": 0.22},
        "comm_pct": 0.74,
        "region": "National",
        "buyer": "Lee Equity Partners",
        "status": "Active",
    },
    {
        "company_name": "Bloom Maternal-Fetal Medicine",
        "sector": "Maternal Health",
        "subsector": "Maternal-Fetal Medicine Specialty Practice",
        "year": 2017,
        "ev_mm": 210.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 18.26,
        "revenue_mm": 101.44,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 2.2,
        "irr": 0.1404,
        "payer_mix": {"commercial": 0.62, "medicare": 0.03, "medicaid": 0.31, "self_pay": 0.04},
        "comm_pct": 0.62,
        "region": "Midwest",
        "buyer": "Revelstoke Capital Partners",
        "status": "Realized",
    },
    {
        "company_name": "Cedar Midwifery & Birth Center",
        "sector": "Maternal Health",
        "subsector": "Midwifery & Freestanding Birthing Centers",
        "year": 2021,
        "ev_mm": 95.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 7.92,
        "revenue_mm": 39.6,
        "ebitda_margin": 0.20,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": 0.1829,
        "payer_mix": {"commercial": 0.58, "medicare": 0.02, "medicaid": 0.33, "self_pay": 0.07},
        "comm_pct": 0.58,
        "region": "West",
        "buyer": "Shore Capital Partners",
        "status": "Active",
    },
    {
        "company_name": "Aurora Breast Health Centers",
        "sector": "Breast Health",
        "subsector": "Breast Imaging & Diagnostic Centers",
        "year": 2019,
        "ev_mm": 540.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 34.84,
        "revenue_mm": 145.17,
        "ebitda_margin": 0.24,
        "hold_years": 5.5,
        "moic": 3.1,
        "irr": 0.2284,
        "payer_mix": {"commercial": 0.56, "medicare": 0.34, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.56,
        "region": "Northeast",
        "buyer": "HIG Capital",
        "status": "Partially Realized",
    },
    {
        "company_name": "Harbor Women's Care Group",
        "sector": "Women's Health",
        "subsector": "Comprehensive Women's Health MSO",
        "year": 2020,
        "ev_mm": 320.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 24.62,
        "revenue_mm": 117.24,
        "ebitda_margin": 0.21,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.64, "medicare": 0.08, "medicaid": 0.24, "self_pay": 0.04},
        "comm_pct": 0.64,
        "region": "Southeast",
        "buyer": "Riverside Company",
        "status": "Active",
    },
    {
        "company_name": "Genesis IVF Holdings",
        "sector": "Fertility",
        "subsector": "National IVF Clinic Roll-Up",
        "year": 2021,
        "ev_mm": 780.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 44.57,
        "revenue_mm": 159.18,
        "ebitda_margin": 0.28,
        "hold_years": 4.0,
        "moic": 2.9,
        "irr": 0.305,
        "payer_mix": {"commercial": 0.71, "medicare": 0.01, "medicaid": 0.02, "self_pay": 0.26},
        "comm_pct": 0.71,
        "region": "National",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "Magnolia OB Practice Alliance",
        "sector": "OB/GYN",
        "subsector": "Regional OB/GYN Practice Alliance",
        "year": 2016,
        "ev_mm": 150.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 13.64,
        "revenue_mm": 80.24,
        "ebitda_margin": 0.17,
        "hold_years": 5.0,
        "moic": 2.1,
        "irr": 0.16,
        "payer_mix": {"commercial": 0.54, "medicare": 0.05, "medicaid": 0.36, "self_pay": 0.05},
        "comm_pct": 0.54,
        "region": "Southeast",
        "buyer": "Thurston Group",
        "status": "Realized",
    },
    {
        "company_name": "Pinnacle Reproductive Medicine",
        "sector": "Fertility",
        "subsector": "Boutique Fertility & Egg Freezing Centers",
        "year": 2018,
        "ev_mm": 460.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 31.72,
        "revenue_mm": 137.91,
        "ebitda_margin": 0.23,
        "hold_years": 6.5,
        "moic": 3.4,
        "irr": 0.2072,
        "payer_mix": {"commercial": 0.72, "medicare": 0.01, "medicaid": 0.03, "self_pay": 0.24},
        "comm_pct": 0.72,
        "region": "West",
        "buyer": "Amulet Capital Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "Trellis Birth Collective",
        "sector": "Maternal Health",
        "subsector": "Midwifery-Led Birthing & Doula Services",
        "year": 2022,
        "ev_mm": 60.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 5.71,
        "revenue_mm": 38.07,
        "ebitda_margin": 0.15,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.52, "medicare": 0.02, "medicaid": 0.38, "self_pay": 0.08},
        "comm_pct": 0.52,
        "region": "West",
        "buyer": "Inverness Graham Investments",
        "status": "Active",
    },
    {
        "company_name": "Sage Women's Specialty Group",
        "sector": "OB/GYN",
        "subsector": "Urogynecology & OB/GYN Subspecialty Group",
        "year": 2019,
        "ev_mm": 380.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 27.14,
        "revenue_mm": 123.36,
        "ebitda_margin": 0.22,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.66, "medicare": 0.12, "medicaid": 0.18, "self_pay": 0.04},
        "comm_pct": 0.66,
        "region": "Northeast",
        "buyer": "Webster Capital",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Breast Surgery Partners",
        "sector": "Breast Health",
        "subsector": "Breast Surgical Oncology Practice",
        "year": 2020,
        "ev_mm": 250.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 105.26,
        "ebitda_margin": 0.19,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.2033,
        "payer_mix": {"commercial": 0.60, "medicare": 0.30, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.60,
        "region": "Midwest",
        "buyer": "Riverside Company",
        "status": "Active",
    },
    {
        "company_name": "Evergreen Fertility Partners",
        "sector": "Fertility",
        "subsector": "Integrated REI & Fertility Lab Network",
        "year": 2019,
        "ev_mm": 720.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 43.64,
        "revenue_mm": 167.85,
        "ebitda_margin": 0.26,
        "hold_years": 5.5,
        "moic": 3.2,
        "irr": 0.2355,
        "payer_mix": {"commercial": 0.70, "medicare": 0.01, "medicaid": 0.04, "self_pay": 0.25},
        "comm_pct": 0.70,
        "region": "Northeast",
        "buyer": "Lee Equity Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "Heritage OB/GYN Associates",
        "sector": "OB/GYN",
        "subsector": "Community OB/GYN Physician Practice",
        "year": 2021,
        "ev_mm": 130.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 11.3,
        "revenue_mm": 62.78,
        "ebitda_margin": 0.18,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.59, "medicare": 0.06, "medicaid": 0.30, "self_pay": 0.05},
        "comm_pct": 0.59,
        "region": "Midwest",
        "buyer": "Shore Capital Partners",
        "status": "Active",
    },
    {
        "company_name": "Summit Women's Imaging Network",
        "sector": "Breast Health",
        "subsector": "Multi-Modality Breast & Women's Imaging",
        "year": 2018,
        "ev_mm": 580.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 38.67,
        "revenue_mm": 154.68,
        "ebitda_margin": 0.25,
        "hold_years": 6.0,
        "moic": 3.6,
        "irr": 0.238,
        "payer_mix": {"commercial": 0.57, "medicare": 0.33, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.57,
        "region": "National",
        "buyer": "HIG Capital",
        "status": "Realized",
    },
]
