"""Extended seed batch 50 — cardiovascular & cardiac subspecialty PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_50: list[dict] = [
    {
        "source_id": "ext50_001",
        "company_name": "Pinnacle Ambulatory Surgery Partners",
        "sector": "Outpatient Surgery Center (ASC)",
        "year": 2017,
        "ev_mm": 185.0,
        "ev_ebitda": 10.5,
        "moic": 3.4,
        "irr": 0.27,
        "hold_years": 4.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.62, "medicare": 0.28, "medicaid": 0.06, "self_pay": 0.04},
        "geography": "Texas",
        "ebitda_margin": 0.22,
        "revenue_mm": round(185.0 / 10.5 / 0.22, 2),
    },
    {
        "source_id": "ext50_002",
        "company_name": "Meridian Vascular Specialists",
        "sector": "Vascular Surgery Group",
        "year": 2019,
        "ev_mm": 130.0,
        "ev_ebitda": 9.0,
        "moic": 3.1,
        "irr": 0.25,
        "hold_years": 4.0,
        "sponsor": "Audax Private Equity",
        "payer_mix": {"commercial": 0.50, "medicare": 0.42, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "Ohio",
        "ebitda_margin": 0.20,
        "revenue_mm": round(130.0 / 9.0 / 0.20, 2),
    },
    {
        "source_id": "ext50_003",
        "company_name": "Heartland Cath Lab Associates",
        "sector": "Cardiac Catheterization Lab",
        "year": 2015,
        "ev_mm": 210.0,
        "ev_ebitda": 11.0,
        "moic": 3.8,
        "irr": 0.31,
        "hold_years": 4.5,
        "sponsor": "General Atlantic",
        "payer_mix": {"commercial": 0.55, "medicare": 0.38, "medicaid": 0.04, "self_pay": 0.03},
        "geography": "Illinois",
        "ebitda_margin": 0.24,
        "revenue_mm": round(210.0 / 11.0 / 0.24, 2),
    },
    {
        "source_id": "ext50_004",
        "company_name": "Apex Electrophysiology Network",
        "sector": "Electrophysiology Group",
        "year": 2020,
        "ev_mm": 275.0,
        "ev_ebitda": 12.5,
        "moic": 2.9,
        "irr": 0.22,
        "hold_years": 5.0,
        "sponsor": "KKR",
        "payer_mix": {"commercial": 0.60, "medicare": 0.33, "medicaid": 0.04, "self_pay": 0.03},
        "geography": "Florida",
        "ebitda_margin": 0.26,
        "revenue_mm": round(275.0 / 12.5 / 0.26, 2),
    },
    {
        "source_id": "ext50_005",
        "company_name": "Crossroads Peripheral Vascular Care",
        "sector": "Peripheral Vascular",
        "year": 2016,
        "ev_mm": 95.0,
        "ev_ebitda": 8.5,
        "moic": 3.5,
        "irr": 0.29,
        "hold_years": 4.0,
        "sponsor": "Shore Capital Partners",
        "payer_mix": {"commercial": 0.44, "medicare": 0.48, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "Georgia",
        "ebitda_margin": 0.18,
        "revenue_mm": round(95.0 / 8.5 / 0.18, 2),
    },
    {
        "source_id": "ext50_006",
        "company_name": "Summit Structural Heart Institute",
        "sector": "Structural Heart Program",
        "year": 2021,
        "ev_mm": 390.0,
        "ev_ebitda": 13.0,
        "moic": 2.6,
        "irr": 0.21,
        "hold_years": 5.5,
        "sponsor": "Blackstone",
        "payer_mix": {"commercial": 0.52, "medicare": 0.41, "medicaid": 0.04, "self_pay": 0.03},
        "geography": "New York",
        "ebitda_margin": 0.28,
        "revenue_mm": round(390.0 / 13.0 / 0.28, 2),
    },
    {
        "source_id": "ext50_007",
        "company_name": "Valiant Valve Care Centers",
        "sector": "Valve Clinic",
        "year": 2018,
        "ev_mm": 145.0,
        "ev_ebitda": 9.5,
        "moic": 3.3,
        "irr": 0.28,
        "hold_years": 4.0,
        "sponsor": "New Mountain Capital",
        "payer_mix": {"commercial": 0.48, "medicare": 0.44, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "Pennsylvania",
        "ebitda_margin": 0.21,
        "revenue_mm": round(145.0 / 9.5 / 0.21, 2),
    },
    {
        "source_id": "ext50_008",
        "company_name": "Velocity Chest Pain Management Group",
        "sector": "Chest Pain Center Management",
        "year": 2014,
        "ev_mm": 68.0,
        "ev_ebitda": 7.5,
        "moic": 4.0,
        "irr": 0.34,
        "hold_years": 3.5,
        "sponsor": "Varsity Healthcare Partners",
        "payer_mix": {"commercial": 0.57, "medicare": 0.30, "medicaid": 0.09, "self_pay": 0.04},
        "geography": "Tennessee",
        "ebitda_margin": 0.16,
        "revenue_mm": round(68.0 / 7.5 / 0.16, 2),
    },
    {
        "source_id": "ext50_009",
        "company_name": "Crestwood Cardiothoracic Surgical Associates",
        "sector": "Cardiothoracic Surgery",
        "year": 2017,
        "ev_mm": 320.0,
        "ev_ebitda": 11.5,
        "moic": 3.2,
        "irr": 0.26,
        "hold_years": 4.5,
        "sponsor": "TPG Capital",
        "payer_mix": {"commercial": 0.53, "medicare": 0.39, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "California",
        "ebitda_margin": 0.25,
        "revenue_mm": round(320.0 / 11.5 / 0.25, 2),
    },
    {
        "source_id": "ext50_010",
        "company_name": "Cornerstone Heart Failure Management",
        "sector": "Heart Failure Clinic",
        "year": 2019,
        "ev_mm": 112.0,
        "ev_ebitda": 10.0,
        "moic": 3.0,
        "irr": 0.24,
        "hold_years": 4.5,
        "sponsor": "ABRY Partners",
        "payer_mix": {"commercial": 0.38, "medicare": 0.53, "medicaid": 0.07, "self_pay": 0.02},
        "geography": "Michigan",
        "ebitda_margin": 0.19,
        "revenue_mm": round(112.0 / 10.0 / 0.19, 2),
    },
    {
        "source_id": "ext50_011",
        "company_name": "Revive Cardiac Rehabilitation Network",
        "sector": "Cardiac Rehab Network",
        "year": 2016,
        "ev_mm": 58.0,
        "ev_ebitda": 7.0,
        "moic": 4.2,
        "irr": 0.36,
        "hold_years": 3.5,
        "sponsor": "Bain Capital",
        "payer_mix": {"commercial": 0.42, "medicare": 0.50, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "North Carolina",
        "ebitda_margin": 0.15,
        "revenue_mm": round(58.0 / 7.0 / 0.15, 2),
    },
    {
        "source_id": "ext50_012",
        "company_name": "Prism Cardiac Imaging Centers",
        "sector": "Cardiac Imaging Center",
        "year": 2018,
        "ev_mm": 175.0,
        "ev_ebitda": 10.0,
        "moic": 3.6,
        "irr": 0.30,
        "hold_years": 4.0,
        "sponsor": "Carlyle Group",
        "payer_mix": {"commercial": 0.58, "medicare": 0.35, "medicaid": 0.04, "self_pay": 0.03},
        "geography": "Massachusetts",
        "ebitda_margin": 0.23,
        "revenue_mm": round(175.0 / 10.0 / 0.23, 2),
    },
    {
        "source_id": "ext50_013",
        "company_name": "Nexus Interventional Radiology Partners",
        "sector": "Interventional Radiology Group",
        "year": 2020,
        "ev_mm": 240.0,
        "ev_ebitda": 11.0,
        "moic": 2.8,
        "irr": 0.22,
        "hold_years": 5.0,
        "sponsor": "Prospect Capital",
        "payer_mix": {"commercial": 0.60, "medicare": 0.32, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "Arizona",
        "ebitda_margin": 0.27,
        "revenue_mm": round(240.0 / 11.0 / 0.27, 2),
    },
    {
        "source_id": "ext50_014",
        "company_name": "Vantage Neurointerventional Surgery Group",
        "sector": "Neurointerventional Surgery",
        "year": 2021,
        "ev_mm": 420.0,
        "ev_ebitda": 13.5,
        "moic": 2.5,
        "irr": 0.20,
        "hold_years": 6.0,
        "sponsor": "Leonard Green & Partners",
        "payer_mix": {"commercial": 0.56, "medicare": 0.36, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "Colorado",
        "ebitda_margin": 0.29,
        "revenue_mm": round(420.0 / 13.5 / 0.29, 2),
    },
    {
        "source_id": "ext50_015",
        "company_name": "Cedarbrook Cerebrovascular Surgery Associates",
        "sector": "Cerebrovascular Surgery",
        "year": 2013,
        "ev_mm": 88.0,
        "ev_ebitda": 8.0,
        "moic": 4.5,
        "irr": 0.38,
        "hold_years": 3.5,
        "sponsor": "Sverica Capital Management",
        "payer_mix": {"commercial": 0.54, "medicare": 0.37, "medicaid": 0.06, "self_pay": 0.03},
        "geography": "Minnesota",
        "ebitda_margin": 0.17,
        "revenue_mm": round(88.0 / 8.0 / 0.17, 2),
    },
]
