"""Extended seed batch 54 — digital health and pharmacy PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_54: list[dict] = [
    {
        "source_id": "ext54_001",
        "company_name": "ClearPath Telehealth",
        "sector": "telehealth platform",
        "year": 2019,
        "ev_mm": 320.0,
        "ev_ebitda": 18.5,
        "moic": 4.2,
        "irr": 0.38,
        "hold_years": 4.0,
        "sponsor": "General Atlantic",
        "payer_mix": {"commercial": 0.62, "medicare": 0.15, "medicaid": 0.08, "self_pay": 0.15},
        "geography": "National",
        "ebitda_margin": 0.22,
        "revenue_mm": 17.3,
    },
    {
        "source_id": "ext54_002",
        "company_name": "MindBridge Virtual Mental Health",
        "sector": "virtual mental health",
        "year": 2020,
        "ev_mm": 210.0,
        "ev_ebitda": 19.2,
        "moic": 3.8,
        "irr": 0.36,
        "hold_years": 3.5,
        "sponsor": "Insight Partners",
        "payer_mix": {"commercial": 0.58, "medicare": 0.10, "medicaid": 0.12, "self_pay": 0.20},
        "geography": "National",
        "ebitda_margin": 0.25,
        "revenue_mm": 10.9,
    },
    {
        "source_id": "ext54_003",
        "company_name": "TherapeuticOS Digital Health",
        "sector": "digital therapeutics",
        "year": 2018,
        "ev_mm": 155.0,
        "ev_ebitda": 17.8,
        "moic": 4.5,
        "irr": 0.41,
        "hold_years": 3.0,
        "sponsor": "Thoma Bravo",
        "payer_mix": {"commercial": 0.65, "medicare": 0.05, "medicaid": 0.05, "self_pay": 0.25},
        "geography": "National",
        "ebitda_margin": 0.28,
        "revenue_mm": 8.7,
    },
    {
        "source_id": "ext54_004",
        "company_name": "PulseWatch Remote Monitoring",
        "sector": "remote patient monitoring",
        "year": 2017,
        "ev_mm": 185.0,
        "ev_ebitda": 16.4,
        "moic": 3.5,
        "irr": 0.32,
        "hold_years": 4.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.55, "medicare": 0.28, "medicaid": 0.10, "self_pay": 0.07},
        "geography": "Southeast",
        "ebitda_margin": 0.20,
        "revenue_mm": 11.3,
    },
    {
        "source_id": "ext54_005",
        "company_name": "ChronoHealth Chronic Disease Platform",
        "sector": "chronic disease management platform",
        "year": 2019,
        "ev_mm": 275.0,
        "ev_ebitda": 18.0,
        "moic": 4.0,
        "irr": 0.37,
        "hold_years": 3.5,
        "sponsor": "Summit Partners",
        "payer_mix": {"commercial": 0.52, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.06},
        "geography": "Midwest",
        "ebitda_margin": 0.24,
        "revenue_mm": 15.3,
    },
    {
        "source_id": "ext54_006",
        "company_name": "PrimaryNow Virtual Care",
        "sector": "virtual primary care",
        "year": 2020,
        "ev_mm": 390.0,
        "ev_ebitda": 19.5,
        "moic": 3.9,
        "irr": 0.35,
        "hold_years": 4.0,
        "sponsor": "Francisco Partners",
        "payer_mix": {"commercial": 0.68, "medicare": 0.12, "medicaid": 0.08, "self_pay": 0.12},
        "geography": "National",
        "ebitda_margin": 0.26,
        "revenue_mm": 20.0,
    },
    {
        "source_id": "ext54_007",
        "company_name": "ScriptDirect Online Pharmacy",
        "sector": "online pharmacy",
        "year": 2016,
        "ev_mm": 120.0,
        "ev_ebitda": 13.5,
        "moic": 3.2,
        "irr": 0.28,
        "hold_years": 5.0,
        "sponsor": "General Atlantic",
        "payer_mix": {"commercial": 0.60, "medicare": 0.15, "medicaid": 0.05, "self_pay": 0.20},
        "geography": "National",
        "ebitda_margin": 0.15,
        "revenue_mm": 8.9,
    },
    {
        "source_id": "ext54_008",
        "company_name": "RxLogic Prescription Management",
        "sector": "prescription management SaaS",
        "year": 2018,
        "ev_mm": 245.0,
        "ev_ebitda": 19.8,
        "moic": 4.8,
        "irr": 0.42,
        "hold_years": 3.5,
        "sponsor": "Thoma Bravo",
        "payer_mix": {"commercial": 0.70, "medicare": 0.10, "medicaid": 0.08, "self_pay": 0.12},
        "geography": "National",
        "ebitda_margin": 0.32,
        "revenue_mm": 12.4,
    },
    {
        "source_id": "ext54_009",
        "company_name": "AdherePlus Medication Adherence",
        "sector": "medication adherence platform",
        "year": 2021,
        "ev_mm": 175.0,
        "ev_ebitda": 17.5,
        "moic": 3.6,
        "irr": 0.34,
        "hold_years": 3.0,
        "sponsor": "Insight Partners",
        "payer_mix": {"commercial": 0.55, "medicare": 0.20, "medicaid": 0.15, "self_pay": 0.10},
        "geography": "Northeast",
        "ebitda_margin": 0.27,
        "revenue_mm": 10.0,
    },
    {
        "source_id": "ext54_010",
        "company_name": "BenefitCore PBM Technology",
        "sector": "pharmacy benefit technology",
        "year": 2017,
        "ev_mm": 480.0,
        "ev_ebitda": 16.0,
        "moic": 3.4,
        "irr": 0.30,
        "hold_years": 5.5,
        "sponsor": "Francisco Partners",
        "payer_mix": {"commercial": 0.72, "medicare": 0.12, "medicaid": 0.10, "self_pay": 0.06},
        "geography": "National",
        "ebitda_margin": 0.18,
        "revenue_mm": 30.0,
    },
    {
        "source_id": "ext54_011",
        "company_name": "SpecialtyRx Partners",
        "sector": "specialty pharmacy",
        "year": 2015,
        "ev_mm": 560.0,
        "ev_ebitda": 12.5,
        "moic": 2.8,
        "irr": 0.24,
        "hold_years": 5.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.58, "medicare": 0.25, "medicaid": 0.10, "self_pay": 0.07},
        "geography": "National",
        "ebitda_margin": 0.14,
        "revenue_mm": 44.8,
    },
    {
        "source_id": "ext54_012",
        "company_name": "InfuseWell Infusion Pharmacy",
        "sector": "infusion pharmacy",
        "year": 2016,
        "ev_mm": 340.0,
        "ev_ebitda": 11.8,
        "moic": 3.0,
        "irr": 0.26,
        "hold_years": 5.0,
        "sponsor": "Summit Partners",
        "payer_mix": {"commercial": 0.62, "medicare": 0.22, "medicaid": 0.10, "self_pay": 0.06},
        "geography": "Southwest",
        "ebitda_margin": 0.16,
        "revenue_mm": 28.8,
    },
    {
        "source_id": "ext54_013",
        "company_name": "CompoundCraft Pharmacy Solutions",
        "sector": "compounding pharmacy",
        "year": 2019,
        "ev_mm": 88.0,
        "ev_ebitda": 10.5,
        "moic": 3.3,
        "irr": 0.29,
        "hold_years": 4.5,
        "sponsor": "General Atlantic",
        "payer_mix": {"commercial": 0.45, "medicare": 0.12, "medicaid": 0.05, "self_pay": 0.38},
        "geography": "Southeast",
        "ebitda_margin": 0.13,
        "revenue_mm": 8.4,
    },
    {
        "source_id": "ext54_014",
        "company_name": "MailMeds Direct Pharmacy",
        "sector": "mail-order pharmacy",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 11.2,
        "moic": 2.9,
        "irr": 0.25,
        "hold_years": 5.0,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.64, "medicare": 0.20, "medicaid": 0.08, "self_pay": 0.08},
        "geography": "National",
        "ebitda_margin": 0.12,
        "revenue_mm": 37.5,
    },
    {
        "source_id": "ext54_015",
        "company_name": "VigiliRx Pharmacovigilance Platform",
        "sector": "pharmacovigilance platform",
        "year": 2022,
        "ev_mm": 195.0,
        "ev_ebitda": 20.0,
        "moic": 4.3,
        "irr": 0.40,
        "hold_years": 3.5,
        "sponsor": "Thoma Bravo",
        "payer_mix": {"commercial": 0.75, "medicare": 0.08, "medicaid": 0.05, "self_pay": 0.12},
        "geography": "National",
        "ebitda_margin": 0.35,
        "revenue_mm": 9.8,
    },
]
