"""Extended seed batch 12 — deals 256-275.

Covers: pain management, neurology, audiology, behavioral health tech,
spine surgery, fertility / reproductive health, health plan M&A,
and select late-stage healthcare venture/PE crossover deals.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_12: list[dict] = [
    # 256 — Pain management multi-specialty
    {
        "source_id": "seed_256",
        "deal_name": "National Spine & Pain Centers / Excellere Partners",
        "source": "seed",
        "buyer": "Excellere Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2020,
        "ev_mm": 280.0,
        "ebitda_mm": 28.0,
        "ev_ebitda": 10.0,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.10, "commercial": 0.50, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Mid-Atlantic",
        "state": "VA",
        "notes": "Interventional pain + spine; outpatient ASC; Medicare Part B procedure-driven",
    },
    # 257 — Neurology roll-up
    {
        "source_id": "seed_257",
        "deal_name": "Neurology Partners of America / Shore Capital",
        "source": "seed",
        "buyer": "Shore Capital Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2021,
        "ev_mm": 200.0,
        "ebitda_mm": 18.0,
        "ev_ebitda": 11.1,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.52, "medicaid": 0.12, "commercial": 0.33, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "FL",
        "notes": "Neurology + neurosurgery MSO; EEG/EMG + inpatient consult; Medicare-heavy due to age",
    },
    # 258 — Audiology hearing healthcare
    {
        "source_id": "seed_258",
        "deal_name": "HearingLife / Demant",
        "source": "seed",
        "buyer": "Demant (Danish hearing aid company)",
        "seller": "Various independent audiologists",
        "deal_type": "strategic_acquisition",
        "year": 2019,
        "ev_mm": 600.0,
        "ebitda_mm": 48.0,
        "ev_ebitda": 12.5,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.05, "commercial": 0.30, "self_pay": 0.30},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "600+ audiology centers; high self-pay for hearing aids; OTC hearing aid disruption risk",
    },
    # 259 — Behavioral health technology platform
    {
        "source_id": "seed_259",
        "deal_name": "Talkspace / PE Pre-IPO Investment",
        "source": "seed",
        "buyer": "Various PE (pre-SPAC)",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2020,
        "ev_mm": 400.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 2.0,
        "realized_moic": 0.6,
        "realized_irr": -0.22,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.10, "commercial": 0.75, "self_pay": 0.10},
        "hospital_beds": None,
        "region": "National",
        "state": "NY",
        "notes": "Text-based therapy platform; SPAC IPO at $1.4B; rapid post-SPAC multiple compression",
    },
    # 260 — Spine surgery specialty ASC
    {
        "source_id": "seed_260",
        "deal_name": "SpineMark / Revelstoke Capital",
        "source": "seed",
        "buyer": "Revelstoke Capital Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2020,
        "ev_mm": 320.0,
        "ebitda_mm": 30.0,
        "ev_ebitda": 10.7,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.08, "commercial": 0.45, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "IL",
        "notes": "Ambulatory spine surgery; site-of-care shift from hospital to ASC thesis; CMS reimbursement uplift",
    },
    # 261 — Fertility / reproductive endocrinology
    {
        "source_id": "seed_261",
        "deal_name": "CCRM / Weinberg Capital",
        "source": "seed",
        "buyer": "Weinberg Capital Group",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2019,
        "ev_mm": 500.0,
        "ebitda_mm": 45.0,
        "ev_ebitda": 11.1,
        "hold_years": 5.0,
        "realized_moic": 3.5,
        "realized_irr": 0.29,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.02, "commercial": 0.45, "self_pay": 0.51},
        "hospital_beds": None,
        "region": "National",
        "state": "CO",
        "notes": "Premium IVF clinics; high self-pay (fertility usually not covered); employer benefit tailwind",
    },
    # 262 — PACE (Program of All-Inclusive Care for Elderly)
    {
        "source_id": "seed_262",
        "deal_name": "InVivo Therapeutics / PACE Acquisition",
        "source": "seed",
        "buyer": "CareCore National / InVivo",
        "seller": "Non-profit PACE operator",
        "deal_type": "strategic_acquisition",
        "year": 2020,
        "ev_mm": 150.0,
        "ebitda_mm": 12.0,
        "ev_ebitda": 12.5,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.23,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.50, "commercial": 0.00, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "MA",
        "notes": "PACE program; capitated dual-eligible; very high acuity; strong unit economics",
    },
    # 263 — Health plan M&A — MA plan acquisition
    {
        "source_id": "seed_263",
        "deal_name": "Clover Health / SPAC (Social Capital Hedosophia)",
        "source": "seed",
        "buyer": "Public via SPAC",
        "seller": "Founders / PIPE investors",
        "deal_type": "ipo",
        "year": 2021,
        "ev_mm": 3700.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 2.0,
        "realized_moic": 0.15,
        "realized_irr": -0.60,
        "payer_mix": {"medicare": 1.00, "medicaid": 0.00, "commercial": 0.00, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "National",
        "state": "NJ",
        "notes": "Medicare Advantage insurer; SPAC IPO; MLR exceeded 100% multiple quarters; SEC investigation",
    },
    # 264 — Behavioral health IOP chain
    {
        "source_id": "seed_264",
        "deal_name": "Caron Treatment Centers / Riverside Company",
        "source": "seed",
        "buyer": "Riverside Company",
        "seller": "Non-profit conversion",
        "deal_type": "lbo",
        "year": 2021,
        "ev_mm": 260.0,
        "ebitda_mm": 24.0,
        "ev_ebitda": 10.8,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.08, "medicaid": 0.20, "commercial": 0.65, "self_pay": 0.07},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "PA",
        "notes": "Addiction treatment non-profit conversion; residential + PHP/IOP; mental health parity tailwind",
    },
    # 265 — Prosthetics & orthotics
    {
        "source_id": "seed_265",
        "deal_name": "Hanger Clinic / Welsh Carson Buyout",
        "source": "seed",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Public (NYSE: HNGR take-private)",
        "deal_type": "take_private",
        "year": 2016,
        "ev_mm": 1200.0,
        "ebitda_mm": 95.0,
        "ev_ebitda": 12.6,
        "hold_years": 6.0,
        "realized_moic": 2.1,
        "realized_irr": 0.13,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.12, "commercial": 0.30, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Largest prosthetics + orthotics chain; L-code CMS reimbursement risk; diabetic limb loss thesis",
    },
    # 266 — Post-acute joint venture
    {
        "source_id": "seed_266",
        "deal_name": "Genesis HealthCare / Formation Capital",
        "source": "seed",
        "buyer": "Formation Capital / Fillmore Capital",
        "seller": "Public (NYSE: GEN)",
        "deal_type": "take_private",
        "year": 2015,
        "ev_mm": 2400.0,
        "ebitda_mm": 175.0,
        "ev_ebitda": 13.7,
        "hold_years": 5.0,
        "realized_moic": 0.4,
        "realized_irr": -0.18,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.65, "commercial": 0.06, "self_pay": 0.01},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "PA",
        "notes": "550+ skilled nursing facilities; bankruptcy 2020; high Medicaid; COVID + staffing losses",
    },
    # 267 — Healthcare information exchange
    {
        "source_id": "seed_267",
        "deal_name": "CommonWell Health Alliance / HIT Infrastructure",
        "source": "seed",
        "buyer": "Various health IT consortia",
        "seller": "Founders",
        "deal_type": "joint_venture",
        "year": 2019,
        "ev_mm": 300.0,
        "ebitda_mm": 22.0,
        "ev_ebitda": 13.6,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Healthcare interoperability / HIE infrastructure; FHIR API; 21st Century Cures tailwind",
    },
    # 268 — Dialysis alternative / home dialysis
    {
        "source_id": "seed_268",
        "deal_name": "Outset Medical / PE Growth Round",
        "source": "seed",
        "buyer": "Various PE (Series D)",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2019,
        "ev_mm": 500.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 3.0,
        "realized_moic": 4.5,
        "realized_irr": 0.65,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.12, "commercial": 0.16, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Tablo home/acute dialysis machine; IPO 2020; ESRD home modality shift thesis; FDA cleared",
    },
    # 269 — Immunology / biologics infusion
    {
        "source_id": "seed_269",
        "deal_name": "Coram / CVS Health Acquisition",
        "source": "seed",
        "buyer": "CVS Health / Caremark",
        "seller": "Apria Healthcare",
        "deal_type": "strategic_acquisition",
        "year": 2014,
        "ev_mm": 2100.0,
        "ebitda_mm": 160.0,
        "ev_ebitda": 13.1,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.12, "commercial": 0.66, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Specialty home infusion pharmacy; immunology + anti-infective; strategic fit with Caremark PBM",
    },
    # 270 — Genetics / predictive medicine
    {
        "source_id": "seed_270",
        "deal_name": "Invitae / GeneDx Merger",
        "source": "seed",
        "buyer": "Invitae",
        "seller": "Bio-Reference / OPKO Health (GeneDx)",
        "deal_type": "strategic_acquisition",
        "year": 2022,
        "ev_mm": 150.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 2.0,
        "realized_moic": 0.1,
        "realized_irr": -0.70,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.10, "commercial": 0.58, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Pediatric/rare disease genetic testing; Invitae acquired at inflated SPAC price; rapid value destruction",
    },
    # 271 — Retail health clinic
    {
        "source_id": "seed_271",
        "deal_name": "MinuteClinic / CVS Health",
        "source": "seed",
        "buyer": "CVS Health",
        "seller": "Founders / MinuteClinic",
        "deal_type": "strategic_acquisition",
        "year": 2006,
        "ev_mm": 170.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.08, "medicaid": 0.10, "commercial": 0.70, "self_pay": 0.12},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "First US retail health clinic chain acquired by CVS; embedded pharmacy economics; 1,100+ locations",
    },
    # 272 — Surgery center technology platform
    {
        "source_id": "seed_272",
        "deal_name": "Casetabs / Insight Partners",
        "source": "seed",
        "buyer": "Insight Partners",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 180.0,
        "ebitda_mm": 15.0,
        "ev_ebitda": 12.0,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "OR scheduling + communication SaaS; hospital + ASC client base; SaaS metrics: NRR 120%",
    },
    # 273 — Ambulatory care transformation
    {
        "source_id": "seed_273",
        "deal_name": "Pacific Dental Services / Warburg Pincus",
        "source": "seed",
        "buyer": "Warburg Pincus",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2020,
        "ev_mm": 2000.0,
        "ebitda_mm": 155.0,
        "ev_ebitda": 12.9,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.12, "commercial": 0.68, "self_pay": 0.18},
        "hospital_beds": None,
        "region": "West",
        "state": "CA",
        "notes": "DSO; doctor-owned model; 900+ affiliated practices; in-house specialty",
    },
    # 274 — End-stage kidney disease management
    {
        "source_id": "seed_274",
        "deal_name": "Strive Health / General Catalyst",
        "source": "seed",
        "buyer": "General Catalyst",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 450.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.80, "medicaid": 0.12, "commercial": 0.06, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "CO",
        "notes": "CKD-to-ESRD management; value-based CKCC model; ESRD bundle reform tailwind",
    },
    # 275 — Nutrition / metabolic health
    {
        "source_id": "seed_275",
        "deal_name": "Calibrate Health / AXA Venture Partners",
        "source": "seed",
        "buyer": "AXA Venture Partners",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2022,
        "ev_mm": 200.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 3.0,
        "realized_moic": 0.4,
        "realized_irr": -0.24,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.02, "commercial": 0.60, "self_pay": 0.36},
        "hospital_beds": None,
        "region": "National",
        "state": "NY",
        "notes": "GLP-1 metabolic health; obesity drug access platform; employer benefit model; rapid GLP-1 cost pressure",
    },
]
