"""Extended seed deals #65 — radiology and imaging theme.

This module provides a curated list of 15 healthcare private equity deals
focused on radiology and imaging, including outpatient imaging centers,
teleradiology platforms, interventional radiology, musculoskeletal (MSK)
imaging, and women's imaging / breast health.

Each deal is represented as a dict with exactly 17 keys covering deal
identity, financial metrics, payer mix, geography, sponsor, and status.
IRR is derived from MOIC and hold period; EBITDA and revenue are derived
from EV, EV/EBITDA, and EBITDA margin.
"""

EXTENDED_SEED_DEALS_65 = [
    {
        "company_name": "Summit Outpatient Imaging Partners",
        "sector": "Imaging",
        "subsector": "Multi-modality Outpatient Imaging Centers",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 33.6,
        "revenue_mm": 140.0,
        "ebitda_margin": 0.24,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": round(2.6 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.62, "medicare": 0.28, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.62,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "NightHawk Teleradiology Holdings",
        "sector": "Teleradiology",
        "subsector": "Overnight Final Reads Platform",
        "year": 2019,
        "ev_mm": 285.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 20.65,
        "revenue_mm": 68.83,
        "ebitda_margin": 0.30,
        "hold_years": 4.5,
        "moic": 2.2,
        "irr": round(2.2 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.55, "medicare": 0.32, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "National",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "Vascular & Interventional Specialists",
        "sector": "Interventional Radiology",
        "subsector": "Office-Based IR Labs",
        "year": 2020,
        "ev_mm": 195.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 16.96,
        "revenue_mm": 60.57,
        "ebitda_margin": 0.28,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": round(2.4 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.58, "medicare": 0.33, "medicaid": 0.05, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "PinkRose Women's Imaging Network",
        "sector": "Diagnostic Imaging",
        "subsector": "Women's Imaging & Breast Health",
        "year": 2021,
        "ev_mm": 165.0,
        "ev_ebitda": 14.2,
        "ebitda_mm": 11.62,
        "revenue_mm": 48.42,
        "ebitda_margin": 0.24,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": round(1.9 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.68, "medicare": 0.22, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.68,
        "region": "West",
        "buyer": "Cressey",
        "status": "Active",
    },
    {
        "company_name": "OrthoScan MSK Imaging Group",
        "sector": "Imaging",
        "subsector": "Musculoskeletal Imaging",
        "year": 2019,
        "ev_mm": 98.0,
        "ev_ebitda": 10.8,
        "ebitda_mm": 9.07,
        "revenue_mm": 41.23,
        "ebitda_margin": 0.22,
        "hold_years": 5.5,
        "moic": 2.8,
        "irr": round(2.8 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.70, "medicare": 0.18, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.70,
        "region": "Midwest",
        "buyer": "Revelstoke",
        "status": "Partially Realized",
    },
    {
        "company_name": "MeridianRad Imaging Services",
        "sector": "Radiology",
        "subsector": "Hospital-Based Radiology Group",
        "year": 2017,
        "ev_mm": 650.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 55.08,
        "revenue_mm": 229.5,
        "ebitda_margin": 0.24,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": round(3.1 ** (1 / 6.0) - 1, 4),
        "payer_mix": {"commercial": 0.52, "medicare": 0.36, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.52,
        "region": "National",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Cascade Radiology Associates",
        "sector": "Radiology",
        "subsector": "Multi-state Radiology Platform",
        "year": 2022,
        "ev_mm": 540.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 40.91,
        "revenue_mm": 170.46,
        "ebitda_margin": 0.24,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": round(1.6 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.57, "medicare": 0.31, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.57,
        "region": "West",
        "buyer": "Ares",
        "status": "Active",
    },
    {
        "company_name": "BlueWave Teleradiology Solutions",
        "sector": "Teleradiology",
        "subsector": "Subspecialty Remote Reads",
        "year": 2016,
        "ev_mm": 75.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 7.14,
        "revenue_mm": 22.31,
        "ebitda_margin": 0.32,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": round(2.3 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "Lee Equity",
        "status": "Realized",
    },
    {
        "company_name": "Cornerstone Interventional Radiology",
        "sector": "Interventional Radiology",
        "subsector": "Peripheral Vascular & Oncology IR",
        "year": 2021,
        "ev_mm": 310.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 24.22,
        "revenue_mm": 93.15,
        "ebitda_margin": 0.26,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": round(1.7 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.54, "medicare": 0.35, "medicaid": 0.07, "self_pay": 0.04},
        "comm_pct": 0.54,
        "region": "Southeast",
        "buyer": "Bridgepoint",
        "status": "Active",
    },
    {
        "company_name": "Heartland Diagnostic Imaging",
        "sector": "Diagnostic Imaging",
        "subsector": "Freestanding Diagnostic Centers",
        "year": 2018,
        "ev_mm": 225.0,
        "ev_ebitda": 11.2,
        "ebitda_mm": 20.09,
        "revenue_mm": 87.35,
        "ebitda_margin": 0.23,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": round(2.5 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.56, "medicare": 0.30, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.56,
        "region": "Midwest",
        "buyer": "Varsity",
        "status": "Realized",
    },
    {
        "company_name": "Radiance Women's Health Imaging",
        "sector": "Diagnostic Imaging",
        "subsector": "3D Mammography & Breast MRI",
        "year": 2023,
        "ev_mm": 140.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 9.03,
        "revenue_mm": 34.73,
        "ebitda_margin": 0.26,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": round(1.4 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.66, "medicare": 0.24, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.66,
        "region": "Northeast",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Pacific MSK Imaging Alliance",
        "sector": "Imaging",
        "subsector": "Sports Medicine & MSK Imaging",
        "year": 2020,
        "ev_mm": 88.0,
        "ev_ebitda": 10.2,
        "ebitda_mm": 8.63,
        "revenue_mm": 43.15,
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": round(2.1 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.72, "medicare": 0.16, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.72,
        "region": "West",
        "buyer": "Nautic",
        "status": "Active",
    },
    {
        "company_name": "Atlas National Radiology Partners",
        "sector": "Radiology",
        "subsector": "National Rad Physician Platform",
        "year": 2017,
        "ev_mm": 860.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 63.7,
        "revenue_mm": 265.42,
        "ebitda_margin": 0.24,
        "hold_years": 6.5,
        "moic": 3.6,
        "irr": round(3.6 ** (1 / 6.5) - 1, 4),
        "payer_mix": {"commercial": 0.53, "medicare": 0.34, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.53,
        "region": "National",
        "buyer": "KKR",
        "status": "Partially Realized",
    },
    {
        "company_name": "Sentinel Teleradiology Network",
        "sector": "Teleradiology",
        "subsector": "Emergency & Trauma Reads",
        "year": 2022,
        "ev_mm": 175.0,
        "ev_ebitda": 14.8,
        "ebitda_mm": 11.82,
        "revenue_mm": 42.21,
        "ebitda_margin": 0.28,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": round(1.8 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.58, "medicare": 0.30, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "National",
        "buyer": "Ares",
        "status": "Active",
    },
    {
        "company_name": "Coastal Interventional Vascular Group",
        "sector": "Interventional Radiology",
        "subsector": "Office-Based Vascular Access & Venous",
        "year": 2024,
        "ev_mm": 52.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 4.73,
        "revenue_mm": 26.28,
        "ebitda_margin": 0.18,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": round(1.5 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.50, "medicare": 0.38, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "Revelstoke",
        "status": "Active",
    },
]
