"""Extended seed corpus 67: Urgent care and walk-in clinics PE deals.

Theme: urgent care chains, retail clinics, occupational health, and
employer-sponsored clinics. Commercial-heavy payer mixes are characteristic
of this subsector due to episodic, acute, and employer-driven care.
"""

EXTENDED_SEED_DEALS_67 = [
    {
        "company_name": "MedExpress Rapid Care Partners",
        "sector": "Urgent Care",
        "subsector": "Multi-state Urgent Care Chain",
        "year": 2018,
        "ev_mm": 520.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 38.52,
        "revenue_mm": 220.11,
        "ebitda_margin": 0.175,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.68, "medicare": 0.12, "medicaid": 0.10, "self_pay": 0.10},
        "comm_pct": 0.68,
        "region": "Southeast",
        "buyer": "Warburg Pincus",
        "status": "Realized",
    },
    {
        "company_name": "FastTrack Walk-In Medical",
        "sector": "Walk-in Clinics",
        "subsector": "Suburban Walk-in Clinics",
        "year": 2019,
        "ev_mm": 185.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 15.42,
        "revenue_mm": 91.79,
        "ebitda_margin": 0.168,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.2033,
        "payer_mix": {"commercial": 0.62, "medicare": 0.14, "medicaid": 0.12, "self_pay": 0.12},
        "comm_pct": 0.62,
        "region": "Midwest",
        "buyer": "Shore Capital Partners",
        "status": "Realized",
    },
    {
        "company_name": "WorkWell Occupational Health Services",
        "sector": "Occupational Health",
        "subsector": "Workers Comp and Injury Care",
        "year": 2017,
        "ev_mm": 310.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 26.96,
        "revenue_mm": 143.4,
        "ebitda_margin": 0.188,
        "hold_years": 5.5,
        "moic": 2.8,
        "irr": 0.2059,
        "payer_mix": {"commercial": 0.72, "medicare": 0.08, "medicaid": 0.06, "self_pay": 0.14},
        "comm_pct": 0.72,
        "region": "National",
        "buyer": "Revelstoke Capital Partners",
        "status": "Realized",
    },
    {
        "company_name": "QuickCare Retail Clinic Network",
        "sector": "Retail Clinics",
        "subsector": "Pharmacy-Adjacent Retail Clinics",
        "year": 2020,
        "ev_mm": 95.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 6.79,
        "revenue_mm": 48.5,
        "ebitda_margin": 0.14,
        "hold_years": 4.0,
        "moic": 2.0,
        "irr": 0.1892,
        "payer_mix": {"commercial": 0.60, "medicare": 0.16, "medicaid": 0.10, "self_pay": 0.14},
        "comm_pct": 0.60,
        "region": "West",
        "buyer": "Audax Private Equity",
        "status": "Active",
    },
    {
        "company_name": "OnSite Employer Health Solutions",
        "sector": "Employer Health",
        "subsector": "Corporate On-Site Clinics",
        "year": 2019,
        "ev_mm": 425.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 27.42,
        "revenue_mm": 152.33,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.85, "medicare": 0.04, "medicaid": 0.03, "self_pay": 0.08},
        "comm_pct": 0.85,
        "region": "National",
        "buyer": "Welsh Carson Anderson & Stowe",
        "status": "Active",
    },
    {
        "company_name": "Metro Urgent Care Holdings",
        "sector": "Urgent Care",
        "subsector": "Urban Urgent Care Platform",
        "year": 2016,
        "ev_mm": 275.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 21.48,
        "revenue_mm": 116.74,
        "ebitda_margin": 0.184,
        "hold_years": 6.0,
        "moic": 3.2,
        "irr": 0.2139,
        "payer_mix": {"commercial": 0.66, "medicare": 0.12, "medicaid": 0.14, "self_pay": 0.08},
        "comm_pct": 0.66,
        "region": "Northeast",
        "buyer": "TA Associates",
        "status": "Realized",
    },
    {
        "company_name": "Rapid Occ Med Partners",
        "sector": "Occupational Health",
        "subsector": "Employer Injury and Drug Screening",
        "year": 2021,
        "ev_mm": 165.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 13.98,
        "revenue_mm": 77.67,
        "ebitda_margin": 0.18,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": 0.1829,
        "payer_mix": {"commercial": 0.74, "medicare": 0.06, "medicaid": 0.06, "self_pay": 0.14},
        "comm_pct": 0.74,
        "region": "Southeast",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "Clinix Retail Health",
        "sector": "Retail Clinics",
        "subsector": "Grocery-Anchored Retail Clinics",
        "year": 2022,
        "ev_mm": 62.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 4.7,
        "revenue_mm": 36.15,
        "ebitda_margin": 0.13,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": 0.1447,
        "payer_mix": {"commercial": 0.58, "medicare": 0.18, "medicaid": 0.12, "self_pay": 0.12},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Sterling Partners",
        "status": "Active",
    },
    {
        "company_name": "AnyTime Urgent Care Group",
        "sector": "Urgent Care",
        "subsector": "Extended-Hours Urgent Care",
        "year": 2017,
        "ev_mm": 380.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 29.23,
        "revenue_mm": 162.39,
        "ebitda_margin": 0.18,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2136,
        "payer_mix": {"commercial": 0.70, "medicare": 0.10, "medicaid": 0.10, "self_pay": 0.10},
        "comm_pct": 0.70,
        "region": "West",
        "buyer": "General Atlantic",
        "status": "Partially Realized",
    },
    {
        "company_name": "TotalWorker Health Systems",
        "sector": "Employer Health",
        "subsector": "Near-Site Employer Clinics",
        "year": 2020,
        "ev_mm": 240.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 16.55,
        "revenue_mm": 86.2,
        "ebitda_margin": 0.192,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.82, "medicare": 0.05, "medicaid": 0.04, "self_pay": 0.09},
        "comm_pct": 0.82,
        "region": "Northeast",
        "buyer": "Thomas H. Lee Partners",
        "status": "Active",
    },
    {
        "company_name": "SnapClinic Walk-In Network",
        "sector": "Walk-in Clinics",
        "subsector": "Neighborhood Walk-in Clinics",
        "year": 2018,
        "ev_mm": 110.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 10.0,
        "revenue_mm": 55.56,
        "ebitda_margin": 0.18,
        "hold_years": 4.5,
        "moic": 2.2,
        "irr": 0.1915,
        "payer_mix": {"commercial": 0.64, "medicare": 0.14, "medicaid": 0.12, "self_pay": 0.10},
        "comm_pct": 0.64,
        "region": "Southeast",
        "buyer": "Shore Capital Partners",
        "status": "Realized",
    },
    {
        "company_name": "Concentrix Occupational Medicine",
        "sector": "Occupational Health",
        "subsector": "Multi-Site Occ Med Platform",
        "year": 2019,
        "ev_mm": 640.0,
        "ev_ebitda": 14.2,
        "ebitda_mm": 45.07,
        "revenue_mm": 235.97,
        "ebitda_margin": 0.191,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.76, "medicare": 0.06, "medicaid": 0.06, "self_pay": 0.12},
        "comm_pct": 0.76,
        "region": "National",
        "buyer": "Warburg Pincus",
        "status": "Partially Realized",
    },
    {
        "company_name": "NowCare Urgent Centers",
        "sector": "Urgent Care",
        "subsector": "Rural and Small-Town Urgent Care",
        "year": 2021,
        "ev_mm": 145.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 11.6,
        "revenue_mm": 70.3,
        "ebitda_margin": 0.165,
        "hold_years": 3.5,
        "moic": 1.7,
        "irr": 0.1637,
        "payer_mix": {"commercial": 0.58, "medicare": 0.16, "medicaid": 0.16, "self_pay": 0.10},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Revelstoke Capital Partners",
        "status": "Active",
    },
    {
        "company_name": "HealthHub Retail Clinic Partners",
        "sector": "Retail Clinics",
        "subsector": "Big-Box Retail Clinic JV",
        "year": 2023,
        "ev_mm": 78.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 4.88,
        "revenue_mm": 40.67,
        "ebitda_margin": 0.12,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.56, "medicare": 0.18, "medicaid": 0.14, "self_pay": 0.12},
        "comm_pct": 0.56,
        "region": "West",
        "buyer": "Audax Private Equity",
        "status": "Active",
    },
    {
        "company_name": "CorporateCare Onsite Health",
        "sector": "Employer Health",
        "subsector": "Self-Insured Employer Clinics",
        "year": 2022,
        "ev_mm": 355.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 23.67,
        "revenue_mm": 123.28,
        "ebitda_margin": 0.192,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.88, "medicare": 0.03, "medicaid": 0.02, "self_pay": 0.07},
        "comm_pct": 0.88,
        "region": "National",
        "buyer": "Welsh Carson Anderson & Stowe",
        "status": "Active",
    },
]
