"""Extended seed deals batch 61.

Theme: Medical devices, orthopedic implants, cardiovascular devices,
diagnostic equipment, surgical instruments, and vision care devices.
Fifteen synthetic healthcare PE transactions representing realistic
deal economics across vintages 2015-2024 in the medtech space.
"""

EXTENDED_SEED_DEALS_61 = [
    {
        "company_name": "Apex Orthopedic Implants",
        "sector": "Orthopedic Implants",
        "subsector": "Hip & Knee Reconstruction Implants",
        "year": 2018,
        "ev_mm": 620.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 42.76,
        "revenue_mm": 142.53,
        "ebitda_margin": 0.30,
        "hold_years": 5.0,
        "moic": 2.8,
        "irr": 0.2287,
        "payer_mix": {"commercial": 0.52, "medicare": 0.38, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.52,
        "region": "Midwest",
        "buyer": "Ampersand Capital",
        "status": "Realized",
    },
    {
        "company_name": "Cardiolux Medical",
        "sector": "Cardiovascular Devices",
        "subsector": "Structural Heart & TAVR Devices",
        "year": 2020,
        "ev_mm": 890.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 50.86,
        "revenue_mm": 145.31,
        "ebitda_margin": 0.35,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.46, "medicare": 0.46, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.46,
        "region": "West",
        "buyer": "New Mountain Capital",
        "status": "Active",
    },
    {
        "company_name": "Precision Surgical Instruments Co",
        "sector": "Surgical Instruments",
        "subsector": "Minimally Invasive Surgical Tools",
        "year": 2017,
        "ev_mm": 340.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 27.2,
        "revenue_mm": 97.14,
        "ebitda_margin": 0.28,
        "hold_years": 6.0,
        "moic": 3.2,
        "irr": 0.2139,
        "payer_mix": {"commercial": 0.58, "medicare": 0.32, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "ClearSight Vision Technologies",
        "sector": "Vision Care Devices",
        "subsector": "Intraocular Lenses & Phaco Equipment",
        "year": 2019,
        "ev_mm": 475.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 31.67,
        "revenue_mm": 90.49,
        "ebitda_margin": 0.35,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.48, "medicare": 0.44, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.48,
        "region": "National",
        "buyer": "Baird Capital",
        "status": "Realized",
    },
    {
        "company_name": "Helix Spine Systems",
        "sector": "Orthopedic Implants",
        "subsector": "Spinal Fusion & Motion Preservation",
        "year": 2021,
        "ev_mm": 280.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 21.54,
        "revenue_mm": 76.93,
        "ebitda_margin": 0.28,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.62, "medicare": 0.30, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.62,
        "region": "Southeast",
        "buyer": "American Securities",
        "status": "Active",
    },
    {
        "company_name": "Vanguard Diagnostic Imaging",
        "sector": "Diagnostic Equipment",
        "subsector": "MRI & CT Imaging Systems",
        "year": 2016,
        "ev_mm": 1100.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 81.48,
        "revenue_mm": 254.63,
        "ebitda_margin": 0.32,
        "hold_years": 6.0,
        "moic": 3.4,
        "irr": 0.2263,
        "payer_mix": {"commercial": 0.54, "medicare": 0.36, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.54,
        "region": "National",
        "buyer": "TA Associates",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Cardiac Rhythm",
        "sector": "Cardiovascular Devices",
        "subsector": "Pacemakers & ICDs",
        "year": 2015,
        "ev_mm": 750.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 46.88,
        "revenue_mm": 137.88,
        "ebitda_margin": 0.34,
        "hold_years": 7.0,
        "moic": 3.8,
        "irr": 0.2101,
        "payer_mix": {"commercial": 0.44, "medicare": 0.48, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.44,
        "region": "Midwest",
        "buyer": "Montagu",
        "status": "Realized",
    },
    {
        "company_name": "StellarPath Diagnostics",
        "sector": "Diagnostic Equipment",
        "subsector": "Molecular & Point-of-Care Diagnostics",
        "year": 2022,
        "ev_mm": 410.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 26.45,
        "revenue_mm": 80.15,
        "ebitda_margin": 0.33,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.56, "medicare": 0.32, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.56,
        "region": "West",
        "buyer": "Advent International",
        "status": "Active",
    },
    {
        "company_name": "TrueEdge Surgical Systems",
        "sector": "Surgical Instruments",
        "subsector": "Energy-Based Surgical Devices",
        "year": 2020,
        "ev_mm": 525.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 37.5,
        "revenue_mm": 113.64,
        "ebitda_margin": 0.33,
        "hold_years": 4.5,
        "moic": 2.5,
        "irr": 0.2258,
        "payer_mix": {"commercial": 0.60, "medicare": 0.30, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.60,
        "region": "Northeast",
        "buyer": "Hellman & Friedman",
        "status": "Partially Realized",
    },
    {
        "company_name": "Northstar Dental Implant Group",
        "sector": "Dental Devices",
        "subsector": "Dental Implants & Prosthetics",
        "year": 2019,
        "ev_mm": 195.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 16.96,
        "revenue_mm": 70.67,
        "ebitda_margin": 0.24,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.68, "medicare": 0.12, "medicaid": 0.08, "self_pay": 0.12},
        "comm_pct": 0.68,
        "region": "Southeast",
        "buyer": "Warburg Pincus",
        "status": "Realized",
    },
    {
        "company_name": "OptivuePro Ophthalmic Devices",
        "sector": "Vision Care Devices",
        "subsector": "Retinal Imaging & OCT Systems",
        "year": 2023,
        "ev_mm": 160.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 11.85,
        "revenue_mm": 32.92,
        "ebitda_margin": 0.36,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.50, "medicare": 0.42, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.50,
        "region": "West",
        "buyer": "Ampersand Capital",
        "status": "Active",
    },
    {
        "company_name": "Sentinel Vascular Solutions",
        "sector": "Cardiovascular Devices",
        "subsector": "Peripheral Vascular Stents & Catheters",
        "year": 2017,
        "ev_mm": 385.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 27.5,
        "revenue_mm": 91.67,
        "ebitda_margin": 0.30,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2136,
        "payer_mix": {"commercial": 0.50, "medicare": 0.40, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "New Mountain Capital",
        "status": "Realized",
    },
    {
        "company_name": "Keystone Orthobiologics",
        "sector": "Orthopedic Implants",
        "subsector": "Orthobiologics & Bone Graft Substitutes",
        "year": 2022,
        "ev_mm": 225.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 18.75,
        "revenue_mm": 68.18,
        "ebitda_margin": 0.275,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": 0.1447,
        "payer_mix": {"commercial": 0.58, "medicare": 0.33, "medicaid": 0.06, "self_pay": 0.03},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Baird Capital",
        "status": "Active",
    },
    {
        "company_name": "Elevate MedTech Instruments",
        "sector": "Medical Devices",
        "subsector": "Disposable Medical Consumables",
        "year": 2021,
        "ev_mm": 95.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 9.05,
        "revenue_mm": 45.25,
        "ebitda_margin": 0.20,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": 0.1829,
        "payer_mix": {"commercial": 0.54, "medicare": 0.34, "medicaid": 0.09, "self_pay": 0.03},
        "comm_pct": 0.54,
        "region": "Northeast",
        "buyer": "American Securities",
        "status": "Active",
    },
    {
        "company_name": "Horizon Imaging Diagnostics",
        "sector": "Diagnostic Equipment",
        "subsector": "Ultrasound & Portable Imaging",
        "year": 2024,
        "ev_mm": 340.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 20.61,
        "revenue_mm": 58.89,
        "ebitda_margin": 0.35,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.52, "medicare": 0.38, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.52,
        "region": "National",
        "buyer": "TA Associates",
        "status": "Active",
    },
]
