"""Extended corpus seed batch 32 — deals 656–675.

Focus: healthcare IT/RCM, behavioral health, home health, urgent care,
lab/diagnostics, physical therapy.
"""
from __future__ import annotations

from typing import Any, Dict, List

EXTENDED_SEED_DEALS_32: List[Dict[str, Any]] = [
    {
        "source_id": "ext_32_001",
        "deal_name": "Netsmart Technologies – GI Partners take-private",
        "buyer": "GI Partners",
        "seller": "public float / NASDAQ",
        "year": 2016,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 950.0,
        "ebitda_at_entry_mm": 85.0,
        "ev_ebitda": 11.2,
        "hold_years": 5.0,
        "realized_moic": 3.0,
        "realized_irr": 0.25,
        "payer_mix": {"commercial": 0.10, "medicare": 0.40, "medicaid": 0.45, "self_pay": 0.05},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 350.0,
        "leverage_pct": 0.60,
        "notes": "Behavioral health / post-acute EHR; highly Medicaid/Medicare reimbursement-driven",
    },
    {
        "source_id": "ext_32_002",
        "deal_name": "Change Healthcare – McKesson / Blackstone JV",
        "buyer": "Blackstone / McKesson",
        "seller": "McKesson Technology Solutions",
        "year": 2017,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 4600.0,
        "ebitda_at_entry_mm": 550.0,
        "ev_ebitda": 8.4,
        "hold_years": 3.0,
        "realized_moic": 2.5,
        "realized_irr": 0.36,
        "payer_mix": {"commercial": 0.50, "medicare": 0.30, "medicaid": 0.15, "self_pay": 0.05},
        "deal_type": "Carve-out / JV",
        "region": "National",
        "revenue_mm": 3200.0,
        "leverage_pct": 0.62,
        "notes": "Revenue cycle / clearinghouse platform; IPO 2020 at $14.5B",
    },
    {
        "source_id": "ext_32_003",
        "deal_name": "Cotiviti – Veritas Capital LBO",
        "buyer": "Veritas Capital",
        "seller": "Connolly Healthcare",
        "year": 2014,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 1100.0,
        "ebitda_at_entry_mm": 165.0,
        "ev_ebitda": 6.7,
        "hold_years": 4.0,
        "realized_moic": 4.8,
        "realized_irr": 0.48,
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 700.0,
        "leverage_pct": 0.65,
        "notes": "Payment accuracy / analytics SaaS; sold to Verscend 2018 at $4.9B",
    },
    {
        "source_id": "ext_32_004",
        "deal_name": "Inovalon – Nordic Capital take-private",
        "buyer": "Nordic Capital",
        "seller": "NASDAQ public float",
        "year": 2022,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 7300.0,
        "ebitda_at_entry_mm": 330.0,
        "ev_ebitda": 22.1,
        "hold_years": 3.0,
        "realized_moic": 1.6,
        "realized_irr": 0.17,
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.10, "self_pay": 0.02},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 820.0,
        "leverage_pct": 0.65,
        "notes": "Cloud data platform for payers/pharma; high entry multiple, macro headwinds",
    },
    {
        "source_id": "ext_32_005",
        "deal_name": "Acadia Healthcare – Waud Capital growth equity",
        "buyer": "Waud Capital Partners",
        "seller": "founders",
        "year": 2006,
        "sector": "Behavioral Health",
        "ev_mm": 85.0,
        "ebitda_at_entry_mm": 14.0,
        "ev_ebitda": 6.1,
        "hold_years": 5.0,
        "realized_moic": 9.5,
        "realized_irr": 0.57,
        "payer_mix": {"commercial": 0.35, "medicare": 0.12, "medicaid": 0.48, "self_pay": 0.05},
        "deal_type": "Growth Equity",
        "region": "South",
        "revenue_mm": 80.0,
        "notes": "Early-stage Acadia; grew to $3B+ revenue by IPO; one of best-performing BH investments",
    },
    {
        "source_id": "ext_32_006",
        "deal_name": "Universal Health Services – behavioral health expansion",
        "buyer": "UHS (existing)",
        "seller": "Various hospital sellers",
        "year": 2010,
        "sector": "Behavioral Health",
        "ev_mm": 2400.0,
        "ebitda_at_entry_mm": 350.0,
        "ev_ebitda": 6.9,
        "hold_years": 7.0,
        "realized_moic": 3.2,
        "realized_irr": 0.19,
        "payer_mix": {"commercial": 0.30, "medicare": 0.15, "medicaid": 0.50, "self_pay": 0.05},
        "deal_type": "Platform acquisition",
        "region": "National",
        "revenue_mm": 5200.0,
        "notes": "UHS BH segment expansion; high Medicaid mix; 200+ inpatient behavioral facilities",
    },
    {
        "source_id": "ext_32_007",
        "deal_name": "Springstone – Summit Partners growth equity",
        "buyer": "Summit Partners",
        "seller": "Springstone founders",
        "year": 2015,
        "sector": "Behavioral Health",
        "ev_mm": 300.0,
        "ebitda_at_entry_mm": 35.0,
        "ev_ebitda": 8.6,
        "hold_years": 4.0,
        "realized_moic": 4.1,
        "realized_irr": 0.43,
        "payer_mix": {"commercial": 0.55, "medicare": 0.10, "medicaid": 0.30, "self_pay": 0.05},
        "deal_type": "Growth Equity",
        "region": "Southeast",
        "revenue_mm": 220.0,
        "leverage_pct": 0.40,
        "notes": "Chemical dependency / mental health facilities; sold to KKR 2019",
    },
    {
        "source_id": "ext_32_008",
        "deal_name": "BrightSpring Health – Apax Partners platform LBO",
        "buyer": "Apax Partners",
        "seller": "ResCare",
        "year": 2019,
        "sector": "Home Health",
        "ev_mm": 1200.0,
        "ebitda_at_entry_mm": 110.0,
        "ev_ebitda": 10.9,
        "hold_years": 4.0,
        "realized_moic": 2.3,
        "realized_irr": 0.23,
        "payer_mix": {"commercial": 0.15, "medicare": 0.35, "medicaid": 0.45, "self_pay": 0.05},
        "deal_type": "Carve-out",
        "region": "National",
        "revenue_mm": 2200.0,
        "leverage_pct": 0.65,
        "notes": "Home and community-based LTSS; IPO 2024; high Medicaid",
    },
    {
        "source_id": "ext_32_009",
        "deal_name": "Kindred at Home – TPG Capital spin-off",
        "buyer": "TPG Capital",
        "seller": "Kindred Healthcare",
        "year": 2018,
        "sector": "Home Health",
        "ev_mm": 800.0,
        "ebitda_at_entry_mm": 70.0,
        "ev_ebitda": 11.4,
        "hold_years": 3.0,
        "realized_moic": 2.7,
        "realized_irr": 0.36,
        "payer_mix": {"commercial": 0.20, "medicare": 0.62, "medicaid": 0.14, "self_pay": 0.04},
        "deal_type": "Carve-out",
        "region": "National",
        "revenue_mm": 1400.0,
        "leverage_pct": 0.58,
        "notes": "Home health + hospice spin from Kindred; merged with LHC Group 2021",
    },
    {
        "source_id": "ext_32_010",
        "deal_name": "Amedisys – home health organic expansion",
        "buyer": "Amedisys (public NASDAQ)",
        "seller": "Various home health agencies",
        "year": 2012,
        "sector": "Home Health",
        "ev_mm": 650.0,
        "ebitda_at_entry_mm": 72.0,
        "ev_ebitda": 9.0,
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.31,
        "payer_mix": {"commercial": 0.18, "medicare": 0.68, "medicaid": 0.10, "self_pay": 0.04},
        "deal_type": "Public co add-on",
        "region": "National",
        "revenue_mm": 1100.0,
        "notes": "Home health acquisitions 2012-2017; Medicare-dominant; regulatory sensitivity",
    },
    {
        "source_id": "ext_32_011",
        "deal_name": "CityMD – Summit Health / Warburg Pincus merger",
        "buyer": "Warburg Pincus",
        "seller": "CityMD / Summit founders",
        "year": 2019,
        "sector": "Urgent Care",
        "ev_mm": 1500.0,
        "ebitda_at_entry_mm": 140.0,
        "ev_ebitda": 10.7,
        "hold_years": 4.0,
        "realized_moic": 2.8,
        "realized_irr": 0.29,
        "payer_mix": {"commercial": 0.72, "medicare": 0.12, "medicaid": 0.10, "self_pay": 0.06},
        "deal_type": "Merger / LBO",
        "region": "Northeast",
        "revenue_mm": 1100.0,
        "leverage_pct": 0.57,
        "notes": "NYC metro urgent care + multispecialty platform; CVS Aetna JV discussions",
    },
    {
        "source_id": "ext_32_012",
        "deal_name": "NextCare Urgent Care – Dignity Health / JLL Partners",
        "buyer": "JLL Partners",
        "seller": "Dignity Health JV",
        "year": 2017,
        "sector": "Urgent Care",
        "ev_mm": 420.0,
        "ebitda_at_entry_mm": 45.0,
        "ev_ebitda": 9.3,
        "hold_years": 4.0,
        "realized_moic": 2.5,
        "realized_irr": 0.26,
        "payer_mix": {"commercial": 0.65, "medicare": 0.15, "medicaid": 0.12, "self_pay": 0.08},
        "deal_type": "Carve-out",
        "region": "Southwest",
        "revenue_mm": 320.0,
        "notes": "AZ/TX urgent care platform; 150+ locations at exit",
    },
    {
        "source_id": "ext_32_013",
        "deal_name": "LabCorp / Covance integration synergy capture",
        "buyer": "Laboratory Corporation (public)",
        "seller": "Covance shareholders",
        "year": 2015,
        "sector": "Diagnostics / Lab",
        "ev_mm": 6200.0,
        "ebitda_at_entry_mm": 650.0,
        "ev_ebitda": 9.5,
        "hold_years": 4.0,
        "realized_moic": 1.8,
        "realized_irr": 0.16,
        "payer_mix": {"commercial": 0.55, "medicare": 0.28, "medicaid": 0.12, "self_pay": 0.05},
        "deal_type": "Strategic acquisition",
        "region": "National",
        "revenue_mm": 9200.0,
        "notes": "CRO + lab diagnostics combination; synergy realization slower than expected",
    },
    {
        "source_id": "ext_32_014",
        "deal_name": "Mednax Anesthesia / National Anesthesia Services – Temasek",
        "buyer": "Temasek / AMSURG",
        "seller": "Mednax",
        "year": 2020,
        "sector": "Anesthesia",
        "ev_mm": 1200.0,
        "ebitda_at_entry_mm": 145.0,
        "ev_ebitda": 8.3,
        "hold_years": 4.0,
        "realized_moic": 2.1,
        "realized_irr": 0.20,
        "payer_mix": {"commercial": 0.52, "medicare": 0.35, "medicaid": 0.10, "self_pay": 0.03},
        "deal_type": "Carve-out",
        "region": "National",
        "revenue_mm": 1800.0,
        "leverage_pct": 0.60,
        "notes": "Physician anesthesia practice management; NSA surprise billing exposure",
    },
    {
        "source_id": "ext_32_015",
        "deal_name": "KIWI Pediatrics – Windrose Health Investors",
        "buyer": "Windrose Health Investors",
        "seller": "pediatric clinic founders",
        "year": 2021,
        "sector": "Pediatrics",
        "ev_mm": 160.0,
        "ebitda_at_entry_mm": 18.0,
        "ev_ebitda": 8.9,
        "hold_years": 3.0,
        "realized_moic": 3.2,
        "realized_irr": 0.47,
        "payer_mix": {"commercial": 0.45, "medicare": 0.03, "medicaid": 0.48, "self_pay": 0.04},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 110.0,
        "notes": "Pediatric primary care; high Medicaid/CHIP; rapid de novo expansion",
    },
    {
        "source_id": "ext_32_016",
        "deal_name": "JAG Physical Therapy – Quad-C Management",
        "buyer": "Quad-C Management",
        "seller": "JAG-ONE founders",
        "year": 2020,
        "sector": "Physical Therapy",
        "ev_mm": 220.0,
        "ebitda_at_entry_mm": 24.0,
        "ev_ebitda": 9.2,
        "hold_years": 3.5,
        "realized_moic": 3.5,
        "realized_irr": 0.43,
        "payer_mix": {"commercial": 0.68, "medicare": 0.25, "medicaid": 0.04, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "Northeast",
        "revenue_mm": 155.0,
        "notes": "NJ/NY physical + occupational therapy platform; 70+ locations",
    },
    {
        "source_id": "ext_32_017",
        "deal_name": "National Physical Therapy – Varsity Healthcare Partners",
        "buyer": "Varsity Healthcare Partners",
        "seller": "NPT founders",
        "year": 2019,
        "sector": "Physical Therapy",
        "ev_mm": 140.0,
        "ebitda_at_entry_mm": 16.0,
        "ev_ebitda": 8.8,
        "hold_years": 4.0,
        "realized_moic": 3.0,
        "realized_irr": 0.32,
        "payer_mix": {"commercial": 0.65, "medicare": 0.28, "medicaid": 0.05, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Midwest",
        "revenue_mm": 100.0,
        "notes": "Outpatient PT platform; steady Medicare/commercial mix",
    },
    {
        "source_id": "ext_32_018",
        "deal_name": "Primoris Oncology – New Mountain Capital",
        "buyer": "New Mountain Capital",
        "seller": "radiation oncology founders",
        "year": 2021,
        "sector": "Oncology",
        "ev_mm": 600.0,
        "ebitda_at_entry_mm": 58.0,
        "ev_ebitda": 10.3,
        "hold_years": 4.0,
        "realized_moic": 2.8,
        "realized_irr": 0.30,
        "payer_mix": {"commercial": 0.52, "medicare": 0.42, "medicaid": 0.04, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 430.0,
        "notes": "Radiation oncology platform; ASC-linked model; strong Medicare volume",
    },
    {
        "source_id": "ext_32_019",
        "deal_name": "Curant Health – Frazier Healthcare Partners",
        "buyer": "Frazier Healthcare Partners",
        "seller": "Curant founders",
        "year": 2018,
        "sector": "Specialty Pharmacy / RCM",
        "ev_mm": 180.0,
        "ebitda_at_entry_mm": 20.0,
        "ev_ebitda": 9.0,
        "hold_years": 4.0,
        "realized_moic": 3.1,
        "realized_irr": 0.33,
        "payer_mix": {"commercial": 0.62, "medicare": 0.30, "medicaid": 0.06, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 140.0,
        "notes": "Specialty pharmacy adherence management; chronic disease focus",
    },
    {
        "source_id": "ext_32_020",
        "deal_name": "MedRisk – ABRY Partners LBO",
        "buyer": "ABRY Partners",
        "seller": "MedRisk founders",
        "year": 2019,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 330.0,
        "ebitda_at_entry_mm": 38.0,
        "ev_ebitda": 8.7,
        "hold_years": 4.0,
        "realized_moic": 3.3,
        "realized_irr": 0.35,
        "payer_mix": {"commercial": 0.90, "medicare": 0.05, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Northeast",
        "revenue_mm": 240.0,
        "leverage_pct": 0.55,
        "notes": "Workers' comp PT / managed care; essentially 100% commercial payer",
    },
]
