"""Extended seed deal set 74: rheumatology, immunology, infusion therapy, and autoimmune disease management.

This module provides a curated list of 15 healthcare private equity deal records
focused on rheumatology practice management, immunology clinics, ambulatory and
home-based infusion therapy, biologic infusion services, and integrated
autoimmune disease management platforms. Each entry is a dictionary with a
fixed 17-key schema used across the RCM_MC corpus for comparables, base rates,
and backtesting workflows.
"""

EXTENDED_SEED_DEALS_74 = [
    {
        "company_name": "Cascade Rheumatology Partners",
        "sector": "Rheumatology",
        "subsector": "Multi-site rheumatology MSO",
        "year": 2019,
        "ev_mm": 185.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 14.8,
        "revenue_mm": 71.15,
        "ebitda_margin": 0.208,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.58, "medicare": 0.32, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.58,
        "region": "West",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Immunology Associates",
        "sector": "Immunology",
        "subsector": "Allergy and clinical immunology platform",
        "year": 2020,
        "ev_mm": 240.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 18.18,
        "revenue_mm": 80.44,
        "ebitda_margin": 0.226,
        "hold_years": 4.0,
        "moic": 2.3,
        "irr": 0.2315,
        "payer_mix": {"commercial": 0.66, "medicare": 0.22, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.66,
        "region": "Northeast",
        "buyer": "Cressey",
        "status": "Active",
    },
    {
        "company_name": "BrightPath Infusion Services",
        "sector": "Infusion Therapy",
        "subsector": "Ambulatory infusion suite network",
        "year": 2018,
        "ev_mm": 395.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 27.24,
        "revenue_mm": 136.2,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 3.1,
        "irr": 0.2284,
        "payer_mix": {"commercial": 0.71, "medicare": 0.19, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.71,
        "region": "Southeast",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "AutoImmune Health Collaborative",
        "sector": "Autoimmune Care",
        "subsector": "Integrated autoimmune disease management",
        "year": 2021,
        "ev_mm": 310.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": 19.62,
        "revenue_mm": 87.2,
        "ebitda_margin": 0.225,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.62, "medicare": 0.28, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.62,
        "region": "Midwest",
        "buyer": "Frazier",
        "status": "Active",
    },
    {
        "company_name": "Summit Biologics Infusion",
        "sector": "Biologic Infusion",
        "subsector": "Specialty biologic infusion centers",
        "year": 2022,
        "ev_mm": 520.0,
        "ev_ebitda": 16.4,
        "ebitda_mm": 31.71,
        "revenue_mm": 130.76,
        "ebitda_margin": 0.2425,
        "hold_years": 2.5,
        "moic": 1.6,
        "irr": 0.2068,
        "payer_mix": {"commercial": 0.74, "medicare": 0.18, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.74,
        "region": "National",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
    {
        "company_name": "Pioneer Rheumatology Group",
        "sector": "Rheumatology",
        "subsector": "Physician-owned rheumatology consolidation",
        "year": 2017,
        "ev_mm": 95.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 8.64,
        "revenue_mm": 48.0,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 2.8,
        "irr": 0.1872,
        "payer_mix": {"commercial": 0.54, "medicare": 0.36, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.54,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Vanguard Allergy & Immunology",
        "sector": "Immunology",
        "subsector": "Allergy testing and immunotherapy MSO",
        "year": 2016,
        "ev_mm": 68.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 6.48,
        "revenue_mm": 37.03,
        "ebitda_margin": 0.175,
        "hold_years": 6.5,
        "moic": 3.4,
        "irr": 0.2072,
        "payer_mix": {"commercial": 0.69, "medicare": 0.18, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.69,
        "region": "Midwest",
        "buyer": "Silversmith",
        "status": "Realized",
    },
    {
        "company_name": "HomeFirst Infusion Care",
        "sector": "Infusion Therapy",
        "subsector": "Home infusion therapy services",
        "year": 2023,
        "ev_mm": 430.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 28.67,
        "revenue_mm": 114.68,
        "ebitda_margin": 0.25,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.63, "medicare": 0.26, "medicaid": 0.08, "self_pay": 0.03},
        "comm_pct": 0.63,
        "region": "National",
        "buyer": "Harren",
        "status": "Active",
    },
    {
        "company_name": "Keystone Autoimmune Network",
        "sector": "Autoimmune Care",
        "subsector": "Lupus and connective tissue disease clinics",
        "year": 2019,
        "ev_mm": 145.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 12.08,
        "revenue_mm": 55.82,
        "ebitda_margin": 0.2164,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": 0.1914,
        "payer_mix": {"commercial": 0.56, "medicare": 0.31, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.56,
        "region": "Northeast",
        "buyer": "Webster",
        "status": "Partially Realized",
    },
    {
        "company_name": "Cornerstone Biologic Partners",
        "sector": "Biologic Infusion",
        "subsector": "Hospital-adjacent biologic infusion JV",
        "year": 2020,
        "ev_mm": 275.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 19.93,
        "revenue_mm": 82.7,
        "ebitda_margin": 0.241,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.67, "medicare": 0.22, "medicaid": 0.08, "self_pay": 0.03},
        "comm_pct": 0.67,
        "region": "West",
        "buyer": "Sterling",
        "status": "Active",
    },
    {
        "company_name": "Evergreen Rheumatology Alliance",
        "sector": "Rheumatology",
        "subsector": "Rural rheumatology access platform",
        "year": 2021,
        "ev_mm": 78.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 6.78,
        "revenue_mm": 36.06,
        "ebitda_margin": 0.188,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": 0.1829,
        "payer_mix": {"commercial": 0.48, "medicare": 0.38, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.48,
        "region": "Midwest",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Atlas Immunology Holdings",
        "sector": "Immunology",
        "subsector": "Clinical immunology diagnostic platform",
        "year": 2022,
        "ev_mm": 610.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 34.86,
        "revenue_mm": 136.71,
        "ebitda_margin": 0.255,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": 0.1447,
        "payer_mix": {"commercial": 0.70, "medicare": 0.20, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.70,
        "region": "National",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
    {
        "company_name": "SunRidge Infusion Centers",
        "sector": "Infusion Therapy",
        "subsector": "Community-based infusion clinics",
        "year": 2017,
        "ev_mm": 52.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 5.2,
        "revenue_mm": 34.67,
        "ebitda_margin": 0.15,
        "hold_years": 6.0,
        "moic": 3.6,
        "irr": 0.238,
        "payer_mix": {"commercial": 0.60, "medicare": 0.27, "medicaid": 0.10, "self_pay": 0.03},
        "comm_pct": 0.60,
        "region": "Southeast",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "Horizon Autoimmune Specialists",
        "sector": "Autoimmune Care",
        "subsector": "Specialty autoimmune pharmacy and care",
        "year": 2024,
        "ev_mm": 720.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": 38.92,
        "revenue_mm": 139.0,
        "ebitda_margin": 0.28,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.72, "medicare": 0.19, "medicaid": 0.06, "self_pay": 0.03},
        "comm_pct": 0.72,
        "region": "National",
        "buyer": "Audax",
        "status": "Active",
    },
    {
        "company_name": "Riverstone Biologic Infusion Group",
        "sector": "Biologic Infusion",
        "subsector": "Office-based biologic infusion rollup",
        "year": 2018,
        "ev_mm": 168.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 13.12,
        "revenue_mm": 58.83,
        "ebitda_margin": 0.223,
        "hold_years": 5.5,
        "moic": 3.8,
        "irr": 0.2747,
        "payer_mix": {"commercial": 0.65, "medicare": 0.24, "medicaid": 0.08, "self_pay": 0.03},
        "comm_pct": 0.65,
        "region": "West",
        "buyer": "Frazier",
        "status": "Realized",
    },
]
