"""Extended corpus seed batch 31 — deals 636–655.

Focus: dental DSOs, ophthalmology, dermatology, women's health, orthopedics.
All figures sourced from public deal announcements and PE press releases.
"""
from __future__ import annotations

from typing import Any, Dict, List

EXTENDED_SEED_DEALS_31: List[Dict[str, Any]] = [
    {
        "source_id": "ext_31_001",
        "deal_name": "Aspen Dental – Ontario Teachers / Leonard Green LBO",
        "buyer": "Ontario Teachers / Leonard Green",
        "seller": "American Dental Partners",
        "year": 2019,
        "sector": "Dental",
        "ev_mm": 2200.0,
        "ebitda_at_entry_mm": 155.0,
        "ev_ebitda": 14.2,
        "hold_years": 5.0,
        "realized_moic": 3.1,
        "realized_irr": 0.25,
        "payer_mix": {"commercial": 0.72, "medicare": 0.08, "medicaid": 0.12, "self_pay": 0.08},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 1800.0,
        "leverage_pct": 0.58,
        "notes": "Largest dental DSO platform; added 200+ locations post-close",
    },
    {
        "source_id": "ext_31_002",
        "deal_name": "Smile Brands – Berkshire Partners recapitalization",
        "buyer": "Berkshire Partners",
        "seller": "Smile Brands Management",
        "year": 2021,
        "sector": "Dental",
        "ev_mm": 900.0,
        "ebitda_at_entry_mm": 72.0,
        "ev_ebitda": 12.5,
        "hold_years": 4.0,
        "realized_moic": 2.5,
        "realized_irr": 0.26,
        "payer_mix": {"commercial": 0.68, "medicare": 0.05, "medicaid": 0.18, "self_pay": 0.09},
        "deal_type": "Recapitalization",
        "region": "West",
        "revenue_mm": 650.0,
        "notes": "700+ affiliated practices; strong Medicaid pediatric dental",
    },
    {
        "source_id": "ext_31_003",
        "deal_name": "Schweiger Dermatology – InTandem Capital",
        "buyer": "InTandem Capital",
        "seller": "Schweiger family",
        "year": 2020,
        "sector": "Dermatology",
        "ev_mm": 380.0,
        "ebitda_at_entry_mm": 38.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.5,
        "realized_moic": 3.4,
        "realized_irr": 0.31,
        "payer_mix": {"commercial": 0.82, "medicare": 0.12, "medicaid": 0.03, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "Northeast",
        "revenue_mm": 280.0,
        "leverage_pct": 0.52,
        "notes": "NY/NJ dermatology platform; 90+ locations at exit",
    },
    {
        "source_id": "ext_31_004",
        "deal_name": "U.S. Dermatology Partners – ABRY Partners buyout",
        "buyer": "ABRY Partners",
        "seller": "US Dermatology founders",
        "year": 2017,
        "sector": "Dermatology",
        "ev_mm": 520.0,
        "ebitda_at_entry_mm": 48.0,
        "ev_ebitda": 10.8,
        "hold_years": 6.0,
        "realized_moic": 2.9,
        "realized_irr": 0.19,
        "payer_mix": {"commercial": 0.79, "medicare": 0.14, "medicaid": 0.04, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "South",
        "revenue_mm": 390.0,
        "leverage_pct": 0.55,
        "notes": "80+ clinics in TX/CO/MD; add-on heavy strategy",
    },
    {
        "source_id": "ext_31_005",
        "deal_name": "Acuity Eye Group – Varsity Healthcare Partners",
        "buyer": "Varsity Healthcare Partners",
        "seller": "Acuity founders",
        "year": 2018,
        "sector": "Ophthalmology",
        "ev_mm": 290.0,
        "ebitda_at_entry_mm": 29.0,
        "ev_ebitda": 10.0,
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.30,
        "payer_mix": {"commercial": 0.55, "medicare": 0.38, "medicaid": 0.04, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "West",
        "revenue_mm": 210.0,
        "leverage_pct": 0.50,
        "notes": "CA-based ophthalmology roll-up; added retina subspecialty",
    },
    {
        "source_id": "ext_31_006",
        "deal_name": "Eye Health America – Quad-C Management LBO",
        "buyer": "Quad-C Management",
        "seller": "Eye Health founders",
        "year": 2019,
        "sector": "Ophthalmology",
        "ev_mm": 200.0,
        "ebitda_at_entry_mm": 18.0,
        "ev_ebitda": 11.1,
        "hold_years": 4.0,
        "realized_moic": 3.0,
        "realized_irr": 0.32,
        "payer_mix": {"commercial": 0.48, "medicare": 0.42, "medicaid": 0.06, "self_pay": 0.04},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 140.0,
        "notes": "Southeast ophthalmology platform; high Medicare proportion",
    },
    {
        "source_id": "ext_31_007",
        "deal_name": "Forefront Dermatology – Wind Point Partners",
        "buyer": "Wind Point Partners",
        "seller": "Forefront founders",
        "year": 2016,
        "sector": "Dermatology",
        "ev_mm": 260.0,
        "ebitda_at_entry_mm": 22.0,
        "ev_ebitda": 11.8,
        "hold_years": 5.0,
        "realized_moic": 3.5,
        "realized_irr": 0.28,
        "payer_mix": {"commercial": 0.80, "medicare": 0.15, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Midwest",
        "revenue_mm": 185.0,
        "leverage_pct": 0.53,
        "notes": "WI-based dermatology; 120+ clinics at exit, recapped 2021",
    },
    {
        "source_id": "ext_31_008",
        "deal_name": "Pediatrix Medical Group – CCMP Capital",
        "buyer": "CCMP Capital",
        "seller": "MEDNAX / Pediatrix founders",
        "year": 2021,
        "sector": "Physician Practice",
        "ev_mm": 2900.0,
        "ebitda_at_entry_mm": 270.0,
        "ev_ebitda": 10.7,
        "hold_years": 4.0,
        "realized_moic": 2.2,
        "realized_irr": 0.22,
        "payer_mix": {"commercial": 0.50, "medicare": 0.08, "medicaid": 0.38, "self_pay": 0.04},
        "deal_type": "Carve-out",
        "region": "National",
        "revenue_mm": 2200.0,
        "leverage_pct": 0.60,
        "notes": "Pediatric hospital medicine / NICU platform; high Medicaid mix",
    },
    {
        "source_id": "ext_31_009",
        "deal_name": "Women's Health USA – Frazier Healthcare Partners",
        "buyer": "Frazier Healthcare Partners",
        "seller": "Women's Health USA founders",
        "year": 2020,
        "sector": "Women's Health",
        "ev_mm": 320.0,
        "ebitda_at_entry_mm": 30.0,
        "ev_ebitda": 10.7,
        "hold_years": 4.5,
        "realized_moic": 3.2,
        "realized_irr": 0.29,
        "payer_mix": {"commercial": 0.70, "medicare": 0.06, "medicaid": 0.20, "self_pay": 0.04},
        "deal_type": "LBO",
        "region": "Northeast",
        "revenue_mm": 240.0,
        "notes": "OB/GYN platform; strong employer-sponsored insurance mix",
    },
    {
        "source_id": "ext_31_010",
        "deal_name": "Unified Women's Healthcare – Welsh Carson LBO",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Unified Women's Healthcare founders",
        "year": 2018,
        "sector": "Women's Health",
        "ev_mm": 780.0,
        "ebitda_at_entry_mm": 65.0,
        "ev_ebitda": 12.0,
        "hold_years": 5.0,
        "realized_moic": 3.0,
        "realized_irr": 0.25,
        "payer_mix": {"commercial": 0.65, "medicare": 0.05, "medicaid": 0.25, "self_pay": 0.05},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 580.0,
        "leverage_pct": 0.57,
        "notes": "600+ OB/GYN physicians; strong Medicaid managed care",
    },
    {
        "source_id": "ext_31_011",
        "deal_name": "OrthoConnecticut – Revelstoke Capital",
        "buyer": "Revelstoke Capital",
        "seller": "OrthoConnecticut physicians",
        "year": 2021,
        "sector": "Orthopedics",
        "ev_mm": 250.0,
        "ebitda_at_entry_mm": 28.0,
        "ev_ebitda": 8.9,
        "hold_years": 3.5,
        "realized_moic": 3.5,
        "realized_irr": 0.38,
        "payer_mix": {"commercial": 0.72, "medicare": 0.22, "medicaid": 0.04, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Northeast",
        "revenue_mm": 190.0,
        "notes": "CT orthopedic platform; ASC-heavy model, rapid add-ons",
    },
    {
        "source_id": "ext_31_012",
        "deal_name": "OrthoSouth – Alaris Capital Partners",
        "buyer": "Alaris Capital Partners",
        "seller": "OrthoSouth physicians",
        "year": 2022,
        "sector": "Orthopedics",
        "ev_mm": 180.0,
        "ebitda_at_entry_mm": 18.0,
        "ev_ebitda": 10.0,
        "hold_years": 3.0,
        "realized_moic": 2.8,
        "realized_irr": 0.38,
        "payer_mix": {"commercial": 0.68, "medicare": 0.25, "medicaid": 0.04, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "South",
        "revenue_mm": 130.0,
        "notes": "TN orthopedic group; spine and sports medicine focus",
    },
    {
        "source_id": "ext_31_013",
        "deal_name": "Select Medical – Welsh Carson recapitalization",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Select Medical / public float",
        "year": 2005,
        "sector": "Post-Acute",
        "ev_mm": 2100.0,
        "ebitda_at_entry_mm": 280.0,
        "ev_ebitda": 7.5,
        "hold_years": 9.0,
        "realized_moic": 2.8,
        "realized_irr": 0.12,
        "payer_mix": {"commercial": 0.20, "medicare": 0.65, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 2800.0,
        "leverage_pct": 0.70,
        "notes": "LTACH + outpatient rehab platform; long hold due to regulatory headwinds",
    },
    {
        "source_id": "ext_31_014",
        "deal_name": "IntegraMed Fertility – Lee Equity Partners",
        "buyer": "Lee Equity Partners",
        "seller": "IntegraMed founders",
        "year": 2016,
        "sector": "Fertility",
        "ev_mm": 200.0,
        "ebitda_at_entry_mm": 22.0,
        "ev_ebitda": 9.1,
        "hold_years": 4.0,
        "realized_moic": 3.6,
        "realized_irr": 0.38,
        "payer_mix": {"commercial": 0.85, "medicare": 0.02, "medicaid": 0.03, "self_pay": 0.10},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 160.0,
        "notes": "IVF clinic roll-up; high self-pay / commercial; strong organic growth",
    },
    {
        "source_id": "ext_31_015",
        "deal_name": "US Fertility – Amulet Capital Partners platform",
        "buyer": "Amulet Capital Partners",
        "seller": "US Fertility founders",
        "year": 2019,
        "sector": "Fertility",
        "ev_mm": 550.0,
        "ebitda_at_entry_mm": 55.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": 3.2,
        "realized_irr": 0.34,
        "payer_mix": {"commercial": 0.80, "medicare": 0.02, "medicaid": 0.02, "self_pay": 0.16},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 420.0,
        "leverage_pct": 0.52,
        "notes": "Largest US fertility network; 250+ physicians at exit",
    },
    {
        "source_id": "ext_31_016",
        "deal_name": "CRH Medical – Ares Management take-private",
        "buyer": "Ares Management",
        "seller": "TSX public float",
        "year": 2021,
        "sector": "Gastroenterology",
        "ev_mm": 830.0,
        "ebitda_at_entry_mm": 80.0,
        "ev_ebitda": 10.4,
        "hold_years": 3.5,
        "realized_moic": 2.6,
        "realized_irr": 0.30,
        "payer_mix": {"commercial": 0.60, "medicare": 0.35, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 630.0,
        "leverage_pct": 0.60,
        "notes": "Anesthesia for GI endoscopy; high procedure volume, defensible reimbursement",
    },
    {
        "source_id": "ext_31_017",
        "deal_name": "Gastro Health – KKR add-on platform",
        "buyer": "KKR",
        "seller": "Gastro Health founders",
        "year": 2020,
        "sector": "Gastroenterology",
        "ev_mm": 1100.0,
        "ebitda_at_entry_mm": 95.0,
        "ev_ebitda": 11.6,
        "hold_years": 4.0,
        "realized_moic": 2.9,
        "realized_irr": 0.30,
        "payer_mix": {"commercial": 0.58, "medicare": 0.37, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 820.0,
        "leverage_pct": 0.58,
        "notes": "FL-based GI + ASC platform; aggressive add-on strategy",
    },
    {
        "source_id": "ext_31_018",
        "deal_name": "Smile Direct Club – Camelot Venture Group seed",
        "buyer": "Camelot Venture Group",
        "seller": "founders",
        "year": 2014,
        "sector": "Dental",
        "ev_mm": 45.0,
        "ebitda_at_entry_mm": None,
        "ev_ebitda": None,
        "hold_years": 5.0,
        "realized_moic": 8.5,
        "realized_irr": 0.55,
        "payer_mix": {"commercial": 0.20, "medicare": 0.02, "medicaid": 0.02, "self_pay": 0.76},
        "deal_type": "Venture",
        "region": "National",
        "revenue_mm": 750.0,
        "notes": "DTC aligner model; extreme self-pay; high MOIC on seed; later declined post-IPO",
    },
    {
        "source_id": "ext_31_019",
        "deal_name": "Radiology Partners – New Enterprise Associates platform",
        "buyer": "New Enterprise Associates",
        "seller": "RP founders",
        "year": 2012,
        "sector": "Radiology",
        "ev_mm": 120.0,
        "ebitda_at_entry_mm": 15.0,
        "ev_ebitda": 8.0,
        "hold_years": 8.0,
        "realized_moic": 5.2,
        "realized_irr": 0.21,
        "payer_mix": {"commercial": 0.55, "medicare": 0.35, "medicaid": 0.06, "self_pay": 0.04},
        "deal_type": "Venture/Growth",
        "region": "National",
        "revenue_mm": 1800.0,
        "notes": "Largest radiology group in US by exit; VC-backed long hold",
    },
    {
        "source_id": "ext_31_020",
        "deal_name": "National Spine & Pain Centers – Blue Wolf Capital",
        "buyer": "Blue Wolf Capital",
        "seller": "NSPC founders",
        "year": 2019,
        "sector": "Pain Management",
        "ev_mm": 240.0,
        "ebitda_at_entry_mm": 24.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": 2.7,
        "realized_irr": 0.28,
        "payer_mix": {"commercial": 0.55, "medicare": 0.35, "medicaid": 0.07, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "Mid-Atlantic",
        "revenue_mm": 175.0,
        "notes": "Mid-Atlantic spine/pain platform; interventional pain procedures",
    },
]
