"""Extended seed batch 20 — deals 416-435."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_20: List[Dict[str, Any]] = [
    {
        "source_id": "seed_416",
        "deal_name": "Surgical Care Affiliates (SCA) / Frist & KKR LBO",
        "buyer": "KKR / Frist family",
        "seller": "HCA Healthcare / legacy SCA",
        "year": 2007,
        "deal_type": "lbo",
        "sector": "asc",
        "ev_mm": 1050.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 105.0,
        "revenue_mm": 700.0,
        "realized_moic": 3.8,
        "realized_irr": 0.30,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.04, "commercial": 0.64, "self_pay": 0.04},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "ASC platform with HCA co-investment model; site-of-care shift pre-COVID; merged with Tenet/USPI 2017",
    },
    {
        "source_id": "seed_417",
        "deal_name": "Mossrehab / Moss Rehab IRF Network expansion",
        "buyer": "Einstein Healthcare Network / Inova strategic",
        "seller": "Albert Einstein Medical Center legacy",
        "year": 2016,
        "deal_type": "joint_venture",
        "sector": "ltach_post_acute",
        "ev_mm": 320.0,
        "ev_ebitda": 9.0,
        "ebitda_mm": 36.0,
        "revenue_mm": 280.0,
        "realized_moic": 2.1,
        "realized_irr": 0.15,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.68, "medicaid": 0.12, "commercial": 0.17, "self_pay": 0.03},
        "geography": "PA",
        "hospital_beds": 420,
        "source": "seed",
        "notes": "Inpatient rehab + LTACH; Medicare IRF criteria tightening reduced eligible volumes over hold period",
    },
    {
        "source_id": "seed_418",
        "deal_name": "Nant Health / Patrick Soon-Shiong growth equity",
        "buyer": "Patrick Soon-Shiong / various VCs",
        "seller": "Founders",
        "year": 2016,
        "deal_type": "growth_equity",
        "sector": "health_it",
        "ev_mm": 2600.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 150.0,
        "realized_moic": 0.3,
        "realized_irr": -0.20,
        "hold_years": 7.0,
        "payer_mix": None,
        "geography": "CA",
        "hospital_beds": None,
        "source": "seed",
        "notes": "AI + genomics + care delivery vanity project; IPO'd 2016 at $2.6B then declined 90%; burned cash without product traction",
    },
    {
        "source_id": "seed_419",
        "deal_name": "IASIS Healthcare / TPG Capital LBO",
        "buyer": "TPG Capital",
        "seller": "Jordan Industries legacy",
        "year": 2004,
        "deal_type": "lbo",
        "sector": "hospital",
        "ev_mm": 1400.0,
        "ev_ebitda": 7.5,
        "ebitda_mm": 187.0,
        "revenue_mm": 1800.0,
        "realized_moic": 2.5,
        "realized_irr": 0.18,
        "hold_years": 7.0,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.28, "commercial": 0.28, "self_pay": 0.06},
        "geography": "Southwest",
        "hospital_beds": 3900,
        "source": "seed",
        "notes": "Community hospital chain AZ/TX/UT/NV; sold to Steward Health 2017; steady returns from Sun Belt market growth",
    },
    {
        "source_id": "seed_420",
        "deal_name": "CASI Pharmaceuticals / Chinese market specialty pharma",
        "buyer": "Multiple VCs / Frazier Healthcare",
        "seller": "Enzon Pharmaceuticals legacy",
        "year": 2014,
        "deal_type": "lbo",
        "sector": "pharmacy",
        "ev_mm": 120.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 40.0,
        "realized_moic": 0.7,
        "realized_irr": -0.08,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.75, "self_pay": 0.10},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Oncology specialty pharma cross-market play; China commercial pivot failed to generate returns",
    },
    {
        "source_id": "seed_421",
        "deal_name": "BioTelemetry / Philips Healthcare acquisition",
        "buyer": "Philips Healthcare",
        "seller": "Public shareholders",
        "year": 2021,
        "deal_type": "merger",
        "sector": "cardiology",
        "ev_mm": 2800.0,
        "ev_ebitda": 28.0,
        "ebitda_mm": 100.0,
        "revenue_mm": 480.0,
        "realized_moic": 5.5,
        "realized_irr": 0.38,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.08, "commercial": 0.28, "self_pay": 0.04},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Remote cardiac monitoring (MCT/Holter); Philips paid 28x EBITDA; cardiac digital health premium justified by CPT codes",
    },
    {
        "source_id": "seed_422",
        "deal_name": "Acadia Healthcare Florida/Tennessee BH hospital cluster",
        "buyer": "Acadia Healthcare (ACHC)",
        "seller": "Regional system carve-outs",
        "year": 2017,
        "deal_type": "add-on",
        "sector": "behavioral_health",
        "ev_mm": 680.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 62.0,
        "revenue_mm": 340.0,
        "realized_moic": 3.0,
        "realized_irr": 0.24,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.22, "medicaid": 0.38, "commercial": 0.38, "self_pay": 0.02},
        "geography": "Southeast",
        "hospital_beds": 1800,
        "source": "seed",
        "notes": "Acadia bolt-on BH hospital cluster; Medicaid managed care penetration risk offset by commercial mix improvement",
    },
    {
        "source_id": "seed_423",
        "deal_name": "Navicent Health / Atrium Health merger",
        "buyer": "Atrium Health",
        "seller": "Navicent Health System nonprofit",
        "year": 2019,
        "deal_type": "merger",
        "sector": "hospital",
        "ev_mm": 1200.0,
        "ev_ebitda": 8.0,
        "ebitda_mm": 150.0,
        "revenue_mm": 1100.0,
        "realized_moic": 2.0,
        "realized_irr": 0.14,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.28, "commercial": 0.25, "self_pay": 0.05},
        "geography": "GA",
        "hospital_beds": 3800,
        "source": "seed",
        "notes": "Georgia regional health system strategic affiliation; synergies from supply chain + IT shared services",
    },
    {
        "source_id": "seed_424",
        "deal_name": "Capio AB / Ramsay Health Care acquisition",
        "buyer": "Ramsay Health Care",
        "seller": "Fresenius / Nordic PE consortium",
        "year": 2018,
        "deal_type": "merger",
        "sector": "hospital",
        "ev_mm": 4350.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 363.0,
        "revenue_mm": 2800.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.10, "commercial": 0.55, "self_pay": 0.05},
        "geography": "Europe",
        "hospital_beds": 14000,
        "source": "seed",
        "notes": "European hospital operator; Ramsay cross-border expansion; international healthcare PE benchmark deal",
    },
    {
        "source_id": "seed_425",
        "deal_name": "IPC Systems / CareMore merger (telehealth ICU era)",
        "buyer": "Teladoc Health",
        "seller": "InTouch Health / investors",
        "year": 2020,
        "deal_type": "merger",
        "sector": "telehealth",
        "ev_mm": 1100.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 100.0,
        "realized_moic": 2.0,
        "realized_irr": 0.14,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.15, "commercial": 0.45, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Telehealth platform pre-COVID; COVID accelerated adoption; pricing pressure post-pandemic normalization",
    },
    {
        "source_id": "seed_426",
        "deal_name": "Curo Health Services / FC/Patriot Capital add-ons",
        "buyer": "Patriot Capital / founding team",
        "seller": "Regional hospice operators",
        "year": 2015,
        "deal_type": "add-on",
        "sector": "hospice",
        "ev_mm": 320.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 34.0,
        "revenue_mm": 200.0,
        "realized_moic": 3.4,
        "realized_irr": 0.28,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.86, "medicaid": 0.09, "commercial": 0.04, "self_pay": 0.01},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hospice roll-up in underserved rural Southeast markets; hospice benefited from aging demographics + COVID family preferences",
    },
    {
        "source_id": "seed_427",
        "deal_name": "CHC Healthcare / CareFlight Air Medical acquisition",
        "buyer": "Global Medical Response (AMR/Air Methods)",
        "seller": "KKR / legacy aviation investors",
        "year": 2019,
        "deal_type": "merger",
        "sector": "ems",
        "ev_mm": 2800.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 255.0,
        "revenue_mm": 2600.0,
        "realized_moic": 1.8,
        "realized_irr": 0.12,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.18, "commercial": 0.30, "self_pay": 0.07},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Air ambulance + ground EMS mega-merger; NSA surprise billing reform eliminated air ambulance balance-billing premium",
    },
    {
        "source_id": "seed_428",
        "deal_name": "NovaBay Pharmaceuticals / Wound care spinout",
        "buyer": "SWK Holdings / specialty finance",
        "seller": "NovaBay Pharma shareholders",
        "year": 2018,
        "deal_type": "growth_equity",
        "sector": "hospital",
        "ev_mm": 85.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 12.0,
        "realized_moic": 0.4,
        "realized_irr": -0.15,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.10, "commercial": 0.45, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Specialty wound care antimicrobial; FDA delay + hospital formulary penetration challenges; equity value evaporated",
    },
    {
        "source_id": "seed_429",
        "deal_name": "Spring Health / General Catalyst growth equity",
        "buyer": "General Catalyst / Kinnevik",
        "seller": "Founders",
        "year": 2021,
        "deal_type": "growth_equity",
        "sector": "behavioral_health",
        "ev_mm": 2000.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 100.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.10, "commercial": 0.70, "self_pay": 0.15},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Employer-facing mental health benefits platform; $3.3B valuation at Series E; employer mental health benefits acceleration",
    },
    {
        "source_id": "seed_430",
        "deal_name": "Fresenius Kabi / NxStage Medical acquisition",
        "buyer": "Fresenius Medical Care",
        "seller": "NxStage public shareholders",
        "year": 2019,
        "deal_type": "merger",
        "sector": "dialysis",
        "ev_mm": 2000.0,
        "ev_ebitda": 25.0,
        "ebitda_mm": 80.0,
        "revenue_mm": 400.0,
        "realized_moic": 3.8,
        "realized_irr": 0.31,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.78, "medicaid": 0.10, "commercial": 0.10, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Home hemodialysis device + services; ESRD TPEP home dialysis push + Fresenius integration created value",
    },
    {
        "source_id": "seed_431",
        "deal_name": "Nexus Health Systems / RehabCare Group add-on",
        "buyer": "ABRY Partners / RehabCare management",
        "seller": "Kindred Healthcare legacy",
        "year": 2017,
        "deal_type": "add-on",
        "sector": "ltach_post_acute",
        "ev_mm": 220.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 26.0,
        "revenue_mm": 180.0,
        "realized_moic": 2.4,
        "realized_irr": 0.18,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.14, "commercial": 0.13, "self_pay": 0.03},
        "geography": "TX",
        "hospital_beds": 800,
        "source": "seed",
        "notes": "LTACH + SNF in Texas; Medicare site-neutral payment advocacy risk; sold to Kindred at Home rebundling 2022",
    },
    {
        "source_id": "seed_432",
        "deal_name": "Healtheon / WebMD Health merger (original digital health)",
        "buyer": "WebMD Health / Emdeon Communications",
        "seller": "Netscape / Jim Clark",
        "year": 1999,
        "deal_type": "merger",
        "sector": "health_it",
        "ev_mm": 7500.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 95.0,
        "realized_moic": 0.5,
        "realized_irr": -0.08,
        "hold_years": 8.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Dot-com era health IT mega-merger; first digital health bubble; eventually became profitable Emdeon under KKR",
    },
    {
        "source_id": "seed_433",
        "deal_name": "AmSurg / AMSURG + Envision Premerger physician group",
        "buyer": "Sheridan Healthcare / AmSurg",
        "seller": "Sheridan management buyout",
        "year": 2014,
        "deal_type": "merger",
        "sector": "physician_group",
        "ev_mm": 2350.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 168.0,
        "revenue_mm": 1100.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.15, "commercial": 0.50, "self_pay": 0.07},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "ASC + anesthesia platform pre-mega-merger; AmSurg + Sheridan = $5.6B combined; then KKR AMSURG disaster",
    },
    {
        "source_id": "seed_434",
        "deal_name": "ModivCare / Providence Service add-on (personal care)",
        "buyer": "Modivcare Inc. (public)",
        "seller": "Personal care operators",
        "year": 2021,
        "deal_type": "add-on",
        "sector": "home_community_based",
        "ev_mm": 575.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 58.0,
        "revenue_mm": 400.0,
        "realized_moic": 1.9,
        "realized_irr": 0.13,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.82, "commercial": 0.10, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Personal care + NEMT add-ons; Medicaid redetermination unwinding 2023 pressured volumes; macro labor inflation",
    },
    {
        "source_id": "seed_435",
        "deal_name": "One Oncology / General Atlantic + US Oncology merger",
        "buyer": "General Atlantic / US Oncology Network",
        "seller": "Existing oncology practice investors",
        "year": 2021,
        "deal_type": "merger",
        "sector": "oncology",
        "ev_mm": 2300.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 144.0,
        "revenue_mm": 850.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.08, "commercial": 0.34, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Oncology management services + 340B program integration; site-neutral payment risk; drug margin sustains economics",
    },
]
