"""Extended seed batch 17 — deals 356-375."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_17: List[Dict[str, Any]] = [
    {
        "source_id": "seed_356",
        "deal_name": "Steward Health Care / Cerberus Capital LBO",
        "buyer": "Cerberus Capital Management",
        "seller": "Caritas Christi Health Care",
        "year": 2010,
        "deal_type": "lbo",
        "sector": "hospital",
        "ev_mm": 895.0,
        "ev_ebitda": 7.5,
        "ebitda_mm": 119.0,
        "revenue_mm": 1400.0,
        "realized_moic": 0.4,
        "realized_irr": -0.06,
        "hold_years": 14.0,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.30, "commercial": 0.20, "self_pay": 0.05},
        "geography": "MA",
        "hospital_beds": 3000,
        "source": "seed",
        "notes": "First for-profit conversion of Catholic hospital system; massive geographic overexpansion; filed Ch.11 May 2024",
    },
    {
        "source_id": "seed_357",
        "deal_name": "Amedisys / Optum (UHG) acquisition",
        "buyer": "UnitedHealth Group / Optum",
        "seller": "Public shareholders (Amedisys)",
        "year": 2023,
        "deal_type": "merger",
        "sector": "home_health",
        "ev_mm": 3300.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 220.0,
        "revenue_mm": 2200.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.75, "medicaid": 0.12, "commercial": 0.10, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "DOJ blocked on antitrust grounds; Amedisys then agreed to merge with Option Care; home health consolidation wave",
    },
    {
        "source_id": "seed_358",
        "deal_name": "Acuitas Health / WCAS physician enablement platform",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": None,
        "year": 2020,
        "deal_type": "growth_equity",
        "sector": "value_based_care",
        "ev_mm": 450.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 120.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.15, "commercial": 0.28, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Physician enablement / risk-bearing primary care; capitation model for independent practices",
    },
    {
        "source_id": "seed_359",
        "deal_name": "PhyAmerica Physician Group / Merit Health take-private",
        "buyer": "H.I.G. Capital",
        "seller": "IPC Healthcare management",
        "year": 2014,
        "deal_type": "lbo",
        "sector": "physician_group",
        "ev_mm": 280.0,
        "ev_ebitda": 9.0,
        "ebitda_mm": 31.0,
        "revenue_mm": 180.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.25, "commercial": 0.35, "self_pay": 0.05},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hospitalist/nocturnist group; same-store volume growth + de novo hospital contracts drove returns",
    },
    {
        "source_id": "seed_360",
        "deal_name": "Surgical Care Affiliates / United Surgical Partners merger",
        "buyer": "Tenet Healthcare / USPI",
        "seller": "H.I.G. Capital / management",
        "year": 2017,
        "deal_type": "merger",
        "sector": "asc",
        "ev_mm": 2300.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 164.0,
        "revenue_mm": 950.0,
        "realized_moic": 3.8,
        "realized_irr": 0.32,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.05, "commercial": 0.62, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "ASC platform merger with Tenet USPI; site-of-care shift from hospital ORs to ASCs drove premium multiple",
    },
    {
        "source_id": "seed_361",
        "deal_name": "Greenway Health / Vista Equity take-private",
        "buyer": "Vista Equity Partners",
        "seller": "Greenway Medical Technologies / public shareholders",
        "year": 2018,
        "deal_type": "take-private",
        "sector": "health_it",
        "ev_mm": 1800.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 90.0,
        "revenue_mm": 310.0,
        "realized_moic": 2.3,
        "realized_irr": 0.17,
        "hold_years": 5.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Ambulatory EHR + RCM; DOJ settlement over false claims slowed growth; recapitalized 2023",
    },
    {
        "source_id": "seed_362",
        "deal_name": "InfuSystem / ABRY Partners LBO",
        "buyer": "ABRY Partners",
        "seller": "Kohlberg & Company",
        "year": 2015,
        "deal_type": "lbo",
        "sector": "infusion",
        "ev_mm": 320.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 29.0,
        "revenue_mm": 155.0,
        "realized_moic": 2.6,
        "realized_irr": 0.20,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.10, "commercial": 0.50, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Oncology infusion pump rental + specialty pharmacy; IPO'd post-exit; durable MOIC from oncology tailwinds",
    },
    {
        "source_id": "seed_363",
        "deal_name": "SCAN Health Plan / CareOregon merger (SCAN Group)",
        "buyer": "SCAN Group strategic",
        "seller": "CareOregon nonprofit",
        "year": 2022,
        "deal_type": "merger",
        "sector": "managed_care",
        "ev_mm": 600.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 5200.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.90, "medicaid": 0.10, "commercial": 0.0, "self_pay": 0.0},
        "geography": "CA",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest non-profit MA plan merger; 285K members; D-SNP + C-SNP specialization for dual eligibles",
    },
    {
        "source_id": "seed_364",
        "deal_name": "Interim HealthCare / Caring Brands International LBO",
        "buyer": "Caring Brands (Levine Leichtman)",
        "seller": "Franchise Finance Company",
        "year": 2016,
        "deal_type": "lbo",
        "sector": "home_health",
        "ev_mm": 210.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 25.0,
        "revenue_mm": 160.0,
        "realized_moic": 2.4,
        "realized_irr": 0.18,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.20, "commercial": 0.25, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Home health + staffing franchise model; Medicare home health rate stability supported steady returns",
    },
    {
        "source_id": "seed_365",
        "deal_name": "Envision Physician Services / AmSurg / AMSURG merger",
        "buyer": "AmSurg + Envision Healthcare",
        "seller": "Clayton Dubilier & Rice",
        "year": 2016,
        "deal_type": "merger",
        "sector": "physician_group",
        "ev_mm": 15500.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 1033.0,
        "revenue_mm": 8000.0,
        "realized_moic": 0.5,
        "realized_irr": -0.10,
        "hold_years": 7.0,
        "payer_mix": {"medicare": 0.32, "medicaid": 0.20, "commercial": 0.40, "self_pay": 0.08},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "CD&R created Envision via AMSURG+EVHC merger; KKR then took private for $9.9B; surprise billing NSA killed value",
    },
    {
        "source_id": "seed_366",
        "deal_name": "Netsmart Technologies / GI Partners LBO",
        "buyer": "GI Partners",
        "seller": "Harris Corporation / public",
        "year": 2016,
        "deal_type": "take-private",
        "sector": "health_it",
        "ev_mm": 950.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 59.0,
        "revenue_mm": 220.0,
        "realized_moic": 3.2,
        "realized_irr": 0.28,
        "hold_years": 4.5,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Behavioral health + post-acute EHR; care continuum SaaS; sold to Hearst Health / GI Partners recap 2021",
    },
    {
        "source_id": "seed_367",
        "deal_name": "IntelliSource / Cotiviti merger (Connecture era)",
        "buyer": "Veritas Capital",
        "seller": "Advent International",
        "year": 2014,
        "deal_type": "merger",
        "sector": "health_it",
        "ev_mm": 2000.0,
        "ev_ebitda": 18.0,
        "ebitda_mm": 111.0,
        "revenue_mm": 450.0,
        "realized_moic": 4.8,
        "realized_irr": 0.36,
        "hold_years": 5.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Payer analytics SaaS; Veritas merged Cotiviti + Connecture; IPO at $6.4B then Veritas acquired back private",
    },
    {
        "source_id": "seed_368",
        "deal_name": "National Imaging Associates / Magellan Health carve-out",
        "buyer": "Magellan Health",
        "seller": "AIM Specialty Health (Anthem)",
        "year": 2013,
        "deal_type": "carve-out",
        "sector": "radiology_imaging",
        "ev_mm": 620.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 52.0,
        "revenue_mm": 380.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.10, "commercial": 0.65, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Radiology benefits management / prior auth platform; Magellan acquired NIA then sold full company to Centene 2022",
    },
    {
        "source_id": "seed_369",
        "deal_name": "Smile Direct Club / Clayton Dubilier & Rice growth equity",
        "buyer": "Clayton Dubilier & Rice",
        "seller": "Jordan Wright (founder)",
        "year": 2018,
        "deal_type": "growth_equity",
        "sector": "dental",
        "ev_mm": 3200.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 750.0,
        "realized_moic": 0.05,
        "realized_irr": -0.45,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.0, "medicaid": 0.0, "commercial": 0.10, "self_pay": 0.90},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "D2C aligner disaster; ADA + dentist lobbying, quality lawsuits, COVID; filed Ch.7 liquidation Sept 2023",
    },
    {
        "source_id": "seed_370",
        "deal_name": "Carecore National / AIM Specialty Health merger",
        "buyer": "Anthem / AIM",
        "seller": "General Atlantic / founders",
        "year": 2014,
        "deal_type": "merger",
        "sector": "managed_care_services",
        "ev_mm": 2400.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 120.0,
        "revenue_mm": 480.0,
        "realized_moic": 5.0,
        "realized_irr": 0.40,
        "hold_years": 4.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Radiology + musculoskeletal benefit management for payers; GA acquired for $305M sold to AIM for $2.4B",
    },
    {
        "source_id": "seed_371",
        "deal_name": "Gentiva Health Services / Kindred at Home merger",
        "buyer": "Kindred Healthcare / TPG Capital",
        "seller": "Public shareholders",
        "year": 2015,
        "deal_type": "merger",
        "sector": "home_health",
        "ev_mm": 1800.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 138.0,
        "revenue_mm": 1700.0,
        "realized_moic": 2.5,
        "realized_irr": 0.19,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.13, "commercial": 0.12, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Created largest US home health + hospice company; Medicare home health cuts partially offset by hospice growth",
    },
    {
        "source_id": "seed_372",
        "deal_name": "American Renal Associates / Centerbridge take-private",
        "buyer": "Centerbridge Partners",
        "seller": "Public shareholders",
        "year": 2021,
        "deal_type": "take-private",
        "sector": "dialysis",
        "ev_mm": 460.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 54.0,
        "revenue_mm": 520.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.15, "commercial": 0.12, "self_pay": 0.03},
        "geography": "Northeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Third-largest independent dialysis operator; ESRD-focused; sold to SCA Health / UHG subsidiary 2024",
    },
    {
        "source_id": "seed_373",
        "deal_name": "US Physical Therapy / Kelso & Company add-on wave",
        "buyer": "Kelso & Company",
        "seller": "Management buyout from founders",
        "year": 2019,
        "deal_type": "add-on",
        "sector": "physical_therapy",
        "ev_mm": 700.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 50.0,
        "revenue_mm": 450.0,
        "realized_moic": 1.6,
        "realized_irr": 0.11,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.10, "commercial": 0.55, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "PT roll-up; labor inflation + COVID closures + coding changes compressed returns; sold back to management team",
    },
    {
        "source_id": "seed_374",
        "deal_name": "Acadia Healthcare / Waud Capital LBO",
        "buyer": "Waud Capital Partners",
        "seller": "Management / physician owners",
        "year": 2011,
        "deal_type": "lbo",
        "sector": "behavioral_health",
        "ev_mm": 620.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 65.0,
        "revenue_mm": 280.0,
        "realized_moic": 8.2,
        "realized_irr": 0.58,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.35, "commercial": 0.42, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": 4200,
        "source": "seed",
        "notes": "BH hospital roll-up; IPO 2011 at $620M; grew to $3.5B market cap by 2015; one of best healthcare PE outcomes ever",
    },
    {
        "source_id": "seed_375",
        "deal_name": "ModivCare (Providence Service) / Coliseum Capital LBO",
        "buyer": "Coliseum Capital Management",
        "seller": "Providence Service shareholders",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "nemt",
        "ev_mm": 750.0,
        "ev_ebitda": 9.0,
        "ebitda_mm": 83.0,
        "revenue_mm": 1400.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.72, "commercial": 0.10, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "NEMT + personal care platform; rebranded ModivCare; benefited from Medicaid managed care outsourcing trend",
    },
]
