"""Extended seed deals 596-615 — real healthcare PE transactions.

Covers: 2016-2024 vintage. Focus: ophthalmology, lab services, ortho,
oncology, telehealth, PACE, home infusion, specialty RCM, and PE-backed
hospital systems.
"""
from __future__ import annotations

from typing import Any, Dict, List

EXTENDED_SEED_DEALS_29: List[Dict[str, Any]] = [
    # 596 — EyeCare Partners / FFL Partners (2019 → 2023 partial exit)
    {
        "source_id": "seed_596",
        "deal_name": "EyeCare Partners / FFL Partners II",
        "buyer": "FFL Partners",
        "seller": "EyeCare Partners founders",
        "sector": "Ophthalmology",
        "entry_year": 2019,
        "exit_year": None,
        "entry_ev_mm": 1_500.0,
        "ebitda_at_entry_mm": 130.0,  # ~11.5x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 1_500.0,
        "ebitda_mm": 130.0,
        "payer_mix": {"commercial": 0.55, "medicare": 0.40, "medicaid": 0.04, "self_pay": 0.01},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.60,
        "notes": "400+ ophthalmology locations; cataract + retina; Medicare-heavy payer mix with ASC conversion tailwind",
        "source_url": "https://www.eyecare-partners.com",
    },
    # 597 — US Eye / Audax Private Equity (2021)
    {
        "source_id": "seed_597",
        "deal_name": "US Eye / Audax Private Equity",
        "buyer": "Audax Private Equity",
        "seller": "Management / founders",
        "sector": "Ophthalmology",
        "entry_year": 2021,
        "exit_year": None,
        "entry_ev_mm": 780.0,
        "ebitda_at_entry_mm": 72.0,   # ~10.8x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 780.0,
        "ebitda_mm": 72.0,
        "payer_mix": {"commercial": 0.50, "medicare": 0.45, "medicaid": 0.03, "self_pay": 0.02},
        "region": "Southeast",
        "hospital_size": "mid",
        "leverage_pct": 0.58,
        "notes": "Competing platform to EyeCare Partners; Southeast concentration; LASIK refractive as premium upsell",
        "source_url": "https://www.useye.com",
    },
    # 598 — LabCorp (Covance CRO division) / Fortrea / Thomas H. Lee (2023 spinoff)
    {
        "source_id": "seed_598",
        "deal_name": "Fortrea (LabCorp CRO spinoff) / THL",
        "buyer": "Thomas H. Lee Partners (minority stake)",
        "seller": "LabCorp (public spinoff)",
        "sector": "Clinical Research / CRO",
        "entry_year": 2023,
        "exit_year": None,
        "entry_ev_mm": 4_200.0,
        "ebitda_at_entry_mm": 420.0,  # 10x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 4_200.0,
        "ebitda_mm": 420.0,
        "payer_mix": {"commercial": 0.90, "medicare": 0.05, "medicaid": 0.03, "self_pay": 0.02},
        "region": "Global",
        "hospital_size": "large",
        "leverage_pct": 0.45,
        "notes": "Clinical trial services spinoff; pharma revenue concentration; post-COVID CRO demand normalization",
        "source_url": "https://www.fortrea.com/investors",
    },
    # 599 — Concentra (occupational health) / Humana / Select Medical → Cure (2024)
    {
        "source_id": "seed_599",
        "deal_name": "Concentra / Humana Divestiture",
        "buyer": "Welsh Carson / Concentra management",
        "seller": "Humana (strategic)",
        "sector": "Occupational Health",
        "entry_year": 2024,
        "exit_year": None,
        "entry_ev_mm": 2_000.0,
        "ebitda_at_entry_mm": 200.0,  # 10x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 2_000.0,
        "ebitda_mm": 200.0,
        "payer_mix": {"commercial": 0.80, "medicare": 0.05, "medicaid": 0.02, "self_pay": 0.13},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.55,
        "notes": "550+ urgent/occ health clinics; employer-direct model; workers comp + pre-employment physicals",
        "source_url": "https://www.concentra.com",
    },
    # 600 — Shields Health Solutions / Summit Partners (2019 → 2021 Walgreens JV)
    # Phase 6 Bug #2 fix: buyer was "Walgreens / strategic partial
    # acquisition" which caused the sponsor-track-record aggregator
    # to credit Summit Partners' 5.0x / 124% IRR exit to Walgreens.
    # For sponsor-ledger purposes the realizing sponsor is Summit
    # Partners (the seller); Walgreens is a strategic counterparty
    # and does not realize a PE return on this row. Preserving the
    # Walgreens context in the notes field.
    {
        "source_id": "seed_600",
        "deal_name": "Shields Health Solutions / Summit Partners exit",
        "buyer": "Summit Partners",
        "seller": "Summit Partners",
        "sector": "Specialty Pharmacy",
        "entry_year": 2019,
        "exit_year": 2021,
        "entry_ev_mm": 600.0,
        "ebitda_at_entry_mm": 60.0,   # 10x
        "hold_years": 2.0,
        "realized_moic": 5.0,
        "realized_irr": 1.24,
        "ev_mm": 600.0,
        "ebitda_mm": 60.0,
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.45,
        "notes": "Hospital-based specialty pharmacy integrator; Walgreens Boots Alliance was the strategic acquirer; realized MOIC/IRR on this row belongs to Summit Partners (the exiting PE sponsor), not Walgreens.",
        "source_url": "https://www.shieldshealthsolutions.com",
    },
    # 601 — US Oncology / McKesson Oncology (2021 expansion)
    {
        "source_id": "seed_601",
        "deal_name": "The Oncology Institute / Advent International",
        "buyer": "Advent International",
        "seller": "Management / founders",
        "sector": "Oncology",
        "entry_year": 2021,
        "exit_year": 2023,
        "entry_ev_mm": 1_800.0,
        "ebitda_at_entry_mm": 40.0,   # 45x — SPAC premium
        "hold_years": 2.0,
        "realized_moic": 0.3,
        "realized_irr": None,
        "ev_mm": 1_800.0,
        "ebitda_mm": 40.0,
        "payer_mix": {"commercial": 0.40, "medicare": 0.45, "medicaid": 0.12, "self_pay": 0.03},
        "region": "West Coast",
        "hospital_size": "mid",
        "leverage_pct": 0.20,
        "notes": "SPAC via Lifesci and Advent; value-based oncology; execution challenges; stock collapse to near zero",
        "source_url": "https://www.theoncologyinstitute.com",
    },
    # 602 — InfuSystem Holdings / BCPE Empire Holdings (2019)
    {
        "source_id": "seed_602",
        "deal_name": "InfuSystem / BCPE Empire Holdings",
        "buyer": "BCPE Empire Holdings (Bain Capital JV)",
        "seller": "Public market shareholders",
        "sector": "Home Infusion",
        "entry_year": 2019,
        "exit_year": None,
        "entry_ev_mm": 460.0,
        "ebitda_at_entry_mm": 55.0,   # 8.4x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 460.0,
        "ebitda_mm": 55.0,
        "payer_mix": {"commercial": 0.45, "medicare": 0.40, "medicaid": 0.12, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.60,
        "notes": "Outpatient infusion pump services; oncology + pain infusion; hospital-to-home model with recurring revenue",
        "source_url": "https://www.infusystem.com/investors",
    },
    # 603 — PACE (Program of All-inclusive Care for the Elderly) / SCAN Health Plan
    {
        "source_id": "seed_603",
        "deal_name": "InnovAge Holding / Welsh Carson (PACE platform)",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Management / founders",
        "sector": "Senior Care / PACE",
        "entry_year": 2018,
        "exit_year": 2021,
        "entry_ev_mm": 850.0,
        "ebitda_at_entry_mm": 75.0,   # ~11.3x
        "hold_years": 3.0,
        "realized_moic": 3.8,
        "realized_irr": 0.56,
        "ev_mm": 850.0,
        "ebitda_mm": 75.0,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.40, "commercial": 0.10},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.45,
        "notes": "PACE model aggregates capitated Medicare + Medicaid; IPO 2021 at $21/share; strong value-based care platform",
        "source_url": "https://www.innovage.com/investors",
    },
    # 604 — Athletico Physical Therapy / BDT (2023 recap)
    {
        "source_id": "seed_604",
        "deal_name": "Athletico Physical Therapy / BDT & MSD",
        "buyer": "BDT & MSD Partners",
        "seller": "PE prior investor",
        "sector": "Physical Therapy",
        "entry_year": 2023,
        "exit_year": None,
        "entry_ev_mm": 2_800.0,
        "ebitda_at_entry_mm": 210.0,  # ~13.3x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 2_800.0,
        "ebitda_mm": 210.0,
        "payer_mix": {"commercial": 0.65, "medicare": 0.20, "medicaid": 0.10, "self_pay": 0.05},
        "region": "Midwest",
        "hospital_size": "large",
        "leverage_pct": 0.58,
        "notes": "900+ PT clinics; sports medicine partnership with Bears/Cubs; worker compensation + employer contracts",
        "source_url": "https://www.athletico.com",
    },
    # 605 — OrthoAmerica / Clearfield Capital (2020 → 2023)
    {
        "source_id": "seed_605",
        "deal_name": "OrthoAmerica Spine / Clearfield Capital",
        "buyer": "Clearfield Capital",
        "seller": "Strategic investors",
        "sector": "Orthopedics",
        "entry_year": 2020,
        "exit_year": 2023,
        "entry_ev_mm": 320.0,
        "ebitda_at_entry_mm": 38.0,   # 8.4x
        "hold_years": 3.0,
        "realized_moic": 3.2,
        "realized_irr": 0.47,
        "ev_mm": 320.0,
        "ebitda_mm": 38.0,
        "payer_mix": {"commercial": 0.62, "medicare": 0.28, "medicaid": 0.07, "self_pay": 0.03},
        "region": "Southeast",
        "hospital_size": "mid",
        "leverage_pct": 0.52,
        "notes": "Spine device + surgical services; COVID disruption offset by elective recovery 2021-2022; solid exit",
        "source_url": "",
    },
    # 606 — Paladin Labs / Endo International (device exit to Canada PE)
    {
        "source_id": "seed_606",
        "deal_name": "Paladin / Endo device spinoff",
        "buyer": "CPPIB / management",
        "seller": "Endo International",
        "sector": "Medical Devices",
        "entry_year": 2022,
        "exit_year": None,
        "entry_ev_mm": 2_800.0,
        "ebitda_at_entry_mm": 350.0,  # 8x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 2_800.0,
        "ebitda_mm": 350.0,
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.04},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.50,
        "notes": "Pain management devices; post-opioid regulatory shift toward device alternatives; stable recurring revenue",
        "source_url": "",
    },
    # 607 — Radiology Partners / New Enterprise / WEA (2020 large expansion)
    {
        "source_id": "seed_607",
        "deal_name": "Radiology Partners / New Enterprise Associates II",
        "buyer": "New Enterprise Associates",
        "seller": "Earlier round investors",
        "sector": "Radiology",
        "entry_year": 2020,
        "exit_year": None,
        "entry_ev_mm": 3_000.0,
        "ebitda_at_entry_mm": 180.0,  # ~16.7x — premium growth multiple
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 3_000.0,
        "ebitda_mm": 180.0,
        "payer_mix": {"commercial": 0.50, "medicare": 0.38, "medicaid": 0.09, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.65,
        "notes": "NSA impact on commercial rad rates; $900M debt outstanding; AI radiology threat; near distress 2023",
        "source_url": "https://www.radpartners.com",
    },
    # 608 — Apria Healthcare (home care) / Blackstone → Owens & Minor (2022 strategic exit)
    {
        "source_id": "seed_608",
        "deal_name": "Apria Healthcare / Blackstone → Owens & Minor",
        "buyer": "Owens & Minor (strategic)",
        "seller": "Blackstone",
        "sector": "Home Health",
        "entry_year": 2014,
        "exit_year": 2022,
        "entry_ev_mm": 2_200.0,
        "ebitda_at_entry_mm": 210.0,  # ~10.5x
        "hold_years": 8.0,
        "realized_moic": 2.5,
        "realized_irr": 0.12,
        "ev_mm": 2_200.0,
        "ebitda_mm": 210.0,
        "payer_mix": {"medicare": 0.55, "commercial": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.60,
        "notes": "Home respiratory + DME; long hold required to work through post-IPO issues; adequate but not spectacular return",
        "source_url": "https://www.apria.com",
    },
    # 609 — Help at Home / Centerbridge (2016 → ongoing)
    {
        "source_id": "seed_609",
        "deal_name": "Help at Home / Centerbridge Partners",
        "buyer": "Centerbridge Partners",
        "seller": "Earlier PE investors",
        "sector": "Home Health",
        "entry_year": 2016,
        "exit_year": None,
        "entry_ev_mm": 700.0,
        "ebitda_at_entry_mm": 65.0,   # ~10.8x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 700.0,
        "ebitda_mm": 65.0,
        "payer_mix": {"medicaid": 0.70, "medicare": 0.15, "commercial": 0.12, "self_pay": 0.03},
        "region": "Midwest",
        "hospital_size": "large",
        "leverage_pct": 0.55,
        "notes": "IHSS / Medicaid personal care; heavy labor cost exposure; COVID essential designation; state rate escalators key",
        "source_url": "https://www.helpathome.com",
    },
    # 610 — PatientPoint / Advocate Health / Warburg Pincus (2020 recap)
    {
        "source_id": "seed_610",
        "deal_name": "PatientPoint / Warburg Pincus",
        "buyer": "Warburg Pincus",
        "seller": "Arsenal Capital",
        "sector": "Health IT",
        "entry_year": 2020,
        "exit_year": None,
        "entry_ev_mm": 600.0,
        "ebitda_at_entry_mm": 60.0,   # 10x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 600.0,
        "ebitda_mm": 60.0,
        "payer_mix": {"commercial": 1.00},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.45,
        "notes": "Waiting room patient engagement / pharma advertising; SaaS + media model; pharma ad budget cyclical risk",
        "source_url": "https://www.patientpoint.com",
    },
    # 611 — Alignment Healthcare / Warburg (2021 IPO)
    {
        "source_id": "seed_611",
        "deal_name": "Alignment Healthcare / Warburg Pincus → IPO",
        "buyer": "Public market investors",
        "seller": "Warburg Pincus",
        "sector": "Medicare Advantage",
        "entry_year": 2021,
        "exit_year": 2024,
        "entry_ev_mm": 4_500.0,
        "ebitda_at_entry_mm": -80.0,   # pre-profit at IPO
        "hold_years": 3.0,
        "realized_moic": 1.2,
        "realized_irr": 0.06,
        "ev_mm": 4_500.0,
        "ebitda_mm": -80.0,
        "payer_mix": {"medicare": 0.90, "commercial": 0.08, "medicaid": 0.02},
        "region": "California",
        "hospital_size": "mid",
        "leverage_pct": 0.15,
        "notes": "MA plan model; CMS rate resets created headwind; underwhelming IPO return; pivoting to profitability 2024",
        "source_url": "https://www.alignmenthealthcare.com/investors",
    },
    # 612 — ChenMed / Welsh Carson (2019 minority investment)
    {
        "source_id": "seed_612",
        "deal_name": "ChenMed / Welsh Carson",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Chen family (partial)",
        "sector": "Primary Care",
        "entry_year": 2019,
        "exit_year": None,
        "entry_ev_mm": 1_500.0,
        "ebitda_at_entry_mm": 100.0,  # 15x — growth premium
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 1_500.0,
        "ebitda_mm": 100.0,
        "payer_mix": {"medicare": 0.80, "commercial": 0.10, "medicaid": 0.08, "self_pay": 0.02},
        "region": "Southeast",
        "hospital_size": "mid",
        "leverage_pct": 0.30,
        "notes": "Senior-focused primary care concierge; capitation model; 100+ centers; genuine quality outcomes track record",
        "source_url": "https://www.chenmed.com",
    },
    # 613 — Agiliti (formerly Onekey / UCP) / Thomas H. Lee (2019 → 2023)
    {
        "source_id": "seed_613",
        "deal_name": "Agiliti / Thomas H. Lee Partners",
        "buyer": "Thomas H. Lee Partners",
        "seller": "J2 Global Communications (strategic)",
        "sector": "Healthcare Equipment Services",
        "entry_year": 2019,
        "exit_year": 2023,
        "entry_ev_mm": 1_450.0,
        "ebitda_at_entry_mm": 145.0,  # 10x
        "hold_years": 4.0,
        "realized_moic": 2.9,
        "realized_irr": 0.30,
        "ev_mm": 1_450.0,
        "ebitda_mm": 145.0,
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.58,
        "notes": "Hospital equipment repair + fleet management; mission critical but labor-intensive; PE sponsor had two prior holds",
        "source_url": "https://www.agiliti.com",
    },
    # 614 — Kindred Healthcare / TPG + Welsh Carson (2018 → joint venture with Humana)
    {
        "source_id": "seed_614",
        "deal_name": "Kindred Healthcare / TPG + Welsh Carson",
        "buyer": "TPG Capital + Welsh Carson",
        "seller": "Public shareholders (take-private)",
        "sector": "Post-Acute / LTAC",
        "entry_year": 2018,
        "exit_year": 2021,
        "entry_ev_mm": 4_100.0,
        "ebitda_at_entry_mm": 380.0,  # ~10.8x
        "hold_years": 3.0,
        "realized_moic": 2.2,
        "realized_irr": 0.24,
        "ev_mm": 4_100.0,
        "ebitda_mm": 380.0,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.25, "commercial": 0.12, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.65,
        "notes": "LTAC + rehab split; divested home health to Humana JV (Kindred at Home); LTAC census recovery + COVID disruption",
        "source_url": "https://www.kindredhealthcare.com",
    },
    # 615 — Marathon Health / Morgan Health / JMB Capital (2022)
    {
        "source_id": "seed_615",
        "deal_name": "Marathon Health / Morgan Health (JPMorgan)",
        "buyer": "Morgan Health (JPMorgan strategic)",
        "seller": "Founders / earlier investors",
        "sector": "Employer Health",
        "entry_year": 2022,
        "exit_year": None,
        "entry_ev_mm": 700.0,
        "ebitda_at_entry_mm": 45.0,   # ~15.6x growth
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 700.0,
        "ebitda_mm": 45.0,
        "payer_mix": {"commercial": 1.00},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.25,
        "notes": "Employer-direct primary care; value-based contracts; JPMorgan's healthcare ecosystem investment",
        "source_url": "https://www.marathonhealth.com",
    },
]
