"""Extended seed deals 73 - wound care, HBO therapy, vein/vascular, podiatry, diabetic foot.

This module provides a curated list of 15 private equity healthcare deal
dictionaries focused on wound care, hyperbaric oxygen therapy, vein and
vascular care, podiatry, and diabetic foot care. Each dict contains exactly
17 keys with derived fields computed consistently.
"""

EXTENDED_SEED_DEALS_73 = [
    {
        "company_name": "Advanced Wound Partners",
        "sector": "Wound Care",
        "subsector": "Chronic Wound Management",
        "year": 2019,
        "ev_mm": 285.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 22.8,
        "revenue_mm": 114.0,
        "ebitda_margin": 0.20,
        "hold_years": 4.5,
        "moic": 2.6,
        "irr": round(2.6 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.38, "medicare": 0.45, "medicaid": 0.12, "self_pay": 0.05},
        "comm_pct": 0.38,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "HyperHeal Centers",
        "sector": "Hyperbaric",
        "subsector": "Outpatient HBO Therapy",
        "year": 2021,
        "ev_mm": 165.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 15.0,
        "revenue_mm": 68.18,
        "ebitda_margin": 0.22,
        "hold_years": 3.5,
        "moic": 2.1,
        "irr": round(2.1 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.30, "medicare": 0.55, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.30,
        "region": "Midwest",
        "buyer": "Alpine Investors",
        "status": "Active",
    },
    {
        "company_name": "VeinClinics Holdings",
        "sector": "Vein Care",
        "subsector": "Varicose Vein Treatment",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 31.11,
        "revenue_mm": 129.63,
        "ebitda_margin": 0.24,
        "hold_years": 5.0,
        "moic": 2.8,
        "irr": round(2.8 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.08, "self_pay": 0.07},
        "comm_pct": 0.55,
        "region": "National",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "PodiatryFirst Group",
        "sector": "Podiatry",
        "subsector": "Multi-Specialty Podiatry MSO",
        "year": 2020,
        "ev_mm": 195.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 16.25,
        "revenue_mm": 81.25,
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 2.3,
        "irr": round(2.3 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.42, "medicare": 0.40, "medicaid": 0.12, "self_pay": 0.06},
        "comm_pct": 0.42,
        "region": "Northeast",
        "buyer": "Revelstoke",
        "status": "Active",
    },
    {
        "company_name": "Diabetic Foot Specialists",
        "sector": "Diabetic Foot",
        "subsector": "Limb Preservation Clinics",
        "year": 2022,
        "ev_mm": 110.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 10.48,
        "revenue_mm": 58.22,
        "ebitda_margin": 0.18,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": round(1.8 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.25, "medicare": 0.50, "medicaid": 0.20, "self_pay": 0.05},
        "comm_pct": 0.25,
        "region": "Southeast",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Vascular Access Partners",
        "sector": "Vascular Care",
        "subsector": "Office-Based Labs",
        "year": 2017,
        "ev_mm": 550.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 37.93,
        "revenue_mm": 151.72,
        "ebitda_margin": 0.25,
        "hold_years": 6.0,
        "moic": 3.2,
        "irr": round(3.2 ** (1 / 6.0) - 1, 4),
        "payer_mix": {"commercial": 0.35, "medicare": 0.50, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.35,
        "region": "West",
        "buyer": "Webster Equity",
        "status": "Realized",
    },
    {
        "company_name": "WoundTech Mobile Services",
        "sector": "Wound Care",
        "subsector": "Mobile Wound Care",
        "year": 2023,
        "ev_mm": 75.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 6.52,
        "revenue_mm": 37.26,
        "ebitda_margin": 0.175,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": round(1.5 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.20, "medicare": 0.60, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.20,
        "region": "Midwest",
        "buyer": "Harren",
        "status": "Active",
    },
    {
        "company_name": "OxyHeal Hyperbaric Network",
        "sector": "Hyperbaric",
        "subsector": "Hospital-Affiliated HBO",
        "year": 2016,
        "ev_mm": 95.0,
        "ev_ebitda": 10.8,
        "ebitda_mm": 8.8,
        "revenue_mm": 44.0,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 2.4,
        "irr": round(2.4 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.28, "medicare": 0.58, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.28,
        "region": "Northeast",
        "buyer": "Silversmith",
        "status": "Realized",
    },
    {
        "company_name": "USA Vein Centers",
        "sector": "Vein Care",
        "subsector": "Cosmetic & Medical Vein",
        "year": 2019,
        "ev_mm": 320.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 24.62,
        "revenue_mm": 91.19,
        "ebitda_margin": 0.27,
        "hold_years": 4.5,
        "moic": 2.5,
        "irr": round(2.5 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.60, "medicare": 0.25, "medicaid": 0.05, "self_pay": 0.10},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "Sterling Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "FootCare Alliance",
        "sector": "Podiatry",
        "subsector": "Podiatry Practice Management",
        "year": 2021,
        "ev_mm": 145.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 12.29,
        "revenue_mm": 63.01,
        "ebitda_margin": 0.195,
        "hold_years": 3.5,
        "moic": 2.0,
        "irr": round(2.0 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.44, "medicare": 0.38, "medicaid": 0.12, "self_pay": 0.06},
        "comm_pct": 0.44,
        "region": "West",
        "buyer": "Nautic",
        "status": "Active",
    },
    {
        "company_name": "LimbSave Diabetic Clinics",
        "sector": "Diabetic Foot",
        "subsector": "Amputation Prevention",
        "year": 2020,
        "ev_mm": 88.0,
        "ev_ebitda": 10.2,
        "ebitda_mm": 8.63,
        "revenue_mm": 47.94,
        "ebitda_margin": 0.18,
        "hold_years": 4.0,
        "moic": 1.9,
        "irr": round(1.9 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.22, "medicare": 0.55, "medicaid": 0.18, "self_pay": 0.05},
        "comm_pct": 0.22,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Premier Vascular Institute",
        "sector": "Vascular Care",
        "subsector": "PAD & Interventional",
        "year": 2018,
        "ev_mm": 680.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 43.87,
        "revenue_mm": 162.48,
        "ebitda_margin": 0.27,
        "hold_years": 5.5,
        "moic": 3.5,
        "irr": round(3.5 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.40, "medicare": 0.48, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.40,
        "region": "National",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Restorix Wound Healing",
        "sector": "Wound Care",
        "subsector": "Hospital Outpatient Wound Centers",
        "year": 2017,
        "ev_mm": 240.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 18.75,
        "revenue_mm": 93.75,
        "ebitda_margin": 0.20,
        "hold_years": 6.0,
        "moic": 2.9,
        "irr": round(2.9 ** (1 / 6.0) - 1, 4),
        "payer_mix": {"commercial": 0.33, "medicare": 0.52, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.33,
        "region": "Midwest",
        "buyer": "Webster Equity",
        "status": "Realized",
    },
    {
        "company_name": "Upperline Health",
        "sector": "Podiatry",
        "subsector": "Integrated Podiatry Platform",
        "year": 2022,
        "ev_mm": 380.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 27.14,
        "revenue_mm": 113.08,
        "ebitda_margin": 0.24,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": round(1.7 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.46, "medicare": 0.40, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.46,
        "region": "Southeast",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "National HBOT Solutions",
        "sector": "Hyperbaric",
        "subsector": "HBO Chamber Management",
        "year": 2024,
        "ev_mm": 52.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 5.2,
        "revenue_mm": 30.59,
        "ebitda_margin": 0.17,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": round(1.4 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.26, "medicare": 0.58, "medicaid": 0.12, "self_pay": 0.04},
        "comm_pct": 0.26,
        "region": "West",
        "buyer": "Alpine Investors",
        "status": "Active",
    },
]
