"""Extended seed 70: ENT, allergy, asthma, audiology, and sleep medicine
platforms spanning multi-site ENT practices, allergy and immunology
clinics, asthma specialty groups, audiology and hearing networks, and
sleep diagnostic and therapy providers.

This module provides a curated list of 15 synthetic healthcare private
equity deals focused on the ENT / allergy / audiology / sleep
continuum. Each deal dict contains 17 standardized fields covering
deal economics, payer mix, geography, sponsor, and realization status.
"""

EXTENDED_SEED_DEALS_70 = [
    {
        "company_name": "Cardinal ENT Partners",
        "sector": "ENT",
        "subsector": "Multi-Site Otolaryngology Group",
        "year": 2018,
        "ev_mm": 520.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 40.0,
        "revenue_mm": 166.67,
        "ebitda_margin": 0.24,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.64, "medicare": 0.26, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.64,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Atlas Allergy & Immunology",
        "sector": "Allergy & Immunology",
        "subsector": "Allergy Testing + Immunotherapy Clinics",
        "year": 2019,
        "ev_mm": 315.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 25.2,
        "revenue_mm": 126.0,
        "ebitda_margin": 0.20,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.2033,
        "payer_mix": {"commercial": 0.68, "medicare": 0.20, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.68,
        "region": "Midwest",
        "buyer": "Webster Equity",
        "status": "Realized",
    },
    {
        "company_name": "Sierra Sleep Health Network",
        "sector": "Sleep Medicine",
        "subsector": "Sleep Labs + Home Sleep Testing",
        "year": 2020,
        "ev_mm": 215.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 18.7,
        "revenue_mm": 110.0,
        "ebitda_margin": 0.17,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.55, "medicare": 0.32, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "West",
        "buyer": "Harren Equity",
        "status": "Active",
    },
    {
        "company_name": "Hearing Horizons Audiology",
        "sector": "Audiology",
        "subsector": "Retail Audiology + Hearing Aid Dispensing",
        "year": 2017,
        "ev_mm": 180.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 17.14,
        "revenue_mm": 95.22,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 2.5,
        "irr": 0.165,
        "payer_mix": {"commercial": 0.42, "medicare": 0.30, "medicaid": 0.05, "self_pay": 0.23},
        "comm_pct": 0.42,
        "region": "National",
        "buyer": "Alpine Investors",
        "status": "Realized",
    },
    {
        "company_name": "Breathe Well Asthma Centers",
        "sector": "Asthma",
        "subsector": "Pediatric Asthma Specialty Clinics",
        "year": 2021,
        "ev_mm": 145.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 10.74,
        "revenue_mm": 53.7,
        "ebitda_margin": 0.20,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.50, "medicare": 0.10, "medicaid": 0.35, "self_pay": 0.05},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "Revelstoke Capital",
        "status": "Active",
    },
    {
        "company_name": "Pinnacle ENT & Sinus Institute",
        "sector": "ENT",
        "subsector": "ENT + Ambulatory Surgery Centers",
        "year": 2019,
        "ev_mm": 720.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 49.66,
        "revenue_mm": 188.96,
        "ebitda_margin": 0.2628,
        "hold_years": 5.5,
        "moic": 3.1,
        "irr": 0.2284,
        "payer_mix": {"commercial": 0.66, "medicare": 0.24, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.66,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Partially Realized",
    },
    {
        "company_name": "Clearwater Allergy Associates",
        "sector": "Allergy",
        "subsector": "Food & Environmental Allergy Clinics",
        "year": 2022,
        "ev_mm": 95.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 8.64,
        "revenue_mm": 54.0,
        "ebitda_margin": 0.16,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.72, "medicare": 0.14, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.72,
        "region": "West",
        "buyer": "Silversmith Capital",
        "status": "Active",
    },
    {
        "company_name": "Rockwell Sleep Diagnostics",
        "sector": "Sleep Medicine",
        "subsector": "Sleep Medicine + CPAP DME",
        "year": 2018,
        "ev_mm": 385.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 32.08,
        "revenue_mm": 183.31,
        "ebitda_margin": 0.175,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": 0.1914,
        "payer_mix": {"commercial": 0.52, "medicare": 0.34, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.52,
        "region": "Midwest",
        "buyer": "Varsity Healthcare Partners",
        "status": "Realized",
    },
    {
        "company_name": "Beacon Hearing Care Group",
        "sector": "Audiology",
        "subsector": "Multi-Site Audiology Practice Network",
        "year": 2020,
        "ev_mm": 265.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 22.46,
        "revenue_mm": 112.3,
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 2.2,
        "irr": 0.2179,
        "payer_mix": {"commercial": 0.45, "medicare": 0.32, "medicaid": 0.05, "self_pay": 0.18},
        "comm_pct": 0.45,
        "region": "Northeast",
        "buyer": "Nautic Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "Summit Pediatric ENT",
        "sector": "ENT",
        "subsector": "Pediatric Otolaryngology Group",
        "year": 2021,
        "ev_mm": 185.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 14.23,
        "revenue_mm": 59.29,
        "ebitda_margin": 0.24,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": 0.2164,
        "payer_mix": {"commercial": 0.58, "medicare": 0.04, "medicaid": 0.34, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Evergreen Asthma & Pulmonary",
        "sector": "Asthma",
        "subsector": "Adult Asthma + Pulmonary Function",
        "year": 2017,
        "ev_mm": 240.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 19.2,
        "revenue_mm": 87.27,
        "ebitda_margin": 0.22,
        "hold_years": 6.0,
        "moic": 2.8,
        "irr": 0.1872,
        "payer_mix": {"commercial": 0.56, "medicare": 0.28, "medicaid": 0.11, "self_pay": 0.05},
        "comm_pct": 0.56,
        "region": "West",
        "buyer": "Frazier Healthcare Partners",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Sleep & Neurology",
        "sector": "Sleep Medicine",
        "subsector": "Sleep Medicine + Neurology Integration",
        "year": 2022,
        "ev_mm": 425.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 30.36,
        "revenue_mm": 138.0,
        "ebitda_margin": 0.22,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "Revelstoke Capital",
        "status": "Active",
    },
    {
        "company_name": "Cascade Allergy & Asthma Partners",
        "sector": "Allergy & Immunology",
        "subsector": "Integrated Allergy + Asthma Clinics",
        "year": 2016,
        "ev_mm": 410.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 31.54,
        "revenue_mm": 150.19,
        "ebitda_margin": 0.21,
        "hold_years": 6.5,
        "moic": 3.4,
        "irr": 0.2072,
        "payer_mix": {"commercial": 0.63, "medicare": 0.22, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.63,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Acoustic Hearing Solutions",
        "sector": "Audiology",
        "subsector": "Hearing Aid Manufacturer-Backed Retail",
        "year": 2023,
        "ev_mm": 620.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 40.0,
        "revenue_mm": 200.0,
        "ebitda_margin": 0.20,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.40, "medicare": 0.30, "medicaid": 0.04, "self_pay": 0.26},
        "comm_pct": 0.40,
        "region": "National",
        "buyer": "Alpine Investors",
        "status": "Active",
    },
    {
        "company_name": "Liberty ENT & Facial Plastics",
        "sector": "ENT",
        "subsector": "ENT + Facial Plastics + Allergy",
        "year": 2024,
        "ev_mm": 835.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 50.61,
        "revenue_mm": 210.88,
        "ebitda_margin": 0.24,
        "hold_years": 4.5,
        "moic": 3.8,
        "irr": 0.3454,
        "payer_mix": {"commercial": 0.70, "medicare": 0.20, "medicaid": 0.05, "self_pay": 0.05},
        "comm_pct": 0.70,
        "region": "Southeast",
        "buyer": "Webster Equity",
        "status": "Active",
    },
]
