"""Extended seed batch 14 — deals 296-315.

Covers: oncology platform roll-ups, anesthesia management, urgent care
secondary buyouts, health system joint ventures, digital health IPOs,
pharmacy networks, and cross-border healthcare services.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_14: list[dict] = [
    # 296 — Oncology MSO
    {
        "source_id": "seed_296",
        "deal_name": "American Oncology Network / GTCR",
        "source": "seed",
        "buyer": "GTCR",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2021,
        "ev_mm": 850.0,
        "ebitda_mm": 72.0,
        "ev_ebitda": 11.8,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.08, "commercial": 0.30, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Community oncology MSO; 140+ oncologists; CMMI OCM/EOM APM; biosimilar opportunity",
    },
    # 297 — Anesthesia management
    {
        "source_id": "seed_297",
        "deal_name": "Envision Anesthesia / USAP",
        "source": "seed",
        "buyer": "US Anesthesia Partners",
        "seller": "Envision Healthcare (post-restructuring)",
        "deal_type": "carve_out",
        "year": 2023,
        "ev_mm": 1200.0,
        "ebitda_mm": 95.0,
        "ev_ebitda": 12.6,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.14, "commercial": 0.44, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Anesthesia group carve-out from Envision restructuring; NSA No Surprises Act exposure",
    },
    # 298 — Urgent care chain secondary
    {
        "source_id": "seed_298",
        "deal_name": "NextCare Urgent Care / Wellspring Capital",
        "source": "seed",
        "buyer": "Wellspring Capital Management",
        "seller": "General Atlantic",
        "deal_type": "secondary_buyout",
        "year": 2019,
        "ev_mm": 550.0,
        "ebitda_mm": 48.0,
        "ev_ebitda": 11.5,
        "hold_years": 5.0,
        "realized_moic": 3.0,
        "realized_irr": 0.25,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.18, "commercial": 0.64, "self_pay": 0.08},
        "hospital_beds": None,
        "region": "Southwest",
        "state": "AZ",
        "notes": "Southwest urgent care chain; 100+ centers; COVID testing volume 2020-21 tailwind",
    },
    # 299 — Health system JV / accountable care
    {
        "source_id": "seed_299",
        "deal_name": "Vanderbilt / Lifepoint Health Strategic Alliance",
        "source": "seed",
        "buyer": "LifePoint Health (RCCH)",
        "seller": "Vanderbilt University Medical Center",
        "deal_type": "joint_venture",
        "year": 2018,
        "ev_mm": 2200.0,
        "ebitda_mm": 160.0,
        "ev_ebitda": 13.8,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.26, "commercial": 0.27, "self_pay": 0.02},
        "hospital_beds": 3400,
        "region": "Southeast",
        "state": "TN",
        "notes": "Academic-community hospital alliance; rural hospital quality improvement thesis",
    },
    # 300 — Digital health IPO
    {
        "source_id": "seed_300",
        "deal_name": "Accolade Health / PE Pre-IPO Round",
        "source": "seed",
        "buyer": "Various PE (pre-IPO)",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2019,
        "ev_mm": 600.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 2.0,
        "realized_moic": 3.8,
        "realized_irr": 0.87,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": "PA",
        "notes": "Health navigation + personalized health advocacy; employer-sponsored; IPO 2020 at $3.5B",
    },
    # 301 — Pharmacy network / PBM technology
    {
        "source_id": "seed_301",
        "deal_name": "RxBenefits / Welsh Carson",
        "source": "seed",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2020,
        "ev_mm": 650.0,
        "ebitda_mm": 55.0,
        "ev_ebitda": 11.8,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "Southeast",
        "state": "AL",
        "notes": "Mid-market PBM optimization platform; employer direct pharmacy benefits; rebate aggregation",
    },
    # 302 — Clinical research organization (CRO)
    {
        "source_id": "seed_302",
        "deal_name": "PPD (Pharmaceutical Product Development) / Thermo Fisher",
        "source": "seed",
        "buyer": "Thermo Fisher Scientific",
        "seller": "Hellman & Friedman + CPPIB",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 17400.0,
        "ebitda_mm": 1350.0,
        "ev_ebitda": 12.9,
        "hold_years": 7.0,
        "realized_moic": 5.5,
        "realized_irr": 0.28,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": "NC",
        "notes": "Global CRO; H&F took private at $3.9B in 2011; strategic exit to Thermo Fisher at $17.4B",
    },
    # 303 — Home infusion specialty
    {
        "source_id": "seed_303",
        "deal_name": "IVX Health / Pharmos Capital",
        "source": "seed",
        "buyer": "Pharmos Capital",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2021,
        "ev_mm": 200.0,
        "ebitda_mm": 18.0,
        "ev_ebitda": 11.1,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.10, "commercial": 0.72, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TN",
        "notes": "Ambulatory infusion centers; biologics/immunology; commercial payer mix; office vs hospital rate arb",
    },
    # 304 — Behavioral health inpatient (acute)
    {
        "source_id": "seed_304",
        "deal_name": "Pyramid Healthcare / Warburg Pincus",
        "source": "seed",
        "buyer": "Warburg Pincus",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2018,
        "ev_mm": 400.0,
        "ebitda_mm": 38.0,
        "ev_ebitda": 10.5,
        "hold_years": 5.0,
        "realized_moic": 3.1,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.45, "commercial": 0.42, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "PA",
        "notes": "BH inpatient + PHP/IOP + SUD residential; PA-concentrated; parity law compliance track record",
    },
    # 305 — Telehealth chronic disease management
    {
        "source_id": "seed_305",
        "deal_name": "Livongo Health / Teladoc Merger",
        "source": "seed",
        "buyer": "Teladoc Health",
        "seller": "Public (Livongo shareholders)",
        "deal_type": "strategic_acquisition",
        "year": 2020,
        "ev_mm": 18500.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 2.0,
        "realized_moic": 0.3,
        "realized_irr": -0.45,
        "payer_mix": {"medicare": 0.08, "medicaid": 0.05, "commercial": 0.80, "self_pay": 0.07},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Diabetes/hypertension AI coaching platform; $18.5B merger at pandemic peak; rapid value destruction",
    },
    # 306 — Physical medicine / PM&R
    {
        "source_id": "seed_306",
        "deal_name": "Select Medical / Welsh Carson",
        "source": "seed",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Public / Founders",
        "deal_type": "take_private",
        "year": 2005,
        "ev_mm": 2400.0,
        "ebitda_mm": 200.0,
        "ev_ebitda": 12.0,
        "hold_years": 10.0,
        "realized_moic": 4.2,
        "realized_irr": 0.17,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.25, "commercial": 0.35, "self_pay": 0.02},
        "hospital_beds": 1800,
        "region": "National",
        "state": "PA",
        "notes": "LTACH + inpatient rehab + outpatient therapy; re-IPO 2015 (SEM); 10-year hold; IRR modest",
    },
    # 307 — Accountable care organization
    {
        "source_id": "seed_307",
        "deal_name": "Optum / DaVita Medical Group",
        "source": "seed",
        "buyer": "UnitedHealth / Optum",
        "seller": "DaVita Inc.",
        "deal_type": "strategic_acquisition",
        "year": 2019,
        "ev_mm": 4900.0,
        "ebitda_mm": 380.0,
        "ev_ebitda": 12.9,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.10, "commercial": 0.33, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "West",
        "state": "CO",
        "notes": "California + Colorado physician group (formerly HealthCare Partners); 1.7M patients; full-risk ACO",
    },
    # 308 — Diagnostic imaging roll-up
    {
        "source_id": "seed_308",
        "deal_name": "RadNet / Imaging Center Acquisitions",
        "source": "seed",
        "buyer": "RadNet Inc. (Nasdaq: RDNT)",
        "seller": "Independent radiologists",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 1800.0,
        "ebitda_mm": 165.0,
        "ev_ebitda": 10.9,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.12, "commercial": 0.43, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Largest independent outpatient radiology operator; AI-assisted mammography; site-of-care shift thesis",
    },
    # 309 — Health insurance brokerage tech
    {
        "source_id": "seed_309",
        "deal_name": "GoHealth / Centerbridge Partners",
        "source": "seed",
        "buyer": "Centerbridge Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2019,
        "ev_mm": 2000.0,
        "ebitda_mm": 200.0,
        "ev_ebitda": 10.0,
        "hold_years": 2.0,
        "realized_moic": 1.3,
        "realized_irr": 0.14,
        "payer_mix": {"medicare": 1.00, "medicaid": 0.00, "commercial": 0.00, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "National",
        "state": "IL",
        "notes": "Medicare Advantage enrollment brokerage; SPAC IPO 2020; CMS marketing rule tightening risk",
    },
    # 310 — Hospital network rural turnaround
    {
        "source_id": "seed_310",
        "deal_name": "RegionalCare Hospital Partners / LifePoint Merger",
        "source": "seed",
        "buyer": "LifePoint Health (merged)",
        "seller": "RCCH HealthCare Partners / Apollo",
        "deal_type": "merger",
        "year": 2018,
        "ev_mm": 5600.0,
        "ebitda_mm": 450.0,
        "ev_ebitda": 12.4,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.28, "commercial": 0.28, "self_pay": 0.02},
        "hospital_beds": 9000,
        "region": "National",
        "state": "TN",
        "notes": "Apollo-backed RCCH + LifePoint merger; 89 hospitals; Brentwood HQ; rural hospital turnaround thesis",
    },
    # 311 — Cardiac monitoring / remote patient monitoring
    {
        "source_id": "seed_311",
        "deal_name": "iRhythm Technologies / Pre-IPO Round",
        "source": "seed",
        "buyer": "Various PE (Series E)",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2019,
        "ev_mm": 600.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 2.0,
        "realized_moic": 5.0,
        "realized_irr": 1.24,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.08, "commercial": 0.50, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Zio patch ambulatory cardiac monitor; FDA cleared; CMS NCD coverage drove 2020-21 revenue surge",
    },
    # 312 — Maternal / prenatal care
    {
        "source_id": "seed_312",
        "deal_name": "Pomelo Care / Oak HC/FT",
        "source": "seed",
        "buyer": "Oak HC/FT",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2022,
        "ev_mm": 200.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.00, "medicaid": 0.52, "commercial": 0.44, "self_pay": 0.04},
        "hospital_beds": None,
        "region": "National",
        "state": "NY",
        "notes": "High-risk pregnancy virtual care; Medicaid maternal mortality crisis tailwind; payer contracts",
    },
    # 313 — Ambulance / fire / emergency services
    {
        "source_id": "seed_313",
        "deal_name": "Falck / US EMS Expansion",
        "source": "seed",
        "buyer": "Falck Group (Danish)",
        "seller": "Various US operators",
        "deal_type": "strategic_acquisition",
        "year": 2020,
        "ev_mm": 800.0,
        "ebitda_mm": 65.0,
        "ev_ebitda": 12.3,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.20, "commercial": 0.30, "self_pay": 0.08},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "International EMS operator expanding US footprint; ground + air; reimbursement reform risk",
    },
    # 314 — Medical staffing / hospitalist
    {
        "source_id": "seed_314",
        "deal_name": "IPC Healthcare / TeamHealth Acquisition",
        "source": "seed",
        "buyer": "TeamHealth / Blackstone",
        "seller": "Public (Nasdaq: IPCM)",
        "deal_type": "take_private",
        "year": 2015,
        "ev_mm": 1600.0,
        "ebitda_mm": 130.0,
        "ev_ebitda": 12.3,
        "hold_years": 5.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.15, "commercial": 0.40, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Hospitalist + post-acute physician staffing; integrated into TeamHealth post-acquisition",
    },
    # 315 — Genetics / biobank / precision health
    {
        "source_id": "seed_315",
        "deal_name": "Color Genomics / PE Series D",
        "source": "seed",
        "buyer": "Various PE (Series D)",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 470.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.15, "commercial": 0.55, "self_pay": 0.10},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Population genomics + employer health programs; BRCA/HBOC testing; 23andMe comparison risk",
    },
]
