"""Extended seed batch 64: nephrology, dialysis, and kidney care PE deals.

This module contains 15 synthetic healthcare private equity deal records
focused on the nephrology and renal care vertical, including dialysis
centers, CKD management platforms, home dialysis providers, and
integrated kidney care services. Payer mixes are skewed Medicare-heavy
consistent with ESRD reimbursement dynamics.
"""

EXTENDED_SEED_DEALS_64 = [
    {
        "company_name": "Cascade Renal Partners",
        "sector": "Dialysis",
        "subsector": "In-Center Hemodialysis",
        "year": 2018,
        "ev_mm": 485.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 42.17,
        "revenue_mm": 210.85,
        "ebitda_margin": 0.20,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": 0.1914,
        "payer_mix": {"commercial": 0.18, "medicare": 0.68, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.18,
        "region": "Midwest",
        "buyer": "Nautic Partners",
        "status": "Realized",
    },
    {
        "company_name": "Sierra Kidney Health",
        "sector": "Kidney Care",
        "subsector": "Integrated Value-Based Kidney Care",
        "year": 2021,
        "ev_mm": 820.0,
        "ev_ebitda": 15.2,
        "ebitda_mm": 53.95,
        "revenue_mm": 245.23,
        "ebitda_margin": 0.22,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.22, "medicare": 0.60, "medicaid": 0.14, "self_pay": 0.04},
        "comm_pct": 0.22,
        "region": "West",
        "buyer": "General Atlantic",
        "status": "Active",
    },
    {
        "company_name": "Meridian Home Dialysis",
        "sector": "Home Dialysis",
        "subsector": "Peritoneal Dialysis Services",
        "year": 2020,
        "ev_mm": 310.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 22.46,
        "revenue_mm": 96.81,
        "ebitda_margin": 0.232,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.20, "medicare": 0.65, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.20,
        "region": "Northeast",
        "buyer": "Cressey & Company",
        "status": "Active",
    },
    {
        "company_name": "Keystone Nephrology Associates",
        "sector": "Nephrology",
        "subsector": "Physician Practice Management",
        "year": 2019,
        "ev_mm": 165.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 15.71,
        "revenue_mm": 65.46,
        "ebitda_margin": 0.24,
        "hold_years": 6.0,
        "moic": 2.8,
        "irr": 0.1872,
        "payer_mix": {"commercial": 0.28, "medicare": 0.58, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.28,
        "region": "Northeast",
        "buyer": "Shore Capital Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "Atlantic Dialysis Network",
        "sector": "Dialysis",
        "subsector": "Multi-State Dialysis Chain",
        "year": 2017,
        "ev_mm": 1050.0,
        "ev_ebitda": 12.6,
        "ebitda_mm": 83.33,
        "revenue_mm": 462.94,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 2.9,
        "irr": 0.1942,
        "payer_mix": {"commercial": 0.16, "medicare": 0.70, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.16,
        "region": "Southeast",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Prairie CKD Solutions",
        "sector": "CKD Management",
        "subsector": "Population Health / Risk-Based CKD",
        "year": 2022,
        "ev_mm": 240.0,
        "ev_ebitda": 16.4,
        "ebitda_mm": 14.63,
        "revenue_mm": 81.28,
        "ebitda_margin": 0.18,
        "hold_years": 4.0,
        "moic": 1.9,
        "irr": 0.1741,
        "payer_mix": {"commercial": 0.24, "medicare": 0.59, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.24,
        "region": "Midwest",
        "buyer": "Bain Capital",
        "status": "Active",
    },
    {
        "company_name": "Gulf Coast Renal Services",
        "sector": "Renal Services",
        "subsector": "Vascular Access & Interventional",
        "year": 2019,
        "ev_mm": 395.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 33.47,
        "revenue_mm": 133.88,
        "ebitda_margin": 0.25,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.21, "medicare": 0.64, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.21,
        "region": "Southeast",
        "buyer": "Audax Group",
        "status": "Realized",
    },
    {
        "company_name": "Northstar Kidney Clinics",
        "sector": "Nephrology",
        "subsector": "Nephrology MSO",
        "year": 2023,
        "ev_mm": 135.0,
        "ev_ebitda": 9.8,
        "ebitda_mm": 13.78,
        "revenue_mm": 61.24,
        "ebitda_margin": 0.225,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.26, "medicare": 0.57, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.26,
        "region": "Midwest",
        "buyer": "Aisling Capital",
        "status": "Active",
    },
    {
        "company_name": "Pacific Home Hemodialysis",
        "sector": "Home Dialysis",
        "subsector": "Home Hemodialysis Platform",
        "year": 2021,
        "ev_mm": 560.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 38.62,
        "revenue_mm": 154.48,
        "ebitda_margin": 0.25,
        "hold_years": 4.0,
        "moic": 2.2,
        "irr": 0.2179,
        "payer_mix": {"commercial": 0.23, "medicare": 0.62, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.23,
        "region": "West",
        "buyer": "Bridgepoint",
        "status": "Active",
    },
    {
        "company_name": "Summit Dialysis Holdings",
        "sector": "Dialysis",
        "subsector": "Rural Dialysis Centers",
        "year": 2016,
        "ev_mm": 220.0,
        "ev_ebitda": 10.2,
        "ebitda_mm": 21.57,
        "revenue_mm": 123.26,
        "ebitda_margin": 0.175,
        "hold_years": 7.0,
        "moic": 3.4,
        "irr": 0.1910,
        "payer_mix": {"commercial": 0.15, "medicare": 0.71, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.15,
        "region": "Midwest",
        "buyer": "HBM Healthcare Investments",
        "status": "Realized",
    },
    {
        "company_name": "Horizon Renal Physicians",
        "sector": "Nephrology",
        "subsector": "Physician Practice Rollup",
        "year": 2020,
        "ev_mm": 275.0,
        "ev_ebitda": 11.2,
        "ebitda_mm": 24.55,
        "revenue_mm": 105.14,
        "ebitda_margin": 0.2335,
        "hold_years": 5.0,
        "moic": 2.3,
        "irr": 0.1813,
        "payer_mix": {"commercial": 0.27, "medicare": 0.58, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.27,
        "region": "National",
        "buyer": "Cressey & Company",
        "status": "Active",
    },
    {
        "company_name": "Evergreen CKD Advantage",
        "sector": "CKD Management",
        "subsector": "Medicare Advantage CKD Risk",
        "year": 2022,
        "ev_mm": 640.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 36.57,
        "revenue_mm": 203.17,
        "ebitda_margin": 0.18,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.19, "medicare": 0.66, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.19,
        "region": "National",
        "buyer": "General Atlantic",
        "status": "Active",
    },
    {
        "company_name": "Tidewater Renal Group",
        "sector": "Renal Services",
        "subsector": "Integrated Nephrology & Dialysis",
        "year": 2018,
        "ev_mm": 730.0,
        "ev_ebitda": 12.1,
        "ebitda_mm": 60.33,
        "revenue_mm": 251.38,
        "ebitda_margin": 0.24,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": 0.2075,
        "payer_mix": {"commercial": 0.22, "medicare": 0.63, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.22,
        "region": "Southeast",
        "buyer": "KKR",
        "status": "Partially Realized",
    },
    {
        "company_name": "Cardinal Kidney Care Partners",
        "sector": "Kidney Care",
        "subsector": "ESRD Seamless Care Organization",
        "year": 2023,
        "ev_mm": 1180.0,
        "ev_ebitda": 17.8,
        "ebitda_mm": 66.29,
        "revenue_mm": 414.31,
        "ebitda_margin": 0.16,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": 0.1829,
        "payer_mix": {"commercial": 0.17, "medicare": 0.68, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.17,
        "region": "National",
        "buyer": "Bain Capital",
        "status": "Active",
    },
    {
        "company_name": "Bluegrass Dialysis Partners",
        "sector": "Dialysis",
        "subsector": "Regional Dialysis JV Operator",
        "year": 2024,
        "ev_mm": 85.0,
        "ev_ebitda": 9.4,
        "ebitda_mm": 9.04,
        "revenue_mm": 47.58,
        "ebitda_margin": 0.19,
        "hold_years": 3.0,
        "moic": 1.55,
        "irr": 0.1573,
        "payer_mix": {"commercial": 0.17, "medicare": 0.67, "medicaid": 0.13, "self_pay": 0.03},
        "comm_pct": 0.17,
        "region": "Southeast",
        "buyer": "Shore Capital Partners",
        "status": "Active",
    },
]
