"""Extended seed batch 15 — deals 316-335."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_15: List[Dict[str, Any]] = [
    {
        "source_id": "seed_316",
        "deal_name": "Kindred at Home Hospice & Home Health Carve-Out",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Kindred Healthcare",
        "year": 2018,
        "deal_type": "carve-out",
        "sector": "home health / hospice",
        "ev_mm": 1420.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 120.3,
        "revenue_mm": 1850.0,
        "realized_moic": 3.4,
        "realized_irr": 0.28,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.10, "commercial": 0.14, "self_pay": 0.04},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Carve-out of Kindred's home health and hospice division; merged with Humana home health assets post-acquisition.",
    },
    {
        "source_id": "seed_317",
        "deal_name": "Behavioral Health Group (BHG) LBO",
        "buyer": "Frazier Healthcare Partners",
        "seller": None,
        "year": 2015,
        "deal_type": "lbo",
        "sector": "behavioral health",
        "ev_mm": 210.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 105.0,
        "realized_moic": 4.6,
        "realized_irr": 0.35,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.55, "commercial": 0.30, "self_pay": 0.10},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Opioid treatment / medication-assisted treatment network; strong unit economics driven by Medicaid reimbursement expansion.",
    },
    {
        "source_id": "seed_318",
        "deal_name": "Smile Brands Dental Group Recapitalization",
        "buyer": "Gryphon Investors",
        "seller": "Smile Brands (prior sponsors)",
        "year": 2019,
        "deal_type": "secondary",
        "sector": "dental",
        "ev_mm": 680.0,
        "ev_ebitda": 12.4,
        "ebitda_mm": 54.8,
        "revenue_mm": 620.0,
        "realized_moic": 1.2,
        "realized_irr": 0.06,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.18, "commercial": 0.55, "self_pay": 0.25},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Secondary buyout of DSO platform; COVID disruption and integration challenges compressed returns below expectations.",
    },
    {
        "source_id": "seed_319",
        "deal_name": "US Renal Care Dialysis LBO",
        "buyer": "Summit Partners",
        "seller": None,
        "year": 2011,
        "deal_type": "lbo",
        "sector": "dialysis",
        "ev_mm": 540.0,
        "ev_ebitda": 9.8,
        "ebitda_mm": 55.1,
        "revenue_mm": 480.0,
        "realized_moic": 3.1,
        "realized_irr": 0.24,
        "hold_years": 5.5,
        "payer_mix": {"medicare": 0.68, "medicaid": 0.12, "commercial": 0.18, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Independent dialysis clinic operator; rolled up regional chains across Sun Belt and Midwest; exited via secondary to CDPQ consortium.",
    },
    {
        "source_id": "seed_320",
        "deal_name": "RadNet Radiology Take-Private",
        "buyer": "Leonard Green & Partners",
        "seller": "Public shareholders (RDNT)",
        "year": 2013,
        "deal_type": "take-private",
        "sector": "radiology",
        "ev_mm": 760.0,
        "ev_ebitda": 10.2,
        "ebitda_mm": 74.5,
        "revenue_mm": 720.0,
        "realized_moic": 0.7,
        "realized_irr": -0.08,
        "hold_years": 3.0,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.08, "commercial": 0.50, "self_pay": 0.04},
        "geography": "California",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Take-private of outpatient imaging chain; reimbursement cuts and leverage made exit difficult; partial loss on equity.",
    },
    {
        "source_id": "seed_321",
        "deal_name": "Acadia Healthcare Behavioral Health IPO",
        "buyer": "Waud Capital Partners",
        "seller": None,
        "year": 2011,
        "deal_type": "ipo",
        "sector": "behavioral health",
        "ev_mm": 950.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 67.9,
        "revenue_mm": 380.0,
        "realized_moic": 8.2,
        "realized_irr": 0.58,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.12, "medicaid": 0.40, "commercial": 0.42, "self_pay": 0.06},
        "geography": "National",
        "hospital_beds": 2200,
        "source": "seed",
        "notes": "IPO of inpatient psychiatric hospital chain assembled through aggressive M&A; Waud distributed shares post-lockup at significant premium.",
    },
    {
        "source_id": "seed_322",
        "deal_name": "Envision Healthcare Physician Staffing Merger",
        "buyer": "KKR",
        "seller": "AmSurg / Envision public shareholders",
        "year": 2018,
        "deal_type": "take-private",
        "sector": "physician groups",
        "ev_mm": 9900.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 733.3,
        "revenue_mm": 7800.0,
        "realized_moic": 0.1,
        "realized_irr": -0.45,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.15, "commercial": 0.50, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Landmark disaster; surprise billing legislation (No Surprises Act) gutted ED staffing economics; filed Chapter 11 in 2023.",
    },
    {
        "source_id": "seed_323",
        "deal_name": "Greenway Health RCM / EHR Platform LBO",
        "buyer": "Vista Equity Partners",
        "seller": "Greenway Medical Technologies",
        "year": 2015,
        "deal_type": "lbo",
        "sector": "RCM / health IT",
        "ev_mm": 635.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": 40.2,
        "revenue_mm": 230.0,
        "realized_moic": 2.3,
        "realized_irr": 0.18,
        "hold_years": 5.5,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Ambulatory EHR and RCM SaaS platform serving independent physician groups; DOJ False Claims Act settlement modestly impacted exit multiple.",
    },
    {
        "source_id": "seed_324",
        "deal_name": "National Veterinary Associates Add-On to QVCP",
        "buyer": "KKR",
        "seller": "None",
        "year": 2019,
        "deal_type": "add-on",
        "sector": "veterinary (animal health)",
        "ev_mm": 2200.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": 118.9,
        "revenue_mm": 980.0,
        "realized_moic": 3.8,
        "realized_irr": 0.31,
        "hold_years": 4.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Add-on platform expansion of KKR's veterinary thesis; bolt-on to existing portfolio; COVID pet adoption tailwind accelerated growth.",
    },
    {
        "source_id": "seed_325",
        "deal_name": "Surgery Partners ASC Rollup LBO",
        "buyer": "H.I.G. Capital",
        "seller": "NovaBay / founder",
        "year": 2015,
        "deal_type": "lbo",
        "sector": "ASCs",
        "ev_mm": 820.0,
        "ev_ebitda": 11.2,
        "ebitda_mm": 73.2,
        "revenue_mm": 610.0,
        "realized_moic": 4.1,
        "realized_irr": 0.36,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.05, "commercial": 0.56, "self_pay": 0.04},
        "geography": "Southeast / Midwest",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Multi-specialty ASC platform; IPO'd on NASDAQ in 2015; H.I.G. achieved strong exit via public market distribution.",
    },
    {
        "source_id": "seed_326",
        "deal_name": "Genoptix Oncology Diagnostics Carve-Out",
        "buyer": "New Mountain Capital",
        "seller": "Novartis",
        "year": 2015,
        "deal_type": "carve-out",
        "sector": "lab diagnostics / oncology",
        "ev_mm": 470.0,
        "ev_ebitda": 9.4,
        "ebitda_mm": 50.0,
        "revenue_mm": 310.0,
        "realized_moic": 2.0,
        "realized_irr": 0.15,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.08, "commercial": 0.44, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hematology/oncology specialized lab carved from Novartis; faced Medicare reimbursement headwinds on molecular diagnostics.",
    },
    {
        "source_id": "seed_327",
        "deal_name": "Cornerstone OnDemand / Healtheon Telehealth Growth Equity",
        "buyer": "TA Associates",
        "seller": None,
        "year": 2020,
        "deal_type": "growth_equity",
        "sector": "telehealth",
        "ev_mm": 320.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 85.0,
        "realized_moic": 1.8,
        "realized_irr": 0.22,
        "hold_years": 3.0,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.10, "commercial": 0.60, "self_pay": 0.15},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Telehealth SaaS platform serving employers and payers; COVID tailwind boosted growth but market normalization compressed exit multiple.",
    },
    {
        "source_id": "seed_328",
        "deal_name": "BrightSpring Health Services Home & Community Care LBO",
        "buyer": "KKR",
        "seller": "RehabCare / Kindred",
        "year": 2019,
        "deal_type": "lbo",
        "sector": "home health / community-based care",
        "ev_mm": 1320.0,
        "ev_ebitda": 10.8,
        "ebitda_mm": 122.2,
        "revenue_mm": 3100.0,
        "realized_moic": 2.6,
        "realized_irr": 0.21,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.18, "medicaid": 0.58, "commercial": 0.18, "self_pay": 0.06},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Large home and community-based services platform for complex populations; IPO'd in January 2024 on NASDAQ (BTSG).",
    },
    {
        "source_id": "seed_329",
        "deal_name": "Integrated Oncology Network Add-On",
        "buyer": "Ridgemont Equity Partners",
        "seller": None,
        "year": 2017,
        "deal_type": "add-on",
        "sector": "oncology",
        "ev_mm": 155.0,
        "ev_ebitda": 8.6,
        "ebitda_mm": 18.0,
        "revenue_mm": 290.0,
        "realized_moic": 3.3,
        "realized_irr": 0.27,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.52, "medicaid": 0.08, "commercial": 0.36, "self_pay": 0.04},
        "geography": "Mid-Atlantic",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Community oncology practice management organization; added radiation oncology and infusion capabilities as add-ons.",
    },
    {
        "source_id": "seed_330",
        "deal_name": "Comfort Systems / Rotech Healthcare DME LBO",
        "buyer": "Apax Partners",
        "seller": "Lincare Holdings",
        "year": 2014,
        "deal_type": "lbo",
        "sector": "DME / home respiratory",
        "ev_mm": 385.0,
        "ev_ebitda": 7.8,
        "ebitda_mm": 49.4,
        "revenue_mm": 340.0,
        "realized_moic": 0.8,
        "realized_irr": -0.05,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.62, "medicaid": 0.14, "commercial": 0.20, "self_pay": 0.04},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Home respiratory and DME platform; competitive bidding rounds slashed Medicare reimbursement and impaired equity value.",
    },
    {
        "source_id": "seed_331",
        "deal_name": "Aspirion Health RCM Distressed Debt-to-Equity",
        "buyer": "Clearlake Capital Group",
        "seller": "Senior lenders (distressed)",
        "year": 2021,
        "deal_type": "distressed",
        "sector": "RCM / health IT",
        "ev_mm": 190.0,
        "ev_ebitda": 8.9,
        "ebitda_mm": 21.3,
        "revenue_mm": 130.0,
        "realized_moic": 4.4,
        "realized_irr": 0.42,
        "hold_years": 3.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Distressed takeover of complex claims recovery RCM platform; operational improvements and strategic sale to Waystar drove outsized return.",
    },
    {
        "source_id": "seed_332",
        "deal_name": "TeamHealth Physician Staffing Take-Private",
        "buyer": "Blackstone",
        "seller": "Public shareholders (TMH)",
        "year": 2016,
        "deal_type": "take-private",
        "sector": "physician groups",
        "ev_mm": 6100.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 381.3,
        "revenue_mm": 2800.0,
        "realized_moic": 1.1,
        "realized_irr": 0.02,
        "hold_years": 8.0,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.14, "commercial": 0.52, "self_pay": 0.06},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Emergency medicine and hospitalist staffing; No Surprises Act severely impacted out-of-network revenue; Blackstone trapped in investment.",
    },
    {
        "source_id": "seed_333",
        "deal_name": "CarepathRx Specialty Pharmacy Joint Venture",
        "buyer": "Warburg Pincus",
        "seller": None,
        "year": 2020,
        "deal_type": "joint_venture",
        "sector": "pharmacy / specialty pharmacy",
        "ev_mm": 275.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 20.8,
        "revenue_mm": 410.0,
        "realized_moic": 3.0,
        "realized_irr": 0.26,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.20, "commercial": 0.48, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hospital-based specialty pharmacy JV with health systems; integrated closed-door pharmacy model with health system partners.",
    },
    {
        "source_id": "seed_334",
        "deal_name": "Lifepoint Health LTACH / Rehabilitation Secondary",
        "buyer": "Apollo Global Management",
        "seller": "RCCH HealthCare Partners / RegionalCare",
        "year": 2018,
        "deal_type": "secondary",
        "sector": "LTACH / post-acute",
        "ev_mm": 5600.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 658.8,
        "revenue_mm": 6200.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.18, "commercial": 0.24, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": 5800,
        "source": "seed",
        "notes": "Apollo took Lifepoint private; combined with RCCH community hospitals; exit via re-IPO; COVID disruption weighed on near-term margins.",
    },
    {
        "source_id": "seed_335",
        "deal_name": "Women's Care Enterprises OB/GYN Rollup",
        "buyer": "Shore Capital Partners",
        "seller": None,
        "year": 2019,
        "deal_type": "lbo",
        "sector": "women's health",
        "ev_mm": 95.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 10.0,
        "revenue_mm": 72.0,
        "realized_moic": 5.1,
        "realized_irr": 0.43,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.25, "commercial": 0.60, "self_pay": 0.05},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "OB/GYN practice management platform; rapid de novo and acquisition growth across FL and SE; sold to Unified Women's Healthcare at premium.",
    },
]
