"""Extended seed 80: Urology and men's health PE deals.

This module contains a curated set of 15 healthcare private equity deal
records focused on the urology and men's health services landscape. The
theme covers:

- Urology practice rollups and integrated urology MSOs
- Men's health platforms (testosterone replacement, ED, fertility)
- Kidney stone centers and lithotripsy networks
- BPH (benign prostatic hyperplasia) management and minimally invasive
  procedural platforms (UroLift, Rezum, prostate artery embolization)
- Urogynecology and female pelvic medicine platforms

Urology economics are shaped by an older, Medicare-heavy patient mix
(prostate disease, stone disease, incontinence) offset by commercial
self-pay demand in men's health wellness segments (TRT, ED). In-office
ancillary revenue (lithotripsy, pathology, radiation oncology, surgery
centers) is the core value-creation lever for PE-backed platforms.

Each record captures deal economics (EV, EV/EBITDA, margins), return
profile (MOIC, IRR, hold period), payer mix, regional footprint, sponsor,
and realization status. These records are synthesized for modeling,
backtesting, and scenario analysis use cases.
"""

EXTENDED_SEED_DEALS_80 = [
    {
        "company_name": "Summit Urology Partners",
        "sector": "Urology",
        "subsector": "Urology Practice Rollup",
        "year": 2018,
        "ev_mm": 485.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 38.8,
        "revenue_mm": 176.36,
        "ebitda_margin": 0.22,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.38, "medicare": 0.48, "medicaid": 0.07, "self_pay": 0.07},
        "comm_pct": 0.38,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Vitality Men's Health Network",
        "sector": "Men's Health",
        "subsector": "TRT and Wellness Clinics",
        "year": 2020,
        "ev_mm": 165.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 11.38,
        "revenue_mm": 45.52,
        "ebitda_margin": 0.25,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.18, "medicare": 0.05, "medicaid": 0.02, "self_pay": 0.75},
        "comm_pct": 0.18,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "StoneWise Kidney Centers",
        "sector": "Kidney Stone",
        "subsector": "Lithotripsy Services Network",
        "year": 2017,
        "ev_mm": 220.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 19.13,
        "revenue_mm": 91.10,
        "ebitda_margin": 0.21,
        "hold_years": 6.0,
        "moic": 2.8,
        "irr": 0.1872,
        "payer_mix": {"commercial": 0.40, "medicare": 0.46, "medicaid": 0.08, "self_pay": 0.06},
        "comm_pct": 0.40,
        "region": "Midwest",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "ProstateCare BPH Institute",
        "sector": "BPH Center",
        "subsector": "Minimally Invasive BPH Procedures",
        "year": 2019,
        "ev_mm": 175.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 13.26,
        "revenue_mm": 62.25,
        "ebitda_margin": 0.213,
        "hold_years": 4.5,
        "moic": 2.1,
        "irr": 0.1792,
        "payer_mix": {"commercial": 0.30, "medicare": 0.58, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.30,
        "region": "West",
        "buyer": "Frazier",
        "status": "Active",
    },
    {
        "company_name": "Meridian Urogynecology Group",
        "sector": "Urogynecology",
        "subsector": "Female Pelvic Medicine",
        "year": 2020,
        "ev_mm": 135.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 10.55,
        "revenue_mm": 45.87,
        "ebitda_margin": 0.23,
        "hold_years": 4.0,
        "moic": 1.9,
        "irr": 0.1741,
        "payer_mix": {"commercial": 0.52, "medicare": 0.35, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.52,
        "region": "Southeast",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Cornerstone Urology Associates",
        "sector": "Urology",
        "subsector": "Integrated Urology MSO",
        "year": 2016,
        "ev_mm": 720.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 61.02,
        "revenue_mm": 271.20,
        "ebitda_margin": 0.225,
        "hold_years": 6.5,
        "moic": 3.2,
        "irr": 0.1960,
        "payer_mix": {"commercial": 0.35, "medicare": 0.52, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.35,
        "region": "Midwest",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Apex Men's Performance",
        "sector": "Men's Health",
        "subsector": "ED and Sexual Health Clinics",
        "year": 2021,
        "ev_mm": 95.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 6.13,
        "revenue_mm": 22.70,
        "ebitda_margin": 0.27,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.12, "medicare": 0.03, "medicaid": 0.01, "self_pay": 0.84},
        "comm_pct": 0.12,
        "region": "West",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Atlantic Stone & Kidney",
        "sector": "Kidney Stone",
        "subsector": "Stone Disease Center of Excellence",
        "year": 2019,
        "ev_mm": 155.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 12.92,
        "revenue_mm": 68.0,
        "ebitda_margin": 0.19,
        "hold_years": 5.0,
        "moic": 2.3,
        "irr": 0.1813,
        "payer_mix": {"commercial": 0.42, "medicare": 0.44, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.42,
        "region": "Northeast",
        "buyer": "Harren",
        "status": "Partially Realized",
    },
    {
        "company_name": "ProsperHealth Urology Holdings",
        "sector": "Urology",
        "subsector": "Multi-state Urology Platform",
        "year": 2017,
        "ev_mm": 830.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 61.48,
        "revenue_mm": 256.17,
        "ebitda_margin": 0.24,
        "hold_years": 6.0,
        "moic": 3.0,
        "irr": 0.2009,
        "payer_mix": {"commercial": 0.36, "medicare": 0.50, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.36,
        "region": "National",
        "buyer": "Webster Equity",
        "status": "Realized",
    },
    {
        "company_name": "RezumFlow BPH Centers",
        "sector": "BPH Center",
        "subsector": "Outpatient BPH Treatment Network",
        "year": 2021,
        "ev_mm": 125.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 8.93,
        "revenue_mm": 37.21,
        "ebitda_margin": 0.24,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.28, "medicare": 0.62, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.28,
        "region": "Southeast",
        "buyer": "Cressey",
        "status": "Active",
    },
    {
        "company_name": "HerPelvic Urogynecology Partners",
        "sector": "Urogynecology",
        "subsector": "Urogynecology Rollup",
        "year": 2022,
        "ev_mm": 82.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 5.94,
        "revenue_mm": 29.70,
        "ebitda_margin": 0.20,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.55, "medicare": 0.32, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.55,
        "region": "West",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Legacy Men's Fertility Group",
        "sector": "Men's Health",
        "subsector": "Male Fertility and Reproductive",
        "year": 2018,
        "ev_mm": 205.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 13.67,
        "revenue_mm": 53.61,
        "ebitda_margin": 0.255,
        "hold_years": 5.5,
        "moic": 2.7,
        "irr": 0.1979,
        "payer_mix": {"commercial": 0.48, "medicare": 0.04, "medicaid": 0.03, "self_pay": 0.45},
        "comm_pct": 0.48,
        "region": "Northeast",
        "buyer": "Frazier",
        "status": "Realized",
    },
    {
        "company_name": "Horizon Stone Disease Institute",
        "sector": "Kidney Stone",
        "subsector": "Integrated Stone Treatment Platform",
        "year": 2022,
        "ev_mm": 110.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 8.46,
        "revenue_mm": 42.73,
        "ebitda_margin": 0.198,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.44, "medicare": 0.42, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.44,
        "region": "Southeast",
        "buyer": "Harren",
        "status": "Active",
    },
    {
        "company_name": "UroLink Surgery Centers",
        "sector": "Urology",
        "subsector": "Urology ASC Network",
        "year": 2019,
        "ev_mm": 395.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 30.38,
        "revenue_mm": 126.58,
        "ebitda_margin": 0.24,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.37, "medicare": 0.49, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.37,
        "region": "National",
        "buyer": "Welsh Carson",
        "status": "Partially Realized",
    },
    {
        "company_name": "Sterling BPH & Prostate Health",
        "sector": "BPH Center",
        "subsector": "UroLift and Prostate Procedures",
        "year": 2016,
        "ev_mm": 245.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 23.33,
        "revenue_mm": 103.69,
        "ebitda_margin": 0.225,
        "hold_years": 6.0,
        "moic": 3.8,
        "irr": 0.2492,
        "payer_mix": {"commercial": 0.26, "medicare": 0.64, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.26,
        "region": "Midwest",
        "buyer": "Cressey",
        "status": "Realized",
    },
]
