"""Extended seed batch 21 — deals 436-455."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_21: List[Dict[str, Any]] = [
    {
        "source_id": "seed_436",
        "deal_name": "Encompass Health / HealthSouth IRF spin + rebrand",
        "buyer": "HealthSouth Corp (public strategic)",
        "seller": "Legacy HME division buyers",
        "year": 2017,
        "deal_type": "carve-out",
        "sector": "ltach_post_acute",
        "ev_mm": 6000.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 500.0,
        "revenue_mm": 3800.0,
        "realized_moic": 2.5,
        "realized_irr": 0.18,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.09, "commercial": 0.16, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": 32000,
        "source": "seed",
        "notes": "Largest US IRF operator; rebrand from HealthSouth eliminated scandal premium; Medicare IRF rate stability",
    },
    {
        "source_id": "seed_437",
        "deal_name": "LifePoint Health / RCCH merge + Province Healthcare rollup",
        "buyer": "Apollo Global Management",
        "seller": "Public shareholders (LifePoint Health)",
        "year": 2018,
        "deal_type": "take-private",
        "sector": "hospital",
        "ev_mm": 5600.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 659.0,
        "revenue_mm": 6600.0,
        "realized_moic": 2.5,
        "realized_irr": 0.19,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.22, "commercial": 0.30, "self_pay": 0.06},
        "geography": "National",
        "hospital_beds": 28000,
        "source": "seed",
        "notes": "Apollo rural hospital roll-up; merged with RCCH post-close; COVID reimbursement support stabilized thesis",
    },
    {
        "source_id": "seed_438",
        "deal_name": "Molina Healthcare / Joseph Molina family buyout",
        "buyer": "Public company (NASDAQ: MOH)",
        "seller": "Molina family legacy / management",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "managed_care",
        "ev_mm": 5200.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 473.0,
        "revenue_mm": 18900.0,
        "realized_moic": 4.5,
        "realized_irr": 0.38,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.82, "commercial": 0.06, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Medicaid MCO with new management team; operational turnaround + ACA marketplace expansion; 5x stock run",
    },
    {
        "source_id": "seed_439",
        "deal_name": "Dermatology Associates / Harvest Partners roll-up",
        "buyer": "Harvest Partners",
        "seller": "Founder dermatologists",
        "year": 2019,
        "deal_type": "lbo",
        "sector": "physician_group",
        "ev_mm": 350.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 35.0,
        "revenue_mm": 160.0,
        "realized_moic": 3.8,
        "realized_irr": 0.32,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.22, "medicaid": 0.05, "commercial": 0.65, "self_pay": 0.08},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Derm DSO roll-up; Mohs surgery + cosmetic mix; cosmetic segment insulates from CMS rate pressure",
    },
    {
        "source_id": "seed_440",
        "deal_name": "Radiology Partners / New Enterprise Associates Series B-D",
        "buyer": "New Enterprise Associates / ADIA",
        "seller": "RadPartners founders",
        "year": 2016,
        "deal_type": "growth_equity",
        "sector": "radiology",
        "ev_mm": 750.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 400.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.12, "commercial": 0.42, "self_pay": 0.06},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Radiology hospital contract platform; grew to $2B+ revenue; NSA impact on radiology professional billing pending",
    },
    {
        "source_id": "seed_441",
        "deal_name": "R1 RCM / TowerBrook + Ascension health system partnership",
        "buyer": "TowerBrook Capital Partners + Ascension",
        "seller": "Accretive Health / Ascension JV",
        "year": 2016,
        "deal_type": "lbo",
        "sector": "rcm",
        "ev_mm": 1200.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 60.0,
        "revenue_mm": 700.0,
        "realized_moic": 5.0,
        "realized_irr": 0.40,
        "hold_years": 5.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "RCM SaaS + outsourced services; health system RCM outsourcing secular trend; IPO and M&A premium exit",
    },
    {
        "source_id": "seed_442",
        "deal_name": "Veritas Medical / Amsurg cardiology add-on",
        "buyer": "Carlyle Group / cardiovascular roll-up",
        "seller": "Cardiologists founding group",
        "year": 2018,
        "deal_type": "add-on",
        "sector": "cardiology",
        "ev_mm": 425.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 35.0,
        "revenue_mm": 180.0,
        "realized_moic": 3.2,
        "realized_irr": 0.27,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.08, "commercial": 0.33, "self_pay": 0.04},
        "geography": "Midwest",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Cardiology group add-on; structural heart + EP lab growth; Medicare cardiology volume resilient",
    },
    {
        "source_id": "seed_443",
        "deal_name": "National Staffing Group / healthcare staffing PE",
        "buyer": "Ridgemont Equity Partners",
        "seller": "Founder / management",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "managed_care_services",
        "ev_mm": 150.0,
        "ev_ebitda": 7.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 180.0,
        "realized_moic": 4.5,
        "realized_irr": 0.38,
        "hold_years": 4.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Healthcare temp staffing; COVID nursing shortage created massive demand spike; travel nurse margin explosion",
    },
    {
        "source_id": "seed_444",
        "deal_name": "Cotiviti / Veritas Capital secondary (post-Healtheon)",
        "buyer": "Carlyle Group",
        "seller": "Veritas Capital",
        "year": 2019,
        "deal_type": "secondary",
        "sector": "health_it",
        "ev_mm": 4800.0,
        "ev_ebitda": 24.0,
        "ebitda_mm": 200.0,
        "revenue_mm": 900.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Payer analytics + payment integrity SaaS secondary buyout; Cotiviti growing at 15%+ annually; Carlyle hold",
    },
    {
        "source_id": "seed_445",
        "deal_name": "MEDNAX / Sheridan Anesthesiology merger",
        "buyer": "MEDNAX Inc (public strategic)",
        "seller": "AmSurg / Sheridan investors",
        "year": 2016,
        "deal_type": "merger",
        "sector": "anesthesiology",
        "ev_mm": 2200.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 169.0,
        "revenue_mm": 1100.0,
        "realized_moic": 1.4,
        "realized_irr": 0.08,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.16, "commercial": 0.49, "self_pay": 0.07},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "MEDNAX expanded into anesthesia; synergies not realized; NSA impacted commercial; divestitures followed",
    },
    {
        "source_id": "seed_446",
        "deal_name": "Ankura Consulting / FTI Health group carve-out",
        "buyer": "Bain Capital Special Situations",
        "seller": "FTI Consulting Group",
        "year": 2017,
        "deal_type": "carve-out",
        "sector": "managed_care_services",
        "ev_mm": 340.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 28.0,
        "revenue_mm": 220.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 5.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Healthcare advisory/consulting carve-out; value-based care transitions drove demand for external expertise",
    },
    {
        "source_id": "seed_447",
        "deal_name": "Community Health Systems / Quorum Health distressed spin",
        "buyer": "CHS management / new equity",
        "seller": "Community Health Systems (CHS)",
        "year": 2016,
        "deal_type": "distressed",
        "sector": "hospital",
        "ev_mm": 1200.0,
        "ev_ebitda": 5.5,
        "ebitda_mm": 218.0,
        "revenue_mm": 2200.0,
        "realized_moic": 0.3,
        "realized_irr": -0.22,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.28, "commercial": 0.26, "self_pay": 0.06},
        "geography": "Southeast",
        "hospital_beds": 7500,
        "source": "seed",
        "notes": "CHS worst-performing hospitals spun into Quorum Health; filed Ch.11 2020; rural hospital distressed investing failure",
    },
    {
        "source_id": "seed_448",
        "deal_name": "MedBridge / TA Associates physical therapy digital",
        "buyer": "TA Associates",
        "seller": "Founders + earlier angels",
        "year": 2018,
        "deal_type": "growth_equity",
        "sector": "digital_health",
        "ev_mm": 180.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 25.0,
        "realized_moic": 4.2,
        "realized_irr": 0.36,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.05, "commercial": 0.55, "self_pay": 0.35},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "PT digital content + remote therapeutic monitoring; COVID drove telehealth physical therapy adoption and platform demand",
    },
    {
        "source_id": "seed_449",
        "deal_name": "PharMerica / BrightSpring merger (KKR + Walgreens)",
        "buyer": "KKR / Walgreens Boots Alliance",
        "seller": "KKR / PharMerica shareholders",
        "year": 2019,
        "deal_type": "merger",
        "sector": "pharmacy",
        "ev_mm": 3200.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 267.0,
        "revenue_mm": 4200.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.25, "commercial": 0.12, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "LTC pharmacy + HCBS merger; BrightSpring IPO at $4.1B in 2024; specialty Rx dispensing growth offset SNF volumes",
    },
    {
        "source_id": "seed_450",
        "deal_name": "GI Alliance / Ares Management + GI physician roll-up",
        "buyer": "Ares Management / Waud Capital",
        "seller": "Founding physician groups",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "gi",
        "ev_mm": 1800.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 138.0,
        "revenue_mm": 700.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.08, "commercial": 0.53, "self_pay": 0.04},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest GI group; colonoscopy ASC shift; ACA preventive care mandate; grew to $3B EV by 2022",
    },
    {
        "source_id": "seed_451",
        "deal_name": "Pediatric Home Service / Stellus Capital specialty",
        "buyer": "Stellus Capital Management",
        "seller": "Founders / management",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "home_health",
        "ev_mm": 90.0,
        "ev_ebitda": 8.0,
        "ebitda_mm": 11.0,
        "revenue_mm": 55.0,
        "realized_moic": 3.3,
        "realized_irr": 0.28,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.03, "medicaid": 0.88, "commercial": 0.09, "self_pay": 0.0},
        "geography": "MN",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Pediatric home respiratory therapy + nursing for vent-dependent kids; TEFRA/Medicaid waiver; sold to Bayada 2022",
    },
    {
        "source_id": "seed_452",
        "deal_name": "Caliber Imaging / pathology AI growth equity",
        "buyer": "General Atlantic / Bessemer Venture Partners",
        "seller": "Founders",
        "year": 2020,
        "deal_type": "growth_equity",
        "sector": "diagnostics",
        "ev_mm": 450.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 20.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.10, "commercial": 0.45, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Confocal moxifloscopy + digital pathology AI; FDA De Novo clearance 2018; real-time skin cancer diagnosis",
    },
    {
        "source_id": "seed_453",
        "deal_name": "Amedisys / LHC Group strategic position building",
        "buyer": "LHC Group / UnitedHealth Group",
        "seller": "Amedisys public shareholders",
        "year": 2018,
        "deal_type": "merger",
        "sector": "home_health",
        "ev_mm": 2200.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 138.0,
        "revenue_mm": 1700.0,
        "realized_moic": 3.5,
        "realized_irr": 0.29,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.73, "medicaid": 0.12, "commercial": 0.12, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Home health + hospice scale play; PDGM reform navigated through clinical operations investment; premium exit multiple",
    },
    {
        "source_id": "seed_454",
        "deal_name": "US Dermatology Partners / BBH (Brockton) roll-up",
        "buyer": "BBH Capital Partners",
        "seller": "Dermatologist founders",
        "year": 2017,
        "deal_type": "lbo",
        "sector": "physician_group",
        "ev_mm": 190.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 90.0,
        "realized_moic": 4.0,
        "realized_irr": 0.35,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.22, "medicaid": 0.06, "commercial": 0.62, "self_pay": 0.10},
        "geography": "TX",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Texas dermatology platform; biologic + cosmetic revenue; Mohs surgery complexity drives margin; sold to USDP 2021",
    },
    {
        "source_id": "seed_455",
        "deal_name": "Nuvance Health / Northwell Health affiliation",
        "buyer": "Northwell Health (nonprofit strategic)",
        "seller": "Western CT Health Network + Health Quest",
        "year": 2023,
        "deal_type": "merger",
        "sector": "hospital",
        "ev_mm": 2200.0,
        "ev_ebitda": 9.0,
        "ebitda_mm": 244.0,
        "revenue_mm": 2100.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.44, "medicaid": 0.18, "commercial": 0.32, "self_pay": 0.06},
        "geography": "NY",
        "hospital_beds": 5600,
        "source": "seed",
        "notes": "Hudson Valley health system affiliation; Northwell scale + purchasing power synergies for regional nonprofit",
    },
]
