"""Extended seed batch 11 — deals 236-255.

Covers: specialty physician groups (cardiology, GI, urology),
post-acute consolidation, health IT / AI platforms, pharmacy benefits,
rural health system affiliations, and durable medical equipment.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_11: list[dict] = [
    # 236 — Cardiology roll-up
    {
        "source_id": "seed_236",
        "deal_name": "Cardiovascular Associates of America / Bluewave Capital",
        "source": "seed",
        "buyer": "Bluewave Capital",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2021,
        "ev_mm": 420.0,
        "ebitda_mm": 38.0,
        "ev_ebitda": 11.1,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.08, "commercial": 0.30, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "AL",
        "notes": "140+ cardiologists; interventional + noninvasive; high Medicare due to CV patient age",
    },
    # 237 — GI physician group
    {
        "source_id": "seed_237",
        "deal_name": "GI Alliance / Ares Management",
        "source": "seed",
        "buyer": "Ares Management",
        "seller": "Waud Capital",
        "deal_type": "secondary_buyout",
        "year": 2021,
        "ev_mm": 1800.0,
        "ebitda_mm": 140.0,
        "ev_ebitda": 12.9,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.10, "commercial": 0.45, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Largest GI MSO in US; 800+ physicians; ASC-heavy; colonoscopy volume growth thesis",
    },
    # 238 — Urology specialty group
    {
        "source_id": "seed_238",
        "deal_name": "United Urology Group / Frazier Healthcare",
        "source": "seed",
        "buyer": "Frazier Healthcare Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2020,
        "ev_mm": 380.0,
        "ebitda_mm": 35.0,
        "ev_ebitda": 10.9,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.52, "medicaid": 0.08, "commercial": 0.38, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Mid-Atlantic",
        "state": "MD",
        "notes": "Mid-Atlantic urology MSO; in-office dispensing; kidney stone + prostate focus",
    },
    # 239 — Post-acute SNF chain acquisition
    {
        "source_id": "seed_239",
        "deal_name": "Diversicare Healthcare / Wellstone Capital",
        "source": "seed",
        "buyer": "Wellstone Capital",
        "seller": "Public (Nasdaq: DVCR take-private)",
        "deal_type": "take_private",
        "year": 2022,
        "ev_mm": 280.0,
        "ebitda_mm": 22.0,
        "ev_ebitda": 12.7,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.60, "commercial": 0.08, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TN",
        "notes": "61 SNFs in Southeast; high Medicaid; occupancy recovery post-COVID thesis",
    },
    # 240 — AI-powered clinical decision support
    {
        "source_id": "seed_240",
        "deal_name": "Veracyte / PE Growth Investment",
        "source": "seed",
        "buyer": "Various PE (growth round)",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2020,
        "ev_mm": 800.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": 5.5,
        "realized_irr": 0.53,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.05, "commercial": 0.48, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Genomic cancer diagnostics; thyroid + bladder cancer; FDA-cleared AI test",
    },
    # 241 — Pharmacy benefit management spin-off
    {
        "source_id": "seed_241",
        "deal_name": "Prime Therapeutics / BCBS PBM JV",
        "source": "seed",
        "buyer": "BCBS Plans (JV owner)",
        "seller": "Various BCBS plans",
        "deal_type": "joint_venture",
        "year": 2019,
        "ev_mm": 2500.0,
        "ebitda_mm": 200.0,
        "ev_ebitda": 12.5,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.10, "commercial": 0.70, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Multi-BCBS plan PBM JV; formulary management + specialty pharmacy; rebate transparency risk",
    },
    # 242 — Rural hospital affiliation
    {
        "source_id": "seed_242",
        "deal_name": "Ballad Health / Mountain States Health Alliance",
        "source": "seed",
        "buyer": "Ballad Health (merged entity)",
        "seller": "Mountain States Health Alliance + Wellmont Health System",
        "deal_type": "merger",
        "year": 2018,
        "ev_mm": 1800.0,
        "ebitda_mm": 130.0,
        "ev_ebitda": 13.8,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.48, "medicaid": 0.30, "commercial": 0.20, "self_pay": 0.02},
        "hospital_beds": 2400,
        "region": "Southeast",
        "state": "TN",
        "notes": "Tri-Cities TN/VA merger; FTC approved with certificate of public advantage; rural concentration",
    },
    # 243 — Durable medical equipment
    {
        "source_id": "seed_243",
        "deal_name": "AdaptHealth / Goldman Sachs BDC",
        "source": "seed",
        "buyer": "AdaptHealth (SPAC acquisition)",
        "seller": "Various DME operators",
        "deal_type": "strategic_acquisition",
        "year": 2019,
        "ev_mm": 900.0,
        "ebitda_mm": 70.0,
        "ev_ebitda": 12.9,
        "hold_years": 3.0,
        "realized_moic": 2.0,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.15, "commercial": 0.22, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "CPAP/APAP + O2 + complex rehab; SPAC + rapid M&A roll-up; Medicare billing compliance risk",
    },
    # 244 — Telemedicine platform
    {
        "source_id": "seed_244",
        "deal_name": "Doctor on Demand / Grand Rounds Merger",
        "source": "seed",
        "buyer": "Included Health (merged)",
        "seller": "Founders / Investors",
        "deal_type": "merger",
        "year": 2021,
        "ev_mm": 1300.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": 2.8,
        "realized_irr": 0.30,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.10, "commercial": 0.82, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Virtual primary care + specialty; employer-sponsored model; COVID tailwind + post-COVID normalization",
    },
    # 245 — Orthopedic surgery center
    {
        "source_id": "seed_245",
        "deal_name": "AMSURG / Envision Healthcare Merger",
        "source": "seed",
        "buyer": "AMSURG (ASC operator)",
        "seller": "Envision Healthcare Investors",
        "deal_type": "merger",
        "year": 2016,
        "ev_mm": 15000.0,
        "ebitda_mm": 900.0,
        "ev_ebitda": 16.7,
        "hold_years": 3.0,
        "realized_moic": 0.5,
        "realized_irr": -0.22,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.12, "commercial": 0.45, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "KKR-backed Envision + AMSURG merger; physician staffing + ASC combination; NSA surprise billing",
    },
    # 246 — Wound care management
    {
        "source_id": "seed_246",
        "deal_name": "Healogics / Arsenal Capital",
        "source": "seed",
        "buyer": "Arsenal Capital Partners",
        "seller": "General Atlantic",
        "deal_type": "secondary_buyout",
        "year": 2019,
        "ev_mm": 750.0,
        "ebitda_mm": 60.0,
        "ev_ebitda": 12.5,
        "hold_years": 5.0,
        "realized_moic": 2.9,
        "realized_irr": 0.24,
        "payer_mix": {"medicare": 0.62, "medicaid": 0.15, "commercial": 0.21, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Wound care management company; hospital-outpatient wound centers; CMS LCD coverage risk",
    },
    # 247 — Revenue cycle AI platform
    {
        "source_id": "seed_247",
        "deal_name": "Waystar / EQT",
        "source": "seed",
        "buyer": "EQT Partners",
        "seller": "Bain Capital + Navicure",
        "deal_type": "secondary_buyout",
        "year": 2019,
        "ev_mm": 2700.0,
        "ebitda_mm": 200.0,
        "ev_ebitda": 13.5,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Cloud RCM platform; Navicure + ZirMed merger; clearinghouse + analytics SaaS",
    },
    # 248 — Home health / HCBS add-on
    {
        "source_id": "seed_248",
        "deal_name": "BrightSpring Home Services / KKR Add-Ons",
        "source": "seed",
        "buyer": "KKR / BrightSpring",
        "seller": "Various HCBS operators",
        "deal_type": "add_on",
        "year": 2020,
        "ev_mm": 400.0,
        "ebitda_mm": 30.0,
        "ev_ebitda": 13.3,
        "hold_years": 2.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.72, "commercial": 0.08, "self_pay": 0.05},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "KY",
        "notes": "Add-on acquisitions into BrightSpring HCBS platform; I/DD + behavioral + pharmacy",
    },
    # 249 — Neonatal / pediatric specialty
    {
        "source_id": "seed_249",
        "deal_name": "MEDNAX / Pediatrix Medical Group / Icahn",
        "source": "seed",
        "buyer": "Icahn Enterprises (activist stake)",
        "seller": "Public (NYSE: MD)",
        "deal_type": "take_private",
        "year": 2021,
        "ev_mm": 2800.0,
        "ebitda_mm": 230.0,
        "ev_ebitda": 12.2,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.28, "commercial": 0.55, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "NICU + pediatric subspecialty staffing; partial divestiture of non-neo lines; NSA exposure",
    },
    # 250 — Healthcare analytics / population health
    {
        "source_id": "seed_250",
        "deal_name": "Arcadia / Warburg Pincus",
        "source": "seed",
        "buyer": "Warburg Pincus",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2020,
        "ev_mm": 500.0,
        "ebitda_mm": 35.0,
        "ev_ebitda": 14.3,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": "VA",
        "notes": "Population health analytics; value-based care enabling platform; FHIR + ADT integration",
    },
    # 251 — Maternal-fetal medicine specialty
    {
        "source_id": "seed_251",
        "deal_name": "Maternal Fetal Medicine of America / Kainos Capital",
        "source": "seed",
        "buyer": "Kainos Capital",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2022,
        "ev_mm": 280.0,
        "ebitda_mm": 26.0,
        "ev_ebitda": 10.8,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.38, "commercial": 0.55, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TX",
        "notes": "MFM subspecialty roll-up; high-risk OB; commercial mix supported by employer insurance",
    },
    # 252 — Radiology / teleradiology
    {
        "source_id": "seed_252",
        "deal_name": "Radiology Partners / New Enterprise Associates",
        "source": "seed",
        "buyer": "New Enterprise Associates / Starr Investment Holdings",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2018,
        "ev_mm": 2000.0,
        "ebitda_mm": 150.0,
        "ev_ebitda": 13.3,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.48, "medicaid": 0.12, "commercial": 0.38, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Largest physician-owned radiology group; 2,500+ radiologists; NSA + AI overread thesis",
    },
    # 253 — Substance use disorder / MAT
    {
        "source_id": "seed_253",
        "deal_name": "Acadia Healthcare / Addiction Treatment Centers Add-Ons",
        "source": "seed",
        "buyer": "Acadia Healthcare",
        "seller": "Various regional operators",
        "deal_type": "add_on",
        "year": 2021,
        "ev_mm": 350.0,
        "ebitda_mm": 32.0,
        "ev_ebitda": 10.9,
        "hold_years": 3.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.12, "medicaid": 0.45, "commercial": 0.40, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TN",
        "notes": "SUD residential + PHP/IOP add-ons; CARF accredited; parity law enforcement tailwind",
    },
    # 254 — Health system technology integration
    {
        "source_id": "seed_254",
        "deal_name": "Kyruus Health / Vista Equity",
        "source": "seed",
        "buyer": "Vista Equity Partners",
        "seller": "Founders / Growth investors",
        "deal_type": "lbo",
        "year": 2022,
        "ev_mm": 600.0,
        "ebitda_mm": 50.0,
        "ev_ebitda": 12.0,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": "MA",
        "notes": "Provider directory + care access platform; SaaS; health system + payer duality",
    },
    # 255 — Animal health / veterinary roll-up (adjacent sector)
    {
        "source_id": "seed_255",
        "deal_name": "NVA (National Veterinary Associates) / JAB Holding",
        "source": "seed",
        "buyer": "JAB Holding Company",
        "seller": "Ares Management",
        "deal_type": "secondary_buyout",
        "year": 2019,
        "ev_mm": 3300.0,
        "ebitda_mm": 250.0,
        "ev_ebitda": 13.2,
        "hold_years": 5.0,
        "realized_moic": 3.0,
        "realized_irr": 0.25,
        "payer_mix": {"medicare": 0.00, "medicaid": 0.00, "commercial": 0.20, "self_pay": 0.80},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Veterinary hospital roll-up; adjacent to healthcare PE playbook; high self-pay; pet insurance growth",
    },
]
