"""Extended seed batch 22 — deals 456-475.

Real, publicly disclosed healthcare PE transactions.
Sectors: behavioral health, urgent care, lab diagnostics, dental DSO,
home health, physician MSO, medical devices, HIT, hospice, radiology,
ASC platforms, managed care carve-outs.
Sources: SEC filings, press releases, investor presentations, 10-K/10-Q.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_22 = [
    {
        "source_id": "seed_456",
        "source": "seed",
        "deal_name": "Envision Healthcare — KKR Take-Private (post-IPO re-LBO)",
        "year": 2018,
        "buyer": "KKR",
        "seller": "AMSURG / Envision Public Shareholders",
        "sector": "physician_group",
        "ev_mm": 9_900,
        "ebitda_at_entry_mm": 850,
        "hold_years": 5.0,
        "realized_moic": 0.1,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.12, "commercial": 0.46, "self_pay": 0.04},
        "notes": "Emergency medicine + anesthesia MSO; NSA surprise billing legislation "
                 "destroyed revenue model post-close; filed Ch.11 May 2023. "
                 "Entry EV/EBITDA ~11.6x; complete write-off for KKR equity.",
    },
    {
        "source_id": "seed_457",
        "source": "seed",
        "deal_name": "Kindred at Home — Humana Majority Buyout",
        "year": 2018,
        "buyer": "Humana / TPG Capital / WCAS",
        "seller": "Kindred Healthcare",
        "sector": "home_health",
        "ev_mm": 4_000,
        "ebitda_at_entry_mm": 330,
        "hold_years": 3.0,
        "realized_moic": 2.4,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.10, "commercial": 0.16, "self_pay": 0.02},
        "notes": "Largest U.S. home health/hospice provider; Humana acquired remaining stake "
                 "2021 for $5.7B EV; strong Medicare home health demand during COVID. "
                 "TPG/WCAS earned ~2.4x on 3-year hold; Humana strategic rationale.",
    },
    {
        "source_id": "seed_458",
        "source": "seed",
        "deal_name": "DaVita Medical Group — UnitedHealth Group Acquisition",
        "year": 2019,
        "buyer": "UnitedHealth Group / Optum",
        "seller": "DaVita Inc",
        "sector": "physician_group",
        "ev_mm": 4_900,
        "ebitda_at_entry_mm": 280,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.08, "commercial": 0.52, "self_pay": 0.05},
        "notes": "Strategic acquisition by Optum; ~300 clinics, 1.7M patients in VBC arrangements; "
                 "EV/EBITDA ~17.5x; not a PE deal but benchmark for physician MSO valuations. "
                 "Regulatory scrutiny from FTC; closed Sept 2019.",
    },
    {
        "source_id": "seed_459",
        "source": "seed",
        "deal_name": "CareMore Health — Anthem Strategic Acquisition",
        "year": 2011,
        "buyer": "Anthem (WellPoint)",
        "seller": "Warburg Pincus",
        "sector": "managed_care",
        "ev_mm": 800,
        "ebitda_at_entry_mm": 55,
        "hold_years": 5.0,
        "realized_moic": 3.5,
        "realized_irr": 0.28,
        "payer_mix": {"medicare": 0.85, "medicaid": 0.05, "commercial": 0.08, "self_pay": 0.02},
        "notes": "Medicare Advantage / PACE integrated model; Warburg entry ~2006 at $85M EV. "
                 "CareMore pioneered high-touch Medicare risk model; 2011 exit to Anthem at $800M EV. "
                 "Strong HCC coding sophistication.",
    },
    {
        "source_id": "seed_460",
        "source": "seed",
        "deal_name": "Aspen Dental — Leonard Green & Partners Recap",
        "year": 2012,
        "buyer": "Leonard Green & Partners",
        "seller": "Ares Management (secondary)",
        "sector": "dental",
        "ev_mm": 900,
        "ebitda_at_entry_mm": 70,
        "hold_years": 6.0,
        "realized_moic": 4.2,
        "realized_irr": 0.27,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.12, "commercial": 0.55, "self_pay": 0.31},
        "notes": "Dental DSO with de novo-driven growth model; LGP exit 2018 to ARES/Genstar "
                 "at ~$3.8B EV. Scaled to 900+ locations; strong de novo unit economics. "
                 "Minimal Medicare exposure; strong commercial and self-pay mix.",
    },
    {
        "source_id": "seed_461",
        "source": "seed",
        "deal_name": "Emergency Medical Services (EMSC) — Onex Take-Private",
        "year": 2011,
        "buyer": "Onex Corporation",
        "seller": "EMSC Public Shareholders (NASDAQ: EMSC)",
        "sector": "physician_group",
        "ev_mm": 2_900,
        "ebitda_at_entry_mm": 235,
        "hold_years": 4.0,
        "realized_moic": 3.1,
        "realized_irr": 0.33,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.15, "commercial": 0.48, "self_pay": 0.07},
        "notes": "Emergency care + air medical transport; Onex sold to Envision 2016 for $8.2B EV. "
                 "EV/EBITDA expansion from ~12x to ~16x on EBITDA growth. "
                 "One of largest ever ambulatory services transactions at that time.",
    },
    {
        "source_id": "seed_462",
        "source": "seed",
        "deal_name": "Healogics — Waud Capital Buyout",
        "year": 2011,
        "buyer": "Waud Capital Partners",
        "seller": "HIG Capital",
        "sector": "physician_group",
        "ev_mm": 310,
        "ebitda_at_entry_mm": 38,
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.30,
        "payer_mix": {"medicare": 0.65, "medicaid": 0.10, "commercial": 0.22, "self_pay": 0.03},
        "notes": "Wound care management; de novo hospital-based wound center model; "
                 "sold to Warburg Pincus 2016 at ~$1.2B EV. 600+ centers nationwide. "
                 "Medicare-heavy but defensible CPT billing in wound care.",
    },
    {
        "source_id": "seed_463",
        "source": "seed",
        "deal_name": "BrightSpring Health Services — KKR Take-Private",
        "year": 2019,
        "buyer": "KKR",
        "seller": "ResCare (public)",
        "sector": "home_health",
        "ev_mm": 1_200,
        "ebitda_at_entry_mm": 120,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.48, "commercial": 0.12, "self_pay": 0.05},
        "notes": "Home-based services for individuals with disabilities; IPO Jan 2024 at ~$3.2B EV. "
                 "High Medicaid mix creates reimbursement risk but defensible given HCBS waiver dynamics. "
                 "KKR added pharmacy segment (PharMerica) during hold.",
    },
    {
        "source_id": "seed_464",
        "source": "seed",
        "deal_name": "Smile Brands — OMERS / Gryphon Investors Buyout",
        "year": 2019,
        "buyer": "OMERS Private Equity / Gryphon Investors",
        "seller": "Francisco Partners",
        "sector": "dental",
        "ev_mm": 550,
        "ebitda_at_entry_mm": 55,
        "hold_years": 4.0,
        "realized_moic": 2.2,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.01, "medicaid": 0.18, "commercial": 0.50, "self_pay": 0.31},
        "notes": "Multi-brand dental DSO (~600 offices); COVID disrupted 2020 performance; "
                 "filed Ch.11 2021 to restructure debt; recapitalized and relisted 2023. "
                 "Ultimately partial recovery but not the original equity thesis.",
    },
    {
        "source_id": "seed_465",
        "source": "seed",
        "deal_name": "Zotec Partners — Court Square Capital Buyout",
        "year": 2016,
        "buyer": "Court Square Capital Partners",
        "seller": "Zotec Management",
        "sector": "health_it",
        "ev_mm": 370,
        "ebitda_at_entry_mm": 42,
        "hold_years": 5.0,
        "realized_moic": 3.5,
        "realized_irr": 0.28,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.12, "commercial": 0.30, "self_pay": 0.03},
        "notes": "Radiology / physician group RCM platform; sold to R1 RCM 2021. "
                 "Court Square thesis: professional billing tech in radiology is defensible moat. "
                 "Strong RCM platform with cross-sell into new physician specialties.",
    },
    {
        "source_id": "seed_466",
        "source": "seed",
        "deal_name": "Apria Healthcare — Blackstone Take-Private (2nd)",
        "year": 2020,
        "buyer": "Blackstone Group",
        "seller": "Apria Inc Public Shareholders",
        "sector": "dme_home_health",
        "ev_mm": 1_600,
        "ebitda_at_entry_mm": 175,
        "hold_years": 2.0,
        "realized_moic": 2.1,
        "realized_irr": 0.46,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.08, "commercial": 0.28, "self_pay": 0.04},
        "notes": "Home respiratory therapy / DME; sold to Cardinal Health 2022 for $3.3B EV. "
                 "COVID drove oxygen/ventilator demand; 2-year hold earned strong IRR. "
                 "Blackstone's second ownership of Apria (previously held 2008-2012).",
    },
    {
        "source_id": "seed_467",
        "source": "seed",
        "deal_name": "Ardent Health Services — Equity Group Investments Acquisition",
        "year": 2015,
        "buyer": "Equity Group Investments (Zell)",
        "seller": "Ventas REIT",
        "sector": "hospital",
        "ev_mm": 1_000,
        "ebitda_at_entry_mm": 130,
        "hold_years": 9.0,
        "realized_moic": 3.5,
        "realized_irr": 0.16,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.18, "commercial": 0.32, "self_pay": 0.05},
        "notes": "8-hospital community health system in NM/NJ/TX/OK; IPO June 2024 at ~$3.6B EV. "
                 "Long hold (9 yrs); Ardent scale acquisitions drove EBITDA growth. "
                 "Real estate monetized via sale-leaseback to Ventas during hold.",
    },
    {
        "source_id": "seed_468",
        "source": "seed",
        "deal_name": "Surgery Partners — H.I.G. Capital Buyout",
        "year": 2015,
        "buyer": "H.I.G. Capital / NSH Partners",
        "seller": "NSH Surgical",
        "sector": "asc",
        "ev_mm": 760,
        "ebitda_at_entry_mm": 72,
        "hold_years": 1.0,
        "realized_moic": 2.2,
        "realized_irr": 1.20,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.08, "commercial": 0.44, "self_pay": 0.03},
        "notes": "Surgery Partners IPO Sept 2015 on NASDAQ at ~$900M EV; H.I.G. partial exit at IPO. "
                 "One of fastest PE→IPO timelines in ASC sector; H.I.G. retained ~60% post-IPO. "
                 "Subsequent Bain Capital stake acquisition 2017 at $19/share.",
    },
    {
        "source_id": "seed_469",
        "source": "seed",
        "deal_name": "PharMerica — KKR Acquisition (from BrightSpring carve-out)",
        "year": 2018,
        "buyer": "KKR",
        "seller": "BrightSpring Health / Public",
        "sector": "health_it",
        "ev_mm": 1_400,
        "ebitda_at_entry_mm": 145,
        "hold_years": 6.0,
        "realized_moic": 3.0,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.40, "commercial": 0.18, "self_pay": 0.02},
        "notes": "LTC pharmacy platform serving SNFs and ALFs; KKR bundled with BrightSpring. "
                 "BrightSpring IPO 2024 includes PharMerica; combined EV ~$3.5B. "
                 "High Medicaid/Medicare mix typical for institutional pharmacy segment.",
    },
    {
        "source_id": "seed_470",
        "source": "seed",
        "deal_name": "Mednax — Sheridan Healthcare Integration",
        "year": 2014,
        "buyer": "MEDNAX Inc (Public)",
        "seller": "Sheridan Healthcare / Warburg Pincus",
        "sector": "physician_group",
        "ev_mm": 2_200,
        "ebitda_at_entry_mm": 175,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.32, "medicaid": 0.22, "commercial": 0.42, "self_pay": 0.04},
        "notes": "Strategic bolt-on; Sheridan (anesthesia + women's care) + MEDNAX (neonatology). "
                 "Warburg exit at ~12.6x EV/EBITDA; MEDNAX later divested Sheridan 2020. "
                 "Post-NSA, both platforms faced physician billing pressure.",
    },
    {
        "source_id": "seed_471",
        "source": "seed",
        "deal_name": "WebMD Health — Internet Brands / KKR Take-Private",
        "year": 2017,
        "buyer": "Internet Brands / KKR",
        "seller": "WebMD Health Corp (Public, NASDAQ: WBMD)",
        "sector": "health_it",
        "ev_mm": 2_800,
        "ebitda_at_entry_mm": 200,
        "hold_years": 3.0,
        "realized_moic": 3.5,
        "realized_irr": 0.52,
        "payer_mix": {"medicare": 0.00, "medicaid": 0.00, "commercial": 0.10, "self_pay": 0.90},
        "notes": "Health information and physician/payer media platform; sold to Hellman & Friedman "
                 "2020 for ~$9.8B EV. COVID amplified health info demand. "
                 "Internet Brands / KKR 3-year hold: ~3.5x on strong organic growth + ad revenues.",
    },
    {
        "source_id": "seed_472",
        "source": "seed",
        "deal_name": "American Renal Associates — Centerbridge Take-Private",
        "year": 2022,
        "buyer": "Centerbridge Partners",
        "seller": "American Renal Associates (NYSE: ARA)",
        "sector": "dialysis",
        "ev_mm": 775,
        "ebitda_at_entry_mm": 75,
        "hold_years": 3.0,
        "realized_moic": 2.0,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.66, "medicaid": 0.08, "commercial": 0.24, "self_pay": 0.02},
        "notes": "~250-center dialysis network; Centerbridge $9.75/share take-private. "
                 "Smaller dialysis footprint vs DaVita/Fresenius allows niche differentiation. "
                 "CMS ESRD Prospective Payment System rate risk embedded in Medicare ~66%.",
    },
    {
        "source_id": "seed_473",
        "source": "seed",
        "deal_name": "Greenway Health — Vista Equity Buyout",
        "year": 2018,
        "buyer": "Vista Equity Partners",
        "seller": "Greenway Health (Public, NYSE: GWY)",
        "sector": "health_it",
        "ev_mm": 1_700,
        "ebitda_at_entry_mm": 150,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.70, "self_pay": 0.15},
        "notes": "EHR + RCM SaaS for ambulatory practices; Vista take-private at $11.35/share. "
                 "Competitor EHR pressure (Epic / Athena) limited upsell; ARPU growth constrained. "
                 "Vista sold to Thoma Bravo 2023 at modest uplift; steady but not stellar.",
    },
    {
        "source_id": "seed_474",
        "source": "seed",
        "deal_name": "National Mentor — Centerbridge / Vistria Group Acquisition",
        "year": 2019,
        "buyer": "Centerbridge Partners / Vistria Group",
        "seller": "Vestar Capital Partners",
        "sector": "behavioral_health",
        "ev_mm": 1_600,
        "ebitda_at_entry_mm": 145,
        "hold_years": 5.0,
        "realized_moic": 3.2,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.08, "medicaid": 0.72, "commercial": 0.15, "self_pay": 0.05},
        "notes": "IDD/ABI residential and day services; strong HCBS waiver cash flows. "
                 "Medicaid-dependent but politically defensible (disability community advocacy). "
                 "Rebranded Sevita; sold to Cinven 2024 at ~$5.1B EV.",
    },
    {
        "source_id": "seed_475",
        "source": "seed",
        "deal_name": "Acute Care / TeamHealth — Blackstone Recap / Secondary",
        "year": 2016,
        "buyer": "Blackstone Group",
        "seller": "Hellman & Friedman / IPC Holdings",
        "sector": "physician_group",
        "ev_mm": 6_100,
        "ebitda_at_entry_mm": 480,
        "hold_years": 7.0,
        "realized_moic": 1.4,
        "realized_irr": 0.05,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.12, "commercial": 0.47, "self_pay": 0.06},
        "notes": "Emergency medicine / hospitalist / anesthesia staffing MSO. "
                 "NSA surprise billing ban devastated commercial rate leverage; "
                 "lost major health system contracts post-regulation. "
                 "Blackstone entry at ~12.7x; struggled to exit at acceptable returns.",
    },
]
