"""Extended seed batch 53 — senior care and post-acute PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_53: list[dict] = [
    {
        "source_id": "ext53_001",
        "company_name": "Heartland Skilled Nursing Partners",
        "sector": "skilled nursing facility chain",
        "year": 2015,
        "ev_mm": 320.0,
        "ev_ebitda": 9.5,
        "moic": 3.1,
        "irr": 0.26,
        "hold_years": 5.0,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"medicare": 0.60, "medicaid": 0.30, "commercial": 0.06, "self_pay": 0.04},
        "geography": "Midwest",
        "ebitda_margin": 0.14,
        "revenue_mm": 240.0,
    },
    {
        "source_id": "ext53_002",
        "company_name": "Sunrise Assisted Living Holdings",
        "sector": "assisted living operator",
        "year": 2017,
        "ev_mm": 185.0,
        "ev_ebitda": 10.2,
        "moic": 2.8,
        "irr": 0.23,
        "hold_years": 4.5,
        "sponsor": "Blackstone",
        "payer_mix": {"medicare": 0.50, "medicaid": 0.25, "commercial": 0.15, "self_pay": 0.10},
        "geography": "Southeast",
        "ebitda_margin": 0.16,
        "revenue_mm": 113.0,
    },
    {
        "source_id": "ext53_003",
        "company_name": "Clarity Memory Care Communities",
        "sector": "memory care community",
        "year": 2016,
        "ev_mm": 145.0,
        "ev_ebitda": 11.0,
        "moic": 3.4,
        "irr": 0.29,
        "hold_years": 4.0,
        "sponsor": "KKR",
        "payer_mix": {"medicare": 0.55, "medicaid": 0.28, "commercial": 0.10, "self_pay": 0.07},
        "geography": "Southwest",
        "ebitda_margin": 0.18,
        "revenue_mm": 83.0,
    },
    {
        "source_id": "ext53_004",
        "company_name": "Maplebrook Continuing Care Retirement",
        "sector": "continuing care retirement community",
        "year": 2013,
        "ev_mm": 420.0,
        "ev_ebitda": 12.0,
        "moic": 2.5,
        "irr": 0.20,
        "hold_years": 6.5,
        "sponsor": "Carlyle Group",
        "payer_mix": {"medicare": 0.52, "medicaid": 0.22, "commercial": 0.18, "self_pay": 0.08},
        "geography": "Northeast",
        "ebitda_margin": 0.12,
        "revenue_mm": 385.0,
    },
    {
        "source_id": "ext53_005",
        "company_name": "Pinnacle Senior Housing REIT",
        "sector": "senior housing REIT",
        "year": 2018,
        "ev_mm": 760.0,
        "ev_ebitda": 12.5,
        "moic": 2.4,
        "irr": 0.19,
        "hold_years": 5.5,
        "sponsor": "Apollo Global Management",
        "payer_mix": {"medicare": 0.48, "medicaid": 0.20, "commercial": 0.22, "self_pay": 0.10},
        "geography": "National",
        "ebitda_margin": 0.13,
        "revenue_mm": 620.0,
    },
    {
        "source_id": "ext53_006",
        "company_name": "Vitality Adult Day Care Network",
        "sector": "adult day care network",
        "year": 2014,
        "ev_mm": 78.0,
        "ev_ebitda": 8.5,
        "moic": 3.6,
        "irr": 0.31,
        "hold_years": 4.0,
        "sponsor": "GTCR",
        "payer_mix": {"medicare": 0.58, "medicaid": 0.32, "commercial": 0.06, "self_pay": 0.04},
        "geography": "Mid-Atlantic",
        "ebitda_margin": 0.17,
        "revenue_mm": 50.0,
    },
    {
        "source_id": "ext53_007",
        "company_name": "CareForce Home Staffing Solutions",
        "sector": "home care staffing",
        "year": 2019,
        "ev_mm": 110.0,
        "ev_ebitda": 9.0,
        "moic": 3.0,
        "irr": 0.27,
        "hold_years": 3.5,
        "sponsor": "Welsh Carson Anderson & Stowe",
        "payer_mix": {"medicare": 0.62, "medicaid": 0.22, "commercial": 0.12, "self_pay": 0.04},
        "geography": "Southeast",
        "ebitda_margin": 0.11,
        "revenue_mm": 118.0,
    },
    {
        "source_id": "ext53_008",
        "company_name": "Harbor View Independent Living",
        "sector": "independent living community",
        "year": 2015,
        "ev_mm": 200.0,
        "ev_ebitda": 10.8,
        "moic": 2.9,
        "irr": 0.24,
        "hold_years": 5.0,
        "sponsor": "Ares Management",
        "payer_mix": {"medicare": 0.30, "medicaid": 0.10, "commercial": 0.25, "self_pay": 0.35},
        "geography": "Pacific Northwest",
        "ebitda_margin": 0.19,
        "revenue_mm": 158.0,
    },
    {
        "source_id": "ext53_009",
        "company_name": "Continuum PACE Program Operators",
        "sector": "PACE program operator",
        "year": 2017,
        "ev_mm": 95.0,
        "ev_ebitda": 8.0,
        "moic": 3.8,
        "irr": 0.33,
        "hold_years": 4.5,
        "sponsor": "New Mountain Capital",
        "payer_mix": {"medicare": 0.65, "medicaid": 0.30, "commercial": 0.03, "self_pay": 0.02},
        "geography": "Northeast",
        "ebitda_margin": 0.15,
        "revenue_mm": 79.0,
    },
    {
        "source_id": "ext53_010",
        "company_name": "ElderPath Geriatric Care Management",
        "sector": "geriatric care management",
        "year": 2020,
        "ev_mm": 65.0,
        "ev_ebitda": 7.5,
        "moic": 2.6,
        "irr": 0.22,
        "hold_years": 4.0,
        "sponsor": "Summit Partners",
        "payer_mix": {"medicare": 0.55, "medicaid": 0.18, "commercial": 0.20, "self_pay": 0.07},
        "geography": "Midwest",
        "ebitda_margin": 0.13,
        "revenue_mm": 60.0,
    },
    {
        "source_id": "ext53_011",
        "company_name": "Meridian Long-Term Acute Care Hospitals",
        "sector": "long-term acute care",
        "year": 2013,
        "ev_mm": 540.0,
        "ev_ebitda": 11.5,
        "moic": 2.3,
        "irr": 0.18,
        "hold_years": 7.0,
        "sponsor": "TPG Capital",
        "payer_mix": {"medicare": 0.68, "medicaid": 0.22, "commercial": 0.08, "self_pay": 0.02},
        "geography": "South Central",
        "ebitda_margin": 0.10,
        "revenue_mm": 505.0,
    },
    {
        "source_id": "ext53_012",
        "company_name": "Restore Inpatient Rehabilitation Facilities",
        "sector": "inpatient rehabilitation facility",
        "year": 2016,
        "ev_mm": 390.0,
        "ev_ebitda": 12.8,
        "moic": 3.2,
        "irr": 0.25,
        "hold_years": 5.5,
        "sponsor": "Bain Capital",
        "payer_mix": {"medicare": 0.66, "medicaid": 0.16, "commercial": 0.14, "self_pay": 0.04},
        "geography": "Southeast",
        "ebitda_margin": 0.16,
        "revenue_mm": 322.0,
    },
    {
        "source_id": "ext53_013",
        "company_name": "BridgeCare Transitional Care Units",
        "sector": "transitional care unit",
        "year": 2018,
        "ev_mm": 130.0,
        "ev_ebitda": 9.8,
        "moic": 2.7,
        "irr": 0.23,
        "hold_years": 4.5,
        "sponsor": "Hellman & Friedman",
        "payer_mix": {"medicare": 0.63, "medicaid": 0.24, "commercial": 0.09, "self_pay": 0.04},
        "geography": "Great Lakes",
        "ebitda_margin": 0.14,
        "revenue_mm": 96.0,
    },
    {
        "source_id": "ext53_014",
        "company_name": "Nexus Post-Acute Care Network",
        "sector": "post-acute care network",
        "year": 2021,
        "ev_mm": 610.0,
        "ev_ebitda": 13.0,
        "moic": 2.2,
        "irr": 0.19,
        "hold_years": 6.0,
        "sponsor": "Francisco Partners",
        "payer_mix": {"medicare": 0.60, "medicaid": 0.26, "commercial": 0.10, "self_pay": 0.04},
        "geography": "National",
        "ebitda_margin": 0.09,
        "revenue_mm": 558.0,
    },
    {
        "source_id": "ext53_015",
        "company_name": "Concord Senior Concierge Medicine",
        "sector": "senior concierge medicine",
        "year": 2019,
        "ev_mm": 88.0,
        "ev_ebitda": 9.2,
        "moic": 4.0,
        "irr": 0.34,
        "hold_years": 4.0,
        "sponsor": "General Atlantic",
        "payer_mix": {"medicare": 0.48, "medicaid": 0.05, "commercial": 0.30, "self_pay": 0.17},
        "geography": "Northeast",
        "ebitda_margin": 0.22,
        "revenue_mm": 52.0,
    },
]
