"""Extended seed 77: Gastroenterology and GI endoscopy PE deal corpus.

This module contains a curated list of 15 private equity healthcare deals
focused on the gastroenterology vertical, including physician practice
management groups, ambulatory endoscopy centers, colonoscopy screening
networks, liver disease specialty clinics, and IBD-focused practices.

Each deal dict contains 17 standardized keys covering company identity,
transaction economics (EV, EBITDA multiple, margin, revenue), return
profile (MOIC, IRR, hold period), payer mix, and sponsor metadata.
"""

EXTENDED_SEED_DEALS_77 = [
    {
        "company_name": "Summit GI Partners",
        "sector": "Gastroenterology",
        "subsector": "Multi-Site GI Practice Management",
        "year": 2018,
        "ev_mm": 485.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": round(485.0 / 13.5, 2),
        "revenue_mm": round(round(485.0 / 13.5, 2) / 0.24, 2),
        "ebitda_margin": 0.24,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": round(2.6 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.58, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.06},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Cascade Endoscopy Centers",
        "sector": "GI Endoscopy",
        "subsector": "Ambulatory Endoscopy Center Network",
        "year": 2019,
        "ev_mm": 310.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": round(310.0 / 12.0, 2),
        "revenue_mm": round(round(310.0 / 12.0, 2) / 0.28, 2),
        "ebitda_margin": 0.28,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": round(2.3 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.62, "medicare": 0.26, "medicaid": 0.07, "self_pay": 0.05},
        "comm_pct": 0.62,
        "region": "West",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Liberty Liver Institute",
        "sector": "Liver Disease",
        "subsector": "Hepatology Specialty Clinics",
        "year": 2020,
        "ev_mm": 175.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": round(175.0 / 14.5, 2),
        "revenue_mm": round(round(175.0 / 14.5, 2) / 0.22, 2),
        "ebitda_margin": 0.22,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": round(2.1 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.54, "medicare": 0.31, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.54,
        "region": "Southeast",
        "buyer": "Frazier Healthcare",
        "status": "Active",
    },
    {
        "company_name": "Crohn's & Colitis Care Alliance",
        "sector": "IBD",
        "subsector": "IBD Specialty Infusion and Clinics",
        "year": 2021,
        "ev_mm": 240.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": round(240.0 / 15.5, 2),
        "revenue_mm": round(round(240.0 / 15.5, 2) / 0.26, 2),
        "ebitda_margin": 0.26,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": round(1.9 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.66, "medicare": 0.22, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.66,
        "region": "Midwest",
        "buyer": "Webster Equity",
        "status": "Active",
    },
    {
        "company_name": "Heartland Colorectal Surgical Group",
        "sector": "Colorectal",
        "subsector": "Colorectal Surgery and Screening",
        "year": 2017,
        "ev_mm": 95.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": round(95.0 / 11.0, 2),
        "revenue_mm": round(round(95.0 / 11.0, 2) / 0.21, 2),
        "ebitda_margin": 0.21,
        "hold_years": 5.5,
        "moic": 2.8,
        "irr": round(2.8 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.51, "medicare": 0.34, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.51,
        "region": "Midwest",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "Pacific Digestive Health",
        "sector": "Gastroenterology",
        "subsector": "Integrated GI Practice Platform",
        "year": 2022,
        "ev_mm": 720.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": round(720.0 / 16.0, 2),
        "revenue_mm": round(round(720.0 / 16.0, 2) / 0.25, 2),
        "ebitda_margin": 0.25,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": round(1.6 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.60, "medicare": 0.27, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.60,
        "region": "West",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Atlantic Endoscopy Holdings",
        "sector": "GI Endoscopy",
        "subsector": "Endoscopy ASC Platform",
        "year": 2016,
        "ev_mm": 550.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": round(550.0 / 11.5, 2),
        "revenue_mm": round(round(550.0 / 11.5, 2) / 0.30, 2),
        "ebitda_margin": 0.30,
        "hold_years": 6.0,
        "moic": 3.4,
        "irr": round(3.4 ** (1 / 6.0) - 1, 4),
        "payer_mix": {"commercial": 0.64, "medicare": 0.24, "medicaid": 0.07, "self_pay": 0.05},
        "comm_pct": 0.64,
        "region": "Northeast",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Lone Star Colonoscopy Network",
        "sector": "Colorectal",
        "subsector": "Colonoscopy Screening Centers",
        "year": 2019,
        "ev_mm": 205.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": round(205.0 / 12.8, 2),
        "revenue_mm": round(round(205.0 / 12.8, 2) / 0.27, 2),
        "ebitda_margin": 0.27,
        "hold_years": 4.5,
        "moic": 2.4,
        "irr": round(2.4 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.57, "medicare": 0.29, "medicaid": 0.09, "self_pay": 0.05},
        "comm_pct": 0.57,
        "region": "Southeast",
        "buyer": "Harren",
        "status": "Partially Realized",
    },
    {
        "company_name": "Great Lakes Hepatology Associates",
        "sector": "Liver Disease",
        "subsector": "Hepatology and NASH Clinical Network",
        "year": 2020,
        "ev_mm": 130.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": round(130.0 / 13.2, 2),
        "revenue_mm": round(round(130.0 / 13.2, 2) / 0.20, 2),
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 2.0,
        "irr": round(2.0 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.50, "medicare": 0.32, "medicaid": 0.12, "self_pay": 0.06},
        "comm_pct": 0.50,
        "region": "Midwest",
        "buyer": "Sterling Partners",
        "status": "Active",
    },
    {
        "company_name": "Rocky Mountain IBD Specialists",
        "sector": "IBD",
        "subsector": "IBD and Autoimmune GI Clinics",
        "year": 2021,
        "ev_mm": 165.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": round(165.0 / 14.0, 2),
        "revenue_mm": round(round(165.0 / 14.0, 2) / 0.23, 2),
        "ebitda_margin": 0.23,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": round(1.8 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.63, "medicare": 0.24, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.63,
        "region": "West",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Gulf Coast Gastroenterology",
        "sector": "Gastroenterology",
        "subsector": "Regional GI Physician Practice",
        "year": 2017,
        "ev_mm": 82.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": round(82.0 / 10.5, 2),
        "revenue_mm": round(round(82.0 / 10.5, 2) / 0.19, 2),
        "ebitda_margin": 0.19,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": round(2.5 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.49, "medicare": 0.33, "medicaid": 0.12, "self_pay": 0.06},
        "comm_pct": 0.49,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Empire State Endoscopy Partners",
        "sector": "GI Endoscopy",
        "subsector": "Urban Endoscopy Center Rollup",
        "year": 2023,
        "ev_mm": 395.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": round(395.0 / 15.8, 2),
        "revenue_mm": round(round(395.0 / 15.8, 2) / 0.29, 2),
        "ebitda_margin": 0.29,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": round(1.5 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.67, "medicare": 0.22, "medicaid": 0.07, "self_pay": 0.04},
        "comm_pct": 0.67,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Active",
    },
    {
        "company_name": "National Digestive Care Alliance",
        "sector": "Gastroenterology",
        "subsector": "National GI MSO Platform",
        "year": 2022,
        "ev_mm": 1050.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": round(1050.0 / 17.5, 2),
        "revenue_mm": round(round(1050.0 / 17.5, 2) / 0.26, 2),
        "ebitda_margin": 0.26,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": round(1.7 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.61, "medicare": 0.26, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.61,
        "region": "National",
        "buyer": "KKR",
        "status": "Active",
    },
    {
        "company_name": "Southern Liver & Transplant Care",
        "sector": "Liver Disease",
        "subsector": "Advanced Liver Disease and Transplant Support",
        "year": 2018,
        "ev_mm": 220.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": round(220.0 / 13.8, 2),
        "revenue_mm": round(round(220.0 / 13.8, 2) / 0.21, 2),
        "ebitda_margin": 0.21,
        "hold_years": 5.5,
        "moic": 3.0,
        "irr": round(3.0 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.53, "medicare": 0.30, "medicaid": 0.11, "self_pay": 0.06},
        "comm_pct": 0.53,
        "region": "Southeast",
        "buyer": "Frazier Healthcare",
        "status": "Realized",
    },
    {
        "company_name": "Midwest Colorectal Care Group",
        "sector": "Colorectal",
        "subsector": "Colorectal Surgical and Screening Platform",
        "year": 2024,
        "ev_mm": 68.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": round(68.0 / 18.5, 2),
        "revenue_mm": round(round(68.0 / 18.5, 2) / 0.32, 2),
        "ebitda_margin": 0.32,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": round(1.4 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.59, "medicare": 0.28, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.59,
        "region": "Midwest",
        "buyer": "Silversmith",
        "status": "Active",
    },
]
