"""Extended seed 79: Vision care and eye care PE deals.

This module contains a curated set of 15 healthcare private equity deal
records focused on the vision and eye care services landscape. The theme
covers:

- Optometry practice rollups and regional chains
- Eyewear retail platforms (frames, sunglasses, specialty)
- Contact lens direct-to-consumer and subscription platforms
- Vision insurance and managed vision care
- LASIK and refractive surgery networks

Vision care is characterized by self-pay-heavy economics (elective
procedures, retail eyewear, DTC lenses) relative to other healthcare
subsectors, and commercial vision-plan coverage rather than traditional
medical insurance. Payer mixes reflect this reality.

Each record captures deal economics (EV, EV/EBITDA, margins), return
profile (MOIC, IRR, hold period), payer mix, regional footprint, sponsor,
and realization status. These records are synthesized for modeling,
backtesting, and scenario analysis use cases.
"""

EXTENDED_SEED_DEALS_79 = [
    {
        "company_name": "ClearVue Optometry Partners",
        "sector": "Optometry",
        "subsector": "Optometry Practice Rollup",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 33.6,
        "revenue_mm": 168.0,
        "ebitda_margin": 0.20,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.45, "medicare": 0.15, "medicaid": 0.05, "self_pay": 0.35},
        "comm_pct": 0.45,
        "region": "Midwest",
        "buyer": "Altas Partners",
        "status": "Realized",
    },
    {
        "company_name": "BrightLens Eyewear Group",
        "sector": "Eyewear Retail",
        "subsector": "Specialty Optical Retail",
        "year": 2019,
        "ev_mm": 275.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 20.83,
        "revenue_mm": 130.19,
        "ebitda_margin": 0.16,
        "hold_years": 4.5,
        "moic": 2.2,
        "irr": 0.1915,
        "payer_mix": {"commercial": 0.30, "medicare": 0.05, "medicaid": 0.02, "self_pay": 0.63},
        "comm_pct": 0.30,
        "region": "Northeast",
        "buyer": "L Catterton",
        "status": "Active",
    },
    {
        "company_name": "LensLoop Subscription Co",
        "sector": "Contact Lens",
        "subsector": "DTC Contact Lens Subscription",
        "year": 2020,
        "ev_mm": 180.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 11.61,
        "revenue_mm": 82.99,
        "ebitda_margin": 0.1399,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.25, "medicare": 0.02, "medicaid": 0.01, "self_pay": 0.72},
        "comm_pct": 0.25,
        "region": "National",
        "buyer": "Warburg",
        "status": "Active",
    },
    {
        "company_name": "VisionShield Managed Care",
        "sector": "Vision Care",
        "subsector": "Managed Vision Insurance",
        "year": 2017,
        "ev_mm": 650.0,
        "ev_ebitda": 14.8,
        "ebitda_mm": 43.92,
        "revenue_mm": 195.20,
        "ebitda_margin": 0.225,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": 0.2075,
        "payer_mix": {"commercial": 0.72, "medicare": 0.10, "medicaid": 0.08, "self_pay": 0.10},
        "comm_pct": 0.72,
        "region": "National",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "FocalPoint LASIK Centers",
        "sector": "LASIK",
        "subsector": "Refractive Surgery Network",
        "year": 2018,
        "ev_mm": 210.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 18.26,
        "revenue_mm": 91.30,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 2.4,
        "irr": 0.1725,
        "payer_mix": {"commercial": 0.08, "medicare": 0.02, "medicaid": 0.01, "self_pay": 0.89},
        "comm_pct": 0.08,
        "region": "West",
        "buyer": "Shore Capital",
        "status": "Partially Realized",
    },
    {
        "company_name": "Sunrise Optical Holdings",
        "sector": "Eyewear Retail",
        "subsector": "Mass-market Optical Chain",
        "year": 2016,
        "ev_mm": 540.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 45.76,
        "revenue_mm": 261.49,
        "ebitda_margin": 0.175,
        "hold_years": 6.5,
        "moic": 2.8,
        "irr": 0.1716,
        "payer_mix": {"commercial": 0.35, "medicare": 0.08, "medicaid": 0.03, "self_pay": 0.54},
        "comm_pct": 0.35,
        "region": "Southeast",
        "buyer": "Leonard Green",
        "status": "Realized",
    },
    {
        "company_name": "Panoramic Eye Care MSO",
        "sector": "Optometry",
        "subsector": "Integrated Optometry MSO",
        "year": 2020,
        "ev_mm": 365.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 28.08,
        "revenue_mm": 132.45,
        "ebitda_margin": 0.2120,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.50, "medicare": 0.18, "medicaid": 0.07, "self_pay": 0.25},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "Audax",
        "status": "Active",
    },
    {
        "company_name": "CrystalView Contacts Direct",
        "sector": "Contact Lens",
        "subsector": "Contact Lens eCommerce",
        "year": 2021,
        "ev_mm": 95.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 5.76,
        "revenue_mm": 41.14,
        "ebitda_margin": 0.14,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.18, "medicare": 0.01, "medicaid": 0.01, "self_pay": 0.80},
        "comm_pct": 0.18,
        "region": "National",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "EagleEye Refractive Group",
        "sector": "LASIK",
        "subsector": "Premium Refractive Surgery",
        "year": 2019,
        "ev_mm": 155.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 12.92,
        "revenue_mm": 59.46,
        "ebitda_margin": 0.2173,
        "hold_years": 4.5,
        "moic": 2.0,
        "irr": 0.1665,
        "payer_mix": {"commercial": 0.10, "medicare": 0.03, "medicaid": 0.02, "self_pay": 0.85},
        "comm_pct": 0.10,
        "region": "West",
        "buyer": "Webster",
        "status": "Partially Realized",
    },
    {
        "company_name": "HorizonSight Vision Benefits",
        "sector": "Vision Care",
        "subsector": "Vision Benefits Administration",
        "year": 2017,
        "ev_mm": 780.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": 49.37,
        "revenue_mm": 201.51,
        "ebitda_margin": 0.245,
        "hold_years": 5.5,
        "moic": 3.0,
        "irr": 0.2211,
        "payer_mix": {"commercial": 0.78, "medicare": 0.09, "medicaid": 0.06, "self_pay": 0.07},
        "comm_pct": 0.78,
        "region": "National",
        "buyer": "Bain Capital",
        "status": "Realized",
    },
    {
        "company_name": "Cascade Optometry Network",
        "sector": "Optometry",
        "subsector": "Regional Optometry Platform",
        "year": 2021,
        "ev_mm": 240.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 18.75,
        "revenue_mm": 96.15,
        "ebitda_margin": 0.195,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.48, "medicare": 0.14, "medicaid": 0.06, "self_pay": 0.32},
        "comm_pct": 0.48,
        "region": "West",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "FrameCraft Premium Eyewear",
        "sector": "Eyewear Retail",
        "subsector": "Luxury Eyewear Retail",
        "year": 2022,
        "ev_mm": 130.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 8.97,
        "revenue_mm": 49.83,
        "ebitda_margin": 0.18,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.22, "medicare": 0.03, "medicaid": 0.01, "self_pay": 0.74},
        "comm_pct": 0.22,
        "region": "Northeast",
        "buyer": "L Catterton",
        "status": "Active",
    },
    {
        "company_name": "OptiCore Eye Health Platform",
        "sector": "Vision Care",
        "subsector": "Integrated Vision Services",
        "year": 2018,
        "ev_mm": 460.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 34.07,
        "revenue_mm": 170.35,
        "ebitda_margin": 0.20,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.55, "medicare": 0.18, "medicaid": 0.07, "self_pay": 0.20},
        "comm_pct": 0.55,
        "region": "Midwest",
        "buyer": "Warburg",
        "status": "Realized",
    },
    {
        "company_name": "TrueLens Subscription Health",
        "sector": "Contact Lens",
        "subsector": "Telehealth Contact Lens Platform",
        "year": 2022,
        "ev_mm": 75.0,
        "ev_ebitda": 17.0,
        "ebitda_mm": 4.41,
        "revenue_mm": 36.75,
        "ebitda_margin": 0.12,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.20, "medicare": 0.01, "medicaid": 0.01, "self_pay": 0.78},
        "comm_pct": 0.20,
        "region": "National",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Summit LASIK & Refractive",
        "sector": "LASIK",
        "subsector": "LASIK Center Rollup",
        "year": 2017,
        "ev_mm": 300.0,
        "ev_ebitda": 11.2,
        "ebitda_mm": 26.79,
        "revenue_mm": 121.77,
        "ebitda_margin": 0.22,
        "hold_years": 6.0,
        "moic": 2.9,
        "irr": 0.1942,
        "payer_mix": {"commercial": 0.12, "medicare": 0.04, "medicaid": 0.02, "self_pay": 0.82},
        "comm_pct": 0.12,
        "region": "Southeast",
        "buyer": "Audax",
        "status": "Realized",
    },
]
