"""Extended seed batch 55 — hospital and health system PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_55: list[dict] = [
    {
        "source_id": "ext55_001",
        "company_name": "Keystone Physician Partners",
        "sector": "hospital-based physician group",
        "year": 2016,
        "ev_mm": 320.0,
        "ev_ebitda": 9.5,
        "moic": 2.9,
        "irr": 0.24,
        "hold_years": 5.0,
        "sponsor": "Welsh, Carson, Anderson & Stowe",
        "payer_mix": {
            "commercial": 0.45,
            "medicare": 0.33,
            "medicaid": 0.17,
            "self_pay": 0.05,
        },
        "geography": "Pennsylvania",
        "ebitda_margin": 0.12,
        "revenue_mm": 280.7,
    },
    {
        "source_id": "ext55_002",
        "company_name": "Meridian Health Alliance",
        "sector": "integrated delivery network",
        "year": 2014,
        "ev_mm": 950.0,
        "ev_ebitda": 10.2,
        "moic": 2.5,
        "irr": 0.20,
        "hold_years": 5.5,
        "sponsor": "KKR",
        "payer_mix": {
            "commercial": 0.40,
            "medicare": 0.36,
            "medicaid": 0.20,
            "self_pay": 0.04,
        },
        "geography": "Ohio",
        "ebitda_margin": 0.09,
        "revenue_mm": 1033.7,
    },
    {
        "source_id": "ext55_003",
        "company_name": "Continuum Care Management Group",
        "sector": "accountable care organization management company",
        "year": 2018,
        "ev_mm": 195.0,
        "ev_ebitda": 8.5,
        "moic": 3.2,
        "irr": 0.28,
        "hold_years": 4.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {
            "commercial": 0.38,
            "medicare": 0.40,
            "medicaid": 0.18,
            "self_pay": 0.04,
        },
        "geography": "Illinois",
        "ebitda_margin": 0.14,
        "revenue_mm": 163.9,
    },
    {
        "source_id": "ext55_004",
        "company_name": "BluePine Regional Health",
        "sector": "regional hospital system",
        "year": 2015,
        "ev_mm": 780.0,
        "ev_ebitda": 9.8,
        "moic": 2.7,
        "irr": 0.22,
        "hold_years": 5.0,
        "sponsor": "Apollo Global Management",
        "payer_mix": {
            "commercial": 0.42,
            "medicare": 0.35,
            "medicaid": 0.18,
            "self_pay": 0.05,
        },
        "geography": "Tennessee",
        "ebitda_margin": 0.10,
        "revenue_mm": 795.9,
    },
    {
        "source_id": "ext55_005",
        "company_name": "Prairie Valley Critical Access System",
        "sector": "critical access hospital",
        "year": 2019,
        "ev_mm": 85.0,
        "ev_ebitda": 7.5,
        "moic": 2.4,
        "irr": 0.19,
        "hold_years": 4.5,
        "sponsor": "Vistria Group",
        "payer_mix": {
            "commercial": 0.35,
            "medicare": 0.38,
            "medicaid": 0.22,
            "self_pay": 0.05,
        },
        "geography": "Iowa",
        "ebitda_margin": 0.08,
        "revenue_mm": 141.7,
    },
    {
        "source_id": "ext55_006",
        "company_name": "Horizon Community Health Network",
        "sector": "community health center network",
        "year": 2017,
        "ev_mm": 155.0,
        "ev_ebitda": 8.0,
        "moic": 2.8,
        "irr": 0.23,
        "hold_years": 5.0,
        "sponsor": "New Mountain Capital",
        "payer_mix": {
            "commercial": 0.28,
            "medicare": 0.30,
            "medicaid": 0.35,
            "self_pay": 0.07,
        },
        "geography": "Georgia",
        "ebitda_margin": 0.11,
        "revenue_mm": 176.1,
    },
    {
        "source_id": "ext55_007",
        "company_name": "Cornerstone FQHC Holdings",
        "sector": "federally qualified health center",
        "year": 2020,
        "ev_mm": 120.0,
        "ev_ebitda": 7.8,
        "moic": 2.3,
        "irr": 0.18,
        "hold_years": 5.5,
        "sponsor": "General Atlantic",
        "payer_mix": {
            "commercial": 0.22,
            "medicare": 0.28,
            "medicaid": 0.40,
            "self_pay": 0.10,
        },
        "geography": "Texas",
        "ebitda_margin": 0.09,
        "revenue_mm": 171.8,
    },
    {
        "source_id": "ext55_008",
        "company_name": "Heartland Rural Health Clinics",
        "sector": "rural health clinic",
        "year": 2016,
        "ev_mm": 95.0,
        "ev_ebitda": 7.2,
        "moic": 2.6,
        "irr": 0.21,
        "hold_years": 4.5,
        "sponsor": "Shore Capital Partners",
        "payer_mix": {
            "commercial": 0.30,
            "medicare": 0.37,
            "medicaid": 0.27,
            "self_pay": 0.06,
        },
        "geography": "Missouri",
        "ebitda_margin": 0.10,
        "revenue_mm": 131.9,
    },
    {
        "source_id": "ext55_009",
        "company_name": "Anchor Safety-Net Hospitals",
        "sector": "safety-net hospital",
        "year": 2013,
        "ev_mm": 430.0,
        "ev_ebitda": 9.0,
        "moic": 2.2,
        "irr": 0.17,
        "hold_years": 6.0,
        "sponsor": "Cerberus Capital Management",
        "payer_mix": {
            "commercial": 0.25,
            "medicare": 0.32,
            "medicaid": 0.36,
            "self_pay": 0.07,
        },
        "geography": "New York",
        "ebitda_margin": 0.07,
        "revenue_mm": 682.5,
    },
    {
        "source_id": "ext55_010",
        "company_name": "Metropolitan Public Health System",
        "sector": "public hospital system",
        "year": 2015,
        "ev_mm": 1150.0,
        "ev_ebitda": 11.5,
        "moic": 2.1,
        "irr": 0.16,
        "hold_years": 7.0,
        "sponsor": "Blackstone",
        "payer_mix": {
            "commercial": 0.30,
            "medicare": 0.34,
            "medicaid": 0.30,
            "self_pay": 0.06,
        },
        "geography": "California",
        "ebitda_margin": 0.08,
        "revenue_mm": 1258.2,
    },
    {
        "source_id": "ext55_011",
        "company_name": "Summit Academic Physician Group",
        "sector": "academic medical group",
        "year": 2018,
        "ev_mm": 560.0,
        "ev_ebitda": 10.5,
        "moic": 3.0,
        "irr": 0.26,
        "hold_years": 5.0,
        "sponsor": "Ares Management",
        "payer_mix": {
            "commercial": 0.48,
            "medicare": 0.32,
            "medicaid": 0.16,
            "self_pay": 0.04,
        },
        "geography": "Massachusetts",
        "ebitda_margin": 0.13,
        "revenue_mm": 411.4,
    },
    {
        "source_id": "ext55_012",
        "company_name": "Lakewood Faculty Practice Partners",
        "sector": "faculty practice plan",
        "year": 2017,
        "ev_mm": 245.0,
        "ev_ebitda": 8.8,
        "moic": 3.1,
        "irr": 0.27,
        "hold_years": 4.5,
        "sponsor": "CCMP Capital Advisors",
        "payer_mix": {
            "commercial": 0.50,
            "medicare": 0.31,
            "medicaid": 0.15,
            "self_pay": 0.04,
        },
        "geography": "Michigan",
        "ebitda_margin": 0.15,
        "revenue_mm": 186.0,
    },
    {
        "source_id": "ext55_013",
        "company_name": "Crestview University Hospital Holdings",
        "sector": "university hospital system",
        "year": 2021,
        "ev_mm": 1100.0,
        "ev_ebitda": 11.8,
        "moic": 2.0,
        "irr": 0.15,
        "hold_years": 7.5,
        "sponsor": "Carlyle Group",
        "payer_mix": {
            "commercial": 0.44,
            "medicare": 0.34,
            "medicaid": 0.17,
            "self_pay": 0.05,
        },
        "geography": "North Carolina",
        "ebitda_margin": 0.10,
        "revenue_mm": 932.2,
    },
    {
        "source_id": "ext55_014",
        "company_name": "Pinnacle Joint Venture Health Partners",
        "sector": "joint venture hospital",
        "year": 2019,
        "ev_mm": 380.0,
        "ev_ebitda": 9.2,
        "moic": 3.5,
        "irr": 0.30,
        "hold_years": 4.0,
        "sponsor": "TPG Capital",
        "payer_mix": {
            "commercial": 0.46,
            "medicare": 0.33,
            "medicaid": 0.16,
            "self_pay": 0.05,
        },
        "geography": "Florida",
        "ebitda_margin": 0.14,
        "revenue_mm": 294.3,
    },
    {
        "source_id": "ext55_015",
        "company_name": "Apex Specialty Hospital Group",
        "sector": "specialty hospital",
        "year": 2022,
        "ev_mm": 480.0,
        "ev_ebitda": 11.0,
        "moic": 3.8,
        "irr": 0.32,
        "hold_years": 4.0,
        "sponsor": "Leonard Green & Partners",
        "payer_mix": {
            "commercial": 0.52,
            "medicare": 0.30,
            "medicaid": 0.14,
            "self_pay": 0.04,
        },
        "geography": "Arizona",
        "ebitda_margin": 0.16,
        "revenue_mm": 272.7,
    },
]
