"""Extended seed deals #71: endocrinology, diabetes, obesity, HRT, thyroid specialty."""

EXTENDED_SEED_DEALS_71 = [
    {
        "company_name": "Meridian Endocrine Partners",
        "sector": "Endocrinology",
        "subsector": "Adult Endocrinology Clinics",
        "year": 2019,
        "ev_mm": 185.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 14.8,
        "revenue_mm": 77.89,
        "ebitda_margin": 0.19,
        "hold_years": 4.5,
        "moic": 2.6,
        "irr": 0.2425,
        "payer_mix": {"commercial": 0.58, "medicare": 0.27, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "GlucoCare Management Group",
        "sector": "Diabetes Care",
        "subsector": "Diabetes Education & CGM Services",
        "year": 2020,
        "ev_mm": 310.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 22.14,
        "revenue_mm": 100.64,
        "ebitda_margin": 0.22,
        "hold_years": 5.0,
        "moic": 3.1,
        "irr": 0.2527,
        "payer_mix": {"commercial": 0.52, "medicare": 0.33, "medicaid": 0.11, "self_pay": 0.04},
        "comm_pct": 0.52,
        "region": "Southeast",
        "buyer": "Oak HC/FT",
        "status": "Active",
    },
    {
        "company_name": "BariWell Obesity Centers",
        "sector": "Obesity Medicine",
        "subsector": "Medical Weight Loss Clinics",
        "year": 2021,
        "ev_mm": 140.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 12.17,
        "revenue_mm": 50.71,
        "ebitda_margin": 0.24,
        "hold_years": 3.5,
        "moic": 2.2,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.42, "medicare": 0.08, "medicaid": 0.05, "self_pay": 0.45},
        "comm_pct": 0.42,
        "region": "West",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "Vitality Hormone Institute",
        "sector": "Hormone Therapy",
        "subsector": "Men's Health & TRT Clinics",
        "year": 2022,
        "ev_mm": 95.0,
        "ev_ebitda": 10.8,
        "ebitda_mm": 8.8,
        "revenue_mm": 41.9,
        "ebitda_margin": 0.21,
        "hold_years": 3.0,
        "moic": 1.9,
        "irr": 0.2383,
        "payer_mix": {"commercial": 0.32, "medicare": 0.05, "medicaid": 0.02, "self_pay": 0.61},
        "comm_pct": 0.32,
        "region": "Southeast",
        "buyer": "Silversmith Capital",
        "status": "Active",
    },
    {
        "company_name": "ThyroHealth Specialists",
        "sector": "Thyroid Specialty",
        "subsector": "Thyroid Surgery & Biopsy Centers",
        "year": 2018,
        "ev_mm": 220.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 16.67,
        "revenue_mm": 83.35,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2097,
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.55,
        "region": "Midwest",
        "buyer": "Frazier Healthcare",
        "status": "Realized",
    },
    {
        "company_name": "MetaboPath Clinics",
        "sector": "Metabolic Care",
        "subsector": "Comprehensive Metabolic Disease",
        "year": 2021,
        "ev_mm": 430.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 27.74,
        "revenue_mm": 123.29,
        "ebitda_margin": 0.225,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.60, "medicare": 0.24, "medicaid": 0.12, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "Revelstoke Capital",
        "status": "Partially Realized",
    },
    {
        "company_name": "Summit Diabetes Network",
        "sector": "Diabetes Care",
        "subsector": "Type 1 & Type 2 Management",
        "year": 2017,
        "ev_mm": 275.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 19.93,
        "revenue_mm": 110.72,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 3.3,
        "irr": 0.2197,
        "payer_mix": {"commercial": 0.50, "medicare": 0.35, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.50,
        "region": "Northeast",
        "buyer": "Audax Group",
        "status": "Realized",
    },
    {
        "company_name": "Cascade Endocrinology Associates",
        "sector": "Endocrinology",
        "subsector": "Pediatric Endocrinology",
        "year": 2020,
        "ev_mm": 115.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 9.75,
        "revenue_mm": 56.69,
        "ebitda_margin": 0.172,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2029,
        "payer_mix": {"commercial": 0.48, "medicare": 0.10, "medicaid": 0.38, "self_pay": 0.04},
        "comm_pct": 0.48,
        "region": "West",
        "buyer": "Harren Equity",
        "status": "Active",
    },
    {
        "company_name": "Lean Path Medical Weight",
        "sector": "Obesity Medicine",
        "subsector": "GLP-1 Telehealth Platform",
        "year": 2023,
        "ev_mm": 560.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 32.0,
        "revenue_mm": 123.08,
        "ebitda_margin": 0.26,
        "hold_years": 2.5,
        "moic": 1.7,
        "irr": 0.2365,
        "payer_mix": {"commercial": 0.38, "medicare": 0.04, "medicaid": 0.03, "self_pay": 0.55},
        "comm_pct": 0.38,
        "region": "National",
        "buyer": "Webster Equity",
        "status": "Active",
    },
    {
        "company_name": "Renew Hormone Clinics",
        "sector": "Hormone Therapy",
        "subsector": "Women's Menopause & BHRT",
        "year": 2019,
        "ev_mm": 72.0,
        "ev_ebitda": 10.2,
        "ebitda_mm": 7.06,
        "revenue_mm": 36.96,
        "ebitda_margin": 0.191,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.30, "medicare": 0.06, "medicaid": 0.02, "self_pay": 0.62},
        "comm_pct": 0.30,
        "region": "Southeast",
        "buyer": "Cressey & Company",
        "status": "Realized",
    },
    {
        "company_name": "Apex Thyroid & Parathyroid",
        "sector": "Thyroid Specialty",
        "subsector": "Thyroid Cancer Surveillance",
        "year": 2022,
        "ev_mm": 165.0,
        "ev_ebitda": 12.9,
        "ebitda_mm": 12.79,
        "revenue_mm": 58.14,
        "ebitda_margin": 0.22,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": 0.2164,
        "payer_mix": {"commercial": 0.57, "medicare": 0.28, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.57,
        "region": "Midwest",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "Heartland Endocrine Partners",
        "sector": "Endocrinology",
        "subsector": "MSO Endocrine Platform",
        "year": 2016,
        "ev_mm": 390.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 26.9,
        "revenue_mm": 128.1,
        "ebitda_margin": 0.21,
        "hold_years": 6.5,
        "moic": 3.6,
        "irr": 0.2150,
        "payer_mix": {"commercial": 0.54, "medicare": 0.30, "medicaid": 0.13, "self_pay": 0.03},
        "comm_pct": 0.54,
        "region": "Midwest",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "InsulinRx Diabetes Services",
        "sector": "Diabetes Care",
        "subsector": "Insulin Pump & Supply Management",
        "year": 2023,
        "ev_mm": 225.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 17.31,
        "revenue_mm": 72.13,
        "ebitda_margin": 0.24,
        "hold_years": 3.5,
        "moic": 2.0,
        "irr": 0.2140,
        "payer_mix": {"commercial": 0.51, "medicare": 0.32, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.51,
        "region": "West",
        "buyer": "Frazier Healthcare",
        "status": "Active",
    },
    {
        "company_name": "TotalMetabolic Health",
        "sector": "Metabolic Care",
        "subsector": "PCOS & Metabolic Syndrome",
        "year": 2024,
        "ev_mm": 88.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 8.0,
        "revenue_mm": 44.44,
        "ebitda_margin": 0.18,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": 0.1447,
        "payer_mix": {"commercial": 0.46, "medicare": 0.12, "medicaid": 0.15, "self_pay": 0.27},
        "comm_pct": 0.46,
        "region": "Southeast",
        "buyer": "Silversmith Capital",
        "status": "Active",
    },
    {
        "company_name": "Horizon Bariatric Group",
        "sector": "Obesity Medicine",
        "subsector": "Surgical Bariatric Centers",
        "year": 2018,
        "ev_mm": 680.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 41.21,
        "revenue_mm": 164.84,
        "ebitda_margin": 0.25,
        "hold_years": 5.5,
        "moic": 2.7,
        "irr": 0.1941,
        "payer_mix": {"commercial": 0.62, "medicare": 0.20, "medicaid": 0.10, "self_pay": 0.08},
        "comm_pct": 0.62,
        "region": "National",
        "buyer": "Audax Group",
        "status": "Partially Realized",
    },
]
