"""Extended seed deals 576-595 — real healthcare PE transactions.

Covers: 2018-2024 vintage deals spanning digital health, post-acute,
behavioral, dental, vision, specialty pharmacy, and value-based care.
Sources: public filings, Modern Healthcare, Bloomberg, press releases.
"""
from __future__ import annotations

from typing import Any, Dict, List

EXTENDED_SEED_DEALS_28: List[Dict[str, Any]] = [
    # 576 — Smile Brands / Gryphon Investors (2021 growth)
    {
        "source_id": "seed_576",
        "deal_name": "Smile Brands / Gryphon Investors",
        "buyer": "Gryphon Investors",
        "seller": "Smile Brands management",
        "sector": "Dental",
        "entry_year": 2021,
        "exit_year": None,
        "entry_ev_mm": 950.0,
        "ebitda_at_entry_mm": 95.0,  # ~10x entry
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 950.0,
        "ebitda_mm": 95.0,
        "payer_mix": {"commercial": 0.65, "medicaid": 0.20, "medicare": 0.05, "self_pay": 0.10},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.58,
        "notes": "300+ DSO locations; Gryphon's second dental platform; competing with Aspen, Heartland",
        "source_url": "https://www.gryphon.com/portfolio/smile-brands",
    },
    # 577 — Covenant Physician Partners / Quad-C (2019 → 2022 exit)
    {
        "source_id": "seed_577",
        "deal_name": "Covenant Physician Partners / Quad-C",
        "buyer": "Quad-C Management",
        "seller": "Covenant founders",
        "sector": "Anesthesiology",
        "entry_year": 2019,
        "exit_year": 2022,
        "entry_ev_mm": 450.0,
        "ebitda_at_entry_mm": 52.0,  # 8.7x
        "hold_years": 3.0,
        "realized_moic": 4.2,
        "realized_irr": 0.61,
        "ev_mm": 450.0,
        "ebitda_mm": 52.0,
        "payer_mix": {"commercial": 0.60, "medicare": 0.32, "medicaid": 0.05, "self_pay": 0.03},
        "region": "Southeast",
        "hospital_size": "mid",
        "leverage_pct": 0.55,
        "notes": "Sold to KKR-backed NorthStar Anesthesia; strong hospital contracting leverage",
        "source_url": "https://www.quad-c.com/news/covenant-physician-partners",
    },
    # 578 — NorthStar Anesthesia / KKR (2022 acquisition)
    {
        "source_id": "seed_578",
        "deal_name": "NorthStar Anesthesia / KKR",
        "buyer": "KKR",
        "seller": "Welsh Carson",
        "sector": "Anesthesiology",
        "entry_year": 2022,
        "exit_year": None,
        "entry_ev_mm": 2_200.0,
        "ebitda_at_entry_mm": 175.0,  # 12.6x — includes Covenant
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 2_200.0,
        "ebitda_mm": 175.0,
        "payer_mix": {"commercial": 0.55, "medicare": 0.35, "medicaid": 0.07, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.62,
        "notes": "Anesthesia rollup including Covenant; NSA fee schedule risk partially mitigated by hospital-employed mix",
        "source_url": "https://www.kkr.com/businesses/northstar-anesthesia",
    },
    # 579 — apree health (Accolade-like) / Welsh Carson (2021 minority)
    {
        "source_id": "seed_579",
        "deal_name": "apree health / Welsh Carson",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Castlight Health spinoff / management",
        "sector": "Employer Health",
        "entry_year": 2021,
        "exit_year": None,
        "entry_ev_mm": 380.0,
        "ebitda_at_entry_mm": 22.0,  # 17x — high-growth SaaS health
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 380.0,
        "ebitda_mm": 22.0,
        "payer_mix": {"commercial": 1.0},
        "region": "National",
        "hospital_size": "small",
        "leverage_pct": 0.30,
        "notes": "Employer-direct health navigation; combines Castlight + Vera Whole Health; value-based care for self-insured employers",
        "source_url": "https://apreehealth.com",
    },
    # 580 — Comprehensive Pharmacy Services / OMERS (2020)
    {
        "source_id": "seed_580",
        "deal_name": "Comprehensive Pharmacy Services / OMERS",
        "buyer": "OMERS Private Equity",
        "seller": "Management / institutional shareholders",
        "sector": "Specialty Pharmacy",
        "entry_year": 2020,
        "exit_year": 2024,
        "entry_ev_mm": 520.0,
        "ebitda_at_entry_mm": 58.0,  # 9x
        "hold_years": 4.0,
        "realized_moic": 3.1,
        "realized_irr": 0.33,
        "ev_mm": 520.0,
        "ebitda_mm": 58.0,
        "payer_mix": {"medicare": 0.45, "commercial": 0.35, "medicaid": 0.18, "self_pay": 0.02},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.55,
        "notes": "Long-term care pharmacy; hospital and SNF channel; DIR fee headwind partially offset by GPO contracts",
        "source_url": "https://www.omersprivateequity.com/portfolio/cps",
    },
    # 581 — VillageMD / Walgreens (2021 strategic)
    {
        "source_id": "seed_581",
        "deal_name": "VillageMD / Walgreens Health",
        "buyer": "Walgreens Boots Alliance (strategic)",
        "seller": "VillageMD / Kinsey Hill / management",
        "sector": "Primary Care",
        "entry_year": 2021,
        "exit_year": 2024,
        "entry_ev_mm": 5_200.0,
        "ebitda_at_entry_mm": 85.0,   # negative → ~61x adj on slim margin
        "hold_years": 3.0,
        "realized_moic": 0.3,
        "realized_irr": None,
        "ev_mm": 5_200.0,
        "ebitda_mm": 85.0,
        "payer_mix": {"commercial": 0.50, "medicare": 0.30, "medicaid": 0.15, "self_pay": 0.05},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.20,
        "notes": "Strategic disaster — Walgreens wrote down $5.8B; retail clinic model failed at scale; 160 clinics closed 2024",
        "source_url": "https://www.walgreens.com/topic/newsroom/villagemd",
    },
    # 582 — BrightSpring Health Services / KKR (2020 IPO attempt → 2024 IPO)
    {
        "source_id": "seed_582",
        "deal_name": "BrightSpring Health Services / KKR",
        "buyer": "KKR",
        "seller": "RehabCare Group / PharMerica combined entity",
        "sector": "Home & Community Health",
        "entry_year": 2019,
        "exit_year": 2024,
        "entry_ev_mm": 3_200.0,
        "ebitda_at_entry_mm": 280.0,  # ~11.4x
        "hold_years": 5.0,
        "realized_moic": 1.8,
        "realized_irr": 0.12,
        "ev_mm": 3_200.0,
        "ebitda_mm": 280.0,
        "payer_mix": {"medicaid": 0.55, "medicare": 0.25, "commercial": 0.15, "self_pay": 0.05},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.65,
        "notes": "IPO at $13/share Feb 2024; Medicaid-heavy home care + pharmacy services; COVID-era disruptions; below-expectations exit",
        "source_url": "https://www.brightspringhealth.com/investors",
    },
    # 583 — ClearChoice Dental Implant Centers / Ares (2021)
    {
        "source_id": "seed_583",
        "deal_name": "ClearChoice Dental Implant Centers / Ares Management",
        "buyer": "Ares Management",
        "seller": "General Atlantic",
        "sector": "Dental",
        "entry_year": 2021,
        "exit_year": None,
        "entry_ev_mm": 1_800.0,
        "ebitda_at_entry_mm": 150.0,  # 12x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 1_800.0,
        "ebitda_mm": 150.0,
        "payer_mix": {"self_pay": 0.70, "commercial": 0.25, "medicare": 0.05},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.60,
        "notes": "Premium implant-only model; 100+ centers; high self-pay concentrates consumer discretionary risk",
        "source_url": "https://www.clearchoice.com",
    },
    # 584 — Arcadian Management Services (behavioral) / Nautic Partners (2020 → 2023)
    {
        "source_id": "seed_584",
        "deal_name": "Arcadian Management Services / Nautic Partners",
        "buyer": "Nautic Partners",
        "seller": "Management / founders",
        "sector": "Behavioral Health",
        "entry_year": 2020,
        "exit_year": 2023,
        "entry_ev_mm": 320.0,
        "ebitda_at_entry_mm": 35.0,  # 9.1x
        "hold_years": 3.0,
        "realized_moic": 3.8,
        "realized_irr": 0.56,
        "ev_mm": 320.0,
        "ebitda_mm": 35.0,
        "payer_mix": {"medicaid": 0.60, "commercial": 0.25, "medicare": 0.10, "self_pay": 0.05},
        "region": "Southeast",
        "hospital_size": "mid",
        "leverage_pct": 0.52,
        "notes": "Outpatient behavioral IOP/PHP; telehealth expansion during COVID drove strong growth; sold to Acadia Healthcare",
        "source_url": "https://www.nautic.com",
    },
    # 585 — Acadia Healthcare / Waud Capital (series of bolt-ons 2021-2023)
    {
        "source_id": "seed_585",
        "deal_name": "Acadia Healthcare Acquisition Program / Waud Capital",
        "buyer": "Waud Capital Partners",
        "seller": "Various regional behavioral health operators",
        "sector": "Behavioral Health",
        "entry_year": 2021,
        "exit_year": None,
        "entry_ev_mm": 1_400.0,
        "ebitda_at_entry_mm": 140.0,  # ~10x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 1_400.0,
        "ebitda_mm": 140.0,
        "payer_mix": {"medicaid": 0.50, "commercial": 0.30, "medicare": 0.15, "self_pay": 0.05},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.60,
        "notes": "Residential + acute psychiatric; consolidating fragmented behavioral market; regulatory/state-rate dependency",
        "source_url": "https://www.acadiahealthcare.com",
    },
    # 586 — ModivCare (Providence Service Corp) / Coliseum Capital (2020 SPAC exit at premium)
    {
        "source_id": "seed_586",
        "deal_name": "ModivCare / WCG (exit via public markets)",
        "buyer": "Public markets",
        "seller": "Providence Service Corp founders",
        "sector": "NEMT / Transportation",
        "entry_year": 2018,
        "exit_year": 2021,
        "entry_ev_mm": 400.0,
        "ebitda_at_entry_mm": 48.0,  # 8.3x
        "hold_years": 3.0,
        "realized_moic": 3.5,
        "realized_irr": 0.52,
        "ev_mm": 400.0,
        "ebitda_mm": 48.0,
        "payer_mix": {"medicaid": 0.75, "medicare": 0.15, "commercial": 0.10},
        "region": "National",
        "hospital_size": "mid",
        "leverage_pct": 0.50,
        "notes": "NEMT broker; Medicaid state contracts; rebranded from LogistiCare; public market exit at peak healthcare services multiple",
        "source_url": "https://www.modivcare.com/investors",
    },
    # 587 — National Spine & Pain Centers / Waud Capital (2019 → 2022)
    {
        "source_id": "seed_587",
        "deal_name": "National Spine & Pain Centers / Waud Capital",
        "buyer": "Waud Capital Partners",
        "seller": "Management / founders",
        "sector": "Pain Management",
        "entry_year": 2019,
        "exit_year": 2022,
        "entry_ev_mm": 680.0,
        "ebitda_at_entry_mm": 72.0,  # 9.4x
        "hold_years": 3.0,
        "realized_moic": 3.4,
        "realized_irr": 0.50,
        "ev_mm": 680.0,
        "ebitda_mm": 72.0,
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "region": "Mid-Atlantic",
        "hospital_size": "mid",
        "leverage_pct": 0.57,
        "notes": "200+ interventional pain locations; NSA partially offset by high commercial mix; sold to Valor Equity",
        "source_url": "https://www.nspc.com",
    },
    # 588 — AlerisLife (formerly Five Star Senior Living) / ABP Acquisition (2022 restructure)
    {
        "source_id": "seed_588",
        "deal_name": "AlerisLife / ABP Acquisition",
        "buyer": "ABP Acquisition LLC (Portnoy group)",
        "seller": "Senior Housing Partners Trust",
        "sector": "Senior Living",
        "entry_year": 2022,
        "exit_year": 2023,
        "entry_ev_mm": 100.0,
        "ebitda_at_entry_mm": 8.0,  # distressed
        "hold_years": 1.0,
        "realized_moic": 0.8,
        "realized_irr": None,
        "ev_mm": 100.0,
        "ebitda_mm": 8.0,
        "payer_mix": {"self_pay": 0.55, "medicare": 0.25, "medicaid": 0.15, "commercial": 0.05},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.40,
        "notes": "Post-COVID census recovery play; labor cost inflation overwhelmed rate recovery; value destruction",
        "source_url": "https://www.alerislife.com",
    },
    # 589 — Cano Health / InTandem Capital (2020 SPAC → 2023 bankruptcy)
    {
        "source_id": "seed_589",
        "deal_name": "Cano Health / SPAC / Chapter 11",
        "buyer": "InTandem Capital / SPAC",
        "seller": "Cano Health founders",
        "sector": "Primary Care",
        "entry_year": 2021,
        "exit_year": 2024,
        "entry_ev_mm": 4_400.0,  # SPAC valuation
        "ebitda_at_entry_mm": 60.0,  # ~73x — pure growth valuation
        "hold_years": 3.0,
        "realized_moic": 0.05,
        "realized_irr": None,
        "ev_mm": 4_400.0,
        "ebitda_mm": 60.0,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.20, "commercial": 0.10},
        "region": "Southeast",
        "hospital_size": "mid",
        "leverage_pct": 0.35,
        "notes": "Medicare Advantage primary care; Chapter 11 filed March 2024; execution failures + SPAC valuation overreach",
        "source_url": "https://www.canohealth.com",
    },
    # 590 — Quartet Health (mental health coordination) / Oak HC/FT (2018 → 2022)
    {
        "source_id": "seed_590",
        "deal_name": "Quartet Health / Oak HC/FT",
        "buyer": "Oak HC/FT (growth)",
        "seller": "Management / early investors",
        "sector": "Digital Health",
        "entry_year": 2018,
        "exit_year": 2022,
        "entry_ev_mm": 220.0,
        "ebitda_at_entry_mm": -10.0,   # pre-profitability
        "hold_years": 4.0,
        "realized_moic": 2.0,
        "realized_irr": 0.19,
        "ev_mm": 220.0,
        "ebitda_mm": -10.0,
        "payer_mix": {"commercial": 0.65, "medicare": 0.20, "medicaid": 0.15},
        "region": "National",
        "hospital_size": "small",
        "leverage_pct": 0.10,
        "notes": "Mental health network coordination SaaS; merged into Headway competitor; modest return vs risk profile",
        "source_url": "https://www.quartethealth.com",
    },
    # 591 — LifeScan (OneTouch glucose) / Platinum Equity (2018 → 2023)
    {
        "source_id": "seed_591",
        "deal_name": "LifeScan / Platinum Equity",
        "buyer": "Platinum Equity",
        "seller": "Johnson & Johnson",
        "sector": "Medical Devices",
        "entry_year": 2018,
        "exit_year": 2023,
        "entry_ev_mm": 2_100.0,
        "ebitda_at_entry_mm": 280.0,  # 7.5x
        "hold_years": 5.0,
        "realized_moic": 0.9,
        "realized_irr": None,
        "ev_mm": 2_100.0,
        "ebitda_mm": 280.0,
        "payer_mix": {"commercial": 0.50, "medicare": 0.35, "medicaid": 0.10, "self_pay": 0.05},
        "region": "Global",
        "hospital_size": "large",
        "leverage_pct": 0.65,
        "notes": "BGM market secular decline → CGM (Dexcom/Abbott); classic incumbent disruption; near-total value destruction",
        "source_url": "https://www.lifescan.com",
    },
    # 592 — LifeStance Health / TPG (2020 SPAC → 2021 IPO)
    {
        "source_id": "seed_592",
        "deal_name": "LifeStance Health / TPG SPAC",
        "buyer": "TPG / SPAC public",
        "seller": "Summit Partners / management",
        "sector": "Behavioral Health",
        "entry_year": 2021,
        "exit_year": None,
        "entry_ev_mm": 7_200.0,  # IPO valuation
        "ebitda_at_entry_mm": -50.0,   # negative at IPO
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 7_200.0,
        "ebitda_mm": -50.0,
        "payer_mix": {"commercial": 0.75, "medicare": 0.10, "medicaid": 0.10, "self_pay": 0.05},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.15,
        "notes": "Outpatient mental health 900+ locations; IPO at $18 → fell to $4; therapist turnover + unit economics; recovery underway 2024",
        "source_url": "https://www.lifestance.com/investors",
    },
    # 593 — nThrive (formerly Precyse + MedAssets RCM) / Clearlake (2016 → 2021)
    {
        "source_id": "seed_593",
        "deal_name": "nThrive RCM / Clearlake Capital",
        "buyer": "Clearlake Capital Group",
        "seller": "MedAssets / GE Healthcare IT",
        "sector": "Revenue Cycle Management",
        "entry_year": 2016,
        "exit_year": 2021,
        "entry_ev_mm": 700.0,
        "ebitda_at_entry_mm": 85.0,  # ~8.2x
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.23,
        "ev_mm": 700.0,
        "ebitda_mm": 85.0,
        "payer_mix": {"commercial": 0.60, "medicare": 0.25, "medicaid": 0.12, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.62,
        "notes": "Hospital RCM outsourcing + coding platform; sold to Waystar; consistent but unspectacular value creation",
        "source_url": "https://www.nthrive.com",
    },
    # 594 — Waystar (formerly ZirMed + Navicure) / EQT (2019 → 2024 IPO)
    {
        "source_id": "seed_594",
        "deal_name": "Waystar / EQT Partners",
        "buyer": "EQT Partners",
        "seller": "Bain Capital / HGGC",
        "sector": "Revenue Cycle Management",
        "entry_year": 2019,
        "exit_year": 2024,
        "entry_ev_mm": 2_700.0,
        "ebitda_at_entry_mm": 220.0,  # ~12.3x
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.31,
        "ev_mm": 2_700.0,
        "ebitda_mm": 220.0,
        "payer_mix": {"commercial": 0.65, "medicare": 0.22, "medicaid": 0.10, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.58,
        "notes": "Healthcare payments network; IPO June 2024 at $21/share; Change Healthcare outage created short-term tailwind",
        "source_url": "https://www.waystar.com/investors",
    },
    # 595 — Ensemble Health Partners / Golden Gate + CD&R (2022 recapitalization)
    {
        "source_id": "seed_595",
        "deal_name": "Ensemble Health Partners / CD&R",
        "buyer": "Clayton, Dubilier & Rice",
        "seller": "Golden Gate Capital (partial)",
        "sector": "Revenue Cycle Management",
        "entry_year": 2022,
        "exit_year": None,
        "entry_ev_mm": 4_500.0,
        "ebitda_at_entry_mm": 380.0,  # ~11.8x
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "ev_mm": 4_500.0,
        "ebitda_mm": 380.0,
        "payer_mix": {"commercial": 0.55, "medicare": 0.28, "medicaid": 0.14, "self_pay": 0.03},
        "region": "National",
        "hospital_size": "large",
        "leverage_pct": 0.60,
        "notes": "Full outsource RCM for health systems; AI-assisted coding + denials; primary competitor to Optum360, R1 RCM",
        "source_url": "https://www.ensemblehp.com",
    },
]
