"""Extended seed deals batch 60.

Theme: Ambulatory Surgery Centers (ASCs), outpatient surgery platforms,
MSO/HHA hybrids, and ophthalmology surgical networks. Fifteen synthetic
healthcare PE transactions representing realistic deal economics across
vintages 2016-2024.
"""

EXTENDED_SEED_DEALS_60 = [
    {
        "company_name": "Meridian Surgical Partners",
        "sector": "ASC",
        "subsector": "Multi-Specialty ASC Platform",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 33.6,
        "revenue_mm": 112.0,
        "ebitda_margin": 0.30,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.62, "medicare": 0.26, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.62,
        "region": "Southeast",
        "buyer": "Waud Capital",
        "status": "Realized",
    },
    {
        "company_name": "Crystal Clear Vision Surgery",
        "sector": "Ophthalmology Surgical",
        "subsector": "Cataract & Refractive ASC Network",
        "year": 2020,
        "ev_mm": 285.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 21.11,
        "revenue_mm": 60.31,
        "ebitda_margin": 0.35,
        "hold_years": 4.0,
        "moic": 2.2,
        "irr": 0.2179,
        "payer_mix": {"commercial": 0.48, "medicare": 0.44, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.48,
        "region": "West",
        "buyer": "Varsity Healthcare Partners",
        "status": "Active",
    },
    {
        "company_name": "Summit Outpatient Surgical",
        "sector": "Outpatient Surgery",
        "subsector": "Orthopedic Surgery Center",
        "year": 2019,
        "ev_mm": 175.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 15.91,
        "revenue_mm": 53.03,
        "ebitda_margin": 0.30,
        "hold_years": 4.5,
        "moic": 2.9,
        "irr": 0.2669,
        "payer_mix": {"commercial": 0.70, "medicare": 0.20, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.70,
        "region": "Midwest",
        "buyer": "Linden Capital Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "Atlantic Eye Surgical Group",
        "sector": "Ophthalmology Surgical",
        "subsector": "Retina & Cataract MSO",
        "year": 2017,
        "ev_mm": 540.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 38.57,
        "revenue_mm": 107.14,
        "ebitda_margin": 0.36,
        "hold_years": 5.5,
        "moic": 3.1,
        "irr": 0.2284,
        "payer_mix": {"commercial": 0.42, "medicare": 0.50, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.42,
        "region": "Northeast",
        "buyer": "Webster Equity Partners",
        "status": "Realized",
    },
    {
        "company_name": "Heritage Home Health & Surgical MSO",
        "sector": "MSO",
        "subsector": "Home Health + Surgical Services Hybrid",
        "year": 2021,
        "ev_mm": 310.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 29.52,
        "revenue_mm": 113.54,
        "ebitda_margin": 0.26,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.38, "medicare": 0.48, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.38,
        "region": "Southeast",
        "buyer": "H.I.G. Capital",
        "status": "Active",
    },
    {
        "company_name": "Pinnacle Pain & Surgery Center",
        "sector": "Surgery Center",
        "subsector": "Pain Management ASC Platform",
        "year": 2019,
        "ev_mm": 135.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 13.5,
        "revenue_mm": 48.21,
        "ebitda_margin": 0.28,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.58, "medicare": 0.32, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Shore Capital Partners",
        "status": "Realized",
    },
    {
        "company_name": "Coastal GI Endoscopy Partners",
        "sector": "ASC",
        "subsector": "Gastroenterology ASC Network",
        "year": 2022,
        "ev_mm": 230.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 19.17,
        "revenue_mm": 58.09,
        "ebitda_margin": 0.33,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.54, "medicare": 0.38, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.54,
        "region": "Southeast",
        "buyer": "Audax Private Equity",
        "status": "Active",
    },
    {
        "company_name": "Vanguard ASC Holdings",
        "sector": "ASC",
        "subsector": "Multi-Specialty ASC Rollup",
        "year": 2016,
        "ev_mm": 680.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 52.31,
        "revenue_mm": 174.37,
        "ebitda_margin": 0.30,
        "hold_years": 6.0,
        "moic": 3.4,
        "irr": 0.2263,
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "Frazier Healthcare Partners",
        "status": "Realized",
    },
    {
        "company_name": "Emerald Isle Ophthalmic Surgery",
        "sector": "Ophthalmology Surgical",
        "subsector": "Cataract Surgery Centers",
        "year": 2021,
        "ev_mm": 190.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 14.84,
        "revenue_mm": 41.22,
        "ebitda_margin": 0.36,
        "hold_years": 3.5,
        "moic": 1.8,
        "irr": 0.1829,
        "payer_mix": {"commercial": 0.40, "medicare": 0.52, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.40,
        "region": "Northeast",
        "buyer": "Sterling Partners",
        "status": "Active",
    },
    {
        "company_name": "Redwood Outpatient Surgical Alliance",
        "sector": "Outpatient Surgery",
        "subsector": "Multi-Site Outpatient Surgery",
        "year": 2018,
        "ev_mm": 365.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 27.65,
        "revenue_mm": 86.41,
        "ebitda_margin": 0.32,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.64, "medicare": 0.24, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.64,
        "region": "West",
        "buyer": "Riverside Company",
        "status": "Realized",
    },
    {
        "company_name": "Magnolia Home & Surgical Services",
        "sector": "MSO",
        "subsector": "Home Health Agency / Surgical Hybrid",
        "year": 2020,
        "ev_mm": 95.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 10.0,
        "revenue_mm": 41.67,
        "ebitda_margin": 0.24,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.34, "medicare": 0.52, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.34,
        "region": "Southeast",
        "buyer": "Shore Capital Partners",
        "status": "Partially Realized",
    },
    {
        "company_name": "Keystone Spine Surgery Center",
        "sector": "Surgery Center",
        "subsector": "Spine & Orthopedic ASC",
        "year": 2022,
        "ev_mm": 125.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 10.87,
        "revenue_mm": 31.06,
        "ebitda_margin": 0.35,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.72, "medicare": 0.18, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.72,
        "region": "Northeast",
        "buyer": "Linden Capital Partners",
        "status": "Active",
    },
    {
        "company_name": "SightLine Surgical Holdings",
        "sector": "Ophthalmology Surgical",
        "subsector": "Ophthalmic ASC & MSO Platform",
        "year": 2019,
        "ev_mm": 475.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 32.76,
        "revenue_mm": 86.21,
        "ebitda_margin": 0.38,
        "hold_years": 5.0,
        "moic": 2.8,
        "irr": 0.2287,
        "payer_mix": {"commercial": 0.44, "medicare": 0.48, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.44,
        "region": "National",
        "buyer": "Waud Capital",
        "status": "Realized",
    },
    {
        "company_name": "Horizon Multi-Specialty ASC",
        "sector": "ASC",
        "subsector": "Multi-Specialty Ambulatory Surgery",
        "year": 2023,
        "ev_mm": 260.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 18.84,
        "revenue_mm": 60.77,
        "ebitda_margin": 0.31,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.58, "medicare": 0.30, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Audax Private Equity",
        "status": "Active",
    },
    {
        "company_name": "Beacon Eye Surgery Institute",
        "sector": "Ophthalmology Surgical",
        "subsector": "Premium Cataract & Refractive",
        "year": 2024,
        "ev_mm": 155.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 10.0,
        "revenue_mm": 23.81,
        "ebitda_margin": 0.42,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.46, "medicare": 0.46, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.46,
        "region": "West",
        "buyer": "Frazier Healthcare Partners",
        "status": "Active",
    },
]
