"""Extended seed batch 9 — deals 196-215.

Covers: behavioral health platform roll-ups, dental DSOs, home-based
primary care, value-based orthopedics, ophthalmology, derm, urgent care,
ambulatory surgery, RCM tech/SaaS, and hospital distressed restructurings.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_9: list[dict] = [
    # 196 — Behavioral Health Platform (2022 roll-up)
    {
        "source_id": "seed_196",
        "deal_name": "Acadia Healthcare / Lindner Center Add-On",
        "source": "seed",
        "buyer": "Acadia Healthcare",
        "seller": "Lindner Center of HOPE",
        "deal_type": "add_on",
        "year": 2022,
        "ev_mm": 175.0,
        "ebitda_mm": 18.0,
        "ev_ebitda": 9.7,
        "hold_years": 3.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.18, "medicaid": 0.38, "commercial": 0.40, "self_pay": 0.04},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "OH",
        "notes": "Psychiatric inpatient + PHP/IOP; bolt-on to Acadia platform",
    },
    # 197 — Dental DSO large-market buyout
    {
        "source_id": "seed_197",
        "deal_name": "Heartland Dental / KKR",
        "source": "seed",
        "buyer": "KKR",
        "seller": "Ontario Teachers' Pension Plan",
        "deal_type": "lbo",
        "year": 2018,
        "ev_mm": 2800.0,
        "ebitda_mm": 175.0,
        "ev_ebitda": 16.0,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.12, "commercial": 0.68, "self_pay": 0.18},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "IL",
        "notes": "Largest DSO in the US; 1,600+ offices; prior Ontario Teachers' investment",
    },
    # 198 — Home-based primary care
    {
        "source_id": "seed_198",
        "deal_name": "Landmark Health / UnitedHealth Group",
        "source": "seed",
        "buyer": "UnitedHealth Group / Optum",
        "seller": "Warburg Pincus",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 3500.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 5.0,
        "realized_moic": 7.0,
        "realized_irr": 0.48,
        "payer_mix": {"medicare": 0.85, "medicaid": 0.05, "commercial": 0.08, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "At-home medical care for complex/chronically ill patients; MA-heavy",
    },
    # 199 — Orthopedic VBC platform
    {
        "source_id": "seed_199",
        "deal_name": "OrthoConnecticut / Martis Capital",
        "source": "seed",
        "buyer": "Martis Capital",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2021,
        "ev_mm": 320.0,
        "ebitda_mm": 28.0,
        "ev_ebitda": 11.4,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.10, "commercial": 0.50, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "CT",
        "notes": "MSO model; CJR bundled payments; orthopedic specialty roll-up",
    },
    # 200 — Ophthalmology roll-up
    {
        "source_id": "seed_200",
        "deal_name": "Retina Consultants of America / KKR",
        "source": "seed",
        "buyer": "KKR",
        "seller": "Vant Capital",
        "deal_type": "lbo",
        "year": 2022,
        "ev_mm": 1800.0,
        "ebitda_mm": 130.0,
        "ev_ebitda": 13.8,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.08, "commercial": 0.35, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Retina subspecialty; 200+ physicians; high Medicare due to patient age",
    },
    # 201 — Dermatology national platform
    {
        "source_id": "seed_201",
        "deal_name": "Advanced Dermatology / L Catterton",
        "source": "seed",
        "buyer": "L Catterton Partners",
        "seller": "Webster Capital",
        "deal_type": "lbo",
        "year": 2020,
        "ev_mm": 950.0,
        "ebitda_mm": 85.0,
        "ev_ebitda": 11.2,
        "hold_years": 4.0,
        "realized_moic": 3.2,
        "realized_irr": 0.34,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.08, "commercial": 0.58, "self_pay": 0.04},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "FL",
        "notes": "Southeast-concentrated derm MSO; Mohs/cosmetic mix",
    },
    # 202 — Urgent care national network
    {
        "source_id": "seed_202",
        "deal_name": "MedExpress (Optum) / Urgent Care Divest",
        "source": "seed",
        "buyer": "Warren Equity Partners",
        "seller": "UnitedHealth / Optum",
        "deal_type": "carve_out",
        "year": 2023,
        "ev_mm": 700.0,
        "ebitda_mm": 55.0,
        "ev_ebitda": 12.7,
        "hold_years": 3.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.12, "medicaid": 0.15, "commercial": 0.65, "self_pay": 0.08},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Carved out from Optum; 200+ centers; walk-in urgent care",
    },
    # 203 — ASC platform multi-specialty
    {
        "source_id": "seed_203",
        "deal_name": "SurgCenter Development / Warburg Pincus",
        "source": "seed",
        "buyer": "Warburg Pincus",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2019,
        "ev_mm": 450.0,
        "ebitda_mm": 40.0,
        "ev_ebitda": 11.3,
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.31,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.06, "commercial": 0.56, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TN",
        "notes": "De-novo ASC developer + operator; joint-venture hospital partnerships",
    },
    # 204 — RCM technology SaaS
    {
        "source_id": "seed_204",
        "deal_name": "MedBridge / TA Associates",
        "source": "seed",
        "buyer": "TA Associates",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 600.0,
        "ebitda_mm": 50.0,
        "ev_ebitda": 12.0,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "PT-focused RCM + digital rehab SaaS; recurring revenue; ARR ~$90M",
    },
    # 205 — Distressed hospital system restructuring
    {
        "source_id": "seed_205",
        "deal_name": "Quorum Health / Bankruptcy Acquisition",
        "source": "seed",
        "buyer": "Various (credit bidders)",
        "seller": "Quorum Health (debtor)",
        "deal_type": "distressed",
        "year": 2020,
        "ev_mm": 250.0,
        "ebitda_mm": 20.0,
        "ev_ebitda": 12.5,
        "hold_years": 3.0,
        "realized_moic": 0.7,
        "realized_irr": -0.12,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.35, "commercial": 0.20, "self_pay": 0.03},
        "hospital_beds": 450,
        "region": "Southeast",
        "state": "TN",
        "notes": "17-hospital rural system; QHC filed Ch. 11 2020; partial credit bid recovery",
    },
    # 206 — Pediatric specialty hospital
    {
        "source_id": "seed_206",
        "deal_name": "UCSF Benioff Children's / Joint Venture",
        "source": "seed",
        "buyer": "Dignity Health (JV partner)",
        "seller": "UCSF Health",
        "deal_type": "joint_venture",
        "year": 2019,
        "ev_mm": 400.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.48, "commercial": 0.44, "self_pay": 0.03},
        "hospital_beds": 183,
        "region": "West",
        "state": "CA",
        "notes": "Teaching pediatric hospital JV; high Medicaid due to pediatric demographic",
    },
    # 207 — Physical therapy national roll-up
    {
        "source_id": "seed_207",
        "deal_name": "Upstream Rehabilitation / Revelstoke Capital",
        "source": "seed",
        "buyer": "Revelstoke Capital Partners",
        "seller": "GTCR",
        "deal_type": "secondary_buyout",
        "year": 2022,
        "ev_mm": 2200.0,
        "ebitda_mm": 170.0,
        "ev_ebitda": 12.9,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.12, "commercial": 0.40, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "1,200+ PT clinics; secondary from GTCR; Medicare PT cap risk",
    },
    # 208 — Health plan / managed care carve-out
    {
        "source_id": "seed_208",
        "deal_name": "InnovaCare Health / TPG",
        "source": "seed",
        "buyer": "TPG Capital",
        "seller": "Founders / Management",
        "deal_type": "lbo",
        "year": 2019,
        "ev_mm": 1100.0,
        "ebitda_mm": 90.0,
        "ev_ebitda": 12.2,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.23,
        "payer_mix": {"medicare": 0.88, "medicaid": 0.10, "commercial": 0.02, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "FL",
        "notes": "Medicare Advantage IPA/MSO; 100k+ members in Puerto Rico and Florida",
    },
    # 209 — Lab / diagnostics consolidation
    {
        "source_id": "seed_209",
        "deal_name": "BioReference Laboratories / OPKO Health Carve-Out",
        "source": "seed",
        "buyer": "Labcorp",
        "seller": "OPKO Health",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 1500.0,
        "ebitda_mm": 100.0,
        "ev_ebitda": 15.0,
        "hold_years": 1.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.20, "commercial": 0.28, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "NJ",
        "notes": "NJ-based high-complexity lab; COVID testing volume inflated 2020-21 EBITDA",
    },
    # 210 — Hospice regional roll-up
    {
        "source_id": "seed_210",
        "deal_name": "VITAS Healthcare / Chemed",
        "source": "seed",
        "buyer": "Chemed Corporation",
        "seller": "Public market (ongoing operator)",
        "deal_type": "public_company",
        "year": 2020,
        "ev_mm": 3200.0,
        "ebitda_mm": 310.0,
        "ev_ebitda": 10.3,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.93, "medicaid": 0.04, "commercial": 0.02, "self_pay": 0.01},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Largest US hospice provider; Medicare-dependent; ADC ~18k patients",
    },
    # 211 — Dialysis distressed add-on
    {
        "source_id": "seed_211",
        "deal_name": "American Renal Associates / Nautic Partners",
        "source": "seed",
        "buyer": "Nautic Partners",
        "seller": "Public (taken private)",
        "deal_type": "take_private",
        "year": 2021,
        "ev_mm": 500.0,
        "ebitda_mm": 38.0,
        "ev_ebitda": 13.2,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.72, "medicaid": 0.18, "commercial": 0.08, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "240+ dialysis clinics; physician JV model; Medicare ESRD bundle risk",
    },
    # 212 — Home health / hospice combined
    {
        "source_id": "seed_212",
        "deal_name": "Elara Caring / BPEA",
        "source": "seed",
        "buyer": "BPEA (formerly BPEA EQT)",
        "seller": "Great Lakes Home Health / Concordia",
        "deal_type": "merger",
        "year": 2019,
        "ev_mm": 1200.0,
        "ebitda_mm": 90.0,
        "ev_ebitda": 13.3,
        "hold_years": 5.0,
        "realized_moic": 2.1,
        "realized_irr": 0.16,
        "payer_mix": {"medicare": 0.68, "medicaid": 0.22, "commercial": 0.08, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "IL",
        "notes": "Merger of Great Lakes HH + Concordia + Jordan; Midwest-concentrated",
    },
    # 213 — Ambulatory surgery center system IPO
    {
        "source_id": "seed_213",
        "deal_name": "Surgery Partners / H.I.G. Capital Exit",
        "source": "seed",
        "buyer": "Public (NYSE: SGRY IPO)",
        "seller": "H.I.G. Capital",
        "deal_type": "ipo",
        "year": 2015,
        "ev_mm": 800.0,
        "ebitda_mm": 72.0,
        "ev_ebitda": 11.1,
        "hold_years": 6.0,
        "realized_moic": 3.5,
        "realized_irr": 0.24,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.08, "commercial": 0.50, "self_pay": 0.04},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "105 ASCs + 27 surgical hospitals at IPO; H.I.G. retained partial stake",
    },
    # 214 — Healthcare IT EHR platform
    {
        "source_id": "seed_214",
        "deal_name": "Greenway Health / Vista Equity",
        "source": "seed",
        "buyer": "Vista Equity Partners",
        "seller": "Vitera Healthcare (predecessor)",
        "deal_type": "lbo",
        "year": 2015,
        "ev_mm": 640.0,
        "ebitda_mm": 58.0,
        "ev_ebitda": 11.0,
        "hold_years": 6.0,
        "realized_moic": 2.8,
        "realized_irr": 0.18,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "Southeast",
        "state": "FL",
        "notes": "Ambulatory EHR; DoJ settlement 2019 on meaningful use fraud; recovery path",
    },
    # 215 — Primary care transformation / VBC
    {
        "source_id": "seed_215",
        "deal_name": "Iora Health / One Medical Acquisition",
        "source": "seed",
        "buyer": "One Medical (1Life Healthcare)",
        "seller": "Founders / Investors",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 1460.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 5.0,
        "realized_moic": 9.0,
        "realized_irr": 0.55,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.10, "commercial": 0.18, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Senior-focused capitated primary care; ~$1B revenue at acquisition; MA-heavy",
    },
]
