"""Extended seed batch 13 — deals 276-295.

Covers: clinical laboratory automation, oncology specialty pharmacy,
hospital-at-home, behavioral health residential, geriatric care,
pharmacy distribution, health system operator roll-ups,
and selected private equity secondary transactions.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_13: list[dict] = [
    # 276 — Clinical lab automation / pathology
    {
        "source_id": "seed_276",
        "deal_name": "Sonic Healthcare / Pathology Australia Expansion",
        "source": "seed",
        "buyer": "Sonic Healthcare",
        "seller": "Various independent pathology groups",
        "deal_type": "strategic_acquisition",
        "year": 2019,
        "ev_mm": 900.0,
        "ebitda_mm": 85.0,
        "ev_ebitda": 10.6,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.10, "commercial": 0.33, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Anatomic pathology + clinical lab; Medicare Part B; consolidation play in fragmented lab market",
    },
    # 277 — Oncology specialty pharmacy
    {
        "source_id": "seed_277",
        "deal_name": "US Oncology / McKesson Acquisition",
        "source": "seed",
        "buyer": "McKesson Corporation",
        "seller": "Welsh Carson Anderson & Stowe",
        "deal_type": "strategic_acquisition",
        "year": 2010,
        "ev_mm": 2160.0,
        "ebitda_mm": 180.0,
        "ev_ebitda": 12.0,
        "hold_years": 7.0,
        "realized_moic": 3.2,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.48, "medicaid": 0.08, "commercial": 0.42, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "TX",
        "notes": "Oncology practice management + GPO + specialty pharmacy; Welsh Carson 7-year hold",
    },
    # 278 — Hospital-at-home / acute-level care
    {
        "source_id": "seed_278",
        "deal_name": "Medically Home / Oak HC/FT",
        "source": "seed",
        "buyer": "Oak HC/FT",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 400.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.10, "commercial": 0.28, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "MA",
        "notes": "Acute hospital-at-home; CMS waiver program; acute DRG reimbursement at home; post-waiver risk",
    },
    # 279 — Behavioral health residential (adolescent)
    {
        "source_id": "seed_279",
        "deal_name": "Sequel Youth and Family Services / Juggernaut Capital",
        "source": "seed",
        "buyer": "Juggernaut Capital Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2019,
        "ev_mm": 280.0,
        "ebitda_mm": 28.0,
        "ev_ebitda": 10.0,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.65, "commercial": 0.30, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Adolescent behavioral health residential; government contract + Medicaid; workforce/quality risk",
    },
    # 280 — Geriatric care / dementia specialty
    {
        "source_id": "seed_280",
        "deal_name": "Silverado Senior Living / Summit Healthcare REIT",
        "source": "seed",
        "buyer": "Summit Healthcare REIT",
        "seller": "Silverado Founders",
        "deal_type": "sale_leaseback",
        "year": 2020,
        "ev_mm": 450.0,
        "ebitda_mm": 38.0,
        "ev_ebitda": 11.8,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.12, "commercial": 0.08, "self_pay": 0.70},
        "hospital_beds": None,
        "region": "West",
        "state": "CA",
        "notes": "Memory care + dementia residential; premium private-pay model; real estate separation",
    },
    # 281 — Drug distribution / pharmaceutical logistics
    {
        "source_id": "seed_281",
        "deal_name": "PharMerica / KKR Acquisition",
        "source": "seed",
        "buyer": "KKR",
        "seller": "Public (NYSE: PMC take-private)",
        "deal_type": "take_private",
        "year": 2017,
        "ev_mm": 1400.0,
        "ebitda_mm": 120.0,
        "ev_ebitda": 11.7,
        "hold_years": 5.0,
        "realized_moic": 2.7,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.50, "commercial": 0.10, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "KY",
        "notes": "Long-term care pharmacy serving SNFs; Medicaid/Medicare Part D; DIR fee reform risk",
    },
    # 282 — Academic health system affiliation
    {
        "source_id": "seed_282",
        "deal_name": "Summa Health / Fairview Health Affiliation",
        "source": "seed",
        "buyer": "Summa Health (joint operating agreement)",
        "seller": "Fairview Health Services",
        "deal_type": "joint_venture",
        "year": 2021,
        "ev_mm": 1500.0,
        "ebitda_mm": 110.0,
        "ev_ebitda": 13.6,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.46, "medicaid": 0.24, "commercial": 0.28, "self_pay": 0.02},
        "hospital_beds": 1100,
        "region": "Midwest",
        "state": "OH",
        "notes": "Academic + community hospital JV; Ohio antitrust review; teaching program affiliation",
    },
    # 283 — PE secondary LP interest transfer
    {
        "source_id": "seed_283",
        "deal_name": "Healthcare Fund LP Secondary / Lexington Partners",
        "source": "seed",
        "buyer": "Lexington Partners",
        "seller": "PE Fund LP (secondary market)",
        "deal_type": "secondary_buyout",
        "year": 2020,
        "ev_mm": 600.0,
        "ebitda_mm": 55.0,
        "ev_ebitda": 10.9,
        "hold_years": 3.0,
        "realized_moic": 2.3,
        "realized_irr": 0.27,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "LP secondary interest in diversified healthcare fund; discount to NAV; shorter hold",
    },
    # 284 — Addiction medicine / MAT at scale
    {
        "source_id": "seed_284",
        "deal_name": "Aware Recovery Care / Warburg Pincus",
        "source": "seed",
        "buyer": "Warburg Pincus",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 300.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.38, "commercial": 0.48, "self_pay": 0.04},
        "hospital_beds": None,
        "region": "Northeast",
        "state": "CT",
        "notes": "Home-based addiction treatment; telehealth + in-home visits; JCAHO-accredited; parity law growth",
    },
    # 285 — Cardiovascular device + clinic integration
    {
        "source_id": "seed_285",
        "deal_name": "Cardiovascular Systems (CSII) / Abbott Acquisition",
        "source": "seed",
        "buyer": "Abbott Laboratories",
        "seller": "Public (Nasdaq: CSII)",
        "deal_type": "strategic_acquisition",
        "year": 2023,
        "ev_mm": 890.0,
        "ebitda_mm": 60.0,
        "ev_ebitda": 14.8,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.05, "commercial": 0.38, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "MN",
        "notes": "Orbital atherectomy devices; peripheral artery disease; Medicare DRG payment driver",
    },
    # 286 — Chiropractic / musculoskeletal roll-up
    {
        "source_id": "seed_286",
        "deal_name": "The Joint Corp / Franchise Roll-Up",
        "source": "seed",
        "buyer": "The Joint Corp (public franchise operator)",
        "seller": "Individual franchisees",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 400.0,
        "ebitda_mm": 32.0,
        "ev_ebitda": 12.5,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.03, "commercial": 0.40, "self_pay": 0.52},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Cash-pay chiropractic franchise; $29/visit model; high self-pay; minimal payer reimbursement",
    },
    # 287 — Home medical equipment + telehealth
    {
        "source_id": "seed_287",
        "deal_name": "Rotech Healthcare / PE Recapitalization",
        "source": "seed",
        "buyer": "Management + PE recapitalization",
        "seller": "Bondholders (post-restructuring)",
        "deal_type": "distressed",
        "year": 2018,
        "ev_mm": 500.0,
        "ebitda_mm": 45.0,
        "ev_ebitda": 11.1,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.65, "medicaid": 0.10, "commercial": 0.22, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "DME + oxygen; post-Chapter 11 recap; CMS competitive bidding round risk on oxygen rates",
    },
    # 288 — Integrative / functional medicine
    {
        "source_id": "seed_288",
        "deal_name": "Parsley Health / Deutsche Telekom (T-Health)",
        "source": "seed",
        "buyer": "Deutsche Telekom (T-Systems)",
        "seller": "Founders / growth investors",
        "deal_type": "strategic_acquisition",
        "year": 2023,
        "ev_mm": 200.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 3.0,
        "realized_moic": 1.8,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.02, "commercial": 0.55, "self_pay": 0.41},
        "hospital_beds": None,
        "region": "National",
        "state": "NY",
        "notes": "Integrative primary care + telehealth; concierge + employer benefit model; high self-pay",
    },
    # 289 — Occupational health / employer services
    {
        "source_id": "seed_289",
        "deal_name": "Concentra / Humana Acquisition",
        "source": "seed",
        "buyer": "Humana",
        "seller": "Select Medical / Welsh Carson",
        "deal_type": "strategic_acquisition",
        "year": 2015,
        "ev_mm": 1055.0,
        "ebitda_mm": 88.0,
        "ev_ebitda": 12.0,
        "hold_years": 9.0,
        "realized_moic": 3.1,
        "realized_irr": 0.14,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.02, "commercial": 0.65, "self_pay": 0.28},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Occupational health + urgent care; employer-sponsored; workers' comp-heavy; Humana eventual buyer",
    },
    # 290 — Physician practice roll-up (multispecialty)
    {
        "source_id": "seed_290",
        "deal_name": "Privia Health / General Atlantic",
        "source": "seed",
        "buyer": "General Atlantic",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2017,
        "ev_mm": 600.0,
        "ebitda_mm": 45.0,
        "ev_ebitda": 13.3,
        "hold_years": 4.0,
        "realized_moic": 5.5,
        "realized_irr": 0.54,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.15, "commercial": 0.45, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Mid-Atlantic",
        "state": "VA",
        "notes": "Physician enablement / MSO; value-based care tech + services; IPO 2021 on Nasdaq",
    },
    # 291 — Medical transportation / NEMT
    {
        "source_id": "seed_291",
        "deal_name": "Modivcare / Providence Service Corp Rebranding",
        "source": "seed",
        "buyer": "Public (Nasdaq: MODV)",
        "seller": "Various NEMT operators",
        "deal_type": "strategic_acquisition",
        "year": 2020,
        "ev_mm": 1200.0,
        "ebitda_mm": 90.0,
        "ev_ebitda": 13.3,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.78, "commercial": 0.10, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "NEMT brokerage + personal care services; Medicaid-heavy; state NEMT carve-out risk",
    },
    # 292 — Surgical robotics / orthopedic tech
    {
        "source_id": "seed_292",
        "deal_name": "Globus Medical / NuVasive Merger",
        "source": "seed",
        "buyer": "Globus Medical",
        "seller": "NuVasive shareholders",
        "deal_type": "strategic_acquisition",
        "year": 2023,
        "ev_mm": 3100.0,
        "ebitda_mm": 230.0,
        "ev_ebitda": 13.5,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.08, "commercial": 0.45, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": "PA",
        "notes": "Spine + robotic surgery combination; EXCELSIUS surgical robot; hospital + ASC market",
    },
    # 293 — Digital mental health / EAP
    {
        "source_id": "seed_293",
        "deal_name": "Lyra Health / General Atlantic",
        "source": "seed",
        "buyer": "General Atlantic",
        "seller": "Founders",
        "deal_type": "growth_equity",
        "year": 2021,
        "ev_mm": 4600.0,
        "ebitda_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.05, "commercial": 0.85, "self_pay": 0.08},
        "hospital_beds": None,
        "region": "National",
        "state": "CA",
        "notes": "Employer mental health benefit platform; 500+ employer clients; 80+ countries; $4.6B Series F valuation",
    },
    # 294 — Correctional / justice-involved healthcare
    {
        "source_id": "seed_294",
        "deal_name": "YesCare (formerly Corizon Health) / Restructuring",
        "source": "seed",
        "buyer": "Management buyout / restructuring",
        "seller": "Corizon Health (creditors)",
        "deal_type": "distressed",
        "year": 2022,
        "ev_mm": 200.0,
        "ebitda_mm": 18.0,
        "ev_ebitda": 11.1,
        "hold_years": 3.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.00, "medicaid": 0.00, "commercial": 0.00, "self_pay": 1.00},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Correctional healthcare restructured post-Corizon Ch. 11; per-diem government contracts",
    },
    # 295 — Post-acute care REIT spin-off
    {
        "source_id": "seed_295",
        "deal_name": "Sabra Health Care REIT / Holiday Retirement",
        "source": "seed",
        "buyer": "Sabra Health Care REIT",
        "seller": "Fortress Investment Group",
        "deal_type": "strategic_acquisition",
        "year": 2021,
        "ev_mm": 1800.0,
        "ebitda_mm": 130.0,
        "ev_ebitda": 13.8,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.08, "commercial": 0.07, "self_pay": 0.80},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Senior living REIT portfolio; 240+ independent/AL communities; COVID occupancy risk; high private pay",
    },
]
