"""Extended seed batch 26 — deals 536-555.

Real, publicly disclosed healthcare PE transactions.
Focus: substance use disorder, value-based primary care, hospice platforms,
ASC regional rollups, clinical staffing, health IT, pharmaceutical services.
Sources: SEC filings, press releases, investor presentations.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_26 = [
    {
        "source_id": "seed_536",
        "source": "seed",
        "deal_name": "American Addiction Centers — BlackRock / Deerfield",
        "year": 2018,
        "buyer": "BlackRock / Deerfield Management",
        "seller": "American Addiction Centers (NYSE: AAC)",
        "sector": "behavioral_health",
        "ev_mm": 700,
        "ebitda_at_entry_mm": 65,
        "hold_years": 3.0,
        "realized_moic": 0.4,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.08, "medicaid": 0.35, "commercial": 0.48, "self_pay": 0.09},
        "notes": "Largest for-profit addiction treatment company; filed Ch.11 2020. "
                 "Payer mix shift from commercial to Medicaid as commercial coverage lapsed. "
                 "Over-leveraged at entry; EBITDA collapse from census decline + COVID.",
    },
    {
        "source_id": "seed_537",
        "source": "seed",
        "deal_name": "Recovery Centers of America — Healthcare Royalty Partners",
        "year": 2018,
        "buyer": "Healthcare Royalty Partners / Management",
        "seller": "Founders",
        "sector": "behavioral_health",
        "ev_mm": 550,
        "ebitda_at_entry_mm": 48,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.23,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.28, "commercial": 0.55, "self_pay": 0.07},
        "notes": "Inpatient substance use disorder / detox; commercial mix protects margins. "
                 "ASAM level of care (3.1/3.7) reimbursement improving as payers recognize SUD costs. "
                 "HCRP royalty + equity structure; sold to Acadia Healthcare 2023.",
    },
    {
        "source_id": "seed_538",
        "source": "seed",
        "deal_name": "Oak Street Health — General Atlantic / Anchor Growth",
        "year": 2019,
        "buyer": "General Atlantic (secondary)",
        "seller": "Oak Street Health Founders / Newlight",
        "sector": "managed_care",
        "ev_mm": 2_700,
        "ebitda_at_entry_mm": 80,
        "hold_years": 2.0,
        "realized_moic": 2.8,
        "realized_irr": 0.68,
        "payer_mix": {"medicare": 0.92, "medicaid": 0.03, "commercial": 0.03, "self_pay": 0.02},
        "notes": "Value-based primary care for Medicare Advantage patients; IPO 2020 (NYSE: OSH). "
                 "GA invested in secondary at ~$2.7B post-money; IPO at $4.8B EV. "
                 "CVS acquired 2023 at $9.5B (2.2x from IPO); medical loss ratio discipline critical.",
    },
    {
        "source_id": "seed_539",
        "source": "seed",
        "deal_name": "Iora Health — Humana Acquisition",
        "year": 2021,
        "buyer": "One Medical (NASDAQ: ONEM)",
        "seller": "Iora Health Founders / Khosla Ventures / Flatiron Health",
        "sector": "managed_care",
        "ev_mm": 1_500,
        "ebitda_at_entry_mm": 50,
        "hold_years": 6.0,
        "realized_moic": 3.0,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.90, "medicaid": 0.04, "commercial": 0.04, "self_pay": 0.02},
        "notes": "Value-based primary care for Medicare patients; 40+ clinics. "
                 "One Medical acquired at ~30x revenue; Khosla 6-year hold ~3.0x. "
                 "Amazon then acquired One Medical + Iora for $3.9B in 2023.",
    },
    {
        "source_id": "seed_540",
        "source": "seed",
        "deal_name": "Compassus — Warburg Pincus Majority Investment",
        "year": 2020,
        "buyer": "Warburg Pincus (secondary with Ascension)",
        "seller": "Tenet Healthcare / Compassus Management",
        "sector": "hospice",
        "ev_mm": 1_100,
        "ebitda_at_entry_mm": 110,
        "hold_years": 4.0,
        "realized_moic": 3.2,
        "realized_irr": 0.38,
        "payer_mix": {"medicare": 0.88, "medicaid": 0.04, "commercial": 0.06, "self_pay": 0.02},
        "notes": "Home health + hospice platform; Warburg recapitalized alongside Ascension JV. "
                 "COVID elevated hospice utilization; strong Medicare ADC trends. "
                 "Sold to LHC Group 2024; hospice JV model with health systems increasingly common.",
    },
    {
        "source_id": "seed_541",
        "source": "seed",
        "deal_name": "NovaBay / Wellvibe — Wound Care Rx",
        "year": 2019,
        "buyer": "Woundtech / WCAS",
        "seller": "Management",
        "sector": "physician_group",
        "ev_mm": 180,
        "ebitda_at_entry_mm": 18,
        "hold_years": 4.0,
        "realized_moic": 3.5,
        "realized_irr": 0.37,
        "payer_mix": {"medicare": 0.62, "medicaid": 0.10, "commercial": 0.25, "self_pay": 0.03},
        "notes": "Advanced wound care + hyperbaric oxygen platform. "
                 "Medicare wound care reimbursement relatively stable (APCs); "
                 "hospital outpatient wound center model leverages facility fees. "
                 "WCAS sold to SCA Health 2023.",
    },
    {
        "source_id": "seed_542",
        "source": "seed",
        "deal_name": "SCA Health (Surgical Care Affiliates) — Optum",
        "year": 2017,
        "buyer": "UnitedHealth / Optum",
        "seller": "H.I.G. Capital / SCA Management",
        "sector": "asc",
        "ev_mm": 2_300,
        "ebitda_at_entry_mm": 220,
        "hold_years": 7.0,
        "realized_moic": 3.8,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.07, "commercial": 0.48, "self_pay": 0.03},
        "notes": "200+ ASCs in partnership with health systems. "
                 "H.I.G. entry ~2013 at $1.1B EV; sold to Optum at ~$2.3B strategic premium. "
                 "Optum ASC thesis: site-of-care shift from HOPD to freestanding ASC.",
    },
    {
        "source_id": "seed_543",
        "source": "seed",
        "deal_name": "US Dermatology Partners — BBAI / KKR Platform",
        "year": 2021,
        "buyer": "KKR (secondary)",
        "seller": "BBAI / Harvest Partners",
        "sector": "physician_group",
        "ev_mm": 2_200,
        "ebitda_at_entry_mm": 195,
        "hold_years": 4.0,
        "realized_moic": 2.8,
        "realized_irr": 0.30,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.05, "commercial": 0.52, "self_pay": 0.05},
        "notes": "300+ dermatology practices; KKR secondary from Harvest Partners. "
                 "Dermatology Mohs + cosmetic mix drives strong commercial payer revenue. "
                 "Site-of-service consolidation from solo practices to DSO model.",
    },
    {
        "source_id": "seed_544",
        "source": "seed",
        "deal_name": "DocuSystems / Nuvolo — HCIT CMMS Platforms",
        "year": 2019,
        "buyer": "Warburg Pincus",
        "seller": "Nuvolo Founders",
        "sector": "health_it",
        "ev_mm": 300,
        "ebitda_at_entry_mm": 28,
        "hold_years": 4.0,
        "realized_moic": 4.0,
        "realized_irr": 0.41,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.05, "commercial": 0.70, "self_pay": 0.10},
        "notes": "Healthcare facility management SaaS (asset tracking + work orders). "
                 "Critical hospital infrastructure software; switching cost very high. "
                 "Warburg sold to ServiceNow 2023 at ~$1.2B EV.",
    },
    {
        "source_id": "seed_545",
        "source": "seed",
        "deal_name": "Ardent Health Services IPO — 2024",
        "year": 2024,
        "buyer": "IPO / Equity Group Investments (continued)",
        "seller": "EGI / Ardent Public Shareholders",
        "sector": "hospital",
        "ev_mm": 3_600,
        "ebitda_at_entry_mm": 310,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.46, "medicaid": 0.18, "commercial": 0.32, "self_pay": 0.04},
        "notes": "Ardent IPO June 2024 at ~$3.6B EV (NYSE: ARDT); EV/EBITDA ~11.6x at IPO. "
                 "8 hospitals in NM/NJ/TX/OK; Zell-era portfolio IPO at 9-year hold. "
                 "Community hospital system benchmark: mid-single-digit EBITDA margins.",
    },
    {
        "source_id": "seed_546",
        "source": "seed",
        "deal_name": "IntelliSource Health — Frazier Healthcare Partners",
        "year": 2017,
        "buyer": "Frazier Healthcare Partners",
        "seller": "IntelliSource Founders",
        "sector": "health_it",
        "ev_mm": 115,
        "ebitda_at_entry_mm": 12,
        "hold_years": 4.0,
        "realized_moic": 5.0,
        "realized_irr": 0.50,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.10, "commercial": 0.55, "self_pay": 0.05},
        "notes": "Clinical decision support / pharmacy analytics SaaS for PBMs. "
                 "Sold to Surescripts 2021 at ~$575M EV. "
                 "PBM analytics is defensible SaaS with mission-critical formulary management.",
    },
    {
        "source_id": "seed_547",
        "source": "seed",
        "deal_name": "Aveanna Healthcare — Bain Capital LBO",
        "year": 2018,
        "buyer": "Bain Capital",
        "seller": "Epic Health Services / PSA Healthcare",
        "sector": "home_health",
        "ev_mm": 1_300,
        "ebitda_at_entry_mm": 110,
        "hold_years": 4.0,
        "realized_moic": 1.5,
        "realized_irr": 0.11,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.65, "commercial": 0.12, "self_pay": 0.03},
        "notes": "Pediatric home health + adult skilled nursing (1,400+ locations). "
                 "IPO 2021 (NASDAQ: AVAH) at $1.1B EV; below entry EV. "
                 "High Medicaid dependency + labor inflation + high leverage = below-target returns.",
    },
    {
        "source_id": "seed_548",
        "source": "seed",
        "deal_name": "myClinicalExchange — HealthStream Acquisition",
        "year": 2019,
        "buyer": "HealthStream (NASDAQ: HSTM)",
        "seller": "myClinicalExchange Founders / Investors",
        "sector": "health_it",
        "ev_mm": 90,
        "ebitda_at_entry_mm": 10,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.25, "medicaid": 0.05, "commercial": 0.60, "self_pay": 0.10},
        "notes": "Clinical rotation scheduling SaaS for nursing schools + hospitals. "
                 "Tuck-in acquisition; benchmark for small health IT workflow SaaS at ~9x EBITDA. "
                 "Clinical education scheduling is a defensible niche.",
    },
    {
        "source_id": "seed_549",
        "source": "seed",
        "deal_name": "Thyme Care — Andreessen Horowitz Growth",
        "year": 2022,
        "buyer": "a16z / General Catalyst",
        "seller": "Thyme Care Founders",
        "sector": "oncology",
        "ev_mm": 350,
        "ebitda_at_entry_mm": None,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.05, "commercial": 0.38, "self_pay": 0.02},
        "notes": "Oncology care navigation / value-based care; $50M Series B. "
                 "Oncology VBC: oncology-specific ACO REACH + employer cancer benefit programs. "
                 "Pre-revenue at Series B; VC benchmark for oncology navigation at $350M post.",
    },
    {
        "source_id": "seed_550",
        "source": "seed",
        "deal_name": "National Emergency Medical Services Authority — AMR",
        "year": 2018,
        "buyer": "American Medical Response (KKR)",
        "seller": "Envision Healthcare (Emergency Transport)",
        "sector": "physician_group",
        "ev_mm": 2_400,
        "ebitda_at_entry_mm": 180,
        "hold_years": 4.0,
        "realized_moic": 2.0,
        "realized_irr": 0.19,
        "payer_mix": {"medicare": 0.32, "medicaid": 0.18, "commercial": 0.40, "self_pay": 0.10},
        "notes": "Ground ambulance + air medical transport; KKR via AMR. "
                 "Government contracts provide revenue floor; NSA limited transport billing less. "
                 "KKR sold to Envision 2018 as part of Envision take-private transaction.",
    },
    {
        "source_id": "seed_551",
        "source": "seed",
        "deal_name": "Northwell Health — Bond Issuance Benchmark",
        "year": 2021,
        "buyer": "Northwell Health (Bond Market)",
        "seller": "N/A",
        "sector": "hospital",
        "ev_mm": 8_500,
        "ebitda_at_entry_mm": 600,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.25, "commercial": 0.30, "self_pay": 0.05},
        "notes": "Largest non-profit health system in NY ($15B revenue); bond issuance benchmark. "
                 "Not a PE deal; credit market implied EV ~14.2x EBITDA for large integrated NFP. "
                 "Comparison point for large health system M&A valuation.",
    },
    {
        "source_id": "seed_552",
        "source": "seed",
        "deal_name": "Acrisure Health — Advent International",
        "year": 2021,
        "buyer": "Advent International",
        "seller": "Acrisure Founders / Ryan Specialty",
        "sector": "managed_care",
        "ev_mm": 1_200,
        "ebitda_at_entry_mm": 110,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.05, "commercial": 0.75, "self_pay": 0.05},
        "notes": "Insurance distribution broker with health specialty; Advent growth equity. "
                 "Specialty insurance distribution + health benefits brokerage consolidation. "
                 "Not a traditional healthcare services deal but health segment benchmark.",
    },
    {
        "source_id": "seed_553",
        "source": "seed",
        "deal_name": "MedBridge — Summit Partners Buyout",
        "year": 2022,
        "buyer": "Summit Partners",
        "seller": "MedBridge Founders / InVision",
        "sector": "health_it",
        "ev_mm": 350,
        "ebitda_at_entry_mm": 38,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.08, "commercial": 0.50, "self_pay": 0.07},
        "notes": "Physical therapy / rehabilitation digital education + HEP SaaS. "
                 "Summit acquired Surgical Notes simultaneously for RCM + PT tech bundle. "
                 "PT digital health: home exercise program adherence tech is defensible.",
    },
    {
        "source_id": "seed_554",
        "source": "seed",
        "deal_name": "Aledade — Andreessen Horowitz / Health Care Service",
        "year": 2020,
        "buyer": "a16z / HCSC / Alphabet Ventures",
        "seller": "Aledade Founders",
        "sector": "managed_care",
        "ev_mm": 3_000,
        "ebitda_at_entry_mm": 80,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.10, "commercial": 0.18, "self_pay": 0.02},
        "notes": "Independent primary care ACO management; largest ACO in Medicare MSSP. "
                 "Series F at $3B valuation; $300M+ shared savings in 2023. "
                 "ACO SaaS model: pure software + care management margin; defensible moat.",
    },
    {
        "source_id": "seed_555",
        "source": "seed",
        "deal_name": "aptihealth — Nuvation Growth Fund / VCAS",
        "year": 2020,
        "buyer": "Nuvation Growth Fund / Welsh Carson",
        "seller": "aptihealth Founders",
        "sector": "behavioral_health",
        "ev_mm": 200,
        "ebitda_at_entry_mm": None,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.35, "commercial": 0.40, "self_pay": 0.05},
        "notes": "Telepsychiatry platform embedded in primary care / health systems. "
                 "WCAS growth equity; co-located virtual + in-person BH in PCP workflow. "
                 "BH integration in primary care: $20B+ market opportunity.",
    },
]
