"""Extended seed batch 10 — deals 216-235.

Covers: managed care / PBM acquisitions, specialty pharma services,
infusion therapy, correctional healthcare, rural health systems,
SNF/AL platform exits, and international health IT.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_10: list[dict] = [
    # 216 — PBM / specialty pharmacy acquisition
    {
        "source_id": "seed_216",
        "deal_name": "Evernorth / Express Scripts (Cigna)",
        "source": "seed",
        "buyer": "Cigna Group",
        "seller": "Public (Express Scripts shareholders)",
        "deal_type": "strategic_acquisition",
        "year": 2018,
        "ev_mm": 67000.0,
        "ebitda_mm": 5200.0,
        "ev_ebitda": 12.9,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Largest PBM acquisition; Cigna paid $67B; PBM segment rebranded Evernorth 2020",
    },
    # 217 — Managed care carve-out / Medicaid
    {
        "source_id": "seed_217",
        "deal_name": "WellCare Health Plans / Centene Acquisition",
        "source": "seed",
        "buyer": "Centene Corporation",
        "seller": "WellCare shareholders",
        "deal_type": "strategic_acquisition",
        "year": 2020,
        "ev_mm": 17300.0,
        "ebitda_mm": 1100.0,
        "ev_ebitda": 15.7,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.68, "commercial": 0.02, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Government managed care consolidation; ~$1B synergies; MA + Medicaid book",
    },
    # 218 — Correctional healthcare
    {
        "source_id": "seed_218",
        "deal_name": "Centurion Health / Wexford Health Merger",
        "source": "seed",
        "buyer": "MHM Services (operator)",
        "seller": "Founders",
        "deal_type": "merger",
        "year": 2019,
        "ev_mm": 300.0,
        "ebitda_mm": 28.0,
        "ev_ebitda": 10.7,
        "hold_years": 5.0,
        "realized_moic": 2.4,
        "realized_irr": 0.19,
        "payer_mix": {"medicare": 0.00, "medicaid": 0.00, "commercial": 0.00, "self_pay": 1.00},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Government contract correctional health; no traditional payer mix; per-diem model",
    },
    # 219 — Rural critical access hospital network
    {
        "source_id": "seed_219",
        "deal_name": "Essentia Health / Rural Minnesota System",
        "source": "seed",
        "buyer": "Essentia Health",
        "seller": "Benedictine Health System",
        "deal_type": "strategic_acquisition",
        "year": 2020,
        "ev_mm": 800.0,
        "ebitda_mm": 55.0,
        "ev_ebitda": 14.5,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.48, "medicaid": 0.28, "commercial": 0.22, "self_pay": 0.02},
        "hospital_beds": 320,
        "region": "Midwest",
        "state": "MN",
        "notes": "Rural CAH network; mission-driven; high Medicare + Medicaid due to rural demographics",
    },
    # 220 — Infusion therapy national platform
    {
        "source_id": "seed_220",
        "deal_name": "BioScrip / Option Care (Merger)",
        "source": "seed",
        "buyer": "Option Care Health (post-merger)",
        "seller": "Public (BioScrip shareholders)",
        "deal_type": "merger",
        "year": 2019,
        "ev_mm": 1800.0,
        "ebitda_mm": 115.0,
        "ev_ebitda": 15.7,
        "hold_years": 4.0,
        "realized_moic": 3.1,
        "realized_irr": 0.33,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.15, "commercial": 0.55, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Merger creates largest independent home infusion operator; Walgreen JV buyout",
    },
    # 221 — SNF/AL platform secondary
    {
        "source_id": "seed_221",
        "deal_name": "Consulate Health Care / Restructuring",
        "source": "seed",
        "buyer": "CIFC / Restructured lenders",
        "seller": "Appointment of receiver",
        "deal_type": "distressed",
        "year": 2021,
        "ev_mm": 400.0,
        "ebitda_mm": 30.0,
        "ev_ebitda": 13.3,
        "hold_years": 3.0,
        "realized_moic": 0.6,
        "realized_irr": -0.18,
        "payer_mix": {"medicare": 0.25, "medicaid": 0.62, "commercial": 0.10, "self_pay": 0.03},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "FL",
        "notes": "150+ SNFs; COVID losses + DOJ settlement; lender workout post COVID",
    },
    # 222 — Health IT / Revenue Cycle analytics
    {
        "source_id": "seed_222",
        "deal_name": "Ciox Health / Datavant Merger",
        "source": "seed",
        "buyer": "Datavant",
        "seller": "Advent International",
        "deal_type": "merger",
        "year": 2021,
        "ev_mm": 7000.0,
        "ebitda_mm": 280.0,
        "ev_ebitda": 25.0,
        "hold_years": 5.0,
        "realized_moic": 8.0,
        "realized_irr": 0.52,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Medical record retrieval + health data network; Advent 5x; data de-ID moat",
    },
    # 223 — Behavioral managed care
    {
        "source_id": "seed_223",
        "deal_name": "Magellan Health / Centene Acquisition",
        "source": "seed",
        "buyer": "Centene Corporation",
        "seller": "Public (Magellan shareholders)",
        "deal_type": "strategic_acquisition",
        "year": 2022,
        "ev_mm": 2200.0,
        "ebitda_mm": 175.0,
        "ev_ebitda": 12.6,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.55, "commercial": 0.25, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Behavioral health managed care + pharmacy + radiology; strategic fit with Centene MH book",
    },
    # 224 — Ambulance / emergency services secondary
    {
        "source_id": "seed_224",
        "deal_name": "Rural Metro / KKR Exit to AMR",
        "source": "seed",
        "buyer": "American Medical Response",
        "seller": "KKR",
        "deal_type": "secondary_buyout",
        "year": 2018,
        "ev_mm": 2100.0,
        "ebitda_mm": 180.0,
        "ev_ebitda": 11.7,
        "hold_years": 5.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.22, "commercial": 0.28, "self_pay": 0.05},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Ground ambulance; Rural Metro + partnership with AMR; reimbursement reform risk",
    },
    # 225 — Value-based primary care urban
    {
        "source_id": "seed_225",
        "deal_name": "ChenMed / Frist Cressey Growth Investment",
        "source": "seed",
        "buyer": "Frist Cressey Ventures",
        "seller": "Chen family / Founders",
        "deal_type": "growth_equity",
        "year": 2019,
        "ev_mm": 1000.0,
        "ebitda_mm": 70.0,
        "ev_ebitda": 14.3,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.90, "medicaid": 0.05, "commercial": 0.05, "self_pay": 0.00},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "FL",
        "notes": "Full-risk capitated MA primary care; urban underserved; 2+ visits/member/month model",
    },
    # 226 — Specialty pharmacy / oncology
    {
        "source_id": "seed_226",
        "deal_name": "Diplomat Pharmacy / UnitedHealth OptumRx",
        "source": "seed",
        "buyer": "UnitedHealth / OptumRx",
        "seller": "Public (Diplomat shareholders)",
        "deal_type": "take_private",
        "year": 2020,
        "ev_mm": 300.0,
        "ebitda_mm": 15.0,
        "ev_ebitda": 20.0,
        "hold_years": 1.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.10, "commercial": 0.53, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "Midwest",
        "state": "MI",
        "notes": "Specialty pharmacy + infusion; taken private at steep discount; integration into OptumRx",
    },
    # 227 — Revenue cycle outsourcing
    {
        "source_id": "seed_227",
        "deal_name": "Parallon / HCA Spin-Out",
        "source": "seed",
        "buyer": "Parallon (HCA captive → external)",
        "seller": "HCA Healthcare",
        "deal_type": "carve_out",
        "year": 2019,
        "ev_mm": 2000.0,
        "ebitda_mm": 180.0,
        "ev_ebitda": 11.1,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TN",
        "notes": "HCA internal RCM platform; sold external RCM services; partial carve-out evaluation",
    },
    # 228 — Genetic testing / precision medicine
    {
        "source_id": "seed_228",
        "deal_name": "Myriad Genetics / Oncology Segment",
        "source": "seed",
        "buyer": "Tempus AI (majority stake)",
        "seller": "Myriad Genetics",
        "deal_type": "strategic_acquisition",
        "year": 2023,
        "ev_mm": 600.0,
        "ebitda_mm": 45.0,
        "ev_ebitda": 13.3,
        "hold_years": 3.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.08, "commercial": 0.50, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Hereditary cancer + precision medicine testing; coverage policy risk for BRCA testing",
    },
    # 229 — Assisted living / memory care roll-up
    {
        "source_id": "seed_229",
        "deal_name": "Brookdale Senior Living / Blackstone",
        "source": "seed",
        "buyer": "Blackstone Real Estate",
        "seller": "Public (partial stake)",
        "deal_type": "take_private",
        "year": 2021,
        "ev_mm": 3000.0,
        "ebitda_mm": 200.0,
        "ev_ebitda": 15.0,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.18, "commercial": 0.12, "self_pay": 0.60},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Largest AL/memory care operator; primarily private pay; occupancy recovery post-COVID thesis",
    },
    # 230 — Healthcare staffing / locum tenens
    {
        "source_id": "seed_230",
        "deal_name": "AMN Healthcare / Connetics / Travel Nursing Roll-up",
        "source": "seed",
        "buyer": "AMN Healthcare Services",
        "seller": "Various staffing agencies",
        "deal_type": "strategic_acquisition",
        "year": 2022,
        "ev_mm": 1400.0,
        "ebitda_mm": 110.0,
        "ev_ebitda": 12.7,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Travel nursing demand surge post-COVID; supply normalization risk 2023-24",
    },
    # 231 — Outpatient behavioral health / SUD
    {
        "source_id": "seed_231",
        "deal_name": "Behavioral Health Group / Shore Capital",
        "source": "seed",
        "buyer": "Shore Capital Partners",
        "seller": "Founders",
        "deal_type": "lbo",
        "year": 2020,
        "ev_mm": 220.0,
        "ebitda_mm": 20.0,
        "ev_ebitda": 11.0,
        "hold_years": 5.0,
        "realized_moic": 4.2,
        "realized_irr": 0.38,
        "payer_mix": {"medicare": 0.08, "medicaid": 0.42, "commercial": 0.45, "self_pay": 0.05},
        "hospital_beds": None,
        "region": "Southeast",
        "state": "TN",
        "notes": "Opioid treatment programs (OTP) + outpatient SUD; methadone clinic network",
    },
    # 232 — Hospital-affiliated physician group
    {
        "source_id": "seed_232",
        "deal_name": "TeamHealth / Blackstone Secondary",
        "source": "seed",
        "buyer": "Blackstone (secondary from Blackstone)",
        "seller": "Blackstone (original)",
        "deal_type": "secondary_buyout",
        "year": 2020,
        "ev_mm": 6200.0,
        "ebitda_mm": 480.0,
        "ev_ebitda": 12.9,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.15, "commercial": 0.43, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "ER + hospital medicine physician staffing; NSA surprise billing risk; leveraged recap",
    },
    # 233 — Home-based waiver services / HCBS
    {
        "source_id": "seed_233",
        "deal_name": "Sevita (formerly RHA Health) / Charlesbank",
        "source": "seed",
        "buyer": "Charlesbank Capital Partners",
        "seller": "Leonard Green & Partners",
        "deal_type": "secondary_buyout",
        "year": 2021,
        "ev_mm": 2800.0,
        "ebitda_mm": 200.0,
        "ev_ebitda": 14.0,
        "hold_years": 4.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.88, "commercial": 0.05, "self_pay": 0.02},
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "I/DD + behavioral + complex care HCBS; heavy Medicaid HCBS waiver dependence",
    },
    # 234 — Academic medical center JV / health system
    {
        "source_id": "seed_234",
        "deal_name": "Allegheny Health Network / Highmark JV",
        "source": "seed",
        "buyer": "Highmark Health",
        "seller": "Allegheny Health System (acquired from bankruptcy)",
        "deal_type": "joint_venture",
        "year": 2018,
        "ev_mm": 1200.0,
        "ebitda_mm": 80.0,
        "ev_ebitda": 15.0,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.44, "medicaid": 0.22, "commercial": 0.32, "self_pay": 0.02},
        "hospital_beds": 1800,
        "region": "Northeast",
        "state": "PA",
        "notes": "Insurer-health system vertical integration; Blue Shield + hospital operating JV",
    },
    # 235 — International health IT export
    {
        "source_id": "seed_235",
        "deal_name": "Inovalon / Nordic Capital Take-Private",
        "source": "seed",
        "buyer": "Nordic Capital",
        "seller": "Public (Nasdaq: INVA)",
        "deal_type": "take_private",
        "year": 2022,
        "ev_mm": 7300.0,
        "ebitda_mm": 380.0,
        "ev_ebitda": 19.2,
        "hold_years": 5.0,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": None,
        "hospital_beds": None,
        "region": "National",
        "state": None,
        "notes": "Cloud analytics SaaS for payers/providers; real-world data + outcomes; $7.3B take-private",
    },
]
