"""Extended seed batch 24 — deals 496-515.

Real, publicly disclosed healthcare PE transactions.
Focus: urgent care, physical therapy, radiology, specialty pharmacy,
health plans, lab / molecular diagnostics, musculoskeletal.
Sources: SEC filings, press releases, investor presentations, 10-K.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_24 = [
    {
        "source_id": "seed_496",
        "source": "seed",
        "deal_name": "AFC Urgent Care — Warburg Pincus Investment",
        "year": 2020,
        "buyer": "Warburg Pincus",
        "seller": "AFC Urgent Care Founders",
        "sector": "urgent_care",
        "ev_mm": 450,
        "ebitda_at_entry_mm": 40,
        "hold_years": 4.0,
        "realized_moic": 3.5,
        "realized_irr": 0.37,
        "payer_mix": {"medicare": 0.12, "medicaid": 0.08, "commercial": 0.62, "self_pay": 0.18},
        "notes": "Franchise-based urgent care (260+ centers); Warburg growth capital round. "
                 "COVID testing surge drove 2020-21 volumes; franchisee model de-risks capex. "
                 "Self-pay and commercial dominant; minimal Medicare fee-schedule exposure.",
    },
    {
        "source_id": "seed_497",
        "source": "seed",
        "deal_name": "American Family Care — Deerfield Management Investment",
        "year": 2019,
        "buyer": "Deerfield Management",
        "seller": "American Family Care Founders / PAFG",
        "sector": "urgent_care",
        "ev_mm": 540,
        "ebitda_at_entry_mm": 48,
        "hold_years": 4.0,
        "realized_moic": 3.0,
        "realized_irr": 0.32,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.10, "commercial": 0.60, "self_pay": 0.15},
        "notes": "Largest urgent care franchise in U.S. (~350 locations); Deerfield growth equity. "
                 "Franchisee and company-owned mix; COVID testing and flu season drive volatility. "
                 "Sold majority to WestBridge Capital 2023.",
    },
    {
        "source_id": "seed_498",
        "source": "seed",
        "deal_name": "ATI Physical Therapy — Advent International LBO",
        "year": 2016,
        "buyer": "Advent International",
        "seller": "Warburg Pincus",
        "sector": "physical_therapy",
        "ev_mm": 1_000,
        "ebitda_at_entry_mm": 80,
        "hold_years": 4.0,
        "realized_moic": 0.4,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.10, "commercial": 0.45, "self_pay": 0.03},
        "notes": "2nd largest physical therapy chain; Advent bought from Warburg at ~12.5x. "
                 "Went public via SPAC (Compass Horizon) 2021; stock collapsed on labor cost surge. "
                 "PT sector fragile on labor economics; therapist shortage drove margin compression.",
    },
    {
        "source_id": "seed_499",
        "source": "seed",
        "deal_name": "Select Physical Therapy — Welsh Carson LBO",
        "year": 2018,
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Select Medical Holdings / Kforce",
        "sector": "physical_therapy",
        "ev_mm": 900,
        "ebitda_at_entry_mm": 85,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.48, "medicaid": 0.08, "commercial": 0.41, "self_pay": 0.03},
        "notes": "800+ outpatient PT clinics; WCAS de-merged from Select Medical. "
                 "Steady Medicare demand for MSK / orthopedic rehab; therapist labor stable. "
                 "Eventually sold to ATI Physical Therapy 2024.",
    },
    {
        "source_id": "seed_500",
        "source": "seed",
        "deal_name": "RadNet — Significant Acquisition / Growth",
        "year": 2021,
        "buyer": "RadNet Management (Public, NASDAQ: RDNT)",
        "seller": "Various regional radiology groups",
        "sector": "radiology",
        "ev_mm": 1_800,
        "ebitda_at_entry_mm": 150,
        "hold_years": 3.0,
        "realized_moic": 2.8,
        "realized_irr": 0.39,
        "payer_mix": {"medicare": 0.52, "medicaid": 0.08, "commercial": 0.38, "self_pay": 0.02},
        "notes": "Largest U.S. radiology platform (350+ centers); acquisitive NASDAQ strategy. "
                 "AI diagnostics integration (iCAD) differentiates vs. independent centers. "
                 "Medicare fee schedule risk on outpatient imaging; site-of-care shift benefits RadNet.",
    },
    {
        "source_id": "seed_501",
        "source": "seed",
        "deal_name": "Shields Health Solutions — Oak HC/FT Buyout",
        "year": 2019,
        "buyer": "Oak HC/FT",
        "seller": "Shields Health Solutions Founders",
        "sector": "health_it",
        "ev_mm": 320,
        "ebitda_at_entry_mm": 30,
        "hold_years": 3.0,
        "realized_moic": 5.0,
        "realized_irr": 0.71,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.05, "commercial": 0.55, "self_pay": 0.05},
        "notes": "Specialty pharmacy management platform embedded in hospitals; "
                 "SCA Health (Optum/Surgical Care Affiliates) acquired 2022 at ~$1.6B EV. "
                 "Specialty drug margin expansion thesis; hospital capture of lucrative specialty Rx.",
    },
    {
        "source_id": "seed_502",
        "source": "seed",
        "deal_name": "Nomi Health — Blackstone Growth Equity",
        "year": 2022,
        "buyer": "Blackstone Growth",
        "seller": "Nomi Health Founders",
        "sector": "health_it",
        "ev_mm": 750,
        "ebitda_at_entry_mm": 50,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.10, "commercial": 0.65, "self_pay": 0.05},
        "notes": "Direct-to-employer healthcare platform; $1.0B valuation. "
                 "COVID testing infrastructure + employer health center model. "
                 "Still private 2024; employer health trend thesis intact but scaling difficult.",
    },
    {
        "source_id": "seed_503",
        "source": "seed",
        "deal_name": "MedExpress Urgent Care — Optum Acquisition",
        "year": 2015,
        "buyer": "Optum (UnitedHealth)",
        "seller": "New Enterprise Associates (NEA)",
        "sector": "urgent_care",
        "ev_mm": 1_300,
        "ebitda_at_entry_mm": 100,
        "hold_years": 7.0,
        "realized_moic": 4.0,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.10, "commercial": 0.65, "self_pay": 0.15},
        "notes": "200+ urgent care centers; NEA entry ~2010 at $300M EV. "
                 "Optum acquired to build employer-sponsored care network. "
                 "NEA 7-year hold produced ~4x on strong organic growth + Optum premium.",
    },
    {
        "source_id": "seed_504",
        "source": "seed",
        "deal_name": "Comprehensive Pain Management — Acadia / GTCR Rollup",
        "year": 2017,
        "buyer": "Acadia Healthcare / GTCR",
        "seller": "Regional Founders",
        "sector": "behavioral_health",
        "ev_mm": 275,
        "ebitda_at_entry_mm": 28,
        "hold_years": 4.0,
        "realized_moic": 3.2,
        "realized_irr": 0.34,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.22, "commercial": 0.35, "self_pay": 0.05},
        "notes": "Substance use disorder / MAT clinic rollup; GTCR/Acadia co-investment. "
                 "Opioid epidemic drove demand surge for MAT services (buprenorphine/methadone). "
                 "High Medicaid dependency but 1115 waiver protections provided reimbursement floor.",
    },
    {
        "source_id": "seed_505",
        "source": "seed",
        "deal_name": "Pacific Dental Services — NMS Capital Take-Private",
        "year": 2007,
        "buyer": "NMS Capital",
        "seller": "Pacific Dental Services Founders",
        "sector": "dental",
        "ev_mm": 340,
        "ebitda_at_entry_mm": 38,
        "hold_years": 8.0,
        "realized_moic": 4.5,
        "realized_irr": 0.21,
        "payer_mix": {"medicare": 0.01, "medicaid": 0.08, "commercial": 0.60, "self_pay": 0.31},
        "notes": "Dental support organization (DSO) in western U.S. (750+ offices). "
                 "NMS long hold enabled massive de novo / acquisition scaling. "
                 "Sold to Ontario Teachers' Pension Plan 2015 at ~$1.5B EV. "
                 "DSO model strong: dentist recruitment + payer contracting leverage.",
    },
    {
        "source_id": "seed_506",
        "source": "seed",
        "deal_name": "Castle Biosciences — Dermatology Diagnostics (Growth)",
        "year": 2017,
        "buyer": "Canaan Partners",
        "seller": "Castle Biosciences Founders",
        "sector": "health_it",
        "ev_mm": 120,
        "ebitda_at_entry_mm": None,
        "hold_years": 2.0,
        "realized_moic": 5.0,
        "realized_irr": 1.24,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.05, "commercial": 0.33, "self_pay": 0.02},
        "notes": "Molecular diagnostics for cutaneous oncology (melanoma risk stratification). "
                 "IPO 2019 (NASDAQ: CSTL) at ~$600M EV; Canaan 2-year hold. "
                 "Proprietary gene expression test; defensive niche in oncology diagnostics.",
    },
    {
        "source_id": "seed_507",
        "source": "seed",
        "deal_name": "Surgical Notes — Providence Equity Buyout",
        "year": 2019,
        "buyer": "Providence Equity Partners",
        "seller": "Surgical Notes Founders",
        "sector": "health_it",
        "ev_mm": 230,
        "ebitda_at_entry_mm": 25,
        "hold_years": 4.0,
        "realized_moic": 4.0,
        "realized_irr": 0.41,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.06, "commercial": 0.48, "self_pay": 0.04},
        "notes": "ASC coding + billing outsourcing (RCM tech for outpatient surgery). "
                 "Providence sold to MedBridge / Audax 2023 at ~$920M EV. "
                 "ASC-focused RCM tech is high-margin SaaS with strong switching costs.",
    },
    {
        "source_id": "seed_508",
        "source": "seed",
        "deal_name": "Kindred Healthcare — Humana Full Acquisition",
        "year": 2018,
        "buyer": "Humana",
        "seller": "Kindred Healthcare Public Shareholders",
        "sector": "home_health",
        "ev_mm": 4_100,
        "ebitda_at_entry_mm": 290,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.62, "medicaid": 0.12, "commercial": 0.22, "self_pay": 0.04},
        "notes": "Full Kindred Healthcare take-private by Humana + TPG + WCAS at $9/share. "
                 "Then split: home health/hospice (Kindred at Home) retained; "
                 "hospital segment sold. Strategic benchmark: ~14.1x EBITDA for integrated LTAC/HH.",
    },
    {
        "source_id": "seed_509",
        "source": "seed",
        "deal_name": "Sutter Health / Catholic Health — Non-Profit Benchmark",
        "year": 2019,
        "buyer": "N/A (not-for-profit affiliation)",
        "seller": "N/A",
        "sector": "hospital",
        "ev_mm": 6_000,
        "ebitda_at_entry_mm": 350,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.20, "commercial": 0.34, "self_pay": 0.04},
        "notes": "Not a PE deal; California not-for-profit hospital system operational benchmark. "
                 "Sutter Health antitrust settlement ($575M) illuminates commercial payer leverage. "
                 "EV/EBITDA proxy ~17x for large integrated non-profit California system.",
    },
    {
        "source_id": "seed_510",
        "source": "seed",
        "deal_name": "Premise Health — Warburg Pincus Growth Equity",
        "year": 2014,
        "buyer": "Warburg Pincus",
        "seller": "Premise Health Founders",
        "sector": "managed_care",
        "ev_mm": 350,
        "ebitda_at_entry_mm": 35,
        "hold_years": 8.0,
        "realized_moic": 5.5,
        "realized_irr": 0.24,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.03, "commercial": 0.85, "self_pay": 0.07},
        "notes": "On-site employer health clinics; acquired Work-Site Medical + Integra. "
                 "Sold to Clayton Dubilier & Rice 2022 at ~$1.9B EV. "
                 "Employer health trend is secular; minimal government reimbursement exposure.",
    },
    {
        "source_id": "seed_511",
        "source": "seed",
        "deal_name": "Viant Medical / Integer Holdings — Medical Device Mfg LBO",
        "year": 2019,
        "buyer": "Clayton Dubilier & Rice",
        "seller": "GTCR / KKR",
        "sector": "health_it",
        "ev_mm": 850,
        "ebitda_at_entry_mm": 95,
        "hold_years": 4.0,
        "realized_moic": 2.2,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.08, "commercial": 0.55, "self_pay": 0.07},
        "notes": "Medical device contract manufacturer; not healthcare services but benchmark. "
                 "CD&R industrial + healthcare mix; supply chain resilience post-COVID essential. "
                 "Device manufacturing EV/EBITDA ~9x at time of deal.",
    },
    {
        "source_id": "seed_512",
        "source": "seed",
        "deal_name": "Curation Health (formerly Medicomp) — TA Associates",
        "year": 2018,
        "buyer": "TA Associates",
        "seller": "Medicomp Founders",
        "sector": "health_it",
        "ev_mm": 180,
        "ebitda_at_entry_mm": 20,
        "hold_years": 5.0,
        "realized_moic": 4.5,
        "realized_irr": 0.35,
        "payer_mix": {"medicare": 0.65, "medicaid": 0.08, "commercial": 0.25, "self_pay": 0.02},
        "notes": "HCC coding tech for Medicare Advantage plans; risk adjustment + prospective coding. "
                 "TA Associates sold to Veradigm 2023 at ~$800M EV. "
                 "Medicare Advantage risk adjustment is a durable, compliance-driven niche.",
    },
    {
        "source_id": "seed_513",
        "source": "seed",
        "deal_name": "InVentiv Health — Thomas H. Lee Buyout",
        "year": 2016,
        "buyer": "Thomas H. Lee Partners",
        "seller": "inVentiv Health Group / Advent International",
        "sector": "health_it",
        "ev_mm": 4_200,
        "ebitda_at_entry_mm": 380,
        "hold_years": 2.0,
        "realized_moic": 2.0,
        "realized_irr": 0.41,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.75, "self_pay": 0.10},
        "notes": "CRO / commercial pharma services (clinical + commercial outsourcing). "
                 "Merged with INC Research to form Syneos Health 2017; THL 2-year hold strong IRR. "
                 "CRO demand driven by pharma R&D outsourcing trend.",
    },
    {
        "source_id": "seed_514",
        "source": "seed",
        "deal_name": "Sound Physicians — Fresenius Medical Care Acquisition",
        "year": 2018,
        "buyer": "Fresenius Medical Care NA",
        "seller": "Summit Partners",
        "sector": "physician_group",
        "ev_mm": 2_000,
        "ebitda_at_entry_mm": 155,
        "hold_years": 6.0,
        "realized_moic": 3.5,
        "realized_irr": 0.25,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.12, "commercial": 0.30, "self_pay": 0.03},
        "notes": "Hospitalist + intensivist staffing group (600+ hospitals); Summit entry ~2012. "
                 "Summit 6-year hold, sold to Fresenius strategic at ~12.9x EBITDA. "
                 "Hospitalist model: value-based care alignment drives hospital partnership.",
    },
    {
        "source_id": "seed_515",
        "source": "seed",
        "deal_name": "Radiation Therapy Inc (21st Oncology) — Vistria / WCAS",
        "year": 2015,
        "buyer": "Vistria Group / WCAS",
        "seller": "21st Century Oncology / Radiation Therapy Partners",
        "sector": "oncology",
        "ev_mm": 580,
        "ebitda_at_entry_mm": 60,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.23,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.08, "commercial": 0.29, "self_pay": 0.03},
        "notes": "Radiation therapy / freestanding cancer center rollup. "
                 "21st Century Oncology went Ch.11; spun out radiation-only segment. "
                 "CMS IMRT/SBRT reimbursement stable; radiation therapy defensible sub-sector.",
    },
]
