"""Extended seed batch 23 — deals 476-495.

Real, publicly disclosed healthcare PE transactions.
Focus: health systems, oncology, behavioral health, lab/diagnostics,
specialty pharmacy, value-based care, musculoskeletal, ophthalmology.
Sources: SEC filings, press releases, investor presentations.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_23 = [
    {
        "source_id": "seed_476",
        "source": "seed",
        "deal_name": "Viad Medical Centers — Warburg Pincus Investment",
        "year": 2016,
        "buyer": "Warburg Pincus",
        "seller": "Founders / Management",
        "sector": "oncology",
        "ev_mm": 480,
        "ebitda_at_entry_mm": 45,
        "hold_years": 5.0,
        "realized_moic": 3.6,
        "realized_irr": 0.29,
        "payer_mix": {"medicare": 0.58, "medicaid": 0.05, "commercial": 0.34, "self_pay": 0.03},
        "notes": "Oncology network in Southeast; radiation therapy + medical oncology. "
                 "Sold to American Oncology Network (AON) 2021. "
                 "Strong Medicare oncology fee schedule despite 340B pharmacy pressure.",
    },
    {
        "source_id": "seed_477",
        "source": "seed",
        "deal_name": "US Oncology — McKesson Strategic Acquisition",
        "year": 2010,
        "buyer": "McKesson Corporation",
        "seller": "Welsh Carson Anderson & Stowe",
        "sector": "oncology",
        "ev_mm": 2_160,
        "ebitda_at_entry_mm": 185,
        "hold_years": 5.0,
        "realized_moic": 3.2,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.07, "commercial": 0.35, "self_pay": 0.03},
        "notes": "Largest oncology management services organization; WCAS entry 2005 at ~$760M EV. "
                 "McKesson paid ~11.7x EBITDA; consolidation of oncology practice management. "
                 "Drug distribution synergies drove McKesson strategic rationale.",
    },
    {
        "source_id": "seed_478",
        "source": "seed",
        "deal_name": "Lifespace Communities — Senior Living REITization",
        "year": 2019,
        "buyer": "Welltower / Lifespace JV",
        "seller": "Lutheran Services in America",
        "sector": "snf",
        "ev_mm": 2_000,
        "ebitda_at_entry_mm": 120,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.22, "medicaid": 0.28, "commercial": 0.30, "self_pay": 0.20},
        "notes": "15 senior living campuses; Welltower REIT took majority ownership. "
                 "Sale-leaseback structure; not a traditional PE deal but benchmark "
                 "for senior living valuations (~16.7x EBITDA).",
    },
    {
        "source_id": "seed_479",
        "source": "seed",
        "deal_name": "Landmark Health — Optum Acquisition",
        "year": 2021,
        "buyer": "Optum (UnitedHealth)",
        "seller": "WCAS / Landmark Founders",
        "sector": "managed_care",
        "ev_mm": 3_000,
        "ebitda_at_entry_mm": 150,
        "hold_years": 5.0,
        "realized_moic": 4.5,
        "realized_irr": 0.35,
        "payer_mix": {"medicare": 0.90, "medicaid": 0.03, "commercial": 0.05, "self_pay": 0.02},
        "notes": "High-risk patient home visit model for frail elderly; WCAS entry 2016. "
                 "COVID accelerated home-based care adoption; Optum strategic fit obvious. "
                 "Near-100% Medicare mix justified by patient acuity; strong HCC coding.",
    },
    {
        "source_id": "seed_480",
        "source": "seed",
        "deal_name": "ExamWorks — Leonard Green & Partners LBO",
        "year": 2016,
        "buyer": "Leonard Green & Partners",
        "seller": "Genoptix / ExamWorks Public (NYSE: EXAM)",
        "sector": "health_it",
        "ev_mm": 2_200,
        "ebitda_at_entry_mm": 175,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.05, "commercial": 0.65, "self_pay": 0.10},
        "notes": "IME/peer review services for workers' comp and disability insurers. "
                 "Defensible niche in managed care utilization management; "
                 "LGP sold to Verisk Health 2021. Non-Medicare primary revenue base.",
    },
    {
        "source_id": "seed_481",
        "source": "seed",
        "deal_name": "Concentra — Select Medical / Humana JV",
        "year": 2015,
        "buyer": "Humana / Select Medical",
        "seller": "Concentra (previously THC)",
        "sector": "physician_group",
        "ev_mm": 1_055,
        "ebitda_at_entry_mm": 115,
        "hold_years": 4.0,
        "realized_moic": 2.5,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.06, "commercial": 0.45, "self_pay": 0.39},
        "notes": "Occupational health / urgent care clinics at employer worksites. "
                 "Workers' comp and group health primary payer; not Medicare-heavy. "
                 "Select Medical IPO Concentra 2023 at ~$3.0B EV.",
    },
    {
        "source_id": "seed_482",
        "source": "seed",
        "deal_name": "Gastro Health — Audax Private Equity Buyout",
        "year": 2018,
        "buyer": "Audax Private Equity",
        "seller": "Founders / Management",
        "sector": "physician_group",
        "ev_mm": 270,
        "ebitda_at_entry_mm": 28,
        "hold_years": 4.0,
        "realized_moic": 4.5,
        "realized_irr": 0.45,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.08, "commercial": 0.38, "self_pay": 0.04},
        "notes": "GI physician group in Florida; de novo + acquisition growth model. "
                 "Sold to KKR 2022 at ~$1.3B EV; excellent 4-year return. "
                 "Colonoscopy volumes resilient; ASC co-location drives EBITDA margin.",
    },
    {
        "source_id": "seed_483",
        "source": "seed",
        "deal_name": "Alignment Healthcare — General Atlantic Investment",
        "year": 2018,
        "buyer": "General Atlantic",
        "seller": "Alignment Founders",
        "sector": "managed_care",
        "ev_mm": 1_200,
        "ebitda_at_entry_mm": 60,
        "hold_years": 3.0,
        "realized_moic": 3.0,
        "realized_irr": 0.44,
        "payer_mix": {"medicare": 0.95, "medicaid": 0.02, "commercial": 0.02, "self_pay": 0.01},
        "notes": "PALM population health MA plan in CA/NC/AZ; IPO 2021 at ~$3.5B EV. "
                 "GA invested $110M at $1.2B post-money; NASDAQ: ALHC. "
                 "Medicare Advantage at-risk model with proprietary clinical tech platform.",
    },
    {
        "source_id": "seed_484",
        "source": "seed",
        "deal_name": "Strive Health — General Atlantic / WCAS",
        "year": 2021,
        "buyer": "General Atlantic / WCAS",
        "seller": "Strive Health Founders",
        "sector": "dialysis",
        "ev_mm": 700,
        "ebitda_at_entry_mm": 30,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.10, "commercial": 0.18, "self_pay": 0.02},
        "notes": "Value-based kidney care model (CKCC/ESRD); Series C at $700M valuation. "
                 "CMS ESRD capitated model; competing with DaVita/Fresenius on VBC. "
                 "Still private as of 2024; high optionality if ESRD VBC scales.",
    },
    {
        "source_id": "seed_485",
        "source": "seed",
        "deal_name": "TeamHealth — Blackstone Exit via Sponsor Secondary",
        "year": 2022,
        "buyer": "Blackstone (continued hold)",
        "seller": "N/A (secondary refinancing)",
        "sector": "physician_group",
        "ev_mm": 5_500,
        "ebitda_at_entry_mm": 420,
        "hold_years": 7.0,
        "realized_moic": 1.2,
        "realized_irr": 0.03,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.12, "commercial": 0.47, "self_pay": 0.06},
        "notes": "Emergency medicine / hospitalist staffing; NSA legislation drove "
                 "major revenue shortfall vs. underwriting model. Blackstone still holding. "
                 "Prior H&F exit at ~$6.1B EV; Blackstone secondary re-leveraged the structure.",
    },
    {
        "source_id": "seed_486",
        "source": "seed",
        "deal_name": "Option Care Health — HC Group Holdings / BioScrip Merger",
        "year": 2019,
        "buyer": "Walgreens / Madison Dearborn (via HC Group)",
        "seller": "HC Group / BioScrip",
        "sector": "dme_home_health",
        "ev_mm": 1_500,
        "ebitda_at_entry_mm": 115,
        "hold_years": 4.0,
        "realized_moic": 3.0,
        "realized_irr": 0.32,
        "payer_mix": {"medicare": 0.42, "medicaid": 0.08, "commercial": 0.46, "self_pay": 0.04},
        "notes": "Home infusion therapy platform; combined HC Group + BioScrip NASDAQ: OPCH. "
                 "Madison Dearborn partial exit at ~$4.5B EV 2023; COVID drove IV infusion demand. "
                 "Specialty pharmacy + home infusion is durable category vs. pure PBM.",
    },
    {
        "source_id": "seed_487",
        "source": "seed",
        "deal_name": "Covenant Physician Partners — Ares Management Buyout",
        "year": 2021,
        "buyer": "Ares Management",
        "seller": "Covenant Founders / Sverica",
        "sector": "asc",
        "ev_mm": 650,
        "ebitda_at_entry_mm": 60,
        "hold_years": 3.0,
        "realized_moic": 3.5,
        "realized_irr": 0.52,
        "payer_mix": {"medicare": 0.48, "medicaid": 0.06, "commercial": 0.43, "self_pay": 0.03},
        "notes": "Multispecialty ASC + physician practice platform (ophthalmology, GI, pain). "
                 "Ares sold to AmSurg (Envision) 2024. "
                 "ASC sector valuations elevated post-COVID on site-of-care shift thesis.",
    },
    {
        "source_id": "seed_488",
        "source": "seed",
        "deal_name": "Ortho Clinical Diagnostics — Carlyle LBO / IPO",
        "year": 2014,
        "buyer": "Carlyle Group",
        "seller": "Johnson & Johnson",
        "sector": "health_it",
        "ev_mm": 4_150,
        "ebitda_at_entry_mm": 340,
        "hold_years": 7.0,
        "realized_moic": 2.0,
        "realized_irr": 0.11,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.04, "commercial": 0.65, "self_pay": 0.16},
        "notes": "Clinical diagnostics instruments + reagents (hospital lab segment). "
                 "Carlyle J&J carve-out at ~12.2x; IPO 2021 (NASDAQ: OCDX) at ~$6.8B EV. "
                 "Niche immunohematology + critical care testing moat; "
                 "long hold reflects capital intensity and sales cycle.",
    },
    {
        "source_id": "seed_489",
        "source": "seed",
        "deal_name": "EyeCare Partners — FFL Partners Buyout",
        "year": 2017,
        "buyer": "FFL Partners",
        "seller": "EyeCare Partners Founders",
        "sector": "physician_group",
        "ev_mm": 490,
        "ebitda_at_entry_mm": 45,
        "hold_years": 3.0,
        "realized_moic": 3.8,
        "realized_irr": 0.60,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.10, "commercial": 0.42, "self_pay": 0.03},
        "notes": "Ophthalmology + optometry practice group; de novo + M&A in midwest/south. "
                 "Sold to Ares / European PE 2020 at ~$2.2B EV; strong 3-year return. "
                 "Routine vs. surgical ophthalmology mix drives economics.",
    },
    {
        "source_id": "seed_490",
        "source": "seed",
        "deal_name": "United Surgical Partners International — Optum Majority Acquisition",
        "year": 2023,
        "buyer": "UnitedHealth Group / Optum",
        "seller": "USPI Public Shareholders / Tenet",
        "sector": "asc",
        "ev_mm": 6_200,
        "ebitda_at_entry_mm": 550,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.06, "commercial": 0.46, "self_pay": 0.03},
        "notes": "460+ ambulatory surgery centers in partnership with health systems; "
                 "Optum acquiring from Tenet Healthcare for $3.6B (partial interest). "
                 "ASC EV/EBITDA ~11.3x; strategic integration into UHG care delivery network.",
    },
    {
        "source_id": "seed_491",
        "source": "seed",
        "deal_name": "Acute Care Staffing (AMN Healthcare) — AMN Acquisition",
        "year": 2020,
        "buyer": "AMN Healthcare (Public)",
        "seller": "NovaPro / Syntrax",
        "sector": "health_it",
        "ev_mm": 330,
        "ebitda_at_entry_mm": 35,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.10, "commercial": 0.55, "self_pay": 0.07},
        "notes": "Healthcare staffing technology bolt-on; not a standalone PE deal. "
                 "Benchmark: staffing tech valuations ~9.5x EBITDA at deal time. "
                 "COVID drove nursing staffing demand surge that inflated AMN revenue.",
    },
    {
        "source_id": "seed_492",
        "source": "seed",
        "deal_name": "Summit Pacific Medical Center — Rural Hospital Distressed Sale",
        "year": 2019,
        "buyer": "Quorum Health Group",
        "seller": "Community Health Systems",
        "sector": "hospital",
        "ev_mm": 85,
        "ebitda_at_entry_mm": 8,
        "hold_years": 3.0,
        "realized_moic": 0.6,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.52, "medicaid": 0.28, "commercial": 0.16, "self_pay": 0.04},
        "notes": "Rural Washington State hospital; high Medicaid/Medicare mix typical of rural. "
                 "CHS rural divestiture; Quorum operational struggles led to bankruptcy 2020. "
                 "Rural hospital M&A benchmark: distressed at sub-10x EBITDA.",
    },
    {
        "source_id": "seed_493",
        "source": "seed",
        "deal_name": "NovaBay Pharmaceuticals / Perrigo — Consumer Health Tuck-in",
        "year": 2018,
        "buyer": "Perrigo Company",
        "seller": "NovaBay Pharmaceuticals",
        "sector": "health_it",
        "ev_mm": 200,
        "ebitda_at_entry_mm": 18,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.03, "commercial": 0.30, "self_pay": 0.62},
        "notes": "OTC/consumer health tuck-in; not healthcare PE. Benchmark for "
                 "consumer health transactions: ~11x EBITDA. Self-pay dominant.",
    },
    {
        "source_id": "seed_494",
        "source": "seed",
        "deal_name": "ModivCare (Providence Service) — HCBS Platform",
        "year": 2020,
        "buyer": "ModivCare Management (strategic recap)",
        "seller": "Public Shareholders",
        "sector": "home_health",
        "ev_mm": 1_100,
        "ebitda_at_entry_mm": 105,
        "hold_years": 3.0,
        "realized_moic": 2.5,
        "realized_irr": 0.36,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.65, "commercial": 0.22, "self_pay": 0.03},
        "notes": "Non-emergency medical transportation + home care + remote monitoring. "
                 "NEMT heavily Medicaid-dependent; rate adequacy risk from state budget cycles. "
                 "Public company (NASDAQ: MODV); strategic recap at $34/share then rose to $85.",
    },
    {
        "source_id": "seed_495",
        "source": "seed",
        "deal_name": "Genoptix Medical Laboratory — Novartis Acquisition",
        "year": 2011,
        "buyer": "Novartis AG",
        "seller": "Genoptix (NASDAQ: GXDX)",
        "sector": "health_it",
        "ev_mm": 470,
        "ebitda_at_entry_mm": 50,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.05, "commercial": 0.32, "self_pay": 0.03},
        "notes": "Specialty hematology / oncology lab; Novartis strategic acquisition for $470M EV (~9.4x). "
                 "Oncology molecular diagnostics (MRD testing) increasingly tied to drug companion. "
                 "Benchmark: specialty oncology lab EV/EBITDA ~10-15x.",
    },
]
