"""Extended seed deals #66 — primary care theme.

This module provides a curated list of 15 healthcare private equity deals
focused on primary care, including multi-site primary care rollups, direct
primary care (DPC) membership platforms, concierge medicine practices,
value-based primary care risk-bearing groups, and senior-focused primary
care (Medicare Advantage-heavy) clinic chains.

Each deal is represented as a dict with exactly 17 keys covering deal
identity, financial metrics, payer mix, geography, sponsor, and status.
IRR is derived from MOIC and hold period; EBITDA and revenue are derived
from EV, EV/EBITDA, and EBITDA margin. Senior primary care deals carry a
Medicare-heavy payer mix reflecting their MA-aligned capitation economics.
"""

EXTENDED_SEED_DEALS_66 = [
    {
        "company_name": "Summit Primary Care Partners",
        "sector": "Primary Care",
        "subsector": "Multi-site Primary Care Rollup",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 33.6,
        "revenue_mm": 186.67,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": round(2.4 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.58, "medicare": 0.28, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "General Atlantic",
        "status": "Realized",
    },
    {
        "company_name": "MainStreet Direct Primary Care",
        "sector": "Direct Primary Care",
        "subsector": "Employer-Sponsored DPC Membership",
        "year": 2020,
        "ev_mm": 145.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 9.67,
        "revenue_mm": 48.35,
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": round(2.1 ** (1 / 4.0) - 1, 4),
        "payer_mix": {"commercial": 0.72, "medicare": 0.08, "medicaid": 0.04, "self_pay": 0.16},
        "comm_pct": 0.72,
        "region": "Southeast",
        "buyer": "Oak HC/FT",
        "status": "Active",
    },
    {
        "company_name": "Crestline Concierge Medicine Group",
        "sector": "Concierge Medicine",
        "subsector": "Retainer-Based Concierge Practices",
        "year": 2019,
        "ev_mm": 210.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 15.0,
        "revenue_mm": 60.0,
        "ebitda_margin": 0.25,
        "hold_years": 5.5,
        "moic": 2.8,
        "irr": round(2.8 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.65, "medicare": 0.15, "medicaid": 0.02, "self_pay": 0.18},
        "comm_pct": 0.65,
        "region": "West",
        "buyer": "TPG",
        "status": "Partially Realized",
    },
    {
        "company_name": "SilverOak Senior Primary Care",
        "sector": "Senior Primary Care",
        "subsector": "Medicare Advantage-aligned Senior Clinics",
        "year": 2021,
        "ev_mm": 980.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": 52.97,
        "revenue_mm": 294.28,
        "ebitda_margin": 0.18,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": round(1.9 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.05, "medicare": 0.82, "medicaid": 0.10, "self_pay": 0.03},
        "comm_pct": 0.05,
        "region": "Southeast",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
    {
        "company_name": "Heartland Value Care Medical Group",
        "sector": "Value-Based Care",
        "subsector": "Risk-Bearing Primary Care IPA",
        "year": 2020,
        "ev_mm": 560.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 33.94,
        "revenue_mm": 169.7,
        "ebitda_margin": 0.20,
        "hold_years": 4.5,
        "moic": 2.6,
        "irr": round(2.6 ** (1 / 4.5) - 1, 4),
        "payer_mix": {"commercial": 0.35, "medicare": 0.45, "medicaid": 0.16, "self_pay": 0.04},
        "comm_pct": 0.35,
        "region": "Midwest",
        "buyer": "Warburg Pincus",
        "status": "Active",
    },
    {
        "company_name": "BlueSky Family Medicine Holdings",
        "sector": "Primary Care",
        "subsector": "Suburban Family Medicine Platform",
        "year": 2017,
        "ev_mm": 245.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 21.3,
        "revenue_mm": 142.0,
        "ebitda_margin": 0.15,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": round(3.1 ** (1 / 6.0) - 1, 4),
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.11, "self_pay": 0.04},
        "comm_pct": 0.55,
        "region": "Midwest",
        "buyer": "Thomas H. Lee",
        "status": "Realized",
    },
    {
        "company_name": "EverWell Direct Primary Care Network",
        "sector": "Direct Primary Care",
        "subsector": "Consumer Subscription DPC",
        "year": 2022,
        "ev_mm": 85.0,
        "ev_ebitda": 17.0,
        "ebitda_mm": 5.0,
        "revenue_mm": 27.78,
        "ebitda_margin": 0.18,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": round(1.6 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.60, "medicare": 0.05, "medicaid": 0.03, "self_pay": 0.32},
        "comm_pct": 0.60,
        "region": "West",
        "buyer": "New Enterprise Associates",
        "status": "Active",
    },
    {
        "company_name": "Pinnacle Concierge Health",
        "sector": "Concierge Medicine",
        "subsector": "Executive Health & Concierge",
        "year": 2016,
        "ev_mm": 95.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 7.31,
        "revenue_mm": 32.49,
        "ebitda_margin": 0.225,
        "hold_years": 6.5,
        "moic": 3.4,
        "irr": round(3.4 ** (1 / 6.5) - 1, 4),
        "payer_mix": {"commercial": 0.68, "medicare": 0.12, "medicaid": 0.02, "self_pay": 0.18},
        "comm_pct": 0.68,
        "region": "Northeast",
        "buyer": "Cressey",
        "status": "Realized",
    },
    {
        "company_name": "EvergreenMD Senior Care Centers",
        "sector": "Senior Primary Care",
        "subsector": "Full-Risk Senior Primary Care Clinics",
        "year": 2019,
        "ev_mm": 1280.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 64.0,
        "revenue_mm": 355.56,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 3.0,
        "irr": round(3.0 ** (1 / 5.0) - 1, 4),
        "payer_mix": {"commercial": 0.04, "medicare": 0.85, "medicaid": 0.08, "self_pay": 0.03},
        "comm_pct": 0.04,
        "region": "National",
        "buyer": "Bain Capital",
        "status": "Partially Realized",
    },
    {
        "company_name": "Cornerstone Primary Care Alliance",
        "sector": "Primary Care",
        "subsector": "Independent Physician Association",
        "year": 2018,
        "ev_mm": 175.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 16.67,
        "revenue_mm": 111.13,
        "ebitda_margin": 0.15,
        "hold_years": 5.5,
        "moic": 2.5,
        "irr": round(2.5 ** (1 / 5.5) - 1, 4),
        "payer_mix": {"commercial": 0.50, "medicare": 0.30, "medicaid": 0.16, "self_pay": 0.04},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "Clayton Dubilier & Rice",
        "status": "Realized",
    },
    {
        "company_name": "Cascade Value Primary Care",
        "sector": "Value-Based Care",
        "subsector": "ACO-Enabled Primary Care Platform",
        "year": 2023,
        "ev_mm": 340.0,
        "ev_ebitda": 19.5,
        "ebitda_mm": 17.44,
        "revenue_mm": 87.2,
        "ebitda_margin": 0.20,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": round(1.4 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.40, "medicare": 0.42, "medicaid": 0.14, "self_pay": 0.04},
        "comm_pct": 0.40,
        "region": "West",
        "buyer": "Oak HC/FT",
        "status": "Active",
    },
    {
        "company_name": "GraniteCare Family Practice Group",
        "sector": "Primary Care",
        "subsector": "Rural & Small-Town Primary Care",
        "year": 2017,
        "ev_mm": 68.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 6.8,
        "revenue_mm": 53.12,
        "ebitda_margin": 0.128,
        "hold_years": 6.0,
        "moic": 2.2,
        "irr": round(2.2 ** (1 / 6.0) - 1, 4),
        "payer_mix": {"commercial": 0.45, "medicare": 0.33, "medicaid": 0.18, "self_pay": 0.04},
        "comm_pct": 0.45,
        "region": "Midwest",
        "buyer": "Cressey",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Executive Concierge Clinics",
        "sector": "Concierge Medicine",
        "subsector": "High-End Concierge & Executive Physicals",
        "year": 2021,
        "ev_mm": 125.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 8.62,
        "revenue_mm": 35.92,
        "ebitda_margin": 0.24,
        "hold_years": 3.5,
        "moic": 1.7,
        "irr": round(1.7 ** (1 / 3.5) - 1, 4),
        "payer_mix": {"commercial": 0.62, "medicare": 0.16, "medicaid": 0.02, "self_pay": 0.20},
        "comm_pct": 0.62,
        "region": "Northeast",
        "buyer": "TPG",
        "status": "Active",
    },
    {
        "company_name": "Legacy Senior Health Medical",
        "sector": "Senior Primary Care",
        "subsector": "Dual-Eligible Senior Primary Care",
        "year": 2022,
        "ev_mm": 720.0,
        "ev_ebitda": 17.8,
        "ebitda_mm": 40.45,
        "revenue_mm": 224.72,
        "ebitda_margin": 0.18,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": round(1.5 ** (1 / 3.0) - 1, 4),
        "payer_mix": {"commercial": 0.03, "medicare": 0.78, "medicaid": 0.16, "self_pay": 0.03},
        "comm_pct": 0.03,
        "region": "National",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
    {
        "company_name": "Northwind Capitated Primary Care",
        "sector": "Value-Based Care",
        "subsector": "Medicare Shared Savings Primary Care",
        "year": 2024,
        "ev_mm": 48.0,
        "ev_ebitda": 21.5,
        "ebitda_mm": 2.23,
        "revenue_mm": 17.15,
        "ebitda_margin": 0.13,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": round(1.5 ** (1 / 2.5) - 1, 4),
        "payer_mix": {"commercial": 0.32, "medicare": 0.48, "medicaid": 0.16, "self_pay": 0.04},
        "comm_pct": 0.32,
        "region": "Midwest",
        "buyer": "Warburg Pincus",
        "status": "Active",
    },
]
