"""Extended seed batch 18 — deals 376-395."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_18: List[Dict[str, Any]] = [
    {
        "source_id": "seed_376",
        "deal_name": "Lifespace Communities / Ryan Companies senior living",
        "buyer": "Ryan Companies / Welltower REIT",
        "seller": "Lutheran Life Communities",
        "year": 2020,
        "deal_type": "reit",
        "sector": "senior_living",
        "ev_mm": 850.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 65.0,
        "revenue_mm": 420.0,
        "realized_moic": 2.1,
        "realized_irr": 0.16,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.20, "commercial": 0.05, "self_pay": 0.45},
        "geography": "Midwest",
        "hospital_beds": 2800,
        "source": "seed",
        "notes": "CCRCs + ILF + ALF sale-leaseback to Welltower; COVID occupancy risk absorbed by REIT structure",
    },
    {
        "source_id": "seed_377",
        "deal_name": "LabCorp / Covance CRO integration",
        "buyer": "Laboratory Corporation of America",
        "seller": "Covance shareholders",
        "year": 2015,
        "deal_type": "merger",
        "sector": "lab",
        "ev_mm": 6100.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 436.0,
        "revenue_mm": 2600.0,
        "realized_moic": 2.8,
        "realized_irr": 0.20,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.10, "commercial": 0.50, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Lab diagnostics + CRO integration; COVID testing surge 2020-21 provided unexpected EBITDA tailwind",
    },
    {
        "source_id": "seed_378",
        "deal_name": "DaVita Medical Group / Optum carve-out (VillageMD era)",
        "buyer": "Optum / UnitedHealth Group",
        "seller": "DaVita Inc.",
        "year": 2019,
        "deal_type": "carve-out",
        "sector": "primary_care",
        "ev_mm": 4900.0,
        "ev_ebitda": 25.0,
        "ebitda_mm": 196.0,
        "revenue_mm": 1700.0,
        "realized_moic": 3.5,
        "realized_irr": 0.29,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.80, "medicaid": 0.10, "commercial": 0.08, "self_pay": 0.02},
        "geography": "West",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Value-based primary care for MA patients; capitation model for complex patients; Optum absorbed into integrated delivery",
    },
    {
        "source_id": "seed_379",
        "deal_name": "MedQuist / Nuance Communications health IT acquisition",
        "buyer": "Nuance Communications / Microsoft acquisition",
        "seller": "MedQuist Holdings",
        "year": 2011,
        "deal_type": "merger",
        "sector": "health_it",
        "ev_mm": 360.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 33.0,
        "revenue_mm": 340.0,
        "realized_moic": 2.5,
        "realized_irr": 0.18,
        "hold_years": 5.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Clinical documentation + CDI SaaS; AI-assisted medical transcription; Microsoft acquired Nuance for $19B in 2022",
    },
    {
        "source_id": "seed_380",
        "deal_name": "Bright Health / New Enterprise Associates growth equity",
        "buyer": "New Enterprise Associates / multiple VCs",
        "seller": "Founders",
        "year": 2016,
        "deal_type": "growth_equity",
        "sector": "managed_care",
        "ev_mm": 500.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 100.0,
        "realized_moic": 0.1,
        "realized_irr": -0.40,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.60, "medicaid": 0.10, "commercial": 0.30, "self_pay": 0.0},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "MA plan startup disaster; expanded too fast; raised $1.5B+ total; delisted 2023 after stock fell 99%",
    },
    {
        "source_id": "seed_381",
        "deal_name": "CONMED Corporation / Gyrus Medical acquisition",
        "buyer": "CONMED Corporation strategic",
        "seller": "Olympus / Gyrus Medical",
        "year": 2017,
        "deal_type": "add-on",
        "sector": "asc",
        "ev_mm": 740.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 46.0,
        "revenue_mm": 220.0,
        "realized_moic": 2.6,
        "realized_irr": 0.20,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.25, "medicaid": 0.05, "commercial": 0.65, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Surgical instruments + electrosurgical platform; ASC site-of-care shift drove capital equipment demand",
    },
    {
        "source_id": "seed_382",
        "deal_name": "Precision Medicine Group / Warburg Pincus growth equity",
        "buyer": "Warburg Pincus",
        "seller": "Founders / employees",
        "year": 2016,
        "deal_type": "growth_equity",
        "sector": "lab",
        "ev_mm": 450.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 220.0,
        "realized_moic": 3.8,
        "realized_irr": 0.32,
        "hold_years": 5.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Oncology CRO + molecular pathology lab; COVID trial activity + oncology drug pipeline drove demand",
    },
    {
        "source_id": "seed_383",
        "deal_name": "EXL Health / Outsourced RCM division growth",
        "buyer": "EXL Service Holdings",
        "seller": "Various hospital clients",
        "year": 2018,
        "deal_type": "growth_equity",
        "sector": "rcm",
        "ev_mm": 800.0,
        "ev_ebitda": 18.0,
        "ebitda_mm": 44.0,
        "revenue_mm": 220.0,
        "realized_moic": 3.2,
        "realized_irr": 0.27,
        "hold_years": 4.0,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Healthcare BPO + RCM outsourcing for payers and providers; value-based contract analytics drove premium retention",
    },
    {
        "source_id": "seed_384",
        "deal_name": "Advanced ICU Care / WindRose Health Investors growth equity",
        "buyer": "WindRose Health Investors",
        "seller": "Mercy Health (legacy investor)",
        "year": 2018,
        "deal_type": "growth_equity",
        "sector": "health_it",
        "ev_mm": 200.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 13.0,
        "revenue_mm": 65.0,
        "realized_moic": 4.1,
        "realized_irr": 0.35,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.15, "commercial": 0.28, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Tele-ICU + critical care telemedicine; COVID dramatically expanded demand for remote intensivist coverage",
    },
    {
        "source_id": "seed_385",
        "deal_name": "United Behavioral Health / Optum BH carve-out",
        "buyer": "Optum / UnitedHealth Group",
        "seller": "UBH public division",
        "year": 2015,
        "deal_type": "carve-out",
        "sector": "behavioral_health",
        "ev_mm": 4800.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 300.0,
        "revenue_mm": 4200.0,
        "realized_moic": 3.1,
        "realized_irr": 0.25,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.35, "commercial": 0.45, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest US managed BH carve-out; integration with PCP practices for collaborative care; DOJ scrutiny on network adequacy",
    },
    {
        "source_id": "seed_386",
        "deal_name": "Adreima / Revenue Cycle Management add-on (Ensemble Health)",
        "buyer": "Ensemble Health Partners / Golden Gate Capital",
        "seller": "OhioHealth system spinout",
        "year": 2020,
        "deal_type": "carve-out",
        "sector": "rcm",
        "ev_mm": 1800.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 90.0,
        "revenue_mm": 430.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Health system RCM spinout; Ensemble Health grew rapidly through health system outsourcing; recapitalized at >$5B",
    },
    {
        "source_id": "seed_387",
        "deal_name": "Ardent Health Services / Equity Group Investments LBO",
        "buyer": "Equity Group Investments (Zell)",
        "seller": "Universal Health Services legacy",
        "year": 2015,
        "deal_type": "lbo",
        "sector": "hospital",
        "ev_mm": 2000.0,
        "ev_ebitda": 7.5,
        "ebitda_mm": 267.0,
        "revenue_mm": 2800.0,
        "realized_moic": 2.2,
        "realized_irr": 0.16,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.25, "commercial": 0.30, "self_pay": 0.05},
        "geography": "Southwest",
        "hospital_beds": 8400,
        "source": "seed",
        "notes": "Regional hospital chain; IPO'd 2024 at ~$4B valuation; disciplined geographic focus on OK, TX, NM, ID markets",
    },
    {
        "source_id": "seed_388",
        "deal_name": "Sound Physicians / Summit Partners LBO",
        "buyer": "Summit Partners",
        "seller": "Optum / Physician management legacy",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "physician_group",
        "ev_mm": 2200.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 157.0,
        "revenue_mm": 1200.0,
        "realized_moic": 3.0,
        "realized_irr": 0.24,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.22, "commercial": 0.33, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hospitalist + nocturnist + intensivist group; NSA headwinds partially offset by hospital outsourcing demand growth",
    },
    {
        "source_id": "seed_389",
        "deal_name": "Quartet Health / Oak HC/FT growth equity",
        "buyer": "Oak HC/FT Partners",
        "seller": "Founders",
        "year": 2017,
        "deal_type": "growth_equity",
        "sector": "behavioral_health",
        "ev_mm": 300.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 30.0,
        "realized_moic": 1.2,
        "realized_irr": 0.05,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.30, "commercial": 0.55, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Collaborative care tech for PCP-BH integration; scaled slowly; merged with Iora Health / One Medical orbit",
    },
    {
        "source_id": "seed_390",
        "deal_name": "Pivot Health / Deerfield acquisition + platform build",
        "buyer": "Deerfield Management",
        "seller": "BlueCross seed investors",
        "year": 2019,
        "deal_type": "growth_equity",
        "sector": "managed_care",
        "ev_mm": 180.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 60.0,
        "realized_moic": 2.0,
        "realized_irr": 0.15,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.75, "self_pay": 0.10},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Short-term health + STM insurance / ACA bridge products; regulatory risk from state surprise billing rules",
    },
    {
        "source_id": "seed_391",
        "deal_name": "National Health Investors / Senior Care REIT strategic acquisition",
        "buyer": "National Health Investors (NHI REIT)",
        "seller": "Senior Care Centers (SNF operator)",
        "year": 2018,
        "deal_type": "reit",
        "sector": "snf",
        "ev_mm": 250.0,
        "ev_ebitda": 8.0,
        "ebitda_mm": 31.0,
        "revenue_mm": 300.0,
        "realized_moic": 1.8,
        "realized_irr": 0.12,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.50, "commercial": 0.12, "self_pay": 0.03},
        "geography": "TX",
        "hospital_beds": 2200,
        "source": "seed",
        "notes": "SNF real estate sale-leaseback; operator defaulted 2020; COVID occupancy collapse triggered lease restructuring",
    },
    {
        "source_id": "seed_392",
        "deal_name": "Inovalon / Nordic Capital + Insight Partners take-private",
        "buyer": "Nordic Capital / Insight Partners",
        "seller": "Public shareholders",
        "year": 2022,
        "deal_type": "take-private",
        "sector": "health_it",
        "ev_mm": 7300.0,
        "ev_ebitda": 55.0,
        "ebitda_mm": 133.0,
        "revenue_mm": 800.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": None,
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Cloud-based data analytics for payers + providers; paid steep growth multiple; profitability turnaround in progress",
    },
    {
        "source_id": "seed_393",
        "deal_name": "Global Indemnity Group / specialty health insurance carve-out",
        "buyer": "Warburg Pincus",
        "seller": "Fox Paine & Company",
        "year": 2014,
        "deal_type": "carve-out",
        "sector": "managed_care",
        "ev_mm": 540.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 54.0,
        "revenue_mm": 680.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.05, "commercial": 0.85, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Specialty health + dental + vision insurance carve-out; employer group market; consistent but unspectacular returns",
    },
    {
        "source_id": "seed_394",
        "deal_name": "Mednax / NP Pediatrics physician group roll-up",
        "buyer": "Mednax (Physician Partners acquirer)",
        "seller": "Various pediatric groups",
        "year": 2016,
        "deal_type": "add-on",
        "sector": "pediatrics",
        "ev_mm": 1500.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 100.0,
        "revenue_mm": 600.0,
        "realized_moic": 1.5,
        "realized_irr": 0.10,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.40, "commercial": 0.52, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "NICU + pediatric subspecialty roll-up; Medicaid rate risk + hospital exclusivity contract disputes compressed returns",
    },
    {
        "source_id": "seed_395",
        "deal_name": "Vitas Healthcare / Chemed Corporation acquisition",
        "buyer": "Chemed Corporation (strategic)",
        "seller": "Vitas Group founders / private shareholders",
        "year": 2004,
        "deal_type": "merger",
        "sector": "hospice",
        "ev_mm": 410.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 34.0,
        "revenue_mm": 450.0,
        "realized_moic": 5.8,
        "realized_irr": 0.25,
        "hold_years": 12.0,
        "payer_mix": {"medicare": 0.85, "medicaid": 0.08, "commercial": 0.05, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest US hospice operator; Medicare hospice rate stability + aging population drove 20-yr compounding return",
    },
]
