"""Extended seed deals 616-635 — healthcare PE transactions 2015-2024.

Focus: behavioral health platforms, RCM services, ASC roll-ups,
telehealth, and value-based care infrastructure. Includes distressed
outcomes, recapitalizations, and sponsor-to-sponsor exits.
"""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_30: List[Dict[str, Any]] = [
    {
        "source_id": "seed_616",
        "source": "corpus_seed",
        "deal_name": "Acadia Healthcare – Warburg Pincus Platform Build",
        "year": 2015,
        "buyer": "Warburg Pincus",
        "seller": "Acadia Healthcare (public)",
        "ev_mm": 580.0,
        "ebitda_at_entry_mm": 62.0,
        "hold_years": 4.2,
        "realized_moic": 3.1,
        "realized_irr": 0.34,
        "leverage_pct": 0.58,
        "sector": "Behavioral Health",
        "region": "Southeast",
        "payer_mix": {"commercial": 0.38, "medicare": 0.22, "medicaid": 0.35, "self_pay": 0.05},
        "status": "realized",
    },
    {
        "source_id": "seed_617",
        "source": "corpus_seed",
        "deal_name": "Greenbrook TMS – Mental Health Roll-Up (Distressed)",
        "year": 2021,
        "buyer": "CDPQ / FFL Partners",
        "seller": "Management",
        "ev_mm": 110.0,
        "ebitda_at_entry_mm": 9.0,
        "hold_years": 2.5,
        "realized_moic": 0.4,
        "realized_irr": -0.28,
        "leverage_pct": 0.72,
        "sector": "Behavioral Health",
        "region": "National",
        "payer_mix": {"commercial": 0.55, "medicare": 0.20, "medicaid": 0.18, "self_pay": 0.07},
        "status": "realized",
    },
    {
        "source_id": "seed_618",
        "source": "corpus_seed",
        "deal_name": "Surgery Partners – New Mountain Capital LBO",
        "year": 2015,
        "buyer": "New Mountain Capital",
        "seller": "Symbion Healthcare",
        "ev_mm": 760.0,
        "ebitda_at_entry_mm": 68.0,
        "hold_years": 4.0,
        "realized_moic": 3.8,
        "realized_irr": 0.40,
        "leverage_pct": 0.62,
        "sector": "Ambulatory Surgery Centers",
        "region": "National",
        "payer_mix": {"commercial": 0.58, "medicare": 0.32, "medicaid": 0.08, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_619",
        "source": "corpus_seed",
        "deal_name": "NovaBay Pharmaceuticals – THL Partners RCM Carve-Out",
        "year": 2019,
        "buyer": "THL Partners",
        "seller": "NovaBay Pharmaceuticals",
        "ev_mm": 90.0,
        "ebitda_at_entry_mm": 10.5,
        "hold_years": 3.8,
        "realized_moic": 2.2,
        "realized_irr": 0.24,
        "leverage_pct": 0.55,
        "sector": "Healthcare IT / RCM",
        "region": "West",
        "payer_mix": {"commercial": 0.72, "medicare": 0.18, "medicaid": 0.08, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_620",
        "source": "corpus_seed",
        "deal_name": "HealthChannels / ScribeAmerica – Warburg Pincus",
        "year": 2018,
        "buyer": "Warburg Pincus",
        "seller": "Management / Growth Equity",
        "ev_mm": 420.0,
        "ebitda_at_entry_mm": 38.0,
        "hold_years": 4.5,
        "realized_moic": 3.3,
        "realized_irr": 0.33,
        "leverage_pct": 0.52,
        "sector": "Healthcare IT / RCM",
        "region": "National",
        "payer_mix": {"commercial": 0.80, "medicare": 0.12, "medicaid": 0.06, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_621",
        "source": "corpus_seed",
        "deal_name": "US Anesthesia Partners – Berkshire Partners",
        "year": 2016,
        "buyer": "Berkshire Partners / Welsh Carson",
        "seller": "Management + Earlier Sponsors",
        "ev_mm": 950.0,
        "ebitda_at_entry_mm": 82.0,
        "hold_years": 5.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "leverage_pct": 0.65,
        "sector": "Anesthesiology",
        "region": "National",
        "payer_mix": {"commercial": 0.52, "medicare": 0.32, "medicaid": 0.14, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_622",
        "source": "corpus_seed",
        "deal_name": "Pediatric Associates – KKR Platform",
        "year": 2020,
        "buyer": "KKR",
        "seller": "Physicians / Management",
        "ev_mm": 820.0,
        "ebitda_at_entry_mm": 72.0,
        "hold_years": 4.0,
        "realized_moic": 2.6,
        "realized_irr": 0.27,
        "leverage_pct": 0.60,
        "sector": "Pediatrics",
        "region": "Southeast",
        "payer_mix": {"commercial": 0.55, "medicare": 0.05, "medicaid": 0.38, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_623",
        "source": "corpus_seed",
        "deal_name": "Caremax – Deerfield / SPAC Distressed",
        "year": 2021,
        "buyer": "Deerfield Management",
        "seller": "SPAC (IMH Financial)",
        "ev_mm": 420.0,
        "ebitda_at_entry_mm": None,
        "hold_years": 2.5,
        "realized_moic": 0.1,
        "realized_irr": -0.55,
        "leverage_pct": 0.80,
        "sector": "Value-Based Care",
        "region": "Southeast",
        "payer_mix": {"commercial": 0.10, "medicare": 0.75, "medicaid": 0.15, "self_pay": 0.00},
        "status": "realized",
    },
    {
        "source_id": "seed_624",
        "source": "corpus_seed",
        "deal_name": "Tivity Health / Prime – Marlin Equity",
        "year": 2022,
        "buyer": "Marlin Equity Partners",
        "seller": "Management",
        "ev_mm": 160.0,
        "ebitda_at_entry_mm": 18.0,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "leverage_pct": 0.58,
        "sector": "Wellness / Fitness Health",
        "region": "National",
        "payer_mix": {"commercial": 0.42, "medicare": 0.48, "medicaid": 0.08, "self_pay": 0.02},
        "status": "unrealized",
    },
    {
        "source_id": "seed_625",
        "source": "corpus_seed",
        "deal_name": "Navvis & Company – Health System Consulting LBO",
        "year": 2020,
        "buyer": "Summit Partners",
        "seller": "Navvis Founders",
        "ev_mm": 75.0,
        "ebitda_at_entry_mm": 9.0,
        "hold_years": 3.5,
        "realized_moic": 2.9,
        "realized_irr": 0.36,
        "leverage_pct": 0.45,
        "sector": "Healthcare Consulting",
        "region": "Midwest",
        "payer_mix": {"commercial": 0.65, "medicare": 0.25, "medicaid": 0.08, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_626",
        "source": "corpus_seed",
        "deal_name": "Covenant Physician Partners – Warburg Pincus Hospital-Based",
        "year": 2019,
        "buyer": "Warburg Pincus",
        "seller": "Management",
        "ev_mm": 650.0,
        "ebitda_at_entry_mm": 55.0,
        "hold_years": 4.2,
        "realized_moic": 3.2,
        "realized_irr": 0.35,
        "leverage_pct": 0.58,
        "sector": "Hospital-Based Physician Groups",
        "region": "Southeast",
        "payer_mix": {"commercial": 0.48, "medicare": 0.35, "medicaid": 0.15, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_627",
        "source": "corpus_seed",
        "deal_name": "American Physician Partners – Distressed Exit",
        "year": 2020,
        "buyer": "TPG Capital",
        "seller": "ABRY Partners",
        "ev_mm": 350.0,
        "ebitda_at_entry_mm": 28.0,
        "hold_years": 2.8,
        "realized_moic": 0.6,
        "realized_irr": -0.18,
        "leverage_pct": 0.72,
        "sector": "Emergency Medicine",
        "region": "National",
        "payer_mix": {"commercial": 0.42, "medicare": 0.38, "medicaid": 0.18, "self_pay": 0.02},
        "status": "realized",
    },
    {
        "source_id": "seed_628",
        "source": "corpus_seed",
        "deal_name": "Primoris Dental – OMERS / Platform",
        "year": 2021,
        "buyer": "OMERS Private Equity",
        "seller": "Founders",
        "ev_mm": 130.0,
        "ebitda_at_entry_mm": 14.0,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "leverage_pct": 0.52,
        "sector": "Dental",
        "region": "Midwest",
        "payer_mix": {"commercial": 0.72, "medicare": 0.05, "medicaid": 0.18, "self_pay": 0.05},
        "status": "unrealized",
    },
    {
        "source_id": "seed_629",
        "source": "corpus_seed",
        "deal_name": "Phreesia – PSG / SaaS Healthcare",
        "year": 2019,
        "buyer": "PSG Equity (Growth)",
        "seller": "Management",
        "ev_mm": 300.0,
        "ebitda_at_entry_mm": 20.0,
        "hold_years": 3.0,
        "realized_moic": 4.8,
        "realized_irr": 0.67,
        "leverage_pct": 0.20,
        "sector": "Healthcare IT / RCM",
        "region": "Northeast",
        "payer_mix": {"commercial": 0.85, "medicare": 0.10, "medicaid": 0.04, "self_pay": 0.01},
        "status": "realized",
    },
    {
        "source_id": "seed_630",
        "source": "corpus_seed",
        "deal_name": "Community Health Systems Carve-Out – Oak Hill Capital",
        "year": 2017,
        "buyer": "Oak Hill Capital",
        "seller": "Community Health Systems",
        "ev_mm": 1200.0,
        "ebitda_at_entry_mm": 90.0,
        "hold_years": 5.5,
        "realized_moic": 1.8,
        "realized_irr": 0.11,
        "leverage_pct": 0.68,
        "sector": "General Hospitals",
        "region": "Southeast",
        "payer_mix": {"commercial": 0.42, "medicare": 0.32, "medicaid": 0.22, "self_pay": 0.04},
        "status": "realized",
    },
    {
        "source_id": "seed_631",
        "source": "corpus_seed",
        "deal_name": "Premise Health / National Wellness – Investor Group",
        "year": 2016,
        "buyer": "OMERS / Warburg Pincus JV",
        "seller": "Walgreens",
        "ev_mm": 1350.0,
        "ebitda_at_entry_mm": 105.0,
        "hold_years": 6.0,
        "realized_moic": 2.4,
        "realized_irr": 0.15,
        "leverage_pct": 0.55,
        "sector": "Employer Health / On-Site Clinics",
        "region": "National",
        "payer_mix": {"commercial": 0.88, "medicare": 0.05, "medicaid": 0.04, "self_pay": 0.03},
        "status": "realized",
    },
    {
        "source_id": "seed_632",
        "source": "corpus_seed",
        "deal_name": "Advanced Dermatology – ACON / GIC Roll-Up",
        "year": 2020,
        "buyer": "ACON Investments / GIC",
        "seller": "Management + Physicians",
        "ev_mm": 480.0,
        "ebitda_at_entry_mm": 42.0,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "leverage_pct": 0.58,
        "sector": "Dermatology",
        "region": "National",
        "payer_mix": {"commercial": 0.65, "medicare": 0.28, "medicaid": 0.05, "self_pay": 0.02},
        "status": "unrealized",
    },
    {
        "source_id": "seed_633",
        "source": "corpus_seed",
        "deal_name": "Hims & Hers – Oaktree / Pre-SPAC",
        "year": 2020,
        "buyer": "Oaktree Capital",
        "seller": "Founders / Series investors",
        "ev_mm": 165.0,
        "ebitda_at_entry_mm": None,
        "hold_years": 2.0,
        "realized_moic": 3.6,
        "realized_irr": 0.82,
        "leverage_pct": 0.15,
        "sector": "Telehealth / DTC",
        "region": "National",
        "payer_mix": {"commercial": 0.35, "medicare": 0.05, "medicaid": 0.05, "self_pay": 0.55},
        "status": "realized",
    },
    {
        "source_id": "seed_634",
        "source": "corpus_seed",
        "deal_name": "CAPA Health – GI Alliance Add-On",
        "year": 2022,
        "buyer": "Ares Management",
        "seller": "CAPA Physicians",
        "ev_mm": 95.0,
        "ebitda_at_entry_mm": 11.0,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "leverage_pct": 0.50,
        "sector": "Gastroenterology",
        "region": "West",
        "payer_mix": {"commercial": 0.62, "medicare": 0.30, "medicaid": 0.07, "self_pay": 0.01},
        "status": "unrealized",
    },
    {
        "source_id": "seed_635",
        "source": "corpus_seed",
        "deal_name": "CareDx – Medline / Growth Buyout",
        "year": 2023,
        "buyer": "Blackstone Growth",
        "seller": "Public Shareholders",
        "ev_mm": 520.0,
        "ebitda_at_entry_mm": 35.0,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "leverage_pct": 0.42,
        "sector": "Transplant / Diagnostics",
        "region": "National",
        "payer_mix": {"commercial": 0.70, "medicare": 0.22, "medicaid": 0.07, "self_pay": 0.01},
        "status": "unrealized",
    },
]
