"""Extended seed 78: Orthopedic rollups and MSK platform PE deals.

This module contains a curated set of 15 healthcare private equity deal
records focused on the orthopedic and musculoskeletal (MSK) services
landscape. The theme covers:

- Orthopedic group practice rollups
- Spine MSO platforms
- Sports medicine platforms
- Joint replacement centers (ASC-focused)
- Broader MSK platform aggregators

Each record captures deal economics (EV, EV/EBITDA, margins), return
profile (MOIC, IRR, hold period), payer mix, regional footprint, sponsor,
and realization status. These records are synthesized for modeling,
backtesting, and scenario analysis use cases.
"""

EXTENDED_SEED_DEALS_78 = [
    {
        "company_name": "Summit Orthopedic Partners",
        "sector": "Orthopedic Rollup",
        "subsector": "Multi-specialty Orthopedic Group",
        "year": 2018,
        "ev_mm": 485.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 38.8,
        "revenue_mm": 176.36,
        "ebitda_margin": 0.22,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.58, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.06},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Pinnacle Spine MSO",
        "sector": "Spine MSO",
        "subsector": "Interventional Spine Platform",
        "year": 2019,
        "ev_mm": 320.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 23.19,
        "revenue_mm": 120.97,
        "ebitda_margin": 0.1917,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.2033,
        "payer_mix": {"commercial": 0.62, "medicare": 0.24, "medicaid": 0.07, "self_pay": 0.07},
        "comm_pct": 0.62,
        "region": "Southeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Atlas Sports Medicine Group",
        "sector": "Sports Medicine",
        "subsector": "Outpatient Sports Medicine Clinics",
        "year": 2020,
        "ev_mm": 215.0,
        "ev_ebitda": 14.2,
        "ebitda_mm": 15.14,
        "revenue_mm": 68.82,
        "ebitda_margin": 0.22,
        "hold_years": 4.0,
        "moic": 2.1,
        "irr": 0.2038,
        "payer_mix": {"commercial": 0.72, "medicare": 0.12, "medicaid": 0.08, "self_pay": 0.08},
        "comm_pct": 0.72,
        "region": "West",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Cornerstone Joint Replacement Centers",
        "sector": "Joint Replacement",
        "subsector": "ASC-based Total Joint Platform",
        "year": 2021,
        "ev_mm": 640.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 41.29,
        "revenue_mm": 165.16,
        "ebitda_margin": 0.25,
        "hold_years": 3.5,
        "moic": 2.2,
        "irr": 0.2527,
        "payer_mix": {"commercial": 0.48, "medicare": 0.42, "medicaid": 0.05, "self_pay": 0.05},
        "comm_pct": 0.48,
        "region": "Southeast",
        "buyer": "Clayton Dubilier & Rice",
        "status": "Active",
    },
    {
        "company_name": "MSK Health Partners",
        "sector": "MSK Platform",
        "subsector": "Integrated MSK Care Platform",
        "year": 2022,
        "ev_mm": 950.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 57.58,
        "revenue_mm": 239.92,
        "ebitda_margin": 0.24,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": 0.2164,
        "payer_mix": {"commercial": 0.55, "medicare": 0.32, "medicaid": 0.08, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "National",
        "buyer": "Thomas H. Lee",
        "status": "Active",
    },
    {
        "company_name": "Heartland Orthopedic Associates",
        "sector": "Orthopedic Rollup",
        "subsector": "Regional Ortho Practice Aggregator",
        "year": 2017,
        "ev_mm": 175.0,
        "ev_ebitda": 11.2,
        "ebitda_mm": 15.63,
        "revenue_mm": 83.14,
        "ebitda_margin": 0.188,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": 0.2075,
        "payer_mix": {"commercial": 0.52, "medicare": 0.32, "medicaid": 0.1, "self_pay": 0.06},
        "comm_pct": 0.52,
        "region": "Midwest",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Pacific Spine Institute MSO",
        "sector": "Spine MSO",
        "subsector": "Minimally Invasive Spine Platform",
        "year": 2020,
        "ev_mm": 410.0,
        "ev_ebitda": 14.8,
        "ebitda_mm": 27.7,
        "revenue_mm": 115.42,
        "ebitda_margin": 0.24,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.64, "medicare": 0.22, "medicaid": 0.08, "self_pay": 0.06},
        "comm_pct": 0.64,
        "region": "West",
        "buyer": "Frazier",
        "status": "Active",
    },
    {
        "company_name": "Northeast Sports & Orthopedic",
        "sector": "Sports Medicine",
        "subsector": "Multi-site Sports Medicine Group",
        "year": 2019,
        "ev_mm": 135.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 11.44,
        "revenue_mm": 50.84,
        "ebitda_margin": 0.225,
        "hold_years": 5.5,
        "moic": 2.7,
        "irr": 0.1979,
        "payer_mix": {"commercial": 0.7, "medicare": 0.15, "medicaid": 0.08, "self_pay": 0.07},
        "comm_pct": 0.7,
        "region": "Northeast",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "Southern Joint Care Network",
        "sector": "Joint Replacement",
        "subsector": "Bundled Payment Joint Network",
        "year": 2021,
        "ev_mm": 285.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 21.11,
        "revenue_mm": 80.73,
        "ebitda_margin": 0.2615,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.45, "medicare": 0.45, "medicaid": 0.05, "self_pay": 0.05},
        "comm_pct": 0.45,
        "region": "Southeast",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Rocky Mountain MSK Alliance",
        "sector": "MSK Platform",
        "subsector": "Value-based MSK Platform",
        "year": 2023,
        "ev_mm": 520.0,
        "ev_ebitda": 17.2,
        "ebitda_mm": 30.23,
        "revenue_mm": 142.59,
        "ebitda_margin": 0.212,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.6, "medicare": 0.28, "medicaid": 0.07, "self_pay": 0.05},
        "comm_pct": 0.6,
        "region": "West",
        "buyer": "Harren",
        "status": "Active",
    },
    {
        "company_name": "Liberty Orthopedic Holdings",
        "sector": "Orthopedic Rollup",
        "subsector": "Single-specialty Ortho Rollup",
        "year": 2016,
        "ev_mm": 95.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 9.05,
        "revenue_mm": 47.63,
        "ebitda_margin": 0.19,
        "hold_years": 6.5,
        "moic": 3.5,
        "irr": 0.2126,
        "payer_mix": {"commercial": 0.54, "medicare": 0.3, "medicaid": 0.1, "self_pay": 0.06},
        "comm_pct": 0.54,
        "region": "Northeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Gulf Coast Spine Partners",
        "sector": "Spine MSO",
        "subsector": "Surgical Spine MSO",
        "year": 2022,
        "ev_mm": 370.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": 23.42,
        "revenue_mm": 93.68,
        "ebitda_margin": 0.25,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.58, "medicare": 0.3, "medicaid": 0.07, "self_pay": 0.05},
        "comm_pct": 0.58,
        "region": "Southeast",
        "buyer": "Audax",
        "status": "Partially Realized",
    },
    {
        "company_name": "Elite Sports Performance Group",
        "sector": "Sports Medicine",
        "subsector": "Sports Med & Physical Therapy Hybrid",
        "year": 2021,
        "ev_mm": 230.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 16.43,
        "revenue_mm": 68.46,
        "ebitda_margin": 0.24,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.68, "medicare": 0.16, "medicaid": 0.09, "self_pay": 0.07},
        "comm_pct": 0.68,
        "region": "National",
        "buyer": "Silversmith",
        "status": "Active",
    },
    {
        "company_name": "Midwest Total Joint Partners",
        "sector": "Joint Replacement",
        "subsector": "Physician-owned ASC Joint Platform",
        "year": 2018,
        "ev_mm": 155.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 12.92,
        "revenue_mm": 47.85,
        "ebitda_margin": 0.27,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2136,
        "payer_mix": {"commercial": 0.5, "medicare": 0.4, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.5,
        "region": "Midwest",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "National MSK Solutions",
        "sector": "MSK Platform",
        "subsector": "Employer-focused MSK Platform",
        "year": 2024,
        "ev_mm": 1350.0,
        "ev_ebitda": 19.5,
        "ebitda_mm": 69.23,
        "revenue_mm": 276.92,
        "ebitda_margin": 0.25,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.75, "medicare": 0.15, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.75,
        "region": "National",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
]
