"""Extended seed batch 58 — behavioral health PE deals.

Covers addiction treatment, outpatient and residential mental health clinics,
applied behavior analysis (ABA) therapy, eating disorder treatment, and
inpatient/outpatient psychiatric facilities.
All financial metrics are internally consistent: ebitda_mm = ev_mm / ev_ebitda,
revenue_mm = ebitda_mm / ebitda_margin, irr = moic^(1/hold_years) - 1.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_58: list[dict] = [
    {
        "company_name": "Odyssey Recovery Centers",
        "sector": "Addiction Treatment",
        "subsector": "Residential Substance Use Treatment",
        "year": 2018,
        "ev_mm": 185.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 14.8,
        "revenue_mm": 105.71,
        "ebitda_margin": 0.14,
        "hold_years": 5.0,
        "moic": 3.2,
        "irr": 0.2619,
        "payer_mix": {"commercial": 0.30, "medicare": 0.10, "medicaid": 0.52, "self_pay": 0.08},
        "comm_pct": 0.30,
        "region": "Southeast",
        "buyer": "Acadia Healthcare",
        "status": "Realized",
    },
    {
        "company_name": "Clearwater Behavioral Health",
        "sector": "Mental Health",
        "subsector": "Outpatient Mental Health Clinics",
        "year": 2020,
        "ev_mm": 240.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 17.14,
        "revenue_mm": 114.27,
        "ebitda_margin": 0.15,
        "hold_years": 4.0,
        "moic": 2.9,
        "irr": 0.305,
        "payer_mix": {"commercial": 0.38, "medicare": 0.12, "medicaid": 0.44, "self_pay": 0.06},
        "comm_pct": 0.38,
        "region": "Midwest",
        "buyer": "Revelstoke Capital",
        "status": "Partially Realized",
    },
    {
        "company_name": "Apex ABA Therapy Group",
        "sector": "ABA Therapy",
        "subsector": "Applied Behavior Analysis — Pediatric",
        "year": 2019,
        "ev_mm": 95.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 8.64,
        "revenue_mm": 66.46,
        "ebitda_margin": 0.13,
        "hold_years": 4.5,
        "moic": 3.5,
        "irr": 0.321,
        "payer_mix": {"commercial": 0.45, "medicare": 0.05, "medicaid": 0.46, "self_pay": 0.04},
        "comm_pct": 0.45,
        "region": "West",
        "buyer": "Lee Equity",
        "status": "Realized",
    },
    {
        "company_name": "Harmony Eating Disorder Centers",
        "sector": "Behavioral Health",
        "subsector": "Residential Eating Disorder Treatment",
        "year": 2017,
        "ev_mm": 60.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 6.0,
        "revenue_mm": 50.0,
        "ebitda_margin": 0.12,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.62, "medicare": 0.08, "medicaid": 0.22, "self_pay": 0.08},
        "comm_pct": 0.62,
        "region": "Northeast",
        "buyer": "Webster Capital",
        "status": "Realized",
    },
    {
        "company_name": "Pinnacle Psychiatric Hospitals",
        "sector": "Psychiatric Services",
        "subsector": "Inpatient Psychiatric Facilities",
        "year": 2016,
        "ev_mm": 420.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 31.11,
        "revenue_mm": 172.83,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 4.0,
        "irr": 0.2599,
        "payer_mix": {"commercial": 0.25, "medicare": 0.18, "medicaid": 0.50, "self_pay": 0.07},
        "comm_pct": 0.25,
        "region": "National",
        "buyer": "Acadia Healthcare",
        "status": "Realized",
    },
    {
        "company_name": "Summit Detox Solutions",
        "sector": "Addiction Treatment",
        "subsector": "Medical Detoxification Services",
        "year": 2021,
        "ev_mm": 78.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 8.21,
        "revenue_mm": 82.1,
        "ebitda_margin": 0.10,
        "hold_years": 3.5,
        "moic": 2.2,
        "irr": 0.2527,
        "payer_mix": {"commercial": 0.32, "medicare": 0.08, "medicaid": 0.53, "self_pay": 0.07},
        "comm_pct": 0.32,
        "region": "Southeast",
        "buyer": "BayMark Partners",
        "status": "Active",
    },
    {
        "company_name": "Kinship ABA Services",
        "sector": "ABA Therapy",
        "subsector": "School-Based ABA Therapy",
        "year": 2022,
        "ev_mm": 52.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 4.95,
        "revenue_mm": 45.0,
        "ebitda_margin": 0.11,
        "hold_years": 3.0,
        "moic": 1.9,
        "irr": 0.2386,
        "payer_mix": {"commercial": 0.48, "medicare": 0.04, "medicaid": 0.44, "self_pay": 0.04},
        "comm_pct": 0.48,
        "region": "Midwest",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "Vantage Mental Health Network",
        "sector": "Mental Health",
        "subsector": "Integrated Outpatient Behavioral Health",
        "year": 2018,
        "ev_mm": 310.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 21.38,
        "revenue_mm": 133.62,
        "ebitda_margin": 0.16,
        "hold_years": 5.5,
        "moic": 3.8,
        "irr": 0.2747,
        "payer_mix": {"commercial": 0.35, "medicare": 0.15, "medicaid": 0.43, "self_pay": 0.07},
        "comm_pct": 0.35,
        "region": "National",
        "buyer": "Centerbridge",
        "status": "Realized",
    },
    {
        "company_name": "BlueRidge Addiction Services",
        "sector": "Addiction Treatment",
        "subsector": "Medication-Assisted Treatment (MAT)",
        "year": 2020,
        "ev_mm": 130.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 11.3,
        "revenue_mm": 86.92,
        "ebitda_margin": 0.13,
        "hold_years": 4.0,
        "moic": 2.7,
        "irr": 0.2819,
        "payer_mix": {"commercial": 0.28, "medicare": 0.10, "medicaid": 0.55, "self_pay": 0.07},
        "comm_pct": 0.28,
        "region": "Southeast",
        "buyer": "BayMark Partners",
        "status": "Active",
    },
    {
        "company_name": "Spectrum ABA Partners",
        "sector": "ABA Therapy",
        "subsector": "Multi-State ABA Therapy Platform",
        "year": 2021,
        "ev_mm": 175.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 14.58,
        "revenue_mm": 104.14,
        "ebitda_margin": 0.14,
        "hold_years": 3.5,
        "moic": 2.5,
        "irr": 0.2993,
        "payer_mix": {"commercial": 0.50, "medicare": 0.05, "medicaid": 0.41, "self_pay": 0.04},
        "comm_pct": 0.50,
        "region": "West",
        "buyer": "KKR",
        "status": "Active",
    },
    {
        "company_name": "Ironwood Psychiatric Group",
        "sector": "Psychiatric Services",
        "subsector": "Outpatient Psychiatric Services",
        "year": 2017,
        "ev_mm": 88.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 8.8,
        "revenue_mm": 73.33,
        "ebitda_margin": 0.12,
        "hold_years": 4.5,
        "moic": 2.8,
        "irr": 0.2571,
        "payer_mix": {"commercial": 0.40, "medicare": 0.20, "medicaid": 0.34, "self_pay": 0.06},
        "comm_pct": 0.40,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Crestview Eating Disorder Clinic",
        "sector": "Behavioral Health",
        "subsector": "Eating Disorder Partial Hospitalization",
        "year": 2023,
        "ev_mm": 45.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 5.29,
        "revenue_mm": 58.78,
        "ebitda_margin": 0.09,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.60, "medicare": 0.07, "medicaid": 0.25, "self_pay": 0.08},
        "comm_pct": 0.60,
        "region": "West",
        "buyer": "Webster Capital",
        "status": "Active",
    },
    {
        "company_name": "Meridian Mental Health System",
        "sector": "Mental Health",
        "subsector": "Community Mental Health Centers",
        "year": 2019,
        "ev_mm": 560.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 35.0,
        "revenue_mm": 175.0,
        "ebitda_margin": 0.20,
        "hold_years": 5.0,
        "moic": 3.6,
        "irr": 0.292,
        "payer_mix": {"commercial": 0.22, "medicare": 0.20, "medicaid": 0.52, "self_pay": 0.06},
        "comm_pct": 0.22,
        "region": "National",
        "buyer": "KKR",
        "status": "Partially Realized",
    },
    {
        "company_name": "Pathways Recovery Network",
        "sector": "Addiction Treatment",
        "subsector": "Intensive Outpatient Addiction Treatment",
        "year": 2024,
        "ev_mm": 38.0,
        "ev_ebitda": 9.0,
        "ebitda_mm": 4.22,
        "revenue_mm": 42.2,
        "ebitda_margin": 0.10,
        "hold_years": 2.0,
        "moic": 1.4,
        "irr": 0.1832,
        "payer_mix": {"commercial": 0.33, "medicare": 0.09, "medicaid": 0.51, "self_pay": 0.07},
        "comm_pct": 0.33,
        "region": "Midwest",
        "buyer": "Nautic Partners",
        "status": "Active",
    },
    {
        "company_name": "Brightside Psychiatric Partners",
        "sector": "Psychiatric Services",
        "subsector": "Partial Hospitalization Psychiatry",
        "year": 2020,
        "ev_mm": 210.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 16.15,
        "revenue_mm": 107.67,
        "ebitda_margin": 0.15,
        "hold_years": 4.0,
        "moic": 3.0,
        "irr": 0.3161,
        "payer_mix": {"commercial": 0.36, "medicare": 0.18, "medicaid": 0.40, "self_pay": 0.06},
        "comm_pct": 0.36,
        "region": "Southeast",
        "buyer": "Bain Capital",
        "status": "Partially Realized",
    },
]
