"""Extended seed deals batch 59.

Healthcare PE deals focused on specialty pharmacy, infusion centers,
compounding pharmacies, 340B pharmacy programs, oncology pharmacy, and
clinical trial services. Fifteen synthetic but realistic deal records
with consistent financial fields and payer mix distributions.
"""

EXTENDED_SEED_DEALS_59 = [
    {
        "company_name": "BrightPath Specialty Pharmacy",
        "sector": "Specialty Pharmacy",
        "subsector": "Rare Disease Distribution",
        "year": 2019,
        "ev_mm": 420.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 33.6,
        "revenue_mm": 373.33,
        "ebitda_margin": 0.09,
        "hold_years": 4.5,
        "moic": 2.6,
        "irr": 0.2366,
        "payer_mix": {"commercial": 0.58, "medicare": 0.22, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "Water Street Healthcare",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Infusion Partners",
        "sector": "Infusion Services",
        "subsector": "Ambulatory Infusion Centers",
        "year": 2020,
        "ev_mm": 285.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 25.91,
        "revenue_mm": 230.31,
        "ebitda_margin": 0.1125,
        "hold_years": 3.5,
        "moic": 2.1,
        "irr": 0.2361,
        "payer_mix": {"commercial": 0.62, "medicare": 0.25, "medicaid": 0.10, "self_pay": 0.03},
        "comm_pct": 0.62,
        "region": "Southeast",
        "buyer": "Nautic",
        "status": "Active",
    },
    {
        "company_name": "OncoRx Therapeutics Network",
        "sector": "Oncology Pharmacy",
        "subsector": "Hospital Dispensing",
        "year": 2018,
        "ev_mm": 680.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 48.57,
        "revenue_mm": 485.7,
        "ebitda_margin": 0.10,
        "hold_years": 5.0,
        "moic": 3.2,
        "irr": 0.2619,
        "payer_mix": {"commercial": 0.45, "medicare": 0.40, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.45,
        "region": "Midwest",
        "buyer": "Madison Dearborn",
        "status": "Realized",
    },
    {
        "company_name": "Harbor Compounding Labs",
        "sector": "Compounding Pharmacy",
        "subsector": "Sterile 503B Outsourcing",
        "year": 2021,
        "ev_mm": 155.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 14.76,
        "revenue_mm": 134.18,
        "ebitda_margin": 0.11,
        "hold_years": 3.0,
        "moic": 1.9,
        "irr": 0.2386,
        "payer_mix": {"commercial": 0.55, "medicare": 0.20, "medicaid": 0.18, "self_pay": 0.07},
        "comm_pct": 0.55,
        "region": "West",
        "buyer": "Gryphon",
        "status": "Active",
    },
    {
        "company_name": "Cornerstone 340B Solutions",
        "sector": "Pharmacy Services",
        "subsector": "340B Program Administration",
        "year": 2022,
        "ev_mm": 510.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 37.78,
        "revenue_mm": 314.83,
        "ebitda_margin": 0.12,
        "hold_years": 2.5,
        "moic": 1.55,
        "irr": 0.1916,
        "payer_mix": {"commercial": 0.35, "medicare": 0.30, "medicaid": 0.28, "self_pay": 0.07},
        "comm_pct": 0.35,
        "region": "National",
        "buyer": "Apollo",
        "status": "Active",
    },
    {
        "company_name": "Trillium Clinical Research",
        "sector": "Clinical Trials",
        "subsector": "Site Management Organization",
        "year": 2019,
        "ev_mm": 325.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 20.97,
        "revenue_mm": 149.79,
        "ebitda_margin": 0.14,
        "hold_years": 4.0,
        "moic": 2.8,
        "irr": 0.2936,
        "payer_mix": {"commercial": 0.70, "medicare": 0.15, "medicaid": 0.10, "self_pay": 0.05},
        "comm_pct": 0.70,
        "region": "Northeast",
        "buyer": "Ampersand",
        "status": "Realized",
    },
    {
        "company_name": "Vanguard Home Infusion",
        "sector": "Infusion Services",
        "subsector": "Home Infusion Therapy",
        "year": 2017,
        "ev_mm": 745.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 57.31,
        "revenue_mm": 572.53,
        "ebitda_margin": 0.1001,
        "hold_years": 5.5,
        "moic": 3.4,
        "irr": 0.2492,
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.09, "self_pay": 0.03},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Summit Specialty Dispensing",
        "sector": "Specialty Pharmacy",
        "subsector": "Limited Distribution Drug",
        "year": 2023,
        "ev_mm": 195.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 16.96,
        "revenue_mm": 199.53,
        "ebitda_margin": 0.085,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1441,
        "payer_mix": {"commercial": 0.52, "medicare": 0.26, "medicaid": 0.17, "self_pay": 0.05},
        "comm_pct": 0.52,
        "region": "Southeast",
        "buyer": "Pharos",
        "status": "Active",
    },
    {
        "company_name": "Cascade Oncology Dispensing",
        "sector": "Oncology Pharmacy",
        "subsector": "Medically Integrated Dispensing",
        "year": 2020,
        "ev_mm": 98.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 9.8,
        "revenue_mm": 108.89,
        "ebitda_margin": 0.09,
        "hold_years": 3.5,
        "moic": 2.0,
        "irr": 0.219,
        "payer_mix": {"commercial": 0.48, "medicare": 0.38, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.48,
        "region": "West",
        "buyer": "Audax",
        "status": "Active",
    },
    {
        "company_name": "Beacon Sterile Compounders",
        "sector": "Compounding Pharmacy",
        "subsector": "Hospital 503A Compounding",
        "year": 2016,
        "ev_mm": 62.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 6.53,
        "revenue_mm": 51.42,
        "ebitda_margin": 0.127,
        "hold_years": 6.0,
        "moic": 3.8,
        "irr": 0.2492,
        "payer_mix": {"commercial": 0.50, "medicare": 0.25, "medicaid": 0.20, "self_pay": 0.05},
        "comm_pct": 0.50,
        "region": "Midwest",
        "buyer": "Clayton Dubilier & Rice",
        "status": "Realized",
    },
    {
        "company_name": "Redwood Clinical Sites",
        "sector": "Clinical Trials",
        "subsector": "Oncology Trial Sites",
        "year": 2022,
        "ev_mm": 445.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 26.97,
        "revenue_mm": 224.75,
        "ebitda_margin": 0.12,
        "hold_years": 3.0,
        "moic": 1.75,
        "irr": 0.2051,
        "payer_mix": {"commercial": 0.68, "medicare": 0.18, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.68,
        "region": "West",
        "buyer": "Water Street Healthcare",
        "status": "Partially Realized",
    },
    {
        "company_name": "Greenleaf 340B Advisory",
        "sector": "Pharmacy Services",
        "subsector": "340B Compliance Services",
        "year": 2018,
        "ev_mm": 215.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 17.92,
        "revenue_mm": 149.33,
        "ebitda_margin": 0.12,
        "hold_years": 5.0,
        "moic": 2.9,
        "irr": 0.2373,
        "payer_mix": {"commercial": 0.38, "medicare": 0.30, "medicaid": 0.27, "self_pay": 0.05},
        "comm_pct": 0.38,
        "region": "Southeast",
        "buyer": "Madison Dearborn",
        "status": "Realized",
    },
    {
        "company_name": "Atlas Infusion Clinics",
        "sector": "Infusion Services",
        "subsector": "Specialty Biologic Infusion",
        "year": 2021,
        "ev_mm": 1050.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 72.41,
        "revenue_mm": 603.42,
        "ebitda_margin": 0.12,
        "hold_years": 3.5,
        "moic": 2.25,
        "irr": 0.2607,
        "payer_mix": {"commercial": 0.65, "medicare": 0.22, "medicaid": 0.10, "self_pay": 0.03},
        "comm_pct": 0.65,
        "region": "National",
        "buyer": "KKR",
        "status": "Active",
    },
    {
        "company_name": "Pinnacle Specialty Rx Group",
        "sector": "Specialty Pharmacy",
        "subsector": "Gene Therapy Distribution",
        "year": 2024,
        "ev_mm": 1180.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 67.43,
        "revenue_mm": 482.68,
        "ebitda_margin": 0.1397,
        "hold_years": 2.5,
        "moic": 1.35,
        "irr": 0.1275,
        "payer_mix": {"commercial": 0.55, "medicare": 0.25, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "Northeast",
        "buyer": "Apollo",
        "status": "Active",
    },
    {
        "company_name": "Keystone Oncology Pharmacy",
        "sector": "Oncology Pharmacy",
        "subsector": "Community Oncology Dispensing",
        "year": 2017,
        "ev_mm": 360.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 27.69,
        "revenue_mm": 221.52,
        "ebitda_margin": 0.125,
        "hold_years": 5.0,
        "moic": 3.1,
        "irr": 0.2539,
        "payer_mix": {"commercial": 0.50, "medicare": 0.35, "medicaid": 0.12, "self_pay": 0.03},
        "comm_pct": 0.50,
        "region": "Midwest",
        "buyer": "Gryphon",
        "status": "Realized",
    },
]
