"""Extended seed 69: Musculoskeletal and orthopedics platforms across
orthopedic surgery groups, physical therapy chains, spine practices,
pain management clinics, and sports medicine networks.

This module provides a curated list of 15 synthetic healthcare private
equity deals focused on the musculoskeletal care continuum. Each deal
dict contains 17 standardized fields covering deal economics, payer
mix, geography, sponsor, and realization status.
"""

EXTENDED_SEED_DEALS_69 = [
    {
        "company_name": "Summit Orthopedic Partners",
        "sector": "Orthopedics",
        "subsector": "Multi-Site Orthopedic Surgery Group",
        "year": 2018,
        "ev_mm": 685.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 50.74,
        "revenue_mm": 211.42,
        "ebitda_margin": 0.24,
        "hold_years": 4.5,
        "moic": 2.8,
        "irr": 0.2571,
        "payer_mix": {"commercial": 0.62, "medicare": 0.28, "medicaid": 0.06, "self_pay": 0.04},
        "comm_pct": 0.62,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Cascade Physical Therapy Network",
        "sector": "Physical Therapy",
        "subsector": "Outpatient PT Chain",
        "year": 2019,
        "ev_mm": 295.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 24.58,
        "revenue_mm": 136.56,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": 0.1914,
        "payer_mix": {"commercial": 0.58, "medicare": 0.24, "medicaid": 0.13, "self_pay": 0.05},
        "comm_pct": 0.58,
        "region": "West",
        "buyer": "Harren Equity",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Spine Institute",
        "sector": "Spine",
        "subsector": "Spine Surgery + Interventional",
        "year": 2020,
        "ev_mm": 520.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 35.86,
        "revenue_mm": 129.46,
        "ebitda_margin": 0.277,
        "hold_years": 3.5,
        "moic": 2.3,
        "irr": 0.2687,
        "payer_mix": {"commercial": 0.66, "medicare": 0.25, "medicaid": 0.05, "self_pay": 0.04},
        "comm_pct": 0.66,
        "region": "Southeast",
        "buyer": "H.I.G. Capital",
        "status": "Active",
    },
    {
        "company_name": "Arbor Pain Management Associates",
        "sector": "Pain Management",
        "subsector": "Interventional Pain Clinics",
        "year": 2017,
        "ev_mm": 210.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 18.26,
        "revenue_mm": 91.3,
        "ebitda_margin": 0.2,
        "hold_years": 5.5,
        "moic": 2.6,
        "irr": 0.1897,
        "payer_mix": {"commercial": 0.54, "medicare": 0.32, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.54,
        "region": "Midwest",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Coastline Sports Medicine Group",
        "sector": "Sports Medicine",
        "subsector": "Sports Med + Ortho Urgent Care",
        "year": 2021,
        "ev_mm": 355.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 27.31,
        "revenue_mm": 105.04,
        "ebitda_margin": 0.26,
        "hold_years": 3.0,
        "moic": 1.9,
        "irr": 0.2386,
        "payer_mix": {"commercial": 0.70, "medicare": 0.18, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.70,
        "region": "West",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Keystone Orthopedic Specialists",
        "sector": "Orthopedics",
        "subsector": "Integrated Ortho Platform",
        "year": 2016,
        "ev_mm": 880.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 62.86,
        "revenue_mm": 249.44,
        "ebitda_margin": 0.252,
        "hold_years": 6.0,
        "moic": 3.1,
        "irr": 0.2075,
        "payer_mix": {"commercial": 0.60, "medicare": 0.30, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.60,
        "region": "Northeast",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Prairie Rehab Physical Therapy",
        "sector": "Physical Therapy",
        "subsector": "Rural + Suburban PT Clinics",
        "year": 2022,
        "ev_mm": 135.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 12.86,
        "revenue_mm": 77.94,
        "ebitda_margin": 0.165,
        "hold_years": 2.5,
        "moic": 1.6,
        "irr": 0.2068,
        "payer_mix": {"commercial": 0.50, "medicare": 0.30, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.50,
        "region": "Midwest",
        "buyer": "Alpine Investors",
        "status": "Active",
    },
    {
        "company_name": "Sierra Spine & Neurosurgery",
        "sector": "Spine",
        "subsector": "Complex Spine + ASC",
        "year": 2019,
        "ev_mm": 745.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 48.06,
        "revenue_mm": 160.2,
        "ebitda_margin": 0.30,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.68, "medicare": 0.24, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.68,
        "region": "West",
        "buyer": "Frazier Healthcare",
        "status": "Partially Realized",
    },
    {
        "company_name": "Beacon Interventional Pain Partners",
        "sector": "Pain Management",
        "subsector": "Multi-State Pain Platform",
        "year": 2020,
        "ev_mm": 410.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 32.8,
        "revenue_mm": 149.09,
        "ebitda_margin": 0.22,
        "hold_years": 4.0,
        "moic": 2.2,
        "irr": 0.2179,
        "payer_mix": {"commercial": 0.56, "medicare": 0.30, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.56,
        "region": "Southeast",
        "buyer": "Webster Equity",
        "status": "Active",
    },
    {
        "company_name": "Atlas Musculoskeletal Holdings",
        "sector": "Musculoskeletal",
        "subsector": "Integrated MSK Platform",
        "year": 2021,
        "ev_mm": 1025.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 62.12,
        "revenue_mm": 231.79,
        "ebitda_margin": 0.268,
        "hold_years": 3.5,
        "moic": 2.0,
        "irr": 0.2190,
        "payer_mix": {"commercial": 0.64, "medicare": 0.26, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.64,
        "region": "National",
        "buyer": "Audax",
        "status": "Active",
    },
    {
        "company_name": "Harbor Sports & Ortho Institute",
        "sector": "Sports Medicine",
        "subsector": "Academic-Affiliated Sports Med",
        "year": 2018,
        "ev_mm": 240.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 20.0,
        "revenue_mm": 80.0,
        "ebitda_margin": 0.25,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.2033,
        "payer_mix": {"commercial": 0.72, "medicare": 0.16, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.72,
        "region": "Northeast",
        "buyer": "Silversmith Capital",
        "status": "Realized",
    },
    {
        "company_name": "Ridgeline Orthopedic Surgery Network",
        "sector": "Orthopedics",
        "subsector": "Orthopedic Surgery + ASC Joint Venture",
        "year": 2023,
        "ev_mm": 560.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 41.48,
        "revenue_mm": 150.29,
        "ebitda_margin": 0.276,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.63, "medicare": 0.27, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.63,
        "region": "Southeast",
        "buyer": "Ampersand",
        "status": "Active",
    },
    {
        "company_name": "Evergreen Therapy Services",
        "sector": "Physical Therapy",
        "subsector": "PT + Occupational Therapy Chain",
        "year": 2017,
        "ev_mm": 175.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 16.67,
        "revenue_mm": 92.61,
        "ebitda_margin": 0.18,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2136,
        "payer_mix": {"commercial": 0.55, "medicare": 0.26, "medicaid": 0.14, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "West",
        "buyer": "Harren Equity",
        "status": "Realized",
    },
    {
        "company_name": "Cornerstone Pain & Spine Specialists",
        "sector": "Pain Management",
        "subsector": "Pain + Spine Combined Practice",
        "year": 2022,
        "ev_mm": 320.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 25.6,
        "revenue_mm": 116.36,
        "ebitda_margin": 0.22,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.60, "medicare": 0.28, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "Midwest",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Vanguard Musculoskeletal Partners",
        "sector": "Musculoskeletal",
        "subsector": "Ortho + PT + Pain Rollup",
        "year": 2024,
        "ev_mm": 470.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 36.15,
        "revenue_mm": 144.6,
        "ebitda_margin": 0.25,
        "hold_years": 3.0,
        "moic": 1.4,
        "irr": 0.1187,
        "payer_mix": {"commercial": 0.61, "medicare": 0.27, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.61,
        "region": "National",
        "buyer": "Varsity",
        "status": "Active",
    },
]
