"""Extended seed batch 16 — deals 336-355."""
from __future__ import annotations
from typing import Any, Dict, List

EXTENDED_SEED_DEALS_16: List[Dict[str, Any]] = [
    {
        "source_id": "seed_336",
        "deal_name": "Kindred Healthcare / TPG + Humana LBO",
        "buyer": "TPG Capital / Humana",
        "seller": "Public shareholders",
        "year": 2018,
        "deal_type": "take-private",
        "sector": "ltach_post_acute",
        "ev_mm": 4100.0,
        "ev_ebitda": 10.8,
        "ebitda_mm": 380.0,
        "revenue_mm": 7200.0,
        "realized_moic": 2.6,
        "realized_irr": 0.19,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.15, "commercial": 0.12, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": 80000,
        "source": "seed",
        "notes": "Largest LTACH operator take-private; split into home health (Kindred at Home) and hospital divisions",
    },
    {
        "source_id": "seed_337",
        "deal_name": "Behavioral Health Group / Frontenac add-on acquisition",
        "buyer": "Frontenac Company",
        "seller": None,
        "year": 2019,
        "deal_type": "add-on",
        "sector": "behavioral_health",
        "ev_mm": 85.0,
        "ev_ebitda": 8.5,
        "ebitda_mm": 10.0,
        "revenue_mm": 42.0,
        "realized_moic": 3.4,
        "realized_irr": 0.28,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.60, "commercial": 0.30, "self_pay": 0.05},
        "geography": "TX",
        "hospital_beds": None,
        "source": "seed",
        "notes": "OTP/MAT clinic add-on; benefited from opioid crisis policy tailwinds and Medicaid expansion",
    },
    {
        "source_id": "seed_338",
        "deal_name": "One Medical / Agilon Primary Care Platform",
        "buyer": "Public IPO (One Medical) / various PE (Agilon)",
        "seller": "Carlyle / existing investors",
        "year": 2020,
        "deal_type": "ipo",
        "sector": "primary_care",
        "ev_mm": 2700.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 277.0,
        "realized_moic": 3.2,
        "realized_irr": 0.26,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.05, "commercial": 0.65, "self_pay": 0.10},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "DPC/concierge primary care IPO; Amazon acquired for $3.9B in 2023",
    },
    {
        "source_id": "seed_339",
        "deal_name": "Envision Healthcare / KKR bankruptcy exit",
        "buyer": "KKR (exit via restructuring)",
        "seller": "KKR",
        "year": 2023,
        "deal_type": "distressed",
        "sector": "emergency_medicine",
        "ev_mm": 1000.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 7900.0,
        "realized_moic": 0.1,
        "realized_irr": -0.30,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.20, "commercial": 0.38, "self_pay": 0.07},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "KKR $9.9B take-private destroyed by surprise billing legislation (NSA) and COVID; filed Ch.11 May 2023",
    },
    # Phase 6 Bug #4 fix: this row describes the same event as
    # seed_162 (ATI Physical Therapy / Advent SPAC 2021). Two rows
    # for one realization double-counted Advent's loss in the
    # sponsor-track-record aggregator (median IRR fell to -38%).
    # Kept as an alternate-angle entry of the same transaction but
    # cleared realized_moic / realized_irr / hold_years so the
    # numbers don't aggregate. seed_162 is the canonical ATI-SPAC
    # realization row. Other metadata (ev_mm / sector / payer_mix)
    # preserved because it still informs deal-search and market-
    # mix queries.
    {
        "source_id": "seed_340",
        "deal_name": "ATI Physical Therapy / Advent SPAC",
        "buyer": "Advent International via Fortress SPAC",
        "seller": "Advent International",
        "year": 2021,
        "deal_type": "spac",
        "sector": "physical_therapy",
        "ev_mm": 2200.0,
        "ev_ebitda": 22.0,
        "ebitda_mm": 100.0,
        "revenue_mm": 730.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.25, "medicaid": 0.10, "commercial": 0.58, "self_pay": 0.07},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Alt-view of seed_162 (ATI SPAC 2021). Realized "
                 "MOIC/IRR cleared to prevent double-counting in the "
                 "sponsor league table. PT SPAC disaster; labor "
                 "inflation + coding changes crushed margins; stock "
                 "fell 95% post-merger.",
    },
    {
        "source_id": "seed_341",
        "deal_name": "National Mentor / Centerbridge LBO",
        "buyer": "Centerbridge Partners",
        "seller": "Vestar Capital Partners",
        "year": 2014,
        "deal_type": "lbo",
        "sector": "home_community_based",
        "ev_mm": 1400.0,
        "ev_ebitda": 9.5,
        "ebitda_mm": 147.0,
        "revenue_mm": 1100.0,
        "realized_moic": 2.8,
        "realized_irr": 0.22,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.80, "commercial": 0.12, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "HCBS/IDD waiver services platform; rebranded to Sevita; second sale to Charlesbank",
    },
    {
        "source_id": "seed_342",
        "deal_name": "US Renal Care / Summit Partners LBO",
        "buyer": "Summit Partners",
        "seller": "Management",
        "year": 2017,
        "deal_type": "lbo",
        "sector": "dialysis",
        "ev_mm": 1100.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 105.0,
        "revenue_mm": 600.0,
        "realized_moic": 3.0,
        "realized_irr": 0.24,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.75, "medicaid": 0.12, "commercial": 0.10, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Third-largest US dialysis operator; ESRD-heavy Medicare dependency; growth via de novo and acquisition",
    },
    {
        "source_id": "seed_343",
        "deal_name": "TridentCare / Gridiron Capital LBO",
        "buyer": "Gridiron Capital",
        "seller": "Kohlberg & Company",
        "year": 2019,
        "deal_type": "lbo",
        "sector": "mobile_diagnostics",
        "ev_mm": 475.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 36.5,
        "revenue_mm": 280.0,
        "realized_moic": 3.5,
        "realized_irr": 0.30,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.65, "medicaid": 0.15, "commercial": 0.17, "self_pay": 0.03},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Mobile x-ray/diagnostics for SNFs; COVID accelerated SNF outsourcing; sold to HCI Equity in 2023",
    },
    {
        "source_id": "seed_344",
        "deal_name": "Alignment Healthcare / General Atlantic growth equity",
        "buyer": "General Atlantic",
        "seller": None,
        "year": 2018,
        "deal_type": "growth_equity",
        "sector": "managed_care",
        "ev_mm": 750.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 450.0,
        "realized_moic": 3.8,
        "realized_irr": 0.32,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.95, "medicaid": 0.05, "commercial": 0.0, "self_pay": 0.0},
        "geography": "CA",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Value-based MA plan; IPO 2021 at $4.8B; full-risk capitation model for complex Medicare patients",
    },
    {
        "source_id": "seed_345",
        "deal_name": "LifeStance Health / TPG growth equity + IPO",
        "buyer": "TPG Capital / public IPO",
        "seller": "Various",
        "year": 2021,
        "deal_type": "ipo",
        "sector": "behavioral_health",
        "ev_mm": 7000.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 521.0,
        "realized_moic": 1.5,
        "realized_irr": 0.08,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.15, "commercial": 0.70, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Outpatient mental health roll-up IPO; over-expanded, burned cash; stock down 70% from peak IPO price",
    },
    {
        "source_id": "seed_346",
        "deal_name": "Nomi Health / Deerfield Management growth equity",
        "buyer": "Deerfield Management",
        "seller": None,
        "year": 2021,
        "deal_type": "growth_equity",
        "sector": "health_it",
        "ev_mm": 1500.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 150.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": None,
        "geography": "UT",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Direct-to-employer health network; COVID testing platform pivoted to value-based care navigation",
    },
    {
        "source_id": "seed_347",
        "deal_name": "Cano Health / InTandem Capital SPAC + Humana JV",
        "buyer": "InTandem Capital Partners via SPAC",
        "seller": "Barry Shevach (founder)",
        "year": 2021,
        "deal_type": "spac",
        "sector": "primary_care",
        "ev_mm": 4400.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 1400.0,
        "realized_moic": 0.1,
        "realized_irr": -0.55,
        "hold_years": 3.0,
        "payer_mix": {"medicare": 0.75, "medicaid": 0.15, "commercial": 0.08, "self_pay": 0.02},
        "geography": "FL",
        "hospital_beds": None,
        "source": "seed",
        "notes": "MA-focused primary care SPAC disaster; filed Ch.11 Feb 2024 after failing to achieve capitation targets",
    },
    {
        "source_id": "seed_348",
        "deal_name": "US Acute Care Solutions / Welsh Carson LBO",
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Sheridan Healthcare / Amsurg legacy",
        "year": 2015,
        "deal_type": "lbo",
        "sector": "emergency_medicine",
        "ev_mm": 2200.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 183.0,
        "revenue_mm": 1100.0,
        "realized_moic": 2.3,
        "realized_irr": 0.17,
        "hold_years": 6.0,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.22, "commercial": 0.40, "self_pay": 0.08},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Hospitalist + EM physician group; NSA surprise billing reform impacted repricing; sold to private buyer 2021",
    },
    {
        "source_id": "seed_349",
        "deal_name": "Apria Healthcare / Blackstone take-private + re-IPO",
        "buyer": "Blackstone Group",
        "seller": "Public shareholders",
        "year": 2012,
        "deal_type": "take-private",
        "sector": "dme_home_health",
        "ev_mm": 1000.0,
        "ev_ebitda": 6.5,
        "ebitda_mm": 154.0,
        "revenue_mm": 1200.0,
        "realized_moic": 3.3,
        "realized_irr": 0.28,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.10, "commercial": 0.30, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest US home respiratory therapy/DME provider; Blackstone IPO'd again in 2020; acquired by Owens & Minor 2022",
    },
    {
        "source_id": "seed_350",
        "deal_name": "Dental Care Alliance / Harvest Partners LBO",
        "buyer": "Harvest Partners",
        "seller": "KKR / founders",
        "year": 2017,
        "deal_type": "lbo",
        "sector": "dental_dso",
        "ev_mm": 520.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 45.0,
        "revenue_mm": 280.0,
        "realized_moic": 3.1,
        "realized_irr": 0.27,
        "hold_years": 4.5,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.25, "commercial": 0.60, "self_pay": 0.13},
        "geography": "Southeast",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Southeast dental DSO; 300+ locations; Aspen Dental management company model; sold to Solaris Health 2022",
    },
    {
        "source_id": "seed_351",
        "deal_name": "Pediatric Associates / Centerbridge + Humana JV",
        "buyer": "Centerbridge Partners / Humana",
        "seller": "Founders / physician owners",
        "year": 2020,
        "deal_type": "joint_venture",
        "sector": "pediatrics",
        "ev_mm": 2000.0,
        "ev_ebitda": 18.0,
        "ebitda_mm": 111.0,
        "revenue_mm": 550.0,
        "realized_moic": None,
        "realized_irr": None,
        "hold_years": None,
        "payer_mix": {"medicare": 0.02, "medicaid": 0.40, "commercial": 0.55, "self_pay": 0.03},
        "geography": "FL",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Largest independent pediatric group in US; value-based peds care; Humana as strategic JV partner",
    },
    {
        "source_id": "seed_352",
        "deal_name": "Matrix Medical Network / Frazier Healthcare LBO",
        "buyer": "Frazier Healthcare Partners",
        "seller": "ABRY Partners",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "managed_care_services",
        "ev_mm": 625.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 50.0,
        "revenue_mm": 310.0,
        "realized_moic": 4.0,
        "realized_irr": 0.34,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.70, "medicaid": 0.08, "commercial": 0.20, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "In-home health risk assessments for MA plans; COVID drove demand for at-home assessments; sold to Centene JV",
    },
    {
        "source_id": "seed_353",
        "deal_name": "Signify Health / New Mountain Capital LBO + IPO",
        "buyer": "New Mountain Capital / public IPO",
        "seller": "Remedy Partners",
        "year": 2017,
        "deal_type": "lbo",
        "sector": "value_based_care",
        "ev_mm": 500.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 200.0,
        "realized_moic": 5.5,
        "realized_irr": 0.38,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.85, "medicaid": 0.05, "commercial": 0.08, "self_pay": 0.02},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Episode-of-care analytics + home health assessments; IPO 2021; CVS acquired for $8B in 2022",
    },
    {
        "source_id": "seed_354",
        "deal_name": "American Vision Partners / Arizona Eye Consultants roll-up",
        "buyer": "MedEquity Capital",
        "seller": "Physician founders",
        "year": 2018,
        "deal_type": "lbo",
        "sector": "ophthalmology",
        "ev_mm": 140.0,
        "ev_ebitda": 9.3,
        "ebitda_mm": 15.0,
        "revenue_mm": 75.0,
        "realized_moic": 4.2,
        "realized_irr": 0.36,
        "hold_years": 4.0,
        "payer_mix": {"medicare": 0.55, "medicaid": 0.10, "commercial": 0.32, "self_pay": 0.03},
        "geography": "AZ",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Southwest ophthalmology platform; cataract + retina + glaucoma; sold to Vance Thompson Vision 2022",
    },
    {
        "source_id": "seed_355",
        "deal_name": "AccordantHealth / Humana spinout (Evolent Health predecessor)",
        "buyer": "TPG Capital / UPMC",
        "seller": "Humana spinout",
        "year": 2011,
        "deal_type": "carve-out",
        "sector": "population_health",
        "ev_mm": 200.0,
        "ev_ebitda": None,
        "ebitda_mm": None,
        "revenue_mm": 80.0,
        "realized_moic": 6.0,
        "realized_irr": 0.42,
        "hold_years": 5.0,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.20, "commercial": 0.30, "self_pay": 0.05},
        "geography": "National",
        "hospital_beds": None,
        "source": "seed",
        "notes": "Population health management spinout; became Evolent Health; IPO 2015; value-based care technology platform",
    },
]
