"""Extended seed 68: Multispecialty outpatient clinics, multispecialty physician
practices, medical homes, and integrated outpatient networks.

This module provides a curated list of 15 synthetic healthcare private equity
deals focused on multispecialty and integrated outpatient care delivery models.
Each deal dict contains 17 standardized fields covering deal economics, payer
mix, geography, sponsor, and realization status.
"""

EXTENDED_SEED_DEALS_68 = [
    {
        "company_name": "Summit Multispecialty Partners",
        "sector": "Multispecialty",
        "subsector": "Adult Primary + Specialty",
        "year": 2018,
        "ev_mm": 420.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 33.6,
        "revenue_mm": 215.38,
        "ebitda_margin": 0.156,
        "hold_years": 4.5,
        "moic": 2.6,
        "irr": 0.2403,
        "payer_mix": {"commercial": 0.58, "medicare": 0.24, "medicaid": 0.12, "self_pay": 0.06},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Cardinal Outpatient Network",
        "sector": "Outpatient",
        "subsector": "Ambulatory Multispecialty",
        "year": 2019,
        "ev_mm": 275.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 25.0,
        "revenue_mm": 147.06,
        "ebitda_margin": 0.17,
        "hold_years": 5.0,
        "moic": 2.2,
        "irr": 0.1706,
        "payer_mix": {"commercial": 0.52, "medicare": 0.28, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.52,
        "region": "Southeast",
        "buyer": "Cressey",
        "status": "Realized",
    },
    {
        "company_name": "Heartland Medical Home Group",
        "sector": "Medical Home",
        "subsector": "Value-Based Primary Care",
        "year": 2020,
        "ev_mm": 185.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 13.21,
        "revenue_mm": 66.05,
        "ebitda_margin": 0.20,
        "hold_years": 3.5,
        "moic": 2.0,
        "irr": 0.2190,
        "payer_mix": {"commercial": 0.30, "medicare": 0.48, "medicaid": 0.18, "self_pay": 0.04},
        "comm_pct": 0.30,
        "region": "Midwest",
        "buyer": "Frazier Healthcare",
        "status": "Active",
    },
    {
        "company_name": "Pacific Integrated Care Alliance",
        "sector": "Integrated Outpatient",
        "subsector": "Primary + Urgent + Specialty",
        "year": 2017,
        "ev_mm": 612.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 45.33,
        "revenue_mm": 275.33,
        "ebitda_margin": 0.1646,
        "hold_years": 5.5,
        "moic": 3.1,
        "irr": 0.2217,
        "payer_mix": {"commercial": 0.55, "medicare": 0.26, "medicaid": 0.14, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "West",
        "buyer": "TPG",
        "status": "Realized",
    },
    {
        "company_name": "Meridian Multispecialty Clinic",
        "sector": "Multispecialty Clinic",
        "subsector": "Regional Clinic Platform",
        "year": 2021,
        "ev_mm": 155.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 14.76,
        "revenue_mm": 92.25,
        "ebitda_margin": 0.16,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": 0.2164,
        "payer_mix": {"commercial": 0.50, "medicare": 0.25, "medicaid": 0.20, "self_pay": 0.05},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Oakwood Physician Partners",
        "sector": "Multispecialty",
        "subsector": "Physician Practice Rollup",
        "year": 2016,
        "ev_mm": 325.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 28.26,
        "revenue_mm": 157.0,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 2.8,
        "irr": 0.1866,
        "payer_mix": {"commercial": 0.54, "medicare": 0.27, "medicaid": 0.13, "self_pay": 0.06},
        "comm_pct": 0.54,
        "region": "Midwest",
        "buyer": "Audax",
        "status": "Realized",
    },
    {
        "company_name": "Beacon Outpatient Health",
        "sector": "Outpatient",
        "subsector": "Community Outpatient",
        "year": 2022,
        "ev_mm": 98.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 8.17,
        "revenue_mm": 58.36,
        "ebitda_margin": 0.14,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1757,
        "payer_mix": {"commercial": 0.46, "medicare": 0.30, "medicaid": 0.19, "self_pay": 0.05},
        "comm_pct": 0.46,
        "region": "Northeast",
        "buyer": "Nautic",
        "status": "Active",
    },
    {
        "company_name": "Lakeshore Medical Home Collective",
        "sector": "Medical Home",
        "subsector": "PCMH Senior-Focused",
        "year": 2019,
        "ev_mm": 240.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 15.48,
        "revenue_mm": 70.36,
        "ebitda_margin": 0.22,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.22, "medicare": 0.58, "medicaid": 0.16, "self_pay": 0.04},
        "comm_pct": 0.22,
        "region": "Midwest",
        "buyer": "KKR",
        "status": "Partially Realized",
    },
    {
        "company_name": "Sunbelt Integrated Physicians",
        "sector": "Integrated Outpatient",
        "subsector": "Multi-Site Integrated Care",
        "year": 2018,
        "ev_mm": 485.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 37.31,
        "revenue_mm": 207.28,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 2.9,
        "irr": 0.2375,
        "payer_mix": {"commercial": 0.51, "medicare": 0.29, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.51,
        "region": "Southeast",
        "buyer": "Linden Capital",
        "status": "Realized",
    },
    {
        "company_name": "Rockies Multispecialty Associates",
        "sector": "Multispecialty Clinic",
        "subsector": "Rural Multispecialty",
        "year": 2020,
        "ev_mm": 72.0,
        "ev_ebitda": 10.0,
        "ebitda_mm": 7.2,
        "revenue_mm": 55.38,
        "ebitda_margin": 0.13,
        "hold_years": 3.5,
        "moic": 1.7,
        "irr": 0.1584,
        "payer_mix": {"commercial": 0.42, "medicare": 0.32, "medicaid": 0.22, "self_pay": 0.04},
        "comm_pct": 0.42,
        "region": "West",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Coastal Physician Network",
        "sector": "Multispecialty",
        "subsector": "Coastal Physician Group",
        "year": 2017,
        "ev_mm": 365.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 30.42,
        "revenue_mm": 174.83,
        "ebitda_margin": 0.174,
        "hold_years": 5.5,
        "moic": 2.5,
        "irr": 0.1743,
        "payer_mix": {"commercial": 0.57, "medicare": 0.24, "medicaid": 0.14, "self_pay": 0.05},
        "comm_pct": 0.57,
        "region": "Northeast",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Prairie Outpatient Services",
        "sector": "Outpatient",
        "subsector": "Ambulatory Services Platform",
        "year": 2023,
        "ev_mm": 128.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 11.64,
        "revenue_mm": 74.62,
        "ebitda_margin": 0.156,
        "hold_years": 2.5,
        "moic": 1.4,
        "irr": 0.1472,
        "payer_mix": {"commercial": 0.48, "medicare": 0.28, "medicaid": 0.19, "self_pay": 0.05},
        "comm_pct": 0.48,
        "region": "Midwest",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Evergreen Medical Home Partners",
        "sector": "Medical Home",
        "subsector": "Advanced Primary Care",
        "year": 2021,
        "ev_mm": 310.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 19.38,
        "revenue_mm": 93.17,
        "ebitda_margin": 0.208,
        "hold_years": 3.0,
        "moic": 1.9,
        "irr": 0.2383,
        "payer_mix": {"commercial": 0.34, "medicare": 0.44, "medicaid": 0.18, "self_pay": 0.04},
        "comm_pct": 0.34,
        "region": "West",
        "buyer": "Frazier Healthcare",
        "status": "Active",
    },
    {
        "company_name": "Atlas Integrated Outpatient Group",
        "sector": "Integrated Outpatient",
        "subsector": "National Integrated Platform",
        "year": 2016,
        "ev_mm": 825.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 56.9,
        "revenue_mm": 316.11,
        "ebitda_margin": 0.18,
        "hold_years": 6.0,
        "moic": 3.4,
        "irr": 0.2269,
        "payer_mix": {"commercial": 0.53, "medicare": 0.27, "medicaid": 0.14, "self_pay": 0.06},
        "comm_pct": 0.53,
        "region": "National",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Highland Multispecialty Clinic Group",
        "sector": "Multispecialty Clinic",
        "subsector": "Regional Clinic Network",
        "year": 2022,
        "ev_mm": 220.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 12.57,
        "revenue_mm": 74.82,
        "ebitda_margin": 0.168,
        "hold_years": 2.5,
        "moic": 1.6,
        "irr": 0.2074,
        "payer_mix": {"commercial": 0.49, "medicare": 0.28, "medicaid": 0.18, "self_pay": 0.05},
        "comm_pct": 0.49,
        "region": "Southeast",
        "buyer": "Audax",
        "status": "Active",
    },
]
