"""Extended seed deals #72: anesthesiology and perioperative services — anesthesia groups, CRNA staffing, pain management, peri-op practice management."""

EXTENDED_SEED_DEALS_72 = [
    {
        "company_name": "North Star Anesthesia Partners",
        "sector": "Anesthesiology",
        "subsector": "Hospital-Based Anesthesia Group",
        "year": 2018,
        "ev_mm": 640.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 47.41,
        "revenue_mm": 225.76,
        "ebitda_margin": 0.21,
        "hold_years": 5.5,
        "moic": 2.8,
        "irr": 0.2059,
        "payer_mix": {"commercial": 0.55, "medicare": 0.28, "medicaid": 0.12, "self_pay": 0.05},
        "comm_pct": 0.55,
        "region": "Southeast",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Keystone Perioperative Solutions",
        "sector": "Perioperative",
        "subsector": "Peri-Op Practice Management",
        "year": 2020,
        "ev_mm": 310.0,
        "ev_ebitda": 12.8,
        "ebitda_mm": 24.22,
        "revenue_mm": 121.1,
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 2.3,
        "irr": 0.2315,
        "payer_mix": {"commercial": 0.58, "medicare": 0.25, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "Northeast",
        "buyer": "Audax",
        "status": "Active",
    },
    {
        "company_name": "Summit CRNA Staffing",
        "sector": "CRNA Staffing",
        "subsector": "Nurse Anesthetist Locums",
        "year": 2021,
        "ev_mm": 185.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 16.09,
        "revenue_mm": 80.45,
        "ebitda_margin": 0.20,
        "hold_years": 3.5,
        "moic": 2.0,
        "irr": 0.2190,
        "payer_mix": {"commercial": 0.52, "medicare": 0.30, "medicaid": 0.14, "self_pay": 0.04},
        "comm_pct": 0.52,
        "region": "Midwest",
        "buyer": "Shore Capital",
        "status": "Active",
    },
    {
        "company_name": "Cornerstone Pain Management",
        "sector": "Pain Services",
        "subsector": "Interventional Pain Clinics",
        "year": 2019,
        "ev_mm": 425.0,
        "ev_ebitda": 14.2,
        "ebitda_mm": 29.93,
        "revenue_mm": 124.71,
        "ebitda_margin": 0.24,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.48, "medicare": 0.35, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.48,
        "region": "West",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "MedStar Anesthesia Associates",
        "sector": "Anesthesia",
        "subsector": "Multi-Site Anesthesia Platform",
        "year": 2017,
        "ev_mm": 875.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 58.33,
        "revenue_mm": 265.14,
        "ebitda_margin": 0.22,
        "hold_years": 6.0,
        "moic": 3.2,
        "irr": 0.2139,
        "payer_mix": {"commercial": 0.56, "medicare": 0.27, "medicaid": 0.12, "self_pay": 0.05},
        "comm_pct": 0.56,
        "region": "National",
        "buyer": "TPG",
        "status": "Realized",
    },
    {
        "company_name": "Blue Ridge Pain Centers",
        "sector": "Pain Services",
        "subsector": "Spine & Pain Clinics",
        "year": 2022,
        "ev_mm": 220.0,
        "ev_ebitda": 12.2,
        "ebitda_mm": 18.03,
        "revenue_mm": 85.86,
        "ebitda_margin": 0.21,
        "hold_years": 3.0,
        "moic": 1.8,
        "irr": 0.2164,
        "payer_mix": {"commercial": 0.50, "medicare": 0.33, "medicaid": 0.14, "self_pay": 0.03},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Pacific Anesthesia Medical Group",
        "sector": "Anesthesiology",
        "subsector": "ASC Anesthesia Services",
        "year": 2020,
        "ev_mm": 510.0,
        "ev_ebitda": 14.8,
        "ebitda_mm": 34.46,
        "revenue_mm": 143.58,
        "ebitda_margin": 0.24,
        "hold_years": 4.5,
        "moic": 2.5,
        "irr": 0.2258,
        "payer_mix": {"commercial": 0.60, "medicare": 0.24, "medicaid": 0.12, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "West",
        "buyer": "American Securities",
        "status": "Partially Realized",
    },
    {
        "company_name": "Apex Perioperative Holdings",
        "sector": "Perioperative",
        "subsector": "Surgical Co-Management & MSO",
        "year": 2016,
        "ev_mm": 290.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 22.31,
        "revenue_mm": 115.0,
        "ebitda_margin": 0.194,
        "hold_years": 6.5,
        "moic": 3.4,
        "irr": 0.2072,
        "payer_mix": {"commercial": 0.54, "medicare": 0.29, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.54,
        "region": "Midwest",
        "buyer": "Summit Partners",
        "status": "Realized",
    },
    {
        "company_name": "Bright Horizon CRNA Group",
        "sector": "CRNA Staffing",
        "subsector": "Rural Hospital CRNA Coverage",
        "year": 2023,
        "ev_mm": 95.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 9.05,
        "revenue_mm": 51.71,
        "ebitda_margin": 0.175,
        "hold_years": 2.5,
        "moic": 1.5,
        "irr": 0.1761,
        "payer_mix": {"commercial": 0.44, "medicare": 0.34, "medicaid": 0.18, "self_pay": 0.04},
        "comm_pct": 0.44,
        "region": "Midwest",
        "buyer": "Harren",
        "status": "Active",
    },
    {
        "company_name": "Coastal Pain & Spine Institute",
        "sector": "Pain Services",
        "subsector": "Comprehensive Pain Management",
        "year": 2019,
        "ev_mm": 160.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 13.56,
        "revenue_mm": 64.57,
        "ebitda_margin": 0.21,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": 0.1914,
        "payer_mix": {"commercial": 0.49, "medicare": 0.32, "medicaid": 0.15, "self_pay": 0.04},
        "comm_pct": 0.49,
        "region": "Southeast",
        "buyer": "Shore Capital",
        "status": "Realized",
    },
    {
        "company_name": "Gateway Anesthesia Partners",
        "sector": "Anesthesia",
        "subsector": "Regional Anesthesia Network",
        "year": 2021,
        "ev_mm": 720.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": 45.57,
        "revenue_mm": 189.88,
        "ebitda_margin": 0.24,
        "hold_years": 4.0,
        "moic": 2.2,
        "irr": 0.2179,
        "payer_mix": {"commercial": 0.57, "medicare": 0.26, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.57,
        "region": "Northeast",
        "buyer": "Ares",
        "status": "Active",
    },
    {
        "company_name": "Sentinel Perioperative Services",
        "sector": "Perioperative",
        "subsector": "OR Management & Scheduling",
        "year": 2022,
        "ev_mm": 135.0,
        "ev_ebitda": 11.2,
        "ebitda_mm": 12.05,
        "revenue_mm": 66.94,
        "ebitda_margin": 0.18,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.51, "medicare": 0.28, "medicaid": 0.16, "self_pay": 0.05},
        "comm_pct": 0.51,
        "region": "West",
        "buyer": "Varsity",
        "status": "Active",
    },
    {
        "company_name": "Vanguard Anesthesia Group",
        "sector": "Anesthesiology",
        "subsector": "Academic Medical Center Anesthesia",
        "year": 2016,
        "ev_mm": 1150.0,
        "ev_ebitda": 17.5,
        "ebitda_mm": 65.71,
        "revenue_mm": 251.76,
        "ebitda_margin": 0.261,
        "hold_years": 6.5,
        "moic": 3.7,
        "irr": 0.2230,
        "payer_mix": {"commercial": 0.62, "medicare": 0.24, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.62,
        "region": "National",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Redwood CRNA Alliance",
        "sector": "CRNA Staffing",
        "subsector": "ASC & Outpatient CRNA Services",
        "year": 2024,
        "ev_mm": 72.0,
        "ev_ebitda": 10.2,
        "ebitda_mm": 7.06,
        "revenue_mm": 40.11,
        "ebitda_margin": 0.176,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.46, "medicare": 0.31, "medicaid": 0.18, "self_pay": 0.05},
        "comm_pct": 0.46,
        "region": "West",
        "buyer": "Harren",
        "status": "Active",
    },
    {
        "company_name": "Crescent Pain Institute",
        "sector": "Pain Services",
        "subsector": "Interventional & Regenerative Pain",
        "year": 2023,
        "ev_mm": 265.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 20.08,
        "revenue_mm": 87.3,
        "ebitda_margin": 0.23,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.53, "medicare": 0.30, "medicaid": 0.13, "self_pay": 0.04},
        "comm_pct": 0.53,
        "region": "Southeast",
        "buyer": "American Securities",
        "status": "Active",
    },
]
