"""Extended seed deals batch 75: MSO platforms, physician practice management,
healthcare services holdcos, and umbrella platforms.

This module contains 15 synthetic healthcare private equity deal records
focused on management services organizations (MSOs), multi-specialty
physician practice management platforms, and healthcare services holding
companies. All figures are illustrative and intended for corpus-level
analytics, scoring, and backtesting workflows.
"""

EXTENDED_SEED_DEALS_75 = [
    {
        "company_name": "Meridian Physician Partners",
        "sector": "MSO Platform",
        "subsector": "Multi-Specialty Primary Care MSO",
        "year": 2018,
        "ev_mm": 485.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 35.93,
        "revenue_mm": 199.61,
        "ebitda_margin": 0.18,
        "hold_years": 5.0,
        "moic": 2.6,
        "irr": 0.2106,
        "payer_mix": {"commercial": 0.52, "medicare": 0.28, "medicaid": 0.14, "self_pay": 0.06},
        "comm_pct": 0.52,
        "region": "Southeast",
        "buyer": "Welsh Carson",
        "status": "Realized",
    },
    {
        "company_name": "Cascadia Health Services Holdings",
        "sector": "Services Holdco",
        "subsector": "Specialty Services Umbrella",
        "year": 2019,
        "ev_mm": 920.0,
        "ev_ebitda": 15.2,
        "ebitda_mm": 60.53,
        "revenue_mm": 302.65,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 2.9,
        "irr": 0.2136,
        "payer_mix": {"commercial": 0.48, "medicare": 0.32, "medicaid": 0.15, "self_pay": 0.05},
        "comm_pct": 0.48,
        "region": "West",
        "buyer": "KKR",
        "status": "Active",
    },
    {
        "company_name": "Atlas Orthopedic Management",
        "sector": "Practice Management",
        "subsector": "Orthopedic MSO",
        "year": 2020,
        "ev_mm": 640.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 45.71,
        "revenue_mm": 208.72,
        "ebitda_margin": 0.219,
        "hold_years": 4.0,
        "moic": 2.3,
        "irr": 0.2315,
        "payer_mix": {"commercial": 0.58, "medicare": 0.30, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.58,
        "region": "Midwest",
        "buyer": "Bain Capital",
        "status": "Active",
    },
    {
        "company_name": "Summit Dermatology Partners",
        "sector": "Multi-Specialty MSO",
        "subsector": "Dermatology Roll-up",
        "year": 2017,
        "ev_mm": 310.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 24.8,
        "revenue_mm": 110.22,
        "ebitda_margin": 0.225,
        "hold_years": 6.0,
        "moic": 2.1,
        "irr": 0.1316,
        "payer_mix": {"commercial": 0.62, "medicare": 0.26, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.62,
        "region": "Northeast",
        "buyer": "Thomas H. Lee",
        "status": "Realized",
    },
    {
        "company_name": "Pinnacle Gastroenterology Group",
        "sector": "Practice Management",
        "subsector": "Gastroenterology MSO",
        "year": 2021,
        "ev_mm": 780.0,
        "ev_ebitda": 15.8,
        "ebitda_mm": 49.37,
        "revenue_mm": 233.76,
        "ebitda_margin": 0.2112,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.50, "medicare": 0.34, "medicaid": 0.12, "self_pay": 0.04},
        "comm_pct": 0.50,
        "region": "Southeast",
        "buyer": "TPG",
        "status": "Active",
    },
    {
        "company_name": "Beacon Women's Health Holdings",
        "sector": "MSO Platform",
        "subsector": "OB/GYN Platform",
        "year": 2019,
        "ev_mm": 420.0,
        "ev_ebitda": 13.2,
        "ebitda_mm": 31.82,
        "revenue_mm": 186.08,
        "ebitda_margin": 0.171,
        "hold_years": 5.0,
        "moic": 2.4,
        "irr": 0.1914,
        "payer_mix": {"commercial": 0.64, "medicare": 0.12, "medicaid": 0.20, "self_pay": 0.04},
        "comm_pct": 0.64,
        "region": "National",
        "buyer": "Oak HC/FT",
        "status": "Partially Realized",
    },
    {
        "company_name": "Keystone Ophthalmology Alliance",
        "sector": "Multi-Specialty MSO",
        "subsector": "Ophthalmology Platform",
        "year": 2016,
        "ev_mm": 230.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 95.24,
        "ebitda_margin": 0.21,
        "hold_years": 6.5,
        "moic": 3.2,
        "irr": 0.196,
        "payer_mix": {"commercial": 0.40, "medicare": 0.48, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.40,
        "region": "Northeast",
        "buyer": "Warburg",
        "status": "Realized",
    },
    {
        "company_name": "Harbor Point Urology Services",
        "sector": "Practice Management",
        "subsector": "Urology MSO",
        "year": 2022,
        "ev_mm": 355.0,
        "ev_ebitda": 13.8,
        "ebitda_mm": 25.72,
        "revenue_mm": 125.46,
        "ebitda_margin": 0.205,
        "hold_years": 3.0,
        "moic": 1.6,
        "irr": 0.1696,
        "payer_mix": {"commercial": 0.44, "medicare": 0.42, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.44,
        "region": "Midwest",
        "buyer": "Nautic",
        "status": "Active",
    },
    {
        "company_name": "Ridgeline Behavioral Health Services",
        "sector": "Healthcare Services",
        "subsector": "Behavioral Health Holdco",
        "year": 2020,
        "ev_mm": 560.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 38.62,
        "revenue_mm": 214.56,
        "ebitda_margin": 0.18,
        "hold_years": 4.5,
        "moic": 2.2,
        "irr": 0.1915,
        "payer_mix": {"commercial": 0.38, "medicare": 0.18, "medicaid": 0.38, "self_pay": 0.06},
        "comm_pct": 0.38,
        "region": "West",
        "buyer": "General Atlantic",
        "status": "Active",
    },
    {
        "company_name": "Evergreen Dental Partners",
        "sector": "MSO Platform",
        "subsector": "DSO Umbrella Platform",
        "year": 2018,
        "ev_mm": 1150.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 69.7,
        "revenue_mm": 334.29,
        "ebitda_margin": 0.2085,
        "hold_years": 5.5,
        "moic": 2.7,
        "irr": 0.1979,
        "payer_mix": {"commercial": 0.56, "medicare": 0.06, "medicaid": 0.22, "self_pay": 0.16},
        "comm_pct": 0.56,
        "region": "National",
        "buyer": "Apollo",
        "status": "Partially Realized",
    },
    {
        "company_name": "Sentinel Cardiology Network",
        "sector": "Multi-Specialty MSO",
        "subsector": "Cardiology Platform",
        "year": 2021,
        "ev_mm": 890.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 55.62,
        "revenue_mm": 255.14,
        "ebitda_margin": 0.218,
        "hold_years": 4.0,
        "moic": 2.0,
        "irr": 0.1892,
        "payer_mix": {"commercial": 0.42, "medicare": 0.46, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.42,
        "region": "Southeast",
        "buyer": "Welsh Carson",
        "status": "Active",
    },
    {
        "company_name": "Trailhead Primary Care Holdings",
        "sector": "Services Holdco",
        "subsector": "Value-Based Primary Care",
        "year": 2022,
        "ev_mm": 1380.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": 74.59,
        "revenue_mm": 466.19,
        "ebitda_margin": 0.16,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": 0.1447,
        "payer_mix": {"commercial": 0.30, "medicare": 0.52, "medicaid": 0.14, "self_pay": 0.04},
        "comm_pct": 0.30,
        "region": "West",
        "buyer": "General Atlantic",
        "status": "Active",
    },
    {
        "company_name": "Lattice ENT & Allergy Group",
        "sector": "Practice Management",
        "subsector": "ENT / Allergy MSO",
        "year": 2019,
        "ev_mm": 185.0,
        "ev_ebitda": 11.8,
        "ebitda_mm": 15.68,
        "revenue_mm": 67.88,
        "ebitda_margin": 0.231,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.60, "medicare": 0.26, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "Midwest",
        "buyer": "Nautic",
        "status": "Realized",
    },
    {
        "company_name": "Fairway Musculoskeletal Holdings",
        "sector": "Healthcare Services",
        "subsector": "Musculoskeletal Umbrella",
        "year": 2023,
        "ev_mm": 110.0,
        "ev_ebitda": 10.5,
        "ebitda_mm": 10.48,
        "revenue_mm": 41.92,
        "ebitda_margin": 0.25,
        "hold_years": 3.0,
        "moic": 1.4,
        "irr": 0.1187,
        "payer_mix": {"commercial": 0.54, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.04},
        "comm_pct": 0.54,
        "region": "Northeast",
        "buyer": "Thomas H. Lee",
        "status": "Active",
    },
    {
        "company_name": "Northstar Integrated Specialty Care",
        "sector": "MSO Platform",
        "subsector": "Integrated Multi-Specialty Platform",
        "year": 2024,
        "ev_mm": 1495.0,
        "ev_ebitda": 19.5,
        "ebitda_mm": 76.67,
        "revenue_mm": 331.33,
        "ebitda_margin": 0.2314,
        "hold_years": 4.5,
        "moic": 3.6,
        "irr": 0.3293,
        "payer_mix": {"commercial": 0.50, "medicare": 0.32, "medicaid": 0.14, "self_pay": 0.04},
        "comm_pct": 0.50,
        "region": "National",
        "buyer": "KKR",
        "status": "Active",
    },
]
