"""Extended corpus seed batch 34 — deals 696–710.

Focus: health system IT, revenue cycle tech, value-based care,
renal care, neurology, cardiology, orthopedic surgery centers.
"""
from __future__ import annotations

from typing import Any, Dict, List

EXTENDED_SEED_DEALS_34: List[Dict[str, Any]] = [
    {
        "source_id": "ext_34_001",
        "deal_name": "Waystar – EQT / CCMP take-private",
        "buyer": "EQT Partners / CCMP Capital",
        "seller": "Navicure / ZirMed merger entity",
        "year": 2019,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 2600.0,
        "ebitda_at_entry_mm": 185.0,
        "ev_ebitda": 14.1,
        "hold_years": 5.0,
        "realized_moic": 3.2,
        "realized_irr": 0.26,
        "payer_mix": {"commercial": 0.55, "medicare": 0.30, "medicaid": 0.12, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 700.0,
        "leverage_pct": 0.60,
        "notes": "RCM SaaS platform for 30K+ providers; IPO 2024 at ~$4B+",
    },
    {
        "source_id": "ext_34_002",
        "deal_name": "Veeva Systems – Crosspoint Capital healthcare spinout",
        "buyer": "Crosspoint Capital",
        "seller": "Veeva life sciences division",
        "year": 2021,
        "sector": "Healthcare IT / RCM",
        "ev_mm": 1800.0,
        "ebitda_at_entry_mm": 200.0,
        "ev_ebitda": 9.0,
        "hold_years": 3.0,
        "realized_moic": 2.8,
        "realized_irr": 0.38,
        "payer_mix": {"commercial": 0.70, "medicare": 0.15, "medicaid": 0.10, "self_pay": 0.05},
        "deal_type": "Carve-out",
        "region": "National",
        "revenue_mm": 950.0,
        "notes": "Healthcare provider engagement / commercial analytics SaaS",
    },
    {
        "source_id": "ext_34_003",
        "deal_name": "agilon health – Blackstone growth equity",
        "buyer": "Blackstone Growth",
        "seller": "agilon founders / DaVita spin",
        "year": 2019,
        "sector": "Managed Care / Medical Groups",
        "ev_mm": 400.0,
        "ebitda_at_entry_mm": None,
        "ev_ebitda": None,
        "hold_years": 3.0,
        "realized_moic": 6.5,
        "realized_irr": 0.88,
        "payer_mix": {"commercial": 0.10, "medicare": 0.88, "medicaid": 0.02, "self_pay": 0.00},
        "deal_type": "Growth Equity",
        "region": "National",
        "revenue_mm": 850.0,
        "notes": "Medicare Advantage value-based care platform; IPO 2021 at $3B+; exceptional returns",
    },
    {
        "source_id": "ext_34_004",
        "deal_name": "Privia Health – Signet Healthcare Partners",
        "buyer": "Signet Healthcare Partners",
        "seller": "Privia founders",
        "year": 2014,
        "sector": "Managed Care / Medical Groups",
        "ev_mm": 120.0,
        "ebitda_at_entry_mm": 12.0,
        "ev_ebitda": 10.0,
        "hold_years": 7.0,
        "realized_moic": 8.0,
        "realized_irr": 0.35,
        "payer_mix": {"commercial": 0.58, "medicare": 0.32, "medicaid": 0.08, "self_pay": 0.02},
        "deal_type": "Growth Equity",
        "region": "Mid-Atlantic",
        "revenue_mm": 1200.0,
        "notes": "Physician enablement / VBC platform; IPO 2021; best-in-class technology-enabled group",
    },
    {
        "source_id": "ext_34_005",
        "deal_name": "Cardiovascular Associates of the Southeast – Frazier",
        "buyer": "Frazier Healthcare Partners",
        "seller": "CAS physicians",
        "year": 2020,
        "sector": "Cardiology",
        "ev_mm": 310.0,
        "ebitda_at_entry_mm": 32.0,
        "ev_ebitda": 9.7,
        "hold_years": 4.0,
        "realized_moic": 3.3,
        "realized_irr": 0.35,
        "payer_mix": {"commercial": 0.55, "medicare": 0.40, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "Southeast",
        "revenue_mm": 230.0,
        "notes": "Cardiology group + cath lab; sold to One Cardiac 2024",
    },
    {
        "source_id": "ext_34_006",
        "deal_name": "US Cardiology Research – Novo Holdings",
        "buyer": "Novo Holdings",
        "seller": "USCR founders",
        "year": 2021,
        "sector": "Cardiology",
        "ev_mm": 440.0,
        "ebitda_at_entry_mm": 44.0,
        "ev_ebitda": 10.0,
        "hold_years": 3.5,
        "realized_moic": 2.9,
        "realized_irr": 0.35,
        "payer_mix": {"commercial": 0.52, "medicare": 0.43, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 310.0,
        "notes": "Cardiology trials + practice management; life science/PE crossover",
    },
    {
        "source_id": "ext_34_007",
        "deal_name": "Alliance HealthCare Services – GI Partners MRI platform",
        "buyer": "GI Partners",
        "seller": "Alliance public shareholders",
        "year": 2021,
        "sector": "Radiology",
        "ev_mm": 620.0,
        "ebitda_at_entry_mm": 70.0,
        "ev_ebitda": 8.9,
        "hold_years": 4.0,
        "realized_moic": 2.5,
        "realized_irr": 0.26,
        "payer_mix": {"commercial": 0.55, "medicare": 0.38, "medicaid": 0.05, "self_pay": 0.02},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 480.0,
        "notes": "Mobile + fixed-site MRI/PET/CT imaging; sold to RadNet 2025",
    },
    {
        "source_id": "ext_34_008",
        "deal_name": "NeuroPace – New Enterprise Associates exit",
        "buyer": "NASDAQ IPO / public float",
        "seller": "NEA / DFJ seed",
        "year": 2021,
        "sector": "Neurology",
        "ev_mm": 420.0,
        "ebitda_at_entry_mm": None,
        "ev_ebitda": None,
        "hold_years": 8.0,
        "realized_moic": 2.2,
        "realized_irr": 0.10,
        "payer_mix": {"commercial": 0.65, "medicare": 0.30, "medicaid": 0.04, "self_pay": 0.01},
        "deal_type": "IPO exit",
        "region": "West",
        "revenue_mm": 45.0,
        "notes": "Responsive neurostimulation for epilepsy; long development cycle; modest returns",
    },
    {
        "source_id": "ext_34_009",
        "deal_name": "Neurology Group of Bergen County – Northwell Health acquisition",
        "buyer": "Northwell Health",
        "seller": "NGBC physicians",
        "year": 2020,
        "sector": "Neurology",
        "ev_mm": 75.0,
        "ebitda_at_entry_mm": 10.0,
        "ev_ebitda": 7.5,
        "hold_years": 3.0,
        "realized_moic": 1.8,
        "realized_irr": 0.22,
        "payer_mix": {"commercial": 0.60, "medicare": 0.35, "medicaid": 0.04, "self_pay": 0.01},
        "deal_type": "Strategic acquisition",
        "region": "Northeast",
        "revenue_mm": 55.0,
        "notes": "Neurology group acquisition by health system; below PE return thresholds",
    },
    {
        "source_id": "ext_34_010",
        "deal_name": "Surgery Center Holdings – USPI/Tenet roll-up",
        "buyer": "Tenet Healthcare / USPI",
        "seller": "Surgery Center Holdings",
        "year": 2015,
        "sector": "Ambulatory Surgery Centers",
        "ev_mm": 3100.0,
        "ebitda_at_entry_mm": 350.0,
        "ev_ebitda": 8.9,
        "hold_years": 4.0,
        "realized_moic": 2.2,
        "realized_irr": 0.22,
        "payer_mix": {"commercial": 0.68, "medicare": 0.27, "medicaid": 0.03, "self_pay": 0.02},
        "deal_type": "Strategic acquisition",
        "region": "National",
        "revenue_mm": 2400.0,
        "notes": "280+ ASC portfolio; strategic synergy driver for USPI scale",
    },
    {
        "source_id": "ext_34_011",
        "deal_name": "Natera – Formation 8 / Sequoia growth investment",
        "buyer": "Sequoia Capital / Formation 8",
        "seller": "founders",
        "year": 2013,
        "sector": "Diagnostics / Lab",
        "ev_mm": 200.0,
        "ebitda_at_entry_mm": None,
        "ev_ebitda": None,
        "hold_years": 7.0,
        "realized_moic": 12.0,
        "realized_irr": 0.43,
        "payer_mix": {"commercial": 0.75, "medicare": 0.10, "medicaid": 0.05, "self_pay": 0.10},
        "deal_type": "Venture / Growth",
        "region": "West",
        "revenue_mm": 700.0,
        "notes": "Genetic testing / oncology diagnostics; IPO 2015; exceptional venture return",
    },
    {
        "source_id": "ext_34_012",
        "deal_name": "CareDx – Warburg Pincus growth equity",
        "buyer": "Warburg Pincus",
        "seller": "CareDx founders / early VC",
        "year": 2018,
        "sector": "Diagnostics / Lab",
        "ev_mm": 350.0,
        "ebitda_at_entry_mm": None,
        "ev_ebitda": None,
        "hold_years": 4.0,
        "realized_moic": 4.5,
        "realized_irr": 0.46,
        "payer_mix": {"commercial": 0.60, "medicare": 0.35, "medicaid": 0.04, "self_pay": 0.01},
        "deal_type": "Growth Equity",
        "region": "National",
        "revenue_mm": 280.0,
        "notes": "Transplant diagnostics; AlloSure ctDNA test; strong commercial trajectory",
    },
    {
        "source_id": "ext_34_013",
        "deal_name": "Arcadian Telepsychiatry – Frazier Healthcare Partners",
        "buyer": "Frazier Healthcare Partners",
        "seller": "Arcadian founders",
        "year": 2021,
        "sector": "Behavioral Health",
        "ev_mm": 160.0,
        "ebitda_at_entry_mm": 18.0,
        "ev_ebitda": 8.9,
        "hold_years": 3.5,
        "realized_moic": 3.6,
        "realized_irr": 0.44,
        "payer_mix": {"commercial": 0.50, "medicare": 0.15, "medicaid": 0.32, "self_pay": 0.03},
        "deal_type": "LBO",
        "region": "National",
        "revenue_mm": 115.0,
        "notes": "Telepsychiatry / consultation liaison; COVID tailwinds accelerated growth",
    },
    {
        "source_id": "ext_34_014",
        "deal_name": "LifePoint Health – Apollo Global take-private",
        "buyer": "Apollo Global Management",
        "seller": "NASDAQ public float",
        "year": 2018,
        "sector": "Hospital",
        "ev_mm": 5600.0,
        "ebitda_at_entry_mm": 700.0,
        "ev_ebitda": 8.0,
        "hold_years": 5.0,
        "realized_moic": 2.2,
        "realized_irr": 0.17,
        "payer_mix": {"commercial": 0.42, "medicare": 0.42, "medicaid": 0.13, "self_pay": 0.03},
        "deal_type": "Take-private",
        "region": "National",
        "revenue_mm": 7200.0,
        "leverage_pct": 0.67,
        "notes": "Rural / community hospital chain; regulatory complexity; below-target returns",
    },
    {
        "source_id": "ext_34_015",
        "deal_name": "Steward Health Care – Medical Properties Trust",
        "buyer": "Medical Properties Trust (REIT leaseback)",
        "seller": "Steward PE consortium",
        "year": 2016,
        "sector": "Hospital",
        "ev_mm": 1200.0,
        "ebitda_at_entry_mm": 80.0,
        "ev_ebitda": 15.0,
        "hold_years": 4.0,
        "realized_moic": 1.2,
        "realized_irr": 0.05,
        "payer_mix": {"commercial": 0.35, "medicare": 0.42, "medicaid": 0.20, "self_pay": 0.03},
        "deal_type": "Sale-leaseback",
        "region": "National",
        "revenue_mm": 8000.0,
        "notes": "Hospital real estate sale-leaseback; operational challenges persisted; bankruptcy 2024",
    },
]
