"""Extended seed batch 57 — healthcare IT and digital health infrastructure PE deals.

Covers EHR/EMR vendors, health information exchanges, interoperability platforms,
clinical decision support, patient engagement tools, and telehealth infrastructure.
All financial metrics are internally consistent: ebitda_mm = ev_mm / ev_ebitda,
revenue_mm = ebitda_mm / ebitda_margin, irr = moic^(1/hold_years) - 1.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_57: list[dict] = [
    {
        "company_name": "Arcadian Health Networks",
        "sector": "Interoperability",
        "subsector": "Health Information Exchange",
        "year": 2018,
        "ev_mm": 210.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": 11.35,
        "revenue_mm": 56.75,
        "ebitda_margin": 0.20,
        "hold_years": 4.0,
        "moic": 3.1,
        "irr": 0.3269,
        "payer_mix": {"commercial": 0.72, "medicare": 0.14, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.72,
        "region": "Northeast",
        "buyer": "Warburg Pincus",
        "status": "Realized",
    },
    {
        "company_name": "PrimePath EHR Solutions",
        "sector": "EHR/EMR",
        "subsector": "Ambulatory EHR",
        "year": 2016,
        "ev_mm": 145.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 10.0,
        "revenue_mm": 47.62,
        "ebitda_margin": 0.21,
        "hold_years": 5.0,
        "moic": 2.8,
        "irr": 0.2285,
        "payer_mix": {"commercial": 0.68, "medicare": 0.18, "medicaid": 0.10, "self_pay": 0.04},
        "comm_pct": 0.68,
        "region": "Midwest",
        "buyer": "Francisco Partners",
        "status": "Realized",
    },
    {
        "company_name": "Veritas Clinical Intelligence",
        "sector": "Clinical Decision Support",
        "subsector": "Sepsis and Deterioration Alerting",
        "year": 2021,
        "ev_mm": 390.0,
        "ev_ebitda": 28.0,
        "ebitda_mm": 13.93,
        "revenue_mm": 53.58,
        "ebitda_margin": 0.26,
        "hold_years": 3.0,
        "moic": 2.9,
        "irr": 0.426,
        "payer_mix": {"commercial": 0.80, "medicare": 0.10, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.80,
        "region": "National",
        "buyer": "Thoma Bravo",
        "status": "Active",
    },
    {
        "company_name": "BridgeLink Interoperability",
        "sector": "Interoperability",
        "subsector": "FHIR API Platform",
        "year": 2020,
        "ev_mm": 275.0,
        "ev_ebitda": 22.0,
        "ebitda_mm": 12.5,
        "revenue_mm": 55.56,
        "ebitda_margin": 0.225,
        "hold_years": 3.5,
        "moic": 3.4,
        "irr": 0.4186,
        "payer_mix": {"commercial": 0.75, "medicare": 0.12, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.75,
        "region": "West",
        "buyer": "General Atlantic",
        "status": "Partially Realized",
    },
    {
        "company_name": "NovaMed Telehealth Platform",
        "sector": "Telehealth",
        "subsector": "Virtual Primary Care",
        "year": 2019,
        "ev_mm": 520.0,
        "ev_ebitda": 32.5,
        "ebitda_mm": 16.0,
        "revenue_mm": 72.73,
        "ebitda_margin": 0.22,
        "hold_years": 4.5,
        "moic": 4.2,
        "irr": 0.3756,
        "payer_mix": {"commercial": 0.83, "medicare": 0.08, "medicaid": 0.06, "self_pay": 0.03},
        "comm_pct": 0.83,
        "region": "National",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Catalyst Patient Engagement",
        "sector": "Patient Engagement",
        "subsector": "Patient Portal and Messaging",
        "year": 2017,
        "ev_mm": 95.0,
        "ev_ebitda": 19.0,
        "ebitda_mm": 5.0,
        "revenue_mm": 29.41,
        "ebitda_margin": 0.17,
        "hold_years": 4.0,
        "moic": 2.6,
        "irr": 0.2698,
        "payer_mix": {"commercial": 0.70, "medicare": 0.15, "medicaid": 0.11, "self_pay": 0.04},
        "comm_pct": 0.70,
        "region": "Southeast",
        "buyer": "GTCR",
        "status": "Realized",
    },
    {
        "company_name": "Helix Data Exchange",
        "sector": "Healthcare IT",
        "subsector": "Clinical Data Aggregation",
        "year": 2022,
        "ev_mm": 640.0,
        "ev_ebitda": 30.0,
        "ebitda_mm": 21.33,
        "revenue_mm": 76.54,
        "ebitda_margin": 0.2787,
        "hold_years": 2.5,
        "moic": 2.2,
        "irr": 0.3708,
        "payer_mix": {"commercial": 0.77, "medicare": 0.11, "medicaid": 0.08, "self_pay": 0.04},
        "comm_pct": 0.77,
        "region": "National",
        "buyer": "Vista Equity Partners",
        "status": "Active",
    },
    {
        "company_name": "ClearChart Specialty EMR",
        "sector": "EHR/EMR",
        "subsector": "Specialty Practice EMR",
        "year": 2015,
        "ev_mm": 78.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 6.0,
        "revenue_mm": 40.0,
        "ebitda_margin": 0.15,
        "hold_years": 6.0,
        "moic": 3.0,
        "irr": 0.2009,
        "payer_mix": {"commercial": 0.65, "medicare": 0.20, "medicaid": 0.11, "self_pay": 0.04},
        "comm_pct": 0.65,
        "region": "Midwest",
        "buyer": "Bain Capital",
        "status": "Realized",
    },
    {
        "company_name": "Synapse Care Navigation",
        "sector": "Patient Engagement",
        "subsector": "Chronic Disease Management",
        "year": 2023,
        "ev_mm": 185.0,
        "ev_ebitda": 25.0,
        "ebitda_mm": 7.4,
        "revenue_mm": 37.0,
        "ebitda_margin": 0.20,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.60, "medicare": 0.22, "medicaid": 0.14, "self_pay": 0.04},
        "comm_pct": 0.60,
        "region": "Northeast",
        "buyer": "Warburg Pincus",
        "status": "Active",
    },
    {
        "company_name": "OmniConnect HIE Services",
        "sector": "Interoperability",
        "subsector": "Statewide Health Information Exchange",
        "year": 2016,
        "ev_mm": 55.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 4.4,
        "revenue_mm": 22.0,
        "ebitda_margin": 0.20,
        "hold_years": 5.5,
        "moic": 2.5,
        "irr": 0.1813,
        "payer_mix": {"commercial": 0.55, "medicare": 0.25, "medicaid": 0.16, "self_pay": 0.04},
        "comm_pct": 0.55,
        "region": "Southeast",
        "buyer": "ABRY Partners",
        "status": "Realized",
    },
    {
        "company_name": "Beacon Telehealth Infrastructure",
        "sector": "Telehealth",
        "subsector": "Rural and Critical Access Telehealth",
        "year": 2020,
        "ev_mm": 320.0,
        "ev_ebitda": 20.0,
        "ebitda_mm": 16.0,
        "revenue_mm": 88.89,
        "ebitda_margin": 0.18,
        "hold_years": 4.0,
        "moic": 3.6,
        "irr": 0.3774,
        "payer_mix": {"commercial": 0.50, "medicare": 0.30, "medicaid": 0.16, "self_pay": 0.04},
        "comm_pct": 0.50,
        "region": "Midwest",
        "buyer": "General Atlantic",
        "status": "Active",
    },
    {
        "company_name": "AlphaCDS Oncology Analytics",
        "sector": "Clinical Decision Support",
        "subsector": "Oncology Treatment Pathways",
        "year": 2018,
        "ev_mm": 480.0,
        "ev_ebitda": 34.0,
        "ebitda_mm": 14.12,
        "revenue_mm": 47.07,
        "ebitda_margin": 0.30,
        "hold_years": 4.5,
        "moic": 3.8,
        "irr": 0.3454,
        "payer_mix": {"commercial": 0.78, "medicare": 0.14, "medicaid": 0.06, "self_pay": 0.02},
        "comm_pct": 0.78,
        "region": "West",
        "buyer": "Francisco Partners",
        "status": "Realized",
    },
    {
        "company_name": "TrueRecord Hospital EHR",
        "sector": "EHR/EMR",
        "subsector": "Acute Care EHR",
        "year": 2019,
        "ev_mm": 800.0,
        "ev_ebitda": 27.0,
        "ebitda_mm": 29.63,
        "revenue_mm": 98.77,
        "ebitda_margin": 0.30,
        "hold_years": 5.0,
        "moic": 3.3,
        "irr": 0.2695,
        "payer_mix": {"commercial": 0.62, "medicare": 0.22, "medicaid": 0.13, "self_pay": 0.03},
        "comm_pct": 0.62,
        "region": "National",
        "buyer": "Thoma Bravo",
        "status": "Partially Realized",
    },
    {
        "company_name": "Mosaic Health IT Consulting",
        "sector": "Healthcare IT",
        "subsector": "EHR Implementation and Optimization",
        "year": 2021,
        "ev_mm": 120.0,
        "ev_ebitda": 15.0,
        "ebitda_mm": 8.0,
        "revenue_mm": 44.44,
        "ebitda_margin": 0.18,
        "hold_years": 3.5,
        "moic": 2.4,
        "irr": 0.2842,
        "payer_mix": {"commercial": 0.74, "medicare": 0.13, "medicaid": 0.09, "self_pay": 0.04},
        "comm_pct": 0.74,
        "region": "Southeast",
        "buyer": "GTCR",
        "status": "Active",
    },
    {
        "company_name": "PulseEngage Remote Monitoring",
        "sector": "Patient Engagement",
        "subsector": "Remote Patient Monitoring",
        "year": 2022,
        "ev_mm": 255.0,
        "ev_ebitda": 21.25,
        "ebitda_mm": 12.0,
        "revenue_mm": 60.0,
        "ebitda_margin": 0.20,
        "hold_years": 2.5,
        "moic": 1.9,
        "irr": 0.2927,
        "payer_mix": {"commercial": 0.58, "medicare": 0.28, "medicaid": 0.11, "self_pay": 0.03},
        "comm_pct": 0.58,
        "region": "West",
        "buyer": "Vista Equity Partners",
        "status": "Active",
    },
]
