"""Extended seed batch 51 — pediatric specialty PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_51: list[dict] = [
    {
        "source_id": "ext51_001",
        "company_name": "Brightpath Pediatric Health System",
        "sector": "Pediatric Hospital System",
        "year": 2018,
        "ev_mm": 620.0,
        "ev_ebitda": 12.4,
        "moic": 3.1,
        "irr": 0.27,
        "hold_years": 5.0,
        "sponsor": "KKR",
        "payer_mix": {"commercial": 0.32, "medicare": 0.04, "medicaid": 0.58, "self_pay": 0.06},
        "geography": "Texas",
        "ebitda_margin": 0.14,
        "revenue_mm": 357.14,
    },
    {
        "source_id": "ext51_002",
        "company_name": "Maplewood Children's Specialty Center",
        "sector": "Children's Specialty Hospital",
        "year": 2016,
        "ev_mm": 430.0,
        "ev_ebitda": 11.0,
        "moic": 3.4,
        "irr": 0.29,
        "hold_years": 4.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.38, "medicare": 0.03, "medicaid": 0.52, "self_pay": 0.07},
        "geography": "Ohio",
        "ebitda_margin": 0.17,
        "revenue_mm": 229.95,
    },
    {
        "source_id": "ext51_003",
        "company_name": "NovaNatal Critical Care Partners",
        "sector": "Neonatal Intensive Care",
        "year": 2019,
        "ev_mm": 310.0,
        "ev_ebitda": 10.5,
        "moic": 2.8,
        "irr": 0.25,
        "hold_years": 4.0,
        "sponsor": "Welsh Carson Anderson & Stowe",
        "payer_mix": {"commercial": 0.29, "medicare": 0.02, "medicaid": 0.62, "self_pay": 0.07},
        "geography": "Georgia",
        "ebitda_margin": 0.13,
        "revenue_mm": 227.25,
    },
    {
        "source_id": "ext51_004",
        "company_name": "SwiftCare Pediatric Emergency Group",
        "sector": "Pediatric Emergency Medicine",
        "year": 2017,
        "ev_mm": 195.0,
        "ev_ebitda": 9.8,
        "moic": 3.7,
        "irr": 0.33,
        "hold_years": 4.0,
        "sponsor": "Summit Partners",
        "payer_mix": {"commercial": 0.35, "medicare": 0.03, "medicaid": 0.48, "self_pay": 0.14},
        "geography": "Florida",
        "ebitda_margin": 0.16,
        "revenue_mm": 124.49,
    },
    {
        "source_id": "ext51_005",
        "company_name": "Apex Pediatric Critical Care Associates",
        "sector": "Pediatric Critical Care",
        "year": 2020,
        "ev_mm": 260.0,
        "ev_ebitda": 11.5,
        "moic": 2.6,
        "irr": 0.22,
        "hold_years": 5.5,
        "sponsor": "Bain Capital",
        "payer_mix": {"commercial": 0.30, "medicare": 0.03, "medicaid": 0.58, "self_pay": 0.09},
        "geography": "Pennsylvania",
        "ebitda_margin": 0.15,
        "revenue_mm": 150.43,
    },
    {
        "source_id": "ext51_006",
        "company_name": "Clearfield Pediatric Surgery Partners",
        "sector": "Pediatric Surgery Group",
        "year": 2015,
        "ev_mm": 155.0,
        "ev_ebitda": 9.5,
        "moic": 4.0,
        "irr": 0.34,
        "hold_years": 4.5,
        "sponsor": "Blackstone",
        "payer_mix": {"commercial": 0.44, "medicare": 0.04, "medicaid": 0.44, "self_pay": 0.08},
        "geography": "Illinois",
        "ebitda_margin": 0.22,
        "revenue_mm": 74.28,
    },
    {
        "source_id": "ext51_007",
        "company_name": "Synapse Pediatric Neurology Network",
        "sector": "Pediatric Neurology",
        "year": 2018,
        "ev_mm": 180.0,
        "ev_ebitda": 10.0,
        "moic": 3.2,
        "irr": 0.28,
        "hold_years": 4.5,
        "sponsor": "Francisco Partners",
        "payer_mix": {"commercial": 0.40, "medicare": 0.05, "medicaid": 0.46, "self_pay": 0.09},
        "geography": "Massachusetts",
        "ebitda_margin": 0.20,
        "revenue_mm": 90.00,
    },
    {
        "source_id": "ext51_008",
        "company_name": "Horizon Pediatric Oncology Centers",
        "sector": "Pediatric Oncology",
        "year": 2021,
        "ev_mm": 490.0,
        "ev_ebitda": 13.5,
        "moic": 2.5,
        "irr": 0.21,
        "hold_years": 6.0,
        "sponsor": "TPG Capital",
        "payer_mix": {"commercial": 0.36, "medicare": 0.04, "medicaid": 0.50, "self_pay": 0.10},
        "geography": "California",
        "ebitda_margin": 0.16,
        "revenue_mm": 227.16,
    },
    {
        "source_id": "ext51_009",
        "company_name": "Heartfirst Pediatric Cardiology Group",
        "sector": "Pediatric Cardiology",
        "year": 2014,
        "ev_mm": 220.0,
        "ev_ebitda": 11.0,
        "moic": 4.2,
        "irr": 0.36,
        "hold_years": 3.5,
        "sponsor": "General Atlantic",
        "payer_mix": {"commercial": 0.42, "medicare": 0.04, "medicaid": 0.45, "self_pay": 0.09},
        "geography": "New York",
        "ebitda_margin": 0.24,
        "revenue_mm": 83.33,
    },
    {
        "source_id": "ext51_010",
        "company_name": "GutHealth Pediatric Gastroenterology Associates",
        "sector": "Pediatric Gastroenterology",
        "year": 2016,
        "ev_mm": 130.0,
        "ev_ebitda": 9.0,
        "moic": 3.5,
        "irr": 0.31,
        "hold_years": 4.0,
        "sponsor": "New Mountain Capital",
        "payer_mix": {"commercial": 0.38, "medicare": 0.03, "medicaid": 0.48, "self_pay": 0.11},
        "geography": "North Carolina",
        "ebitda_margin": 0.19,
        "revenue_mm": 76.02,
    },
    {
        "source_id": "ext51_011",
        "company_name": "AirCare Pediatric Pulmonology Partners",
        "sector": "Pediatric Pulmonology",
        "year": 2019,
        "ev_mm": 115.0,
        "ev_ebitda": 8.5,
        "moic": 3.0,
        "irr": 0.26,
        "hold_years": 5.0,
        "sponsor": "Varsity Healthcare Partners",
        "payer_mix": {"commercial": 0.35, "medicare": 0.03, "medicaid": 0.52, "self_pay": 0.10},
        "geography": "Tennessee",
        "ebitda_margin": 0.18,
        "revenue_mm": 75.16,
    },
    {
        "source_id": "ext51_012",
        "company_name": "Equilibrium Pediatric Endocrinology Group",
        "sector": "Pediatric Endocrinology",
        "year": 2020,
        "ev_mm": 95.0,
        "ev_ebitda": 8.0,
        "moic": 2.9,
        "irr": 0.24,
        "hold_years": 5.5,
        "sponsor": "Ridgemont Equity Partners",
        "payer_mix": {"commercial": 0.37, "medicare": 0.03, "medicaid": 0.50, "self_pay": 0.10},
        "geography": "Minnesota",
        "ebitda_margin": 0.21,
        "revenue_mm": 56.55,
    },
    {
        "source_id": "ext51_013",
        "company_name": "RenalCare Pediatric Nephrology Network",
        "sector": "Pediatric Nephrology",
        "year": 2017,
        "ev_mm": 145.0,
        "ev_ebitda": 10.2,
        "moic": 3.3,
        "irr": 0.29,
        "hold_years": 4.5,
        "sponsor": "Frazier Healthcare Partners",
        "payer_mix": {"commercial": 0.33, "medicare": 0.04, "medicaid": 0.54, "self_pay": 0.09},
        "geography": "Washington",
        "ebitda_margin": 0.17,
        "revenue_mm": 83.65,
    },
    {
        "source_id": "ext51_014",
        "company_name": "Mobiliti Pediatric Rheumatology Associates",
        "sector": "Pediatric Rheumatology",
        "year": 2013,
        "ev_mm": 80.0,
        "ev_ebitda": 8.8,
        "moic": 3.8,
        "irr": 0.32,
        "hold_years": 4.0,
        "sponsor": "Great Hill Partners",
        "payer_mix": {"commercial": 0.41, "medicare": 0.03, "medicaid": 0.46, "self_pay": 0.10},
        "geography": "Colorado",
        "ebitda_margin": 0.23,
        "revenue_mm": 39.56,
    },
    {
        "source_id": "ext51_015",
        "company_name": "ShieldMD Pediatric Infectious Disease Partners",
        "sector": "Pediatric Infectious Disease",
        "year": 2022,
        "ev_mm": 165.0,
        "ev_ebitda": 11.8,
        "moic": 2.4,
        "irr": 0.20,
        "hold_years": 6.5,
        "sponsor": "Health Enterprise Partners",
        "payer_mix": {"commercial": 0.31, "medicare": 0.04, "medicaid": 0.55, "self_pay": 0.10},
        "geography": "Michigan",
        "ebitda_margin": 0.12,
        "revenue_mm": 116.53,
    },
]
