"""Extended seed batch 56 — healthcare staffing and services PE deals."""
from __future__ import annotations

EXTENDED_SEED_DEALS_56: list[dict] = [
    {
        "source_id": "ext56_001",
        "company_name": "Apex Medical Staffing Group",
        "sector": "medical staffing agency",
        "year": 2016,
        "ev_mm": 185.0,
        "ev_ebitda": 10.5,
        "moic": 3.4,
        "irr": 0.27,
        "hold_years": 4.5,
        "sponsor": "Gridiron Capital",
        "payer_mix": {"commercial": 0.78, "medicare": 0.10, "medicaid": 0.07, "self_pay": 0.05},
        "geography": "Southeast",
        "ebitda_margin": 0.17,
        "revenue_mm": 108.8,
    },
    {
        "source_id": "ext56_002",
        "company_name": "NovaTrav Nursing Solutions",
        "sector": "travel nurse platform",
        "year": 2019,
        "ev_mm": 320.0,
        "ev_ebitda": 12.0,
        "moic": 3.8,
        "irr": 0.31,
        "hold_years": 4.0,
        "sponsor": "ABRY Partners",
        "payer_mix": {"commercial": 0.80, "medicare": 0.08, "medicaid": 0.07, "self_pay": 0.05},
        "geography": "National",
        "ebitda_margin": 0.19,
        "revenue_mm": 140.4,
    },
    {
        "source_id": "ext56_003",
        "company_name": "Meridian Locum Partners",
        "sector": "locum tenens company",
        "year": 2015,
        "ev_mm": 145.0,
        "ev_ebitda": 9.5,
        "moic": 3.1,
        "irr": 0.25,
        "hold_years": 5.0,
        "sponsor": "Audax Private Equity",
        "payer_mix": {"commercial": 0.75, "medicare": 0.12, "medicaid": 0.08, "self_pay": 0.05},
        "geography": "Midwest",
        "ebitda_margin": 0.15,
        "revenue_mm": 101.8,
    },
    {
        "source_id": "ext56_004",
        "company_name": "PrimeAllied Health Staffing",
        "sector": "allied health staffing",
        "year": 2017,
        "ev_mm": 95.0,
        "ev_ebitda": 8.5,
        "moic": 2.9,
        "irr": 0.24,
        "hold_years": 4.5,
        "sponsor": "Kelso & Company",
        "payer_mix": {"commercial": 0.77, "medicare": 0.11, "medicaid": 0.07, "self_pay": 0.05},
        "geography": "Southwest",
        "ebitda_margin": 0.14,
        "revenue_mm": 79.2,
    },
    {
        "source_id": "ext56_005",
        "company_name": "Vantage Healthcare Recruiting",
        "sector": "healthcare recruiting firm",
        "year": 2018,
        "ev_mm": 75.0,
        "ev_ebitda": 9.0,
        "moic": 3.2,
        "irr": 0.28,
        "hold_years": 4.0,
        "sponsor": "GTCR",
        "payer_mix": {"commercial": 0.82, "medicare": 0.08, "medicaid": 0.06, "self_pay": 0.04},
        "geography": "Northeast",
        "ebitda_margin": 0.18,
        "revenue_mm": 46.7,
    },
    {
        "source_id": "ext56_006",
        "company_name": "Summit Physician Practice Management",
        "sector": "physician practice management company",
        "year": 2016,
        "ev_mm": 260.0,
        "ev_ebitda": 11.5,
        "moic": 3.6,
        "irr": 0.29,
        "hold_years": 4.5,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.74, "medicare": 0.13, "medicaid": 0.08, "self_pay": 0.05},
        "geography": "National",
        "ebitda_margin": 0.20,
        "revenue_mm": 113.0,
    },
    {
        "source_id": "ext56_007",
        "company_name": "ClearClaim Medical Billing",
        "sector": "medical billing company",
        "year": 2014,
        "ev_mm": 55.0,
        "ev_ebitda": 8.0,
        "moic": 2.8,
        "irr": 0.22,
        "hold_years": 5.5,
        "sponsor": "Audax Private Equity",
        "payer_mix": {"commercial": 0.79, "medicare": 0.10, "medicaid": 0.07, "self_pay": 0.04},
        "geography": "Southeast",
        "ebitda_margin": 0.22,
        "revenue_mm": 30.9,
    },
    {
        "source_id": "ext56_008",
        "company_name": "Pinnacle Healthcare Outsourcing",
        "sector": "healthcare outsourcing company",
        "year": 2020,
        "ev_mm": 380.0,
        "ev_ebitda": 13.5,
        "moic": 4.2,
        "irr": 0.35,
        "hold_years": 3.5,
        "sponsor": "KKR",
        "payer_mix": {"commercial": 0.83, "medicare": 0.08, "medicaid": 0.05, "self_pay": 0.04},
        "geography": "National",
        "ebitda_margin": 0.23,
        "revenue_mm": 122.7,
    },
    {
        "source_id": "ext56_009",
        "company_name": "Horizon Health Consulting Group",
        "sector": "healthcare consulting firm",
        "year": 2017,
        "ev_mm": 120.0,
        "ev_ebitda": 10.0,
        "moic": 3.3,
        "irr": 0.26,
        "hold_years": 4.5,
        "sponsor": "Gridiron Capital",
        "payer_mix": {"commercial": 0.81, "medicare": 0.09, "medicaid": 0.06, "self_pay": 0.04},
        "geography": "Mid-Atlantic",
        "ebitda_margin": 0.21,
        "revenue_mm": 57.1,
    },
    {
        "source_id": "ext56_010",
        "company_name": "Cornerstone Health Executive Search",
        "sector": "healthcare executive search",
        "year": 2018,
        "ev_mm": 42.0,
        "ev_ebitda": 7.5,
        "moic": 2.7,
        "irr": 0.21,
        "hold_years": 5.0,
        "sponsor": "Kelso & Company",
        "payer_mix": {"commercial": 0.84, "medicare": 0.07, "medicaid": 0.05, "self_pay": 0.04},
        "geography": "National",
        "ebitda_margin": 0.24,
        "revenue_mm": 23.3,
    },
    {
        "source_id": "ext56_011",
        "company_name": "TrustCred Credentialing Services",
        "sector": "credentialing services company",
        "year": 2019,
        "ev_mm": 88.0,
        "ev_ebitda": 9.8,
        "moic": 3.0,
        "irr": 0.25,
        "hold_years": 4.0,
        "sponsor": "ABRY Partners",
        "payer_mix": {"commercial": 0.80, "medicare": 0.09, "medicaid": 0.07, "self_pay": 0.04},
        "geography": "Midwest",
        "ebitda_margin": 0.19,
        "revenue_mm": 53.7,
    },
    {
        "source_id": "ext56_012",
        "company_name": "AccuCode Medical Coding",
        "sector": "medical coding company",
        "year": 2015,
        "ev_mm": 62.0,
        "ev_ebitda": 8.8,
        "moic": 2.6,
        "irr": 0.20,
        "hold_years": 5.5,
        "sponsor": "Audax Private Equity",
        "payer_mix": {"commercial": 0.78, "medicare": 0.11, "medicaid": 0.07, "self_pay": 0.04},
        "geography": "South Central",
        "ebitda_margin": 0.20,
        "revenue_mm": 35.2,
    },
    {
        "source_id": "ext56_013",
        "company_name": "SwiftAuth Prior Authorization Services",
        "sector": "prior authorization services",
        "year": 2021,
        "ev_mm": 155.0,
        "ev_ebitda": 11.0,
        "moic": 4.0,
        "irr": 0.34,
        "hold_years": 3.0,
        "sponsor": "GTCR",
        "payer_mix": {"commercial": 0.76, "medicare": 0.12, "medicaid": 0.07, "self_pay": 0.05},
        "geography": "National",
        "ebitda_margin": 0.22,
        "revenue_mm": 64.6,
    },
    {
        "source_id": "ext56_014",
        "company_name": "ClearCheck Insurance Verification",
        "sector": "insurance verification services",
        "year": 2022,
        "ev_mm": 110.0,
        "ev_ebitda": 10.2,
        "moic": 4.4,
        "irr": 0.37,
        "hold_years": 3.0,
        "sponsor": "Warburg Pincus",
        "payer_mix": {"commercial": 0.85, "medicare": 0.07, "medicaid": 0.05, "self_pay": 0.03},
        "geography": "West",
        "ebitda_margin": 0.25,
        "revenue_mm": 43.1,
    },
    {
        "source_id": "ext56_015",
        "company_name": "CareLine Healthcare Call Center",
        "sector": "healthcare call center",
        "year": 2020,
        "ev_mm": 198.0,
        "ev_ebitda": 12.5,
        "moic": 3.7,
        "irr": 0.30,
        "hold_years": 4.0,
        "sponsor": "ABRY Partners",
        "payer_mix": {"commercial": 0.79, "medicare": 0.10, "medicaid": 0.07, "self_pay": 0.04},
        "geography": "National",
        "ebitda_margin": 0.18,
        "revenue_mm": 85.3,
    },
]
