"""Extended seed deals batch 63.

Theme: Oncology — community oncology physician networks, radiation
oncology centers, oncology-focused practice management / MSO platforms,
CAR-T and cellular therapy centers, and oncology biotech services.
Fifteen synthetic healthcare PE transactions representing realistic
deal economics across vintages 2016-2024 in the oncology services
space.
"""

EXTENDED_SEED_DEALS_63 = [
    {
        "company_name": "Cedarline Community Oncology Partners",
        "sector": "Community Oncology",
        "subsector": "Multi-Site Community Oncology Physician Network",
        "year": 2018,
        "ev_mm": 520.0,
        "ev_ebitda": 13.0,
        "ebitda_mm": 40.0,
        "revenue_mm": 181.82,
        "ebitda_margin": 0.22,
        "hold_years": 5.0,
        "moic": 2.7,
        "irr": 0.2198,
        "payer_mix": {"commercial": 0.46, "medicare": 0.44, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.46,
        "region": "Southeast",
        "buyer": "Nautic Partners",
        "status": "Realized",
    },
    {
        "company_name": "Northbeam Radiation Oncology",
        "sector": "Radiation Oncology",
        "subsector": "Freestanding Radiation Therapy Centers",
        "year": 2019,
        "ev_mm": 780.0,
        "ev_ebitda": 15.5,
        "ebitda_mm": 50.32,
        "revenue_mm": 209.67,
        "ebitda_margin": 0.24,
        "hold_years": 5.5,
        "moic": 3.1,
        "irr": 0.2284,
        "payer_mix": {"commercial": 0.38, "medicare": 0.52, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.38,
        "region": "Northeast",
        "buyer": "Bain Capital",
        "status": "Partially Realized",
    },
    {
        "company_name": "Apex Oncology Practice Holdings",
        "sector": "Oncology Services",
        "subsector": "Oncology-Focused Practice Management MSO",
        "year": 2020,
        "ev_mm": 640.0,
        "ev_ebitda": 14.0,
        "ebitda_mm": 45.71,
        "revenue_mm": 190.46,
        "ebitda_margin": 0.24,
        "hold_years": 4.5,
        "moic": 2.6,
        "irr": 0.2366,
        "payer_mix": {"commercial": 0.48, "medicare": 0.42, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.48,
        "region": "National",
        "buyer": "TPG",
        "status": "Active",
    },
    {
        "company_name": "Helix Cellular Therapy Centers",
        "sector": "Cellular Therapy",
        "subsector": "CAR-T Infusion & Apheresis Centers",
        "year": 2022,
        "ev_mm": 1100.0,
        "ev_ebitda": 18.5,
        "ebitda_mm": 59.46,
        "revenue_mm": 228.69,
        "ebitda_margin": 0.26,
        "hold_years": 4.0,
        "moic": 2.5,
        "irr": 0.2574,
        "payer_mix": {"commercial": 0.58, "medicare": 0.34, "medicaid": 0.06, "self_pay": 0.02},
        "comm_pct": 0.58,
        "region": "National",
        "buyer": "Blackstone",
        "status": "Active",
    },
    {
        "company_name": "Summit Radiation & Proton Institute",
        "sector": "Radiation Oncology",
        "subsector": "Proton & Advanced Radiation Therapy",
        "year": 2017,
        "ev_mm": 910.0,
        "ev_ebitda": 16.0,
        "ebitda_mm": 56.88,
        "revenue_mm": 225.71,
        "ebitda_margin": 0.252,
        "hold_years": 6.0,
        "moic": 3.4,
        "irr": 0.2263,
        "payer_mix": {"commercial": 0.36, "medicare": 0.55, "medicaid": 0.06, "self_pay": 0.03},
        "comm_pct": 0.36,
        "region": "West",
        "buyer": "KKR",
        "status": "Realized",
    },
    {
        "company_name": "Willowbrook Oncology Associates",
        "sector": "Community Oncology",
        "subsector": "Regional Medical Oncology Practice",
        "year": 2016,
        "ev_mm": 230.0,
        "ev_ebitda": 11.5,
        "ebitda_mm": 20.0,
        "revenue_mm": 117.65,
        "ebitda_margin": 0.17,
        "hold_years": 5.0,
        "moic": 2.2,
        "irr": 0.1708,
        "payer_mix": {"commercial": 0.42, "medicare": 0.45, "medicaid": 0.10, "self_pay": 0.03},
        "comm_pct": 0.42,
        "region": "Midwest",
        "buyer": "Altaris Capital",
        "status": "Realized",
    },
    {
        "company_name": "Beacon Oncology Biotech Services",
        "sector": "Oncology Services",
        "subsector": "Oncology CRO & Biotech Clinical Services",
        "year": 2021,
        "ev_mm": 840.0,
        "ev_ebitda": 17.0,
        "ebitda_mm": 49.41,
        "revenue_mm": 176.46,
        "ebitda_margin": 0.28,
        "hold_years": 4.0,
        "moic": 2.8,
        "irr": 0.2936,
        "payer_mix": {"commercial": 0.64, "medicare": 0.28, "medicaid": 0.05, "self_pay": 0.03},
        "comm_pct": 0.64,
        "region": "Northeast",
        "buyer": "CVC Capital",
        "status": "Active",
    },
    {
        "company_name": "Cascade Community Oncology Network",
        "sector": "Community Oncology",
        "subsector": "Community Oncology Roll-Up Platform",
        "year": 2019,
        "ev_mm": 390.0,
        "ev_ebitda": 12.5,
        "ebitda_mm": 31.2,
        "revenue_mm": 156.0,
        "ebitda_margin": 0.20,
        "hold_years": 5.0,
        "moic": 2.5,
        "irr": 0.2011,
        "payer_mix": {"commercial": 0.44, "medicare": 0.43, "medicaid": 0.10, "self_pay": 0.03},
        "comm_pct": 0.44,
        "region": "West",
        "buyer": "Ares",
        "status": "Partially Realized",
    },
    {
        "company_name": "Ironwood Radiation Therapy Partners",
        "sector": "Radiation Oncology",
        "subsector": "Linear Accelerator & IMRT Center Network",
        "year": 2020,
        "ev_mm": 460.0,
        "ev_ebitda": 13.5,
        "ebitda_mm": 34.07,
        "revenue_mm": 162.24,
        "ebitda_margin": 0.21,
        "hold_years": 4.5,
        "moic": 2.3,
        "irr": 0.2033,
        "payer_mix": {"commercial": 0.40, "medicare": 0.50, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.40,
        "region": "Southeast",
        "buyer": "Bridgepoint",
        "status": "Active",
    },
    {
        "company_name": "Vanguard Cellular Therapy Holdings",
        "sector": "Cellular Therapy",
        "subsector": "CAR-T Manufacturing Support & Site Services",
        "year": 2023,
        "ev_mm": 1350.0,
        "ev_ebitda": 19.5,
        "ebitda_mm": 69.23,
        "revenue_mm": 265.25,
        "ebitda_margin": 0.261,
        "hold_years": 3.0,
        "moic": 1.7,
        "irr": 0.1935,
        "payer_mix": {"commercial": 0.60, "medicare": 0.33, "medicaid": 0.05, "self_pay": 0.02},
        "comm_pct": 0.60,
        "region": "National",
        "buyer": "Apollo",
        "status": "Active",
    },
    {
        "company_name": "Meridian Medical Oncology Group",
        "sector": "Community Oncology",
        "subsector": "Integrated Oncology & Infusion Practice",
        "year": 2018,
        "ev_mm": 310.0,
        "ev_ebitda": 12.0,
        "ebitda_mm": 25.83,
        "revenue_mm": 134.53,
        "ebitda_margin": 0.192,
        "hold_years": 6.0,
        "moic": 2.9,
        "irr": 0.1942,
        "payer_mix": {"commercial": 0.43, "medicare": 0.45, "medicaid": 0.09, "self_pay": 0.03},
        "comm_pct": 0.43,
        "region": "Midwest",
        "buyer": "Nautic Partners",
        "status": "Realized",
    },
    {
        "company_name": "Harborlight Oncology Services",
        "sector": "Oncology Services",
        "subsector": "Oncology Specialty Pharmacy & Support Services",
        "year": 2021,
        "ev_mm": 580.0,
        "ev_ebitda": 14.5,
        "ebitda_mm": 40.0,
        "revenue_mm": 173.91,
        "ebitda_margin": 0.23,
        "hold_years": 3.5,
        "moic": 1.9,
        "irr": 0.2013,
        "payer_mix": {"commercial": 0.52, "medicare": 0.38, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.52,
        "region": "Northeast",
        "buyer": "Ares",
        "status": "Active",
    },
    {
        "company_name": "Lantern Oncology Diagnostics",
        "sector": "Oncology Services",
        "subsector": "Molecular Diagnostics & Companion Testing",
        "year": 2022,
        "ev_mm": 710.0,
        "ev_ebitda": 16.5,
        "ebitda_mm": 43.03,
        "revenue_mm": 172.12,
        "ebitda_margin": 0.25,
        "hold_years": 4.0,
        "moic": 2.4,
        "irr": 0.2447,
        "payer_mix": {"commercial": 0.55, "medicare": 0.36, "medicaid": 0.06, "self_pay": 0.03},
        "comm_pct": 0.55,
        "region": "National",
        "buyer": "CVC Capital",
        "status": "Active",
    },
    {
        "company_name": "Pinecrest Radiation Oncology Group",
        "sector": "Radiation Oncology",
        "subsector": "Community Radiation Oncology Practice",
        "year": 2016,
        "ev_mm": 175.0,
        "ev_ebitda": 11.0,
        "ebitda_mm": 15.91,
        "revenue_mm": 99.44,
        "ebitda_margin": 0.16,
        "hold_years": 6.5,
        "moic": 3.6,
        "irr": 0.2178,
        "payer_mix": {"commercial": 0.34, "medicare": 0.56, "medicaid": 0.07, "self_pay": 0.03},
        "comm_pct": 0.34,
        "region": "Southeast",
        "buyer": "Altaris Capital",
        "status": "Realized",
    },
    {
        "company_name": "Evergreen CAR-T Center Holdings",
        "sector": "Cellular Therapy",
        "subsector": "Outpatient Cellular Therapy & Stem Cell Centers",
        "year": 2024,
        "ev_mm": 970.0,
        "ev_ebitda": 18.0,
        "ebitda_mm": 53.89,
        "revenue_mm": 224.54,
        "ebitda_margin": 0.24,
        "hold_years": 3.0,
        "moic": 1.5,
        "irr": 0.1447,
        "payer_mix": {"commercial": 0.56, "medicare": 0.36, "medicaid": 0.06, "self_pay": 0.02},
        "comm_pct": 0.56,
        "region": "West",
        "buyer": "Blackstone",
        "status": "Active",
    },
]
