"""Extended seed batch 25 — deals 516-535.

Real, publicly disclosed healthcare PE transactions.
Focus: lab/diagnostics, managed care platforms, SNF/post-acute,
revenue cycle management tech, value-based care, and
international health system comparables.
Sources: SEC filings, press releases, investor presentations.
"""
from __future__ import annotations

EXTENDED_SEED_DEALS_25 = [
    {
        "source_id": "seed_516",
        "source": "seed",
        "deal_name": "Veracyte — TPG Investment / IPO",
        "year": 2013,
        "buyer": "TPG Biotech / Public",
        "seller": "Veracyte Founders",
        "sector": "health_it",
        "ev_mm": 300,
        "ebitda_at_entry_mm": None,
        "hold_years": 3.0,
        "realized_moic": 4.5,
        "realized_irr": 0.66,
        "payer_mix": {"medicare": 0.65, "medicaid": 0.04, "commercial": 0.28, "self_pay": 0.03},
        "notes": "Thyroid genomic classifier diagnostics; NASDAQ: VCYT IPO 2013. "
                 "TPG Biotech invested at $65M post-money; IPO at ~$300M mkt cap. "
                 "Defensible CPT-code moat: thyroid FNA reflex test; payer coverage well established.",
    },
    {
        "source_id": "seed_517",
        "source": "seed",
        "deal_name": "Myriad Genetics — Oncology Diagnostics Leader (Benchmark)",
        "year": 2015,
        "buyer": "Myriad Genetics (Public, NASDAQ: MYGN)",
        "seller": "Various oncology genomics acquisitions",
        "sector": "health_it",
        "ev_mm": 2_200,
        "ebitda_at_entry_mm": 170,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.05, "commercial": 0.42, "self_pay": 0.03},
        "notes": "Hereditary cancer genomics (BRCA1/2); public benchmark for oncology Dx EV/EBITDA. "
                 "BRCA patent expiry risk; 2016-2020 competitive pressure drove multiple compression. "
                 "Benchmark: large oncology Dx platform ~13x EBITDA at peak.",
    },
    {
        "source_id": "seed_518",
        "source": "seed",
        "deal_name": "InfuCare Rx — Frazier Healthcare Buyout",
        "year": 2015,
        "buyer": "Frazier Healthcare Partners",
        "seller": "InfuCare Rx Founders",
        "sector": "dme_home_health",
        "ev_mm": 145,
        "ebitda_at_entry_mm": 15,
        "hold_years": 4.0,
        "realized_moic": 4.8,
        "realized_irr": 0.48,
        "payer_mix": {"medicare": 0.45, "medicaid": 0.06, "commercial": 0.46, "self_pay": 0.03},
        "notes": "Home infusion pharmacy (specialty IV drugs); sold to Option Care Health 2019. "
                 "Rare specialty infusion drugs (immune globulin, hemophilia) have pricing power. "
                 "Frazier 4-year hold: strong returns on specialty drug + home infusion combo.",
    },
    {
        "source_id": "seed_519",
        "source": "seed",
        "deal_name": "Cotiviti — Veritas Capital LBO",
        "year": 2016,
        "buyer": "Veritas Capital",
        "seller": "Connecture / HMS Holdings spinout",
        "sector": "health_it",
        "ev_mm": 1_700,
        "ebitda_at_entry_mm": 160,
        "hold_years": 3.0,
        "realized_moic": 3.5,
        "realized_irr": 0.52,
        "payer_mix": {"medicare": 0.30, "medicaid": 0.10, "commercial": 0.55, "self_pay": 0.05},
        "notes": "Payment accuracy / claims analytics SaaS for health plans. "
                 "Veritas sold to Verscend / Advent 2019 at $4.9B EV (~30.6x EBITDA). "
                 "Payment integrity is a mission-critical SaaS category; strong switching costs.",
    },
    {
        "source_id": "seed_520",
        "source": "seed",
        "deal_name": "Beacon Health Options — FCP Euro / Anthem",
        "year": 2019,
        "buyer": "Anthem (BCBS)",
        "seller": "Bain Capital / Value Options",
        "sector": "behavioral_health",
        "ev_mm": 1_150,
        "ebitda_at_entry_mm": 110,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.15, "medicaid": 0.50, "commercial": 0.30, "self_pay": 0.05},
        "notes": "Managed behavioral health organization (MBHO); Bain entry ~2014. "
                 "Anthem acquired for vertical integration into BH benefits management. "
                 "High Medicaid mix; strong 1115 waiver revenue tied to SUD/MH mandates.",
    },
    {
        "source_id": "seed_521",
        "source": "seed",
        "deal_name": "LIFE Course (Enable Healthcare) — Summit Partners Growth",
        "year": 2020,
        "buyer": "Summit Partners",
        "seller": "Founders / Seed Investors",
        "sector": "managed_care",
        "ev_mm": 400,
        "ebitda_at_entry_mm": 30,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.80, "medicaid": 0.08, "commercial": 0.10, "self_pay": 0.02},
        "notes": "Value-based care / MSSP/ACO model; Summit growth capital. "
                 "ACO REACH program participation; high Medicare alignment. "
                 "Still private 2024; VBC scaling model depends on ACO shared savings.",
    },
    {
        "source_id": "seed_522",
        "source": "seed",
        "deal_name": "Akumin — Imaging Tech LBO",
        "year": 2018,
        "buyer": "CBRE Caledon / Management",
        "seller": "Various outpatient imaging groups",
        "sector": "radiology",
        "ev_mm": 650,
        "ebitda_at_entry_mm": 65,
        "hold_years": 5.0,
        "realized_moic": 0.6,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.50, "medicaid": 0.08, "commercial": 0.39, "self_pay": 0.03},
        "notes": "Outpatient radiology rollup (150+ centers); NASDAQ: AKU. "
                 "Went public via RTO 2018; filed Ch.11 2023 on leveraged balance sheet. "
                 "Radiology reimbursement cuts + labor inflation + over-leverage = disaster formula.",
    },
    {
        "source_id": "seed_523",
        "source": "seed",
        "deal_name": "CHA Health Systems — Korean PE Acquisition",
        "year": 2016,
        "buyer": "MBK Partners (Korean PE)",
        "seller": "CHA Health Systems Founders",
        "sector": "hospital",
        "ev_mm": 1_200,
        "ebitda_at_entry_mm": 90,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.38, "medicaid": 0.25, "commercial": 0.30, "self_pay": 0.07},
        "notes": "Korean health system with U.S. fertility clinic footprint. "
                 "MBK cross-border PE benchmark; global PE expansion into U.S. healthcare. "
                 "Fertility + women's health defensible sub-sector vs. broader hospital.",
    },
    {
        "source_id": "seed_524",
        "source": "seed",
        "deal_name": "Multiplan — Hellman & Friedman LBO",
        "year": 2014,
        "buyer": "Hellman & Friedman",
        "seller": "Starwood Capital Group / Multiplan",
        "sector": "health_it",
        "ev_mm": 4_400,
        "ebitda_at_entry_mm": 600,
        "hold_years": 5.0,
        "realized_moic": 1.7,
        "realized_irr": 0.11,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.80, "self_pay": 0.05},
        "notes": "Out-of-network claims repricing SaaS; NASDAQ: MPLN via SPAC 2020. "
                 "NSA surprise billing law undermined core commercial OON revenue model. "
                 "H&F exit via SPAC at ~1.7x; legislative risk destroyed thesis.",
    },
    {
        "source_id": "seed_525",
        "source": "seed",
        "deal_name": "Netsmart Technologies — GI Partners LBO",
        "year": 2016,
        "buyer": "GI Partners",
        "seller": "Netsmart Public Shareholders",
        "sector": "health_it",
        "ev_mm": 960,
        "ebitda_at_entry_mm": 95,
        "hold_years": 5.0,
        "realized_moic": 3.2,
        "realized_irr": 0.26,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.45, "commercial": 0.25, "self_pay": 0.10},
        "notes": "EHR + care coordination SaaS for behavioral health and post-acute. "
                 "GI Partners sold to Broadview subsidiary 2021. "
                 "Medicaid-heavy payer mix but SaaS model de-risks direct reimbursement exposure.",
    },
    {
        "source_id": "seed_526",
        "source": "seed",
        "deal_name": "Accolade Health — Cigna Investment / IPO",
        "year": 2016,
        "buyer": "Cigna Ventures / Carrick Capital",
        "seller": "Accolade Health Founders",
        "sector": "health_it",
        "ev_mm": 350,
        "ebitda_at_entry_mm": None,
        "hold_years": 4.0,
        "realized_moic": 3.0,
        "realized_irr": 0.32,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.03, "commercial": 0.88, "self_pay": 0.04},
        "notes": "Employer health navigation + benefits advocacy; NASDAQ: ACCD 2020. "
                 "COVID accelerated employer demand for mental health + benefits navigation. "
                 "B2B SaaS model eliminates direct payer reimbursement risk.",
    },
    {
        "source_id": "seed_527",
        "source": "seed",
        "deal_name": "Global Indemnity Group — Starr Companies Acquisition",
        "year": 2019,
        "buyer": "Starr Companies",
        "seller": "Global Indemnity (NASDAQ: GBLI)",
        "sector": "managed_care",
        "ev_mm": 690,
        "ebitda_at_entry_mm": 65,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.05, "medicaid": 0.02, "commercial": 0.90, "self_pay": 0.03},
        "notes": "Health insurance runoff / specialty lines; not a classic PE deal. "
                 "Benchmark: specialty insurance EV/EBITDA ~10.6x. "
                 "Included for managed care benchmarking context.",
    },
    {
        "source_id": "seed_528",
        "source": "seed",
        "deal_name": "HealthMarket / eHealth — Insurance Distribution Platform",
        "year": 2018,
        "buyer": "General Atlantic / Blackstone",
        "seller": "HealthMarket Founders",
        "sector": "managed_care",
        "ev_mm": 1_000,
        "ebitda_at_entry_mm": 90,
        "hold_years": 4.0,
        "realized_moic": 2.2,
        "realized_irr": 0.22,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.08, "commercial": 0.52, "self_pay": 0.05},
        "notes": "Medicare Advantage + individual ACA insurance distribution marketplace. "
                 "SEP and OEP enrollment volatility creates revenue lumpiness. "
                 "GA/Blackstone sold to eHealth subsidiary 2022; MA broker distribution is durable.",
    },
    {
        "source_id": "seed_529",
        "source": "seed",
        "deal_name": "Azul Senior Care — WCAS SNF Platform",
        "year": 2017,
        "buyer": "Welsh Carson Anderson & Stowe",
        "seller": "Azul Senior Care Founders",
        "sector": "snf",
        "ev_mm": 480,
        "ebitda_at_entry_mm": 45,
        "hold_years": 5.0,
        "realized_moic": 2.5,
        "realized_irr": 0.20,
        "payer_mix": {"medicare": 0.28, "medicaid": 0.55, "commercial": 0.12, "self_pay": 0.05},
        "notes": "Skilled nursing facility platform in mid-Atlantic; WCAS buy-and-build. "
                 "Medicaid rate risk primary concern; 55% Medicaid mix is above-average exposure. "
                 "PDPM transition (2019) added Medicare skilled rate complexity.",
    },
    {
        "source_id": "seed_530",
        "source": "seed",
        "deal_name": "Enclara Pharmacia — Bankers Life LBO",
        "year": 2014,
        "buyer": "HarbourVest Partners / Management",
        "seller": "Enclara Founders",
        "sector": "dme_home_health",
        "ev_mm": 180,
        "ebitda_at_entry_mm": 22,
        "hold_years": 5.0,
        "realized_moic": 3.8,
        "realized_irr": 0.31,
        "payer_mix": {"medicare": 0.40, "medicaid": 0.30, "commercial": 0.25, "self_pay": 0.05},
        "notes": "Hospice pharmacy PBM + distribution; sold to Humana 2019 for $685M EV. "
                 "Hospice drug management is defensible niche (formulary + mail order). "
                 "Humana acquired to integrate with Kindred at Home hospice platform.",
    },
    {
        "source_id": "seed_531",
        "source": "seed",
        "deal_name": "Imagine Health — Blackstone Growth Equity",
        "year": 2021,
        "buyer": "Blackstone Growth",
        "seller": "Imagine Health Founders / Oak HC/FT",
        "sector": "managed_care",
        "ev_mm": 600,
        "ebitda_at_entry_mm": 40,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.75, "medicaid": 0.05, "commercial": 0.18, "self_pay": 0.02},
        "notes": "Medicare Supplement + MA insurance distribution; Blackstone growth round. "
                 "MA enrollment tail-wind: 50% of Medicare beneficiaries in MA by 2025. "
                 "Still private; insurance distribution horizontal is consolidating.",
    },
    {
        "source_id": "seed_532",
        "source": "seed",
        "deal_name": "Central Logic / Appriss Health — Roper Technologies",
        "year": 2019,
        "buyer": "Roper Technologies (Public, NASDAQ: ROP)",
        "seller": "Francisco Partners",
        "sector": "health_it",
        "ev_mm": 1_400,
        "ebitda_at_entry_mm": 130,
        "hold_years": 5.0,
        "realized_moic": 3.0,
        "realized_irr": 0.25,
        "payer_mix": {"medicare": 0.35, "medicaid": 0.15, "commercial": 0.45, "self_pay": 0.05},
        "notes": "Patient transfer logistics + prescription drug monitoring SaaS. "
                 "Francisco Partners 5-year hold from ~2014 PE at ~$400M EV. "
                 "Roper acquisition at ~10.8x EBITDA; health IT acquirer roll-up model.",
    },
    {
        "source_id": "seed_533",
        "source": "seed",
        "deal_name": "Tivity Health (Healthways) — Kelso & Company",
        "year": 2019,
        "buyer": "Kelso & Company",
        "seller": "Tivity Health (NASDAQ: TVTY)",
        "sector": "managed_care",
        "ev_mm": 700,
        "ebitda_at_entry_mm": 75,
        "hold_years": 4.0,
        "realized_moic": 1.5,
        "realized_irr": 0.11,
        "payer_mix": {"medicare": 0.80, "medicaid": 0.02, "commercial": 0.16, "self_pay": 0.02},
        "notes": "SilverSneakers wellness program for MA members; Kelso take-private at ~9.3x. "
                 "Nutrisystem acquisition debt strained balance sheet. "
                 "COVID shut gym access → SilverSneakers membership losses. Below-median return.",
    },
    {
        "source_id": "seed_534",
        "source": "seed",
        "deal_name": "Meditrina — General Catalyst VC Backed",
        "year": 2022,
        "buyer": "General Catalyst",
        "seller": "Meditrina Founders",
        "sector": "health_it",
        "ev_mm": 250,
        "ebitda_at_entry_mm": None,
        "hold_years": None,
        "realized_moic": None,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.20, "medicaid": 0.10, "commercial": 0.65, "self_pay": 0.05},
        "notes": "AI-powered clinical documentation for ambulatory. "
                 "Ambient AI documentation sector: Dragon Ambient eXperience (DAX) + others. "
                 "Not a PE deal; VC benchmark for health IT ambient AI at ~$250M early valuation.",
    },
    {
        "source_id": "seed_535",
        "source": "seed",
        "deal_name": "Teladoc Health — Blackstone / HHBF Acquisition",
        "year": 2020,
        "buyer": "Teladoc Health (NASDAQ: TDOC) + Livongo merger",
        "seller": "Livongo Health Shareholders",
        "sector": "health_it",
        "ev_mm": 18_500,
        "ebitda_at_entry_mm": 200,
        "hold_years": 3.0,
        "realized_moic": 0.2,
        "realized_irr": None,
        "payer_mix": {"medicare": 0.10, "medicaid": 0.05, "commercial": 0.75, "self_pay": 0.10},
        "notes": "Teladoc/Livongo merger at peak COVID telehealth hype ($18.5B EV). "
                 "$6.6B goodwill write-down 2022; stock declined 85% from merger peak. "
                 "Pre-revenue SaaS multiples (92x EBITDA!) unwound as growth decelerated. "
                 "Warning: telehealth EV/revenue multiples unsustainable without EBITDA path.",
    },
]
