"""
Step 87: Markdown report format.

Generates a report.md with the same key sections as the HTML report
but in GitHub-flavored Markdown for portability.
"""
from __future__ import annotations

import os
from typing import Any, Dict, Optional

import numpy as np
import pandas as pd

from ..infra.logger import logger
from .narrative import generate_narrative


def _fmt_money(val: float) -> str:
    if abs(val) >= 1_000_000:
        return f"${val / 1_000_000:,.1f}M"
    if abs(val) >= 1_000:
        return f"${val / 1_000:,.0f}K"
    return f"${val:,.0f}"


def _fmt_pct(val: float) -> str:
    return f"{val * 100:.1f}%"


def generate_markdown_report(
    outdir: str,
    *,
    hospital_name: str = "Target Hospital",
    ev_multiple: float = 8.0,
    annual_revenue: float = 0.0,
    n_sims: int = 30000,
) -> str:
    """Generate a Markdown report from simulation outputs."""
    summary_path = os.path.join(outdir, "summary.csv")
    if not os.path.exists(summary_path):
        logger.warning("summary.csv not found in %s; cannot generate Markdown report", outdir)
        return ""

    summary = pd.read_csv(summary_path, index_col=0)
    lines = []

    # Title
    lines.append(f"# RCM Monte Carlo Analysis: {hospital_name}")
    lines.append("")
    lines.append(f"*{n_sims:,} Monte Carlo iterations | Revenue: {_fmt_money(annual_revenue)}*")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    narrative = generate_narrative(summary, hospital_name=hospital_name, ev_multiple=ev_multiple)
    lines.append(narrative)
    lines.append("")

    # Key Metrics Table
    lines.append("## Key Metrics")
    lines.append("")
    lines.append("| Metric | Mean | P10 (Conservative) | P90 (Stress) |")
    lines.append("|--------|------|--------------------|--------------| ")

    for metric in summary.index:
        label = metric.replace("_", " ").title()
        mean_val = float(summary.loc[metric, "mean"])
        p10_val = float(summary.loc[metric, "p10"])
        p90_val = float(summary.loc[metric, "p90"])

        if "drag" in metric or "ebitda" in metric or "leakage" in metric or "cost" in metric or "economic" in metric:
            lines.append(f"| {label} | {_fmt_money(mean_val)} | {_fmt_money(p10_val)} | {_fmt_money(p90_val)} |")
        elif "dar" in metric:
            lines.append(f"| {label} | {mean_val:.1f} days | {p10_val:.1f} days | {p90_val:.1f} days |")
        else:
            lines.append(f"| {label} | {mean_val:,.2f} | {p10_val:,.2f} | {p90_val:,.2f} |")

    lines.append("")

    # Enterprise Value Impact
    if "ebitda_drag" in summary.index:
        ebitda = float(summary.loc["ebitda_drag", "mean"])
        ev = ebitda * ev_multiple
        lines.append("## Enterprise Value Impact")
        lines.append("")
        lines.append(f"At a **{ev_multiple:.0f}x EBITDA multiple**, the annual EBITDA opportunity of {_fmt_money(ebitda)} "
                      f"translates to **{_fmt_money(ev)} in enterprise value**.")
        lines.append("")

    # Sensitivity
    sens_path = os.path.join(outdir, "sensitivity.csv")
    if os.path.exists(sens_path):
        sens = pd.read_csv(sens_path)
        if not sens.empty and "driver" in sens.columns:
            lines.append("## Top Sensitivity Drivers")
            lines.append("")
            lines.append("| Rank | Driver | Correlation |")
            lines.append("|------|--------|-------------|")
            for i, row in sens.head(10).iterrows():
                driver = str(row.get("driver", "")).replace("_", " ").title()
                corr = float(row.get("correlation", 0))
                lines.append(f"| {i+1} | {driver} | {corr:.3f} |")
            lines.append("")

    # Data Sources
    lines.append("## Data Sources")
    lines.append("")
    lines.append("- **simulations.csv**: Raw Monte Carlo output (one row per iteration)")
    lines.append("- **summary.csv**: Aggregate statistics (mean, P10, P50, P90, P95)")
    lines.append("- **provenance.json**: Machine-readable run manifest and metric lineage")
    lines.append("- **sensitivity.csv**: Driver correlation rankings")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by RCM Monte Carlo v0.5.0*")

    content = "\n".join(lines)

    # Write to file
    md_path = os.path.join(outdir, "report.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info("Wrote: %s", md_path)

    return md_path
