"""Packet-driven export renderer.

Every export path — HTML memo, PPTX deck, JSON blob, raw CSV, DOCX
questions, LP update — goes through :class:`PacketRenderer`. Each
method takes a :class:`DealAnalysisPacket` (or a list of them for the
portfolio LP update) and returns a rendered artifact.

Why this module exists:
- Partners kept finding different numbers in the PPTX vs. the live
  UI because each export pulled from the store independently. With
  the packet as the single source of truth, numbers can't drift.
- Audit. Every export footer prints the packet hash and run_id, so a
  partner who sees a stale number in a printed deck can pinpoint the
  exact analysis run that produced it.

Optional dependencies:
- ``python-pptx`` — if missing, the PPTX path emits a structured
  fallback .txt with the same outline, so callers never get a silent
  None. We've had partners paste from the fallback into an external
  PPT; that's a valid workflow.
- ``python-docx`` — same pattern, fallback is a partner-ready markdown
  file that opens cleanly in Word / Google Docs.
"""
from __future__ import annotations

import csv
import html
import json
import logging
import os
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from ..analysis.packet import (
    DealAnalysisPacket,
    DiligencePriority,
    PACKET_SCHEMA_VERSION,
    RiskSeverity,
    SectionStatus,
)

logger = logging.getLogger(__name__)


# ── Constants ────────────────────────────────────────────────────────

_PRODUCT_VERSION = "1.0"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ── Value formatting (mirrors the workbench / renderer conventions) ──

def _fmt_money(v: Optional[float]) -> str:
    if v is None or v != v:
        return "—"
    f = float(v)
    if abs(f) >= 1e9:
        return f"${f/1e9:.2f}B"
    if abs(f) >= 1e6:
        return f"${f/1e6:.1f}M"
    if abs(f) >= 1e3:
        return f"${f/1e3:,.0f}K"
    return f"${f:,.0f}"


def _fmt_pct(v: Optional[float]) -> str:
    if v is None or v != v:
        return "—"
    return f"{float(v):.1f}%"


def _fmt_num(v: Optional[float], dp: int = 2) -> str:
    if v is None or v != v:
        return "—"
    return f"{float(v):.{dp}f}"


def _esc(s: Any) -> str:
    return html.escape("" if s is None else str(s))


# ── Audit footer ─────────────────────────────────────────────────────

@dataclass
class AuditFooter:
    """Footer text used in every export (HTML/PPTX/DOCX/MD).

    Partners specifically asked for packet hash + run_id on every
    printed surface so a stale deck can be traced back to the exact
    analysis that produced it. The footer is generated once per
    export call and passed into each format's template.
    """
    run_id: str
    input_hash: str
    observed_count: int
    predicted_count: int
    generated_at: datetime
    model_version: str

    def as_lines(self) -> List[str]:
        ts = self.generated_at.strftime("%Y-%m-%d %H:%M UTC")
        return [
            f"Generated by RCM-MC v{_PRODUCT_VERSION} on {ts}",
            f"Analysis Packet ID: {self.run_id}",
            f"Input Hash: {self.input_hash or 'n/a'}",
            f"This analysis is based on {self.observed_count} observed "
            f"and {self.predicted_count} predicted metrics.",
            f"Model version: {self.model_version}",
        ]

    def as_html(self) -> str:
        return "<br>".join(html.escape(line) for line in self.as_lines())

    def as_plain_text(self) -> str:
        return "\n".join(self.as_lines())


def _footer_for(
    packet: DealAnalysisPacket,
    inputs_hash: str = "",
) -> AuditFooter:
    return AuditFooter(
        run_id=packet.run_id or "",
        input_hash=inputs_hash,
        observed_count=len(packet.observed_metrics or {}),
        predicted_count=len(packet.predicted_metrics or {}),
        generated_at=packet.generated_at or _utcnow(),
        model_version=packet.model_version or PACKET_SCHEMA_VERSION,
    )


# ── Renderer ─────────────────────────────────────────────────────────

class PacketRenderer:
    """Render a packet into HTML / PPTX / JSON / CSV / DOCX artifacts.

    Output files land under ``out_dir`` (defaults to a fresh temp dir so
    tests don't leak). Callers who want deterministic paths — the
    server for `/exports/downloads/...` URLs, the CLI for `--out` — pass
    their own directory.
    """

    def __init__(self, out_dir: Optional[Path] = None) -> None:
        if out_dir is None:
            out_dir = Path(tempfile.mkdtemp(prefix="rcm_exports_"))
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        self.out_dir = out_dir

    # ── HTML diligence memo ─────────────────────────────────────

    def render_diligence_memo_html(
        self,
        packet: DealAnalysisPacket,
        *,
        inputs_hash: str = "",
    ) -> str:
        footer = _footer_for(packet, inputs_hash)
        sections = [
            _memo_section_exec_summary(packet),
            _memo_section_completeness(packet),
            _memo_section_rcm_performance(packet),
            _memo_section_bridge(packet),
            _memo_section_risks(packet),
            _memo_section_mc(packet),
            _memo_section_diligence_questions(packet),
            _memo_section_comparables(packet),
        ]
        return (
            '<!DOCTYPE html>'
            '<html lang="en"><head><meta charset="utf-8">'
            f'<title>{_esc(packet.deal_name or packet.deal_id)} · Diligence Memo</title>'
            f'<style>{_MEMO_CSS}</style>'
            '</head>'
            '<body><div class="memo-body">'
            f'<h1>{_esc(packet.deal_name or packet.deal_id)}</h1>'
            f'<p class="muted">Diligence Memo · {packet.generated_at.strftime("%Y-%m-%d")}</p>'
            + "".join(sections)
            + f'<footer class="memo-footer">{footer.as_html()}</footer>'
            '</div></body></html>'
        )

    # ── PPTX ────────────────────────────────────────────────────

    def render_diligence_memo_pptx(
        self,
        packet: DealAnalysisPacket,
        *,
        inputs_hash: str = "",
    ) -> Path:
        footer = _footer_for(packet, inputs_hash)
        try:
            from pptx import Presentation    # type: ignore
            from pptx.util import Inches, Pt  # type: ignore
        except ImportError:
            return self._render_pptx_fallback(packet, footer)

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # Slide 1: Title
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = (
            f"RCM Diligence Memo — {packet.deal_name or packet.deal_id}"
        )
        slide.placeholders[1].text = (
            f"{packet.generated_at.strftime('%Y-%m-%d')}\n"
            f"Analysis ID: {packet.run_id}"
        )

        # Slide 2: Executive summary + completeness
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Executive Summary"
        body = slide.placeholders[1]
        body.text = _memo_exec_text(packet)

        # Slide 3: RCM profile (key metrics as text list — text is the
        # most compatible thing across python-pptx versions; tables are
        # fiddly when we can't assume a template layout).
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "RCM Profile"
        slide.placeholders[1].text = _memo_profile_text(packet)

        # Slide 4: Bridge
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "EBITDA Value Creation"
        slide.placeholders[1].text = _memo_bridge_text(packet)

        # Slide 5: Monte Carlo
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Monte Carlo Returns"
        slide.placeholders[1].text = _memo_mc_text(packet)

        # Slide 6: Risks
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Risk Flags"
        slide.placeholders[1].text = _memo_risks_text(packet)

        # Slide 7: Diligence questions
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Diligence Questions (P0)"
        slide.placeholders[1].text = _memo_questions_text(packet)

        # Slide 8: Comparables + footer
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Comparable Set & Audit"
        slide.placeholders[1].text = (
            _memo_comparables_text(packet)
            + "\n\n"
            + footer.as_plain_text()
        )

        path = self.out_dir / f"{_safe_stem(packet)}.pptx"
        prs.save(str(path))
        return path

    def _render_pptx_fallback(
        self, packet: DealAnalysisPacket, footer: AuditFooter,
    ) -> Path:
        """Hand-built minimal OOXML ``.pptx`` via stdlib ``zipfile``.

        When ``python-pptx`` is absent we still produce a file partners
        can open in PowerPoint. It isn't beautiful — no theme images,
        no master art — but the deck has the eight required slides
        (title + bullets), valid relationships, and valid content
        types, which is enough for Office + LibreOffice to load it.

        Kept in this module (rather than a separate ``pptx_fallback``
        file) so the public surface stays narrow: the server and CLI
        just call ``render_diligence_memo_pptx`` and get back a
        ``.pptx`` path regardless of whether ``python-pptx`` is
        installed. Tests assert both outputs have the same set of
        slide IDs.
        """
        slides_content: List[Tuple[str, str]] = [
            ("Title",
                f"{packet.deal_name or packet.deal_id}\n"
                f"Generated {packet.generated_at.strftime('%Y-%m-%d')}"),
            ("Executive Summary", _memo_exec_text(packet)),
            ("RCM Profile", _memo_profile_text(packet)),
            ("EBITDA Value Creation", _memo_bridge_text(packet)),
            ("Monte Carlo Returns", _memo_mc_text(packet)),
            ("Risk Flags", _memo_risks_text(packet)),
            ("Diligence Questions (P0)", _memo_questions_text(packet)),
            ("Comparables & Audit",
                _memo_comparables_text(packet)
                + "\n\n" + footer.as_plain_text()),
        ]
        path = self.out_dir / f"{_safe_stem(packet)}.pptx"
        _write_minimal_pptx(path, slides_content)
        return path

    # ── XLSX ────────────────────────────────────────────────────

    def render_deal_xlsx(
        self,
        packet: DealAnalysisPacket,
        *,
        inputs_hash: str = "",
    ) -> Path:
        """Multi-sheet Excel workbook. Falls back to CSV when
        ``openpyxl`` is missing.

        Partners want Excel because downstream workflows (decks, LP
        updates, IC memos) all live there. The CSV export stays as
        the stdlib-only fallback; ``render_deal_xlsx`` is the
        structured, multi-sheet version when the optional dep is
        present.
        """
        from .xlsx_renderer import render_deal_xlsx as _render_xlsx
        try:
            return _render_xlsx(
                packet, self.out_dir, inputs_hash=inputs_hash,
            )
        except ImportError:
            # openpyxl absent — fall back to the CSV export the caller
            # was going to get anyway. The audit row records ``csv``
            # so partners see the fallback happened.
            return self.render_raw_data_csv(
                packet, inputs_hash=inputs_hash,
            )

    # ── JSON ────────────────────────────────────────────────────

    def render_packet_json(self, packet: DealAnalysisPacket) -> str:
        """Full packet as pretty JSON. The canonical wire format."""
        return packet.to_json(indent=2)

    # ── Raw CSV ─────────────────────────────────────────────────

    def render_raw_data_csv(
        self,
        packet: DealAnalysisPacket,
        *,
        inputs_hash: str = "",  # noqa: ARG002 — not in CSV body; see footer log
    ) -> Path:
        """One row per RCM metric with current + benchmark + predicted."""
        try:
            from ..analysis.completeness import RCM_METRIC_REGISTRY
        except Exception:  # noqa: BLE001
            RCM_METRIC_REGISTRY = {}

        # Build per-metric impacts lookup so we can report ebitda_impact.
        impact_by_metric: Dict[str, float] = {}
        for imp in (packet.ebitda_bridge.per_metric_impacts or []):
            impact_by_metric[imp.metric_key] = float(imp.ebitda_impact)

        # Risk-flag lookup keyed by trigger metric.
        risks_by_metric: Dict[str, List[str]] = {}
        for rf in (packet.risk_flags or []):
            for tm in (rf.trigger_metrics or [rf.trigger_metric] or []):
                if not tm:
                    continue
                sev = rf.severity.value if hasattr(rf.severity, "value") else str(rf.severity)
                risks_by_metric.setdefault(tm, []).append(f"{sev}: {rf.title or ''}")

        path = self.out_dir / f"{_safe_stem(packet)}.csv"
        with open(path, "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow([
                "metric_key", "display_name", "current_value", "source",
                "benchmark_p50", "predicted_value", "ci_low", "ci_high",
                "ebitda_impact", "risk_flags",
            ])
            # Union of all metrics we know about for this deal: rcm_profile
            # + predicted + registry defaults. Keeps the CSV stable row
            # count across deals.
            seen: set = set()
            ordered_keys: List[str] = []
            for k in (packet.rcm_profile or {}):
                if k not in seen:
                    seen.add(k); ordered_keys.append(k)
            for k in (packet.predicted_metrics or {}):
                if k not in seen:
                    seen.add(k); ordered_keys.append(k)
            for k in ordered_keys:
                pm = packet.rcm_profile.get(k)
                pred = packet.predicted_metrics.get(k)
                meta = RCM_METRIC_REGISTRY.get(k) or {}
                display = meta.get("display_name") or k
                value = pm.value if pm is not None else None
                source = pm.source.value if pm is not None else ""
                p50 = meta.get("benchmark_p50")
                pred_val = pred.value if pred is not None else None
                ci_low = pred.ci_low if pred is not None else None
                ci_high = pred.ci_high if pred is not None else None
                ebitda_impact = impact_by_metric.get(k)
                risks = "; ".join(risks_by_metric.get(k, []))
                w.writerow([
                    k, display,
                    _fmt_cell_num(value), source,
                    _fmt_cell_num(p50),
                    _fmt_cell_num(pred_val),
                    _fmt_cell_num(ci_low),
                    _fmt_cell_num(ci_high),
                    _fmt_cell_num(ebitda_impact),
                    risks,
                ])
            # Trailing comment rows for provenance.
            footer = _footer_for(packet, inputs_hash)
            for line in footer.as_lines():
                w.writerow([f"# {line}"])
        return path

    # ── LP update (portfolio) ───────────────────────────────────

    def render_lp_update_html(
        self,
        packets: Iterable[DealAnalysisPacket],
    ) -> str:
        """Portfolio-level LP update assembled from multiple packets.

        One card per deal with name, total EBITDA opportunity, top
        risk flag, top diligence question, and the packet's audit
        footer for trace-back.
        """
        pks = list(packets or [])
        cards: List[str] = []
        total_opportunity = 0.0
        deal_count = 0
        critical_count = 0
        for p in pks:
            deal_count += 1
            opp = float(p.ebitda_bridge.total_ebitda_impact or 0.0)
            total_opportunity += opp
            critical = [r for r in (p.risk_flags or [])
                        if getattr(r.severity, "value", r.severity) == "CRITICAL"]
            critical_count += len(critical)
            top_risk = critical[0] if critical else (p.risk_flags[0] if p.risk_flags else None)
            risk_html = (
                f'<div class="lp-risk"><span class="lp-badge lp-badge-'
                f'{(top_risk.severity.value if hasattr(top_risk.severity, "value") else top_risk.severity).lower()}">'
                f'{_esc(top_risk.severity.value if hasattr(top_risk.severity, "value") else top_risk.severity)}'
                f'</span> {_esc(top_risk.title)}</div>'
                if top_risk else '<div class="lp-muted">no risk flags</div>'
            )
            top_q = next(
                (q for q in (p.diligence_questions or [])
                 if (q.priority.value if hasattr(q.priority, "value") else str(q.priority)) == "P0"),
                None,
            )
            q_html = (f'<div class="lp-q">{_esc(top_q.question)}</div>'
                       if top_q else '')
            cards.append(
                f'<div class="lp-card">'
                f'<div class="lp-card-header">'
                f'<span class="lp-deal-name">{_esc(p.deal_name or p.deal_id)}</span>'
                f'<span class="lp-opportunity">{_fmt_money(opp)}</span>'
                f'</div>'
                f'{risk_html}{q_html}'
                f'<div class="lp-audit">Run {_esc(p.run_id)} · '
                f'{_esc(p.generated_at.strftime("%Y-%m-%d"))}</div>'
                f'</div>'
            )
        headline = (
            f'<div class="lp-headline">'
            f'<div><span class="lp-num">{deal_count}</span>'
            f'<span class="lp-lbl">active deals</span></div>'
            f'<div><span class="lp-num">{_fmt_money(total_opportunity)}</span>'
            f'<span class="lp-lbl">total opportunity</span></div>'
            f'<div><span class="lp-num">{critical_count}</span>'
            f'<span class="lp-lbl">critical risks</span></div>'
            f'</div>'
        )
        ts = _utcnow().strftime("%Y-%m-%d %H:%M UTC")
        return (
            '<!DOCTYPE html>'
            '<html lang="en"><head><meta charset="utf-8">'
            '<title>Portfolio LP Update</title>'
            f'<style>{_LP_CSS}</style>'
            '</head><body>'
            '<h1>Portfolio LP Update</h1>'
            f'<p class="lp-muted">{ts} · {deal_count} deals</p>'
            + headline
            + '<div class="lp-grid">'
            + "\n".join(cards)
            + '</div>'
            + f'<footer class="lp-audit">Generated by RCM-MC v{_PRODUCT_VERSION} · aggregated from {deal_count} analysis packets</footer>'
            + '</body></html>'
        )

    # ── DOCX diligence questions ────────────────────────────────

    def render_diligence_questions_docx(
        self,
        packet: DealAnalysisPacket,
        *,
        inputs_hash: str = "",
    ) -> Path:
        """Diligence questions grouped by priority → category.

        When ``python-docx`` is installed we emit a real .docx. Without
        it we fall back to a .md file that opens cleanly in Word /
        Google Docs — partners pasting into their own template is the
        common case anyway, so the fallback is explicitly partner-safe,
        not a stub.
        """
        footer = _footer_for(packet, inputs_hash)
        try:
            from docx import Document   # type: ignore
        except ImportError:
            return self._render_questions_markdown_fallback(packet, footer)

        doc = Document()
        doc.add_heading(
            f"{packet.deal_name or packet.deal_id} — Diligence Questions",
            level=1,
        )
        doc.add_paragraph(
            f"Generated {packet.generated_at.strftime('%Y-%m-%d')} · "
            f"Analysis Packet {packet.run_id}"
        )
        for priority in ("P0", "P1", "P2"):
            bucket = [q for q in (packet.diligence_questions or [])
                      if (q.priority.value if hasattr(q.priority, "value") else str(q.priority)) == priority]
            if not bucket:
                continue
            doc.add_heading(f"{priority} Questions ({len(bucket)})", level=2)
            by_cat: Dict[str, list] = {}
            for q in bucket:
                by_cat.setdefault(q.category or "GENERAL", []).append(q)
            for cat, qs in by_cat.items():
                doc.add_heading(cat, level=3)
                for q in qs:
                    p = doc.add_paragraph(style="List Bullet")
                    p.add_run(q.question)
                    if q.context:
                        ctx = doc.add_paragraph(style="Intense Quote")
                        ctx.add_run(f"Context: {q.context}")
        doc.add_heading("Audit Trail", level=2)
        for line in footer.as_lines():
            doc.add_paragraph(line)
        path = self.out_dir / f"{_safe_stem(packet)}_questions.docx"
        doc.save(str(path))
        return path

    def _render_questions_markdown_fallback(
        self, packet: DealAnalysisPacket, footer: AuditFooter,
    ) -> Path:
        lines = [
            f"# {packet.deal_name or packet.deal_id} — Diligence Questions",
            "",
            f"Generated {packet.generated_at.strftime('%Y-%m-%d')} · "
            f"Analysis Packet {packet.run_id}",
            "",
        ]
        for priority in ("P0", "P1", "P2"):
            bucket = [q for q in (packet.diligence_questions or [])
                      if (q.priority.value if hasattr(q.priority, "value") else str(q.priority)) == priority]
            if not bucket:
                continue
            lines.append(f"## {priority} Questions ({len(bucket)})")
            lines.append("")
            by_cat: Dict[str, list] = {}
            for q in bucket:
                by_cat.setdefault(q.category or "GENERAL", []).append(q)
            for cat, qs in by_cat.items():
                lines.append(f"### {cat}")
                for q in qs:
                    lines.append(f"- {q.question}")
                    if q.context:
                        lines.append(f"  - *Context:* {q.context}")
                lines.append("")
        lines.append("---")
        lines.append("## Audit Trail")
        for l in footer.as_lines():
            lines.append(f"- {l}")
        path = self.out_dir / f"{_safe_stem(packet)}_questions.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        return path


# ── Memo section builders ───────────────────────────────────────────

def _memo_section_exec_summary(packet: DealAnalysisPacket) -> str:
    total_impact = float(packet.ebitda_bridge.total_ebitda_impact or 0.0)
    grade = packet.completeness.grade or "—"
    critical = sum(
        1 for r in (packet.risk_flags or [])
        if (r.severity.value if hasattr(r.severity, "value") else str(r.severity)) == "CRITICAL"
    )
    assessment = (
        f"Grade {grade} data completeness. "
        f"Total EBITDA opportunity modeled at {_fmt_money(total_impact)}. "
        f"{critical} critical risk flag(s) identified."
    )
    return (
        '<section class="memo-section">'
        '<h2>1. Executive Summary</h2>'
        f'<p>{_esc(packet.deal_name or packet.deal_id)} — '
        f'{_esc(packet.profile.name or "")}</p>'
        f'<p>{_esc(assessment)}</p>'
        '</section>'
    )


def _memo_section_completeness(packet: DealAnalysisPacket) -> str:
    c = packet.completeness
    missing = c.missing_fields[:5]
    missing_html = "".join(
        f'<li>{_esc(m.display_name or m.metric_key)} '
        f'(sensitivity rank {m.ebitda_sensitivity_rank})</li>'
        for m in missing
    ) or '<li>all required metrics observed</li>'
    return (
        '<section class="memo-section">'
        '<h2>2. Data Completeness &amp; Quality</h2>'
        f'<p>Grade <strong>{c.grade or "—"}</strong>, covering '
        f'{c.observed_count}/{c.total_metrics} metrics '
        f'({_fmt_pct(c.coverage_pct * 100)}).</p>'
        '<h3>Top missing metrics (by EBITDA sensitivity)</h3>'
        f'<ol>{missing_html}</ol>'
        '</section>'
    )


def _memo_section_rcm_performance(packet: DealAnalysisPacket) -> str:
    try:
        from ..analysis.completeness import RCM_METRIC_REGISTRY
    except Exception:  # noqa: BLE001
        RCM_METRIC_REGISTRY = {}
    rows = []
    # Show just the headline metrics partners scan first.
    headline = [
        "denial_rate", "days_in_ar", "net_collection_rate",
        "clean_claim_rate", "cost_to_collect", "first_pass_resolution_rate",
    ]
    for k in headline:
        pm = packet.rcm_profile.get(k)
        if pm is None:
            continue
        meta = RCM_METRIC_REGISTRY.get(k) or {}
        p50 = meta.get("benchmark_p50")
        source = pm.source.value if hasattr(pm.source, "value") else str(pm.source)
        rows.append(
            f'<tr>'
            f'<td>{_esc(meta.get("display_name") or k)}</td>'
            f'<td class="num">{_fmt_num(pm.value, dp=1)}</td>'
            f'<td>{_esc(source)}</td>'
            f'<td class="num">{_fmt_num(p50, dp=1) if p50 is not None else "—"}</td>'
            f'</tr>'
        )
    if not rows:
        return ('<section class="memo-section"><h2>3. RCM Performance Summary</h2>'
                '<p>No headline metrics observed.</p></section>')
    return (
        '<section class="memo-section">'
        '<h2>3. RCM Performance Summary</h2>'
        '<table><thead><tr>'
        '<th>Metric</th><th class="num">Current</th>'
        '<th>Source</th><th class="num">Benchmark P50</th>'
        '</tr></thead><tbody>'
        + "".join(rows)
        + '</tbody></table>'
        '</section>'
    )


def _memo_section_bridge(packet: DealAnalysisPacket) -> str:
    br = packet.ebitda_bridge
    if br.status != SectionStatus.OK:
        return ('<section class="memo-section"><h2>4. EBITDA Value Creation</h2>'
                f'<p>Bridge unavailable: {_esc(br.reason or "no data")}.</p></section>')
    rows = []
    for imp in br.per_metric_impacts:
        rows.append(
            f'<tr>'
            f'<td>{_esc(imp.metric_key)}</td>'
            f'<td class="num">{_fmt_num(imp.current_value, dp=1)}</td>'
            f'<td class="num">{_fmt_num(imp.target_value, dp=1)}</td>'
            f'<td class="num">{_fmt_money(imp.ebitda_impact)}</td>'
            f'</tr>'
        )
    summary = (
        f'<p>Total EBITDA impact: <strong>{_fmt_money(br.total_ebitda_impact)}</strong> '
        f'({br.margin_improvement_bps:+d} bps margin). '
        f'New EBITDA: {_fmt_money(br.target_ebitda)}.</p>'
    )
    ev = br.ev_impact_at_multiple or {}
    ev_line = ""
    if ev:
        ev_bits = " · ".join(f"{k} {_fmt_money(v)}" for k, v in ev.items())
        ev_line = f"<p>Enterprise value uplift: {_esc(ev_bits)}.</p>"
    return (
        '<section class="memo-section">'
        '<h2>4. EBITDA Value Creation Opportunity</h2>'
        + summary + ev_line
        + '<table><thead><tr><th>Lever</th>'
        '<th class="num">Current</th><th class="num">Target</th>'
        '<th class="num">EBITDA Impact</th></tr></thead><tbody>'
        + "".join(rows)
        + '</tbody></table>'
        '</section>'
    )


def _memo_section_risks(packet: DealAnalysisPacket) -> str:
    flags = (packet.risk_flags or [])[:5]
    if not flags:
        return ('<section class="memo-section"><h2>5. Risk Assessment</h2>'
                '<p>No risk flags raised.</p></section>')
    items = []
    for rf in flags:
        sev = rf.severity.value if hasattr(rf.severity, "value") else str(rf.severity)
        ear = (f' <em>EBITDA at risk: {_fmt_money(rf.ebitda_at_risk)}</em>'
               if rf.ebitda_at_risk else "")
        items.append(
            f'<li><strong>[{_esc(sev)}] {_esc(rf.title)}</strong>: '
            f'{_esc(rf.detail or rf.explanation)}{ear}</li>'
        )
    return (
        '<section class="memo-section">'
        '<h2>5. Risk Assessment</h2>'
        '<ol>' + "".join(items) + '</ol>'
        '</section>'
    )


def _memo_section_mc(packet: DealAnalysisPacket) -> str:
    mc = packet.simulation
    if mc is None or mc.status != SectionStatus.OK:
        return ('<section class="memo-section"><h2>6. Monte Carlo Returns Summary</h2>'
                '<p>Simulation not run.</p></section>')
    u = mc.ebitda_uplift
    return (
        '<section class="memo-section">'
        '<h2>6. Monte Carlo Returns Summary</h2>'
        f'<p>{mc.n_sims:,} simulations. EBITDA impact '
        f'{_fmt_money(u.p10)} (P10) · <strong>{_fmt_money(u.p50)}</strong> (P50) · '
        f'{_fmt_money(u.p90)} (P90).</p>'
        f'<p>MOIC P50 {_fmt_num(mc.moic.p50, dp=2)}x · '
        f'IRR P50 {_fmt_pct((mc.irr.p50 or 0.0) * 100)}.</p>'
        '</section>'
    )


def _memo_section_diligence_questions(packet: DealAnalysisPacket) -> str:
    p0 = [q for q in (packet.diligence_questions or [])
          if (q.priority.value if hasattr(q.priority, "value") else str(q.priority)) == "P0"]
    if not p0:
        return ('<section class="memo-section"><h2>7. Key Diligence Questions</h2>'
                '<p>No P0 items.</p></section>')
    items = []
    for q in p0[:15]:
        items.append(
            f'<li>{_esc(q.question)}'
            + (f' <em>({_esc(q.context)})</em>' if q.context else '')
            + '</li>'
        )
    return (
        '<section class="memo-section">'
        '<h2>7. Key Diligence Questions (P0)</h2>'
        '<ol>' + "".join(items) + '</ol>'
        '</section>'
    )


def _memo_section_comparables(packet: DealAnalysisPacket) -> str:
    cs = packet.comparables
    if not cs or not cs.peers:
        return ('<section class="memo-section"><h2>8. Comparable Set</h2>'
                '<p>No comparable set available.</p></section>')
    rows = []
    for peer in cs.peers[:10]:
        rows.append(
            f'<tr><td>{_esc(peer.id)}</td>'
            f'<td class="num">{_fmt_num(peer.similarity_score, dp=2)}</td></tr>'
        )
    return (
        '<section class="memo-section">'
        '<h2>8. Comparable Set</h2>'
        f'<p>{len(cs.peers)} hospitals matched on '
        f'{", ".join(cs.features_used or [])}.</p>'
        '<table><thead><tr><th>Peer</th>'
        '<th class="num">Similarity</th></tr></thead>'
        '<tbody>' + "".join(rows) + '</tbody></table>'
        '</section>'
    )


# ── Plain-text versions for PPTX body placeholders ──────────────────

def _memo_exec_text(packet: DealAnalysisPacket) -> str:
    total = float(packet.ebitda_bridge.total_ebitda_impact or 0.0)
    grade = packet.completeness.grade or "—"
    return (
        f"Grade {grade} data completeness.\n"
        f"Total EBITDA opportunity: {_fmt_money(total)}.\n"
        f"New EBITDA: {_fmt_money(packet.ebitda_bridge.target_ebitda)}."
    )


def _memo_profile_text(packet: DealAnalysisPacket) -> str:
    lines = []
    for k in ("denial_rate", "days_in_ar", "net_collection_rate",
               "clean_claim_rate", "cost_to_collect"):
        pm = packet.rcm_profile.get(k)
        if pm is None:
            continue
        lines.append(f"• {k}: {_fmt_num(pm.value, dp=1)}")
    return "\n".join(lines) or "No RCM profile metrics available."


def _memo_bridge_text(packet: DealAnalysisPacket) -> str:
    br = packet.ebitda_bridge
    if br.status != SectionStatus.OK:
        return f"Bridge unavailable: {br.reason}"
    lines = [
        f"Current EBITDA: {_fmt_money(br.current_ebitda)}",
        f"Target EBITDA: {_fmt_money(br.target_ebitda)}",
        f"Total impact: {_fmt_money(br.total_ebitda_impact)} "
        f"({br.margin_improvement_bps:+d} bps)",
    ]
    for imp in br.per_metric_impacts:
        lines.append(f"  • {imp.metric_key}: {_fmt_money(imp.ebitda_impact)}")
    return "\n".join(lines)


def _memo_mc_text(packet: DealAnalysisPacket) -> str:
    mc = packet.simulation
    if mc is None or mc.status != SectionStatus.OK:
        return "Monte Carlo: not run."
    u = mc.ebitda_uplift
    return (
        f"{mc.n_sims:,} sims\n"
        f"P10 {_fmt_money(u.p10)} · P50 {_fmt_money(u.p50)} · P90 {_fmt_money(u.p90)}\n"
        f"MOIC P50: {_fmt_num(mc.moic.p50, dp=2)}x"
    )


def _memo_risks_text(packet: DealAnalysisPacket) -> str:
    flags = (packet.risk_flags or [])[:5]
    if not flags:
        return "No risk flags raised."
    lines = []
    for rf in flags:
        sev = rf.severity.value if hasattr(rf.severity, "value") else str(rf.severity)
        line = f"[{sev}] {rf.title}"
        if rf.ebitda_at_risk:
            line += f" ({_fmt_money(rf.ebitda_at_risk)} at risk)"
        lines.append(line)
    return "\n".join(lines)


def _memo_questions_text(packet: DealAnalysisPacket) -> str:
    p0 = [q for q in (packet.diligence_questions or [])
          if (q.priority.value if hasattr(q.priority, "value") else str(q.priority)) == "P0"]
    if not p0:
        return "No P0 items."
    return "\n".join(f"• {q.question}" for q in p0[:10])


def _memo_comparables_text(packet: DealAnalysisPacket) -> str:
    cs = packet.comparables
    if not cs or not cs.peers:
        return "No comparable set."
    lines = [f"{len(cs.peers)} peers matched on {', '.join(cs.features_used or [])}"]
    for peer in cs.peers[:6]:
        lines.append(f"  {peer.id} ({peer.similarity_score:.2f})")
    return "\n".join(lines)


# ── Utilities ───────────────────────────────────────────────────────

def _write_minimal_pptx(
    path: Path, slides: List[Tuple[str, str]],
) -> None:
    """Emit a minimum-viable OOXML ``.pptx`` zip archive.

    Parts we produce (matches what PowerPoint and LibreOffice accept
    as a no-theme deck):

    - ``[Content_Types].xml`` — content-type mappings for every part.
    - ``_rels/.rels`` — root → ``ppt/presentation.xml``.
    - ``ppt/presentation.xml`` — slide size (720×540 pt), slide ID
      list referencing the slide rels.
    - ``ppt/_rels/presentation.xml.rels`` — rels to each slide, the
      slide master, and the theme.
    - ``ppt/slideMasters/slideMaster1.xml`` + rels.
    - ``ppt/slideLayouts/slideLayout1.xml`` + rels.
    - ``ppt/theme/theme1.xml`` — bare ``a:theme`` element (no colors
      beyond the defaults); PowerPoint fills in the rest.
    - ``ppt/slides/slideN.xml`` + rels for each slide.

    Keeping the XML inline as constants here rather than as data files
    because this fallback needs to work from a fresh stdlib-only
    install — if we shipped template files under ``package-data``
    someone skipping that data dir (e.g. pyinstaller) would break the
    fallback silently.
    """
    import zipfile
    from html import escape as _xml_escape

    def _text_body(text: str) -> str:
        """Split ``text`` into paragraphs → ``<a:p>`` bullet blocks."""
        paragraphs: List[str] = []
        for raw_line in (text or "").split("\n"):
            line = raw_line.rstrip()
            if not line:
                paragraphs.append('<a:p><a:endParaRPr lang="en-US"/></a:p>')
                continue
            paragraphs.append(
                '<a:p><a:r><a:rPr lang="en-US" dirty="0"/>'
                f'<a:t>{_xml_escape(line)}</a:t></a:r></a:p>'
            )
        return "".join(paragraphs) or (
            '<a:p><a:endParaRPr lang="en-US"/></a:p>'
        )

    def _slide_xml(title: str, body: str) -> str:
        return (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"'
            ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'
            ' xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">'
            '<p:cSld><p:spTree>'
            '<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/>'
            '<p:nvPr/></p:nvGrpSpPr>'
            '<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
            '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>'
            # Title shape.
            '<p:sp><p:nvSpPr><p:cNvPr id="2" name="Title 1"/>'
            '<p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr>'
            '<p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr>'
            '<p:spPr><a:xfrm><a:off x="457200" y="274638"/>'
            '<a:ext cx="8229600" cy="1143000"/></a:xfrm></p:spPr>'
            '<p:txBody><a:bodyPr/><a:lstStyle/>'
            f'<a:p><a:r><a:rPr lang="en-US" dirty="0"/>'
            f'<a:t>{_xml_escape(title)}</a:t></a:r></a:p>'
            '</p:txBody></p:sp>'
            # Body shape.
            '<p:sp><p:nvSpPr><p:cNvPr id="3" name="Content Placeholder 2"/>'
            '<p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr>'
            '<p:nvPr><p:ph idx="1"/></p:nvPr></p:nvSpPr>'
            '<p:spPr><a:xfrm><a:off x="457200" y="1600200"/>'
            '<a:ext cx="8229600" cy="4525962"/></a:xfrm></p:spPr>'
            f'<p:txBody><a:bodyPr/><a:lstStyle/>{body}</p:txBody></p:sp>'
            '</p:spTree></p:cSld>'
            '<p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>'
        )

    n = len(slides)

    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/ppt/presentation.xml"'
        ' ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>'
        '<Override PartName="/ppt/slideMasters/slideMaster1.xml"'
        ' ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>'
        '<Override PartName="/ppt/slideLayouts/slideLayout1.xml"'
        ' ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>'
        '<Override PartName="/ppt/theme/theme1.xml"'
        ' ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>'
        + "".join(
            f'<Override PartName="/ppt/slides/slide{i}.xml"'
            f' ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
            for i in range(1, n + 1)
        )
        + '</Types>'
    )

    root_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"'
        ' Target="ppt/presentation.xml"/>'
        '</Relationships>'
    )

    slide_id_list = "".join(
        f'<p:sldId id="{256 + i}" r:id="rId{i}"/>'
        for i in range(1, n + 1)
    )
    presentation_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"'
        ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'
        ' xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">'
        f'<p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId{n + 1}"/></p:sldMasterIdLst>'
        f'<p:sldIdLst>{slide_id_list}</p:sldIdLst>'
        '<p:sldSz cx="9144000" cy="6858000"/>'
        '<p:notesSz cx="6858000" cy="9144000"/>'
        '</p:presentation>'
    )

    presentation_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        + "".join(
            f'<Relationship Id="rId{i}"'
            f' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide"'
            f' Target="slides/slide{i}.xml"/>'
            for i in range(1, n + 1)
        )
        + f'<Relationship Id="rId{n + 1}"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster"'
        ' Target="slideMasters/slideMaster1.xml"/>'
        f'<Relationship Id="rId{n + 2}"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"'
        ' Target="theme/theme1.xml"/>'
        '</Relationships>'
    )

    slide_master_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"'
        ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'
        ' xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">'
        '<p:cSld><p:bg><p:bgRef idx="1001"><a:schemeClr val="bg1"/></p:bgRef></p:bg>'
        '<p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/>'
        '<p:nvPr/></p:nvGrpSpPr>'
        '<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
        '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>'
        '</p:spTree></p:cSld>'
        '<p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1"'
        ' accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5"'
        ' accent6="accent6" hlink="hlink" folHlink="folHlink"/>'
        '<p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>'
        '</p:sldMaster>'
    )
    slide_master_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"'
        ' Target="../slideLayouts/slideLayout1.xml"/>'
        '<Relationship Id="rId2"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"'
        ' Target="../theme/theme1.xml"/>'
        '</Relationships>'
    )

    slide_layout_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"'
        ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'
        ' xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"'
        ' type="obj" preserve="1">'
        '<p:cSld name="Title and Content">'
        '<p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/>'
        '<p:nvPr/></p:nvGrpSpPr>'
        '<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
        '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>'
        '</p:spTree></p:cSld>'
        '<p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>'
    )
    slide_layout_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster"'
        ' Target="../slideMasters/slideMaster1.xml"/>'
        '</Relationships>'
    )

    # Bare theme — PowerPoint fills in missing color tokens.
    theme_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"'
        ' name="Office Theme">'
        '<a:themeElements>'
        '<a:clrScheme name="Office">'
        '<a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1>'
        '<a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1>'
        '<a:dk2><a:srgbClr val="44546A"/></a:dk2>'
        '<a:lt2><a:srgbClr val="E7E6E6"/></a:lt2>'
        '<a:accent1><a:srgbClr val="5B9BD5"/></a:accent1>'
        '<a:accent2><a:srgbClr val="ED7D31"/></a:accent2>'
        '<a:accent3><a:srgbClr val="A5A5A5"/></a:accent3>'
        '<a:accent4><a:srgbClr val="FFC000"/></a:accent4>'
        '<a:accent5><a:srgbClr val="4472C4"/></a:accent5>'
        '<a:accent6><a:srgbClr val="70AD47"/></a:accent6>'
        '<a:hlink><a:srgbClr val="0563C1"/></a:hlink>'
        '<a:folHlink><a:srgbClr val="954F72"/></a:folHlink>'
        '</a:clrScheme>'
        '<a:fontScheme name="Office">'
        '<a:majorFont><a:latin typeface="Calibri Light"/>'
        '<a:ea typeface=""/><a:cs typeface=""/></a:majorFont>'
        '<a:minorFont><a:latin typeface="Calibri"/>'
        '<a:ea typeface=""/><a:cs typeface=""/></a:minorFont>'
        '</a:fontScheme>'
        '<a:fmtScheme name="Office">'
        '<a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst>'
        '<a:lnStyleLst><a:ln><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln>'
        '<a:ln><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln>'
        '<a:ln><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst>'
        '<a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle>'
        '<a:effectStyle><a:effectLst/></a:effectStyle>'
        '<a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst>'
        '<a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
        '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst>'
        '</a:fmtScheme>'
        '</a:themeElements>'
        '</a:theme>'
    )

    slide_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"'
        ' Target="../slideLayouts/slideLayout1.xml"/>'
        '</Relationships>'
    )

    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("_rels/.rels", root_rels)
        z.writestr("ppt/presentation.xml", presentation_xml)
        z.writestr("ppt/_rels/presentation.xml.rels", presentation_rels)
        z.writestr(
            "ppt/slideMasters/slideMaster1.xml", slide_master_xml,
        )
        z.writestr(
            "ppt/slideMasters/_rels/slideMaster1.xml.rels",
            slide_master_rels,
        )
        z.writestr(
            "ppt/slideLayouts/slideLayout1.xml", slide_layout_xml,
        )
        z.writestr(
            "ppt/slideLayouts/_rels/slideLayout1.xml.rels",
            slide_layout_rels,
        )
        z.writestr("ppt/theme/theme1.xml", theme_xml)
        for i, (title, body_text) in enumerate(slides, start=1):
            z.writestr(
                f"ppt/slides/slide{i}.xml",
                _slide_xml(title, _text_body(body_text)),
            )
            z.writestr(
                f"ppt/slides/_rels/slide{i}.xml.rels", slide_rels,
            )


def _safe_stem(packet: DealAnalysisPacket) -> str:
    import re
    base = packet.run_id or packet.deal_id or "packet"
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(base))


def _fmt_cell_num(v: Optional[float]) -> str:
    if v is None or v != v:
        return ""
    return f"{float(v):.4f}"


# ── Minimal CSS for memo / LP update ────────────────────────────────

_MEMO_CSS = """
:root { --bg:#fafbfc; --fg:#1a1f2c; --muted:#6b7280; --border:#e5e7eb; --accent:#1f4e78; }
body { margin: 0; background: var(--bg); color: var(--fg);
       font-family: -apple-system, "Segoe UI", sans-serif; font-size: 14px; line-height: 1.55; }
.memo-body { max-width: 820px; margin: 32px auto; padding: 24px;
             background: #fff; border: 1px solid var(--border); }
h1 { color: var(--accent); margin: 0 0 4px 0; font-size: 24px; }
h2 { color: var(--accent); margin: 28px 0 8px 0; font-size: 17px;
     padding-bottom: 4px; border-bottom: 2px solid var(--border); }
h3 { font-size: 14px; margin: 14px 0 6px 0; }
.muted { color: var(--muted); font-size: 12px; }
table { width: 100%; border-collapse: collapse; margin: 6px 0; }
th, td { padding: 6px 10px; border-bottom: 1px solid var(--border);
         font-size: 13px; text-align: left; }
th { background: #f3f4f6; font-weight: 600; font-size: 11px;
     text-transform: uppercase; letter-spacing: 0.05em; }
td.num, th.num { text-align: right;
                  font-family: "JetBrains Mono", Menlo, monospace;
                  font-variant-numeric: tabular-nums; }
.memo-footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid var(--border);
               font-size: 11px; color: var(--muted); font-family: monospace; }
.memo-section { margin-bottom: 20px; }
"""

_LP_CSS = """
body { margin: 0; padding: 24px;
       background: #fafbfc; color: #1a1f2c;
       font-family: -apple-system, "Segoe UI", sans-serif; }
h1 { color: #1f4e78; margin: 0 0 4px 0; }
.lp-muted { color: #6b7280; font-size: 12px; }
.lp-headline { display: flex; gap: 18px; margin: 20px 0; }
.lp-headline > div {
  padding: 10px 14px; background: #fff; border: 1px solid #e5e7eb;
  border-radius: 3px; min-width: 140px;
}
.lp-num { display: block; font-size: 24px; font-weight: 600;
          font-family: "JetBrains Mono", monospace; }
.lp-lbl { display: block; font-size: 11px; color: #6b7280;
          text-transform: uppercase; letter-spacing: 0.05em; }
.lp-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
           gap: 12px; }
.lp-card { background: #fff; border: 1px solid #e5e7eb; padding: 12px; }
.lp-card-header { display: flex; justify-content: space-between;
                  align-items: baseline; margin-bottom: 6px; }
.lp-deal-name { font-weight: 600; font-size: 15px; }
.lp-opportunity { font-family: "JetBrains Mono", monospace;
                   color: #10b981; font-weight: 600; }
.lp-badge { display: inline-block; padding: 1px 6px; border-radius: 3px;
            font-size: 10px; font-weight: 700; }
.lp-badge-critical { background: #fee2e2; color: #991b1b; }
.lp-badge-high { background: #fef3c7; color: #92400e; }
.lp-badge-medium { background: #fef3c7; color: #92400e; }
.lp-badge-low { background: #e5e7eb; color: #374151; }
.lp-risk { margin-top: 4px; font-size: 13px; }
.lp-q { margin-top: 6px; font-size: 12px; color: #374151;
         font-style: italic; }
.lp-audit { margin-top: 8px; font-size: 10px; color: #6b7280;
             font-family: monospace; }
"""
